### ISSUE TITLE
Donate banner, swap to say "Thank You"

### ISSUE THREAD

**Issue by harry-wood** [openstreetmap/openstreetmap-website#1001]
Could we swap the text of the donate banner to say a "Thank You" message

"Support OpenStreetMap"  ->   "Thank You"
"Bigger Servers for a Growing OpenStreetMap" -> "We hit our fundraising target!"
"Hardware Funding Drive 2015"  ...leave as is

CWG have been discussing this along with @zerebubuth  and @Firefishy and few others.  The plan is to "scale back" the banners, and then fairly soon (maybe another week) drop them all together.  Aiming for a short sharp positive fund raising period, and then stop and save our energy for next time.

I actually thought we'd already dropped the banner completely last week, but that was my cookies playing tricks on me.

**Comment by tomhughes** [comment]
Well the question is, if we change it do we also show it to everybody again? or only to those people that haven't already cancelled it (cf your cookies)?

**Comment by harry-wood** [comment]
hmmm. I guess there's a certain logic in showing it to people again yes. Might be a good memory jog for people who closed it the first time and forgot to donate. But if it's lots more hassle... no need to worry about it
