### ISSUE TITLE
Remember authorized OAuth applications for a user

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/openstreetmap-website#1002]
When you log in via OAuth from any of web services that support it, you need to press "Okay" button even if you did it a hundred times for a service. It does not matter if you have authorized an application to use your data, you'll need to do it again and again, as soon as that site cookies expire.

![sshot-oauth](https://cloud.githubusercontent.com/assets/766031/8557311/189425ea-2505-11e5-80a3-9d4854adb6a3.png)

Could somebody make a check, so that if you authorized an app to do something once, then the confirmation is automatic?

If not, it would be great not to have multiple similar lines in the list above.

**Comment by tomhughes** [comment]
As I explained on IRC yesterday that isn't how OAuth works. The idea is that you're supposed to keep hold of the token, not keep getting new ones. We can't start giving out the same token to multiple possibly unrelated requestors.

**Comment by tomhughes** [comment]
Oh sorry I think it was somebody else I was talking to about this yesterday!
