### ISSUE TITLE
drop the fund-raiser banner completely

### ISSUE THREAD

**Issue by harry-wood** [openstreetmap/openstreetmap-website#1003]
Following on from #1001, we can drop the fund-raiser banner completely now that we've said "Thank You" for a little while.

The standard donate site URL http://donate.openstreetmap.org is now back up and running. So this also coincides with that. Essentially we're all wrapped up with the 2015 fund raising drive now. I've just removed the banner at the top of the wiki pages.

**Comment by HolgerJeromin** [comment]
I would like to have the strings for the found-raising and "thank you" still in the code. 
The german found-raising translation was very buggy, but the timeframe was too short to correct (at least that was my reason for not fixing it). 
In the next years it would be better to have the year in the code and not the translation. So we do not have to wait for updating translation in all languages.

**Comment by tomhughes** [comment]
That assumes that the text will be the same next time, which seems unlikely.

**Comment by tomhughes** [comment]
I mean two of the key lines of text have already been removed anyway when we moved from the original banner to the thank you one...

**Comment by HolgerJeromin** [comment]
> That assumes that the text will be the same next time, which seems unlikely.

Ok, i have no experience with that. 

    Support OpenStreetMap 
    Bigger Servers for a 
    Growing OpenStreetMap

looked quite universal.

> I mean two of the key lines of text have already been removed anyway when we moved from the original banner to the thank you one...

That was the reason of this comment. right now it is easier to "save" the translation work. Next year it would be harder to fetch old translations.

**Comment by harry-wood** [comment]
Yeah the text might be fairly similar next year...  or it might not. I guess the whole translation workflow doesn't lend itself to jiggling around with banner messages at short notice.

I suggest we drop it as a translation text too for the moment (because that's the only tidy way to organise it really at this stage)  but next year we will at least try to plan some banner texts a bit further in advance (there's a few aspects of the donation drive we hope to plan further in advance)
