### ISSUE TITLE
Add an URL to this issue tracker to http://www.openstreetmap.org/help

### ISSUE THREAD

**Issue by krichter722** [openstreetmap/openstreetmap-website#1008]

**Comment by Nakaner** [comment]
I don't think that this issue tracker should to be linked from http://www.openstreetmap.org/help. This is an issue tracker regarding the website code. Bugs reported here are usually not reported by newbies.

**Comment by tomhughes** [comment]
Agreed - the help page is about helping people use OpenStreetMap not about the technology that drives it. Plus there's the whole "which bug tracker" issue that would have to be resolved first :-(
