### ISSUE TITLE
[security issue] E-mail address exposed

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/openstreetmap-website#1010]
It is possible to get the e-mail address of any user by visiting XXX.

The OSM user will be sent a confirmation mail and the page will show their email address.

**Comment by tomhughes** [comment]
<sarcasm>You've heard of responsible disclosure then?</sarcasm>

**Comment by tomhughes** [comment]
The site has now been taken offline until this issue can be addressed.

**Comment by M1dgard** [comment]
I'm so sorry, I should have left the URL out and waited for someone to contact me.

**Comment by tomhughes** [comment]
I have applied 9fdea1c7398618a99e5b553af2674db7f7326b23 temporarily and the site should be back up in a moment.
