### ISSUE TITLE
Member missing from relation in html output

### ISSUE THREAD

**Issue by vincentdephily** [openstreetmap/openstreetmap-website#1013]
The member 'Céide Fields' is missing from https://www.openstreetmap.org/relation/1555390 in the html output. It's here in the xml output and the editor. Perhaps the accented character it throwing the display off ?

**Comment by pnorman** [comment]
ID of the missing member?

**Comment by tomhughes** [comment]
Well I assume he means https://www.openstreetmap.org/way/361603931 as that is the only object by that name in the XML that the API returns.

The problem is that the web view also includes that way, contrary to the claim made.

Unless some more information is provided to explain what the claimed problem is I see nothing wrong here.

**Comment by vincentdephily** [comment]
Yes, it's [361603931](https://www.openstreetmap.org/way/361603931) I was talking about. Investigating further :

Firefox 38.1.0 Linux screenshot:
![ceidefields_firefox](https://cloud.githubusercontent.com/assets/115401/8823246/871bf31e-306b-11e5-9c76-ff0fbfa41cf5.png)

Chromium 43.0.2357.65 Linux screenshot:
![ceidefields_chromium](https://cloud.githubusercontent.com/assets/115401/8823244/8589e4fc-306b-11e5-99f2-27a093354744.png)

Note how chromium has the icon but not the text, and Firefox has the text but not the icon. Konqueror (both webkit and khtml) renders the same as Chromium. The html code looks fine to me and is pretty much the same for all members. I experimented forcing different charsets in Konqueror, but it doesn't change anything. So it look like a CSS issue, as that is the only thing left that varies between the entries.
