### ISSUE TITLE
Add more parameters for changeset#query API calls

### ISSUE THREAD

**Issue by ghost** [openstreetmap/openstreetmap-website#1016]
Say my application needs to get _only_ the oldest changeset of a given user. It would have to be able to specify parameters:
- maximum amount of returned changesets (currently API calls can take a long time because in the worst case 100 CSs are returned)
- order oldest to newest

So basically to be able to drop the `DESC` and to change the `100` in /app/controllers/changeset_controller.rb on line 222.

If there's another way to achieve this effect, please let me know.

**Comment by M1dgard** [comment]
Um yeah, I just realised this would change the API spec and that probably can't be done. An idea for 0.7 then

**Comment by tomhughes** [comment]
Seems like a very strange requirement, and I'm reluctant to try and turn the API into some sort of turing complete query language...

**Comment by M1dgard** [comment]
I'm making a platform to welcome Belgian OSM contributors and would like to find out the date of their first edit.

**Comment by M1dgard** [comment]
Currently we have a Google Sheet where the data is put by IFTTT from the feed of [resultmaps.neis-one.org](http://resultmaps.neis-one.org/newestosmcountryfeed.php?c=Belgium) but it's a bit cumbersome. NeisOne seems to have his own database with all changesets for making all those pretty statistics, but for my application that would be a complete overkill.

**Comment by pnorman** [comment]
> Say my application needs to get *only* the oldest changeset of a given user. It would have to be able to specify parameters:

What's the usecase in **editing**? I realize there are non-editing uses.

**Comment by M1dgard** [comment]
I suppose there are none.

So I can't use the API? Should I keep my own DB dump?

**Comment by woodpeck** [comment]
There are ways in between the two. The user's numerical user ID will give you a hint at their signup date. You could find out "today's" current user ID and from today on watch the changeset replication at http://planet.openstreetmap.org/replication/changesets/, and keep a small database of "user IDs from whom I have seen at least one edit" - this way you will be able to tell whenever someone registered later than today makes their first edit.

**Comment by tomhughes** [comment]
Well you can get the signup date (not first edit date) from the user details call anyway.

**Comment by M1dgard** [comment]
It's more difficult to get the numerical ID if you've only got the display name, but I reckon there's no 'valid' use case for that either?

It would be very useful for me, my program could follow neis-one's RSS feed and get a list of new contributors in Belgium, complete with first edit date from there - way easier, but only display names are in the feed so now I can't get their image and changeset count if I can't do a lookup by display name.

**Comment by simonpoole** [comment]
I sense massive overkill. Belgium gets roughly as many new signups/period as CH does, and it is really absolutely no issue with manually processing them. Which we do via RSS -> e-mail and then simply send a canned message to the new ones every 2nd day, which includes a quick glance at any one which seems extraordinary. Pascal's RSS feed already includes display name, and a link to an edit in the first changeset (which is two clicks away from any new display name the user may have chosen since signup).

Now if we were talking about 100s per day I might understand things better.

**Comment by mmd-osm** [comment]
I'm going to close this one. Original reporter's account has been deleted in the meantime, requirement unclear / overkill.

**Comment by AntonKhorev** [comment]
> Say my application needs to get only the oldest changeset of a given user.

This is actually implemented with the `limit=1` parameter.
