### ISSUE TITLE
Refactoring has broken Callback URL which used to allow custom URL schemes

### ISSUE THREAD

**Issue by jamba-ca** [openstreetmap/openstreetmap-website#1019]
It looks [this refactoring](https://github.com/openstreetmap/openstreetmap-website/commit/dbe165bbb3d6eda37d9579f1ac767599f9055607#diff-3ef1e2237f323b7d4dc1ce1fc11a5c20R13) has broken what used to be a very useful feature: Allowing the submission of a Callback URL with a custom URL scheme (e.g., myapp://somewhere) when creating an app. It's now back to limiting Callback URLs to http/https.

**Comment by mendhak** [comment]
Thanks @tomhughes, it's appreciated!
