### ISSUE TITLE
Add layer for proposed objects

### ISSUE THREAD

**Issue by rmikke** [openstreetmap/openstreetmap-website#1022]
While it's good that proposed ways are not rendered by default, it would be even better if they could be visible on demand. It's good to know, what is planned and OSM should make it possible, especially when someone has already put some work copying all the data from some project documentation. For me, only the proposed ways on OSM show all the projects in Poland in one place and it's much easier to get an overview from OSM than from official documentation, which is hard to come by.

The solution would be creating additional layer in mapnik, that would be visible on demand, like notes are now. By default it would be switched off.

**Comment by HolgerJeromin** [comment]
Someone has to create and maintain such a layer. Than i do not think there would be a huge problem to add it to the website...

**Comment by tomhughes** [comment]
Indeed - the creation of new rendering is not a matter for this bug tracker. If such a layer is created then the wiki describes the procedure for requesting it to be added to the site.

**Comment by Firefishy** [comment]
Here is the criteria for adding a new layer: http://wiki.openstreetmap.org/wiki/Featured_tiles
