### ISSUE TITLE
GPX import failing because <time> missing

### ISSUE THREAD

**Issue by bagage** [openstreetmap/openstreetmap-website#1023]
I know that this is probably a wrong place to report this issue, but I am not sure where it should stand. 
When uploading a GPX trace on openstreemap.org without `<time>` field in any `<trkpt>` attributes [(for instance this one)](http://h2096617.stratoserver.net:443/brouter?lonlats=4.277802,49.201224|4.31385,49.197859&nogos=&profile=trekking&alternativeidx=0&format=gpx), import will fail with following error:

> Found no good GPX points in the input data. At least 75% of the trackpoints lacked a <time> tag.

However it seems to me that there is no good reason for such a limitation: this attribute is not mandatory at all in [GPX format specification](http://www.topografix.com/GPX/1/1/gpx.xsd) and should not be used by openstreetmap(?):

```XML
<xsd:element name="time" type="xsd:dateTime" minOccurs="0">
<xsd:annotation><xsd:documentation>
Creation/modification timestamp for element. Date and time in are in Univeral Coordinated Time (UTC), not local time! Conforms to ISO 8601 specification for date/time representation. Fractional seconds are allowed for millisecond timing in tracklogs. 
</xsd:documentation></xsd:annotation></xsd:element>
```
  I can see that [ericfischer's fork](https://github.com/ericfischer/gpx-import) did actually remove this in commit [c9eb2d4836ac](https://github.com/ericfischer/gpx-import/commit/c9eb2d4836ac77c233141722253f51636c9f6267) but it seems that his version was never merged with [the official one used by openstreetmap.org](https://git.openstreetmap.org/gpx-import.git/)? 

Even if his fork is not mergeable, could the `<time>` check be removed? If not, what is the reason behind it?

Again, sorry for misplacing my issue!

**Comment by gravitystorm** [comment]
This is a longstanding requirement from the API, and it's unlikely that we'll change it. 

http://help.openstreetmap.org/questions/2130/gpx-file-no-time-tag/2146 has good background details on why this is the case. As one of the comments says, if you don't want to keep the timestamps in your GPX file, for privacy or other reasons, don't upload it to OpenStreetMap.

**Comment by bagage** [comment]
Thanks, indeed the fact that:

> "The reason it's required is that it reduces the temptation for individuals to upload data in the GPX format that has not been gathered by a GPS. Of course that's not foolproof and it's not intended to be." (Andy Robinson from the mailing-list)

Is a very good reason for this choice. I am totally fine with this actually but wanted to know what reason was behind this choice. Thanks.
