### ISSUE TITLE
database glitch resulting in valid element not displayed on the map

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#1024]
>this perfectly good road is not rendered for some reason: https://www.openstreetmap.org/way/141673809

![mosvorota](https://cloud.githubusercontent.com/assets/766031/9073842/03837a3e-3b0d-11e5-8ef0-4c21510081de.png)

Rendering of this place - data from Overpass, local render with openstretmap-carto style shows no glitches.

![https___www openstreetmap org_way_141673809 map 19_59 89218_30 31941 master-_master 19 19 350px master - master 350px](https://cloud.githubusercontent.com/assets/899988/9074423/d464bfcc-3b09-11e5-92b3-3eae960b68a9.png)

Please, do not edit this element to force data refresh - maybe it is something fixable (previous cases involved obnoxiously complicated multipolygons). Editing it may make harder to investigate what went wrong.

Originally reported on https://github.com/gravitystorm/openstreetmap-carto/issues/1722

**Comment by matkoniecz** [comment]
Database serving data to render of Humanitarian style has a similar glitch in the same area.
 
![selection_001](https://cloud.githubusercontent.com/assets/899988/9074452/1a97bf6c-3b0a-11e5-8679-8013bb1559ed.png)

**Comment by Zverik** [comment]
They say in Russian forum that this is a osm2pgsql bug: when all ways have tags that a multipolygon on them has, these ways drop that tag.

**Comment by lonvia** [comment]
Looks like another instance of https://github.com/openstreetmap/osm2pgsql/issues/304 Definitely not a website/API bug.

**Comment by tomhughes** [comment]
Invalid - this tracker is for bugs in this repository.
