### ISSUE TITLE
Untranslated button

### ISSUE THREAD

**Issue by BathoryPeter** [openstreetmap/openstreetmap-website#1025]
OAuth "Save changes" button has only some default value:
https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/oauth/authorize.html.erb#L18
Please add it to translatable strings.

**Comment by HolgerJeromin** [comment]
Or reuse the translation from the diary code:
`<%= submit_tag t('diary_entry.edit.save_button') %>`
