### ISSUE TITLE
"Where am I" link in the search field obscures search query

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/openstreetmap-website#1026]
1. Enter "55.748234234234 38.127423423424" (or any other long query) in the search field.
2. Start a search and click on any nominatim result.
3. Click "back" in the browser.

On step 3 (in Safari) or on step 2 (in Firefox) "Where am I" link appears, that obscures a part of the search query.

**Comment by tomhughes** [comment]
Fixed by #1085
