### ISSUE TITLE
Location of New Note marker: OK to centre it?

### ISSUE THREAD

**Issue by danstowell** [openstreetmap/openstreetmap-website#1028]
Discussing this with @zerebubuth while trying to work out programmatic interaction with Note creation:

The change added in commit 40b3c828e7289cc3e3566375450ee378c8229bc4 (3 Feb 2013), "Avoid making the map scroll when adding a new note". We suspect this might relate the the older "bubble" rather than "sidebar" text entry. It might be OK to simply use the map centre now.

The code is currently here:
https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/javascripts/index/new_note.js#L111

If anyone has insight please let me know otherwise I'll check it tomorrow, and might propose simplifying it back to centreing? At present (on these laptop screens) the New Note pointer is off-centre for no obvious reason.

**Comment by tomhughes** [comment]
I suspect you're right, assuming that y counts from zero at the top at any rate.

**Comment by danstowell** [comment]
Thanks. Closing this since I've opened PR #1029
