### ISSUE TITLE
Flagging inappropriate 'notes' for moderators to deal with

### ISSUE THREAD

**Issue by rickmastfan67** [openstreetmap/openstreetmap-website#1031]
I just came across a new note that was posted today (08/12/15) that is completely inappropriate.  It seems it's a personal attack by an anonymous person on another person who lives at a specific address.

Unfortunately, I don't want to 'close' it and have it linked to my user OSM account. (I will not post the direct link to it here, but it's Note 412850.)  This is where a report/flag feature would come in handy big time for an inappropriate note so that mods could be alerted to it and either hide it or delete it.

It could be as simple as a text button with the word 'report' in it.  And on the backend, would simply send out an email to the OSM mods.  However, I would assume you'd want the reporter to add some text as to why it is being reported to help weed out 'false' reports.  This 'report' feature would be available only to people logged into the OSM website of course.

Now, if I could code, I'd help out here and try to do it myself.  However, I couldn't code my way out of a paper box to be honest.  So, I'd thought I'd at least post an issue on this subject.

I would assume this could go hand-in-hand with what @SomeoneElseOSM wants in #975 & #921.

**Comment by woodpeck** [comment]
Offensive notes should be flagged to data@osmfoundation.org where they can be hidden (what I did with the offensive note just now). A "report" feature for notes is in the works. I will leave this ticket open so that it may be closed when that feature is rolled out.

**Comment by rickmastfan67** [comment]
The downside is it now shows up on your account in the notes, which is what #921 complains about. :(

**Comment by woodpeck** [comment]
Yep - but better there than on the map

**Comment by rickmastfan67** [comment]
Very true!

**Comment by HolgerJeromin** [comment]
I (normal osm account) am able to reactivate this hidden note. At least the GUI shows me the button. Is this intentional? Or should i open another issue?

**Comment by tomhughes** [comment]
@HolgerJeromin you shouldn't even be able to see it (modulo the bug in #921) or is that what you mean? In any case you shouldn't even have an unhide button!

**Comment by HolgerJeromin** [comment]
I guessed the URL and got this (pink anonymization from me):
![github1031](https://cloud.githubusercontent.com/assets/2410353/9229770/0ea0e060-411f-11e5-8931-470fce64061d.png)

**Comment by tomhughes** [comment]
Yes, that's a bug that I just fixed in caa1a0128a057bf7358cf60926e0c243113b5a50.

**Comment by HolgerJeromin** [comment]
Thanks for fixing this. Right now the german text has the incomplete sentence:

"**mit der Nummer 412850 konnte leider nicht gefunden werden.**"

from de.yaml i see the language template is
`sorry: '%{type} mit der Nummer %{id} konnte leider nicht gefunden werden.'`
so the `type` is missing in the error output. 
Probably not related to your fix, but another older problem.

**Comment by gravitystorm** [comment]
Refs #1576

**Comment by SomeoneElseOSM** [comment]
Now that the "Report this note" link is live, I think that this can be closed?

**Comment by tomhughes** [comment]
True.
