### ISSUE TITLE
EFF Privacy Badger complains about openstreetmap.org cookies (being used by "3rd parties")

### ISSUE THREAD

**Issue by neiljp** [openstreetmap/openstreetmap-website#1032]
I assume these are the cookies set by the domain and maybe www. subdomain, and then used by other subdomains (rather than other websites), which PB then sees as 'suspicious'. So far I've not noticed what the blocking does, and what the issue really is (it doesn't seem to provide that information), but I'm posting this here in the hope that someone more knowledgeable will have an idea!

**Comment by danstowell** [comment]
Thanks for the report. FYI on their FAQ it says "If you find domains that are under- or over-blocked, please [file a bug](https://github.com/EFForg/privacybadgerchrome/issues) on Github." The question we need to resolve is whether our cookies do anything that really should raise an eyebrow - if not, we simply close this bug and tell you to go over to *their* issue tracker instead ;)

I previously added OSM's tileservers (and HOT's tileservers too) to the official Privacy Badger whitelist.

OSM provides OpenID access to third-party sites such as http://tasks.hotosm.org and so PB may be reacting to that. I don't know if they'd be happy to whitelist it or not, I haven't asked.

To be clear: the tiles and the auth are things that we, to some extent, allow to be used across other sites, and so they're often indistinguishable from tracking cookies or tracking pixels, from the point of view of PB. For the EFF, it's just a question of whether we're trustworthy in our use of them.

**Comment by danstowell** [comment]
Ah, a correction to my reply: I think adding things to the "yellowlist" makes sense for tileservers (as I have previously done) because the PB will then block cookies but allow content. This doesn't help with the cookie issue.

Quoting from the [PB FAQ](https://www.eff.org/privacybadger): "You can [get cookies working again for your site] by posting a specific compliant [DNT policy](https://www.eff.org/dnt-policy) to the URL https://example.com/.well-known/dnt-policy.txt, where "example.com" is all of your DNT-compliant domains." Since OSM is probably compliant with EFF's boilerplate DNT policy, I guess what is needed is for the Data Working Group to confirm that, and then we can simply place that text in the appropriate place.

(Happy to be corrected again, if needed...)

**Comment by tomhughes** [comment]
I see nothing actionable here - if you find an actual problem that you can describe then please open a ticket doing so.

If EFF want us to change something they need to tell us what, not just issue vague innuendos.

**Comment by tomhughes** [comment]
For the record the tile server make no use of any cookies, and as far as I know we don't attempt to expose any cookies to them from anywhere else. They wouldn't use them even if we did!

**Comment by danstowell** [comment]
Tom it is actionable. I will write to the DWG and see how they feel about the EFF's required text. If they believe it is appropriate, then we will put the DNT text on our server - easy fix.

**Comment by tomhughes** [comment]
The only cookies I see on www.openstreetmap.org have that as the domain and are therefore not visible to any third parties.

**Comment by tomhughes** [comment]
@danstowell How many people exactly are we going to allow to start demanding that we post special files?

**Comment by tomhughes** [comment]
I mean seriously this DNT thing is like one week old. I think we should see if it takes off before we start pandering to it.

**Comment by pnorman** [comment]
> I guess what is needed is for the Data Working Group to confirm that, and then we can simply place that text in the appropriate place.

The Data Working Group deals with issues with OpenStreetMap data and has nothing to do with website development, cookies, or privacy policies.

**Comment by tomhughes** [comment]
I assume he meant LWG but in any case I don't see any way we are, or can ever be, compliant with 1(a) in that policy, would not like to guarantee compliance with 2(a) and am not sure how the hell 4 is supposed to work.

**Comment by danstowell** [comment]
@tomhughes I understand. Also, sorry for my misleading first comment. However I think you're closing the topic down very presumptively. I'd better shut up because I've even got confused about the flipping Working Groups so I'm not adding light to the situation.

**Comment by tomhughes** [comment]
I mean on the face of it 1(a) means we can't record what user created a changeset or uploaded a GPX track if they have DNT enabled.

**Comment by neiljp** [comment]
As a data point, when not logged in it indicates that the tileservers are 'potential trackers', and when logged in it also lists:
- i0.wp.com
- www.gravatar.com
- secure.gravatar.com
These are all just 'yellow'.

FYI, the issue title is possibly incorrect as I suspect the tileservers are identified in that way due to the indexing through different tiles, or something similar. They're a solved situation anyhow, according to @danstowell.

I only noticed as one can look at a list of domains accessed and how they are being treated by PB, and openstreetmap.org was 'red'. I've just gone through a number of osm-related sites and found that achavi appears to be using www.openstreetmap.org, and that is blocked at the moment via PB; I haven't looked at all other osm-related sites, just the ones I could think of offhand.

While the stable release of PB is new, I posted this so that I could find out what the situation is, and if possible that OSM could be proactive in this context. I'm not expecting instant action, but equally it seemed a reasonable question. While LWG may have other pressing matters, if @danstowell wishes to enquire on this matter, I feel it would be positive to clarify this.

**Comment by tomhughes** [comment]
I'm not sure where i0.wp.com is coming from as I see no references to that in our network traffic or the cookies reported by my browser.

As far as I can see gravatar is not issuing any cookies and has no access to our cookies as they are issued against www.openstreetmap.org.

**Comment by neiljp** [comment]
As per my last comment, it may not (just) be cookies that are analysed by the tool, as per https://www.eff.org/privacybadger

I believe it tries to identify trackers based on looking for elements loaded from different sites that could be user-identifying, hence presumably the tile servers, or how they are accesed - there is more that the link above.

Re i0.wp.com, I guessed that the diaries might be implemented via WP, but... I don't know the code.

**Comment by neiljp** [comment]
The i0.wp.com request is for an image that (at least here) sits next to the number of unread messages and username in the top-right box, ie. a call to:
http://i0.wp.com/www.openstreetmap.org/assets/users/images/large-d0aba9dcb4610f25419f897e588cf907.png

The secure.gravatar.com image seemingly redirects to the above image:
https://secure.gravatar.com/avatar/fc091913de5b882e7268c0d638a611bd.jpg?s=25&d=http%3A%2F%2Fwww.openstreetmap.org%2Fassets%2Fusers%2Fimages%2Flarge-d0aba9dcb4610f25419f897e588cf907.png

I guess it is the long numeric url which may be suggesting that there is a problem, in each case, which appears like it could be a unique id to the user. I'm not sure exactly how it is determining these things, but at least that explains where the urls come from.

**Comment by tomhughes** [comment]
Yes I realised later last night that the i0.wp.com was probably gravatar related, as gravatar is part of wordpress. The long number is just the hash of the email address, precisely so that the email address doesn't have to be revealed to gravatar.

**Comment by danstowell** [comment]
OK, right. The main thing that is happening here is NOT that PB is acting suspicious about long URLs. Instead, it detects when resources get used across multiple sites. Gravatar is a classic case, since of course it's been designed to be used across multiple sites. So for you @neiljp what it means is that PB has detected that there is more than one website that YOU visit, that invokes the same Gravatar URLs.

In theory Gravatar could be doing evil tracking of users, simply based on the fact that it knows who is requesting its URLs. So the way to solve the PB warnings for Gravatar is to get Gravatar to follow EFF's policies. That's not an issue for OSM.

If I go to the "User diaries" page I see lots of PB warnings. However none of them are about resources loaded from OSM servers. I don't know if there's any reason for us to be concerned about those "foreign" resources re tracking.

**Comment by tomhughes** [comment]
I'm guessing on the diaries that is where people have embedded images.

**Comment by tomhughes** [comment]
Which by the way is another reason why we couldn't post dnt-policy, because we have no idea what third party sites people might reference via diary images, and hence point 3 would be impossible to achieve.

**Comment by M1dgard** [comment]
> hence point 3 would be impossible to achieve.

Not technically impossible, if we were to let a server retrieve the image and serve it ourselves. But I reckon that's not going to happen.
