### ISSUE TITLE
HTTP map tiles on HTTPS page

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/openstreetmap-website#1033]
Due to mixed content blocking, the cycle, transport and humanitarian style are blank when visiting https://openstreetmap.org.

Cycle and transport support HTTPS, humanitarian's certificate is untrusted.

When on an HTTPS site, at least cycle and transport can already use HTTPS.

**Comment by tomhughes** [comment]
Those tile providers do not support https, so we have no choice. When they do we will happily use https with them.

**Comment by tomhughes** [comment]
Hmm I see you claim that some of them do - that certainly didn't use to be the case I'm sure, or we would have added them.

What's the story with your layers @gravitystorm? Are we OK to use https?

**Comment by tomhughes** [comment]
Incidentally, images are "passive" mixed content and are not normally blocked. What browser are you using that blocks passive mixed content?

**Comment by gravitystorm** [comment]
I'm happy for you to use https for the Transport and OpenCycleMap layers

**Comment by M1dgard** [comment]
@tomhughes Pale Moon. And I know it's mixed content blocking because in the console errors like 'Blocked loading mixed display content "http://a.tile.thunderforest.com/cycle/13/4166/2731.png"' appear.
Thanks for looking into it.

**Comment by tomhughes** [comment]
I've opened https://github.com/jfirebaugh/leaflet-osm/pull/8 as the first step...

**Comment by tomhughes** [comment]
Thunderforest layers have been fixed in 6f5acd26e8b05a77d415420fc4e2309b2e659a09.

**Comment by tomhughes** [comment]
Humanitarian layer was fixed in 0d2e1608ba7aba12f173c526be8813a2a4b99095 so all layers should be fixed now.
