### ISSUE TITLE
OSRM routing directions displayed in English regardless of 'ru' setting in user profile or HTTP Accept-Language

### ISSUE THREAD

**Issue by d1g** [openstreetmap/openstreetmap-website#1047]
Client-side issue but I'm not sure if this is right place to report this bug. 

Case 1 (en user, ok):
1. open account settings (current route /user/xxx/account, user-agnostic route here would be more useful btw)
2. set 'Preferred Languages' to 'en' 
3. open http://www.openstreetmap.org/directions?engine=osrm_car&route=48.85715%2C2.33652%3B48.85652%2C2.33818
4. "Directions" is in English. "Turn left onto" is also in English

Case 2 (fr user, ok):
1. same
2. set 'Langues préférées' to 'fr' 
3. same 
4. "Itinéraire" is in French. "Tourner à gauche sur" is also in French

Case 3 (ru user, bug):
1. same
2. set 'Предпочитаемые языки:' to 'ru'
3. same
4. "Маршрут" is in Russian. "Turn left onto" is in English (!), expected: "Примите влево на"

[Link to OSRM query](http://map.project-osrm.org/?hl=en&loc=48.857151,2.336513&loc=48.856598,2.338113&z=17&center=48.855980,2.337395&alt=0&df=0&re=0&ly=-1171809665).

**Comment by d1g** [comment]
Also, setting preferred languages to 'RU' and 'ru_RU' results in 'en' page ('Directions', but not 'Маршрут'). Probably we want less error-prone input field for 'preferred languages' (multiselect)

**Comment by tomhughes** [comment]
Well do translations actually exist for those strings? If they don't we will fall back to english...

**Comment by tomhughes** [comment]
As I suspected there is no translation present for that string in our Russian locale.

See http://wiki.openstreetmap.org/wiki/Website_Internationalization#How_to_translate for more information on how to help out with translation.

Language matching follows normal HTTP rules, and there shouldn't normally be any need to edit that field at all as we capture it from the browser when you sign up.

**Comment by d1g** [comment]
> no translation present for that string in our Russian locale.

@tomhughes, well but http://map.project-osrm.org/ was translated in Russian (and [25 languages in total](https://github.com/Project-OSRM/osrm-frontend/tree/3a764f01da2234c7e2e6cee6551dbe7b1640ec44/WebContent/localization)). Wouldn't it be better to *reuse strings* from project-osrm?

> Well do translations actually exist for those strings?
> no translation present for that string in our Russian locale.

Do you mean in source code or translation platform? 
["Turn left onto" was translated 7 days ago](https://translatewiki.net/w/i.php?title=Osm:Javascripts.directions.instructions.turn_left_without_exit/ru&action=history) - how should I know if it is included in current version of website or not?

**Comment by tomhughes** [comment]
No, it can take a few weeks before translations are pushed back to openstreetmap and there hasn't been a sync for a about a month now, probably because people have been away over the summer.

**Comment by d1g** [comment]
> and there hasn't been a sync for a about a month now, probably because people have been away over the summer

@tomhughes, does it mean that you are not the person responsible for this and we cannot update strings sooner? Is there anything we can do about it?

**Comment by tomhughes** [comment]
No, the TranslateWiki folks push the changes from their end.

**Comment by d1g** [comment]
@tomhughes, thanks for info! Probably it should be stated at http://wiki.openstreetmap.org/wiki/Website_Internationalization#How_to_translate
