### ISSUE TITLE
bundle install error

### ISSUE THREAD

**Issue by chantalokh** [openstreetmap/openstreetmap-website#1048]
hello everyone,
I have the following error while executing bundle install:

Installing nokogumbo 1.4.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
 /users2/osm00/bin/ruby-2.2.3/bin/ruby -r ./siteconf20150831-13603-1sq5g1v.rb extconf.rb
checking for xmlNewDoc() in -lxml2... yes
checking for nokogiri.h in /users2/osm00/bin/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2/ext/nokogiri... no
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
checking for gzdopen() in -lz... yes
checking for iconv... yes
.....
ERROR: getaddrinfo: Name or service not known
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

i dont know why he isent finding  nokogiri.h in /users2/osm00/bin/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2/ext/nokogiri, the file exists!!!
have you any idea??
thanks

**Comment by tomhughes** [comment]
Why would I have any idea about a problem installing a third party module? You need to ask the authors of that module why you can't install it.

But before you do that do what it says and read mkmf.log and mostly likely you will find that you are just missing some dependency.
