### ISSUE TITLE
Trouble with OSM OAuth on localhost

### ISSUE THREAD

**Issue by TheFive** [openstreetmap/openstreetmap-website#1049]
Using oauth in my development environment results in 

----------------------
Application error

The OpenStreetMap server encountered an unexpected condition that prevented it from fulfilling the request (HTTP 500)

Feel free to contact the OpenStreetMap community if your problem persists. Make a note of the exact URL / post data of your request.

This may be a problem in our Ruby On Rails code. 500 occurs with exceptions thrown outside of an action (like in Dispatcher setups or broken Ruby code)

-----------------------

If i run my app on thefive.sabic.uberspace.de/osmbc i am fine and i can log in. So my App and my OSM Account should work.
If i run my app in my local test environment localhost:3000/osmbc i got the error.

I tried deleting all cookies (server and client side), change the browser from chrome to safari and create a new OAuth app with a new secret. The problem is still the same.

This behavior occurs since yesterday, before that i had no problem with the OAuth mechanism.

Christoph

**Comment by tomhughes** [comment]
Nothing has changed at our end. This is almost always the result of sending requests with an invalid signature (the 500 error is a bug in an upstream library that we use).
