### ISSUE TITLE
No such file or directory - config/countries.xml

### ISSUE THREAD

**Issue by sacemsacem** [openstreetmap/openstreetmap-website#1059]
When i try to start the rails server as daemon,

bundle exec script/rails server -d

Seems that the rails cannot locate the file correctly. User got the following error from browser:

No such file or directory - config/countries.xml

However, there are no issues if I start the rails not in daemon mode.

Please help.

**Comment by tomhughes** [comment]
Sorry, that's not a way I ever run it so I have nothing to offer.
