### ISSUE TITLE
Suggestion: humanitarian as standard map layer

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/openstreetmap-website#1063]
I'm wondering if the current standard map layer couldn't be replaced by the humanitarian layer (or by a combination of humanitarian and MapQuest Open). In my opinion, the humanitarian layout has a clearer layout (e.g., streets and symbols are not overemphasised) and the colours are softer and fit better together. All in all, it looks nicer and more professional.

The town centre of Bern as shown with the humanitarian layer:
![e4b70400-669e-11e5-9a18-00bafe2f8372](https://cloud.githubusercontent.com/assets/14875493/10163388/eaed92d0-66b2-11e5-8601-00036339ae0c.png)

The same place with the standard layer:
![e7306654-669e-11e5-93a8-da457aebfad1](https://cloud.githubusercontent.com/assets/14875493/10163391/f1a1f62a-66b2-11e5-96d0-2a60e4974711.png)

**Comment by tomhughes** [comment]
No, it can't, because the server that runs the humanitarian layer couldn't possibly stand the strain.

It's the wrong solution anyway - if there are problems with our rendering then we should address them, not just switch to a third party layer.

If you want to help with that then https://github.com/gravitystorm/openstreetmap-carto is where the in-house style is developed.

**Comment by SelfishSeahorse** [comment]
Hey! That's a pity ... I've posted on [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto/issues/1882) first, but they referred me here. :smiley: Actually, the default layer isn't wrong or broken, but perhaps OpenStreetMap and its users would profit from a cleaner, nicer default map design.

**Comment by tomhughes** [comment]
Well it might, but the way to achieve that is to make our style cleaner and nicer not to switch to a new one.

**Comment by polarbearing** [comment]
@SelfishSeahorse - the road style is currently overhauled in carto anyway, have a look [here](https://github.com/gravitystorm/openstreetmap-carto/pull/1736), probably read the thread from the bottom, there are links to the demonstration as well.
