### ISSUE TITLE
add details in description meta tag; and add og:description and twitter:description

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/openstreetmap-website#1066]
Adding more detail in the description meta-tag, and adding additional meta-tag, is an easy way to improve sharing of OSM links. For instance, a link to an OSM feature can include the name and type of feature in the description meta-tags.

Related to https://github.com/openstreetmap/openstreetmap-website/issues/739, which specs out possibilities and issues for addition of map image during sharing.

**Comment by tomhughes** [comment]
Why can't all these damned sites agree on one standard? How many of these tags are we going to be expected to add? How big does a site have to be before it becomes impossible for us to tell them to go take a long walk off a short pier when they come up with this nonsense...

**Comment by mikelmaron** [comment]
Yea, turns out they've kinda agreed. I think supporting the Open Graph standard should be enough.

http://stackoverflow.com/a/29067915

**Comment by woodpeck** [comment]
Does that mean we can kick out the tags "contact:facebook", "facebook", "contact:google_plus", "contact_twitter", "twitter", etc.?

**Comment by HolgerJeromin** [comment]
@woodpeck This is only about the HTML meta data for osm.org website, for sharing an URL.

**Comment by mikelmaron** [comment]
For reference, here is where the meta-tags are added. 

https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/layouts/_head.html.erb#L28-L29

Not clear to me if both description and og:description metatags are necessary to cover everywhere we want better descriptions. Certainly for title, I think it just pulls from the title tag, doesn't require og:title.

In either case, need to set up the value of this/these metatags to https://github.com/openstreetmap/openstreetmap-website/blob/c9d35839befe92d916425baa4daec7dd77ade929/app/helpers/browse_helper.rb#L4 or something more expansive (including the type of feature)

**Comment by tomhughes** [comment]
The big problem I see is that we will have no idea what language to use for the description because what twitter/facebook/whatever fetches the page they won't be logged in, or presumably sending any Accept-Language header so we will just default to english.

In any case in the first instance I was assuming we would just do a simple fixed description, not try and generate something custom for each different page.

**Comment by mikelmaron** [comment]
Yea, and there's no way to add alternate languages to og. So keep it simple, and set description to printable_name, and force to use the English text and the default "name" tag

**Comment by pnorman** [comment]
`og:image` is a required property. Given we don't have a way to generate an image specific to the graph object, for the same reasons as #739, what could we do here?

There is the `og:locale` property, so we can do `<meta property="og:locale" content="en_GB" />` It also allows for `og:locale:alternate`, to specify alternate locales which are available, but doesn't talk about how to retrieve those alternate locales.

https://developers.facebook.com/docs/opengraph/guides/internationalization#bestpractices discusses OG localization in the context of Facebook, and a `X-Facebook-Locale` header is used.

> and add og:description and twitter:description

I can't find a reference to `twitter:description` on the twitter graph docs - could you provide a link to documentation?
-----

@mikelmaron Could you provide what you think the open graph properties would be for a few example objects?

**Comment by mikelmaron** [comment]
After looking into it more, the only addition needed now is `og:title`, set to the same as `title`; some sites, like Slack, only pay attention to the OG tags. 

Facebook uses `title` if `og:title` is not set, so ok there. Could consider adding support for `X-Facebook-Locale` as @pnorman suggests, later on.

So in summary, I think adding `og:title` set to `printable_name` should be sufficient to close out this issue.

**Comment by pnorman** [comment]
> After looking into it more, the only addition needed now is og:title,

What about `og:image` being required?

**Comment by mikelmaron** [comment]
> What about og:image being required?

Agree that it would be great to do more with `og:image` than serve the logo, but that should be sufficient for now, and doesn't need to change.

Also, "required" in practice isn't enforced. There are four required OG tags, but right now OSM just has the one.

**Comment by HolgerJeromin** [comment]
Can this be closed after https://github.com/openstreetmap/openstreetmap-website/commit/e62e879b3bb70bb93fe96d3cc669f219cd23ed8d ?

**Comment by tomhughes** [comment]
Well that depends - this ticket is sufficiently vague that it's hard to know what will count as it being completely fixed.

In particular this specifically asked for `description` which we are not currently adding.

My plan was to extend things to allow further page specific customisation and then, within reason, allow people to offer patches to make pages add more specific details.

**Comment by mikelmaron** [comment]
We whittled down the requirement in the comments. Thanks @tomhughes. Closing
