### ISSUE TITLE
Deleted user: "check spelling , or [wrong link]"

### ISSUE THREAD

**Issue by malenki** [openstreetmap/openstreetmap-website#1069]
When browsing the creator of an object on OSM whose account  got deleted the message is displayed
"Please check your spelling, or maybe the link you clicked is wrong".  Both is wrong when following a link displayed at osm.org.¹
It would be better to 
a) add a general info like "or the account doesn't exist anymore"
or 
b) add a specific info for deleted users "This account previously belonging to user XY got deleted"

Maybe #579 is also related.

¹ Example: [Changeset](https://www.openstreetmap.org/changeset/18198251) from a user who seemingly doesn't exist anymore. Click on "user_1418319" to see the message mentioned above.

**Comment by sonalkr132** [comment]
I think this is fixed now and can be closed. Check: https://www.openstreetmap.org/user/user_1418319

**Comment by tomhughes** [comment]
I still see the exact same message @malenki refers to.

**Comment by sonalkr132** [comment]
> **The user user_1418319 does not exist**
Sorry, there is no user with the name user_1418319. *Please check your spelling, or maybe the link you clicked is wrong.*

Aggh! I only looked at bold line. :disappointed:

I will have a look into this.

**Comment by mmd-osm** [comment]
Issue has been fixed in the meantime.
![image](https://github.com/openstreetmap/openstreetmap-website/assets/5842757/baa47cf2-8185-4db8-a935-c039ca477f54)
