### ISSUE TITLE
osmosis import : duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by adam21** [openstreetmap/openstreetmap-website#1071]
Hello everyone,

I had successfully installed openstreetmap-website on Ubuntu 14.04.
Now I'am trying to import a pbf file into the "openstreetmap" database using the following command:

```
osmosis --read-pbf /home/osm-data/my_citie.osm.pbf   --write-apidb host="localhost" database="openstreetmap"   user="postgres" password="*********" validateSchemaVersion="no"
```
but I still get this error:

```
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "current_nodes_pkey1"
```

Note: Osmosis Version is 0.40.1
I installed it with "sudo apt-get install osmosis"
PBF file downloded from Mapzen Metro Extracts

Someone has already encountered this problem?
Thank you for your help

**Comment by tomhughes** [comment]
This has nothing to do with the web site code.

**Comment by stephan75** [comment]
In case of not having found by yourself:

See https://trac.openstreetmap.org/query?component=osmosis

**Comment by tomhughes** [comment]
Most likely the problem is either that there is existing data in the database with overlapping node IDs or there is duplicate data in that extract. Either that or it's a bug in osmosis. It certainly isn't a bug in the web site code though.

**Comment by adam21** [comment]
Thank you for your help, The problem was solved,  but I still do not understand the issue :
I have installed the latest version of osmosis (0.44.1) and used a ".bz2" osm file witch I downloaded from geofabrik, now the import goes without any error.

**Comment by pengrui2009** [comment]
@adam21 I hava the same problem with you,could you give some ideal?

**Comment by zerebubuth** [comment]
Here are some tips for trying to fix the duplicate key issue. There might be more answers relevant to this on [help.openstreetmap.org](https://help.openstreetmap.org), and it's worth asking follow-up questions there in case someone in the community has already figured it out.

* The first thing to check is whether the input file has duplicate nodes. If it is a ["history"](https://wiki.openstreetmap.org/wiki/Planet.osm/full) file, then it is *not* suitable for loading with Osmosis' `--write-apidb` command. If it is a "normal" non-history file, it is possible that the file itself is broken. If you can get the same extract from somewhere else, then it might be worth trying that.
* It has happened to me that I've tried to import into a database which I thought was empty, but actually contained data (in my case, from a previous failed run). It's worth checking that the database is truly empty of all fixtures, test data, previous runs, and so forth, before starting the import. If in doubt, drop and re-create the database. I don't use Rails itself to do this, as I don't trust it not to put in data that I don't know about; I just load the `db/structure.sql` file directly. This might be me cargo-culting, I'm not sure :wink:
* Adding data to an existing database [is not supported](https://help.openstreetmap.org/questions/51995/duplicate-key-value-violates-unique-constraint-relations_pkey) by `--write-apidb`. If you do want to add data on top of existing data then you'll need to [derive a change](https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.46#--derive-change_.28--dc.29) between your two inputs and [add only the change](https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.46#--write-apidb-change_.28--wdc.29) to the database.
*  Finally, there is a complex method which can be used to clean the data, but I do not recommend it! It might cause more problems than it solves, but if you feel confident then give it a go. It's possible to remove duplicates by [deriving the change](https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.46#--derive-change_.28--dc.29) between [an empty input](https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.46#--read-empty_.28--rem.29) and your file, then [simplifying the change](https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.46#--simplify-change_.28--simc.29) and [applying the change](https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.46#--apply-change_.28--ac.29) to [an empty input](https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.46#--read-empty_.28--rem.29).

**Comment by pengrui2009** [comment]
@zerebubuth Thank you for your tips.I think I have find the reason that it was caused by the bug on Osmosis Version 0.40.1.I hava been succeed in importing the data with Osmosis Version 0.44.1
