### ISSUE TITLE
Undefined method when trying to edit

### ISSUE THREAD

**Issue by adam21** [openstreetmap/openstreetmap-website#1072]
Hello everyone,

I used the example below to configure potlatch2 editor  : 

```
# Default editor
default_editor: "potlatch2"
# OAuth consumer key for Potlatch 2
potlatch2_key: "8lFmZPsagHV4l3rkAHq0hWY5vV3Ctl3oEFY1aXth"
```

But when trying to edit with potlatch2, I get this error message : 

![image](https://cloud.githubusercontent.com/assets/11215545/10578040/d8892862-766f-11e5-86ce-2028900b8e84.png)

The error is saying that the method "access_token_for_ser" is undefined , Do you have any idea please ?

**Comment by tomhughes** [comment]
Well clearly that isn't a valid key, or you haven't restarted rails since you put that in the configuration.

**Comment by adam21** [comment]
I have restarted rails after updating application.yml file, but how can I get a valid key ??

**Comment by tomhughes** [comment]
By registering an OAuth application in the normal way - how did you get the value you are using at the moment?

**Comment by adam21** [comment]
I'am getting this value from the config description [here](https://github.com/openstreetmap/openstreetmap-website/blob/master/CONFIGURE.md)

Please correct me if I'm wrong

**Comment by tomhughes** [comment]
That's an example! It won't match any client in your database for, err, fairly obvious reasons.

You need to visit `http://myserver/user/myuser/oauth_clients` and register a client in your server and use it's key. Then the `ClientApplication.find_by_key` might actually find it...

**Comment by adam21** [comment]
I used the OAuth settings to generate a key and now I'am able to add new spatial objects (point, line, polygon) but not to edit my own apidb that I have set up with osmosis.

In the configuration page - Populating database section, the [yet-to-be-written script](https://github.com/openstreetmap/openstreetmap-website/issues/282) link doesn't point to a ready for use solution.

Do I have to create this script myself ? Can I edit an existing apidb the same way like in the openstreetmap public website ? 

![image](https://cloud.githubusercontent.com/assets/11215545/10584223/3e16669c-7691-11e5-8d90-73e46a1b658e.png) 

Thank you

**Comment by tomhughes** [comment]
Can I suggest that the mailing list or IRC would be a more appropriate place to seek help - there is clearly no bug here.

Yes of course you can edit the database in the normal way.
