### ISSUE TITLE
notes: relative date in german translation duplicates "vor"

### ISSUE THREAD

**Issue by Florian77711** [openstreetmap/openstreetmap-website#1080]
When showing the details of a note on openstreetmap.org, the date-value of the description and the comments show something like "vor vor 4 Monaten" in german , where the correct grammar would be "vor 4 Monaten".

**Comment by Florian77711** [comment]
Looking at the HTML-Code, this looks kind of interesting, where the title is set twice with different values (but both german):
```
<abbr title="Dienstag, 10. März 2015, 20:28 Uhr">
    vor <span title="10. März 2015 um 20:28">vor 8 Monaten</span>
</abbr>
```
Looking a little bit in the config-locales de (https://github.com/openstreetmap/openstreetmap-website/blob/91d22710ba4b64d8c15f33f694a7a9206556b825/config/locales/de.yml#L165) , the problem may be the following:
```
    commented_by: Kommentar von %{user} <abbr title='%{exact_time}'>vor %{when}</abbr>
```
Where "vor" is "hardcoded" in the locales, but the %{when} already adds a "vor" to the date-string

**Comment by HolgerJeromin** [comment]
So the problem has to be solved at the translation website. Nearly all places with dates are affected btw. For example changeset details.
