### ISSUE TITLE
For some time after note closure, inform that changes take time to render

### ISSUE THREAD

**Issue by RicoElectrico** [openstreetmap/openstreetmap-website#1084]
It may be (and indeed that was the case sometimes) confusing for non-OSM-proficient people that changes take time to render. I propose a box below "closed by" message to be displayed for 24h or so:

> Notice: changes (if any) may take time to appear on the map. 

(If you feel this fit, "take time to appear" could link to the same help.osm.org question that iD displays after changes. Or even mention "map data" as an alternative, but that might me superfluous.)

Also it'd be nice to tidy up the layout, especially fixing #704. Comments should make a chronological flow.

**Comment by mmd-osm** [comment]
This issue is very old. I don't see any comments/reactions. Also nobody else created a similar issue. Is this really needed today? 
I would close this issue or now. Please comment if you think it's still relevant.

**Comment by AntonKhorev** [comment]
Non-OSM-proficient people don't know that just by closing a note they are not making any changes to the map. It wouldn't help to tell them that some changes that never happened may take time to appear.
