### ISSUE TITLE
GPLv2 as it applies to openstreetmap rails project

### ISSUE THREAD

**Issue by drewpotter** [openstreetmap/openstreetmap-website#1086]
Hello,

I am just wondering what the GPLv2 means if I wanted to create a website based off of this project and modified it, would I need to release those changes under the GPLv2 even if I didn't distribute the project?

Does distribution simply include hosting the website on a public server in this case?

Thanks.

**Comment by tomhughes** [comment]
It means what it says it means, and distribution refers to the thing that the license applies, which is to say the code. Now I guess you could argue that javascript which is sent to the user's browser is distributed, but the ruby code certainly isn't. I've never heard of anybody trying to read GPL in that way - it is after all why AGPL exists for people that want to extend the meaning of distribution in that way.

Obviously this isn't legal advice - I'm not a lawyer and I'm certainly not your lawyer. If you want a proper opinion as to what the license means you should ask a lawyer.
