### ISSUE TITLE
Diary taken over by spam

### ISSUE THREAD

**Issue by planemad** [openstreetmap/openstreetmap-website#1093]
The OSM diary just got hit by [12 pages of spam posts](https://www.openstreetmap.org/diary?page=12) by [this user](https://www.openstreetmap.org/user/역삼오피@bamwar).

Maybe block creating diary posts till a user has atleast 1 edit?

Related #1083

**Comment by simonpoole** [comment]
Then you would be complaining that there was spam added to the map by the user. Anything that requires a spammer to edit is -not a good idea- (TM). There are already hurdles in place (otherwise things would be a lot worse).

**Comment by tomhughes** [comment]
Duplicate.

**Comment by planemad** [comment]
Posts were cleared but is back again by multiple usernames all containing `bamwar`
