### ISSUE TITLE
Invalid map position when using third party authentication

### ISSUE THREAD

**Issue by bagage** [openstreetmap/openstreetmap-website#1102]
I am not sure if the problem lands in openstreetmap-website or iD, but when I try to open an URL containing `editor=id` to a given position without being authenticated: I have to authenticate myself first, but then the map is NOT placed to the expected position. The same scenario is working fine using email/password authentication.

Here are steps to reproduce:

1. open [this first position](http://www.openstreetmap.org/#map=6/39.028/15.359)
* log out from openstreetmap.org account
* open [this second position](http://www.openstreetmap.org/edit?editor=id#map=18/44.4172220943/4.75632411629)
* use third party provider to authenticate
* you will be redirect to first position instead of the second one.

If you change step 4. by using standard authentication, you are correctly redirected to position 2 as expected.

**Comment by tomhughes** [comment]
I don't think you really mean OAuth here, you just mean authenticating using a third party provider right? Some of those might use OAuth but that's a mere detail and I don't expect it impacts on whether the fragment is preserved.

**Comment by bagage** [comment]
You are right @tomhughes, wrong term here. I edited title accordingly.

**Comment by tomhughes** [comment]
No problem. I can see the problem, it's just not exactly trivial to fix. Preserving fragments is hard...

**Comment by bagage** [comment]
OK got it! It is not a major issue anyway, one can still use standard authentication as a work-around.
