### ISSUE TITLE
Query features "?" should also show lat/lon of where we put it

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1110]
If the query features "?" also listed the lat/lon of the place we put
it, it would be 1000 times better than "Where am I", at least for getting the lat/lon of ones favorite spot on the map.

**Comment by tomhughes** [comment]
Please stop opening multiple bugs complaining about "what am I". We already have #412 to cover this and just trying to shove your preferred behaviour into another feature doesn't change the underlying issues.
