### ISSUE TITLE
Sitemap.xml is missing

### ISSUE THREAD

**Issue by BushmanK** [openstreetmap/openstreetmap-website#1113]
/robots.txt file refers to non-existent /sitemap.xml.gz file, which should obviously contain a map.
This link should be deleted as redundant or sitemap.xml should be created, if needed.

**Comment by tomhughes** [comment]
You're right of course, but I'm wondering why you're concerned about it?

Basically the story is that the sitemap is enormous and I can never be bothered to try and keep it up to date. To be honest I don't know if it would even be practical to do so.

**Comment by BushmanK** [comment]
In case of osm.org, sitemap can't be "enormous" - there are less than ten links there.
I'm not insisting on any of two ways, but having a sitemap.xml just makes the search result for "Openstreetmap" look better (which will not harm anyone), while having this non-working reference is obviously redundant. Changes of osm,org front page are so rare, that I don't see any problem with keeping sitemap.xml up to date.

And, speaking of reason for my concern - it doesn't bother me more than any non-working code in the world, but once I stumbled upon it (looking for a cause of another problem), why not to check, if anyone cares about it? I didn't take any actions by myself, because I'm completely unaware of situation in this repository - many OSM projects are quite conservative.

**Comment by tomhughes** [comment]
There are millions of links actually - one for every node, way and relation not to mention users, diary entries and so on.

What I was really asking was whether this was actually causing you a problem or whether it was just something cosmetic that you had somehow noticed. Apparently it was the second, which is fine.

**Comment by BushmanK** [comment]
No, it doesn't cause me any specific problem.
