### ISSUE TITLE
Sex spam in OSM data

### ISSUE THREAD

**Issue by SHARCRASH** [openstreetmap/openstreetmap-website#1124]
What a surprise! Sex spam in OSM data... I hope this is not the start of a spam wave... Is it time to insert some sort of exam before being allowed to edit OSM data to prevent spamming and other aberrations? 

Changeset: http://www.openstreetmap.org/changeset/36329828
Spammer: http://www.openstreetmap.org/user/Desire%20Escorts%20Amsterdam

**Comment by tomhughes** [comment]
This tracker is for bugs in the code, not for content reports.

**Comment by SHARCRASH** [comment]
OK sorry thanks...
