### ISSUE TITLE
Changeset comment notifications sent in wrong locales

### ISSUE THREAD

**Issue by sabas** [openstreetmap/openstreetmap-website#1125]
I've started receiving email notifications in random languages, but I've it-IT on my user profile
For example in Dutch
```
Hallo,
USER heeft gereageerd op een van uw wijzigingenset gemaakt op 2016-01-05 13:16:18 UTC 
```
Or partly in Turk
```
Merhaba,

EneaSuper has left a comment on one of your changesets
```

**Comment by tomhughes** [comment]
Well it's not a question of "enforcing" anything, you've just found a bug.

**Comment by tomhughes** [comment]
We're definitely selecting the right locale (https://github.com/openstreetmap/openstreetmap-website/blob/master/app/models/notifier.rb#L156) so it's not obvious why this should happen.

Have you only seen it with changeset comment notifications? or is it more general than that?

**Comment by tomhughes** [comment]
My immediate guess would be that something in rails has changed so that `mail` doesn't send the mail immediately, by which time we have exited the `with_recipient_locale` block and the locale has been reset.

**Comment by sabas** [comment]
Looking at previous emails I got this behavior also on 24/12 with an email in Korean, but are all changeset comments notifications. Private messages are all in Italian.

A month ago I switched from english to italian as main language.

**Comment by tomhughes** [comment]
I think it's because you have `it-IT` but that isn't an actual language we have. Using `it` does work.

There's obviously some difference in the way we match languages for the web site vs when sending emails.

**Comment by sabas** [comment]
Ok, I'll change it to ```it```
