### ISSUE TITLE
The search submit button should be labeled "Search" or (Magnifying glass)

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1127]
1. Browse http://www.openstreetmap.org/
2. Observe the word Go on a button in the upper left.

The search submit button should be labeled "Search" or (Magnifying glass).
Compare Google or Wikipedia.
Mislabeling it "Go" implies that it will move the map directly to the place you type in.
But in fact it just displays search results.
And after that even the word "Search" is no longer sitting in the textbox.
So all that is left is "Go" and no "Search" at all!
Show me one other site that uses Go for Search.
Go should be reserved for Google's "I'm feeling lucky" action.

**Comment by tomhughes** [comment]
Presumably you noticed that there isn't actually space for a longer word? That's why we went with the, admittedly suboptimal but short "Go" instead.

**Comment by polarbearing** [comment]
"Do" would be an alternative of the same length, while also suboptimal.
Maybe adding a tooltip to the Go button would help: "Start searching".
the "Where am I" link and the directions button have tooltips, the Go button not.

**Comment by jidanni** [comment]
Well as right next door to it you use a graphic for Directions. So maybe also use a graphic for Search. Use one that looks like some of the Unicode mentioned in 
http://stackoverflow.com/a/12036141 . Also add alt="Search" etc. at the same time too.

**Comment by polarbearing** [comment]
A magnifying glass, in a map context, has mostly the meaning of zoom, not search. 

The tooltip could also read "Go searching", thus expanding the label on the button verbally.

**Comment by jidanni** [comment]
https://maps.google.com/
https://maps.bing.com/
https://maps.here.com/
...
all use a magnifying glass.

**Comment by polarbearing** [comment]
That does not mean that it is right. OSM was set up in order not to copy the mistakes Google etc make. A magnifying glass magnifies, it does not search.

**Comment by danstowell** [comment]
@polarbearing I would argue that you are wrong and @jidanni is right. A well-known rule of web usability: "Users spend most of their time on other sites. This means that users prefer your site to work the same way as all the other sites they already know." [cite](https://www.nngroup.com/articles/end-of-web-design/). This rule is not always the rule to use but it's the one to use in this case.

**Comment by jidanni** [comment]
Well on http://urmap.com.tw/ there are three magnifying glasses, search,
zoom-in, and zoom-out!

And mainly + and - are what communicates zooming, these days and there
too.

Yes I seem to remember non-slippy map sites with plain magnifying glasses for
zoom in (but then what to use for zoom out?!) But I checked and they are
all now using + and -.

So I posit that these days magnifying glass means search, on map sites and elsewhere.

**Comment by jidanni** [comment]
I found a pair of + - magnifying glasses! Right in Google chrome (chromium)'s
PDF viewer. OK but that isn't a map application.

**Comment by jidanni** [comment]
But Firefox's PDF viewer uses plain + - for zoom. So what does Google Chrome PDF viewer use + - for, choosing page numbers? Nope, they are within the magnifying glasses. Er, OK fellows it sees I should take   a    little     nap...

**Comment by polarbearing** [comment]
> I found a pair of + - magnifying glasses!
That's what I see in geoportals quite often, and no button at all for the search field because you can just press the Enter key.
> the same way as all the other sites
strange argument, if you always do the same as others, you deny progress.

**Comment by GaspardPO** [comment]
>  Mislabeling it "Go" implies that it will move the map directly to the place you type in.
> But  in fact it just displays search results.

It seems that now when clicking on "Go", it displays the result, but also move the map to the place.

May be it was a change during the two previous years.

I assume that now the "Go" button does what it implies : it goes to a place.
So we can probably close this issue.
