### ISSUE TITLE
Unclear exactly what final 'Remember me' refers to on Login page

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1128]
At the bottom of the login page one sees:
_______
>Alternatively, use a third party to login:
>
>Login with OpenIDLogin with a Google OpenIDLogin with a Facebook AccountLogin with a Windows Live AccountLogin with a Yahoo OpenIDLogin with a Wordpress OpenIDLogin with an AOL OpenID
>Log in with an OpenID OpenID:
>(what is this?)
>Remember me

_______

It is not clear if this second 'Remember me' refers to both the ...Facebook... AND the 'Log in with an OpenID,    OpenID:', OR just the 'Log in with an OpenID OpenID:'.

**Comment by tomhughes** [comment]
Hmm, there is something wrong there - the input field and checkbox are supposed to be hidden until you select openid.

**Comment by jidanni** [comment]
In #3899 now the 2nd Remember Me is gone...
