### ISSUE TITLE
OSRM routing mode broken

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/openstreetmap-website#1129]
OSRM routing mode currently doesn't produce routes for me.

The javascript console shows a `No 'Access-Control-Allow-Origin' header is present` error. The following request is sent, but produces a strage result:
 
````
$ curl "http://router.project-osrm.org/viaroute?z=14&output=json&instructions=true&loc=46.493665357623804%2C11.326904296875&loc=47.00086080525212%2C11.502685546875" --verbose
* Hostname was NOT found in DNS cache
*   Trying 141.3.85.1...
* Connected to router.project-osrm.org (141.3.85.1) port 80 (#0)
> GET /viaroute?z=14&output=json&instructions=true&loc=46.493665357623804%2C11.326904296875&loc=47.00086080525212%2C11.502685546875 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: router.project-osrm.org
> Accept: */*
> 
	< HTTP/1.1 302 Found
* Server nginx/1.1.19 is not blacklisted
< Server: nginx/1.1.19
< Date: Sun, 10 Jan 2016 09:40:14 GMT
< Content-Type: text/html; charset=UTF-8
< Content-Length: 0
< Connection: keep-alive
< Location: http://magento-experimental.test.signifyd.com:80/
< 
* Connection #0 to host router.project-osrm.org left intact
````

The interface at [osrm.at](http://osrm.at) requests routes from `http://api-osrm-routed-production.tilestream.net/` instead of `http://router.project-osrm.org/`. Maybe the URL has to be updated on osm.org as well? On the other hand, the [documentation](https://github.com/Project-OSRM/osrm-backend/wiki/Api-usage-policy#server-name) on github still lists the now broken endpoint…

//cc @TheMarex

**Comment by tomhughes** [comment]
So it sounds like the problem is at the OSRM end, so I'm not sure what you expect us to do? Have you reported it to the OSRM people?

**Comment by tyrasd** [comment]
You're right.

**Comment by tomhughes** [comment]
I have pinged OSRM on IRC already, given it wasn't clear where to file a ticket for the public instance, but I'll watch that ticket as well in case we need to change something.

**Comment by systemed** [comment]
Given that the OSRM demo server has been erratic for a while, would it be worth considering Graphhopper's car profile as the default? (We don't have the Graphhopper car profile in the menu at present, but it should just be a matter of adding a `car` option at the bottom of https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/javascripts/index/directions/graphhopper.js.)

cc @karussell

**Comment by danpat** [comment]
Currently, `router.project-osrm.org` is a reverse proxy to `api-osrm-routed.tilestream.net`.  The reasons for this are long and historical, but basically, the original OSRM demo server at KIT is no longer being actively maintained.  We managed to get a reverse proxy set up on it so that existing users wouldn't need to change anything, but it looks like that reverse proxy is now broken, and the maintainer of the box is unavailable :-(

You can point to `api-osrm-routed.tilestream.net`, it was the machine that has actually been serving requests for the last several months anyway.

We are endeavoring to get access to the DNS/SSL certificates needed to resurrect `router.project-osrm.org`, but no luck so far.

**Comment by tomhughes** [comment]
I've switched the live site to use the tilestream.net instance now.

**Comment by danpat** [comment]
@tomhughes thanks.  Please note that this is hopefully just temporary, that URL is not intended to be the permanent home, just a stopgap to temporarily stem the tide of bug reports.

**Comment by tomhughes** [comment]
@danpat That, in part at least, is why I didn't change the OSM code base, but just our production instance...

**Comment by stephan75** [comment]
@systemed please be aware that the main web instance of graphhopper public server is **still not able** to work with turn restrictions.
see https://discuss.graphhopper.com/t/status-of-turn-restrictions-in-web-frontend-engine/169 for details.
I assume that the same server is used for foot and bicycle routing.

**Comment by freenerd** [comment]
Sorry for all the trouble. https://router.project-osrm.org is up again. We've also taken measures to ensure it will be more stable in the future, by removing an intermediate proxy and pointing DNS more directly at the demo server.

**Comment by RikdeBoer** [comment]
Issue has resurfaced a couple of days ago on 

router.project-osm.org 

In its response header the server must explicitly state which sites may access it. Like so:

Access-Control-Allow-Origin: *

However there is nothing of this kind in the response header, so all calls fail.

**Comment by RikdeBoer** [comment]
It just started working again. Yay!
