### ISSUE TITLE
Changeset discussion not available

### ISSUE THREAD

**Issue by malenki** [openstreetmap/openstreetmap-website#1134]
As the subject sais. Discussing [this changeset](https://www.openstreetmap.org/changeset/36578572) is just impossible.
Screenshot of how it looks right now:  
![2016-01-14_211529_scr](https://cloud.githubusercontent.com/assets/188565/12336278/fd71e1f4-bb03-11e5-89e4-22ea0e2a51ad.png)

**Comment by pnorman** [comment]
You can't comment on open changesets. See #845

**Comment by malenki** [comment]
Sorry for the invalid issue. I hadn't realised that the changeset was still open.
