### ISSUE TITLE
Rake migrate fails on passing a string to ActiveRecord::Base.establish_connection

### ISSUE THREAD

**Issue by ilit-all** [openstreetmap/openstreetmap-website#1137]
When installing according to INSTALLATION.md via Ubuntu 14.04, I get the following error. Does anyone have any idea what causes this?

ilit@ilit-isedc:/opt/osm/openstreetmap-website$ sudo bundle exec rake db:createDEPRECATION WARNING: Passing a string to ActiveRecord::Base.establish_connection for a configuration lookup is deprecated, please pass a symbol (:postgresql) instead. (called from call at /usr/lib/ruby/2.2.0/rake/task.rb:240)
rake aborted!
ActiveRecord::AdapterNotSpecified: 'postgresql' database is not configured. Available: ["development", "adapter", "database", "username", "password", "host", "encoding", "test", "production"]
/var/lib/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:248:in `resolve_symbol_connection'
/var/lib/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:231:in `resolve_string_connection'
/var/lib/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:213:in `resolve_connection'
/var/lib/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
/var/lib/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:151:in `block in resolve_all'
/var/lib/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:150:in `each'
/var/lib/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/connection_specification.rb:150:in `resolve_all'
/var/lib/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:69:in `resolve'
/var/lib/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/core.rb:46:in `configurations='
/var/lib/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:5:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:create => db:load_config
(See full trace by running task with --trace)
_____________________________________________________-

This error occurs in other calls Rake.

**Comment by tomhughes** [comment]
Looks like you have setup `database.yml` incorrectly, but it's certainly not a bug in our code.

If you need help please use IRC or the mailing list.

**Comment by tomhughes** [comment]
Incidentally nothing in the instructions tells you to use sudo when migrating the database and I wouldn't recommend it.

**Comment by ilit-all** [comment]
Thank you very much, Tom!
