### ISSUE TITLE
Large lakes not shown (depending on resolution)

### ISSUE THREAD

**Issue by JuangDse** [openstreetmap/openstreetmap-website#1149]
If you go to

http://www.openstreetmap.org/#map=6/-10.984/35.964
http://www.openstreetmap.org/#map=7/-10.984/35.964

and look at the main lake in the center (Lake Malawi), you will notice that the first map only shows its lower part and the second its upper.

**Comment by tomhughes** [comment]
Not a web site issue - rendering issues should be reported at https://github.com/gravitystorm/openstreetmap-carto/issues.

**Comment by polarbearing** [comment]
Tile status/caching issue. Refreshed: [carto 2036](https://github.com/gravitystorm/openstreetmap-carto/issues/2036)
