### ISSUE TITLE
Revoking oauth token

### ISSUE THREAD

**Issue by zbycz** [openstreetmap/openstreetmap-website#1150]
Hi,

we are using oauth as a login method at www.openstreetmap.cz, but there is an issue -> every time user logs in a new "Oauth access token" is created.

When I obtain a valid access token (oauth_token + oauth_token_secret), i would need to revoke the old pair i saved in the database. (Alternative would be to revoke the newly obtained and use the old one)

On the OSM website there is a resource `POST https://www.openstreetmap.org/oauth/revoke` which is invoked as a form submit - with:
```
utf8=%E2%9C%93
&authenticity_token=...
&token=...&commit=Odvolat%21
```

I know the token, but **how to construct the authenticity_token**?

-----------------

btw, I tried POSTing to this resource the same way I request api, but it responds with 403.
```php
$this->oauth->fetch('https://www.openstreetmap.org/oauth/revoke', [
                'token' => $this->getSession('oauth')->token
            ], OAUTH_HTTP_METHOD_POST);
```

Also i tried to find in this repo, where is the authenticity_token constructed, but didnt find it.
Thanks for help from czech community :-)

**Comment by tomhughes** [comment]
Firstly, why are you generating a new token every time if you've still got a valid token in the database?

Secondly, we provide OAuth so you can authenticate people to perform access on openstreetmap.org not so that you can use our database to authenticate users to your web site, and we do not support such (ab)uses of it.

Thirdly, use the OAuth specification to learn how to use OAuth rather than trying to guess from what our web site code does... For the record the `authenticity_token` is standard parameter that rails attaches to all forms as a security measure but it will be ignored by API methods like that.

**Comment by tomhughes** [comment]
For the record https://tools.ietf.org/html/rfc7009#section-2.1 is the specification for the revoke API endpoint.

**Comment by zbycz** [comment]
Hello Tom, 

firstly, thanks for replying. I havent probably expressed myself correctly, let me explain.

- We need users to autheticate to www.openstreetmap.cz website, because we are building a POI edit tool (see [demo](http://openstreetmap.cz/#map=15/50.1075/14.2754&layers=A)). And in order to let users commit changesets to OSM, we need the access token. Also in near future, we would like to launch our own iD instance with some additional features.

I save the token to the database - but once the user lost his cookie, I dont have any other means of identification. Would you agree, that forcing him to create specific set of login/password for our website is really unfriendly?

So everything works just fine, with the issue that every time user forgots his cookie, i request a new token. (btw, same issues goes for this project as well https://github.com/osmlab/osm-auth)

Thanks for pointing me to the specs, I found it before as well. But token revocation was introduced in OAuth2.0 - but osm.org uses OAuth1.0. So i guessed that maybe you implemented the token-revocation endpoint in current website. Thats why i was trying to call it. But when i call it - i get status 403 .

Regarding the fact the revocation endpoint already exist (only for ruby in-app requests), would you mind to allow accessing it with valid oauth token as well?

**Comment by tomhughes** [comment]
As far as I know that endpoint is a standard thing provided by the ruby oauth gem we use and wasn't implemented by us.

**Comment by zbycz** [comment]
You are right - but this [source](https://github.com/openstreetmap/openstreetmap-website/blob/77c25dca8c9b60c2fd8dae6eeee1405ec24edf27/app/controllers/oauth_controller.rb#L8-L11) authorizes the revoke endpoint only with session logged user.

If you wanted to enable OAuth authorized request as well, it would need calling [authorize](https://github.com/openstreetmap/openstreetmap-website/blob/5d3ecffa28510c867665001a7615559a185869c6/app/controllers/application_controller.rb#L170) method as well.

Do you think its possible to implement it?

**Comment by zdila** [comment]
Also umap can use OSM for authentication. I use it often and so I can now see many issued tokens at http://www.openstreetmap.org/user/username/oauth_clients/. So it seems to be problem of OAuth 1.0 design and we must live with valid tokens "pollution".

BTW at next.freemap.sk we will also use OSM for authentication and we will have the same problem. Workaround is to ignore it ;).
