### ISSUE TITLE
Wrap around code blogs in diary

### ISSUE THREAD

**Issue by malenki** [openstreetmap/openstreetmap-website#1152]
When using code blocks in an OSM diary entry the code is not wrapped around.

It would be nice if this could be done automagically so that it isn't the writers task to wrap the code lines by hand.
![2016-02-11_191731_scr](https://cloud.githubusercontent.com/assets/188565/12985834/c0d727f2-d0f4-11e5-9098-1756c35aa7d5.png)

**Comment by tomhughes** [comment]
Well code is code and is presented "as is" on pretty much every publishing platform.

That's the whole point of code blocks, that they don't try and do clever formatting!

**Comment by malenki** [comment]
Probably I should enhance the <s>ugly</s> one-liners I often use.

**Comment by mmd-osm** [comment]
2500 char string is wrapped around today.

![image](https://github.com/openstreetmap/openstreetmap-website/assets/5842757/78167e6c-92f0-49af-a252-d1d3f3fdb39a)
