### ISSUE TITLE
Smooth transitions when zooming in on website

### ISSUE THREAD

**Issue by SomeViktor** [openstreetmap/openstreetmap-website#1153]
Hey everybody, I'm afraid I'm not entirely shure if this is the right repo to open this issue in, sorry if its not.
I think it would improve the user experience a lot if the openstreetmap website had smooth transitions when zooming in.
What I mean by that: Right now, theres some sort of white flash and then the map is reloaded on a higher level of detail.
What I think would be better: to keep the "old", more zoomed out map view visible, zoom in to that, and then replace the map tile by tile as soon as the new tiles are loaded, if possible in a smooth transition.
I think that would make the usage a lot more "smooth" and comfortable

**Comment by tomhughes** [comment]
The map is using any leaflet, so any issues with the map UI should be handled at https://github.com/Leaflet/Leaflet/issues.

**Comment by tomhughes** [comment]
That said, I don't see the behaviour you describe, so I suspect it is specific to your browser/os/graphics card.
