### ISSUE TITLE
Marker location changes colour

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/openstreetmap-website#1155]
If I go a map location, e.g.
http://www.openstreetmap.org/#map=19/52.19503/0.13755&layers=N
then open the share panel, and click 'Include marker', a blue marker is shown.

If I paste the resulting permalink URL, e.g.
http://www.openstreetmap.org/?mlat=52.19503&mlon=0.13755#map=19/52.19503/0.13755&layers=N
into the browser, that link now shows the marker in red.

This is inconsistent and a usability problem - it means that someone could send a link to someone else with a note "See the location of the blue marker" and the recipient will not know what is being shown.

**Comment by marcows** [comment]
That's true. But if using the same blue marker and then on the resulting map you open the share panel and click on "Include marker" again, there would be two blue markers, confusing as well. Even if this might not be a common use case in practice.

Perhaps the moving marker (to set the position) should have the same color, but brighter or semi-transparent.

@simon04 @tomhughes what do you think?
