### ISSUE TITLE
Object query hits javascript error TypeError: t.bounds is undefined

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#1156]
For full details and some background infos, please refer to this post: https://help.openstreetmap.org/questions/48088/what-makes-a-closed-way-show-up-as-an-enclosing-feature-with-query-features
That's where the issue was initially reported.

**How to reproduce:**

* See http://www.openstreetmap.org/query?lat=39.6181&lon=-74.5019#map=15/39.6176/-74.4857

**Issues:**

* Although there are several enclosing features, none of them are shown.
* Javascript console shows the following error message: `TypeError: t.bounds is undefined`

**Further analysis:**

Upon calling the `query` feature above, the following Overpass API is getting executed in background:

```C
[timeout:5][out:json];is_in(39.6163,-74.5054)->.a;way(pivot.a);
out tags geom(39.59927344095099,-74.5391035079956,39.633324269501465,-74.4717264175415);relation(pivot.a);out tags bb;
```

Overpass result:

```
  "type": "way",
  "id": 33832747,
  "geometry": [
...

    null,
    null,
    null,
    null
  ],
  "tags": {
    "area": "yes",
    "boundary": "national_park",
    "name": "Pinelands National Reserve"
  }
},
```

To display a list of enclosing features on the UI, they're initially sorted by their respective size. This is implemented in the following [piece of Javascript code](https://github.com/openstreetmap/openstreetmap-website/blob/36cbda3c80beac9496316389d4f082383ed4322a/app/assets/javascripts/index/query.js#L230-#L239). Due to the missing `bounds` element in the Overpass API result for way 3383274, we hit a Javascript error.

```
    function i(t, e) {
        var n = t.bounds.maxlon - t.bounds.minlon
          , o = t.bounds.maxlat - t.bounds.minlat
          , a = n * o
          , r = e.bounds.maxlat - e.bounds.minlat
          , i = e.bounds.maxlat - e.bounds.minlat
          , s = r * i;
        return a - s
    }
```

**Comment by tomhughes** [comment]
Surely when looking for enclosing objects it's entirely normal for none of the nodes to be in the visible area?

Certainly we wouldn't want to filter out those results, just not try and draw the bbox or something.

**Comment by mmd-osm** [comment]
> enclosing objects it's entirely normal for none of the nodes to be in the visible area?

Yes, http://www.openstreetmap.org/way/33832747 is pretty huge, and if you're on zoomlevel 15, it just happens, that you're inside the area, but none of the nodes are in the bbox provided in the Overpass query. That's pretty much what `geom(39.59927344095099,-74.5391035079956,39.633324269501465,-74.4717264175415)` is good for.

**Comment by tomhughes** [comment]
Well exactly - every time I click somewhere in London the "England" polygon will doubtless enclose it but without any nodes being in the bbox so why do we not see this all the time?

**Comment by mmd-osm** [comment]
Well, the overpass query only restricts the ways'  output via `geom(...)`. Relations are just returned as is. I guess in case of the "England" polygon, we're dealing with a relation, so that's really a different case.

**Comment by ljb279** [comment]
Would it be OK if I try to 'fix' the specific case mentioned above on the map?  (I am the one who started the question on help.openstreetmap.org referenced above.)

What I want to do is create a new multipolygon relation with one role=outer member - way 33832747, move the name and boundary tags from that way to the new relation, and remove area=yes from the way. If I understand the above, that should allow 'enclosing features' to work within the Pinelands National Reserve.

I understand this could make it harder to fix the underlying cause, so I don't want to do it without approval. But right now this affects a large part of Southern New Jersey where I do mapping.

**Comment by ljb279** [comment]
Followup: I tried the above change to Way 33832747 on the map but it didn't help with 'enclosing features'. I still get an empty list in the browser, and TypeError.  So I undid my change, putting everything back the way it was.

**Comment by mmd-osm** [comment]
@ljb279 : under normal circumstances, transforming the area from way to relation would make the error on the UI go away. However, as the area creation on overpass-api.de lags behind a few weeks (no updated since 2016-02-11), your changes were not reflected on the UI at any time - the query was still using the old areas, hence returning way 33832747 without bounds.

**Comment by tomhughes** [comment]
So the root problem is that, for enclosing features defined by a way, we ask overpass for a geometry clipped to the current view:

```
out tags geom(....)
```

Now normally that returns a bounding box as well as the clipped geometry, and I assumed that was the full bounding box, but it turns out it is the bounding box of the clipped geometry.

That causes two problem - firstly this exception if the geometry is completely clipped away so that there is nothing left and hence no bounding box and secondly it means we are sorting features incorrectly because we use the bounding boxes to sort them by size.

**Comment by mmd-osm** [comment]
At least in the [documentation](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Print_.28out.29)  I could not find an explicit hint how `bounds` should behave in the context of `out geom(...)`: 

> The attribute "geom" can be followed by a bounding box in the format "(south,west,north,east)". In this case only coordinates that are inside the bounding box are produced. For way segments also the first coordinate outside the bounding box is produced to allow for properly formed segments. 

I assume that only those nodes which are produced by `out geom(...)` would also count towards the `bounds` element.

 @drolbr : Roland, can you please comment on this one? Am I missing something here or is this all works as designed?

Maybe adding another `out bb ids;` would be an option to produce a full bounding box without repeating all data again:

```C
[timeout:5][out:json];is_in(39.6163,-74.5054)->.a;way(pivot.a);
out tags geom(39.59927344095099,-74.5391035079956,39.633324269501465,-74.4717264175415);
out bb ids;relation(pivot.a);out tags bb;
```

This returns an additional way with id and unclipped  `bounds` details and should be usable for sorting purposes.

```JSON
{
  "type": "way",
  "id": 33832747,
  "bounds": {
    "minlat": 39.1919712,
    "minlon": -75.0191372,
    "maxlat": 40.1129889,
    "maxlon": -74.2086371
  }
```
Of course there's also the option to have ways behave like relations via `out bb tags;`

**Comment by tomhughes** [comment]
Yes doing separate outputs for bounds and geom works, but then it needs to be merged client side. I'm trying to make that work at the moment...

**Comment by mmd-osm** [comment]
Thanks for the quick fix! I didn't look at the code in detail, but I assume it also handles contradicting `bounds` details, like in the following example:

```C
  [timeout:5][out:json];is_in(39.6163,-74.5054)->.a;way(pivot.a);
out tags bb;out ids geom(39.2,-74.5,41,-74);relation(pivot.a);out tags bb;
```

```JSON
{
  "type": "way",
  "id": 33832747,
  "bounds": {
    "minlat": 39.1919712,
    "minlon": -75.0191372,
    "maxlat": 40.1129889,
    "maxlon": -74.2086371
  },
  "tags": {
    "area": "yes",
    "boundary": "national_park",
    "name": "Pinelands National Reserve",
    "website": "http://www.nps.gov/pine/",
    "wikipedia": "en:New Jersey Pinelands National Reserve"
  }
},
{
  "type": "way",
  "id": 33832747,
  "bounds": {
    "minlat": 39.5259208,
    "minlon": -74.5065613,
    "maxlat": 40.1129889,
    "maxlon": -74.2086371
  },
  "geometry": [
    null,
```

**Comment by tomhughes** [comment]
Hmm that's a good point...

**Comment by tomhughes** [comment]
Fixed in 6e154d48c0e77ea110fc93772c6a2be113a90bb1.

**Comment by mmd-osm** [comment]
Thanks, that looks better now!

There's one thing I noted. Wasn't there some red bbox shown on the map when hovering over each entry in the enclosing feature list? That feature was quite handy to get some idea about the actual size of an enclosing feature.

Was it maybe removed in a different commit or is it some kind of side effect of this issue? Apologies if my memory is playing tricks on me here and that feature never existed in the first place.

**Comment by tomhughes** [comment]
I think that's only for features where we have a geometry isn't it?

**Comment by tomhughes** [comment]
Yes - eg http://www.openstreetmap.org/query?lat=51.76596&lon=-0.00648 where the first entry highlights the outline but the others are outside the viewport so don't.

**Comment by mmd-osm** [comment]
I might be confusing this with overpass turbo. I thought for relations, we also look at the `bounds` element and show some red bbox on the osm.org map.

**Comment by mmd-osm** [comment]
Ah, it's really an issue with the delete:

```Javascript
 if ("geometry" in element) {
   delete element.bounds;
  }
``` 

That should only be done for ways, relations need to be excluded.

**Comment by tomhughes** [comment]
Well relations won't have a geometry, because we only ask for a bounding box there.

**Comment by mmd-osm** [comment]
yes, sorry. you're right...

**Comment by ljb279** [comment]
I just want to add that this ("enclosing features" query) is working really well for me now. Thanks for the effort fixing it.
