### ISSUE TITLE
Hang / timeout when saving: PUT /api/0.6/changeset/create

### ISSUE THREAD

**Issue by brianreavis** [openstreetmap/openstreetmap-website#1157]
Has anyone else been experiencing this? I haven't been able to save any changes in the last few days. I'm not throwing anything crazy at it – just saving a single parking area times out. I've tried Chrome and Firefox. All other API methods (`/capabilities`, etc) work fine.

**Request URL:** https://www.openstreetmap.org/api/0.6/changeset/create
**Request Headers:**
```
Authorization:OAuth oauth_consumer_key="(redacted)", oauth_nonce="(redacted)", oauth_signature="(redacted)", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1455927807", oauth_token="(redacted)"
Content-Type:text/xml
Origin:https://www.openstreetmap.org
Referer:https://www.openstreetmap.org/id
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
```
**Request Payload**
```xml
<osm><changeset version="0.6" generator="iD"><tag k="created_by" v="iD 1.8.5"/><tag k="imagery_used" v="Bing"/><tag k="host" v="https://www.openstreetmap.org/id"/><tag k="locale" v="en-US"/><tag k="comment" v="Test save (earlier attempts were locking up)"/></changeset></osm>
```

![image](https://cloud.githubusercontent.com/assets/118480/13192931/6b37350e-d72e-11e5-85b3-5d19d0703455.png)

**Comment by tomhughes** [comment]
No, nobody else has reported such a problem, so it's likely a network problem specific to you.

**Comment by brianreavis** [comment]
I don't think it is – I've now tried on multiple ISPs, multiple computers, and multiple browsers. I had someone else save on their computer and it worked. Then I signed in on that same computer with my account and saving hangs there too.

Account: http://www.openstreetmap.org/user/Brian%20Reavis

**Comment by brianreavis** [comment]
@tomhughes Re-open? More strange behavior: try to add me as a friend on OSM. I've had multiple people try this and it spins and spins... never completes. My account seems to be in some sort of broken state.

**Comment by tomhughes** [comment]
Well a problem with your account would be an operational issue, so not appropriate here - contacting support@openstreetmap.org would be the correct way to deal with that.

That said I don't see what sort of problem could spontaneously appear.

**Comment by tomhughes** [comment]
So it wasn't the account as such, you had a wedged changeset upload from several days ago that was holding a lock on your user record.

I haven't seen that happen for years!

It should be fixed now anyway.
