### ISSUE TITLE
Upcoming breaking OSRM API change

### ISSUE THREAD

**Issue by systemed** [openstreetmap/openstreetmap-website#1161]
This will presumably affect our routing UI code:

- https://lists.openstreetmap.org/pipermail/osrm-talk/2016-February/001127.html
- https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api

Given that there isn't an announced switchover date, but it'll just happen; there's no instance of the new API to test against; some breakage is almost inevitable.

I'd suggest then that, when it does happen, we temporarily drop OSRM (defaulting to Graphhopper instead) until we can modify our code to work with the new format. I don't anticipate the changes will be complex.

**Comment by TheMarex** [comment]
Thanks for opening this ticket @systemed. I expect the file we need to update is [this one](https://github.com/openstreetmap/openstreetmap-website/blob/509f07b32e00174588081aca64b9ec1446948c8d/app/assets/javascripts/index/directions/osrm.js)?

Lets coordinate on this. I would love to have this just work with minimal breakage. Do you think it is realistic to get a PR merged before Friday? Looking at the currently implementation I would expect the code to be actually simpler.

**Comment by tomhughes** [comment]
Merging a PR is no problem, in principle at least.

Are we actually going o need to do a simultaneous deployment here? There isn't going to be an overlap period where both APIs are available?

**Comment by gravitystorm** [comment]
The only way to avoid a simultaneous deployment would be to change the client to detect the response version and handle both. Testing the new version might be challenging unless someone sets up a server with the PR already merged.

**Comment by TheMarex** [comment]
We are currently still running a fallback 4.9 version with fresh data. We want to change this soon, so #1261 tracks the progress of using the 5.x API.

**Comment by tomhughes** [comment]
Resolved by merging #1261.

**Comment by Oskrin** [comment]
Hola disculpen como hicieron para cambiar a la versión 5 sigo teniendo problemas con eso gracias
