### ISSUE TITLE
Question mark tool calls recycling containers “recycling centres”

### ISSUE THREAD

**Issue by Wuzzy2** [openstreetmap/openstreetmap-website#1164]
If you use the question mark on a recyclnig container, it will be displayed as “recycling centre” which is not correct.

How to reproduce: 

* Open www.openstreetmap.org
* Put the map anywhere where you see a node with tags `amenity=recycling` and `recycling_type=container`.
* Click on the question mark symbol on the right
* Click on the recycling symbol of the node
* Look at the list which appears

Example: Node 706259173, version 1.
Link to example: http://www.openstreetmap.org/#map=19/48.46313/7.94689

It should show “recycling container” but instead it shows “recyling centre” which is clearly false.

**Comment by tomhughes** [comment]
I'm sure there are thousands of tag combinations that it doesn't know about - in the absence of a description for a specific key+value combination if falls back to something more general.

In this case it has no knowledge of `recycling_type` at all so it falls back to a generic description for `amenity=recycling` which is not actually "recycling centre" but rather "recycling point" which would cover everything from a small container to a row of large skips.

I really don't see a problem here - we are never going to have names for every minor tag variation or we would have to have thousands of them.

**Comment by Wuzzy2** [comment]
How about renaming it more generically to “Recycling container or recycling centre”. Yes, it's a *bit* of a mouthful but it is almost always guaranteed to be correct, compared to writing just “Recycling centre”. :-)
