### ISSUE TITLE
Number of received blocks on user page incorrect

### ISSUE THREAD

**Issue by stephankn** [openstreetmap/openstreetmap-website#1168]
Number of blocks received is not correctly displayed on the user page.

Check here:
https://www.openstreetmap.org/user/wambacher

it lists "blocks received 0"
but clicking on the link reveals that the user had 1 block in the past
https://www.openstreetmap.org/user/wambacher/blocks
https://www.openstreetmap.org/user_blocks/605

By comparing with this user:
https://www.openstreetmap.org/user/sorein
https://www.openstreetmap.org/user/sorein/blocks

it looks like it is counting the active blocks which would be either 0 or 1.

Should be corrected to display the number of blocks received. So user "sorein" would show 7 blocks.

**Comment by tomhughes** [comment]
It's the number of currently active blocks, not the total number ever received. That is by design.

**Comment by tomhughes** [comment]
See also https://trac.openstreetmap.org/ticket/4972.

**Comment by stephankn** [comment]
Thanks for changing the label.

Could this issue be opened as a feature request to change the design to display the number of blocks ever received? Helps to easier identify users who had been warned in the past. Those users could require special attention especially if blocks happen more than once.

Even better: "blocks received the last 2 years" would be more forgiving about issues long time ago.
