### ISSUE TITLE
New Email Address field is pre-populated with username when editing my settings

### ISSUE THREAD

**Issue by bkowshik** [openstreetmap/openstreetmap-website#1169]
I am editing my information on the OSM profile page.
https://www.openstreetmap.org/user/bkowshik/account

When I visit the page, the **New Email Address** field is automatically filled with my username.

So, when I click on **Save**, because the username is not a valid email address I am asked to enter a proper email address.

I think it is a bug with per-populating the **New Email Address** field.

**Comment by smsm1** [comment]
Do you have a password manager installed? Could it be the browser or the password manager is automatically filling the `New Email Address` field as I cannot reproduce the problem from here. Could you try to reproduce on another web browser or computer.

**Comment by tomhughes** [comment]
I agree, this is likely some "auto form filling" feature of your browser or of a browser plugin you have installed.

**Comment by tomhughes** [comment]
Possibly because the field is called `user[new_email]` and if a form filler stopped at the `[` character it might think it is called `user` and fill in a username.

**Comment by SomeoneElseOSM** [comment]
For info, I see the same "problem" in SeaMonkey 2.39 on Windows, not other browsers.  I'd always assumed that it was the browser "trying to be clever" and populating a previously-used username.
