### ISSUE TITLE
Single link to a service that can visually display changeset

### ISSUE THREAD

**Issue by d1g** [openstreetmap/openstreetmap-website#1170]
We all know that http://www.openstreetmap.org/changeset/12345678 simply contains listing, without visual representation.

But visual representation is important to identify mistakes. While everyone in OSM make mistakes (and not only in OSM), newcomers make them more often, so they would benefit from such tool (a self-learning tool I would say). 

http://wiki.openstreetmap.org/wiki/OSM_History_Viewer#Changeset_visualisation
there others, but they are more text-based AFAIK than visual 

Yandex displays geometry changes directly in object history: https://n.maps.yandex.ru/#!/objects/1560431152/history/14677852?z=19&ll=37.610822%2C55.749771&l=nk%23sat

I suggest to add link to http://nrenner.github.io/achavi/?changeset=12345678 at /changeset/12345678 route as quick solution.

**Comment by tomhughes** [comment]
Sorry, but we're not going to be adding links to lots of random external services.

**Comment by d1g** [comment]
@tomhughes, so the solution is to host achavi.openstreetmap.org?! https://github.com/nrenner/achavi#license

I don't see how single link to achavi is about "links to lots of random external services"

**Comment by tomhughes** [comment]
Well it's not, but it opens the door. If we link to that then why not to the dozens of other changeset analyzers people have written? What do I tell them when they ask for a link? How do I decide who gets to have a link and who doesn't?

But yes equally we try to avoid relying on third party services because when they break, or the person running them gets bored and they go away, it is us that gets the complaints about things not working any more.

**Comment by d1g** [comment]
> f we link to that then why not to the dozens of other changeset analyzers people have written? 

Yes, but it makes no sense to use **none of them** at osm.org.

We have 6(?) decent routers at front page, it is good thing. But for changeset visualization there no option.

> What do I tell them when they ask for a link? 

You will show them community previous consensus on this topic (see below) and we could re-vote (if necessary at all)

> How do I decide who gets to have a link and who doesn't?

Well this question is easiest to solve: we can start community voting for 1/2 of the month or a year and use a winner at osm.org.

Tom, I understand your concerns about multiple options but we won't bite you for picking one (or a few) community likes to see at osm.org :) 

Past discussion called "dreams about changeset visualization" http://forum.openstreetmap.org/viewtopic.php?id=31097
I started new discussion for Russian speaking audience: http://forum.openstreetmap.org/viewtopic.php?id=53811


You could do the same in other public channels and open issue for, say, a month to see more opinions ;)

**Comment by iandees** [comment]
I would rather see a PR to create and view the changeset diff on osm.org instead of linking to another provider.

**Comment by d1g** [comment]
> But yes equally we try to avoid relying on third party services because when they break, or the person running them gets bored and they go away, it is us that gets the complaints about things not working any more.

@tomhughes so, we could pick any open sourced solution (with a good license) and host it at openstreetmap.org? With this in mind, there still plenty of options.

> I would rather see a PR to create and view the changeset diff on osm.org instead of linking to another provider.

@iandees (technically) Achavi can be integrated directly in osm.org interface, with only 3rd party dependency on [overpass servers](http://wiki.openstreetmap.org/wiki/Overpass_API#Introduction)

Good thing you can track their up time here: http://wiki.openstreetmap.org/wiki/Overpass_API/status

**Comment by HolgerJeromin** [comment]
the "?" feature depends on overpass. So this is probably no show stopper. But lack of code is...

**Comment by d1g** [comment]
@HolgerJeromin but we have code in other options, like: https://github.com/openstreetmap/openstreetmap-website/pull/876

If it OWL API works faster (and scales more) than Overpass API, then we go for ppawel code (to have at least one working solution at osm.org)
