### ISSUE TITLE
Allow users to login right from osm.org first page, just like Facebook does

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1177]
Put the Username________ Password_________ right there on the first page, so people can login with one less HTTP request.

That is how Facebook has always done it.

**Comment by HolgerJeromin** [comment]
Facebook is not usable without login. Osm is. 
Do we have space for username and password fields? I doubt that.

**Comment by tomhughes** [comment]
Agreed - login needs a substantial amount of space for the username and password fields and all the social login mechanics, and OSM is usable without logging in.

**Comment by jidanni** [comment]
Not totally true: "Facebook is not usable without login."
