### ISSUE TITLE
Query tool should check for errors in overpass API responses

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#1178]
During testing the #1156 fix, I noticed that the error handling is not ideal. Unlike other APIs, some Overpass API error messages are returned as `remark` element in the JSON response, even with an HTTP return code of 200.

This is affects the query feature, when the Overpass API query takes longer than 5 seconds and hits a timeout on the Overpass server. Currently, the UI would simply say "no enclosing features found", although the query actually failed with a timeout.

Please see this ticket for details on the error reporting mechanism via `remark`: https://github.com/drolbr/Overpass-API/issues/94

Here's an example how this is solved in overpass turbo: [link](https://github.com/tyrasd/overpass-turbo/blob/3f57688fe1da78e57d88fe202747281d84dfb156/js/overpass.js#L117-L148)

**Comment by tomhughes** [comment]
There is nothing in our API that returns a `remark` element in the XML. In fact the word `remark` doesn't appear in our repository at all.

**Comment by mmd-osm** [comment]
`remark` is in fact returned by Overpass API. You need to evaluate it in addition to the HTTP return code to get some meaningful error message.

**Comment by tomhughes** [comment]
We're using JSON output rather than XML so do we know what this looks like in the JSON output? Do you have an example of a query that returns an error in this way?

**Comment by tomhughes** [comment]
Ah it just has a `remark` key at the top level.

**Comment by tomhughes** [comment]
Hmm, looks like a timeout can return partial results plus a remark.

**Comment by mmd-osm** [comment]
Right. While an `out;` statement does not get interrupted by a timeout, all other statements in a query may run into a timeout. If there are multiple `out` statements in a query, the first one might have already returned some data, while the second `out` doesn't get executed anymore due to a timeout.
