### ISSUE TITLE
Changeset discussion not available when changeset has no comment

### ISSUE THREAD

**Issue by liotier** [openstreetmap/openstreetmap-website#1184]
Examples:
http://www.openstreetmap.org/changeset/37874055
http://www.openstreetmap.org/changeset/37877202

But as a counter-example, with the exact same environment but this changeset, the discussion is available as expected: http://www.openstreetmap.org/changeset/37872114

**Comment by pnorman** [comment]
You can't start changeset discussions on still-open changesets: #845

**Comment by liotier** [comment]
Thanks you for this clarification.
