### ISSUE TITLE
Vagrant provisioning fails with "sudo: rake: command not found"

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#1193]
I'm running the latest [vagrant 1.8.1](https://www.vagrantup.com/downloads.html) on Ubuntu 14.04 and followed the [Installing Vagrant](https://github.com/openstreetmap/openstreetmap-website/blob/master/VAGRANT.md) instructions to set up a local instance of the openstreetmap website.

Unfortunately, the provisioning process via `vagrant up` aborts with the following error message:

``` 
==> default: sudo: rake: command not found
```

For full log infos, please refer to this file: [logfile_vagrant.txt](https://github.com/openstreetmap/openstreetmap-website/files/190435/logfile_vagrant.txt)

Were there some recent changes which are somehow not yet reflected for Vagrant set up?

**Comment by tomhughes** [comment]
Possibly - it's not something any of the core users use so it's not really maintained.

**Comment by mmd-osm** [comment]
I did the following changes to the provision.sh script, and the server seems to start up at least now. Unfortunately, I have no idea, if this is the right way to do it, ymmv.


```
diff --git a/script/vagrant/setup/provision.sh b/script/vagrant/setup/provision.sh
index 5699b53..769f0e8 100644
--- a/script/vagrant/setup/provision.sh
+++ b/script/vagrant/setup/provision.sh
@@ -17,11 +17,13 @@ apt-get install -y ruby2.0 libruby2.0 ruby2.0-dev \
                      libmagickwand-dev libxml2-dev libxslt1-dev nodejs \
                      apache2 apache2-threaded-dev build-essential git-core \
                      postgresql postgresql-contrib libpq-dev postgresql-server-dev-all \
-                     libsasl2-dev imagemagick
+                     libsasl2-dev imagemagick rbenv
 gem2.0 install bundler
 
 ## install the bundle necessary for openstreetmap-website
 pushd /srv/openstreetmap-website
+#
+rbenv rehash
 # do bundle install as a convenience
 sudo -u vagrant -H bundle install
 # create user and database for openstreetmap-website
@@ -49,5 +51,5 @@ if [ ! -f config/application.yml ]; then
                sudo -u vagrant cp config/example.application.yml config/application.yml
 fi
 # migrate the database to the latest version
-sudo -u vagrant rake db:migrate
+sudo -u vagrant bundle exec rake db:migrate
 popd


```

**Comment by tomhughes** [comment]
Well using `bundle exec rake` is certainly an obvious potential fix, but introducing `rbenv` into the equation adds a whole new layer of complication... Does it really need that as well?

Basically I would expect the fix to be either to install whatever apt has the system rake, or to use bundle exec to make sure we can find the gem installed one even if it's on some odd path.

**Comment by mmd-osm** [comment]
I appreciate your feedback, especially that we basically don't want to introduce `rbenv` as well as having `rake` as standalone binary. After a bit of more search through stackoverflow, I found a comment to do an `rm Gemfile.lock` first. This turned out to be pretty useful.

My updated instructions for [Installing Vagrant](https://github.com/openstreetmap/openstreetmap-website/blob/master/VAGRANT.md) would be as follows:

```
git clone git@github.com:openstreetmap/openstreetmap-website.git
cd openstreetmap-website
rm Gemfile.lock
vagrant up
```

Any other changes were not required anymore, in particular no need for `rbenv`.

Pretty awesome to have a rails server running in just a few minutes without much hassle!

**Comment by tomhughes** [comment]
Hang on, why are you closing this?

**Comment by tomhughes** [comment]
Removing `Gemfile.lock` is a very bad idea because it means you may wind up running a different set of modules to everybody else.

**Comment by tomhughes** [comment]
So the real problem is that the bundle install fails with:

```
Could not find jwt-1.5.3 in any of the sources
```

Which means that rake is never installed, along with all the other modules.

The reason is that jwt 1.5.3 appears to have been withdrawn for some reason.

**Comment by tomhughes** [comment]
This should be fixed by 414388f3b744e67ab30e9885e01de7c81e964d7d with 8fd70ff44ff9cebdbe491f641dbe6d62bb85c601 improving the error reporting by making it stop as soon as a command fails.

**Comment by mmd-osm** [comment]
Oh, sorry for closing the message too early. I thought this is merely a minor documentation issue and removing `Gemfile.lock` was a valid thing to do (which obviously isn't the case...). As I'm not that familiar with all the details, I was following the accepted answer given here: http://stackoverflow.com/questions/36216967/rails-installed-gem-version-and-gemfile-lock-version - which seems to be kind of not the right way to do. 

Thanks for the fix, I'll give the updated version a try tonight.

**Comment by mmd-osm** [comment]
Retest looks good :+1:
