### ISSUE TITLE
Please include map scale bar in downloaded images

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/openstreetmap-website#1195]
The download as image-function on the 'Share' sidebar would be much more useful if the map scale bar would get exported too.

**Comment by tomhughes** [comment]
That's extremely difficult I'm afraid, and also doesn't relate to any code in this repository as those images are rendered on the tile server by the same code that generates the map tiles.

The code in question is https://github.com/openstreetmap/chef/blob/master/cookbooks/tile/templates/default/export.erb and implementing this would require extending that to be able to overlay a scale and duplicating all the logic that is in the javascript on the main site (which itself is part of the Leaflet project, not our code) to figure out the scale details.
