### ISSUE TITLE
catch invalid URLs instead of just showing somewhere else

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1198]
Idea: If user browses e.g.,
http://www.openstreetmap.org/#map=18/24.18313,120.79612 instead of
http://www.openstreetmap.org/#map=18/24.18313/120.79612
then redirect the user to an error page, instead of just showing him what looks like a
legitimate map (of somewhere else! (based on previous browsing or default Europe, etc.)

That way he will not pass on such invalid URLs to his friends and friends of friends until one day somebody discovers it is showing somewhere else!

**Comment by mmd-osm** [comment]
TBH, I don't see the need for this. If you copy and paste the URL from the browser windows and send the URL to someone else, everything will be fine. I don't see where the invalid URL should come from in the first place. You're not manually trying to come up with these invalid urls, do you?

**Comment by jidanni** [comment]
Fine,
- https://www.openstreetmap.org/#map=18/24.18313,120.79612

resolves to
- https://www.openstreetmap.org/#map=12/24.1828/120.8653
- https://www.openstreetmap.org/#map=7/23.611/120.768
- etc.

Depending on
- use of a fresh incognito window
- cookies
- etc.

In conclusion, by always assuming valid input, a garbage in garbage out situation is created.  OSM can no longer be trusted because OSM assumes valid input without checking, and then goes on to process it further.

Yes you can cross your fingers and hope input is always valid, and cross your fingers again and expect that users will realize they have given invalid input and stop doing that.

But that usually works when users see right away that they aren't getting any results (except a big 404). But instead here we see seemingly correct results, that aren't correct. Also it may be a third party that introduces the error, not the user. E.g., a flawed Wikipedia template.

**Comment by mmd-osm** [comment]
Well, if third parties are trying to reverse engineer (or simply guess) our url format and get it wrong, it’s really their issue and they would be the ones to make it work properly.

**Comment by pnorman** [comment]
If someone invents random stuff to put into the URL that's their responsibility. If any part of the site generates a link with the format you mention, can you provide an example?

**Comment by jidanni** [comment]
It's like checking for incorrect six-digit PINs, without ever
considering the case of being given seven digits.

https://brightsec.com/blog/an-introduction-to-the-importance-of-input-validation-in-preventing-security-vulnerabilities/

Let's see what Google does.
- OK https://www.google.com/maps/search/?api=1&query=42.16613%2C-87.78237
- XX https://www.google.com/maps/search/?api=1&query=42.16613%2F-87.78237

> Google Maps can't find 42.16613/-87.78237
> Make sure your search is spelled correctly. Try adding a city, state, or zip code.
> [Try Google Search instead](https://www.google.com/search?q=42.16613/-87.78237&hl=en&authuser=0)

"Show me a ladder that high" is no excuse for not locking the window.

**Comment by mmd-osm** [comment]
If you look at the code I linked to above, you will notice that it in fact does input validation. The only thing you don't see is an error message. Invalid input is simply discarded silently, and that is what you see here.

**Comment by jidanni** [comment]
Well all that hard work of validation is thrown away.

https://www.openstreetmap.org/#map=barf
"works great".

When it should do like
https://www.openstreetmap.org/barf

**Comment by pnorman** [comment]
Not showing an error when an anchor is not found is standard.

Redirecting https://example.com/#foo to https://example.com/foo would be surprising to users and contrary to expectations.

But, as this is closed there's no real need to discuss this further.

**Comment by jidanni** [comment]
https://ux.stackexchange.com/questions/85451/when-invalid-querystring-paramater-detected-in-a-web-page-url-throw-an-error-or/85455#85455

**Comment by AntonKhorev** [comment]
https://github.com/openstreetmap/openstreetmap-website/issues/1198#issue-146475492 is about invalid fragments (after `#`)

https://github.com/openstreetmap/openstreetmap-website/issues/1198#issuecomment-2192796745 is about invalid query strings (after `?`)

**Comment by jidanni** [comment]
The point is as in the Ux.stackexchange article,
> I'm (generally) against silently ignored errors because error may go unnoticed and what user get won't be what he expects.

What exact part of the URL, and how to exactly deal with it are technical details.

The problem is half the time the results the OSM website shows the user look legitimate, when in fact they will create disasters later:

1. State Department personnel browse the Whitehouse.
2. State Department personnel copy the URL they see into their announcement.
3. State Department personnel double check their announcement being sure all links work, and indeed they do.

Hours later reports come in that
- "I clicked on your link to the Whitehouse, but instead got the burger place I looked up last week." 
- "I clicked on your link to the Whitehouse, but instead got a zoomed out map of my country."

Well it turns out State Department personnel had somehow messed up the link, but since OSM.org is so forgiving, everybody, including the State Department personnel just get "the next best link" in such cases, which is the last thing they were browsing. 

And what if it was a Friday, and one needed to wait till Monday until they could get into the office to fix it?

**Comment by AntonKhorev** [comment]
You ask for "redirect the user to an error page", which is a technical detail. Its typically not done for invalid fragments because a server doesn't see fragments. Client-side javascript code may do something in response to invalid map coordinates inside a fragment, but that probably won't be a redirect.

**Comment by jidanni** [comment]
Places to send the map when invalid coordinates are detected:

- North Pole
- South Pole
- https://en.wikipedia.org/wiki/Null_Island

But all might be mistaken for where the user really wanted to go.

Therefore indeed, a hard 404 would still be better.

**Comment by mmd-osm** [comment]
@jidanni  It would be good if we could stop the discussion now. You keep iterating the same points over and over, and it’s not adding any value.
