### ISSUE TITLE
Empty notes

### ISSUE THREAD

**Issue by the-knife** [openstreetmap/openstreetmap-website#1203]
Hello,

Since few weeks, some empty notes (without a single comment) have appeared :

Example :
http://www.openstreetmap.org/note/541817
http://api.openstreetmap.org/api/0.6/notes/541817

Obviously this is a bug, as nothing is possible with them, even closing is unavailable.

Here is a extensive list of the notes with this problem :

```
ID;LAT;LON;CREATED_AT
530962;0.0000000;0.0000000;2016-03-21T10:52:03Z
532469;0.0000000;0.0000000;2016-03-24T14:32:28Z
534201;34.9989651;135.7585824;2016-03-28T01:49:11Z
539440;0.0000000;0.0000000;2016-04-05T15:22:20Z
539655;0.0000000;0.0000000;2016-04-05T19:20:14Z
539917;0.0000000;0.0000000;2016-04-05T23:37:24Z
540110;0.0000000;0.0000000;2016-04-06T03:51:55Z
540823;0.0000000;0.0000000;2016-04-06T15:58:06Z
540877;0.0000000;0.0000000;2016-04-06T16:57:23Z
540956;0.0000000;0.0000000;2016-04-06T17:58:29Z
541096;0.0000000;0.0000000;2016-04-06T20:09:34Z
541817;0.0000000;0.0000000;2016-04-07T12:40:25Z
541822;0.0000000;0.0000000;2016-04-07T12:48:06Z
542182;0.0000000;0.0000000;2016-04-07T19:39:50Z
545213;0.0000000;0.0000000;2016-04-11T10:26:30Z
546110;0.0000000;0.0000000;2016-04-12T14:34:44Z
546403;0.0000000;0.0000000;2016-04-13T05:09:30Z
546500;0.0000000;0.0000000;2016-04-13T08:52:14Z
```

Regards,

the_knife

**Comment by DeeHants** [comment]
I have now closed most of these notes, but left 552726 open for debugging.

While the main website doesn't allow creation of these, the API does, and it looks like the page crashes when trying to get the author of the first comment and finds it doesn't exist (you'll see the one I closed above now says created by me).

http://www.openstreetmap.org/note/552726
http://api.openstreetmap.org/api/0.6/notes/552726

Note that a similar crash has just been fixed in [JOSM](https://josm.openstreetmap.de/ticket/12799).

**Comment by DeeHants** [comment]
As the crash still occurs in the website, can this be reopened please?

**Comment by zerebubuth** [comment]
Hi @DeeHants - this issue is open, although confusingly the referenced issue from the notes dump makes it look like it's closed.

**Comment by DeeHants** [comment]
@zerebubuth Yeah, I've just had that pointed out to me. Consider me duly larted :)

**Comment by the-knife** [comment]
Nice work @DeeHants.
(it seems you forgot note #534201)

**Comment by DeeHants** [comment]
Yeah, I ignored that, now deleted though.

**Comment by harry-wood** [comment]
Just came across one of these. http://www.openstreetmap.org/note/924499  What's the right fix do we think? Should the PUT of a note without any comments be disallowed by the API? a 400 bad request "At least one comment required"? and/or should the website view be fixed cope with viewing such a note?

**Comment by harry-wood** [comment]
Discussed on IRC today, @tomhughes did some peering in the databased and tracked down a validation error handling glitch. ...and fixed it : https://github.com/openstreetmap/openstreetmap-website/commit/7c9229fbfca70f65cc587129b18f1de4d993f9e2  So hopefully it's no longer possible to PUT a note with no comments.
