### ISSUE TITLE
If we used a Graphhopper API key, would routing db be updated faster (not using other features)

### ISSUE THREAD

**Issue by neiljp** [openstreetmap/openstreetmap-website#1206]
Just saw this:
https://graphhopper.com/#os-comparison
and wondered if having a key would enable a more frequently updated routing db via GH?

(TBC, I'm not suggesting using other features, which quite probably cost)

**Comment by mtmail** [comment]
Adding graphhopper maintainer @karussell

**Comment by karussell** [comment]
Openstreetmap already uses an API key, no one can access our API without a key. Currently the update frequency could be improved but for us this is just a hardware thing which is currently a bit too expensive, but not too far away in the future we'll work on this too.

**Comment by tomhughes** [comment]
Guess we can close this then.
