### ISSUE TITLE
Install libpgosm.so into pkglibdir of postgres

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/openstreetmap-website#1211]
The postgres shared library should be installed into the libdir of the postgresql server being used, as determined by `pg_config --pkglibdir`

**Comment by tomhughes** [comment]
Well I'd really rather avoid putting non-packaged software in /usr like that, but I'm going to see if there is some other alternative.

**Comment by pnorman** [comment]
I don't like it either. I suppose the real right way to do it is to bundle it up into an extension and package that, or alternately, just package the .so

**Comment by mmd-osm** [comment]
This issue is no longer relevant, we've removed db/functions/* and libpgosm.so in the meantime.
