### ISSUE TITLE
Tags containing 0x7f unicode control character 

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#1213]
Recently, [someone noticed strange unicode characters in some keys/values](http://forum.openstreetmap.org/viewtopic.php?pid=590901#p590901). It looks like this unicode control character 0x7f made it to the main database. Is `0x7f` a permitted control character, or did it simply slip through some validation checks?

As an example: http://www.openstreetmap.org/api/0.6/node/3188718399 - with 0x7f as first character for `phone`

I'm not sure if the main API would still accept 0x7f, or if this has been fixed at some point in the past already. Also, the question comes up how to deal with existing data in the database? Would a manual clean up be an option?

As the diff files don't contain any `0x7f` character, I guess a more recent planet would be required to identify relevant objects.

**Comment by tomhughes** [comment]
Well 0x7f is a valid unicode character - it's a control character but it's an entirely valid codepoint.

What you're probably really asking is whether it's valid in XML and I don't know the answer to that without checking. In any case it's not clear that we should let the fact that our API uses XML dictate what codepoints we allow, although I think there is precedent for doing so. I thought tags were one of the things we did filter though...

**Comment by tomhughes** [comment]
So 0x7f is valid in XML as well - https://www.w3.org/TR/xml/#charsets.

**Comment by pnorman** [comment]
Yep, it's valid so no one should have any problems consuming it, but the XML spec discourages their use, so it's probably part of a range we should filter out.

**Comment by tomhughes** [comment]
Please no, it's enough hassle already...

**Comment by mmd-osm** [comment]
We also took a look at the minutely diff file, which introduced the 0x7f characters for node 3188718399:

 `gunzip -c 929.osc.gz | grep "3188718399" -A 10 | hexdump -C`. 

Our conclusion was, that diff files don't include 0x7f anymore. Only the main API and most likely a planet dump seem to be the only places where they still occur.

```
00000000  20 20 20 20 3c 6e 6f 64  65 20 69 64 3d 22 33 31  |    <node id="31|
00000010  38 38 37 31 38 33 39 39  22 20 76 65 72 73 69 6f  |88718399" versio|
00000020  6e 3d 22 32 22 20 74 69  6d 65 73 74 61 6d 70 3d  |n="2" timestamp=|
00000030  22 32 30 31 35 2d 30 33  2d 32 39 54 31 38 3a 30  |"2015-03-29T18:0|
00000040  31 3a 30 34 5a 22 20 75  69 64 3d 22 33 37 31 37  |1:04Z" uid="3717|
00000050  31 31 22 20 75 73 65 72  3d 22 6b 6e 6f 63 6b 70  |11" user="knockp|
00000060  65 6e 6e 79 22 20 63 68  61 6e 67 65 73 65 74 3d  |enny" changeset=|
00000070  22 32 39 38 33 33 36 36  34 22 20 6c 61 74 3d 22  |"29833664" lat="|
00000080  35 30 2e 34 35 39 33 35  38 31 22 20 6c 6f 6e 3d  |50.4593581" lon=|
00000090  22 33 30 2e 34 34 37 30  31 33 34 22 3e 0a 20 20  |"30.4470134">.  |
000000a0  20 20 20 20 3c 74 61 67  20 6b 3d 22 61 6d 65 6e  |    <tag k="amen|
000000b0  69 74 79 22 20 76 3d 22  72 65 73 74 61 75 72 61  |ity" v="restaura|
000000c0  6e 74 22 2f 3e 0a 20 20  20 20 20 20 3c 74 61 67  |nt"/>.      <tag|
000000d0  20 6b 3d 22 65 6d 61 69  6c 22 20 76 3d 22 62 61  | k="email" v="ba|
000000e0  67 72 61 74 69 2e 6b 69  65 76 40 79 61 6e 64 65  |grati.kiev@yande|
000000f0  78 2e 72 75 22 2f 3e 0a  20 20 20 20 20 20 3c 74  |x.ru"/>.      <t|
00000100  61 67 20 6b 3d 22 6e 61  6d 65 22 20 76 3d 22 d0  |ag k="name" v=".|
00000110  91 d0 b0 d0 b3 d1 80 d0  b0 d1 82 d0 b8 22 2f 3e  |............."/>|
00000120  0a 20 20 20 20 20 20 3c  74 61 67 20 6b 3d 22 6e  |.      <tag k="n|
00000130  61 6d 65 3a 72 75 22 20  76 3d 22 d0 91 d0 b0 d0  |ame:ru" v=".....|
00000140  b3 d1 80 d0 b0 d1 82 d0  b8 22 2f 3e 0a 20 20 20  |........."/>.   |
00000150  20 20 20 3c 74 61 67 20  6b 3d 22 70 68 6f 6e 65  |   <tag k="phone|
00000160  22 20 76 3d 22 2b 33 38  20 28 30 34 34 29 20 34  |" v="+38 (044) 4|
00000170  35 36 2d 33 35 2d 35 35  3b 2b 33 38 20 28 30 39  |56-35-55;+38 (09|
00000180  38 29 20 37 35 37 2d 38  35 2d 38 35 22 2f 3e 0a  |8) 757-85-85"/>.|
00000190  20 20 20 20 20 20 3c 74  61 67 20 6b 3d 22 77 65  |      <tag k="we|
000001a0  62 73 69 74 65 22 20 76  3d 22 68 74 74 70 3a 2f  |bsite" v="http:/|
000001b0  2f 77 77 77 2e 62 61 67  72 61 74 69 2e 63 6f 6d  |/www.bagrati.com|
000001c0  2e 75 61 2f 22 2f 3e 0a  20 20 20 20 3c 2f 6e 6f  |.ua/"/>.    </no|
000001d0  64 65 3e 0a 20 20 3c 2f  6d 6f 64 69 66 79 3e 0a  |de>.  </modify>.|
000001e0  20 20 3c 64 65 6c 65 74  65 3e 0a 20 20 20 20 3c  |  <delete>.    <|
000001f0  6e 6f 64 65 20 69 64 3d  22 33 31 38 38 37 35 32  |node id="3188752|
00000200  39 30 39 22 20 76 65 72  73 69 6f 6e 3d 22 32 22  |909" version="2"|
00000210  20 74 69 6d 65 73 74 61  6d 70 3d 22 32 30 31 35  | timestamp="2015|
00000220  2d 30 33 2d 32 39 54 31  35 3a 34 35 3a 31 38 5a  |-03-29T15:45:18Z|
00000230  22 20 75 69 64 3d 22 31  34 37 36 31 34 36 22 20  |" uid="1476146" |
00000240  75 73 65 72 3d 22 41 6c  65 63 73 30 31 22 20 63  |user="Alecs01" c|
00000250  68 61 6e 67 65 73 65 74  3d 22 32 39 38 32 37 37  |hangeset="298277|
00000260  33 36 22 20 6c 61 74 3d  22 34 35 2e 39 30 32 32  |36" lat="45.9022|
00000270  31 31 34 22 20 6c 6f 6e  3d 22 38 2e 37 31 36 35  |114" lon="8.7165|
00000280  36 34 32 22 2f 3e 0a                              |642"/>.|
```

**Comment by tomhughes** [comment]
Well you'd have to ask @brettch why osmosis has elided it... Though it might just be java being silly ;-)

**Comment by mmd-osm** [comment]
I found the following snipped in the [osmosis sources](https://github.com/openstreetmap/osmosis/blob/e5d77d4c29436b458a900d509af5a01edfe88aac/osmosis-xml/src/main/java/org/openstreetmap/osmosis/xml/common/ElementWriter.java#L41):

```Java
XML_ENCODING.put(new Character((char) 0x7F), "");
```

I guess the purpose is to replace `0x7f` by an empty string, e.g. a deliberate decision to suppress `0x7f` at least for XML output. That also explains why we can't query for `0x7f` in Overpass API - it's just not in the diff file.

**Comment by brettch** [comment]
I can't recall the thinking behind this, but it was probably me.  I'll need to dig through the git history to see if there's any clue in the commit comment(s).  Git blame isn't helping, it appears to be getting confused by file renames.

**Comment by mmd-osm** [comment]
@brettch : it looks like the check was first introduced here in osmosis: https://github.com/openstreetmap/osmosis/commit/89b1c133195527d00b6a112da02227b333f4524a?diff=unified

**Comment by mueschel** [comment]
According to Taginfo, many new keys with this error appeared on June 10th. I would appreciate if these characters could be removed from the database because the information contained in these keys is currently not accessible for most applications.

**Comment by SomeoneElseOSM** [comment]
@mueschel Regardless of the whether the database should or should not store it, if you think someone's added it to OSM by mistake then at the very least I'd talk to the person who added it (e.g. via a changeset discussion) - assuming of course it's really in there and not some kind of artifact of the processing that creates the taginfo data.

**Comment by mueschel** [comment]
The only way to find the objects is by digging through the planet file with 700 GB of uncompressed xml data. @mmd-osm did this in May: http://dev.overpass-api.de/tmp/psv/0x7f_analysis

**Comment by mmd-osm** [comment]
@SomeoneElseOSM: this affects many different users and changesets. Using changeset discussion does not seem feasible to me. In most cases people probably have absolutely no idea, what the issue might be and why/how they should fix it. Also, over time more and more entries will be created.

On the other hand, it's impossible to find those cases via Overpass API, as the minutely diff don't contain that character - osmosis simply filtered this stuff out, so they never appear in downstream systems. Only a planet file contains the 0x7f. However, no ordinary user is going to download a planet to go and fix them.

**Comment by SomeoneElseOSM** [comment]
@mueschel I don't understand the "According to Taginfo, many new keys with this error appeared on June 10th" above?  That would suggest that it's possible to get some information on (or at least examples of) the problem without reverting to the full planet file.  I'm not sure what encoding the dev link is supposed to be (I'm guessing just ascii - it doesn't seem to be UTF-8).  At least one of the 0x7Fs in there ( http://www.openstreetmap.org/node/96305028 ) seems to be valid UTF-8 on the browse page.

**Comment by mmd-osm** [comment]
@SomeoneElseOSM : 
- The encoding in the dev file represents 0x7f as a single byte. Just open it in firefox. I used a patched osmconvert version to create it.

- AFAIK, Jochen uses a planet file once in a while to initialize Taginfo database. (@joto.)

**Comment by joto** [comment]
@mmd-osm I reinitialized the taginfo planet a few days ago from a planet I had on a different server updated for a months or so. I did this because of some complaints of corrupt data which tends to happen when replication diffs are broken (as happend multiple times in the last months.) This might or might not have triggered the sudden appearance of these tags in taginfo.

**Comment by mmd-osm** [comment]
Someone seems to take care of those 0x7f chars and manually removes them: https://www.openstreetmap.org/user/Aleks-Berlin

Closing here.

**Comment by mmd-osm** [comment]
Fast forward a few years, we're no longer using osmosis for minutely diffs, and the new method doesn't filter 0x7f anymore. Any Overpass instance running on minutely diffs can easily identify these objects now using `nwr[~"."~"\\x7f"];out ids;` 

At the time of writing this, I could find one node, 55 ways, and 7 relations. It seems that nobody is currently fixing those, the oldest object dates back to April 2021. I guess that's ok given the fairly low object count.
