### ISSUE TITLE
When looking at a hidden note, you can't then navigate to another note.

### ISSUE THREAD

**Issue by DeeHants** [openstreetmap/openstreetmap-website#1215]
After I've [hidden a note](http://www.openstreetmap.org/note/506777), I can't then navigate to any other notes by clicking on them.
I'm a member of the DWG so this may differ for people without moderator access.

Using IE11 on Windows 7.

**Comment by harry-wood** [comment]
people without moderator access (like me) can't see hidden notes. We just see _"Sorry, #506777 could not be found"_. So I guess that makes this a lower priority issue
