### ISSUE TITLE
Disable Editing when Editing is Disabled

### ISSUE THREAD

**Issue by talllguy** [openstreetmap/openstreetmap-website#1217]
Just an idea here. When there are issues that prevent edits from occurring, consider disabling (graying out) the `Edit` button.
![2016-05-09 11_18_39-openstreetmap](https://cloud.githubusercontent.com/assets/1827881/15117926/e820fe78-15d7-11e6-8140-dcd7210fc3d5.png)

**Comment by HolgerJeromin** [comment]
Is is possible (but can lead to more conflicts) to load data in an Editor and upload later.

**Comment by mmd-osm** [comment]
Can we close this? Read only database only implies that you can’t upload any changes to the map. You can still open the editor without uploading changes.

**Comment by mmd-osm** [comment]
Closing, please see previous comment...
