### ISSUE TITLE
How to make browser url with coordinates like Openstreetmap

### ISSUE THREAD

**Issue by marie15** [openstreetmap/openstreetmap-website#1218]
Hi everybody, I want  to create an URL like openstreetmap which contain my application domain and latitude and longitude of map center. Do you have any idea how to do that with javascript or AngularJS?
Thankx for advance

**Comment by tomhughes** [comment]
This is not an issue with our code.

Please try https://help.openstreetmap.org/ for help on using OpenStreetMap in your own web site.

**Comment by marie15** [comment]
Oki thankx
