### ISSUE TITLE
User block detail page does not have user ID

### ISSUE THREAD

**Issue by bkowshik** [openstreetmap/openstreetmap-website#1222]
A user can change the `display_name` over time but the `user id` remains the same. The [user block detail page](http://www.openstreetmap.org/user_blocks/1) does not contain the `user id`.

**Comment by tomhughes** [comment]
User IDs are, for the most part, an internal implementation detail that is not normally exposed and especially not on the web site (as opposed to the API).

There has occasionally been talk of introducing an unchangeable username of some sort to avoid the problems with URLs change when the display name has changed.

**Comment by bkowshik** [comment]
Thank you @tomhughes I will follow updates on unchangeable usernames.

As per discussion on the [PR](https://github.com/openstreetmap/openstreetmap-website/pull/1223), no further actions here.
Closing.
