### ISSUE TITLE
Mobile sign up not working

### ISSUE THREAD

**Issue by Turnit-On** [openstreetmap/openstreetmap-website#1227]
hello I have an issue here when I and people try to sign up in my community using via mobile it does not take me/them to another stage but instead the mobile sign up form keep on popping up again and again. please help me to resolve this issue.
Thank you

**Comment by tomhughes** [comment]
Well I'm not sure what you expect me to say - there is nothing in that report that would allow me to reproduce the problem.

At the end of the day the mobile signup is just the same web pages as the desktop signup - the style sheet just changes as the screen gets smaller. So if it works in your web browser and not on your mobile device then it is most likely a problem with the way your device is interacting with it and only you can debug that.

Are you actually launching a proper web browser on the device? or embedding some sort of web control in your application? What mobile OS is it - Android? iOS? Windows?

**Comment by gravitystorm** [comment]
I'm going to close this since we haven't heard back from the original reporter, and there have been no other reports since to indicate that it's a common problem. If anyone has any details about similar problems, please open a new issue.
