### ISSUE TITLE
French translation for leisure/slipway is confusing

### ISSUE THREAD

**Issue by fab-girard** [openstreetmap/openstreetmap-website#1230]
Hello,
slipway is translated in french "Plan incliné" in `vendor/assets/iD/iD/locales/fr.json`.
http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dslipway
Contributors use this tag for "rampe d'accès pour fauteuil roulant" (correct tag is wheelchair=yes in this case) or when road is just sloping.

To avoid errors, I suggest the translation "Mise à l'eau". The json could be in this case : 
```
"leisure/slipway": {
  "name": "Mise à l'eau",
  "terms": "Cale de lancement, Cale, Cale de mise à l'eau, Rampe, Rampe de mise à l'eau"
}
```

Fab

**Comment by tomhughes** [comment]
Issues in iD need to be reported upstream at https://github.com/openstreetmap/iD/issues.

**Comment by fab-girard** [comment]
Thanks, sorry for this !
