### ISSUE TITLE
Add OpenID support for the wiki

### ISSUE THREAD

**Issue by strk** [openstreetmap/openstreetmap-website#1232]
I was very happy to find OpenID support on the main website, but the wiki site (wiki.openstreetmap.org) still only supporte user/password (and different credentials from the ones of the main site).

This ticket is to equest enabling OpenID for the wiki too.

An extension exists for that: https://www.mediawiki.org/wiki/Extension:OpenID

**Comment by tomhughes** [comment]
This tracker is for www.openstreetmap.org not wiki.openstreetmap.org. Wiki requests are probably best filed against the wiki component in trac.

**Comment by strk** [comment]
and trac url is ?

**Comment by strk** [comment]
If it is https://trac.openstreetmap.org/, how do I register an account to use there ?

**Comment by tomhughes** [comment]
It uses OSM accounts.

**Comment by strk** [comment]
Thanks, done: https://trac.openstreetmap.org/ticket/5404
