### ISSUE TITLE
Location issue on Edge

### ISSUE THREAD

**Issue by nikhilnayak98** [openstreetmap/openstreetmap-website#1235]
Show my location not clickable on Microsoft edge browser.

**Comment by mmd-osm** [comment]
I tried this on a recent Edge browser on Win10, and cannot reproduce it. The button is clearly visible, once I click on it, it will take me to my current location, privacy settings permitting.

I'd suggest to close this issue as not reproducible.

**Comment by gravitystorm** [comment]
Thanks for testing @mmd-osm !
