### ISSUE TITLE
Allow embedding .gifv files in diary entries

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#1236]
Unfortunately, unlike many other image types embedding .gifv fails. Direct links are working.

Example of .gifv file where embedding in diary entry is reasonable: http://i.imgur.com/r5UoTs1.gifv (how rendering on z14 changed over time in openstreetmap-carto).

**Comment by pnorman** [comment]
What you've linked isn't an image, but a HTML page which plays the movie http://i.imgur.com/r5UoTs1.webm (or .mp4 as a fallback)

**Comment by tomhughes** [comment]
What on earth is a `gifv` anyway... But in any case I don't believe we have any custom restrictions in place, we just use a standard markdown rendering library so any limitations are either in markdown or in that library and are outside our control.

**Comment by tomhughes** [comment]
As @pnorman says that "gifv" is just an HTML page that wraps a flash app around a normal animated gif. The purpose of that is entirely unclear, but http://i.imgur.com/r5UoTs1.gif is the underlying GIF so why not just use that instead?

**Comment by matkoniecz** [comment]
> is the underlying GIF so why not just use that instead?

Thanks! And sorry for spurious bug report.
