### ISSUE TITLE
missing image on 404 page

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#1241]
404 page is 

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html>
<body>
  <img src="/assets/osm_logo.png" style="float:left; margin:10px">
  <div style="float:left;">
    <h1>File not found</h1>  
    <p>Couldn't find a file/directory/API operation by that name on the OpenStreetMap server (HTTP 404)</p>
    <p>Feel free to <a href="http://wiki.openstreetmap.org/wiki/Contact" title="Various contact channels explained">contact</a> the OpenStreetMap community if you have found a broken link / bug. Make a note of the exact URL of your request.</p>
  </div>
</body>
</html>
```

But /assets/osm_logo.png is not available for 404 page, what results in a broken image symbol

See for example https://www.openstreetmap.org/assets/osm_logo.png 

Note that this image exists at https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/images/osm_logo.png

![selection_005](https://cloud.githubusercontent.com/assets/899988/16260748/079e9888-3869-11e6-9493-e91226ae275a.png)

**Comment by grischard** [comment]
This seems to have been resolved. https://www.openstreetmap.org/40404 shows the error page with the image. Can you still reproduce the problem? If yes, can you please include steps to reproduce?

**Comment by tomhughes** [comment]
Well it's still wrong really - it should be using a proper asset pathed image.

**Comment by bennett-elder-gs** [comment]
http://www.openstreetmap.org/assets/osm_logo.png loads the image and http://www.openstreetmap.org/assets/images/osm_logo.png does not so that would seem to suggest that this is fixed. I see osm_logo.png in an asset path and I believe it's being used correctly.

**Comment by tomhughes** [comment]
Well neither of those is a proper asset path - a proper path would include a checksum.
