### ISSUE TITLE
Display that a changeset is still open, and the time at which it will close automatically

### ISSUE THREAD

**Issue by polarbearing** [openstreetmap/openstreetmap-website#1243]
There are regularly reports when people try to discuss a changeset that is still open, see #845,  #1134, #1184, #1242, to some degree #639, #631.

Thus I suggest to add a line to the changeset (somewhere near the discussion button) that it is indeed still open, and comments are not possible yet. 

In addition, the expected timeout for auto-close could be shown.

**Comment by mmd-osm** [comment]
This issue can be closed, additional hint for the user was added in #1705.
