### ISSUE TITLE
replying to osm message failed

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/openstreetmap-website#1246]
I just got a reply back as undeliverable after I replied to a message (email):

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  m-575584-aeefb0@messages.openstreetmap.org

The following text was generated during the delivery attempt:

------ m-575584-aeefb0@messages.openstreetmap.org ------

WARNING: Nokogiri was built against LibXML version 2.9.1, but has dynamically loaded 2.9.3

Action: failed
Final-Recipient: rfc822;m-575584-aeefb0@messages.openstreetmap.org
Status: 5.0.0

(here follows the message)

**Comment by tomhughes** [comment]
Operational issue, not a web site bug as such.

**Comment by tomhughes** [comment]
Should be fixed now.
