### ISSUE TITLE
Map jumps after left sidebar is closed

### ISSUE THREAD

**Issue by strump** [openstreetmap/openstreetmap-website#1255]
Steps to reproduce:
1. Open link https://www.openstreetmap.org/way/140950703
2. Drag the map (this is important!)
3. Close left sidebar
4. Drag the map:

**Actual result:** map jumps to the left when you start dragging;
**Expected result:** map is dragged normally.

![osm_sidebar_bug](https://cloud.githubusercontent.com/assets/720808/16985493/77f3f2aa-4e89-11e6-991f-8351b9442726.gif)

I found two workarounds:
### Workaround 1:

In [leaflet.map.js line #263](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/javascripts/leaflet.map.js#L263) put `animate:true`. I don't know why, but it helps.
### Workaround 2:

In [leaflet.js line #8664](https://github.com/openstreetmap/openstreetmap-website/blob/master/vendor/assets/leaflet/leaflet.js#L8664)
remove assignment `this._el._leaflet_pos = this._newPos`. For some reason, this could help.

**Comment by tomhughes** [comment]
There are many, many tickets already for this. If anybody knew of  way to fi it that didn't break three other things it would have been done :-(

**Comment by strump** [comment]
Sorry, didn't find issue with this bug.
Is it caused by pan animation?

**Comment by SomeoneElseOSM** [comment]
A number of the previous issues are mentioned on https://github.com/openstreetmap/openstreetmap-website/issues/857 (the top issue search result for "jump").

**Comment by strump** [comment]
Looks like this issue is not relevant anymore.
Closing!
