### ISSUE TITLE
Sign in to OSM with Google account for mobile

### ISSUE THREAD

**Issue by tommybuonomo** [openstreetmap/openstreetmap-website#1256]
Hello,

I'm a developer for the [OSM Contributor](https://wiki.openstreetmap.org/wiki/OSM_Contributor) App.

I try to log the users to OpenStreetMap using OpenID, and more particulary using their google account. I've already done the half of the work using this request: 
```
https://accounts.google.com/o/oauth2/v2/auth?
response_type=code&
client_id=651529786092-6c5ahcu0tpp95emiec8uibg11asmk34t.apps.googleusercontent.com&
redirect_uri=https://www.openstreetmap.org/auth/google/callback&
scope=openid email&
login_hint=tommy.buonomo@gmail.com&
state=f6fb251c967d4563abee68751ea973c44f5a7d5672fce452
```

After that, i'm logged and I get the `OSM.oauth_token`, 
`OSM.oauth_token_secret`, 
`OSM.oauth_consumer_key`, 
`OSM.oauth_consumer_secret`,
 but I can't ask for the access token without the `oauth_verifier` parameter, which is not in the callback response.

Therefore, there is no API currently for this kind of authentification.

Thank you,

Tommy Buonomo.

**Comment by tomhughes** [comment]
I'm confused - you say you're using OpenID but google no longer support OpenID and indeed the URL you quote appears to be using google's OAuth 2 authentication API instead.

I'm not sure what any of that has to do with our OAuth implementation though - that is completely separate. Are you saying that you are trying to mechanically log the user in via their google account and then authorise yourself to use our API as them by getting an OAuth token? If so then I hope you are allowing them to authorise that on our web site and not trying to do that automatically?

Everything you need to get an access token is available anyway, or nobody would be able to use OAuth and lots of applications do!

The best thing is probably to look at our tests (https://github.com/openstreetmap/openstreetmap-website/blob/master/test/integration/oauth_test.rb) which should be thoroughly testing all the supported OAuth flows and will show you what sequence of calls to make and parameters to provide.
