### ISSUE TITLE
Annoying banners

### ISSUE THREAD

**Issue by nebulon42** [openstreetmap/openstreetmap-website#1260]
The recently added banners (#1240) sometimes really annoy me. While I think it is worthwhile to present information, those are too big and since they are obscuring a significant portion of the map I have to click to get rid of them. It is hard to simply ignore them. Since there are many (e.g. SOTM, SOTM Asia...) I have to click repeatedly. So I was forced to add those to my ad blocker.

Please consider either:
* significantly reducing them in height
* adding a user option to permanently disable them

**Comment by tomhughes** [comment]
Seriously, it's one click per banner, so a total of four clicks so far and that click is remembered in a cookie so you never have to see that banner again.

Adding a permanent disable option would obviously completely defeat the object.

About the only thing I can agree with is that they're probably a bit big but I'm mostly limited by what the conference organisers provide on that front. We're pretty much done for this year I think but next year I'll try and get people to tone them down a bit.
