### ISSUE TITLE
Directions error: router.project-osrm.org returns 504

### ISSUE THREAD

**Issue by mikini** [openstreetmap/openstreetmap-website#1263]
The directions functionality on the main map is broken.

Inputting a starting (Esbjerg, Denmark) and destination (Copenhagen, Denmark) point will load  http://www.openstreetmap.org/directions?engine=osrm_car&route=55.466%2C8.452%3B55.687%2C12.570 which result in a routing error: "Couldn't find a route between those two places." message, and in the browser console I see a  error;

Firefox 47.0 (Ubuntu 15.10):
> 17:34:47.325 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://router.project-osrm.org/route/v1/driving/8.452,55.466;12.57,55.687?overview=false&geometries=polyline&steps=true. (Reason: CORS header 'Access-Control-Allow-Origin' missing).1 (unknown)

Chromium 51.0.2704.79 (Ubuntu 15.10):
> http://router.project-osrm.org/route/v1/driving/8.452,55.466;12.57,55.687?overview=false&geometries=polyline&steps=true Failed to load resource: the server responded with a status of 504 (GATEWAY_TIMEOUT)
> XMLHttpRequest cannot load http://router.project-osrm.org/route/v1/driving/8.452,55.466;12.57,55.687?overview=false&geometries=polyline&steps=true. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.openstreetmap.org' is therefore not allowed access. The response had HTTP status code 504.

Internet Explorer 11.0.9600.18376 (Windows Server 2008 R2 Standard)
>SEC7120: Origin http://www.openstreetmap.org not found in Access-Control-Allow-Origin header.
>File: directions
>SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.
>File: directions

A manual request however shows, as Chromium is aware, that the router.project-osrm.org API returns status code 504:

> $ wget -S -O- "http://router.project-osrm.org/route/v1/driving/8.452,55.466;12.57,55.687?overview=false&geometries=polyline&steps=true"
--2016-08-08 17:52:51--  http://router.project-osrm.org/route/v1/driving/8.452,55.466;12.57,55.687?overview=false&geometries=polyline&steps=true
Resolving router.project-osrm.org (router.project-osrm.org)... 52.21.213.38
Connecting to router.project-osrm.org (router.project-osrm.org)|52.21.213.38|:80... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 504 GATEWAY_TIMEOUT
  Date: Mon, 08 Aug 2016 15:53:06 GMT
  Server: nginx/1.4.6 (Ubuntu)
  Content-Length: 0
  Connection: keep-alive
Retrying.
....

**Comment by tomhughes** [comment]
Well you need to report that to OSRM really, not us - we have no control over their server.

**Comment by mikini** [comment]
Thought that somebody here might care that functionality us broken and have the right contacts at OSRM to ping.

To me as as a somewhat stranger to OSM operations and the OSRM project it smells like this is connected to the changes of #1261. And/or might be preparations of the shutdown of OSRM 4.9 API announced in https://lists.openstreetmap.org/pipermail/osrm-talk/2016-August/001275.html that impacts 5.x production?

I'll try to find the right OSRM place to report it.

**Comment by mikini** [comment]
I see that router.project-osrm.org is returning results again.

I'm daring to think and ask why a prominent feature as directions on the frontpage of openstreetmap.org is using a "14 days+ breakage intended" demo server from OSRM? 

The fact that router.project-osrm.org is a demo service is being emphasized by OSRM in the follow ups to these issues reported by OSRM users:
https://github.com/Project-OSRM/osrm-frontend/issues/180
https://github.com/Project-OSRM/osrm-backend/issues/2698
https://github.com/Project-OSRM/osrm-backend/issues/2706

Wouldn't it be an idea to put a "beta", "demo" or "not a core OSM service" note on the routing tab if this is how it is regarded? At least when the API is down?

For interested parties, the latter of the above OSRM issues is the one that tracks the actual trigger for the current breakage; a problem in u-turn handling discovered by a [changeset in the wild from Egypt](http://www.openstreetmap.org/changeset/40938983#map=14/31.1423/29.8277).
It has been fixed in https://github.com/Project-OSRM/osrm-backend/pull/2720 and more work done in https://github.com/Project-OSRM/osrm-backend/issues/2730.

**Comment by simonpoole** [comment]
@mikini while most of the things on openstreetmap.org work smoothly nearly all of the time, there are no claims nor expectations that any of the services, with the exception of the editing API, it serves as a conduit to are for production use for end users. This is just as true for third party services show cased on openstreetmap.org as for services run by our volunteers.

The situation is a consequence of OSMs business model which leaves end user services to commercial and non-commercial third parties.
