### ISSUE TITLE
500 error on github login possible

### ISSUE THREAD

**Issue by pointhi** [openstreetmap/openstreetmap-website#1265]
## HowTo reproduce:

1.) register osm account with some email address.
2.) register another osm account using github (which points to another email address)
3.) add email address of first osm account to github
4.) try to login via github

**Comment by tomhughes** [comment]
I don't see how this can affect anything - the only time we pay any attention to the email returned by github is to populate the email form when creating a new account. We don't use it at all for login.

You're sure the 500 was from us rather than github I assume? Do you have a timestamp? Only I don't really want to have to do all that to reproduce it so it would be easier if I can find the exception in our logs.

**Comment by pointhi** [comment]
The log should be visible in the time range between 2016-08-13 09:35 - 2016-08-13 09:56 UTC.
The ip should be something like 88.116.***.***

**Comment by tomhughes** [comment]
Think I've found it and this is the trace:

```
NoMethodError
undefined method `auth_provider=' for nil:NilClass
/srv/www.openstreetmap.org/rails/app/controllers/user_controller.rb:524:in `auth_success'
```

Which looks like it was following the path for attaching a new external login for a user which doesn't seem to match your description.

Did you try and change the external auth method for your original user at some point?

**Comment by pointhi** [comment]
Yes, I tried for my official user to enable github auth at the beginning, because I though there would pop up some window where I can link the account.

**Comment by tomhughes** [comment]
Well that's exactly what should have happened - when you select github in the settings page and hit save it should send you to github to authenticate and then link that to the account.

It looks like you started that but never completed it and the details were still stored in your session and it then tried to use them when you weren't logged in yet which caused the 500 error.

**Comment by tomhughes** [comment]
Ah did you try and do that after creating the other account? So you tried to attach github auth to an account while there was already another account linked to that github account?

**Comment by pointhi** [comment]
Hm, either I overlooked the github register page on the first try, or It didn't displayed at first place. (there was an email mismatch between osm and github, but I think that should be no problem).
