### ISSUE TITLE
allow deletion of new (blank) osm accounts

### ISSUE THREAD

**Issue by pointhi** [openstreetmap/openstreetmap-website#1266]
When someone registers an osm account, and didn't do any actions on it except register it. Deletion of the account should be possible without writing an email to support. There is no need for it, because the user didn't contributed to the project in any way yet.

This would be especially helpful for people which registered an account by accident.

**Comment by tomhughes** [comment]
Currently our policy is to to require people to email. One thing it does is to allow me to track the kinds of reasons why people want to close accounts and the rate at which they do so.

**Comment by zerebubuth** [comment]
Would it be possible to have a "self-service" which includes a drop-down and/or text box for the reason and enqueues an email containing that data?

I'm just thinking that it would streamline the service, and take out a point of manual intervention. Hopefully the information content would be the same.

On a side note - are we keeping a record of the reasons why people request deletion? Is that published anywhere?

**Comment by pointhi** [comment]
What I found out is, that deleted OSM accounts keep the email address locked, which means you cannot move your current account to this email address (email already taken)

**Comment by tomhughes** [comment]
We probably are reaching the point where we may want to allow self service I agree, as the person who deals with the requests that's mostly down to when I get bored enough of doing them manually to implement something.

We don't keep any formal record, it's more just that if somebody makes a comment then I may use that to tweak something.

Where people do comment the most common seems to be that it "wasn't what they expected" or that they thought they needed to register to do something (other than edit) that we either don't provide or which doesn't need registration.
