### ISSUE TITLE
"OpenStreetMap" got translated in Polish locale

### ISSUE THREAD

**Issue by Teiron** [openstreetmap/openstreetmap-website#1269]
In [this commit](https://github.com/openstreetmap/openstreetmap-website/commit/116766239d6dbb8956233415a70e44a0033b0f17#diff-9dd965712449996048bac1647804859e) string "OpenStreetMap" got translated into "Otwarta Mapa Drogowa" probably by overzealous translator.

Can anything be done about it?

![2016-08-15 22_02_04-_otwarta mapa drogowa_](https://cloud.githubusercontent.com/assets/12804636/17677649/0e992fa4-6334-11e6-9469-7316f8e0445f.png)

**Comment by tomhughes** [comment]
Sure, you can go to Translatewiki and fix it ;-) See http://wiki.openstreetmap.org/wiki/Website_internationalization#How_to_translate for details.

**Comment by tomhughes** [comment]
You might want to check other recent changes BTW as they also changed "ltr" into a polish explanation of left-to-right text which would have broken things if I hadn't caught it.

**Comment by Teiron** [comment]
Is there any place except standard TranslateWiki page where it could have been translated? I don't see any reference to this issue there.

**Comment by tomhughes** [comment]
What do you mean by a reference to the issue? All that will have happened is that somebody will have logged in and made a change to the translation.

**Comment by tomhughes** [comment]
Maybe somebody has already fixed it? It's the layout.project_name.title key.

**Comment by kocio-pl** [comment]
I guess it was already reverted - TranslateWiki interface is not helpful, but at least I can't find the translated name. Could you test it and deploy?

**Comment by Nikerabbit** [comment]
https://translatewiki.net/w/i.php?title=Osm:Html.dir/pl&diff=6955508&oldid=6953000&rcid=10777320&curid=4837294

https://translatewiki.net/w/i.php?namespace=1222&tagfilter=&translations=only&users=&trailer=%2Fpl&hidebots=&title=Special%3ARecentChanges

**Comment by kocio-pl** [comment]
Wow, that's really horrible UI!...

It looks like it's been really reverted:

https://translatewiki.net/w/i.php?title=Osm%3ALayouts.project_name.title%2Fpl&type=revision&diff=6955639&oldid=6953006
https://translatewiki.net/w/i.php?title=Osm%3ALayouts.project_name.h1%2Fpl&type=revision&diff=6955638&oldid=6953007

**Comment by Nikerabbit** [comment]
The main UI is at https://translatewiki.net/w/i.php?title=Special:Translate&group=out-osm-site&language=pl&filter=%21translated&action=translate

If you have specific feedback I am happy to hear but I cannot promise it will be solved quickly.

Also, next translation push from me is planned for Thursday morning (UTC).

**Comment by kocio-pl** [comment]
I know the main interface, it looks nice, but it's slow when tying to search strings and I was surprised that I could not find the history of changes (I'm along time Wikipedia editor). These usability problems may be hard to fix.

Please make that push ASAP, because it's annoying for polish community. However If that means Thursday morning anyway, I can live with that.

**Comment by Nikerabbit** [comment]
Did you try the advanced search that goes to Special:SearchTranslations? That should be fast. Also, you can access history by opening the message and clicking it's name to open dropdown with link to history.

I can push earlier but I don't know if it actually helps. What is your process of applying the new translations after a push?

**Comment by tomhughes** [comment]
@Nikerabbit I just run the tests and if they pass then I push the live tag and it will go live over the next half hour.

**Comment by kocio-pl** [comment]
@Nikerabbit These are exactly UI problem for me (not missing functionality or something like this) - it works fast, but you had to tell me about this page and I still couldn't find the history even following your hint. But as I said - these are probably hard things to fix and they don't belong to this issue anyway.

**Comment by Nikerabbit** [comment]
I made an additional push now.

**Comment by kocio-pl** [comment]
Thank you, the issue is resolved now.
