### ISSUE TITLE
Sprockers method register_engine is deprecated

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/openstreetmap-website#1275]
When starting, rails server writes:
```
Sprockers method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
(called from block in config/initializers/r2.rb:22)
```
It also shows this link: https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#registering-all-versions-of-sprockets-in-processors

**Comment by tomhughes** [comment]
I believe this comes from one of the gems and is outside out control.

**Comment by tomhughes** [comment]
Hmm or it could be the r2 initialiser. I never see it though so I wonder if you have updated your bundle or something?

**Comment by tomhughes** [comment]
So it is r2 but neither "rails s" or "rails c" reports that for me so I can only assume you have updated your bundle and are therefore in an unsupported configuration.
