### ISSUE TITLE
Public transportation integration

### ISSUE THREAD

**Issue by paskalito** [openstreetmap/openstreetmap-website#1276]
Hi

im not sure if this is the right place, 'causse theres loadas of very ol issues and stuff. but - i thought it would be awesome if osm.org and https://github.com/grote/Transportr would join forces and integrate the knowledge about public transport systems around the world into the main osm website. (so you just could choose public transport (transpotr) in the dropdown menu )
- it bothers me that i still have to use google for that... ;(

**Comment by tomhughes** [comment]
That's really outside the scope - our goal is not to provide an "end user" site like google maps but rather to support editing of our data set.
