### ISSUE TITLE
Stats page error

### ISSUE THREAD

**Issue by yogiks** [openstreetmap/openstreetmap-website#1278]
[Database statistics page](https://www.openstreetmap.org/stats/data_stats.html) tells - _Exception: could not connect to server: No route to host Is the server running on host "katla.bm.openstreetmap.org" (10.0.32.40) and accepting TCP/IP connections on port 5432?_

Full error screenshot below - 

![error](https://cloud.githubusercontent.com/assets/6291913/18314321/426b002e-7530-11e6-9526-f918066c7bee.png)

**Comment by tomhughes** [comment]
Operational issue, nothing to do with the code here.

**Comment by tomhughes** [comment]
I suspect there was a temporary glitch at the point when this ran last night - it seems to be fine now so should run correctly tonight.
