### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by edpop** [openstreetmap/openstreetmap-website#1281]
Hello.

I have my own osm-website (website+cgimap+iD, 16 RAM) and I get a lot of 500's on saving.
I see tag "live" made 2 years ago, is it obsolete? There is a "mirror" in project description, but you push commits here.
I trying to understand, which version is stable. Please, tell me.

Thank you.

**Comment by tomhughes** [comment]
This question would be more appropriate on the mailing list really, given that it doesn't relate to a problem with our code but rather to your deployment of our code.

The code we run in production is the `live` tag at https://git.openstreetmap.org/rails.git and this repo is a copy of that repo for ease of development. The live tag here is probably just a copy of the one in the primary repo when this mirror was created.
