### ISSUE TITLE
Lots of event banners for State of the Map

### ISSUE THREAD

**Issue by jancborchardt** [openstreetmap/openstreetmap-website#1286]
This just happened to me when going to OpenStreetmap.org on a new browser:
![capture du 2016-09-14 15-45-58](https://cloud.githubusercontent.com/assets/925062/18514678/cc84e7ea-7a92-11e6-80c2-cebc5963a3d3.png)
… the usual – maybe helpful but I click them away. ;)

Refresh / close the tab and later open OSM again:
![capture du 2016-09-14 15-46-23](https://cloud.githubusercontent.com/assets/925062/18514712/efeb9530-7a92-11e6-9fa9-2a734a6af66e.png)
Conference season I guess … clicking X.

Later, refresh / close again:
![capture du 2016-09-14 15-46-39](https://cloud.githubusercontent.com/assets/925062/18514737/08de37b4-7a93-11e6-986b-f7f948459ed7.png)
I especially like the design here :) But again I’m elsewhere, closing.

Refreshing again:
![capture du 2016-09-14 15-47-07](https://cloud.githubusercontent.com/assets/925062/18514764/22dcdc4c-7a93-11e6-99da-f0c4f20e59ea.png)
Not kidding – this has got to be a bug.

X-ing it and refreshing one last time:
![capture du 2016-09-14 15-47-32](https://cloud.githubusercontent.com/assets/925062/18514787/345e6ff8-7a93-11e6-8c47-94571f8b04dc.png)

_Now_ I can go ahead and use OSM in peace. ;)

Some takeaways:
- [ ] maybe just have _one_ banner for all the state of the maps. It could even be customized based on the person’s language/location
- [ ] never have multiple banners where after clicking all of them away, after refresh there’s more coming ;)
- [ ] a nice image like for the SotM banners might be nice for the default intro banner. Or maybe icons for the buttons. Like an info »i« for the »Learn more« and a map for the »start mapping«
- [ ] I’d cut the »Welcome to OpenStreetMap« to instead make the very good short description below more present

(And as always, thank you for the awesome work! :) Hope my feedback helps.)

**Comment by jidanni** [comment]
See also https://github.com/openstreetmap/openstreetmap-website/issues/1333 .

**Comment by tomhughes** [comment]
There was a bug that meant closing a banner didn't always persist but it was fixed a while ago. Other than that I'm afraid this isn't going to change.
