### ISSUE TITLE
Embedded maps are broken for Thunderforest layers

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#1293]
I saw [a report](https://help.openstreetmap.org/questions/52023/embedded-maps-not-working) on help.openstreetmap.org and thought I should investigate.

The embedded maps are no longer working for the Transport and Cycle layers, since the JavaScript code that generates the embedding output does not included the JavaScript code that sets the API Keys. Using an embedded map on a test site, I see the following in the console:

```
Error: No value provided for variable {apikey}
...unction(e,n){var o=a[n];if(o===t)throw new Error("No value provided for variable...
```

http://www.openstreetmap.org/export/embed.html?layer=cyclemap
http://www.openstreetmap.org/export/embed.html

I'm assuming that the `app/assets/javascripts/embed.js.erb` file isn't including the correct file (i.e. `app/assets/javascripts/osm.js.erb` where the API Key is transferred into the javascript code).

Unfortunately I haven't figured out the javascript dependencies for `embed.js.erb` so I can't see what should be fixed and where the dependency should be added. I don't see any of the files referenced at the top of that file ( "leaflet", "leaflet.osm", "i18n/translations") so there's some magic somewhere.

**Comment by tomhughes** [comment]
Well embed.js.erb is kind of standalone, but as it's erb it can insert the global directly...

**Comment by black-snow** [comment]
@tomhughes Embedded maps are (again?) not working for me.

```html
<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://www.openstreetmap.org/export/embed.html?bbox=13.27938884496689%2C52.47697613861493%2C13.282763063907625%2C52.478498702364185&amp;layer=mapnik&amp;marker=52.47773742707537%2C13.281075954437256" style="border: 1px solid black"></iframe><br/><small><a href="http://www.openstreetmap.org/?mlat=52.47774&amp;mlon=13.28108#map=19/52.47774/13.28108">Größere Karte anzeigen</a></small>
```

shows nothing but a gray box. Has anything changed?
