### ISSUE TITLE
Search: "Error contacting http://overpass-api.de/api/interpreter: Too Many Requests"

### ISSUE THREAD

**Issue by sladen** [openstreetmap/openstreetmap-website#1301]
Search results presently return:
```
  Query Features
    Nearby features
      Error contacting http://overpass-api.de/api/interpreter: Too Many Requests
    Enclosing features
      Error contacting http://overpass-api.de/api/interpreter: Too Many Requests
```
or:
```
Query Features
  Nearby features
    Error contacting http://overpass-api.de/api/interpreter: Gateway Timeout
  Enclosing features
    Error contacting http://overpass-api.de/api/interpreter: Gateway Timeout
```
Ideally a solution should be found so that some results (eg. Nomination) can be successfully still be returned instead.

**Comment by tomhughes** [comment]
I'm not sure what you mean. The query tool is driven by overpass, not nominatim. The search tool is driven by nominatim (among other things).

In any case this is not a web site issue - it is an overpass issue and/or an operations issue (in that we should have our own overpass instance instead of relying on the public one).

**Comment by sladen** [comment]
@tomhughes: I've retitled the bug.  Please can be reopen this again.

**Comment by tomhughes** [comment]
What would constitute "meaningful" in your imagination?

**Comment by tomhughes** [comment]
I mean we just report the error we get from overpass and I'm not sure what more we could do? I mean we could just hide that and say "The overpass interpreter returned an error" instead but I'm not really sure how that helps and it makes diagnosing problems harder if the upstream error is hidden.

**Comment by mmd-osm** [comment]
We're having the same discussion over there at overpass turbo: https://github.com/tyrasd/overpass-turbo/issues/269

Basically, in case of HTTP 429, there were too many queries and the server expects a minimum wait time, which is only visible via `/api/status` call.

So, yes. There are some options for a better error messages. Also, sending two queries at the same time is futile, if the server has a rate limit of 1 (visible in `/api/status` as `Rate limit: 1`). I guess you should sync up with Roland for details. @drolbr

**Comment by DaveF63** [comment]
Displaying more end-user friendly messages explaining what needs (or doesn't need) to be done will reduce the number of bug 'issues' which I'm sure would please @tomhughes :-)
