### ISSUE TITLE
 Two user_id use the same display_name in the .pbf data file

### ISSUE THREAD

**Issue by nimingkong** [openstreetmap/openstreetmap-website#1303]
I download the china-latest.osm.pbf data file in the geofabrik. I find that the data file has two user id use the same display_name, one is:
`<node id="223916865" version="3" timestamp="2016-02-19T19:39:34Z" uid="1708958" user="Nodes&amp;Roads" changeset="37316131" lat="26.7539917" lon="100.7842765"/>`

another is:
`<node id="224205724" version="3" timestamp="2016-02-20T00:02:20Z" uid="3642735" user="Nodes&amp;Roads" changeset="37320893" lat="28.03937" lon="99.5270481"/>`

So when i use osmosis to import the file into apidb, some error appears, it says that unable to insert user with id 3642735 into the database, duplicate key value violates unique constraint "users_display_name_idx", Key (display_name)=(Nodes&Roads) already exists. I find the error by transform the file from .pbf to .osc, if i want use the .pbf file, what should i do to deal with the condition?

**Comment by tomhughes** [comment]
This is not a problem with the web site code - it is a problem with the data you are using as I believe you have already been advised on help.openstreetmap.org.

Please don't ask the same question in multiples places simultaneously, it just causes confusion and duplication of effort in answering.

**Comment by mmd-osm** [comment]
Same issue as https://github.com/openstreetmap/openstreetmap-website/issues/282#issuecomment-248061596
