### ISSUE TITLE
Impossible to get out of “bug reporting mode”?

### ISSUE THREAD

**Issue by Wuzzy2** [openstreetmap/openstreetmap-website#1308]
I don't know if it's just me but apparently whenever I go into “bug reporting mode” on the website, it seems there is no turning back. I can't get rid of all the bug report overlay symbols. Reloading doesn't help. Clicking again on the bug reporting mode symbols doesn't help. Closing the sidebar doesn't help. I fear the only way to get out is by deleting cookies (not tested). WTF?

No matter if it is actually impossible to get out of this mode *without* deleting cookies or if I have just missed the magic undo button, I think this means I have discovered a pretty annoying usabilty issue on the homepage.
There should be a clear and obvious (!) way to get ouf of “bug reporting mode” once you're in. Apparently the website is lacking one.

“Getting out” means: Stop adding bug symbols by clicking, hide all bug markers. Basically the website should function like before you clicked on the bug reporting mode icon.

**Comment by tomhughes** [comment]
Just open the map layers selector and turn off the notes layer.
