### ISSUE TITLE
Document the non-db quadtile functions in the installation notes

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#1313]
While debugging why a single controller test was taking over 30 seconds to run, I found out about the non-database quad_tile functions (the database ones are already well documented).

These are implemented in ruby in `lib/quad_tile.rb`, but there is also a C-based implementation in the `lib/quad_tile/` directory. The test suite passes if you don't have the C-based version compiled, since the ruby code is used instead, but you can speed up the entire test suite (on my machine, by 40 seconds per run or ~20%) by compiling them.

The only other documentation that I've found is in the chef code for the deployed version:

https://github.com/openstreetmap/chef/blob/5b551a1cef6be428bc0b1b3ad04d0e9fe39409e4/cookbooks/web/definitions/rails_port.rb#L269-L289

From that, instructions would appear to be straightforward:

```
cd lib/quad_tile
ruby extconf.rb
make
```

**Comment by mmd-osm** [comment]
Isn't this issue superseded by #1899 and can be closed now?

**Comment by tomhughes** [comment]
Yes.
