### ISSUE TITLE
Drag and drop of routing markers not working anymore

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/openstreetmap-website#1315]
While planing a route i was able to drag the markers into the map.
![image](https://cloud.githubusercontent.com/assets/2410353/19192509/b8b33822-8ca6-11e6-82de-fccbc6341f87.png)

This is no possible anymore (since Leaflet 1.0?). The markers jumps back with no effect.

If the markers are there, they are dragable.

**Comment by woodpeck** [comment]
worksforme! (Firefox)

**Comment by HolgerJeromin** [comment]
Seems to be a [vivaldi](https://vivaldi.com/) only problem.
