### ISSUE TITLE
See certain things only (e.g. railways and waterways) 

### ISSUE THREAD

**Issue by willnwhite** [openstreetmap/openstreetmap-website#1316]
I'm planning a narrowboat trip and I want to see where the railway stations are in relation to the waterways, so we know there's a railway station we can catch a train home from at the end of the day and leave the boat moored for next weekend. It'd be cool to be able to select exactly what things you want to see on the map. It's hard to pick out the waterways and railways from everything else. I want a "narrowboat mode", and I guess there'd be other uses for being able to select only the things you want to see. I guess this is just an extension of the existing idea of layers.

**Comment by HolgerJeromin** [comment]
Perhaps you should try the tool 
Overpass Turbo 
for that.

**Comment by willnwhite** [comment]
Thanks, I may try to learn how to use that.
For OSM, I was thinking of just a text input: "railways" "waterways".

**Comment by tomhughes** [comment]
I don't think there's any realistic prospect of this being supported - the map is made up of rendered images that are subject to heavy caching in order to scale to the number of users we need to to support so there is no way we can be rendering different versions for each user.

**Comment by willnwhite** [comment]
Couldn't it be done client-side?

**Comment by tomhughes** [comment]
Maybe, at point in the future, with vector tiles it might be possible in theory.

In practice the number of combinations of things that people might want is so mind boggling that it's hard to believe a reasonable interface could be devised that an average user would be able to cope with.

If and when we have vector tiles with client side rendering then this could be revisited if somebody wanted to put the effort in, but that is probably a year or more away at least.

**Comment by willnwhite** [comment]
I guess this could be a sub-interface of the layers interface.

I think the way to deal with use-case overload like this is to collect them over time until you/we're happy with one change that can address many of them. I just watched [this talk](https://www.youtube.com/watch?v=DSjbTC-hvqQ&list=PLglJM3BYAMPH2zuz1nbKHQyeawE4SN0Cd&index=1) by Evan Czaplicki, who's in charge of the Elm programming language, and he's addressing the same problem.

**Comment by willnwhite** [comment]
Oh, unless you're talking about combinations of layers that people might want, like my railways and waterways combo. That's why I suggested a text input, that would match to different layers, rather than say a list of checkboxes.
