### ISSUE TITLE
Put link to https://wiki.openstreetmap.org/wiki/Standard_tile_layer/Key

### ISSUE THREAD

**Issue by Wuzzy2** [openstreetmap/openstreetmap-website#1321]
(This is a spin-off issue of #1307.)

## Suggestion
I suggest to put a link to https://wiki.openstreetmap.org/wiki/Standard_tile_layer/Key on the key sidebar. At the bottom.

## Rationale
The idea is that the user can then see the more “complete” key here. Since Standard has very many symbols, putting them on an external page might help.

## Explanation
This wiki page contains most, if not all symbols, many lines and area colors and is very detailed already. It is not 100% complete nor perfect and maybe it never will (because of the complexity of Standard). Of course, it will also be doomed to become outdated over time. But the same problem applies with the “official” key as well. I'm also not saying that the “wiki solution” should be permanent (if a better solutions pops up in the future), but I suppose it is a very good start and partially solves the problem that the current “official” key is VERY incomplete.

**Comment by tomhughes** [comment]
We try to avoid linking to wiki pages, and certainly the idea of a wiki page that is open to random edits at any time being considered as a master key seems insane.

The correct solution to all these problems is to autogenerate a key from the style sheet.

**Comment by Wuzzy2** [comment]
I agree, autogenerating the key would be best. But someone has to implement it first. I don't know how many months users have to wait for this. Thus, I thought of the wiki as a temporary solution, until the key is automatically generated. If the automatic key is there, the link can of course be removed as it won't be needed anymore.

I doubt this particular wiki page will see vandalism and even if it happens it will probably be fixed by anonther user. But if it turns out to be a problem, it could be replaced by some static page instead. My idea is: Better something than (almost) nothing.
