### ISSUE TITLE
Change the way the attribution is showed in map

### ISSUE THREAD

**Issue by yopaseopor** [openstreetmap/openstreetmap-website#1324]
In the Spanish talk-es email list we are talking about licenses and specially attribution. The main sentence is: We need an specific permission about every use of some open data to OSM because we only put source attribution in changeset and in element, because OpenStreetMap contributors is not enough for the attribution clauses of CC-by for the majority of administrations with open data (for example). So I have a question, what about change the way attribution it is showed in maps which uses OSM, being similar to other maps like Gmaps (depending the zone you have other attributions than only Google 2016) ? Map would be able to show the sources of the changesets you are watching every moment, for example, making the exact attribution clear and immediate.

**Comment by simonpoole** [comment]
OpenStreetMap is mainly an open data project. The issues with input licences, for example CC by *, could clearly be delt with some way on openstreetmap.org, but it would be very difficult to impossible to enforce this downstream, aka with consumers of our data (and it would need a licence change).

This is, for example, not an issue for google as they have complete control over how the data they distribute is used.

In any case this is not a subject for the website issue tracker.
