### ISSUE TITLE
OSM New Logo Proposal

### ISSUE THREAD

**Issue by elioqoshi** [openstreetmap/openstreetmap-website#1326]
Based on the new Donation Initiative Logo, I thought it would be a good time to discuss around adapting a new logo which is more suitable for print, smaller displays and generally a broader variety of backgrounds.

Having this in mind, I came up with a proposal of a logo, including the wordmark, which was never included as part of it. The wordmark is written in "Overpass" an Open Source font sponsored by Red Hat. 

![osm new logo proposal](https://cloud.githubusercontent.com/assets/5436686/19390878/6a13e570-922a-11e6-9eee-1f0c51745752.jpg)

What do you think of it? I believe it's time to suggest a new more modern logo for OSM nowadays to make it more usable for communities to adapt it.

**Comment by jancborchardt** [comment]
cc @tomhughes on this since we had good interface design discussions in the past. :)

I collaborated a bit with @elioqoshi on the logo and think it’s a good step up from the current one which is polished but a bit complicated.
Additionally this one is based on the simpler logo used at https://donate.openstreetmap.org so there seems to be some drive for that already.
We chose Overpass because it’s similar to the typography used on highway signs like Interstate and DIN – relevant to maps. ;)

**Comment by ppawel** [comment]
Wow this looks quite fresh and cool. Love the font! If only the magnifying glass was more prominent / visible, like grey or black or whatever (now it is empty space so you have to know the previous logo to notice it I think) then it would be perfect!

**Comment by jancborchardt** [comment]
@ppawel yeah, we thought about making the magnifying glass a proper form instead of just negative space. In grey like it appears on the donation page looks quite good. Might be worth investigating. :)

**Comment by tomhughes** [comment]
The logo is far more than the logo for the website - changing the project logo is way above my pay grade and not something that is appropriate to discuss here.

As and when the wider project makes a decision to change it's logo you can come back here and request we may the necessary technical changes to use the logo on the web site.

I'm not entirely sure who you do need to talk - maybe CWG in the first instance? It will certainly need to go to a broader discussion among the members though.

**Comment by simonpoole** [comment]
Given that htis is bike shedding bait, I'll bite: if at all the "Open" in the name should be bold not "StreetMap"

Seriously adopting a significantly new logo would have all kind of consequences that really really need to be thought through and definitely need to take place somewhere more public than here.

**Comment by Zverik** [comment]
Looks awesome. Changing the logo for a project this big is a complicated process, but you can do it bottom-up: publish it on the wiki under a license as open as you can, and see it used in more and more works.

**Comment by elioqoshi** [comment]
Thanks for the feedback :)
I have posted this on the Talk Mailing list and the Communications Team as well, so I am asking about feedback, not direct implementation. No need to close the issue

**Comment by jancborchardt** [comment]
@tomhughes sure, understandable – thanks for your input. As @elioqoshi said he posted it on the mailing list as well, so let’s see how it continues there. (With the different communication channels of each project it’s just always difficult to know where to bring up a specific issue. :)

**Comment by elioqoshi** [comment]
![osm new logo proposal](https://cloud.githubusercontent.com/assets/5436686/19391785/4c650492-922e-11e6-99a0-9b806b7189b2.jpg)

That's the version with opposite wordmark thickness
