### ISSUE TITLE
Persist banner suppression server side for logged in users

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1333]
Add a https://www.openstreetmap.org/user/*/account setting to remove the
`<div id="banner">...</div>` without the user needing to click the X.

E.g., just as with all websites, one can opt out of receiving similar
email notices without needing to delete (X) each one.

Yes they are great notices, but not so great for everybody.

E.g., just as with all other mapping websites, where they wouldn't dream
of making the user have to click an X to see what he wants to see.

**Comment by tomhughes** [comment]
Sorry, but I don't think it's too much too ask that you see an occasional notice about an upcoming event or donation drive.

**Comment by jidanni** [comment]
Occasional perhaps in your browser, not mine.

**Comment by tomhughes** [comment]
Are you saying that they come back after you have closed them? That shouldn't happen, at least as long as you don't flush your cookies.

**Comment by jidanni** [comment]
Some users use many different browsers from many different places.
They feel "if I am logged in, I should have some way to control this,
other than Adblock Plus."
That's what it is there for, to stop annoying banner ads.
They feel "Don't make me have to click that X. Not even one more time."
"Those messages may be important to you, but not to me. Stop bothering
me with them."

**Comment by tomhughes** [comment]
I've reopened this, but changed it to request that the closes be persisted on the server for logged in users so that they operate across all browsers. Hopefully somebody will be interested in doing that and it will be enough for you?

**Comment by jidanni** [comment]
Sounds great!
(P.S., I already submitted
    `openstreetmap.org/assets/banners/*`
to AdblockPlus Easylist.
So please don't get angry.)

**Comment by Firefishy** [comment]
@jidanni That is a real horrible move of your, absolutely unjustified. If the addition to Adblock list goes through you have just removed an unobtrusive way for OpenStreetMap to communicate with its users about OpenStreetMap stuff. I am not angry, I am furious with you. You could have just added it to your local block list if you felt so strongly.

**Comment by edgemaster** [comment]
[EasyList Policy](https://easylist.to/pages/policy.html):
> Self-promotion should not be specifically removed by EasyList, although equally should not be whitelisted if it is blocked.

**Comment by jancborchardt** [comment]
Yeah, sorry that’s not cool. The »State of the Map« banners might not be that relevant for users, but the donation drive is very important to keep this project alive!

@jidanni I suggest you donate at https://donate.openstreetmap.org since you use the project. :) The faster the donation goal is reached, the shorter the banner will be shown.

**Comment by jidanni** [comment]
One cannot remove pending posts in PhpBB,
Now that it has been posted, I will cancel my request.

**Comment by jidanni** [comment]
Some users use many different browsers from many different places.
They feel "if I am logged in, I should have some way to control this,
other than Adblock Plus."
They feel "Don't make me have to click that X. Not even one more time."
"Those messages may be important to you, but not to me. Stop bothering
me with them."

**Comment by nebulon42** [comment]
I disagree with "unobtrusive". In fact I'm also seeing reoccurring banners even if I have dismissed them. I have added those annoying things to my local blocking list. See also #1260.

**Comment by tomhughes** [comment]
Do you mean recurring in the same browser (or more precisely with the same cookies) or when you switch browser or clear your cookies?

**Comment by nebulon42** [comment]
I had a closer look and it seems that I somehow changed my cookie policy to "until browser is closed" but didn't remember. That explains the recurring banners, so no bug in the implementation with cookies I guess. Just wanted to add that the donation drive is an exception here. With annoying I was mainly referring to the abundance of conference banners.
