### ISSUE TITLE
Dragging routing icons does not work in IE/Edge

### ISSUE THREAD

**Issue by mormegil-cz** [openstreetmap/openstreetmap-website#1343]
In Internet Explorer 11, the routing icons cannot be dragged, it does not work at all. In Edge, the dragging seems to work, but the “to” icon is dropped always, even though the “from” icon was dragged.

Both issues come from a wrong implementation of the drag&drop code in OSM (plus worse compatibility of IE, obviously): The first argument to `DataTransfer.setData` is not some data subkey (like `$().data()` works), it is `format` (see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setData) and [WhatWG](https://html.spec.whatwg.org/multipage/interaction.html#dom-datatransfer-setdata)) And IE explicitly supports only two formats: `text` and `URL` (see [MSDN](https://msdn.microsoft.com/en-us/library/ms536744.aspx)), so we need to use one of them (probably `text`) and do our own subkeying under that, if needed. (It might make sense to separate drag&drop handling to some library to cover this compatibility stuff, should drag&drop get used more in OSM.)

Also, IE does not support `.setDragImage` (see [CanIUse](http://caniuse.com/#feat=dragndrop)), so we need to conditionalize that.

**Comment by tomhughes** [comment]
I noticed that [MSDN](https://msdn.microsoft.com/en-us/library/ms536744.aspx) also lists `setData` as deprecated as of Edge so does that mean there is some newer replacement in the standard we should be using? or is Edge really planning to remove something that is standard and previously supported?

**Comment by tomhughes** [comment]
Argh. If you're going to open a PR then you really don't need to open a separate issue first! One ticket is quite enough... I almost started working on this!

**Comment by mormegil-cz** [comment]
Right, sorry for that, I was not sure about the work style here (the guidelines do not mention anything about that).

I seriously doubt MS is going to remove support for `.setData` anytime soon in Edge. 1. It _is_ standard (even though not a very nice interface). 2. There is no real alternative right now: The preferred `.items` is not supported in Firefox until FF50, and is not supported in IE at all. But, as I said, having the compatibility issues encapsulated in a small library might be worth it.
