### ISSUE TITLE
All routes are drawn via hard-coded location, Laguna Road, east of SanDiego

### ISSUE THREAD

**Issue by RikdeBoer** [openstreetmap/openstreetmap-website#1345]
No matter where you drop your markers, the routing is drawn via "Laguna Road",[-114.462634,32.875313]

See for instance http://map.project-osrm.org

**Comment by tomhughes** [comment]
So why are you telling us? It's an OSRM bug as far as I know, so you need to tell them.

**Comment by tomhughes** [comment]
Confirmed by the fact that it happens on http://map.project-osrm.org that this is an OSRM bug.

**Comment by danpat** [comment]
The OSRM server currently is having problems processing the whole OSM planet file (some weird conditions, we don't know where, are triggering a crash).  We've got the server producing routes for California only for now.
