### ISSUE TITLE
The text does not fit in the button

### ISSUE THREAD

**Issue by zlant** [openstreetmap/openstreetmap-website#1353]
The text does not fit in the button
![image](https://cloud.githubusercontent.com/assets/8606466/19855201/541b1d80-9f84-11e6-8d11-f84bf26b6f16.png)

Solution:
`max-width: 180px;`
replace
`max-width: 100%;`
in openstreetmap-website/app/assets/stylesheets/common.scss

**Comment by tomhughes** [comment]
Well except that still leaves the buttons over two lines presumably, when they are supposed to be together on one line I think?

Is there no way to make the text shorter?

**Comment by tomhughes** [comment]
Incidentally you need to provide some context - what exactly is that sidebar? I assume it's a note? or maybe changeset history? Which line exactly in common.scss are you suggesting we change?

**Comment by zetx16** [comment]
The forum discussed a long time shorter replacement. None came to nothing.

This is note. Line 2164.

**Comment by d1g** [comment]
@tomhughes 
> Is there no way to make the text shorter?

We did several attempts on this. We have no better _and_ shorter words for this. "комментировать" is the least confusing translation AFAIK.

Shorter text labels "Обработать" are confusing (users open/close them repeatedly just to understand what button does)
Same about "Разрешить".

**Comment by mmd-osm** [comment]
I would assume this was fixed in https://github.com/openstreetmap/openstreetmap-website/pull/4871, as mentioned there by @AntonKhorev
