### ISSUE TITLE
Add coord for every note

### ISSUE THREAD

**Issue by d1g** [openstreetmap/openstreetmap-website#1355]
When you open http://www.openstreetmap.org/note/294569 - coordinates are not shown to user (http://www.openstreetmap.org/note/294569#map=15/56.8874/65.3966).

mavl suggested to move map a little to get this information http://www.openstreetmap.org/user/mavl/diary/39791

But 1. coordinates would be imprecise 2. **website can do this for user**

**Comment by tomhughes** [comment]
I think keeping a "clean URL" is deliberate (objects like nodes do the same I believe) so that it can be copied if required without extra information in the way.

**Comment by d1g** [comment]
@tomhughes, true URL isn't the best solution, but we need at least one way to see coords of the no**t**e. I suggest to use same view as http://www.openstreetmap.org/node/12

There no coords in http://www.openstreetmap.org/note/12 ATM.

**Comment by Skippern** [comment]
There could be a "center to" button on the note page, that allow the map to be centred on the note location. I don't see reason for this to be automatic, as it could be desirable to maintain the map while browsing several notes in the same area, but at times use the notes to move the map, specially if you desire to use the "edit" button to start editing the area around the note.
