### ISSUE TITLE
API returning old data from before upload of changeset?! (Changes are rendered!)

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/openstreetmap-website#1356]
I have no idea what is wrong here...

I uploaded a changeset from iD (http://www.openstreetmap.org/changeset/43349895), and while the rendering updated to correctly reflect the changes, as soon as I go into iD or JOSM again, and download the same area, I get back the data from BEFORE(!) the changeset upload. And yet, as said, I do see the changes rendered! I also get back old data when I choose to show map data on the OpenStreetMap website using the option for that from the right button / menu bar.

The only remarkable thing I noticed during upload of this changeset, was a warning of a way feature not having tags. I only noticed the warning when I already hit the upload button, so couldn't correct it.

But how can JOSM and iD show the data from before the changeset when I start a new edit session???

**Comment by mboeringa** [comment]
Here is an image to illustrate the issue. Notice the red arrows pointing to areas where the returned data using "Show map data" doesn't match the rendering.

Please note the rendering correctly represents the latest edits made in the linked changeset, the blue lines are wrong!

![api_old_data](https://cloud.githubusercontent.com/assets/7635726/19929738/216d263a-a105-11e6-91bd-20ab663b9171.jpg)

**Comment by mmd-osm** [comment]
See https://wiki.openstreetmap.org/wiki/Platform_Status : "Some API queries returning old data"

**Comment by mboeringa** [comment]
Ah, thanks! I hope they get this fixed soon, because it could get nasty if people start editing old data.
