### ISSUE TITLE
Ghost Ways Crossing City

### ISSUE THREAD

**Issue by cwmke** [openstreetmap/openstreetmap-website#1358]
I noticed an issue with 2 ways crossing a decent sized section of Milwaukee. Using JOSM as well as the online editor I was unable to find any ways that would be causing this. I have cleared my cache and have checked both on my phone and desktop (Firefox, Chromium). Any help will be greatly appreciated.

The below picture demonstrates the issue well. If you search for Veterans Park Lagoon you will find the ghost ways crossing the lagoon.
![ghostway1](https://cloud.githubusercontent.com/assets/1923967/20030954/bdac8bd2-a33d-11e6-86a8-197a5461ae44.png)

**Comment by tomhughes** [comment]
This does not appear to report a bug in the web site code, but rather erroneous data that should be corrected in the normal way.

It's possible that the data has already been corrected of course, in which case the rendering will be cleaned up when those tiles next re-render.

**Comment by cwmke** [comment]
When would the new rendering be expected? I noticed this last night and it remains this morning which is why I reported it. As originally explained, I checked the editors and there isn't a way to be corrected in the normal way which is why I believed it to be a bug.

**Comment by tomhughes** [comment]
Even it was a bug (which I'm sure it isn't) it would be in the style sheet and not the web site code so this would be the wrong place ;-)

As to when it will re-render well that rather depends on the nature of the error and the zoom level. If the error involved a relation then it might not re-render automatically until the next style update.

**Comment by dieterdreist** [comment]
it is a very long way...

http://www.openstreetmap.org/way/18200032

strangely, this seems to be modified 9 years ago, so I guess some of our
recent changes in the setup brought it to light (maybe a postgres update?)
Btw.: the changeset bounding box seems is much smaller than the way:
http://www.openstreetmap.org/changeset/415398#map=7/46.054/-96.147

Cheers,
Martin

**Comment by dieterdreist** [comment]
a driveway from milwaukee to a mosque in morocco ;-)

Have fixed it now...

Cheers,
Martin

**Comment by tomhughes** [comment]
I suspect there must be two different ones given there are two lines.

Presumably some changes in the style sheet means it has started rendering.

**Comment by openstreetmap-website** [comment]
The way was last modified by the TIGER import, but its nodes may have been
modified since.

We should take this to the talk-us mailing list so as to stop bothering
people here. :-)

**Comment by tomhughes** [comment]
Yes I was just going to say that most likely somebody has managed to reuse a node...

**Comment by SomeoneElseOSM** [comment]
Looks like people are onto it: https://github.com/grundid/amenity-editor/issues/3

**Comment by dieterdreist** [comment]
2016-11-05 16:54 GMT+01:00 Tom Hughes <notifications@github.com>:

> Yes I was just going to say that most likely somebody has managed to reuse
> a node...




yes, I think it's this changeset (amenity editor):
http://www.openstreetmap.org/changeset/43410083

Cheers,
Martin

**Comment by dieterdreist** [comment]
is there a way the API can block this version of the editor? Seems
reasonable, as it will break other stuff as well.

Cheers,
Martin

**Comment by tomhughes** [comment]
I have applied https://www.openstreetmap.org/user_blocks/1077 to let this user know to stop using Amenity Editor in this way until it is fixed.

A fuller block will have to be done in apache config (a few JOSM versions have been blocked in the past) and will only be possible if it passes a sensible version...

**Comment by cwmke** [comment]
Thanks @dieterdreist for fixing this! @tomhughes thank as well. I didn't realise this was an improper place to post something like this. Should I take something similar to the forums in the future?

**Comment by tomhughes** [comment]
The OAuth client ID being used used by the public install at http://ae.osmsurround.org/ has now been invalidated and all existing tokens revoked so it can no longer make edits.
