### ISSUE TITLE
Spin off diaries into `openstreetmap-diaries` separate app from `openstreetmap-website`

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/openstreetmap-website#1362]
split from #1361

**Comment by bhousel** [comment]
coping over comments for easier replying

from @zerebubuth:
>I think the biggest connection is the users table. We'd need to share that information and sessions between the different projects to make it still seem like one whole "site". This is something that's been on my TODO list for a few years (see What to Do? step 6), and I'm very sad that I have only just crossed step 1 off that list, almost a year later.
>
>@bhousel I would love to help do this. What could we start doing?
>
>@gravitystorm does this overlap with the devise stuff you were talking about before? Would that be helpfully combined with this, or would it be a distraction?

from @tomhughes:
>The users table is the biggest connection right now, but if we ever get the moderation queue sorted out that that creates a single point where all moderations reports (whether the report is against a diary entry, a diary comment, a user or whatever) are held in a single queue.

from @bhousel:
>Good ideas @zerebubuth & @tomhughes, thanks! 
Could a hypothetical openstreetmap-diaries app just use OAuth via osm-auth lib against the main site when people want to post or comment? Then it wouldn't need the full users table. It would still need something like a diary-users table that just contains user details to link to posts/comments.

**Comment by gravitystorm** [comment]
I think this is a bad idea. I'm all for developing diary entries further but I can't see any reasons for developing it independently from the main code. We can show diary entries from friends. We can moderate diary entries (soon). We can show diary entries near users changesets. etc etc. All of this becomes harder to do if they are in a separate code base from the rest of the models.

What reason, other than "architecture", is there for splitting off the diaries? 

If we feel that we need a different approach to coding the diary entries, then I would suggest looking for components (in the form of gems) that add more features without having to write the code ourselves. But I don't see the benefits of developing them in their own repo and I can see a whole bunch of drawbacks.

**Comment by gravitystorm** [comment]
> @gravitystorm does this overlap with the devise stuff you were talking about before?

Not afaik, but maybe there's some devise features that I'm unaware of. Moving to devise is so that we maintain less code around signin/signup tasks (like forgotten password reset emails etc), I don't think it is really anything to do with trying to run federated apps.

**Comment by bhousel** [comment]
Hey @gravitystorm - Just wanted to bump this issue again, as it relates to some of the feedback we received from TeachOSM.  

Some of the content on the diaries is problematic for teachers who want to use OSM in their classes.  (For examples, please ping me directly, I'd prefer not to link to it).  

We heard from several teachers that any software that they use in school must go through a review process.  This is reasonable.  While most diaries are fine, it would be sad if the day that somebody was reviewing openstreetmap.org, they happen to click the diary link and see a lot of spam or inappropriate content.

I feel like the spam problem alone is reason enough to move the diaries off site into a separate domain from openstreetmap.org, but just adding this as another reason.


--- 
_Background: I worked with TeachOSM recently on an event in which we trained geography teachers how to use OSM. Several of the teachers have already incorporated OSM into their curricula, and provided helpful feedback on ways that we can support them. This is one of a few related issues for discussion based on this feedback. Thanks!_
cc @nualacowan @geomantic

**Comment by bhousel** [comment]
> I don't see how this would change the domain.

Could it, though?  What are your thoughts on any of the following:

* split diary code into a separate app and GitHub repo
* leave diaries at openstreetmap.org/diary
* make diaries private (need to be logged in to view)
* per #1822 - need to be logged in and directee/student accounts can not access diaries
* move to separate subdomain - diary.openstreetmap.org
* move to separate domain - osm-diaries.org
* add disclaimer for external links ("You are now leaving OpenStreetMap and following this link may contain content that not constitute an endorsement or approval of...")

**Comment by tomhughes** [comment]
If I understand things correctly then the problem of children seeing unsuitable content may go away once GDPR comes in as I believe we are likely to have to impose an age limit on accounts.

**Comment by systemed** [comment]
> I feel like the spam problem alone is reason enough to move the diaries off site into a separate domain from openstreetmap.org, but just adding this as another reason.

The spam problem should be mostly addressed by #1576.

It's worth noting that reading the diaries through the blogs.osm.org aggregator (as many people do) gives a slightly misleading impression of the spam problem. Spam on OSM diaries per se is generally killed promptly, and will no doubt be faster still when #1576 lands. Unfortunately, killed spam currently persists on blogs.osm.org as per https://github.com/gravitystorm/blogs.osm.org/issues/17 . The latter should be fairly easily fixable via PR and is currently the lowest-hanging fruit for spam on OSM.

(I'll just leave this here for laughs: https://www.cnbc.com/2018/04/13/google-maps-spam-fighters.html )

**Comment by bhousel** [comment]
> I am skeptical regarding the idea of creating a "family friendly" sanitised OSM experience. 

Totally agree - this isn't about sanitizing all of OSM, and most of OSM does not need sanitizing.  The diaries are unusual in that they need _constant_ sanitizing.  

The issue that I'm raising is that anyone doing a "review" of OpenStreetMap must consider the diaries as a core part of OpenStreetMap and judge our project according to whatever appears there.  In the past day, I've visited the `/diary` page twice, and every time, the entry at the top is spam.  Yes it gets removed quickly, but the point is that this feature doesn't represent us, wastes sysadmin resources, and increases the attack surface area of the website.

#1576 just looks like a method for reporting spam.  Could we instead default diary entries to unpublished in a queue until a moderator approves them?  It's only a handful of entries every day.

> If you wanted to do that in earnest, you would have to limit exposure to map elements too ("OMG my child saw a PENIS SHAPED LANDUSE on the map")

Seems like a strawman argument - nobody is proposing this.

**Comment by gravitystorm** [comment]
I'm going to close this issue, since I don't think that it's worthwhile to separate out the diaries into a separate codebase. This doesn't mean that I think everything with the diaries is satisfactory, just that I believe the code separation suggestion is not the right approach.
