### ISSUE TITLE
Update Google logo on Log In page

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1364]
Please update  the Google logo on the Log In page.
https://en.wikipedia.org/wiki/Google_logo#Favicon

**Comment by tomhughes** [comment]
A link to a copy of the logo would have been more useful than a link to a wikipedia article...

**Comment by jidanni** [comment]
Just get it from the same place you got the last one.
You shouldn't trust me. I could give you a false logo.
Maybe it is in here somewhere,
https://developers.google.com/identity/branding-guidelines
