### ISSUE TITLE
Have "+" become grey upon reaching maximum zoom limit

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1365]
User zooms map by pressing "+".
At one point zooming stops, additional clicking on "+" is fruitless.
At that point please have the "+" icon fade in color, thus warning the
user not to bother clicking it anymore.
I have not experimented with "-" but please do the same.

**Comment by tomhughes** [comment]
I suspect this is a leaflet issue and not in our control.

**Comment by tomhughes** [comment]
Hmm maybe now, the default leaflet controls do do it.

**Comment by manfredbrandl** [comment]
Leaflet 1.2.0 (8/8/2017) allows this behaviour. @tomhughes could you consider using that? Maybe also for "-" when max zoom out is reached.

**Comment by tomhughes** [comment]
We are - in fact we're using 1.3.1 and have been since the day it was released.

That's not really relevant though because we're not using leaflet's zoom control, we're using our own one (https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/javascripts/leaflet.zoom.js).
