### ISSUE TITLE
CORS for the map key

### ISSUE THREAD

**Issue by joukewitteveen** [openstreetmap/openstreetmap-website#1368]
It would be nice if http://www.openstreetmap.org/key would support cross-origin resource sharing (CORS). For this, two things need to happen.
- [ ] Include the proper Access-Control-Allow-Origin header in the reply.
- [ ] Embed images (using base64 encoding).

**Comment by tomhughes** [comment]
Why would it be nice? That URL is an internal implementation detail and not something intended for consumption by any other web sit. We reserve the right to change or remove it any time.

**Comment by tomhughes** [comment]
I'm also not sure why whether the images are embedded has anything to do with CORS support? So long as the images can be loaded via CORS then it shouldn't matter surely?

**Comment by joukewitteveen** [comment]
Sure, you may change it or remove it, but chances are it will be there for a while longer and it is very easy to use for maps on other websites that use osm tiles.
When requesting the div through an XMLHttpRequest, it would be nice to not have to transform the image source URLs. Embedding the images would, certainly given their size, be an elegant option.

**Comment by tomhughes** [comment]
Sorry, but I don't want to encourage people to rely on internal implementation details so I don't think we're going to do this.

**Comment by joukewitteveen** [comment]
Too bad, it looked like an easy to implement improvement.
Is there an official way to access some kind of map key? My current solution is to just mirror the said key. I know it may stop working at any point in time, but that is OK for me.
At least an accessible key would motivate people to keep it of sufficient quality.
