### ISSUE TITLE
Missing translations for OSRM

### ISSUE THREAD

**Issue by boothym** [openstreetmap/openstreetmap-website#1369]
Error: [missing en-GB.javascripts.directions.instructions.slight_right_with_exit" translation]

For example in https://www.openstreetmap.org/directions?engine=osrm_car&route=56.06425%2C-3.23062%3B56.06384%2C-3.22957#map=19/56.06405/-3.23010 slight_right_with_exit is missing, as is sharp and turn when going towards the other roundabout exits.

**Comment by tomhughes** [comment]
So you probably need to get on TranslateWiki and add them then - see http://wiki.openstreetmap.org/wiki/Website_internationalization#How_to_translate for more information.

**Comment by tomhughes** [comment]
Hmm actually that seems to be missing from the master locale.

**Comment by tomhughes** [comment]
@TheMarex I suspect this comes from 311acad0c43401fe3d7651d021154af2efbedff5?

**Comment by boothym** [comment]
Also noticed there's a typo in this line: https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/javascripts/index/directions/osrm.js#L33

**Comment by simonpoole** [comment]
And another one 

13. [missing "en.javascripts.directions.instructions.turn_left_with_exit" translation]

**Comment by tomhughes** [comment]
@simonpoole do you have an example of a route which requires that?

**Comment by simonpoole** [comment]
@tomhughes sorry for the delay, was out (driving the route): https://www.openstreetmap.org/directions?engine=osrm_car&route=47.3898%2C8.3865%3B47.2835%2C9.4854#map=10/47.4081/8.9264

**Comment by tomhughes** [comment]
@simonpoole fixed in 25a50122966ed518c8c1981809e82a4e120e1671

**Comment by tomhughes** [comment]
I think 442994d46d3c00fdc16a746d4020634b4bdda0d3 should fix the original issue as well (the output from the router is actually giving continue now rather than a slight turn).
