### ISSUE TITLE
Replace the term diary

### ISSUE THREAD

**Issue by zubgjacc** [openstreetmap/openstreetmap-website#1371]
Has no one else found it odd that a public blog is called diary? Aren't diaries typically private? It is misleading.

**Comment by tomhughes** [comment]
Not necessarily. To quote [wikipedia](https://en.wikipedia.org/wiki/Diary):

> A diary is a record (originally in handwritten format) with discrete entries arranged by date reporting on what has happened over the course of a day or other period

A diary might be private, but it might equally be a public record of events.
