### ISSUE TITLE
Use image_url instead of image_path in feeds?

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#1379]
In RSS and Atom feeds, we need to supply the full url (i.e. with hostname) when constructing links to images. We use `image_path("foo.png", :host => SERVER_URL)` and #1378 makes this consistent.

However, there's an alternative: `image_url("foo.png")`, which also generates full urls. It seems to work to me. All of our `url_for(foo, :only_path => false)` work for generating urls for non-image paths, without needing SERVER_URL to be passed around.

Is there any reason that I haven't figured out to stick with `image_path` instead of `image_url`?

**Comment by smsm1** [comment]
I wonder if this code was copied from emails, which have an issue of knowing the hostname to use.

**Comment by gravitystorm** [comment]
Thanks @tomhughes !
