### ISSUE TITLE
Diary comments email 

### ISSUE THREAD

**Issue by boothym** [openstreetmap/openstreetmap-website#1380]
If you comment on a diary entry, and then another user also leaves a comment, you receive this kind of email:

**Subject: [OpenStreetMap] $anotherUser commented on your diary entry**

Hi $username,

$anotherUser has commented on your recent OpenStreetMap diary entry with the subject $subject:

$message

etc

I was a bit confused when I received this - it makes it seem like I had written the diary entry! It could be changed so that it says "diary comment" instead?

**Comment by tomhughes** [comment]
Yes it's a bug dating from the change to allow generalised subscriptions. Worse than that is that email replies are mishandled because it assumes that the reply has come from the original diary entry author.

**Comment by SomeoneElseOSM** [comment]
Recent emails are now "commented on a diary entry" so presumably this is fixed now?

**Comment by tomhughes** [comment]
Is that the English version or a "fix" somebody has made to a translation?

**Comment by AntonKhorev** [comment]
Looks like "your diary entry" existed only in en-GB, so this was never a problem in this repository.

**Comment by mmd-osm** [comment]
Issue seems to be resolved as per previous comments, closing.
