### ISSUE TITLE
Multiple consecutive spaces in tag display

### ISSUE THREAD

**Issue by harry-wood** [openstreetmap/openstreetmap-website#1386]
Wherever we are displaying tags, if the tags have multiple consecutive spaces, we're not displaying this at all. They get spat out in the HTML as space characters, but obviously browsers then ignore this, and display it as a single space. That's a (minor) problem, because users (or mappers who might fix this tagging issue) can't really see consecutive spaces very easily.

Currently there's an example here with lots of consecutive spaces in a name: http://www.openstreetmap.org/way/6199771

![screen shot 2016-12-06 at 11 03 10](https://cloud.githubusercontent.com/assets/227525/20923392/17dd7a2a-bba4-11e6-9328-2d741603cc6f.png)

but this applies to any tag, not just names, and to any number of space characters greater than 1. It also applies to any tag display, so even if somebody fixes the above example, we'll still see the problem lower down on this page: http://www.openstreetmap.org/way/6199771/history

**Comment by tomhughes** [comment]
Well it's supposed to be a "pretty display" so that seems reasonable, and in practical terms I don't think there's anything we can do anyway...

**Comment by tomhughes** [comment]
I guess we could set `white-space: pre-wrap` in the style but I'm not sure if it's a good idea or not.

**Comment by tomhughes** [comment]
Here's what it would look like if we did that:

![screenshot from 2016-12-06 11-40-37](https://cloud.githubusercontent.com/assets/147741/20924357/f32477f6-bba8-11e6-8978-e3d6c83b42e0.png)

**Comment by tomhughes** [comment]
I suspect this was a bonkers attempt to make it render both names on the road with space between them by the way ;-)

**Comment by zerebubuth** [comment]
Could we replace spaces with the U+23B5 BOTTOM SQUARE BRACKET (⎵) character? Or highlight "non-standard" spacing (i.e: more than one space between words) by using that character with an `<abbr>` saying how many spaces are there?

**Comment by tomhughes** [comment]
Problem with that is will it cause line breaking problems by getting rid of the spaces as line break points?

**Comment by tomhughes** [comment]
To be honest I'm not sure there's anything wrong with the CSS fix I proposed - it doesn't look as bad as I thought it might.

**Comment by Zverik** [comment]
I agree, bottom brackets are counter-intuitive for some, and with the CSS fix multiple spaces (even two) are immediately visible.

**Comment by harry-wood** [comment]
yeah. looks pretty good to me with `white-space: pre-wrap`
