### ISSUE TITLE
Mapzen link points to 404 error

### ISSUE THREAD

**Issue by sb12** [openstreetmap/openstreetmap-website#1388]
Hello,
the link underneath the routing instructions of mapzen currently points to https://mapzen.com/projects/valhalla which currently returns a 404 error page.

**Comment by tomhughes** [comment]
So where do you think it should point?

**Comment by iandees** [comment]
It should probably go to https://mapzen.com/products/turn-by-turn/

**Comment by tomhughes** [comment]
Only if I can send mapzen the "don't break links" award ;-)

**Comment by iandees** [comment]
(We're working on fixing the redirect 😄 )

**Comment by migurski** [comment]
I'll make a redirect; never knew about that old link.

**Comment by migurski** [comment]
Redirect complete!
