### ISSUE TITLE
undefined method `create_request_token' for nil:NilClass

### ISSUE THREAD

**Issue by miladkdz** [openstreetmap/openstreetmap-website#1398]
I get this error while trying to oauth sign in to my own deployed instance of openstreetmaps-website.

This is my http request:

URL: http://localhost:3000/oauth/request_token
METHOD: POST
Authorization Header Value: OAuth oauth_consumer_key="xxxx", oauth_nonce="xxxx", oauth_signature="xxxx", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1482577164"

**Comment by miladkdz** [comment]
The issue was with proxy passing and Nginx. I will be glad to help anyone who encounter this in the future.

**Comment by HansonYe** [comment]
Hi miladkdz. I encounter this problem now. Would you tell me how to fix it?

**Comment by miladkdz** [comment]
Hi @HansonYe 
We used Nginx as reverse proxy and the hostname was something other than the thing we defined in application.yml. And since the system uses this string to encode oauth tokens, this error was raised. So we fixed Nginx config and everything is up and running now.
How did you deploy the system?

**Comment by mnameghi** [comment]
Hi @miladkdz 
Witch configs was wrong? I had this problem too.

**Comment by miladkdz** [comment]
@mnameghi Are you running OSM behind a reverse proxy? Just make sure you are passing all the headers to it.

**Comment by mnameghi** [comment]
Yes and I used these confis:
```
proxy_set_header  X-Real-IP        $remote_addr;
proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
proxy_set_header  Host             $http_host;
proxy_redirect    off;
proxy_set_header   X-Forwarded-Proto  $scheme;
proxy_pass_header  Set-Cookie;
proxy_pass http://127.0.0.1:3000;
```

**Comment by miladkdz** [comment]
@mnameghi Problem I was facing lifted by making sure that the hostname passed to the server is the same as the one indicated in the application.yml file.
