### ISSUE TITLE
vagrant up command fails for openstreetmap-website

### ISSUE THREAD

**Issue by IOOI-SqAR** [openstreetmap/openstreetmap-website#1402]
When trying to follow the instructions given on [https://github.com/openstreetmap/openstreetmap-website/blob/master/VAGRANT.md](https://github.com/openstreetmap/openstreetmap-website/blob/master/VAGRANT.md) the `vagrant up` command fails like this:

`==> default: Gem::InstallError: nokogiri requires Ruby version >= 2.1.0.`
`==> default: An error occurred while installing nokogiri (1.7.0), and Bundler cannot`
`==> default: continue.`
`==> default: Make sure that `gem install nokogiri -v '1.7.0'` succeeds before bundling.`
`The SSH command responded with a non-zero exit status. Vagrant`
`assumes that this means the command failed. The output for this command`
`should be in the log above. Please read the output to determine what`
`went wrong.`

when I look further up in the vagrant output I can see that `ruby2.0 (2.0.0.484-1ubuntu2.2)` was installed before. I attached the full vagrant output:
[openstreetmap-website vagrant up.0.log.txt](https://github.com/openstreetmap/openstreetmap-website/files/682153/openstreetmap-website.vagrant.up.0.log.txt)

**Comment by tomhughes** [comment]
Well as it says, you need ruby 2.1 not 2.0.

**Comment by tomhughes** [comment]
I guess this probably needs the Vagrant file changing to a new image but I know nothing about the vagrant stuff.

**Comment by IOOI-SqAR** [comment]
This now works as expected!
