### ISSUE TITLE
Follow-up #1400

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#1407]
Apologies to create a new issue for this stuff, but #1400 is locked unfortunately and I wanted just to add a two line comment. So here we go:

I could reproduce the issue with Merkaartor 0.17.2 locally, the API URL as it is maintained in Merkaartor is perfectly ok, but somehow Merkaartor screwed up the "Host" part in the HTTP header by adding something like ":P" in the HTTP request - instead of ":80". (`P` actually corresponds to ascii 80).

I guess this strict host check is somehow new or user:wycbtma didn't use Merkaartor for some time.

I don't know if you want to support such a crappy and old client, at least the user who reported it (and somehow is unable to upgrade for whatever reason) can no longer use his version.

See this HTTP trace I collected in wireshark:

```
GET /api/0.6/way/65190596/relations HTTP/1.1
Host: www.openstreetmap.org:P
User-Agent: Merkaartor/0.17 (X11;SVNREV)
Authorization: Basic Og==
content-length: 0

HTTP/1.1 301 Moved Permanently
Date: Fri, 06 Jan 2017 17:39:15 GMT
Server: Apache/2.4.18 (Ubuntu)
Location: http://www.openstreetmap.org/api/0.6/way/65190596/relations
Content-Length: 356
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://www.openstreetmap.org/api/0.6/way/65190596/relations">here</a>.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at www.openstreetmap.org:p Port 80</address>
</body></html>
```

**Comment by tomhughes** [comment]
So as I said all along the client is broken and there's no bug here.
