### ISSUE TITLE
"Search" returns a postcode, where does it stem from?

### ISSUE THREAD

**Issue by jscheidtmann** [openstreetmap/openstreetmap-website#1409]
When searching for "Peter-Rasspe-Str" on OSM.org, the search returns one entry:

"Peter-Rasspe-Straße, Hasseldelle, Gräfrath, Stöcken, Solingen, Regierungsbezirk Düsseldorf, Nordrhein-Westfalen, 42653, Deutschland"

This information is slightly wrong: Gräfrath is somewhere else, as ist the postcode 42653 (which should be 42651). When looking in the database, no postcode is associated with this line (53182290). 

a) I can't find information in the wiki how search operates. Please provide some information there (or point me to it).
b) How is this information derived? 
c) What needs to be done to correct it?

Thanks in advance, Grimaldi

**Comment by tomhughes** [comment]
Firstly this is most likely just a data issue, so you should probably ask at https://help.openstreetmap.org/ for advice on how to improve the data.

It might be an issue with the geocoding engine, in which case you should raise it at https://trac.openstreetmap.org/newticket?component=nominatim in the "nominatim" component.

What it definitely isn't is a bug in the web site code.

**Comment by HolgerJeromin** [comment]
As a reference: The debug view of the search is here
http://nominatim.openstreetmap.org/details.php?place_id=77781148

**Comment by lonvia** [comment]
The postcode comes from http://www.openstreetmap.org/node/312774373, Nominatim pulls in any postcodes from objects that are part of the address. You can go through the list in the details page to find the culprit.

For bug reports with search, please use preferably the [nominatim bug tracker on github](https://github.com/twain47/Nominatim/issues).
