### ISSUE TITLE
Find missing routes algorithm

### ISSUE THREAD

**Issue by HarelM** [openstreetmap/openstreetmap-website#1410]
Hi, I'm not sure to whom I should address it and if this is something that should be here or not, but here goes:
I'm the co-founder and main developer of https://israelhiking.osm.org.il/
This site relay heavily on OSM data.
We have decided to simplify the map editing user experience by writing an algorithm that can find missing routes and add them to the map according to minimal user input (mainly tags we are interested in like highway and colour). 
We still promote the usage of iD as OSM editor for more advanced work.
From tests we made the algorithm is pretty fast and does a good job in finding missing routes.
Our entire code base is open source and I think the OSM community can benefit a lot from our work.
I'm not a Ruby developer, but I'd be happy to help someone translating the code to whatever language needed.
The main classes that are involved in the process can be seen here:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Controllers/OsmController.cs
mainly ```PostGpsTrace```
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Services/AddibleGpxLinesFinderService.cs
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Services/GpxLoopsSplitterService.cs
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Services/Osm/OsmLineAdderService.cs
I'd love to hear your intake on this, what it ever done before somewhere else? was it successful? do you think it misses the point in some aspect?

**Comment by tomhughes** [comment]
I have absolutely no idea what you're talking about but you don't appear to be reporting a bug in the code in this repository or suggesting an enhancement to it.

Our default routing is provided by the OSRM project (http://project-osrm.org/) and the iD editor can be find at https://github.com/openstreetmap/iD/ so maybe you meant to report this to one of those projects?

**Comment by HarelM** [comment]
This is not a bug but an enhacement - an algorithm that can find unmapped parts in a GPS trace uploaded to OSM.
It is not related to routing.
I don't think it's related to iD editor since as far as I can understand iD is just the UI part over the OSM API.
I think it will benefit the OSM community greatly, and since this repository is maintaining the API I believe it might be the right place to open this issue.
Please read again my post thoroughly before closing this issue, I'll be happy to elaborate on anything that is not clear.

**Comment by tomhughes** [comment]
It doesn't sound like something that would be part of the web site though, and C# code is certainly no use for  the web site.

It sounds like something you should just run as a separate service that people who are interested can use to get ideas about what to map.

**Comment by HarelM** [comment]
Frankly, I'm disappointed by your answers... But I see that we are not sharing the same perspective so I'll drop this.
As a side note the main feature here is an algorithm, it happens to be written in C# but I don't see how this makes any difference.
You are using in your site OSRM, GraphHopper, Nominatim and other stuff, I don't see how this is any different besides the effort needed in order to write it in Ruby or Java so that it will be able to be cross platform - I don't think it's big enough in order to be a separate service such as the above and I don't think it belongs to any other place besides the API around OSM.
Thanks anyway...

**Comment by tomhughes** [comment]
We "use" those by calling external APIs run by other people. We don't run them ourselves. As it happens we would like to run an OSRM instance when we have the resources but we certainly wouldn't try to run all of them.

Sure we could run this as a separate service, but it sounds very niche, and there's a limit to how much we can take on.

Look currently what you have done is point us at some code in a language that I have no experience in and said you think we should use it - perhaps if you explained how you envision it being used and how it would appear in the UI we could understand better what it is you're thinking. Currently it's very hard to get a grip on what exactly you're suggesting.

**Comment by HolgerJeromin** [comment]
Such things start as a project of third party users and when they are stable and useful for many people sometimes they are taken and installed on OSMF Servers.

One example would be Taginfo which is now hosted on OSMF hardware (not even linked from osm.org main page!), but even overpass api (which is used in osm.org page) and overpass turbo are running separate.

**Comment by gravitystorm** [comment]
@HarelM Thanks for getting in touch. It sounds to me like your algorithm and code would be a useful Quality Assurance tool. These are usually developed and run as standalone services by members of the community, rather than being brought into this codebase. This issue tracker tries to focus just on the codebase for the API and website, rather than any wider OSM development topics.

I would suggest either running your tool as a separate QA project, or even better, if your tool can be integrated into one of the existing OpenStreetMap QA systems (Keepright, Osmsose, OSM Inspector etc), perhaps as a plugin. This way the suggestions from your tool will be processed by existing community members who are interested in QA topics. There's a range of options here.

More information about QA tools is available on the wiki at https://wiki.openstreetmap.org/wiki/Quality_assurance . Discussions for general OSM development topics are often found on the dev mailing list, see https://lists.openstreetmap.org/listinfo/dev

**Comment by tomhughes** [comment]
Indeed, and you can always ask for an account on our dev server (http://wiki.openstreetmap.org/wiki/Using_the_dev_server) if you want somewhere to setup a service people can try out.

**Comment by simonpoole** [comment]
@HarelM currently it is very difficult to evaluate what you have written. I would suggest that you set up a public test instance that runs against our sandbox/dev instance of the API. This discussion should in any case be going on in the github repo of your app, not here.

In any case while it is true in some way that "iD is just the UI part over the OSM API." it represents multiple man years of work and is quite complex (as any other OSM editor.

Note: way back when I started off with OSM it was quite customary to take a GPS track directly transform its geometry to a way and add that to the OSM database. In most cases that has been replaced by direct tracing from aerial imagery in the last five years. So while using GPS traces to highlight potentially missing roads is useful QA, I'm not sure that adding such segments directly to OSM is useful.

**Comment by HarelM** [comment]
Happy to explain my wider perspective, I'm not sure how this falls to the QA category though:
The current UX we are using is the following:
1. User upload a GPS trace to OSM from either a mobile phone or from his PC.
2. The GPS trace is uploaded to the list of all the current GPS trace and can be seen in the UI (Our UI is a bit different from yours, but has the same functionality basically).
3. The user would like to find and add unmapped highways and so he clicks on a button related to a GPS trace he just uploaded.
4. The GPS trace is sent to the server for processing and the unmapped (and simplified) parts are returned and presented on the map so that the user can easily add them.

I'm not disrespecting any aspect of iD, I think it a wonderful web app, don't get me wrong.

The way I see it, it is a key feature in order to reduce the barrier preventing people from editing the map.
I know that this feature have positively identified places I forgot to map and with a few clicks was able to add them to OSM - I know that in the past traces were uploaded as is, I don't think this is the same although it has some similarities.

You are more than free to join the discussing here on our github project:
https://github.com/IsraelHikingMap/Site/issues/267

I'll be happy to answer any question you have :-)

**Comment by HolgerJeromin** [comment]
If the user already found the missing gps track already (every logged in user has "my tracks" in the profile) he can click on the gps track and click edit.
![image](https://cloud.githubusercontent.com/assets/2410353/21762882/5de38948-d65b-11e6-9bac-900f4ac66828.png)

Then the default OSM Editor opens with this track highlighted and he can draw the missing highway based on an aerial and his track.

**Comment by HarelM** [comment]
True, I'm aware of current capabilities :-). This does not fall under what's currently implemented.
It should allow an easier starting point for adding parts of a recorded unmapped trace. I can even think of a scenario when a user uploads a trace and instead of just sending a mail that the track was uploaded engage him by letting him know that some parts of the trace are missing and encourage him to go back to the editor and add them.

**Comment by Supaplextw** [comment]
Hi HareIM

I think maybe post your idea and what you can do on the mailing list
https://lists.openstreetmap.org/listinfo

Maybe post at Talk-OSM will got much bigger attention.

**Comment by HarelM** [comment]
@Supaplextw I think I did (not sure, something with approval), can't say I got any feedback.
Feel free to contact me if you decide to invest time in this, I think it's a very neat feature.

**Comment by HarelM** [comment]
I know this is a bit old, but I have invested in the last week a few more hours to polish the algorithm, I also created a wiki page to explain how it works.
In case any of you are interested [here's the link](https://github.com/IsraelHikingMap/Site/wiki/Candidates-algorithm:-find-unmapped-routes)
This works only in Israel and can be used using our site: https://israelhiking.osm.org.il/ by logging in to your OSM user on the right side, click the wrench and click the search icon on one of the traces.
(site language can be changed on the right).
I have seen the algorithm preform very well, here's an example (blue is the original trace, red is the algorithm's results):
![image](https://user-images.githubusercontent.com/3269297/34457714-70b8cb3a-edc2-11e7-9276-81b7cd4244e9.png)

**Comment by Nerdyvedi** [comment]
Is it not possible to add it for places other than Israel ?

**Comment by HarelM** [comment]
The results can be seen in the wiki page explaining the algorithm, the linked issue above and the screenshot in my comment.
I don't have a python implementation of this algorithm, but it shouldn't be hard to translate the code in theory.
It can only work inside israel since we only parse the israel OSM file. In theory (haven't tested that theory) one can create an instance of our server and parse a different country to see how the algorithm works for other places.
Feel free to open an issue on my repository if you would like to continue the discussion. This is issue was never reopen so I doubt this interests other people besides me...
