### ISSUE TITLE
Invalid page for gpx address when user is not logged in

### ISSUE THREAD

**Issue by HarelM** [openstreetmap/openstreetmap-website#1411]
The following behavior is probably not correct:
I have a link to edit a GPX route on the map, for example the following link:
https://www.openstreetmap.org/edit?gpx=2335382
If I use this link when I'm not logged in to OSM I get a 404 page (instead of "unauthorized").
Since this is my gpx file, I would expect to get a login page first, and if this is an incorrect link (for example not my gpx file) then a 404 page.
Hope I made myself clear.

**Comment by HarelM** [comment]
Cool, thanks for the super-fast fix!
Let me know when it's up and running and I'll be glad to test it.

**Comment by HolgerJeromin** [comment]
Toms changes were in the past directly deployed.

**Comment by HarelM** [comment]
Not sure I understand the last comment... 
Current behavior (tests a few seconds ago) is that I still get 404 when not logged in for the provided address above instead of getting the login page.

**Comment by tomhughes** [comment]
I did mark it for deployment but it takes up to half an hour to roll out. It should be live now.

**Comment by HarelM** [comment]
Works perfectly! Thanks!
