### ISSUE TITLE
Search results are too wide on safari/iPhone

### ISSUE THREAD

**Issue by beatep** [openstreetmap/openstreetmap-website#1414]
Steps to reproduce:

1. Open openstreetmap.org on iPhone iOS 10.2.
2. Click on the menu icon top right.
3. Search someting.
4. The result list ist too wide, so the x for closing the layer is not visible.

![img_2271](https://cloud.githubusercontent.com/assets/1794446/22072089/7648f55c-dda1-11e6-952a-977915a7b16e.PNG)

**Comment by HolgerJeromin** [comment]
Wow. Even the menu (three lines) is not visible.
All elements in the sidebar have explicit width=100%. 
Given the screenshot I suspect that this browser does not have implicit 
width=100%
on <body>. 
I think that would not hurt :-)

**Comment by beatep** [comment]
fun fact: if I reload the page, everything is ok ;)

**Comment by tomhughes** [comment]
What screen size is your device? Because I've tried it with some pretty small sizes (down to 320x480 in fact) and it seems to be fine for me,

**Comment by beatep** [comment]
it's the iPhone 6S (not plus). [Resolution](http://www.apple.com/iphone/compare/): 1334-by-750-pixel at 326 ppi.

**Comment by tomhughes** [comment]
Well at 750 pixels wide it shouldn't even be in small screen mode! I believe that iOS actually lies and presents a different "logical size" to the web page though?

**Comment by HolgerJeromin** [comment]
All modern mobile browsers lie about the pixel size.
device pixel != css pixel

**Comment by beatep** [comment]
If I resize my firefox on the Mac to 750px, there is also the small screen mode, but after searching the x is visible. On safari/Mac, too, even on iPhone Simulator! Very strange, I don't have a clue, sorry.

**Comment by HolgerJeromin** [comment]
I bet on a bug in the browser which does not default to width:100% on body.

**Comment by dieterdreist** [comment]
sent from a phone
> On 18 Jan 2017, at 18:23, Tom Hughes <notifications@github.com> wrote:
> 
> Well at 750 pixels wide it shouldn't even be in small screen mode! I believe that iOS actually lies and presents a different "logical size" to the web page though?


yes, it's half the pixels (retina), i.e. 375px wide.

**Comment by AntonKhorev** [comment]
Is this still happening for anyone? It shouldn't be possible now.

![image](https://github.com/openstreetmap/openstreetmap-website/assets/4158490/bb0fef38-c681-40fd-a2ab-bf6e01e3716f)

**Comment by systemed** [comment]
Yes, the original issue still happens for me.

I think the problem is that when you tap in the search input, iOS zooms in slightly so that the search box is full-width. (This is probably 110% zoom or thereabouts.)

Then when you click "Go" and get results, it stays at 110% zoom. This means that the "X" is not visible.

There are a couple of suggestions in [this SO question](https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone).

**Comment by AntonKhorev** [comment]
After it zooms, is "Go" visible or do you have to scroll for it?

**Comment by systemed** [comment]
It's visible:

![OpenStreetMap](https://github.com/openstreetmap/openstreetmap-website/assets/694425/60899311-9c81-414f-a36e-31e3635d86aa)

**Comment by AntonKhorev** [comment]
According to StackOverflow, it zooms because the font size is smaller than 16px. Does it try to fit the "Go" button or is it a coincidence? It seems like it does, but how does it decide to fit "Go" but not the directions button?

**Comment by systemed** [comment]
I think it's a coincidence. Rotating the phone to landscape gives a margin on each side but with "Go" hidden under the notch.

Setting `font-size: 16px` on the element does indeed prevent it from zooming.
