### ISSUE TITLE
HTTPS support in api06.dev

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/openstreetmap-website#1418]
Could we have HTTPS support in api06.dev.openstreetmap.org, please?
Specially for the login at http://api06.dev.openstreetmap.org/login

**Comment by tomhughes** [comment]
No, we don't have a certificate that will cover that. It's also an operational issue, not a code issue, so not appropriate here.

**Comment by naoliv** [comment]
Even a self-signed certificate is better than nothing.
And where could I request this?

**Comment by tomhughes** [comment]
At https://github.com/openstreetmap/operations/issues but please don't - there is no chance of us deploying a self signed certificate.

That is a test deployment and contains nothing of any importance that needs protecting.

**Comment by naoliv** [comment]
It's not about the data, but about the username and password.
Somebody could capture them.

**Comment by tomhughes** [comment]
Well I'd hope any developer that needed to use the site would be using unique passwords anyway...

When we get letsencrypt working we can look at it but it's not likely to happen before that.

**Comment by tomhughes** [comment]
For the record this was implemented in https://github.com/openstreetmap/chef/commit/492559ef865a09dba696babf6178a05b33cc2eb8.

**Comment by naoliv** [comment]
Thank you!
