### ISSUE TITLE
Tiles at z17 not rendering properly

### ISSUE THREAD

**Issue by talllguy** [openstreetmap/openstreetmap-website#1420]
I have observed that the tiles at z17 are not rendering with changes to the map. Their status date is **Sat Jan 01 00:00:00 2000**, which seems like an error. This does not affect z18-19 or 16-lower.

## Steps to reproduce
Tested on Google Chrome Version 55.0.2883.87 m (64-bit)

1. Navigate to an area with some recent edits, e.g. [here](http://www.openstreetmap.org/#map=16/39.5374/-76.6368). _Note that this is z16_.
2. [Disable cache](http://stackoverflow.com/a/7000899/2105596) for testing purposes
3. Force empty cache and reload (see Fig. A below). This will ensure that the latest non-cached tiles are loaded.
4. Zoom in a step to z17 and note the odd green notch in the park multipolygon. I fixed this over the weekend. Repeat step 3 to reload. When I tested this 31 Jan 2017 1511UTC, Fig. B is how z16 looked, and Fig. C is how z17 looked.
5. Try forcing a _dirty_ status on one of the z17 tiles. Look in the dev tools _Network_ tab for a PNG that should be updated, e.g. [49840](http://c.tile.openstreetmap.org/17/37633/49840.png).
6. add a `/dirty` to the end of the tile URL, i.e. `http://c.tile.openstreetmap.org/17/37633/49840.png/dirty`. You should see a message, "Tile submitted for rendering"
7. Wait a few minutes for good measure.
8. Repeat steps 2, 3, and 4 and note that there is no change.

## Further analysis
I was showing a newly mapped woods trail to someone unfamiliar with OSM yesterday and noticed that the tiles were acting up on a computer browser that had never launched the OSM website.

I [checked the tile status](http://c.tile.openstreetmap.org/17/37633/49840.png/status) for the affected tiles, e.g. 49840, and noticed that the last rendered date is always **`Sat Jan 01 00:00:00 2000`**

## Screenshots
Figure A (reload)
![image](https://cloud.githubusercontent.com/assets/1827881/22470008/d7fda078-e79b-11e6-8ee1-de807e073867.png)

Figure B (z16)
![chrome_2017-01-31_10-07-09](https://cloud.githubusercontent.com/assets/1827881/22470484/7cdf6cba-e79d-11e6-91ce-e349330ef6c7.png)

Figure C (z17)
![chrome_2017-01-31_10-08-52](https://cloud.githubusercontent.com/assets/1827881/22470487/80998bf6-e79d-11e6-907b-e43d816e761e.png)

Figure D (tile 49840 status)
![image](https://cloud.githubusercontent.com/assets/1827881/22471168/8ec59ff6-e79f-11e6-95f9-64ab609ed4c3.png)

**Comment by talllguy** [comment]
I've also noticed that this same notch appears on other OSM based maps that typically update minutely, CC @aaronlidman 
![image](https://cloud.githubusercontent.com/assets/1827881/22475620/83d9b7b8-e7ad-11e6-920c-77b1e341e9ae.png)

**Comment by tomhughes** [comment]
Operational issue, not a code bug.

**Comment by tomhughes** [comment]
The old date is not a problem by the way - if anything it is good because it shows the tile is dirty and due to be re-rendered when resources are available.

**Comment by tomhughes** [comment]
Note also that right now a new style is rolling out, so re-render requests are unlikely to be acted on immediately.

**Comment by tomhughes** [comment]
Just to confirm that timestamp is the one used to mark tiles as dirty when the data changes, so that tile is pending a re-render when resources are available.

**Comment by talllguy** [comment]
Tom, thanks for the prompt follow up and clarification on this issue. I was not aware that a new style was rolling out (other than occaisional iterative updates to over at openstreetmap-carto. Where can I find out more about the new style?

**Comment by tomhughes** [comment]
Usually release notes are posted to the lists but I don't believe that has happened this time. It's a matter for carto people though not me.

**Comment by talllguy** [comment]
I understand. Thanks for the information.

**Comment by HolgerJeromin** [comment]
@talllguy you can watch https://github.com/openstreetmap/chef/commits/master for updates. Often (always?) you will see an [issue over there](https://github.com/openstreetmap/chef/issues?q=is%3Aissue+is%3Aclosed), too.

pnorman posted a mail on dev a few days ago.

**Comment by tomhughes** [comment]
Paul's email was actually about an upcoming change, not about this release.

**Comment by tomhughes** [comment]
Oh he did announce 3.1.0 as well.

**Comment by talllguy** [comment]
Thanks. We're talking about [this message](https://lists.openstreetmap.org/pipermail/dev/2017-January/029650.html) from @pnorman, which mentions https://github.com/openstreetmap/osm2pgsql/pull/668 , correct?

**Comment by tomhughes** [comment]
No https://lists.openstreetmap.org/pipermail/dev/2017-January/029673.html is the one I meant.
