### ISSUE TITLE
500 error when click edit if history of deleted way url active

### ISSUE THREAD

**Issue by EdLoach** [openstreetmap/openstreetmap-website#1430]
Take as an example [this way](http://www.openstreetmap.org/way/130344453/history) and try clicking edit. It also seems to occur most times when you just have [a deleted way](http://www.openstreetmap.org/way/130344453) link visible (I'm sure I had at least one time where it did work).

**Comment by tomhughes** [comment]
Both those seem to work fine for me.

**Comment by EdLoach** [comment]
OK, have tried again. Works fine for me on Chrome, Edge and Firefox but not Opera. Difference seems to be that Opera tries to open http://www.openstreetmap.org/edit?way=130344453 but the others (well, at least Chrome) just opens http://www.openstreetmap.org/edit

**Comment by tomhughes** [comment]
Ah it only happens if you move the map after loading the page.
