### ISSUE TITLE
contextmenu overwriting with shiftKey does not work

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/openstreetmap-website#1452]
Even after deploy of #1447 disabling the contextmenu does not work (tested in vivaldi and chrome)
`.contextmenu.disable()` is called now but the contextmenu is still shown.

Perhaps this is bug in Leaflet.contextmenu because only `'mouseleave'` and `'keydown'` are [deregistered](https://github.com/aratcliffe/Leaflet.contextmenu/blob/745e33a61b81b519cec13a22b1be16426d4f7434/src/Map.ContextMenu.js#L57-L59) with our `contextmenu.disable()` call. 

cc @danstowell

**Comment by tomhughes** [comment]
I kind of see the opposite in chrome - it is disabled the first time I shift click but then never re-enabled.

**Comment by danstowell** [comment]
I have Chromium here (Version 55.0.2883.87, on Ubuntu 16.04) and everything works as intended I'm afraid! A right-click gives our menu, a shift-right-click gives the browser's own menu. I have vanilla Chromium (I don't use it much, so don't install add-ons etc).

**Comment by tomhughes** [comment]
I think the issue is that you don't always get the mouseup event, depending on how the menu is dismissed.

**Comment by HolgerJeromin** [comment]
Perhaps your browser missed the `mouseup` event so it does not reenable anymore. Loosing events are not rare with mouse interaction so the whole concept (keeping mousedown and leaving the browser focus with a keyboard shortcut).
So the whole process is probably best done with keeping the events registered and calling preventDefault() in the eventhandler itself if shiftKey is pressed.

**Comment by tomhughes** [comment]
Yeah, the issue then is making sure the handler order is correct, plus leaflet unhelpfully calls preventDefault itself for contextmenu events if there are any handlers registered.

**Comment by tomhughes** [comment]
Let's see if ad0e829fc7711761ffc65d50b119a14757bba220 helps - it seems to for me with Chromium at least.

**Comment by HolgerJeromin** [comment]
Works here with vivaldi and chrome (windows 7). Seems not too ugly, too.
Thanks for the quick fix!
