### ISSUE TITLE
Subscribe to an object

### ISSUE THREAD

**Issue by andrewharvey** [openstreetmap/openstreetmap-website#1454]
It would be nice to be able to Subscribe to an object in OSM to receive a notification if that feature is changed.

There could be a setting allowing you to auto-subscribe to any object you touch.

This would benefit new users so they can see how their edits are improved over time and experienced users who can keep track of changes made to things they once touched.

**Comment by dieterdreist** [comment]
sent from a phone

> On 22 Feb 2017, at 05:20, Andrew Harvey <notifications@github.com> wrote:
> 
> It would be nice to be able to Subscribe to an object in OSM to receive a notification if that feature is changed.


likely you'd also want to get notifications if the shape of an object changes without the osm object changing (moving around nodes of a way or relation)

**Comment by andrewharvey** [comment]
> likely you'd also want to get notifications if the shape of an object changes without the osm object changing (moving around nodes of a way or relation)

Yes, I think the notification would trigger if the version of the osm object (node, way, relation) you're watching has increased. Hence tag changes, geometry changes both result in the version of the object increasing.

**Comment by dieterdreist** [comment]
sent from a phone

> On 22 Feb 2017, at 08:02, Andrew Harvey <notifications@github.com> wrote:
> 
> Yes, I think the notification would trigger if the version of the osm object (node, way, relation) you're watching has increased. Hence tag changes, geometry changes both result in the version of the object increasing.


no, geometry changes increase the version of nodes, but the version of ways and relations only increase if you change the members, not if you change the position of their node members

**Comment by Zverik** [comment]
So this should be an RSS feed not only for an object, but also for all of its members? The former is pretty simple to do, I guess.

**Comment by tomhughes** [comment]
I not sure subscribing to objects really makes much sense and it would probably quickly get out of control in terms of the number of subscription records.

What's really needed as we've known for a long time is a way to get some sort of subscription to an area that is actually accurate (ie only triggers when there are really changes in an area) but that's a hard problem. There already lots of tickets for it though I'm sure

So I'm going to close this as I don't think it would ever be practical to allow object level subscriptions.

**Comment by zerebubuth** [comment]
I should note that this was (one of) the original use-cases for [OWL](https://wiki.openstreetmap.org/wiki/OWL). Unfortunately, no version of OWL ever got to the point of deployment, although it is a service that many people would be interested in. If anyone would like to help out by figuring out what state the latest incarnation of OWL is in, and what needs to be done to finish it and deploy it, then that would be most welcome. Feel free to contact me, and I'll give whatever help I can.

**Comment by andrewharvey** [comment]
> So this should be an RSS feed not only for an object, but also for all of its members? The former is pretty simple to do, I guess.

Yes that's one way of addressing this. It might quickly turn into an unmanageable number of feeds to subscribe to though. A lot of the benefits I think come from being auto-subscribed once you make a change (if you've enabled auto-subscription).

> I not sure subscribing to objects really makes much sense and it would probably quickly get out of control in terms of the number of subscription records.

I haven't really thought about the implementation, just the feature would be nice to have to monitor places you know (since you've edited them in the past) but without the huge investment of looking through all changes in the bbox.

> What's really needed as we've known for a long time is a way to get some sort of subscription to an area that is actually accurate (ie only triggers when there are really changes in an area) but that's a hard problem. There already lots of tickets for it though I'm sure

I think that's a separate issue, a casual user with limited time to devote to OSM mightn't want to go through all the changes in their bbox, but they might be interested when the 10 features they've added to OSM over the last few months get changed by someone else.

> So I'm going to close this as I don't think it would ever be practical to allow object level subscriptions.

No problem. I unfortunately don't have the time to help out, just thought I would pass on the idea to see what others think.

**Comment by Zverik** [comment]
> I should note that this was (one of) the original use-cases for OWL. Unfortunately, no version of OWL ever got to the point of deployment, although it is a service that many people would be interested in. 

Most people subscribe to [WhoDidIt](https://wiki.openstreetmap.org/wiki/Quality_assurance#WhoDidIt) notifications these days.

Monitoring changes for _all_ changed objects is an overkill and will quickly get out of hand. And the load on the website would be quite high. Many mappers learn to let their contributions go and not burden themselves with guarding every change.

**Comment by bjohas** [comment]
Just to add my endorsement to this. I think being able to (selectively) subscribe to changes from iD / JOSM would be great. Certainly you wouldn't want to describe to everything, but there are certain things that tend to get broken, and it would be good to get updates. I think updates are also nice to discover whether other people are working on the objects.

http://osm-hall-monitor.herokuapp.com/ offers a service - maybe it could be integrated more tightly? Or maybe another solution could be found? 

+1
