### ISSUE TITLE
Block VWorld as a source

### ISSUE THREAD

**Issue by mxa** [openstreetmap/openstreetmap-website#1464]
In Korea there is a serious issue because people are using
http://xdworld.vworld.kr:8080/2d/Satellite/201612/{z}/{x}/{y}.jpeg
as a background and map their copyrighted imagery, making OSM a derived work. VWorld is a governmental source and is already informed about the situation.
Is it possible to blacklist the usage of VWorld as a source?
Presumably it is also related to Pokemon Go, we are trying to find out.

Issue opened here per request https://github.com/openstreetmap/iD/issues/3858#issuecomment-282079362

**Comment by tomhughes** [comment]
@mxa A PR to add it to the imagery blacklist at https://github.com/openstreetmap/openstreetmap-website/blob/master/config/example.application.yml#L89 is what is needed

@simonpoole I assume legal won't have an issue if we block this?

**Comment by simonpoole** [comment]
@tomhughes no problem (well actually "please do"
@mxa have you informed the DWG? An example changeset would be good, if they are using iD it is reasonably easy to track down use.

@woodpeck fyi

**Comment by Andygol** [comment]
>@mxa have you informed the DWG? An example changeset would be good,

@simonpoole I've informed @sev- (as I know his a member of DWG) about using this imagery in S.Korea.

There is [full list of changesets](http://osmcha.mapbox.com/?is_suspect=True&sort=-date&checked=All&imagery_used__icontains=xdworld.vworld.kr&is_whitelisted=True&harmful=False&page=1) where were used `xdworld.vworld.kr` ([*.CSV](http://osmcha.mapbox.com/?is_suspect=True&sort=-date&checked=All&imagery_used__icontains=xdworld.vworld.kr&is_whitelisted=True&harmful=False&page=1))

I left comments in this changesets but didn't receive any answer 
- http://osmcha.mapbox.com/45874798/
- http://osmcha.mapbox.com/45904089/
- http://osmcha.mapbox.com/45851607/
- http://osmcha.mapbox.com/45672805/

**Comment by simonpoole** [comment]
@bhousel what is expected behaviour supposed to be for blocked imagery in iD? I just created two changesets with the vworld imagery as background, even though the capability API call already returns the google and the vworld regexp.

**Comment by bhousel** [comment]
> @bhousel what is expected behaviour supposed to be for blocked imagery in iD? I just created two changesets with the vworld imagery as background, even though the capability API call already returns the google and the vworld regexp.

It should just silently fail to use the imagery and fallback to Bing.  So we can leave open  openstreetmap/iD#3858 to track the issue.

**Comment by mxa** [comment]
@Andygol I also left some comments (in English) but no answer.
@bhousel I think it should not fail silently, but it should give a message explaining why it is not ok to use non-licensed sources. In fact I think this warning message should pop up any time a custom background is used. If the source is blacklisted, it should say that.
btw, it still works, just tried it.

**Comment by pnorman** [comment]
No one has yet contacted the DWG, but we are aware of it now and have an issue open.

Let's keep this about what **this** issue is about, the addition to the block list. iD issues belong on their issue tracker, and changeset discussions aren't code bugs.
