### ISSUE TITLE
Grey Standard layer because of refused connection to tile server

### ISSUE THREAD

**Issue by persep** [openstreetmap/openstreetmap-website#1470]
Since this morning I get a grey layer when accessing [Openstreetmap ](https://www.openstreetmap.org/). That is a normal openstretmap site but only a grey background where the map should appear.

![clipboard03](https://cloud.githubusercontent.com/assets/1191676/23407649/3d28e02c-fdc5-11e6-933e-f411dbdfbf86.jpg)

By changing the map layer I have no problems with the Cycle, transport and humanitarian layers but the Standard one is all grey.

By using firefox's network inspector I can see that the tiles are not loading because there is no response from the tile server, I don't get any response or status.

If I try to load a tile like
`https://b.tile.openstreetmap.org/14/8184/6289.png`
I get the "Unable to connect" error page. But with a normal connection (without the s)
`http://b.tile.openstreetmap.org/14/8184/6289.png`
it loads fine.
I have a Windows 10 64 computer updated and firefox 51.0.1 32 bit. I tried deleting cache and cookies but it didn't work. Also tried with Chrome and Edge (latest versions) but it didn't work. i can access othet https sites like Google and Github without problems.

But I tried with Tor Browser and it did work loading both the normal and secure connection tiles.

**Comment by tomhughes** [comment]
This is not really a web site issue as it relates to the tile servers, so https://github.com/openstreetmap/operations/issues would be a better place to raise it.

If you can load http://tile.openstreetmap.org/cgi-bin/debug and tell me what "Cache server" it reports then I can investigate.

**Comment by persep** [comment]
Hi,
this is the tile debug:
tile.openstreetmap.org debug
`
Server Stats

Cache Server: culebre.openstreetmap.org

Render Server: orm.openstreetmap.org
Load Average: 148.46
File Status

world_boundaries-spherical.tgz last modified: Tue Jun 4 11:59:57 2013
simplified-land-polygons-complete-3857.zip last modified: Fri Jan 27 08:14:26 2017
ne_110m_admin_0_boundary_lines_land.zip last modified: Tue Jun 4 12:00:51 2013
land-polygons-split-3857.zip last modified: Fri Jan 27 08:14:47 2017
antarctica-icesheet-polygons-3857.zip last modified: Tue Feb 28 06:50:49 2017
antarctica-icesheet-outlines-3857.zip last modified: Tue Feb 28 06:51:00 2017
Browser Request Headers

HTTP_COOKIE: _osm_totp_token=442019
CONTEXT_DOCUMENT_ROOT: /srv/tile.openstreetmap.org/cgi-bin/
SERVER_SOFTWARE: Apache/2.4.18 (Ubuntu)
CONTEXT_PREFIX: /cgi-bin/
SERVER_SIGNATURE:
Apache/2.4.18 (Ubuntu) Server at tile.openstreetmap.org Port 80

REQUEST_METHOD: GET
SERVER_PROTOCOL: HTTP/1.0
QUERY_STRING:
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HTTP_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
HTTP_CONNECTION: keep-alive
SERVER_NAME: tile.openstreetmap.org
REMOTE_ADDR: 90.68.179.140
HTTP_VIA: 1.1 culebre.openstreetmap.org:3128 (squid/2.7.STABLE9)
SERVER_PORT: 80
SERVER_ADDR: 193.63.75.98
DOCUMENT_ROOT: /srv/tile.openstreetmap.org/html
SCRIPT_FILENAME: /srv/tile.openstreetmap.org/cgi-bin/debug
SERVER_ADMIN: webmaster@openstreetmap.org
SCRIPT_URI: http://tile.openstreetmap.org/cgi-bin/debug
HTTP_DNT: 1
HTTP_HOST: tile.openstreetmap.org
SCRIPT_URL: /cgi-bin/debug
HTTP_UPGRADE_INSECURE_REQUESTS: 1
HTTP_CACHE_CONTROL: max-age=518400
REQUEST_URI: /cgi-bin/debug
HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
GATEWAY_INTERFACE: CGI/1.1
SCRIPT_NAME: /cgi-bin/debug
REMOTE_PORT: 33218
HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.5
REQUEST_SCHEME: http
HTTP_ACCEPT_ENCODING: gzip, deflate
`

**Comment by tomhughes** [comment]
Thanks. That server had a disk replaced yesterday and it looks like the https server instance didn't come up properly afterwards. 

It should be fixed now.

**Comment by persep** [comment]
Work great now. Thanks
