### ISSUE TITLE
Ready OSM image

### ISSUE THREAD

**Issue by iagsav** [openstreetmap/openstreetmap-website#1474]
Hello! I try to install OSM website using your instructions. But I fails. May be you can create ready OSM VirtualBox (or another virtual) image? I think, it will be useful for more OSM users - developers.

**Comment by zerebubuth** [comment]
Hi!

We used to have a VirtualBox image, but it kept falling out of date as there was no one to maintain it and nobody was using it.

We do have a `Vagrantfile` in the project, so it should be possible to [install Vagrant](https://www.vagrantup.com/docs/installation/) and run `vagrant up` in the project root to get a working virtual machine.

Unfortunately, I don't know how well-used the Vagrant configuration is, and it might also fail. Please let us know if you run into any problems when running `vagrant up`, or which the VM it makes.

**Comment by tomhughes** [comment]
If somebody wants to step up to maintain one then fine we can add it but until then I'm going to close this - a vbox image wouldn't actually need any changes here anyway as far as I know.

**Comment by iagsav** [comment]
Thank you for your answers!
