### ISSUE TITLE
Error 500 when browsing way history

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/openstreetmap-website#1476]
https://www.openstreetmap.org/way/22786546/history
The error is consistent. The way has only 7 versions, so I believe this has something to do with the last version containing redacted nodes.

**Comment by Zverik** [comment]
The same with https://www.openstreetmap.org/relation/8536/history (just noticed this on #osm-dev).

**Comment by tomhughes** [comment]
Judging by the time it's taking to respond for me I'd say it's more likely it's just timing out.

**Comment by tomhughes** [comment]
Yep, it aborts after 30s which is the timeout for web views.

**Comment by Zverik** [comment]
But why a way with only 7 versions timeouts?

**Comment by pnorman** [comment]
> I believe this has something to do with the last version containing redacted nodes.

Unlikely, since that would imply a way containing a deleted node. The redact API can only be called on deleted objects.

> The same with https://www.openstreetmap.org/relation/8536/history (just noticed this on #osm-dev).

As also discussed on IRC at the same time, that case is exceptional and and related to leftover problems with the P1 API

**Comment by gravitystorm** [comment]
> The redact API can only be called on deleted objects.

Note that this is not accurate - the redact API can be called on any version of any object, so long as it is not the latest version.

https://github.com/gravitystorm/openstreetmap-website/blob/6c0501d62a72fe217c522bcbf0017926c7e30fd6/lib/redactable.rb#L14-L21

I'm sure that in most day-to-day cases the object is also deleted when the old versions are redacted, but for example during the licence change we redacted old versions of still-visible objects.

I thought I should clarify here in case it causes confusion in the future.
