### ISSUE TITLE
remove fake qqq locale upstream

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#1482]
Every time there's a merge from Translatewiki, it includes a fake qqq locale that TomH then deletes (e.g. https://github.com/openstreetmap/openstreetmap-website/commit/f4d2a01484a216cb8dd37671270694bdfec7a629 ). It would be good to fix this upstream.

**Comment by tomhughes** [comment]
So why on earth have you opened a ticket here, where there is literally nothing we can do about it.

I am already in communication with the Translatewiki people about it and have been ever since it started.

**Comment by tomhughes** [comment]
For the record @Nikerabbit mailed me two days ago to say he had forgotten that he promised to fix this and that was opening an issue in the Translatewiki tracker to remind himself.

**Comment by gravitystorm** [comment]
@tomhughes great, thanks for the updates. Hopefully it'll be fixed soon.

**Comment by Nikerabbit** [comment]
Fixed. Example: https://github.com/openstreetmap/openstreetmap-website/commit/c2ee6048589f670a9e909fe96a02da07878a1cdf

**Comment by gravitystorm** [comment]
Thanks @Nikerabbit !
