### ISSUE TITLE
Tests fail locally but not with travis

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/openstreetmap-website#1487]
Currently running the tests locally fail with 
```
  1) Failure:
ApiControllerTest#test_changes_start_end_valid [/home/simon/openstreetmap-website/test/controllers/api_controller_test.rb:357]:
Expected response to be a <success>, but was <500>


  2) Failure:
ApiControllerTest#test_changes_zoom_valid [/home/simon/openstreetmap-website/test/controllers/api_controller_test.rb:324]:
Expected response to be a <success>, but was <500>


  3) Failure:
ApiControllerTest#test_changes_simple [/home/simon/openstreetmap-website/test/controllers/api_controller_test.rb:283]:
Expected response to be a <success>, but was <500>


  4) Failure:
ApiControllerTest#test_changes_hours_valid [/home/simon/openstreetmap-website/test/controllers/api_controller_test.rb:345]:
Expected response to be a <success>, but was <500>

```
but not in the CI harness. At least one of the fails seems to be time of day related, if @gravitystorm doesn't jump on it, I'll investigate further.

**Comment by tomhughes** [comment]
You don't have the 3GL functions loaded in your database.

**Comment by simonpoole** [comment]
Seems as if my structure.sql  got reverted back to the one in the repo (likely by a git stash) and installing the functions in the test db was failing because it couldn't find the compiled library, re-running bundle exec rake db:migrate regenerated structure.sql and resolved the issue.

Sorry for the false alarm.
