### ISSUE TITLE
preview for diary posts

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/openstreetmap-website#1497]
It would be convenient to see a preview of the markdown code before publishing it.

**Comment by pnorman** [comment]
![image](https://cloud.githubusercontent.com/assets/1190866/24242521/33062fde-0f75-11e7-8580-714159a254ae.png)

The edit/preview button is on the right, like other places where Markdown is used. This might not be the clearest UI, but functionality exists.

**Comment by dieterdreist** [comment]
ooops, so sorry. I had not noticed it (had changed the osm language to local some days ago because of a workshop and must have missed it because of this).
