### ISSUE TITLE
Register & password reset problem

### ISSUE THREAD

**Issue by DaveF63** [openstreetmap/openstreetmap-website#1498]
Hi
![capture](https://cloud.githubusercontent.com/assets/9528328/24243601/8f9d08c4-0fb3-11e7-8ce1-b9b300c6a4d9.JPG)

A few new users registering or resetting passwords received errors when using this URL. When the '.example' was removed it worked as expected. Why is it there? Can it be removed?

**Comment by tomhughes** [comment]
Is that still happening now? There was a brief window last night when I think it was broken but it should be OK now as far as I know.

**Comment by Firefishy** [comment]
Confirmed fixed. It was broken for around a 30min window from around 18:25 to 18:53 GMT/UTC.
