### ISSUE TITLE
RSS/ATOM Feeds for OSM notes with GeoURI enabled

### ISSUE THREAD

**Issue by BoFFire** [openstreetmap/openstreetmap-website#1499]
Hi :)
**First issue :**

Can we improve interoperability of the "Notes RSS Feed" with ATOM Feed readers ?
It passed W3C RSS validation but there's a recommandation about ATOM.
`https://validator.w3.org/feed/check.cgi?url=http%3A//api.openstreetmap.org/api/0.6/notes/feed%3Fbbox%3D4.350452%252C36.217606%252C5.482965%252C36.895943`

**Second issue :**

When I get the feed of notes in my RSS reader and when I try to open the location of a single note in OSMAnd for example, it appears that GeoRSS doesn't tell OSMAnd where to find that note and find myself in Lon, 0 and Lat. 0
Can we make it explicit so that one single note can be opened in any editor supporting GeoURI affected to a single object ?

Concrete example : I'm using Flym as an RSS Reader on Android and I created a "note feed monitoring of this bbox" (It could be on any Reader RSSOwl, or anything else) :
`http://api.openstreetmap.org/api/0.6/notes/feed?bbox=4.350452%2C36.217606%2C5.482965%2C36.895943`

I get the feed no problem with an `<a href="http://api.openstreetmap.org/user/xyz">` in it.No problem.
I want to click on something "GeoURI ?" so that the "specific location of that note" could be opened with any editor or viewer I'm using, supporting GeoTagging "OSMAnd, Vespucci ...".
Not necessarilly opening the _content of the note_ but I need **only the position**.

In case of OSMAnd, I'll get the position, OK then I'll enable the Layer "OSM Notes" and get the notes on that position and _close_ it or _comment_ it or _resolve_ it.

Example : something such as
`<a href="geo:37.786971,-122.399677">`
or
`<a href="geo:37.786971,-122.399677;u=35">`

Résumé : Asking make it possible to retrieve Location of a note when it comes from and RSS/ATOM Feed.

Thank you for reading me,
Sincerely,
ButterflyOfFire from OSMAlgeria

Ressources :
https://tools.ietf.org/html/rfc5870
https://en.wikipedia.org/wiki/Geo_URI_scheme

**Comment by tomhughes** [comment]
Please don't report multiple issues in one ticket - it makes tickets impossible to close when things are completed.

The question of RSS vs Atom is just a matter of personal choice - there's no right or wrong really and in this case we want it to be GeoRSS and there's no equivalent for Atom as far as I know.

So lets just treat this as being about the second point - as you say most feed readers won't understand the extensions in GeoRSS that give the position so what you're asking for is an explicit link in the content to the location?

**Comment by BoFFire** [comment]
Sorry for reporting 2 issues in one :
Yes, just an explicit link in the content to the location.
If it is not possible I'll try manually to inject a GeoURI to somewhere in this RSSblockFeed to test :)
```
`      </description>
      <dc:creator>ButterflyOfFire_</dc:creator>
      <pubDate>Sat, 02 Apr 2016 08:54:00 +0000</pubDate>
      <geo:lat>36.8632886</geo:lat>
      <geo:long>4.8171901</geo:long>
      <georss:point>36.8632886 4.8171901</georss:point>
    </item>
````

**Comment by tomhughes** [comment]
The problem with geo URIs is that they are only really useful on mobile devices, but we have no way of knowing what sort of device with consume an RSS feed at the point that we serve it and they may just confuse users who are not on mobile devices.

**Comment by BoFFire** [comment]
@tomhughes :) Let's consider this as "not an issue" but an RSS feature not related with the website but only the RSS Feed builder (for monitoring/managing notes).
For example :
Hello this is OSM Feed of the day.
Oh woow nice :
_- Note number 123, created by user "porn" and posted comment : "PornDay Powaa in this location where $user is living"_
_- Note number 321, created by user "Noob" and posted a comment : "abcdefghijklmnopqrstuvwxyz"_
Oh nice, that's cool news from BBox OSM Notes to start the day. Why not try to take 1 minute with GeoURI and solve these when drinking coffee ?
And sorry again for my bad english.

**Comment by BoFFire** [comment]
And yes, the feed of Pascal Neis is in my reader ;)
http://resultmaps.neis-one.org/osm-notes
