### ISSUE TITLE
Enhancement: Add Delete button on read message window

### ISSUE THREAD

**Issue by katpatuka** [openstreetmap/openstreetmap-website#1504]
Adding a **Delete** button to the **Reply**, **Mark as unread** and **Back** buttons at the bottom of the read message window would be useful.

**Comment by hd719** [comment]
Hello can I work on this?

**Comment by katpatuka** [comment]
I'd be glad! No one else seems to be interested in this topic anyway... ;)

**Comment by tomhughes** [comment]
Sure - nobody else is as far as I know.
