### ISSUE TITLE
Changeset comments replies by direct message

### ISSUE THREAD

**Issue by tilmanb** [openstreetmap/openstreetmap-website#1505]
There seems to be a prominently placed option to reply to a changeset comment via direct message (that i cannot find in the code), more and more replies are coming by dm instead of by cs comment.
I think we should encourage users to reply to changeset comments via the changeset comment, and discourage them from replying by direct message, so that the discussion stays transparent.
If someone points me to the code / translation string, I could try to make a formulation proposal.

**Comment by tomhughes** [comment]
There's no such option as far as I know - they must just be clicking through to your user page and doing it from there.

Of course there may also be third party software using our API that is presenting such an option in a more prominent way.

**Comment by dieterdreist** [comment]
sent from a phone

> On 29 Mar 2017, at 15:13, Tom Hughes <notifications@github.com> wrote:
> 
> There's no such option as far as I know - they must just be clicking through to your user page and doing it from there.
> 

if you reply (via email) to the email that notifies about the changeset comment, will this become a direct message or a reply on the changeset discussion?

**Comment by tomhughes** [comment]
Reply via email is not support for changeset comments - it will just wind up in my support mailbox.
