### ISSUE TITLE
"Query features" marker on map disappears too quickly

### ISSUE THREAD

**Issue by Artoria2e5** [openstreetmap/openstreetmap-website#1514]
Users can currently use the "query features" context menu for reading out what lies near the mouse pointer. However, the only indication for where the user has asked for on the map is a circular orange marker that disappears pretty quickly. OpenStreetMap's website should probably fix this presentation to:

1. Keep the marker until the panel is closed. Show it as long as the user is not looking at another element.
2. Show lat/lon coordinates used in the query as a uniform reference. This is part of the "show us the coordinates" plot.

**Comment by tomhughes** [comment]
Personally I don't see any need for this - the next thing you normally do is to hover over features in the side panel which then highlights them on the map.

The disappearing circle is mostly just there to provide feedback that the click worked and what area it will be looking over so you can try again if it didn't quite cover what you wanted.

**Comment by Artoria2e5** [comment]
> you can try again if it didn't quite cover what you wanted.

Makes sense.

**Comment by mmd-osm** [comment]
OP seemed ok with explanation given, closing here.
