### ISSUE TITLE
https://www.openstreetmap.org/id does not load something

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/openstreetmap-website#1518]
I have no idea if this url should work, but i just clicked on the link on a [changeset](https://www.openstreetmap.org/changeset/47519897).

Google Chrome does not load anything because
parent.$ of code parent.$.throttle in the id code was not defined.

I just learned that this url is in edit mode is embedded in a iframe and at this time there is more stuff loaded from the hosting html. So i am not sure if this is an iD, an integration problem or is even a problem :-)

**Comment by bhousel** [comment]
That host tag comes from iD, [this line of code](https://github.com/openstreetmap/iD/blob/eb62e22a375aa0fa689befa9b1c3560dcbf1e8bf/modules/util/detect.js#L102)

You're right that `window.location` when embedded in an iframe is not the true location.  We could and maybe should use `window.top.location` instead when iD is embedded.  I'll open an ticket on the iD repo for discussion..

**Comment by HolgerJeromin** [comment]
Setting that would result in osm.org/edit
I am not sure if this is a better value to save

**Comment by HolgerJeromin** [comment]
Perhaps id should check if all needed libraries are loaded and abort gracefully with a message in the body. This could contain a link to the osm main page.

**Comment by tomhughes** [comment]
I'm terminally confused... What exactly were the steps you did to trigger this @HolgerJeromin? You say you clicked "the link" on a changeset but it's not really clear what link exactly and I don't see why the changeset view would have an undecorated link to the id page of the type shown in the title of this bug...

What I really want to know though is whether there is actually an OSM bug here? @bhousel seems to be saying it's an iD bug?

**Comment by HolgerJeromin** [comment]
I clicked this link

![image](https://cloud.githubusercontent.com/assets/2410353/24788647/f24932f6-1b6e-11e7-86a7-2f63fd28f2df.png)

 and got a white page

**Comment by simonpoole** [comment]
I suspect that simply shouldn't be linkified to start with as it is simply a pointer to the instance of iD that was used for the changeset, not really a useful thing to click on.

**Comment by bhousel** [comment]
I think it can be closed here.. Moved to https://github.com/openstreetmap/iD/issues/3950

AFAIK we are the only editor generating a `host` tag.  I do think it's reasonable that if we put a URL there, it should be something that a user can actually click on.
