### ISSUE TITLE
bundle install fails with "Could not find openstreetmap-omniauth-google-oauth2-0.2.6.1"

### ISSUE THREAD

**Issue by danstowell** [openstreetmap/openstreetmap-website#1520]
Following through INSTALL.md on this ubuntu 16.04 machine, I get stuck after installing all the system dependencies, with:

<pre>
(..sm/openstreetmap-website) % bundle install
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Could not find openstreetmap-omniauth-google-oauth2-0.2.6.1 in any of the sources
zsh: exit 7     bundle install
</pre>

I have found a project at https://github.com/zquestz/omniauth-google-oauth2 but if it's somehow needed manually for successful installation of osm-website, I don't see it in the instructions.

**Comment by tomhughes** [comment]
Nothing in our Gemfile requires that gem so this appears to be user error.

**Comment by tomhughes** [comment]
Note that we did require that special patched version at one point but once upstream was fixed we went back to upstream - the current requirement (https://github.com/openstreetmap/openstreetmap-website/blob/master/Gemfile#L64) is for omniauth-google-oauth2 (no openstreetmap- prefix) version 0.2.7 or later.

**Comment by tomhughes** [comment]
I note that your fork (https://github.com/danstowell/openstreetmap-website/blob/master/Gemfile#L60) is from the time when we did have that require so I suspect that contrary to what you said on IRC you were trying to run your very out of date copy of master not the actual master.

**Comment by danstowell** [comment]
Darn. Yes I was pulling latest, but not from upstream osm. (Forgot about my "convenient" git remote config.) Thanks
