### ISSUE TITLE
Export creates font rendering errors

### ISSUE THREAD

**Issue by jc86035** [openstreetmap/openstreetmap-website#1523]
Exporting using [this link](http://render.openstreetmap.org/cgi-bin/export?bbox=114.1491,22.2681,114.2044,22.3268&scale=12000&format=svg) causes a strange font rendering error, where the railway station names are sized incorrectly and have the wrong spacing between characters. (I think a cookie from a normal export using the Share tab is required before the link works.)

<img width="591" alt="Screenshot of the export" src="https://cloud.githubusercontent.com/assets/3948362/25302743/b82b0ff8-2777-11e7-812d-1b053fa48fac.png">

Oddly, this doesn't happen with [the PNG export at the same zoom level](http://render.openstreetmap.org/cgi-bin/export?bbox=114.1491,22.2681,114.2044,22.3268&scale=12000&format=png) or [an SVG export with the same bounding box at 1:20000](http://render.openstreetmap.org/cgi-bin/export?bbox=114.1491,22.2681,114.2044,22.3268&scale=20000&format=svg).

**Comment by tomhughes** [comment]
Export uses exactly the same rendering engine and rules as the normal map tiles so any issue here is either in the stylesheet or in mapnik.

**Comment by HolgerJeromin** [comment]
or even in the used SVG renderer that @jc86035 has used.

**Comment by jc86035** [comment]
I don't think it's a problem with the renderer (I used Safari since it loads quickly, but it also happens in Inkscape), since every object should have been converted to a path by Mapnik.

**Comment by tomhughes** [comment]
It's very dependent on what you export though - a smaller area at the same scale doesn't seem to do it so I'm going with a mapnik issue related to exactly what other labels etc the collision detection sees.
