### ISSUE TITLE
Deliver some assets with HTTP Header Cache-Control: immutable 

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/openstreetmap-website#1525]
Some stuff are served with a path which seems to be a MD5 hash
menu-icon-ba3407aa1c5ff7b2153008abeb7f8789165716ecc0195a606d4569d0e8e0b716.png

If this is the case the browser will never ever will get an other file when requesting this resource. 
Modern browsers support the HTTP Header `Cache-Control: immutable` for such things. 
See this blog about it:
http://bitsup.blogspot.de/2016/05/cache-control-immutable.html

**Comment by tomhughes** [comment]
We already send a long expiry and I see no point in sending something non-standard. If and when it is standardised we can look at it.

**Comment by HolgerJeromin** [comment]
Hitting reload results in a roundtrip for the 304. 
Cache-Control: max-age=365000000, immutable
Is valid according to the standard.

**Comment by tomhughes** [comment]
What standard? That blog post talks about possibly standardising it in the future as far as I can see.

**Comment by tomhughes** [comment]
In any case it's an operational/chef issue, not a code issue.

**Comment by HolgerJeromin** [comment]
But perhaps this is really not needed as the browser are changing:

FYI: "Chrome no longer forces validation on reload, so immutable shouldn't be necessary." from https://bugs.chromium.org/p/chromium/issues/detail?id=611416#c12
