### ISSUE TITLE
410 when viewing XML for deleted node

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/openstreetmap-website#1526]
I apologize if there is already an issue for this, but when you are viewing information about a deleted node and click "Download XML", it displays a 410 error.
To view the history, you need to click "View History", and then download the XML, returning no errors.
View this here: [http://www.openstreetmap.org/node/4811474463](http://www.openstreetmap.org/node/4811474463)

Maybe a function that checks if the node exists is needed and the download XML box will only show if this is the case?

**Comment by tomhughes** [comment]
That is expected as 410 is the HTTP status for "Gone" and that entity no longer exists so that is the correct status.

The error, if there is one, is providing links to an API in a user facing web interface.
