### ISSUE TITLE
Incorrect preposition when someone comments on someone else's diary entry you have commented on

### ISSUE THREAD

**Issue by smsm1** [openstreetmap/openstreetmap-website#1531]
I have commented and am following a diary entry and got the an email about the following new comment on the diary entry: http://www.openstreetmap.org/user/joost%20schouppe/diary/40854#comment38351

The subject of the email is:
"[OpenStreetMap] SimonPoole commented on your diary entry"

Whilst it should say:
"[OpenStreetMap] SimonPoole commented on a diary entry you commented on"
or 
"[OpenStreetMap] SimonPoole commented on a diary entry you are following"

Similarly for the message body:
"SimonPoole has commented on your recent OpenStreetMap diary entry with the subject Missing Maps Mapathons as a recruiting instrument:"
It's not my diary entry, so it should instead say something like:
"SimonPoole has commented on a recent OpenStreetMap diary entry you are following with the subject Missing Maps Mapathons as a recruiting instrument:

**Comment by tomhughes** [comment]
So go fix it on Translatewiki.

**Comment by smsm1** [comment]
I suspect it should be 2 separate emails with slightly different wording being sent out. One for where you are the author of the diary entry, and another for when when you are a subscriber of the comments but not the author. The current wording works when you are the author of the diary entry.

**Comment by tomhughes** [comment]
No the problem is that the text in the `en` messages was changed to make sense when subscriptions were added but the `en-GB` translation has never been fixed so makes no sense.

**Comment by tomhughes** [comment]
The `en` text is just "[OpenStreetMap] %{user} commented on a diary entry" now.

**Comment by smsm1** [comment]
Sure, I've updated them now.

**Comment by smsm1** [comment]
Thanks for the additional details.
