### ISSUE TITLE
Search results panel should show results for both lat,lon and lon,lat when pasting in co-ordinates

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/openstreetmap-website#1532]
Currently, if you paste in co-ordinates into the search box on the OSM home page, the result given assumes this to be in the order lat,lon:

![result](https://cloud.githubusercontent.com/assets/361423/25534534/f5c6d8c0-2c2b-11e7-834b-6f5ca929fb73.jpg)

However, various systems use the order lon,lat (and I make no comment either way on this!).

It would be useful if the results screen could show both orders, as per this example from a CycleStreets search:

![better](https://cloud.githubusercontent.com/assets/361423/25534655/5c6afff2-2c2c-11e7-930f-b667ab8fe952.jpg)

This would remove the friction of having to do a "cut, remove comma, move mouse cursor, re-add comma, paste" operation.

**Comment by dieterdreist** [comment]
sent from a phone

> On 28. Apr 2017, at 17:05, Martin <notifications@github.com> wrote:
> 
> It would be useful if the results screen could show both orders, as per this example from a CycleStreets search:


especially if one of the values is between 90 and 180 (plus minus) and the other is between-90 and +90, it could be assumed to be a longitude, currently you get an "latitude is out of range" error

**Comment by mvl22** [comment]
I see that both now appear, so as this is now working I will close this ticket.

![Screen Shot 2020-08-28 at 17 32 12](https://user-images.githubusercontent.com/361423/91591210-79e81900-e954-11ea-9c00-1d8eebd47bdf.png)
