### ISSUE TITLE
consider blacklisting HERE imagery

### ISSUE THREAD

**Issue by richlv** [openstreetmap/openstreetmap-website#1536]
as per https://www.openstreetmap.org/changeset/44590020 , looks like somebody has used HERE imagery to update openstreetmap. it might be worth blacklisting the imagery url.

**Comment by simonpoole** [comment]
IMHO we can probably disallow ".*\\.here\\.com/.*" given that it is highly unlikely that will match any legit source.

**Comment by simonpoole** [comment]
https://github.com/openstreetmap/openstreetmap-website/pull/1537
