### ISSUE TITLE
Add New Image Availability Announcement

### ISSUE THREAD

**Issue by cliffordsnow** [openstreetmap/openstreetmap-website#1541]
Can we get an announcement of the new DigitalGlobe background images added to the website? Not use that occasional users are aware of updated imagery.

**Comment by tomhughes** [comment]
Seriously, no. Announcements are for the blog not the web site.

**Comment by cliffordsnow** [comment]
Seriously, Yes - Because only a small fraction read the blog. Provide a link to the blog. But let's get the word out that imagery other than Bing exists.

**Comment by simonpoole** [comment]
@cliffordsnow there is currently no news facility on the website. It was originally included in the mockups for the Knight Foundation financed redo of the website, but was never implemented (likely because the money ran out, or was used for iD or whatever).

**Comment by HolgerJeromin** [comment]
I have not checked them myself but they seems to be mainly useful where Bing is not available or really bad. 
Providing a hint for other imagery is the job of the editors, not the website.

**Comment by tomhughes** [comment]
If editors are not defaulting to the best imagery for an area then the solution is to fix the imagery index.

**Comment by polarbearing** [comment]
@cliffordsnow - we have maybe a thousand OSM-compatible layers in the governmental geo-portal in Berlin, including perfect annual orthophotos. So I educate new mappers from my experience what is best to use in my region, and how to do it, I cannot expect to have that all posted. 
As for the MOTD, woudn't it be good to open a ticket in [iD](/openstreetmap/iD) then?

**Comment by simonpoole** [comment]
@tomhughes in general the editors do default to the best imagery for the non-global sources. The problem with bing vs DG (or any global layer) is that "somebody" would actually have to grade the imagery and provide polygons where one or the other is best (taking in to account all other sources on top). 

That is naturally unlikely to happen, besides the all the other problems: moving target, likely so many polygons that the editors would blow up and so on. 

Note on the side: bing in principle can provide max zoom meta-data per region that could be used to determine if the imagery is hi-res or not.
