### ISSUE TITLE
ActiveRecord::RecordNotUnique error occurs when save .

### ISSUE THREAD

**Issue by sophia-xll** [openstreetmap/openstreetmap-website#1542]
I have an osm data. Both node and way ids are increasing from 1,so it is with changset. I use postgresql database to store , openstreetmap-website to show, and ID editor to edit. All works well when edit. However, When I try to save , It occurs error:
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "changsets_pkey" DETAIL: Key (id)=(1) already exists. : INSERT INTO "changesets" ("created_at", "user_id") VALUES ($1, $2, $3) RETURNING "id"
Click save button again ,it occurs error:
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "current_nodes_pkey1" DETAIL: Key (id)=(1) already exists. : INSERT INTO "current_nodes" ("latitude", "longitude", "changeset_id", "version", "visible", "timestamp", "tile") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"
I guess id editor save node,way and changeset using ids increasing from 1. If I am right ,How to edit osm data which ids increasing from 1?

**Comment by tomhughes** [comment]
This is not a bug - you have apparently loaded data into your database via a backdoor somehow without updating the sequences to reflect those changes.

**Comment by sophia-xll** [comment]
I describe my operation steps as following:
1. download an a.osm data from osm website.
2. renumber the a.osm data using osmium tools. Here the minimum of node_id is 1. 
3. import the renumbered osm data into postgresql database using osmosis tools.
4. I edit the data within local deployment environment of openstreetmap-website using ID editor.
5. when i save the data, the frontend told me the above error(duplicate key value violates unique constraint).
how can i update the sequences as you said？
thanks for your help.

**Comment by simonpoole** [comment]
As @tomhughes has already pointed out: new ids in the database are allocated from sequences, so you need to determine the highest id per OSM object from your import and set the sequences to that (+1 likely).

**Comment by tomhughes** [comment]
It's not a conversation for a bug really anyway - loading data into an API database is not really a supported operation because it's not something we ever need to do.

I suggest asking on the mailing list or IRC and see if somebody is able to help you.

**Comment by bhousel** [comment]
@sophia-xll use `ALTER SEQUENCE` to update the sequence nextval before you start inserting records, otherwise postgres will try to start with 1.
https://www.postgresql.org/docs/current/static/sql-altersequence.html

**Comment by tomhughes** [comment]
To be honest I thought osmosis did that for you if you used it right, but I'm no osmosis expert and this isn't the place to ask for help for osmosis or to report a bug in it.

**Comment by sophia-xll** [comment]
Thanks for all the reply. According to  the answers above, I use "ALTER SEQUENCE changesets_id_seq RESTART WITH 47065503;" to sql , now it works well.
