### ISSUE TITLE
Forum question on how to update wiki_pages.yml

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#1552]
Reporting this on behalf of some users on the [German forum](https://forum.openstreetmap.org/viewtopic.php?pid=647928#p647928).

The forum question was basically about the process to get wiki_pages.yml updated and what the current update interval is. That file appears to have been automatically created by some script around 2 years ago. It now lacks some recent additions like man_made=pumping_station, so that no hyperlink is being rendered for those newer tag values:

![image](https://www2.pic-upload.de/img/33229214/1.png)

**Comment by tomhughes** [comment]
There's a script in the repository (script/misc/update-wiki-pages) so run it and open a PR if you want them updated.

**Comment by mmd-osm** [comment]
[x] done.
