### ISSUE TITLE
NoMethodError in SiteController#index:undefined method `access_token_for_user' for nil:NilClass

### ISSUE THREAD

**Issue by sophia-xll** [openstreetmap/openstreetmap-website#1559]
Hello everyone! 
    I can use ID editor to save after configuring OAuth consumer keys ,through 'http://172.17.0.1:6300/edit?editor=id#map=16/40.1665/124.3288'. But I cannot open 'http://172.17.0.1:6300/#map=16/40.1665/124.3288' . Error is 'NoMethodError in SiteController#index :undefined method `access_token_for_user' for nil:NilClass' . 
    I have no idea,Thanks for any help.

![default](https://user-images.githubusercontent.com/25217255/26915049-efb28a74-4c56-11e7-8ed1-74a35779c872.png)

**Comment by tomhughes** [comment]
This appears to be a configuration error in your environment and not a bug in the web site code.

**Comment by tomhughes** [comment]
My best guess is that you're configured your keys wrong - it can't seem to find a `client_application` record in the database for the key that something (presumably iD) is passing.
