### ISSUE TITLE
Duplicate values on display_name attribute.

### ISSUE THREAD

**Issue by ardean80** [openstreetmap/openstreetmap-website#1560]
Hi. 
I'm trying to apply with osmosis the day diff [#1726](http://planet.openstreetmap.org/replication/day/000/001/726.osc.gz) to my osm apidb, but I got this error: _duplicate key value violates unique constraint "users_display_name_idx"_. 
This happens because, apparently, two users (whose ids are [6115593](http://www.openstreetmap.org/api/0.6/user/6115593) and [4518891](http://www.openstreetmap.org/api/0.6/user/4518891)) have the same display_name ("Андрей Б"), but this should not be possible, according to the current osm apidb [schema](https://github.com/openstreetmap/openstreetmap-website/blob/master/db/structure.sql). 
How could this happen on OSM? What should I do in order to address this issue?

**Comment by tomhughes** [comment]
Perfectly possible if users have changed their name over time and you are working with dumps that reflect the name they had at that time.

As to solutions, well that's a matter for the author of whatever tool you are using to do the import. Maybe just drop the names and assign machine generated ones?

**Comment by ardean80** [comment]
I see. Users can change their names at any time...but it should not be possible, according to the osm apidb schema, to set one's name with the same value of another user's name. Instead this is the scenario I see if I check those users' details with OSM APIs, because thow two users _currently_ have the same name.
In some way the diff data coming from OSM are not correct, because they violate the unique index costraint on display_name attribute and this doesn't seem a problem related to osmosis.

**Comment by tomhughes** [comment]
The diff data is correct at time of generation but (obviously) we don't go back and regenerate every diff when somebody changes their name so old diffs will refer to them by their old name.

We do not provide any tools to import to an api database from diffs, and it is not an operation we support, so you will have to seek help elsewhere - if you are using osmosis to do the load then that would be the place to ask as they have chosen to provide a tool to load diffs into an apidb that apparently doesn't handle the case where names change.

**Comment by gravitystorm** [comment]
@tomhughes you've been distracted by the mention of diffs. @ardean80 has linked to the two users, who both have the same display name *right now*, according to the XML API.

> two users (whose ids are [6115593](http://www.openstreetmap.org/api/0.6/user/6115593) and [4518891](http://www.openstreetmap.org/api/0.6/user/4518891)) have the same display_name ("Андрей Б")

I couldn't find any difference between them by looking at the hex values of the strings copied from the XML:

```
'Андрей Б'.unpack('H*')
=> ["d090d0bdd0b4d180d0b5d0b920d091"]
```
I'm guessing there must be another character in the database record that allows them to pass the uniqueness tests, but that is being stripped out when the XML is being built. Or perhaps it's a combining character issue? If someone with db access could have a look at the strings that might prove useful.

**Comment by tomhughes** [comment]
That appears to be the result of index corruption having allowed the second account to be created - the data does (as far as I can tell) appear to be exactly the same but an index lookup only finds the more recent one. Trying to create a new unique index on the field fails and reports a duplicate on that record.

**Comment by ardean80** [comment]
Ok. So how could this be solved on the OSM apidb side? Are you going to change one of the two names in order to reestabilish the uniqueness?

**Comment by tomhughes** [comment]
That's an operational issue but yes, I am working to resolve it.

**Comment by ardean80** [comment]
Ok, thank you. :)
