### ISSUE TITLE
OSM Cycling layer legend

### ISSUE THREAD

**Issue by FrenchyF** [openstreetmap/openstreetmap-website#1564]
The legend on the OSM cycling layer doesn't explain what the small blue dots (for bike racks with a capacity below 20) on the map are. Can this be fixed?

**Comment by tomhughes** [comment]
Sure if somebody provides a key we can add it.

**Comment by FrenchyF** [comment]
Thanks. What exactly do you need?

An image for the small bike racks symbol should be attached. The key should say "Bicycle parking (small)", and the entry in the current key should be changed to "Bicycle parking (large,with capacity)"
![bicycle_parking_small](https://user-images.githubusercontent.com/29601726/27385642-386987b6-568b-11e7-928e-4906f193e464.png)

**Comment by tomhughes** [comment]
A patch against https://github.com/openstreetmap/openstreetmap-website/blob/master/config/key.yml with the relevant additional images and any changes to https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/en.yml#L1428 that may be required.

**Comment by tomhughes** [comment]
The key for the cycle layer was added in #1004 so that should give a good idea of how it works.
