### ISSUE TITLE
Missing feature tests

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#1570]
Our test suite is heavily focussed on controller and model tests. Unfortunately this means that very little of the site is actually tested, that is, very few of the tests render the views, or check that links are working and pointing in the right place etc. The controller tests don't render views, and each controller method is directly tested, rather than using the routes.

This means that problems crop up even though all the tests pass - see e.g. https://github.com/openstreetmap/openstreetmap-website/commit/117f0e82260efba3c6862e3aefa4b015b062a109

The advice I've read over the years is to focus less on controller tests, and more on feature tests - where a web browser is used to render the html, click on links etc. I find this works well in my other projects.

I would suggest we do some or all of the following, but of course I'm open to suggestions:
* Add feature tests to catch all the problems in the commit mentioned above
* Ensure that the signup flow works using feature tests
* Consider replacing the non-API, non-XML/RSS controller tests as feature tests

**Comment by tomhughes** [comment]
Adding tests for the things in that commit is on my to do list for this evening ;-) I only pushed it without tests to get it out ASAP.

**Comment by tomhughes** [comment]
It's not true that controller tests don't render views by the way - they absolutely do.

**Comment by gravitystorm** [comment]
> It's not true that controller tests don't render views by the way - they absolutely do.

My mistake. Minitest (and rails, by default) have different setup and naming to what I'm used to with RSpec.

The tests were added in fe1e28b4f45f6aa4bb53dc5163c187c5206b66a7 . I will make sure to add "[system](http://guides.rubyonrails.org/testing.html#system-testing)" tests instead of controller tests in future pull requests (e.g. `visit login_url`, `fill_in :email, :with => user.email` etc). But I won't keep this issue open here given there's no further specific actions required.

**Comment by tomhughes** [comment]
Hmm I thought you were referring to integration tests - system tests (which I wasn't aware of) use capybara and rely on an actual browser of some sort so there needs to be some thought and investigation before we start using those.

We do have a handful of experimental javascript tests that worked in that way although I think they may be broken since the rails 5 upgrade as I had to comment out konacha in the gemfile - those tests aren't run by default.

**Comment by tomhughes** [comment]
Also system tests are new in rails 5.1 and we're only on 5.0 at the moment as composite_primary_keys doesn't support 5.1 yet. So I guess we need to wait on https://github.com/composite-primary-keys/composite_primary_keys/pull/404 before we can consider this.
