### ISSUE TITLE
HTTP error 422 on creating notes

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/openstreetmap-website#1571]
I am getting error reports from users who use [osmapi](https://github.com/westnordost/osmapi) (OSM API 0.6 client implementation) since today 4 PM CEST that the OSM API gives them a

`422 Unprocessable Entity`

error.

**Comment by westnordost** [comment]
While investigating, I ran the test cases in osmapi again. They fail for notes.

An example call that is made is:
https://master.apis.dev.openstreetmap.org/api/0.6/notes?lat=-21.0&lon=94.0&text=test+case

The API returns

`No l was given`.

Apparently, the call now expects the following parameters: `l`, `r`, `t` and `b`. This is clearly an error.

**Comment by simonpoole** [comment]
I can confirm the error, at least against dev.

**Comment by tomhughes** [comment]
Most likely either an `ActionController::InvalidAuthenticityToken` or `ActionController::InvalidCrossOriginRequest` exception is being thrown - both lead to that status code being returned.

**Comment by westnordost** [comment]
And rolled out already (at least on dev), thank you :-)
