### ISSUE TITLE
Request: Add Autocomplete for Addresses and Places Search

### ISSUE THREAD

**Issue by renziver** [openstreetmap/openstreetmap-website#1572]
I think it would be useful if the there is a autocomplete feature in the search bar even before the user hit the search or enter button.

<img width="442" alt="screen shot 2017-07-03 at 9 54 59 am" src="https://user-images.githubusercontent.com/13497174/27775557-c3a7feae-5fd5-11e7-9b0c-59726fb2b68c.png">

**Comment by tomhughes** [comment]
Auto-complete is not supported by our geocoder and attempting to do it is therefore banned by the usage policy (https://operations.osmfoundation.org/policies/nominatim/) so we cannot do this as things stand.
