### ISSUE TITLE
Add banners for SOTM(s) 2017

### ISSUE THREAD

**Issue by RobJN** [openstreetmap/openstreetmap-website#1579]
Hi all,

We are just over a month away from SotM 2017. Although we have had success in signing people up to our email newsletter, the banner on osm.org option still drives a lot of traffic to our (and sister) sites.

Last year @bhousel coordinated via #1240

- Are we okay to do banners again?
- Cheeky request, but are there any volunteers to do the design work for the banner if I share the logo? If not then the SotM WG team can find time.

**Comment by tomhughes** [comment]
Yes of course it's ok (rather I'd say WTF have you left it until now).

No we don't have any designers hanging around.

**Comment by bhousel** [comment]
See #1580 which adds a FAQ and some information about creating banner images.
