### ISSUE TITLE
Generate HTTPS links in user-messaging notices

### ISSUE THREAD

**Issue by muralito** [openstreetmap/openstreetmap-website#1581]
The links generated in the user-messaging notices, sent to useres by mail,  are using HTTP protocol.
It would be better to direct the user to HTTPS to protect privacy.

http://www.openstreetmap.org/message/read/<msgnumber>
http://www.openstreetmap.org/message/reply/<msgnumber>

**Comment by tomhughes** [comment]
This comes under the general heading of "things we're not going to change until we decide to go https by default" I think. See many previous bugs for details.

**Comment by muralito** [comment]
OK, understood, then i would suggest that the notice does not contain any link, rather than contain HTTP links.
