### ISSUE TITLE
Close layer panel upon selection

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1589]
The layers panel, mentioned in
https://github.com/openstreetmap/openstreetmap-website/issues/1551 really should close as soon as the user has made a choice. You really shouldn't have the user poking around trying to find that little X. I mean it's not like you allow him to choose more than one layer. So you might as well close the panel as soon as he has made a choice. Yes, in the case he also wants to select something from the bottom well, he will yes, need to come back again. But for 95% of the cases, it would save him a step if the panel closed right away.

**Comment by tomhughes** [comment]
Sorry, but I disagree. I imagine it's quite common for people to browse through the different layers to see what they look like and having it close each time would be very annoying.
