### ISSUE TITLE
Issue when logging in if account is suspended

### ISSUE THREAD

**Issue by n42k** [openstreetmap/openstreetmap-website#1590]
When you try to login with a suspended account, it doesn't render the HTML and instead displays it as text:
`Sorry, your account has been suspended due to suspicious activity.<br />Please contact the <a href="mailto:support@openstreetmap.org">webmaster</a> if you wish to discuss this.`

![screenshot_2017-07-18_23-26-16](https://user-images.githubusercontent.com/1624180/28342541-bf50a9b8-6c10-11e7-9088-30c989b4a910.png)

**Comment by tomhughes** [comment]
I suspect it rather depends on the exact route you followed when logging in, but in general there are tricky sanitisation issues involved.

Where (if anywhere) were you referred back to by the login? or was that at the top of the login page itself?

**Comment by n42k** [comment]
I believe I logged in at [https://www.openstreetmap.org/login?referer=%2Fdiary](https://www.openstreetmap.org/login?referer=%2Fdiary) or [https://www.openstreetmap.org/login?referer=%2Flogin%3Freferer%3D%252Fdiary%252Fnew](https://www.openstreetmap.org/login?referer=%2Flogin%3Freferer%3D%252Fdiary%252Fnew), and the error message was displayed below the 'Login' bar in the header.

As a side note, thanks for unlocking my account!
