### ISSUE TITLE
Add tag key and value max length to capabilities API call

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/openstreetmap-website#1593]
See https://github.com/MarcusWolschon/osmeditor4android/issues/590 will document and create a PR if nobody beats me to it when i'm back from vacation.

**Comment by simonpoole** [comment]
Joting this down mainly for my benefit.

The root cause here seems to be a railsism that the default string length in rails is 255 characters that is mapped to character varying(255) (in PGSQL) , the down side of this is that the code is peppered with explicit references to 255 (range checking etc). From an API pov this effects at least tag key, value lengths on objects and changesets and role values for relation members. 

IM(very)HO I would refactor the code to reference a configuration value for the string length which means adding explicit limit values where necessary, this would touch a fair amount of code. One could argue that this a lot of work just so that we can actually return a max value that could in principle be set different per rails-port instance. 

@gravitystorm and @tomhughes any opinion?

**Comment by tomhughes** [comment]
I don't understand what your goal is - are you running an alternate installation of the code that you want to have a different limit?

The limit is almost certainly accidental and/or arbitrary. Certainly with postgres there is really no advantage to specifying a limit in the type - the on disk representation for `text` and `varchar(N)` is identical. All the latter form does is make the database police a maximum length.

**Comment by smsm1** [comment]
The history of the limit is from the MySQL days, and it was decided that keeping the limit would be best for consistency, and also to prevent people from writing an essay in a key/value pair. 

It's reasonable to hard code this value in the apps as it's not a config that will very unlikely change, it's been the same value since probably the beginning of OSM, so the likelihood of it changing is low.

**Comment by simonpoole** [comment]
@smsm1 even if the value never changes there is (well in every programming language that I'm reasonably fluent in, which doesn't include rails) a programming style issue in that there are numerous references to 255 sprinkled around the code instead of it being a constant.

In any case I've documented the limit now: http://wiki.openstreetmap.org/wiki/API_v0.6#Maximum_string_lengths and while 255 would seem to be shortish for some of the strings (changeset tags at least), if nobody feels particularly strong about the issue, there is no point in undertaking the effort.

**Comment by smsm1** [comment]
I agree a constant of some form would be a more consistent, and if I was implementing the code from scratch, would use a constant instead. 

I thought the max string length had already been documented on the API pages.

**Comment by HarelM** [comment]
Continuing from issue #1702, any chance to change this limit?
I wanted to add a description to a point I was editing from my site which uses the API and got to this limitation pretty fast - meaning the description is very partial when limited to 255 characters.
