### ISSUE TITLE
Update OSM API v0.6 documentation on trace PUT, DELETE

### ISSUE THREAD

**Issue by HarelM** [openstreetmap/openstreetmap-website#1596]
Hi,

Can you please update the API documentation regarding PUT and DELETE methods for user traces?
Following this question:
https://help.openstreetmap.org/questions/8725/is-there-an-api-to-modify-gpx-metadata
I couldn't find it here:
http://wiki.openstreetmap.org/wiki/API_v0.6
Probably needs a xml example too.

Thanks! Keep up the good work!

**Comment by tomhughes** [comment]
The API documentation in the wiki is user contributed and is nothing to do with us.

**Comment by HarelM** [comment]
Ok, Do you have a place where a developer that wants to use OSM API can go besides this page that you maintain and have examples?
