### ISSUE TITLE
Upload text has grammar mistakes in Hebrew

### ISSUE THREAD

**Issue by HarelM** [openstreetmap/openstreetmap-website#1599]
The following text is incorrect:
קובץ ה־GPX שלך הועלה ומחכה להכנסה אל מסד הנתונים. זה בדרך יקרה בתוך חצי שעה ויישלח לך מכתב עם השלמת הפעולה.
The text should probably be:
קובץ ה־GPX שלך הועלה ומחכה להכנסה אל מסד הנתונים. זה בדרך כלל יקרה בתוך חצי שעה ויישלח לך מכתב עם השלמת הפעולה.

**Comment by simonpoole** [comment]
Text strings are translated on https://translatewiki.net/ simply create an account there and directly fix the string there. 

Note: the translation are updated regularly, but not immediately.

**Comment by tomhughes** [comment]
Indeed - there is more at http://wiki.openstreetmap.org/wiki/Website_internationalization#How_to_translate on how to update translations.

**Comment by HarelM** [comment]
Too complicated, I needed to translate another 15 unrelated sentences in order to get permission to translate this. The permission requires someone to manually check my translations, by the time I get the required approval I'll forget what I wanted to do.
I have little patience for this, good luck!

**Comment by gravitystorm** [comment]
@HarelM I'm sorry to hear that you don't have the patience! Have you used other translation systems for open-source development, like Transifex? Which ones? What would make a better system?

**Comment by HarelM** [comment]
The registration was not very friendly but I managed to register and update the translation in the end...
I use [Zanata](http://zanata.org/) for my site but I'm not sure it's any better as I think you need to approve users that you want to translate for you and it's a bit sluggish.
Having said that, it works well with `.po` and `.pot` files which are very easy to use.
I use [Angular gettext](https://angular-gettext.rocketeer.be/) in my site and the extraction of text and compilation is done almost automatically using `gulp`.
