### ISSUE TITLE
user account update goes to 404

### ISSUE THREAD

**Issue by chris4d** [openstreetmap/openstreetmap-website#1601]
reproduce as follows:
navigate to user account page https://www.openstreetmap.org/user/Chris4d/account
select a new "home" location on the embedded map widget (or any other action)
click "save changes" submit button
browser goes to https://www.openstreetmap.org/user/57751 which does not exist

**Comment by tomhughes** [comment]
The fix will be live on about half an hour.

**Comment by osmtools** [comment]
hmm, is this fix live on production? after "save changes" there's (still) a 404

    File not found
    Couldn't find a file/directory/API operation by that name on the OpenStreetMap server (HTTP 404)
    Feel free to contact the OpenStreetMap community if you have found a broken link / bug. Make a note of the exact URL of your request.

**Comment by tomhughes** [comment]
It should be live, yes, though I did just have another report that might be related.

**Comment by tomhughes** [comment]
Hmm it's still sending PATCH for some reason even though the form clearly says `method=post` but I'm sure it was working in my dev tree...

**Comment by tomhughes** [comment]
Urgh because it has a hidden `_method` parameter for some reason.
