### ISSUE TITLE
Is it possible to change the tile server ?

### ISSUE THREAD

**Issue by dedpnd** [openstreetmap/openstreetmap-website#1606]
Good day! 
I can replace the standard server: 
`
"http://a.tile.openstreetmap.org/${z}/${x}/${y}.png",
"http://b.tile.openstreetmap.org/${z}/${x}/${y}.png",
"http://c.tile.openstreetmap.org/${z}/${x}/${y}.png"
`
on your own ?
Can you tell me how to do it.

**Comment by tomhughes** [comment]
Please don't use the bug tracker to ask questions about how to use the code - the dev or rails-dev mailing lists (https://lists.openstreetmap.org/listinfo) are the appropriate venues for that.

The answer is that you have to change the code - this is not configurable.
