### ISSUE TITLE
Query tool: hovering over relations sometimes unresponsive

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#1608]
Testcase: http://www.openstreetmap.org/query?lat=43.5370&lon=-6.4806#map=13/43.5298/-6.4386

Issue: I'm hovering over the different elements on the left. While ways are updated immediately on the map, hovering over the different relations a couple of times takes 5-30s each here. During that time, the UI appears somewhat sluggish, not to say frozen.

I realize that those relations are quite long, yet the Overpass API result returns an empty / null geometry for most part of the relation. What I find a bit puzzling is that overpass turbo renders the query results more or less instantaneously: http://overpass-turbo.eu/s/qPT

![image](https://user-images.githubusercontent.com/5842757/29003224-f59aab94-7ab2-11e7-996c-83f832d0e337.png)

![image](https://user-images.githubusercontent.com/5842757/29003202-86b4df7e-7ab2-11e7-8158-a50dbe75c21a.png)

Tested on Firefox 54.0 and Chrome 51, Ubuntu 16.04.  + Win10

**Comment by mmd-osm** [comment]
Further checking in Chrome, it looks like we have to process a several thousand (!) layers for the relations in question. I think it is faily obvious that this is not the best thing to do. Most of these layers seem also pretty empty.

Could it be, that the following JSON fragment returned from Overpass API tricks the application into creating those useless layers?

```JSON
    {
      "type": "way",
      "ref": 7660203,
      "role": "",
      "geometry": [
      ]
    },
```


![grafik](https://user-images.githubusercontent.com/5842757/29006312-98507e4c-7aed-11e7-92ce-ed2c0e5e99fd.png)

**Comment by mmd-osm** [comment]
Suggested fix:

```javascript
diff --git a/app/assets/javascripts/index/query.js b/app/assets/javascripts/index/query.js
index 018aedf..7ac613d 100644
--- a/app/assets/javascripts/index/query.js
+++ b/app/assets/javascripts/index/query.js
@@ -146,7 +146,7 @@ OSM.Query = function(map) {
 
     if (feature.type === "node" && feature.lat && feature.lon) {
       geometry = L.circleMarker([feature.lat, feature.lon], featureStyle);
-    } else if (feature.type === "way" && feature.geometry) {
+    } else if (feature.type === "way" && feature.geometry && feature.geometry.length > 0) {
       geometry = L.polyline(feature.geometry.filter(function (point) {
         return point !== null;
       }).map(function (point) {

```

**Comment by mmd-osm** [comment]
Thanks for the quick merge. I just figured out that the usual ways now don't show up anymore, which is sort of embarrassing: http://www.openstreetmap.org/query?lat=43.4602&lon=-6.4156#map=15/43.4602/-6.4156

Investigating...

**Comment by tomhughes** [comment]
If you mean http://www.openstreetmap.org/way/193407337 then that seems to be being returned from overpass without a geometry.

**Comment by mmd-osm** [comment]
Yes, right. That somehow changed in the most recent version. On the French instance, you still get a partial geometry as before, overpass-api.de and Rambler (both on the most recent version) behave differently and don't return any geometry at all.

Test case:
[timeout:10][out:json];way(193407337);
out  geom(43.44416399866694,-6.424341201782227,43.458401741026194,-6.399600505828857);

**Comment by mmd-osm** [comment]
fyi: I added a fix to my Overpass dev instance now, which seems to work. See the following instructions on how to use a different Overpass instance in Chrome for testing: https://github.com/mmd-osm/Overpass-API/wiki/Switching-to-a-test-Overpass-API-instance

Now, we just have to wait till Roland merges the patch and rolls it out to the official instance.
