### ISSUE TITLE
Applications authorization with OAuth does not work (request_token returns 500)

### ISSUE THREAD

**Issue by slavanap** [openstreetmap/openstreetmap-website#1610]
Hello,
I'm trying to attach locally hosted iD editor to locally hosted OSM server.
I'm adding OAuth application to my test account:
![step 1](https://user-images.githubusercontent.com/1901547/29180941-0b8563d4-7e02-11e7-9696-83169e37db98.png)
As a result I've got OAuth URLs:
![step 2](https://user-images.githubusercontent.com/1901547/29181038-5b238eca-7e02-11e7-92de-2279366c1055.png)
But request_token URL doesn't work:
![step 3](https://user-images.githubusercontent.com/1901547/29181066-72e89d66-7e02-11e7-89b0-75e33267c2ba.png)
What am I doing wrong?

**Comment by tomhughes** [comment]
This is a forum for reporting bugs, not a support forum for teaching you how to configure your own instance of the code - those sort of issues are better dealt with on IRC or the mailing lists.

The error almost certainly means that you have passed an application ID that does not exist in your database, which means that it gets `nil` when it tries to lookup the client application object and then fails calling `create_request_token` on it. The exception is basically a bug in the oauth gem but that's outside our control.
