### ISSUE TITLE
DiaryEntryController.list

### ISSUE THREAD

**Issue by lelelelemon** [openstreetmap/openstreetmap-website#1612]
The location for diaryEntry can be previously stored into the database, since the value used to calculate it will keep non-changed.

**Comment by tomhughes** [comment]
Sorry, but I don't understand what you mean. Can you explain a bit more fully?

**Comment by lelelelemon** [comment]
Sorry to make you confused, what I want to say is in your _location.html.erb:
<%= t 'diary_entry.location.location' %>

<a href="<%= url_for :controller => 'site', :action => 'index', :anchor => "map=14/#{location.latitude}/#{location.longitude}" %>">
<abbr class="geo" title="<%= number_with_precision(location.latitude, :precision => 4) %>; <%= number_with_precision(location.longitude, :precision => 4) %>">
<%= describe_location location.latitude, location.longitude, 14, location.language_code %>
</abbr>
</a>

every diary, will call "describe_location location.latitude, location.longitude, 14, location.language_code" to get the real location, which is quite time consuming, why don't directly store this value into database

**Comment by tomhughes** [comment]
It doesn't actually call nominatim every time as the results are cached - see https://github.com/openstreetmap/openstreetmap-website/blob/master/lib/nominatim.rb#L8 for details.

The main advantage to not storing it in the database is that it allows the description to improve over time as our data improves - the cache means it won't update immediately but it will age out eventually or sometimes the caches are purged for various reasons.

**Comment by lelelelemon** [comment]
but i still think the frequency to change it is very small
