### ISSUE TITLE
Problem Creating a User

### ISSUE THREAD

**Issue by lfraval** [openstreetmap/openstreetmap-website#1613]
Has the creation of a user I have an error.
"Encoding::CompatibilityError in User#terms"
![capture du 2017-08-16 15-57-46](https://user-images.githubusercontent.com/7376510/29366976-bc951a3c-829b-11e7-81b8-6467d52224c2.png)
and log rails server
![capture du 2017-08-16 16-01-52](https://user-images.githubusercontent.com/7376510/29367152-45251a5a-829c-11e7-9b3e-aebaff4d5fe9.png)

**Comment by tomhughes** [comment]
This is an installation/configuration error in your environment and not an issue with the software.

**Comment by tomhughes** [comment]
My best guess by the way, as I've already said on IRC, is that you are somehow running your ruby process in a single byte ASCII encoding.

I know you said you were using `bundle exec rails server` to start the builtin rails web server in which case, if you're on linux, you could try setting `LANG=en.utf8` in the environment before running it, though I thought pretty much all modern linuxes defaulted to a UTF8 locale.

If it's not linux then you'll need to find out how to control the default locale for ruby on your platform.

**Comment by ludovicf01** [comment]
thans you tomhughes

**Comment by ludovicf01** [comment]
The trouble was in config/legales/GB.yml where "owner's" got a strange quote instead of a normal quote. At least this solved my problem.
Solved with @psychiclocust ;)

**Comment by tomhughes** [comment]
Well yes that has a UTF8 encoded smart quote and the french one will have UTF8 encoded accents. None of that would be a problem if your ruby was running in UTF8 mode though and running it in single byte is probably just going to break in other places.
