### ISSUE TITLE
Errors occured while trying to save:Couldn't authenticate you .

### ISSUE THREAD

**Issue by sophia-xll** [openstreetmap/openstreetmap-website#1615]
hello everyone,
     when after editing using ID editor ,I press 'save' button then come's error" Couldn't authenticate you".
How to fix this error? Thanks for any help .

**Comment by sophia-xll** [comment]
file:///root/%E4%B8%8B%E8%BD%BD/4.png
file:///root/%E4%B8%8B%E8%BD%BD/3.png
file:///root/%E4%B8%8B%E8%BD%BD/2.png
file:///root/%E4%B8%8B%E8%BD%BD/1.png
file:///root/%E4%B8%8B%E8%BD%BD/4.png
file:///root/%E4%B8%8B%E8%BD%BD/3.png
file:///root/%E4%B8%8B%E8%BD%BD/2.png
file:///root/%E4%B8%8B%E8%BD%BD/1.png
file:///root/%E4%B8%8B%E8%BD%BD/4.png
file:///root/%E4%B8%8B%E8%BD%BD/3.png
file:///root/%E4%B8%8B%E8%BD%BD/2.png
file:///root/%E4%B8%8B%E8%BD%BD/1.png
file:///root/%E4%B8%8B%E8%BD%BD/4.png
file:///root/%E4%B8%8B%E8%BD%BD/3.png
file:///root/%E4%B8%8B%E8%BD%BD/2.png
file:///root/%E4%B8%8B%E8%BD%BD/1.png

**Comment by tomhughes** [comment]
Is this on openstreetmap.org? or are you running your own instance?

**Comment by sophia-xll** [comment]
Thanks for your reply @tomhughes.
 It  is running on my own instance. I requested Oauth key using "http://192.168.6.229:6300" before. Again I change URL"http://172.17.0.1:6300" to  requested Oauth key. Then edit on 'http://192.168.6.229:6300', and It can be saved now. Although I don't know why they are different.

**Comment by tomhughes** [comment]
Right in that case it's going to be configuration problem with your instance not a bug in the code.

Most likely you just haven't configured the application key correctly in `application.yml` but if you're still have problems then IRC or one of the mailing lists is the place to seek help.
