### ISSUE TITLE
Feature request: search for place near map center/in map range

### ISSUE THREAD

**Issue by Artoria2e5** [openstreetmap/openstreetmap-website#1617]
OSM's search box often returns places from all over the world (try "Main Street"), which is usually inconvenient for users who just want to look around themselves' current map view. Typing the city name after the search query helps, but it gets clumsy on phones which gets slow to type.

This problem may be helped by providing an option for search queries to be related to the current map view, be it some "in current view" (bounding box?) setting or a "sort by distance from current map center" option.

**Comment by tomhughes** [comment]
The search already prioritises the local area.

**Comment by neiljp** [comment]
As far as I can tell, it prioritises only for exact matches.

For example, given:
https://www.openstreetmap.org/#map=18/45.52265/-122.68114
then searching for "Powell's" leads to a jump across the US to:
https://www.openstreetmap.org/search?query=Powell%27s#map=19/38.94236/-77.01501
whereas searching for "Powell's city of books" gives the hoped-for:
https://www.openstreetmap.org/search?query=Powell%27s%20city%20of%20books#map=19/45.52333/-122.68164

"Main Street" may be an exact match situation, so perhaps this issue does not cover the above case, but should inexact searches in the local area be included first?

**Comment by tomhughes** [comment]
Well that's a general issue with Nominatim, that it tends to only match exact names, and isn't specific to the prioritisation of local results.

In any case all of this is nothing to do with the web site code - it just passes the query string and bounding box to Nominatim and it decides what to match and how to order the matches, so https://github.com/openstreetmap/Nominatim/issues would be the place to discuss any changes.
