### ISSUE TITLE
Kabyle localization

### ISSUE THREAD

**Issue by belkacem77** [openstreetmap/openstreetmap-website#1620]
We are localizing OpenStreetMap  into Kabyle using https://translatewiki.net/
Please, would you like consider Kabyle locale on next release?

**Comment by tomhughes** [comment]
We publish all translations that TranslateWiki push to us.

**Comment by gravitystorm** [comment]
In addition to what Tom said, Translatewiki decide when there's enough strings translated to include it. So some languages that have only a few translations are not included on our website. On the Translatewiki website they say that they include translations when they reach 35%, and Kabyle currently has only 21%.

https://translatewiki.net/w/i.php?title=Special:MessageGroupStats&group=out-osm-site

When it reaches the target, Translatewiki will include it in the next push to our repository, and we'll deploy it shortly after that. So the first step is to do more translations, and everything after that will happen in due course.

**Comment by belkacem77** [comment]
Hi,
Thanks for you both.
Great!!!
Well, we will be ready shortly. Tanks again

**Comment by BoFFire** [comment]
\o/ yes !
Tanmirt :)
