### ISSUE TITLE
nofollow

### ISSUE THREAD

**Issue by cliffordsnow** [openstreetmap/openstreetmap-website#1624]
I'm looking for information for a talk I'm giving next month on SEO. Can you tell me approximately when you added the ref=nofollow to the website? 

BTW - a big thanks for having the nofollow on URLs.

**Comment by tomhughes** [comment]
That's a completely inappropriate use of the issue tracker - use IRC or the mailing list to ask questions like that or just ask git!

**Comment by gravitystorm** [comment]
The earliest I can find is https://github.com/openstreetmap/openstreetmap-website/commit/6bfa897cfc38bcf8cb7c6a8649101ea699ea5c5a in Nov 2009. There's a few more commits around 2010 expanding the use of nofollow to other situations, like the browse pages.

**Comment by tomhughes** [comment]
Yes that's the one (`git log -S nofollow` is your friend) but as I say this is an issue tracker not a web discussion forum...

**Comment by cliffordsnow** [comment]
@tomhughes sorry for asking here - While I use github, I'm not knowledgeable in the proper edicate.
