### ISSUE TITLE
unable to watch changesets that are not yet closed but there is a "watch" button

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#1627]
Noticed on https://www.openstreetmap.org/changeset/51641815? (unclosed at this moment)

Comment box is missing (I guess that it is intentional, though there is no explanation why comments are impossible), I see "watch" button that may be clicked resulting i no change - after reload it still "watch" button, not "stop watching button".

Initial:
![selection_003](https://user-images.githubusercontent.com/899988/29971090-58dc9f22-8f27-11e7-817e-c44682d16cee.png)

after clicking "Obserwuj" (watch in Polish)
![selection_004](https://user-images.githubusercontent.com/899988/29971100-68d19aae-8f27-11e7-8073-e046176a307f.png)

after reload
![selection_005](https://user-images.githubusercontent.com/899988/29971107-6de4214c-8f27-11e7-9c85-f6e79138bba6.png)

**Comment by HolgerJeromin** [comment]
related: #845

**Comment by mmd-osm** [comment]
We could disable the "Watch" button and display some explanatory text, see the example below. Wording may not be ideal, it's just an idea how it could look like.

### Changeset still open

![grafik](https://user-images.githubusercontent.com/5842757/33803856-d16b975c-dd99-11e7-8f30-8c7212bf546c.png)

### Changeset closed

![grafik](https://user-images.githubusercontent.com/5842757/33803871-0376a368-dd9a-11e7-93a2-5d61bc8dadaa.png)

```ruby
diff --git a/app/views/browse/changeset.html.erb b/app/views/browse/changeset.html.erb
index 86d1906..d4fd2e8 100644
--- a/app/views/browse/changeset.html.erb
+++ b/app/views/browse/changeset.html.erb
@@ -13,6 +13,7 @@
 
   <h4 class="comments-header"><%= t('browse.changeset.discussion') %></h4>
 
+  <% unless @changeset.is_open? %>
   <div class="buttons clearfix subscribe-buttons">
     <form action="#" class="hide_unless_logged_in">
       <% if current_user and @changeset.subscribers.exists?(current_user.id) %>
@@ -22,6 +23,7 @@
       <% end %>
     </form>
   </div>
+  <% end %>
 
   <div class="clearfix"></div>
 
@@ -72,6 +74,10 @@
         <input type="submit" name="comment" value="<%= t('javascripts.changesets.show.comment') %>" data-changeset-id="<%= @changeset.id %>" data-method="POST" data-url="<%= changeset_comment_url(@changeset) %>" disabled="1"/>
       </div>
     </form>
+  <% else %>
+    <div class="notice hide_unless_logged_in">
+    <%= t('browse.changeset.still_open') %>
+    </div>
   <% end %>
 
   <% unless @ways.empty? %>
diff --git a/config/locales/en.yml b/config/locales/en.yml
index 062fd95..6a59614 100644
--- a/config/locales/en.yml
+++ b/config/locales/en.yml
@@ -131,6 +131,7 @@ en:
         title_comment: "Changeset %{id} - %{comment}"
       join_discussion: "Log in to join the discussion"
       discussion: Discussion
+      still_open: "Changeset still open, check back later for discussion"
     node:
       title: "Node: %{name}"
       history_title: "Node History: %{name}"
```

**Comment by pnorman** [comment]
> We could remove the "Watch" button and display some explanatory text as long as the changeset is still open.

The reason for prohibiting comments on open changesets is they're still volatile and could change (#845). These reasons don't apply to watching a changeset.

**Comment by mmd-osm** [comment]
> These reasons don't apply to watching a changeset.

Technically speaking, you still can't subscribe to an open changeset as it triggers an exception, see: https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/changeset_controller.rb#L360

That's why I disabled this button here - it doesn't work anyway as of today. Unless the subscribe function gets changed as well.

**Comment by matkoniecz** [comment]
In that situation from user perspective it makes more sense to allow watching open changesets target than remove watch button.

**Comment by mmd-osm** [comment]
Ok, I added a pull request, sub/unsubscribe is now allowed even if the changeset is still open.
