### ISSUE TITLE
Get UID from user display name

### ISSUE THREAD

**Issue by GuillaumeAmat** [openstreetmap/openstreetmap-website#1628]
Hi there,

I'm looking for a way to obtain the informations of a user, such as his UID and avatar, from his display name.

The OSM API only provides a way with the UID:
http://wiki.openstreetmap.org/wiki/API_v0.6#Details_of_a_user

Is it already implemented or planned?

Thank you!

**Comment by woodpeck** [comment]
I am not aware of an API call that does this, however there's this third-party service that might help:

http://whosthat.osmz.ru/?q=woodpeck

**Comment by mmd-osm** [comment]
I see two more options, both of which have limitations:

* http://planet.openstreetmap.org/replication/changesets/  -> you need to setup your own db, does not include users without changesets. 
* [Changesets API call](http://wiki.openstreetmap.org/wiki/API_v0.6#Query:_GET_.2Fapi.2F0.6.2Fchangesets) has a display_user parameter, but I'm pretty sure this is highly discouraged due to the overhead involved. Also requires a user to have made some edits before.

**Comment by GuillaumeAmat** [comment]
Thank you both for your messages :)

@woodpeck, Do you know if that site is reliable in term of QoS?

@mmd-osm, I thought about that too but as you said, it does not work with contribution-less accounts :/

I think I will implement a solution with the *whosthat* service as I don't really have the choice ^^

**Comment by mmd-osm** [comment]
BTW: who's that has the same limitation wrt users without any commits, as it uses either diff files or the changeset files I mentioned.

**Comment by Zverik** [comment]
@GuillaumeAmat I maintain the Whosthat service, it hasn't gone offline for a very long time. It has an API: https://github.com/zverik/whosthat

**Comment by tyrasd** [comment]
> contribution-less accounts

As far as I know, *whosthat* also doesn't know about users who never contributed any data to the map (please correct me if I'm wrong). see https://github.com/Zverik/whosthat/issues/3 for the related feature request.

If you really want to get uids for all users, you probably have to scrape the [`/user/` call](http://wiki.openstreetmap.org/wiki/API_v0.6#Details_of_a_user) like Pascal Neis does for his tools and analyses: http://neis-one.org/2016/11/osm-contributor-groups/#comment-18575

**Comment by GuillaumeAmat** [comment]
Thank you all for your answers, it helps a lot. I guess I will use the *Who's that* API (thanks @Zverik) and warn the users about the contribution issue.

**Comment by GuillaumeAmat** [comment]
@Zverik Can you tell me why that user is not found by your service?
http://whosthat.osmz.ru/?q=RebeccaPicault

That user has several contributions... http://www.openstreetmap.org/user/RebeccaPicault/history

Thank you!
