### ISSUE TITLE
geocoder.us might need to be pulled from configs

### ISSUE THREAD

**Issue by b-jazz** [openstreetmap/openstreetmap-website#1633]
Geocoder doesn't appear to exist any longer. I don't know the history or the situation, but it looks dead. If so, it should be removed/replaced in the configs.

Repro:
1) http://osm.org
2) search for "90210"
3) receive error: "Error contacting rpc.geocoder.us: Failed to open TCP connection to rpc.geocoder.us:80 (getaddrinfo: Temporary failure in name resolution)"

The dns server for geocoder.us is pointed at tridity.org (part of hover.com apparently) and tridity.org is not responding to DNS requests. Maybe they're the ones with the problem. But geocoder hasn't fixed the problem in a while now and their website hasn't been scraped by archive.org for a couple of years, so I'm thinking maybe they don't exist. If I'm wrong and they are just having temporary problems, please close this out.

**Comment by tomhughes** [comment]
The geocoder.us domain is still registered by @schuyler by the looks of it so maybe he can provide some guidance?

**Comment by schuyler** [comment]
The service is inactive. Please go ahead and remove it.

**Comment by schuyler** [comment]
(if the service is still valuable, please let me know and maybe I can stand up a new version)

**Comment by tomhughes** [comment]
No it's no problem - we have the US postcode data loaded on nominatim anyway I believe so there's no real loss.

I will pull it from the OSM code...
