### ISSUE TITLE
Mapzen: routing problem, where to report?

### ISSUE THREAD

**Issue by AllroadsNL** [openstreetmap/openstreetmap-website#1635]
Where to report at Mapzen?

http://www.openstreetmap.org/directions?engine=mapzen_car&route=50.76615%2C5.98374%3B50.76440%2C5.97146#map=15/50.7712/5.9805

There is this gate node  2173190343

http://osmlab.github.io/osm-deep-history/#/node/2173190343

There was a routing problem on the road found this gate, changed tags.
But now this behavior.

If set some closer then it takes the short route over the gate.

When playing with positions it must have something to do with the gate.

This gate is always open! But when ice on road then closed.

**Comment by tomhughes** [comment]
Not here, that's for sure. Suggest you ask ask Mapzen.
