### ISSUE TITLE
Weird navbar on GPS traces page

### ISSUE THREAD

**Issue by JamesKingdom** [openstreetmap/openstreetmap-website#1639]
When viewing the GPS traces page, it is displayed as so:
![](https://i.glideservers.com/u/jamd2fcd60e-771e-4216-b6ed-7dafc5be74e9.png)
It looks like it should on a mobile, with the collapsed selector on the top right, but clicking my username, it opens the drop down on the wrong side of the screen,
This is at 1920x1080.

**Comment by tomhughes** [comment]
Works fine for me - your browser must be doing something weird.

**Comment by tomhughes** [comment]
To be clear it should only switch to that mode at about 620 pixels wide - there may be some variation based on language I think. That seems to be the case for me in both Firefox and Chromium.

**Comment by JamesKingdom** [comment]
This is in chrome 59, and I've tried in incognito mode so it's not any plugins.
It seems to be 50/50, if I refresh it normally goes away, but another refresh brings it back.
I was on en-GB, but it still happens on en and en-US.
Using firefox fixes it though.

**Comment by SomeoneElseOSM** [comment]
I get the same effect here - Windows 7, 1680x1050 display, Chrome 60 and 61 (it just updated itself) incognito mode, browse to osm.org, click "GPS traces" and the mobile menu appears as per screenshot above.  

Any other information that would be useful?

**Comment by tomhughes** [comment]
OK I can see it with chromium on my laptop but not on my desktop. Would I be right in thinking that you're both using hidpi (aka retina) displays?

**Comment by JamesKingdom** [comment]
> Would I be right in thinking that you're both using hidpi (aka retina) displays?

I don't think so, just a standard TN [Acer panel].(https://www.acer.com/ac/en/GB/content/model/UM.FW3EE.001)

**Comment by SomeoneElseOSM** [comment]
Not here - antique Lenovo Thinkpad R500 with 1680x1050 panel.  "Set custom text size" is set to 125%.  FWIW I get the same effect if I plug in an old 1280x1024 LCD panel and start Chrome there.

**Comment by tomhughes** [comment]
It seems that https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/javascripts/application.js#L82 is the problem - it tries to measure the width of the header elements in the full width and compact modes to work out when to switch between modes given that different languages have different widths.

It looks like just running in the `ready` callback is not enough any more and it hasn't yet figured out the width of the elements properly - adding a zero second delay with `setTimeout` appears to work around it but I wonder if there's a better event to wait on?

**Comment by JamesKingdom** [comment]
Thanks @tomhughes ! :+1:
