### ISSUE TITLE
API: check (and notificate) for new keys after close changeset

### ISSUE THREAD

**Issue by osmtools** [openstreetmap/openstreetmap-website#1641]
In the last days, i worked the [OSM Latest Key](http://osm.mueschelsoft.de/taginfo/newkeys.htm) and created a lot of [comments](http://resultmaps.neis-one.org/osm-discussion-comments?uid=92644&commented) on several changesets. And what should I say, besides new keys there are also many typos, and all editors are represented.

So, could it be possible that the API check for new keys after the close event of a changeset and additionally notificate the changeset creator with a general email?

This email should has a general text about new keys, typos, taginfo, wiki, and so on.

What's your opinion?

**Comment by tomhughes** [comment]
I'm afraid I have no idea what you're talking about. What are these "keys" you keep mentioning?

**Comment by tomhughes** [comment]
Do you mean new (as in not used anywhere else in the database) keys added to objects by the changeset?

I don't think that kind of validation is a job for the API and it would be very complicated and expensive to implement - there are plenty of third party QA services that do a much better job of that sort of thing.

**Comment by osmtools** [comment]
Have you ever looked into the list, mentioned above?

And yes, you're right, i mean this "new" (and so far unkown, undocumented) keys added to objects.

**Comment by tomhughes** [comment]
As I say I don't think that is really practical.
