### ISSUE TITLE
Record IDENTIFIABLE trace id in changeset

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1645]
Click ```See your traces```.
Pick an IDENTIFIABLE trace and click ```edit```.
After saving the edit, the XML contains
```
<tag k="imagery_used" v="Bing aerial imagery;Local GPX"/>
<tag k="comment" v="Used trace."/>
```
Shouldn't it also contain the trace number/URL?
I mean the trace is IDENTIFIABLE, not even just PUBLIC,
and you do mention it is Bing imagery, not just plain "imagery"...

**Comment by pnorman** [comment]
Changeset tags don't come from the website code, they come from the editor you use.

**Comment by bhousel** [comment]
Hey @jidanni can you open this as an issue on the [iD repository](https://github.com/openstreetmap/iD)?  I agree we should fix the `imagery_used` tag to say something other than "Local GPX".

**Comment by jidanni** [comment]
Currently see:
```
Tags
changesets_count	4777
created_by	iD 2.31.1
host	https://www.openstreetmap.org/edit
imagery_used	Bing Maps Aerial;.gpx data file
locale	en-US
```

**Comment by HolgerJeromin** [comment]
Very offtopic here. And you know it!
The reason for that is clear linked from that.

**Comment by jidanni** [comment]
Thanks!
OK, my "confirmation dialog" idea
https://github.com/openstreetmap/iD/issues/4530#issuecomment-2676020675
will save the day!
