### ISSUE TITLE
Enhancement : Users Dump File

### ISSUE THREAD

**Issue by pierzen** [openstreetmap/openstreetmap-website#1655]
To my knowledge, there is no User's infos Dump File like for Changesets and Changeset details (ie. objects edited). The only access is via https://www.openstreetmap.org/api/0.6/user/XXXX

For statistical purpose, I would like to access this info to identify user characteristics such as BOT / Mechanical or Import Accounts, Organization Affiliation, blocked accounts and what else without stressing the API.

I suggest that a dump file be updated with a certain periodicity (monthly?).

**Comment by tomhughes** [comment]
This appears to be an operational issue and not anything to do with the web site code.

**Comment by tomhughes** [comment]
I would also add that there are likely to be significant privacy/leg issues here, especially with GDPR coming in soon so the first people to talk to is probably the LWG.

**Comment by simonpoole** [comment]
@pierzen Tom has already pointed this out, but just to expand a bit on the topic. 

Introduction of the GDPR is a work item of the LWG and will have impact on what data we make publicly available. This doesn't mean that post any such changes it wont be possible to have access to certain data for research and statistics, but that it is extremely unlikely that we will be allowing general public access to any thing that allows identification of individuals and we definitely don't want to expand the scope of what we are distributing now, to reign everything back in again in half a year (note such restrictions will likely apply to the public API too). 

I suspect that there will be the start of a public discussion rsn on the topic (depending on workload).
