### ISSUE TITLE
leaflet.layers.js - mini map bing maps

### ISSUE THREAD

**Issue by obama** [openstreetmap/openstreetmap-website#1657]
what speaks against passing the whole `options` here?
https://github.com/openstreetmap/openstreetmap-website/blob/44b817a6d59e9ad120c0fb73686b942581b4af82/app/assets/javascripts/leaflet.layers.js#L53

i wanted to add the bing maps leaflet addon (in my osm fork), which uses not `apikey` but `bingMapsKey`. so by passing the layers options-object instead i can make that plugin work too.

**Comment by tomhughes** [comment]
It's not necessary for our code - what you want to do in your private fork is entirely up to you and not relevant to us.
