### ISSUE TITLE
user iD editor error

### ISSUE THREAD

**Issue by zhl11b** [openstreetmap/openstreetmap-website#1660]
![a2pz2oan8 wtnxi40 41 xo](https://user-images.githubusercontent.com/6011897/31874866-1c565336-b7fe-11e7-8287-50c9f2ce0ca3.png)
when i click edit,get this page.

**Comment by tomhughes** [comment]
This is not a bug - you just haven't configured your install correctly.

**Comment by tomhughes** [comment]
To be specified you need to register an OAuth client for iD in your database and then set `id_key` in `config/application.yml`.

**Comment by zhl11b** [comment]
thank u,it works
