### ISSUE TITLE
layers=H has lots of little squares

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1669]
http://www.openstreetmap.org/#map=19/24.15075/120.66357&layers=H has lots of little squares.
Not sure where to submit this bug.

**Comment by HolgerJeromin** [comment]
Probably related:
https://mobile.twitter.com/OSM_FR/status/924966979370455041
And #1667

**Comment by jidanni** [comment]
I don't think it is related and the squares are still there.

**Comment by tomhughes** [comment]
Whatever it isn't related to it's nothing to do with us - that layer is provided by OSM France.

**Comment by jidanni** [comment]
I cannot find the OSM France bug tracker.

**Comment by jidanni** [comment]
https://wiki.openstreetmap.org/wiki/Humanitarian_map_style getting warmer.

**Comment by jidanni** [comment]
I'll try https://github.com/hotosm/HDM-CartoCSS
