### ISSUE TITLE
Add a a "Report a Problem for this Layer" button

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1671]
I have an idea that can reduce a lot of reports being sent to the wrong
place (usually https://github.com/openstreetmap/openstreetmap-website
!): add a "Report a Problem for this Layer" button. Scenario:

User spots problem when browsing one of the four Map Layers.

User wishes to do his best to report the problem to the responsible
parties in the most direct way possible.

User sees a "Tiles courtesy of" link in the lower right corner. (Some
layers don't even have that, but just a "Donate" button.)

Unfortunately this link is not a direct link to the bug tracker URL for
that layer. Nor can the user usually find the bug tracker for that layer
very easily from that link. He ends up wrongly reporting it as a general
website issue.

So just to the right of the "Tiles courtesy of/Donate" link/button,
please add an additional "Report a Problem for this Layer" button. You
could have it render as just a "!" with "Report a Problem for this
Layer" as its mouseover.

So what would it link to? Well for instance for the Humanitarian Layer,
it could link to https://github.com/hotosm/HDM-CartoCSS/issue .

That would save the user a day of digging, and the
https://github.com/openstreetmap/openstreetmap-website team one less bug
to close.

**Comment by jidanni** [comment]
Another idea would be replacing the "Tiles courtesy of/Donate" button
with "More about this layer".

This "More about this layer" links would lead to the wiki page for this
layer.

Then there on the wiki page one could see both who provided the layer,
and a link, e.g.,
https://wiki.openstreetmap.org/wiki/OpenCycleMap#Contact_info_.2F_Reporting_problems
to where to report problems.

(Better yet would be a standard place in the right panel of the wiki
page for the problems URL).

One issue though is for legal reasons you might still want the "Tiles
courtesy of" name to appear on the map...

**Comment by tomhughes** [comment]
This will just bombard the layer providers with all sorts of reports about things that are nothing to do with them - no end user is going to be able to figure out what is a data bug, what is a stylesheet bug and what is a web site code bug.

That's even if we could make them understand that such a link was only for issues with the actual map display, which would be hard enough in itself.

**Comment by jidanni** [comment]
In that case I would just add a link to the layer's wiki entry. https://github.com/openstreetmap/openstreetmap-website/issues/1671#issuecomment-342479731

**Comment by jidanni** [comment]
Still stuck at the same problem:

User sees a problem in a certain layer, e.g., Humanitarian.

At the bottom of the map is

```
© OpenStreetMap contributors. Tiles style by Humanitarian OpenStreetMap Team hosted by OpenStreetMap France. Website and API terms
```

From there we end up at

https://www.hotosm.org/

at the bottom of which we then go to

https://github.com/hotosm?page=1
https://github.com/hotosm?page=2
https://github.com/hotosm?page=3
https://github.com/hotosm?page=4
https://github.com/hotosm?page=5

But we still haven't found the place to report bugs for this layer.

I propose a link at the bottom of the map, specifically tailored to send
the user to the right place to report bugs for the current layer.

An example would be
https://github.com/gravitystorm/openstreetmap-carto
for the Standard layer.

You must admit, to go from
https://www.openstreetmap.org/
to https://github.com/gravitystorm/openstreetmap-carto
would take a whole team of Sherlock Holmes.

To prevent "bombarding", a mouseover on the link could say this link is only for ....
