### ISSUE TITLE
Add 'swap from and to' to directions

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1678]
http://www.openstreetmap.org/directions?engine=osrm_car&route=24.16453%2C120.86340%3B24.16506%2C120.86437#m
is great. But they forgot a most basic functionality: swap from and to.

**Comment by jidanni** [comment]
Using the mouse to cut and paste one into the other... because of some address expansion engine working, results in what was 115 meters becoming 48 meters.
I.e., one cannot do a clean swap via other methods easily.

**Comment by jidanni** [comment]
The user would probably have to edit the string seen in the URL bar, avoiding the %2C's etc.

**Comment by jguthrie100** [comment]
I took the opportunity to add a pull request @ #1693

**Comment by jidanni** [comment]
@jguthrie100 Thanks.

**Comment by tomhughes** [comment]
This was fixed in #1693.
