### ISSUE TITLE
Remove share button from routing until it can be made to share routing

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1679]
1. Visit http://www.openstreetmap.org/directions?engine=osrm_car&route=24.16509%2C120.86437%3B24.16453%2C120.86329
2. Push "Share"

User will think he is sharing what he sees, only to be told that that is not what he shared.

**Comment by tomhughes** [comment]
That's just insane.

You don't remove a feature just because it doesn't do quite what one person thinks it should.

**Comment by jidanni** [comment]
I'll build a better bug in #1681 after lunch.
