### ISSUE TITLE
Search ignores language setting

### ISSUE THREAD

**Issue by ehahn** [openstreetmap/openstreetmap-website#1680]
When I set

- `de` as my preferred language in my OSM account
- `en` as my preferred language in my browser (Accept-Language header)

the UI is in German but the search field expects English feature names. For example, I cannot search for post boxes using the search term "Briefkasten", I have to use "post box". This is unexpected when the UI is in German.

**Comment by tomhughes** [comment]
Out of scope here - this is a matter for the various search engines (primarily [nominatim](https://github.com/openstreetmap/Nominatim)) that we get results from.

**Comment by tomhughes** [comment]
For the record we do pass the `accept-language` parameter to nominatim, based on the current preferred languages see https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/geocoder_controller.rb#L123.
