### ISSUE TITLE
Names, admin_levels by  11 admin_level values for specific countries

### ISSUE THREAD

**Issue by AllroadsNL** [openstreetmap/openstreetmap-website#1683]
On the map you can right click the mouse and look for features.

When you are in certain countries the right name is not mentioned for the admin_levels.

For example:
Stadsgrens should be Gemeentegrens in the Netherlands
Staatsgrens should be Provinciegrens in the Netherlands.

This is probably because of the list.

[11 admin_level values for specific countries](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative#11_admin_level_values_for_specific_countries)

This look very strange for people, who are searching, and expect to see something different border. admin_levels.

As [mentioned](https://forum.openstreetmap.org/viewtopic.php?pid=673182#p673182) in the forum by someone who keep the admin_levels in the Netherlands up to date, he write: 
This is a design failure, admin_levels can change for different countries and can not be translated with a single list, worldwide.

Hope you all can change this.

**Comment by tomhughes** [comment]
If you mean the "show address" option then that just shows what Nominatin reports so you'd need to report it at https://github.com/openstreetmap/Nominatim/issues not here.

**Comment by AllroadsNL** [comment]
Not the "show address" the one below. "query features".

Then, the list in "Enclosing features" but then in Netherlands.
City Boundary Raalte (wrong),  Stadsgrens Raalte (wrong NL)= admin_level 8 = Municipality boundary Raalte = in NL = Gemeentegrens Raalte

State Boundary Overijssel (wrong), Staatsgrens Overijssel (wrong NL)  = admin_level 4 = Province boundary Overijssel = in NL = Provinciegrens Overijssel

The translation from city to stad is correct.
But the problem is the name with the admin_level, 11 admin_level for specific countries.

admin_level 9 is city boundary

**Comment by tomhughes** [comment]
Well those names come from https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/en.yml#L887 or rather from the translations of those strings made via Translatewiki - see https://wiki.openstreetmap.org/wiki/Website_Internationalization#How_to_translate for information on how to contribute to those translations.

Note though that there is only one name for each admin level - they are not sensitive to which country you are looking at. So any names have to be globally generic which rather conflicts with the way admin_level is specified so there probably isn't a good solution here due to the poor design of the admin_level tag.

**Comment by AllroadsNL** [comment]
Everyone who look in the Netherlands, the Netherlands people, expect with this boundary to read in the Netherlands language "Gemeentegrens".

"We" "Openstreetmap", look bad, stupid, foolish..(name it)...when people see this.
This is probably also in other countries.

"We" do it wrong, when this name does not show up.

> here due to the poor design of the admin_level tag
 What is the best way to solve it?

It is not a problem of translation, as it looks.
Query method and conversion of the admin_level.
It seems that every country must make list, how the admin_level should be called.
I miss the municipality boundary. In above link.

**Comment by tomhughes** [comment]
Whilst that might be a lovely idea I'm not sure it's very practical - we would need to maintain a database of boundaries for 200 plus countries as well as 200 x 11 possible names.

At least it's not something that's going to happen without somebody stepping up to do the significant amount of work necessary to make it happen.

**Comment by AllroadsNL** [comment]
> as well as 200 x 11 possible names

The 200 x 11 comes from the translation.
The database need only to be in the correct English admin_level names for each country.

Should this be open again?

**Comment by tomhughes** [comment]
No the 200 x 11 comes from having english names for each of 11 admin levels in each of 200 countries.

Then each of those has to be translated into each language.

We certainly could reopen it but I'm reluctant to keep open tickets that are never likely to be implemented just because one person thinks it's a nice idea.

**Comment by AllroadsNL** [comment]
I understand that.

> one person thinks it's a nice idea.

It is still a issue, the issue stays, (open).

On the [forum](https://forum.openstreetmap.org/viewtopic.php?id=60477) I mentioned this problem, they wrote to it, our admin_level osmmember says it is a design failure.
Then I created a link to this issue, probably all who read the forum think now they solve it here.
It is not just me.

That one not well overthought mentioned solution is not likely be implemented, can not be the reason to keep it closed.

Hope for better solutions.

**Comment by pnorman** [comment]
> No the 200 x 11 comes from having english names for each of 11 admin levels in each of 200 countries.

> Then each of those has to be translated into each language.

And each has to be translated independently, because the terms in some other language might differ even if they're the same in English.

I agree with keeping it closed unless a practical solution is suggested.
