### ISSUE TITLE
Right click and selecting "Directions to here" can unintuitively blank the directions "From" text box

### ISSUE THREAD

**Issue by aftertea** [openstreetmap/openstreetmap-website#1684]
When a user searches for a location (i.e. Big Ben), clicks Directions, and then selects the second point for the directions to route, it forgets the initially selected location. 

**Replication steps** 

1. On https://www.openstreetmap.org in the search bar search for a location (i.e Big Ben)
2. Press the Directions button to the right of the search bar. 
-- "From" is now populated with the address of Big Ben, URL is [this](https://www.openstreetmap.org/directions?from=Big%20Ben#map=19/51.50069/-0.12411)
3. On the map, right click any location and select "Directions to here"

**Actual Result**

- Big Ben is removed from the "From" text box. 
- Location clicked on the map is entered into "To" text box

**Expected result**

- Big Ben remains in the "From" text box. 
- Location clicked on the map is entered into "To" text box

**Note**

Its possible that the real bug here is that the initial clicking of "Directions" should populate the "To" text box, instead of the "From"

**Comment by tomhughes** [comment]
I think it's more that the two things are not related or integrated in any way.

Searching and then clicking directions is one way of activating routing, and using the "route from" or "route to" options on the map is another. They are likely unaware of each other and each simply launches routing afresh with the fields they know populated and others empty.
