### ISSUE TITLE
Coordinates jumping to random nearby location in routing mode

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/openstreetmap-website#1685]
When I entered two coordinates in routing mode, OSM suddenly transformed the coordinates into a position at a path nearby. 

![grafik](https://user-images.githubusercontent.com/31667811/33038195-23119be4-ce34-11e7-9308-629c3f79005f.png)

However, I needed the routing algorithm to calculate the exact distance and not randomly set positions. The situation is even made worse by the fact, that OSM pinned the coordinates not to the nearest path, but to the middle point of the nearest _named_ path. Is there a way to work around this issue?

**Comment by tomhughes** [comment]
I'd suggest using the upstream router directly if you want that as currently our interface always geocodes the inputs.

**Comment by hikemaniac** [comment]
Ok, thank you. :+1: I have one more question. Why does OSM geocode coordinates to the nearest named highway object not just to the nearest one?
