### ISSUE TITLE
Make email values a link in object detail mode

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/openstreetmap-website#1689]
It would be very helpful and time saving to have the email values of objects being a link, so when you click them, your preferred mail program opens. This is basically a html command (mailto:example@example.org) and this is already what OSM does with phone and fax values (tel:12345). Would it be possible to implement this feature?

**Comment by tomhughes** [comment]
Patches welcome - the obvious problem is how to decide what is an "email value" exactly and what the changes of a false positive are.

**Comment by biswesh456** [comment]
@tomhughes if I got what you were discussing about then I think are talking about validating if a string is most likely to be an actual email or not. 
I found out this regex in stackoverflow:   /^(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6}$/i 

Will it help in this case?

**Comment by rileythomp** [comment]
Does this still need to be worked on?

**Comment by hikemaniac** [comment]
As far as I know, no one else has yet started to work on this issue and I'd gladly see this implemented! 👍

**Comment by boubascript** [comment]
Are there no still pull requests or people working on this at the moment?

I found the implementation of phone value linking in [app/helpers/browse_tags_helper.rb](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/helpers/browse_tags_helper.rb) and wrote a quick function there for emails to see if it would do what I thought, and it seems to achieve what you meant.

I have to look more into email validation so I can figure out how restrictive to make the email regex match. I also need to clean up and of course add tests, but I'd like to make a pull request for this.

**Comment by tomhughes** [comment]
Matching email addresses - it is the very last thing discussed in the canonical book on regular expressions and the discussion runs to ten pages ;-)

**Comment by boubascript** [comment]
Since the only *real* way to know if an email is valid is to actually try to send an email to it, would it be fine in this case to try a more permissive regex that generally matches every email (even though it may allow some false positives)? Worst case scenario, an obscure/odd email is hyperlinked when it probably shouldn't be.

**Comment by tomhughes** [comment]
To be fair the discussion in question is very much dealing in worst cases and finding likely email addresses is a much simpler task - the biggest problem really is boundary detection but that is the same for anything where you are picking URLs out of text as well.

I have to say that this feature sounds like it is more use to end users than mappers though so I wonder if it is actually in scope.

**Comment by boubascript** [comment]
The goal is to hyperlink the email value, so would it instead make sense to link only the likely/standard email formats and leave the worst edge cases unlinked (users could still simply manually copy the email if needed)? I think I'd lean toward this as the least misleading approach.

Also, is part of the issue the possibility of email-linking values for keys that are not actually email? If so we could also regex match the key itself to ensure only email keys are being considered. 

As for scope, I wouldn't know a lot about that as a beginner but I think telephone linking is on the same level of functionality as email linking, and is already implemented. If one is in scope it seems the other should be.
