### ISSUE TITLE
Remote control for merkaartor does not work anymore

### ISSUE THREAD

**Issue by RM87** [openstreetmap/openstreetmap-website#1694]
Remote control for merkaartor does not open the desired area for editing anymore. Currently Firefox esr 52.5.0

Around 24 november it worked with a glitch of loading the area 4 times.

A month ago it it worked fine (disregarding the osm website notice that remote editing failed, which is there due to missing feedback from merkaartor).

**Comment by tomhughes** [comment]
There have been no changes in the relevant parts of our code in that timeframe so I think it must be an issue with some sort of change in your environment.

**Comment by tomhughes** [comment]
I just tested this on linux and (aside from trying to load each area 10 times) it seems to work for me.

**Comment by mmd-osm** [comment]
Same here, Merkaartor loads the area 10 times.

Some things to check:

- Did you activate Port 8111 in the Merkaartor settings?

![grafik](https://user-images.githubusercontent.com/5842757/33795806-ab32689c-dce8-11e7-9d58-7eb747af0727.png)

- Do you have any plugins installed on Firefox

- Do you call osm.org via http? 
https will **not** work, as it would require Merkaartor to listen to post 8112 which is not supported as it seems.
See https://help.openstreetmap.org/questions/47300/how-do-i-enable-remote-control-for-merkaartor

**Comment by RM87** [comment]
Will close this here an osm website side seems ok.
https://github.com/openstreetmap/merkaartor/issues/147  is for tracking the future of this issue. Probably an issue with threads and QtNetwork. Still no idea why different webbrowsers do give different results
