### ISSUE TITLE
Creating new local user according to CONFIGURE.md fails

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#1695]
Local installation on http://localhost:3000, trying to register a new user according to https://github.com/openstreetmap/openstreetmap-website/blob/master/CONFIGURE.md#managing-users :

> If you create a user by signing up to your local website, you need to confirm the user before you can log in, which normally happens by clicking a link sent via email. If don't want to set up your development box to send emails to public email addresses then you can create the user as normal and then confirm it manually through the Rails console

- Step 1: http://localhost:3000/user/new, Enter new user data, confirm --> ok
- Step 2: Redirected to http://localhost:3000/user/terms, Accept conditions, etc. --> ok
- Step 3: Redirected to http://localhost:3000/user/save --> fail

![grafik](https://user-images.githubusercontent.com/5842757/33572334-e9be068e-d932-11e7-9fe7-c742a208df20.png)

app/controllers/user_controller.rb:77:in `save'
config/initializers/cors.rb:9:in `call'

In line 77. current_user also has some input values I recognize: (output via `puts current_user`)

```
{"email"=>"my@email", "id"=>nil, "pass_crypt"=>"supersecret", "creation_time"=>"2017-12-04T19:58:01.472Z", "display_name"=>"mmd2", "data_public"=>false, "description"=>"", "home_lat"=>nil, "home_lon"=>nil, "home_zoom"=>3, "nearby"=>[], "pass_salt"=>nil, "image_file_name"=>nil, "email_valid"=>false, "new_email"=>nil, "creation_ip"=>nil, "languages"=>[], "status"=>"pending", "terms_agreed"=>nil, "consider_pd"=>false, "auth_uid"=>nil, "preferred_editor"=>nil, "terms_seen"=>false, "description_format"=>"markdown", "image_fingerprint"=>nil, "changesets_count"=>0, "traces_count"=>0, "diary_entries_count"=>0, "image_use_gravatar"=>false, "image_content_type"=>nil, "auth_provider"=>""}
```

Code in question has been last touched in 41000078b9e0131d75ce610f148655fb7b32da73, maybe that's related?

Server is running in dev mode:

```
bundle exec rails server
=> Booting Puma
=> Rails 5.1.4 application starting in development 
=> Run `rails server -h` for more startup options
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
Puma starting in single mode...
* Version 3.11.0 (ruby 2.3.1-p112), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
```

**Comment by tomhughes** [comment]
Yes I noticed this the other day - the switch to using cookie storage for sessions has broken it I think. If you configure a better session store it will likely work.

**Comment by tomhughes** [comment]
Confirmed that it works if you touch `tmp/caching-dev.txt` and then restart the server, which causes it to use file based sessions.
