### ISSUE TITLE
Granting / revoking roles for own user

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#1697]
I wonder if we really want to allow a user to grant and revoke roles on his/her own user. My suggesting would be to disallow such an operation. Maybe this should be further restricted to the administrator role?

**Comment by tomhughes** [comment]
They already have to be an administrator to grant or revoke roles - all actions in the `user_roles` controller are subject to the `require_administrator` filter.

I don't see any particular reason to stop an administrator acting on their own account - maybe stop them removing their own administrator role but I don't see any need for anything more than that.

**Comment by mmd-osm** [comment]
> maybe stop them removing their own administrator role

That's exactly what I wanted to accomplish. As there's no additional confirmation popup, I accidentally locked myself out, and had to head for the rails console.

Second attempt is now restricted to the *administrator* role: bcd4fa52893a60ed5e2d0cc72377eab78006c1eb. Code style and naming conventions may not be ideal - will happily apply suggestions for improvement.
