### ISSUE TITLE
Bboxes and points are offset in Opera Mobile for Android

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/openstreetmap-website#170]
All data displayed on "browse" pages (bboxes for changesets, node positions etc.) is offset to north-west. This doesn't change with panning and zooming. I can provide screenshots later, this is easily reproducible.

**Comment by pnorman** [comment]
@Zverik Is this still an issue with the webkit changes in Opera?

**Comment by Zverik** [comment]
I don't use Opera Mobile anymore, so I don't know. Let's close this.
