### ISSUE TITLE
Only ever call the JOSM Remote API over HTTP

### ISSUE THREAD

**Issue by grischard** [openstreetmap/openstreetmap-website#1703]
Since most major browsers now support calling http://127.0.0.1:port from https pages without throwing mixed content warnings, [JOSM is going to remove support for https](https://github.com/openstreetmap/operations/issues/117#issuecomment-352150065). Links to edit the map should therefore, when using an external editor, only ever call http://127.0.0.1:8111, and no longer call https://127.0.0.1:8112. This will also simplify setting up JOSM for many users.

Should I submit a PR simplifying [this bit of code](https://github.com/openstreetmap/openstreetmap-website/blob/2a21c8218589f182f104d88c959e6e0181e32064/app/assets/javascripts/index.js#L246) and [this one](https://github.com/openstreetmap/openstreetmap-website/blob/986779966bb5aae241b350c3a948267fb8ceb594/app/controllers/application_controller.rb#L416)? It can then be merged when ~~JOSM is about to drop https support~~ browser support is good enough.

**Comment by tomhughes** [comment]
Yes please.

**Comment by damjang** [comment]
Hm, I have the opposite problem: my browser PaleMoon every time throw a mixed content error and block the script to edit in josm. I can push "Disable protection on this page" but this work only once. Next time I have the same problem. How I can resolve?

**Comment by tomhughes** [comment]
You can't basically, unless you browser will allow HTTP loads to localhost from HTTPS pages, which other modern browsers will.
