### ISSUE TITLE
Query Features button looks like a help button

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/openstreetmap-website#1712]
The Query Features button is labeled with a question mark, which makes it look like a help button:

![query](https://user-images.githubusercontent.com/1231218/34513883-56574604-f01f-11e7-8ce0-13c7335d3de6.png)

Since iD places its help button in roughly the same spot, iD uses a bookmark-in-book icon, which is difficult to discern. openstreetmap/iD#4650 would turn it into a question mark.

The query button’s function reminds me of click-to-select functions found in various developer tools, such as the Inspect Element function in browser DOM inspectors. In Firefox and Chrome, the button’s icon depicts an arrow cursor pointing at a box, while Safari uses a crosshair icon:

<img width="36" alt="firefox" src="https://user-images.githubusercontent.com/1231218/34513954-b599bda4-f01f-11e7-95e1-95c5bf561080.png"> <img width="31" alt="chrome" src="https://user-images.githubusercontent.com/1231218/34513964-c273cdd0-f01f-11e7-91ee-8e52139d7ecc.png"> <img width="38" alt="safari" src="https://user-images.githubusercontent.com/1231218/34513973-d409c2b6-f01f-11e7-9d42-a57a7973cbb4.png">  
_Inspect buttons in Firefox, Chrome, and Safari_

In this context, I think the crosshair could be confused with geolocation, but the pointer arrow should be pretty self-explanatory. Unlike the existing geolocation button, this arrow would more closely resemble a mouse cursor (pointing to the northwest and having a shaft).

/cc @bhousel

**Comment by tomhughes** [comment]
Happy to accept a PR with a better icon.

**Comment by manfredbrandl** [comment]
I suggest, that the icon should look like the cursor after klicking the query feature: 
![image](https://user-images.githubusercontent.com/5360273/34518472-dd8b26d0-f07f-11e7-95ec-f247324eebce.png)

**Comment by tomhughes** [comment]
Well that isn't how my cursor looks...  The cursor shape is browser specific.

**Comment by tomhughes** [comment]
To explain more the cursor is styled as `cursor: help` which is a builtin cursor and despite https://developer.mozilla.org/en-US/docs/Web/CSS/cursor showing an example much like your one what Firefox actually renders is a simple question mark with an arrow at the base.

**Comment by manfredbrandl** [comment]
All my browsers (IE 11.0.9600.18837, Firefox 53.0.7, Chrome 63.0.3239.84) show the same icon.
@tomhughes What do you think of my suggested icon-shape, even if the cursor may look different on some browsers?

**Comment by tomhughes** [comment]
Well firefox on linux has always done what I described for me but I don't seem to be able to capture a picture of it!

Looks fine as an icon to me anyway.

**Comment by manfredbrandl** [comment]
Capturing the cursor seems to be difficult. On Windows the utility psr.exe which is usually used to produce an bug report including screen-video-capture helped. Isn't there also a screen-video-capture utility including cursor in Linux?

**Comment by tomhughes** [comment]
Apparently it comes from the gnome theme:

![question_arrow_000](https://user-images.githubusercontent.com/147741/34519389-a31f05f6-f07b-11e7-9b2e-0d93c21328d0.png)

**Comment by bhousel** [comment]
I’ll just redraw the icon from scratch. This is what I do for most of the iD graphics. It’s easier than trying to capture/extract the cursor image, and anyway then the license of the produced icon is clear.
