### ISSUE TITLE
Add easy way for users to remember which of their traces they have already finished adding to the map

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1715]
On My Traces, add a checkbox, called "done", only visible to the user, where he can store the state of the traces he has already finished editing into the map.

OK, an alternative the user can already use is adding a tag "done' or "mapped" when in openstreetmap.org/trace/99...99/edit .

**Comment by tomhughes** [comment]
This seems pretty niche to me...

**Comment by polarbearing** [comment]
Uploaded GNSS traces have multiple purposes. E.g., other users adjust aerial imagery to collections of traces, even years after their upload. Thus they are never 'done'.

As for your personal workflow, you could move your files from one folder to another on your disk, or use a flagging system in you operating system.

**Comment by jidanni** [comment]
Well for reporters in war torn areas, or refugees, there is no saying when ones independent records will be lost. Therefore it is best if one's records are all in the same place.
I have opted for adding a https://www.openstreetmap.org/user/jidanni/traces/tag/jidanni_done to mine.
Anyway, this brings up a point of documenting a recommended way for each users' "personal tags" not to collide with "site wide tags" or other people's "personal tags".
So you need to say somewhere if they should use Username/my_tag or Username:My_tag or Username_my_tag or what.

**Comment by mmd-osm** [comment]
I think the proposed workflow to add custom tags (like xxx_done or maybe xxx_todo) seems doable. Managing traces locally like described by polarbearing seems like a good alternative.
