### ISSUE TITLE
Record of which trace was used thrown away upon saving edit

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1744]
Click a trace.
Click Edit.
Now save your edit.
Notice there is no trace of the trace saved anywhere along with the save.
Not in any Sources record. Not anywhere.
One cannot tell if the user was basing his edit on trace 12345, or trace 23456.
Important information thrown away.
One might think, well if they are throwing it away, maybe instead attach a record to this trace: used to make changes 11223344, 22334455, etc.
Anyway, you keep a record of which imagery was used, but not which trace.
If it is a privacy issue, then have a checkbox...

**Comment by tomhughes** [comment]
This is a matter for the editors, not the web site.
