### ISSUE TITLE
Add ASCII scale bar to trace display

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1746]
Let's take a look at an average trace,
https://www.openstreetmap.org/user/Sammyhawkrad/traces/2606342

We can see a lot of work has gone into the display.
It is even animated.
However, without a simple, even just ASCII
```
0              10 km
|________________|
```
(adds only 53 characters to the 10.36KB page, 1/200th)
scale bar below it, all scale is lost.
One cannot tell if it is around the block,
or around the nation (without needing an additional click on the Map link.
Which brings up the point: you are showing people a map, without a scale bar...
but it is Cartography 101 that a map has a scale bar. OK, there is also no North arrow,
but at least North is always up.)

**Comment by tomhughes** [comment]
Literally nobody is browsing around random traces wondering how long they are.

**Comment by matkoniecz** [comment]
> (adds only 53 characters to the 10.36KB page, 1/200th)

And adds one more feature to implement and maintain. In what situation somebody would browse random traces and wonder about their length?

**Comment by jidanni** [comment]
OK scale bars are bad. You can close the issue.
