### ISSUE TITLE
Reversing route only works once

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/openstreetmap-website#1748]
When planning a route and pressing the "reverse directions" button, the two points are swapped. However this only works once:

![routing reverse failing](https://user-images.githubusercontent.com/31667811/36166409-b97224d6-10f2-11e8-88cc-3e4da11e1158.gif)

The directions are not reversed and the original input is changed to coordinates and not changed back to an address again. Can someone please fix this misbehaviour?

 I tested this on both Firefox 57.0.4 and Safari on Mac OS X 10.10.5, the bug remains.

**Comment by tomhughes** [comment]
I did try to make it work but it's quite hard because the geocoding is not always reversible so it can sometimes get stuck as you are seeing.
