### ISSUE TITLE
when saving with iD editor: land.html missing 404

### ISSUE THREAD

**Issue by outlawx** [openstreetmap/openstreetmap-website#1760]
The file is missing. When i try to save an edit made with iD a popup window comes up (for login or oauth stuff) with the url mydomain/land.html and content 404.
I created the file in the public folder content from here https://github.com/openstreetmap/iD/tree/master/dist and now it is working as expected.
Maybe someone can look into this trivial issue. Thanks

**Comment by tomhughes** [comment]
This is the openstreetmap-website repository, not the iD repository.

**Comment by outlawx** [comment]
Yeah i know. But iD editor is shipped with the rails port and the land.html file seems to be missing. I got curious and looked into the iD repo.

**Comment by tomhughes** [comment]
There is no land.html file that is in any way relevant to this repository.

I believe that's the default callback file for authentication if you deploy your own instance? But that's something you need to discuss with the iD team.

Unless you're getting an error when running the builtin iD instance on www.openstreetmap.org or another instance of the rails port code then it is not a matter for here.

**Comment by bhousel** [comment]
Hey @tomhughes , while you are right that this user is probably just running a fork and set up something wrong, I was actually able to trigger this error on www.openstreetmap.org

It's possible for a user to start editing, and then just revoke all their OAuth tokens in another window.  (or have them revoked server side for whatever reason).  

In this situation it would be great for the user to be allowed to reauthenticate and save their changes.  iD will prompt the user to reauthenticate, but we do need the `land.html` file there to return to.

<img width="1352" alt="screenshot 2018-02-19 15 39 31" src="https://user-images.githubusercontent.com/38784/36396299-518d8750-158b-11e8-830e-ced17d719022.png">

**Comment by bhousel** [comment]
I should add - the url for the land file is not going to be at the root level (like shown in the screenshot), so it is probably up to the integration code to set the location of the land file, since the default guess will be wrong.  I have to see if this is possible.  

Or you could add a route, but I think that's kind of a hacky solution.

**Comment by outlawx** [comment]
@bhousel yes I'm just running a local server for some "fantasy" map and the popup window in your screenshot looks exactly alike
thanks for clarification :+1:

**Comment by tomhughes** [comment]
@outlawx You almost certainly haven't configured a key for ID in `config/application.yml`.

**Comment by outlawx** [comment]
@tomhughes I most certainly do have configured keys for ID, potlatch and common in application.yml ;) Potlatch is working. And I have done it multiple times while fiddling with different webservers, startup-scripts and so on...
I know this isn't the right place since my server is a local fork for some fantasy map and I'm not into the details but I was just expecting iD to work on the local installation with everything so well integrated :)

**Comment by bhousel** [comment]
> @tomhughes I most certainly do have configured keys for ID, potlatch and common in application.yml ;) Potlatch is working. And I have done it multiple times while fiddling with different webservers, startup-scripts and so on...
> I know this isn't the right place since my server is a local fork for some fantasy map and I'm not into the details but I was just expecting iD to work on the local installation with everything so well integrated :)

This step is tricky though - you need actually to log into your local application and visit your user page and set up an OAuth application for the editor.  (or you need to setup a process to seed your local database with appropriate values in the `client_applications` table that match whatever you put into the `.yml` file).  

What's probably happening is that your local pgsql database has nothing in here that matches iD, and so it doesn't know how to handle an OAuth request.

see https://github.com/openstreetmap/openstreetmap-website/blob/master/CONFIGURE.md#oauth-consumer-keys

**Comment by tomhughes** [comment]
Basically you need to do something like https://github.com/openstreetmap/chef/blob/master/cookbooks/dev/templates/default/rails.setup.rb.erb which is the script we use to create the necessary records on dev instances.

**Comment by a-kari** [comment]
> The file is missing. When i try to save an edit made with iD a popup window comes up (for login or oauth stuff) with the url mydomain/land.html and content 404.
> I created the file in the public folder content from here https://github.com/openstreetmap/iD/tree/master/dist and now it is working as expected.
> Maybe someone can look into this trivial issue. Thanks

Thank you, copying `land.html` to `openstreetmap-website/public` folder helped me, too.
