### ISSUE TITLE
old_name key name not linked to wiki without clear reason

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#1762]
see https://www.openstreetmap.org/way/34499083#map=19/49.96249/18.69686

name tag is linked, old name is not linked

I see no differences between https://wiki.openstreetmap.org/w/index.php?title=Key:name&action=edit and https://wiki.openstreetmap.org/w/index.php?title=Key:old_name&action=edit that should matter

old_name was not edited recently (see https://wiki.openstreetmap.org/w/index.php?title=Key:old_name&action=history ) so that it should not be a cache issue

**Comment by mmd-osm** [comment]
See #1736: the automated script removed the old_name tag the last time it ran. There were no error messages whatsoever. Maybe try and run the script again to see if it makes a difference.

**Comment by matkoniecz** [comment]
I will try running https://raw.githubusercontent.com/mmd-osm/openstreetmap-website/master/script/misc/update-wiki-pages - for now I am installing dependencies of thing necessary to install dependencies if this script.

**Comment by matkoniecz** [comment]
For people attempting to figure out similar problems: this Perl script relies on https://www.mediawiki.org/wiki/API:Embeddedin and run queries similar to https://wiki.openstreetmap.org/w/api.php?action=query&list=embeddedin&eititle=Template:KeyDescription&eilimit=500 (further pages may be request by passing eicontinue in &eicontinue= parameters),

At least in this case wiki API failed to include page with a template that exists on it, so it is a wiki bug. I will try to clear Wiki cache by making edit to this page and rerun this script.

**Comment by matkoniecz** [comment]
There is also https://wiki.openstreetmap.org/w/index.php?title=Special%3AWhatLinksHere&limit=500&target=Template%3AKeyDescription&namespace=0 that is probably using the same internal calls to display similar list and is easier to paginate for humans.
