### ISSUE TITLE
OSM directions not displaying exit numbers

### ISSUE THREAD

**Issue by omgitsgela** [openstreetmap/openstreetmap-website#1768]
I was editing my local area and I came across an instance where GPS directions aren't generating the exit number data on the OSM site when you calculate a route via the embedded OSRM interface.

Attached is a screenshot of the same route, left calculated on the OSM website, and right calculated on OSRM. Note that the left says to "Take the ramp on the right towards _____", while the OSRM on the right says to "Take exit 43 on the right towards destination".

The expected behavior is the rightmost direction set being generated directly in OSM when querying a navigational direction set.

This should be considered a moderate importance issue, as exit numbers are critical to directions within the United States locale, and not displaying them is missing major route data that the end user requires.

![osrm bugs](https://user-images.githubusercontent.com/25420944/36644260-831ddc36-1a25-11e8-9e50-217f21b49f54.png)

(old title "OSM is not displaying the latest OSRM-based car navigation instructions" changed)

**Comment by tomhughes** [comment]
Our routing is there to support mappers rather than drivers so this certainly isn't critical.

I think you are misunderstanding things though - the OSRM API doesn't send us a textual description which we then display. Rather it sends us details of the route which we then turn into text, and we happen to make different decisions about how to do that than the OSM website does.

**Comment by neiljp** [comment]
@tomhughes Having followed the recent major road changes (from 'unnamed road' to eg. 'Massachusetts Avenue'), this looks like it highlights an incomplete adjustment for the 'slight right' and equivalent cases?

**Comment by omgitsgela** [comment]
@tomhughes , Happening to make different decisions about how you display data generated from OSRM doesn't mean my issue I'm reporting is invalid, and frankly I'm a little miffed that you'd unilaterally just close the ticket rather than explore options to fix a documented, reported problem.

Are you stating that it's OSM's position that OSM developers don't care to provide accurate data for its features available on its website?

**Comment by tomhughes** [comment]
I'm saying your request as written, ie to display exactly the same text as OSRM, is not possible.

If you want to open a ticket requesting a specific change such as showing exit numbers then fine.

**Comment by tomhughes** [comment]
I am actually looking at adding the exit numbers, but it's not trivial - we already have 16 versions of that message and adding exit numbers of an option will double that to 32 different versions!

**Comment by systemed** [comment]
@omgitsgela Maybe easiest just to rename this ticket?

(From IRC)

Test case is https://www.openstreetmap.org/directions?engine=osrm_car&route=42.69290%2C-71.14200%3B42.69610%2C-71.13930#map=17/42.69493/-71.14064 which returns https://router.project-osrm.org/route/v1/driving/-71.142,42.6929;-71.1393,42.6961?overview=false&geometries=polyline&steps=true . In the response, `steps[1]` contains a new attribute of `"exits": "43"` which could be written out.

OSRM's navigational guidance has been moving on rapidly and 100% feature parity would probably be difficult, but one approach might be to have a hash of extra attributes for each parsed route step (e.g. `{ "exit": 43 }`) which could then be written out below the main instruction, so there's no need to rephrase every possible instruction each time OSRM changes its output. I do something similar for cycle.travel's instructions and it works quite well.

**Comment by omgitsgela** [comment]
@tomhughes I'm not sure on the specifics of what's going on in the background to generate that data, whether its being done locally with OSRM code or being processed off site and imported, but exit conventions for US are talked about on the Wiki at https://wiki.openstreetmap.org/wiki/Exit_Info . The tags presented there offer a good algorithm for parsing the data to pull an exit number out, else consider it just a ramp to turn towards.

Thanks for your attention to this issue.

**Comment by tomhughes** [comment]
@omgitsgela Parsing of OSM data it outside out control - that is done by OSRM upstream - we just consume what they provide us via their API. That does include exit numbers, we just don't show them.
