### ISSUE TITLE
Banner on main page keeps coming back on refresh, even after x

### ISSUE THREAD

**Issue by danstowell** [openstreetmap/openstreetmap-website#1770]
Hi - today on the OSM main page I see a Fossgis 2018 banner. I press the "x", close it, it goes away. I Ctrl+R refresh the page - the banner is back!

I'm logged in as myself. I'm using Firefox 58.0.2. (I use PrivacyBadger but it's making no complaints here, doesn't seem to be blocking any osm cookie functionality.)

Even after pressing the "x" I don't seem to see a cookie with a name referencing fossgis. Some failure to store the value?

![screenshot_2018-02-27_15-57-27](https://user-images.githubusercontent.com/202965/36739058-f2874942-1bd6-11e8-897c-97d8a5ffe3f7.png)

**Comment by tomhughes** [comment]
Works fine for me. I removed the fossgis2018 cookie, reloaded and got the banner, closed it and the cookie was recreated and the banner no longer appears.

Think it must be your browser.

**Comment by pnorman** [comment]
> I'm logged in as myself. I'm using Firefox 58.0.2. (I use PrivacyBadger but it's making no complaints here, doesn't seem to be blocking any osm cookie functionality.)

If you disable PrivacyBadger does it still happen?

**Comment by danstowell** [comment]
> If you disable PrivacyBadger does it still happen?

Yes. However it doesn't happen on my other machine. I'd better close this, reopen if anyone else has a problem...
