### ISSUE TITLE
Fix double underline on abbr content

### ISSUE THREAD

**Issue by aaronlidman** [openstreetmap/openstreetmap-website#1771]
<img width="399" alt="screen shot 2018-02-27 at 11 42 26 am" src="https://user-images.githubusercontent.com/58878/36751025-d5cd4590-1bb3-11e8-9996-6b9161eb0886.png">

Most browsers have added default `text-transform` styling to abbr content in the last few years, which conflicts with the existing border style.

The existing `border-bottom` should be removed in favor of the browser default, which is effectively the same styling we currently have.

**Comment by HolgerJeromin** [comment]
damn, tom was faster :-)
But perhaps my code is a little bit better for old browsers...
