### ISSUE TITLE
7235 South Vine Street, Littleton, CO 80122 should be 7241 South Vine Street, Centennial CO 80122

### ISSUE THREAD

**Issue by RodySmith** [openstreetmap/openstreetmap-website#1775]
7235 South Vine Street, Littleton, CO 80122 Should be 7241 South Vine Street, Centennial CO 80122
The Location Lat is 39.58563
The Location Lon is -104.96438

I am using Automatic in conjunction with American Family Insurance's Automobile Insurance Policy

**Comment by tomhughes** [comment]
Geocoding issues should be raised at https://github.com/openstreetmap/Nominatim/issues.

**Comment by RodySmith** [comment]
Are you emailing me to tell me the issue has been corrected? I simply want My home address to show correctly in my Automatic App working with my American Family's ins policy. Has that been corrected?Thank you.

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 28, 2018 at 12:22 PM, Tom Hughes<notifications@github.com> wrote:   
Geocoding issues should be raised at https://github.com/openstreetmap/Nominatim/issues.

**Comment by tomhughes** [comment]
I have no idea what this Automatic app is but it isn't made by us.

It might use our data, but this is not the place to report problems in the data.

It might use our geocoder to get an address in which case the link I gave is the correct place to report it.

This bug tracker is only for bugs in the web site interface at www.openstreetmap.org.

**Comment by ingalls** [comment]
Hey @RodySmith Thanks for your feedback, Automatic uses Mapbox's geocoder under the hood. If you could report future problems via: https://github.com/mapbox/geocoder-feedback that would be great!

**Comment by RodySmith** [comment]
NickI clicked on the link you gave me and got "404 - This in not the web page you are looking for." But from there I found a 'Contact GitHub' and will try to see if that contact will help correct my address.Thank you
(p.s. I'll let you know if it doesn't)
    On Wednesday, February 28, 2018, 2:44:47 PM MST, Nick <notifications@github.com> wrote:  
 
 
Hey @RodySmith Thanks for your feedback, Automatic uses Mapbox's geocoder under the hood. If you could report future problems via: https://github.com/mapbox/geocoder-feedback that would be great!

**Comment by tomhughes** [comment]
Nobody at GitHub is going to be able to help...

**Comment by RodySmith** [comment]
Just wanted to confirm that (using the link below) my home address (7241 S Vine Street, Centennial, CO 80122) does now point to the center of my home in satellite mode. But other locations, such as what was sent to me by GitHubStaff:(https://github.com/mapbox/geocoder-feedback) do not. In fact this last link has it at a different place in my neighborhood than the first incorrect one. Plus the Automatic still has it in the same place /address as it always had. This is just feedback - I have come to understand that if I forget where I parked may car, say in a large lot, the app will not be of much, if any help in locating it. I suppose I can live with if especially if locating my car isn't what I expect it to do.For what is it worth if you are interested in feedback.Thank you,
    On Thursday, March 1, 2018, 11:21:44 AM MST, Holger Jeromin <notifications@github.com> wrote:  
 
 
@ingalls Your link (mapbox/geocoder-feedback) is missing http protocol and was converted to a github link in the notification email. This one is the correct one:
https://www.mapbox.com/geocoder-feedback/

**Comment by tomhughes** [comment]
I repeat, this is entirely the wrong place to report this.
