### ISSUE TITLE
[question] How can I use OpenStreetMap without JavaScript?  

### ISSUE THREAD

**Issue by anchev** [openstreetmap/openstreetmap-website#1780]
Hello,

I am concerned about the Spectre and Meltdown vulnerabilities and the possibility for mischief they create for JavaScript coming from websites. So I am browsing the web with JS completely disabled. Still I have been looking for a way to use maps without JS.

My question is: How can I use OpenStreetMap without any JavaScript? (on a Linux system)

Forgive me for asking here but I couldn't find any forum or mailing list. If there is a more appropriate page to ask this, please share a link to it. Thanks!

**Comment by bhousel** [comment]
There are forums, mailing lists, and a stackexchange: https://help.openstreetmap.org/

I would not expect that you'll be able to use OpenStreetMap without JavaScript, as the main site relies on [Leaflet.js](http://leafletjs.com/) to draw the map.

**Comment by anchev** [comment]
Thanks for the link. Unfortunately I cannot take advantage of it because it also requires from me to enable JS in order to post a question.

Do you at least know of any FOSS application which uses an HTTP API to OpenStreetMap without JS? (or something along these lines)

**Comment by tomhughes** [comment]
Sorry, but this is really out of scope for this bug tracker.

Frankly trying to use the web these days without any javascript at all is just going to be an exercise in banging your head against one brick wall after another. By all means use something like uMatrix to control it but trying not to load any is going to be incredibly frustrating.

**Comment by anchev** [comment]
Thank you. I use uMatrix :)

**Comment by SomeoneElseOSM** [comment]
@anchev Someone (possibly not you) has just asked https://help.openstreetmap.org/questions/62551/how-can-i-use-openstreetmap-without-javascript .  You can just wait for the answers.
