### ISSUE TITLE
Note Search API can't find question marks

### ISSUE THREAD

**Issue by ENT8R** [openstreetmap/openstreetmap-website#1781]
Imagine the following usecase:
You want to use the Notes API to search for some questions. This could maybe be done by simply searching for a question mark.

But sadly the following URL does not work at all:
`https://api.openstreetmap.org/api/0.6/notes/search?q=?`
Is there a way to get results for this query?

I can imagine that this issue happens because there are 2 question marks in the URL which makes the parsing of the parameters impossible...

See ENT8R/NotesReview#15 for the initial issue.

**Comment by tomhughes** [comment]
I doubt that's the problem at all - more like is just that the postgres freetext search can't that. In fact I cant prove that:

```
x=# select plainto_tsquery('english', '?');
NOTICE:  text-search query contains only stop words or doesn't contain lexemes, ignored
 plainto_tsquery 
-----------------
 
(1 row)
```

So I don't think there's much we can do unless we fundamentally change the search technology.

**Comment by ENT8R** [comment]
Alright! Thank you for your quick response! Then I have to inform the users somehow that this search will have no result.
