### ISSUE TITLE
render icon for shop=charity

### ISSUE THREAD

**Issue by Hjart** [openstreetmap/openstreetmap-website#1784]
JOSM has an icon for [charity shop](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcharity):
![josmcharity](https://user-images.githubusercontent.com/9010705/37283547-a913455a-25f8-11e8-9d59-d1a052439a33.png)
It's at https://josm.openstreetmap.de/browser/josm/trunk/images/presets/shop/charity.svg
Can we please have it rendered here too?

**Comment by tomhughes** [comment]
If you mean on the map, then that is a matter for the map style (https://github.com/gravitystorm/openstreetmap-carto/issues).
