### ISSUE TITLE
Simplify user links

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#1785]
Currently our views are full of very verbose links to users, for example:

> link_to contact.display_name, :controller => 'user', :action => 'view',  :display_name => contact.display_name

This can be simplified by using the "user_path" method, to something like

> link_to contact.display_name, user_path(contact.display_name)

Normally this could be made even easier, since rails does the right thing with `model_path(model)` by default. However, since we use the `display_name` in the url rather than the `id`, we first need to define `to_param` on the User model:

```
def to_param
  display_name
end
```
This then allows the links to be even more straightforward, since link_to accepts an object and figures out the path itself:

> link_to contact.display_name, contact

**Comment by mikelmaron** [comment]
Related to user links clean up

* Link to settings go to https://www.openstreetmap.org/user/{username}/account .`{username}/` can be dropped from the path, you can only edit your own settings.
* Link to messages go to https://www.openstreetmap.org/user/{username}/inbox and https://www.openstreetmap.org/user/{username}/outbox. `{username}/` can be dropped from the path, you can only view your own messages.
* Link for "My Traces" on the user profile page points at https://www.openstreetmap.org/traces/mine, and then redirects to https://www.openstreetmap.org/user/{username}/traces. Should go straight there.

**Comment by tomhughes** [comment]
You can't just remove the username from those URLs or users "acount", "inbox" and "outbox" will be very upset ;-)

**Comment by tomhughes** [comment]
...and yes at least one of those does exist

**Comment by mikelmaron** [comment]
oh geez!
