### ISSUE TITLE
"Query features" always fails with "No Transport" on Opera 11.64

### ISSUE THREAD

**Issue by nachanon** [openstreetmap/openstreetmap-website#1786]
I have recently begin to use and [contribute to OpenStreetMap](https://www.openstreetmap.org/user/Nutchanon%20Wetchasit) again after a 6-year hiatus, since it now works better than [Google Maps](https://maps.google.com/) in my preferred browser ([Opera 11.64](http://ftp.opera.com/ftp/pub/opera/win/1164/int/)) despite having a not-so-good coverage in the area I frequent to; which I'm currently working to fix that.

However, there is one problem which bugged me since I have started to use it as my main map provider in 2017: **the _Query features_ command always failed with "No Transport" error message** on this browser. This does not effect the _Show address_ command- which is still working nicely, but this cannot be used as its substitute in many cases, e.g. checking on nameless features or inspecting densely-packed areas.

Exact steps to reproduce:

- Start Opera 11.64 with JavaScript enabled.
- Go to <https://www.openstreetmap.org/>
- Move the map to [13.74684 N, 100.53047 E at zoom level 19](https://www.openstreetmap.org/#map=19/13.74684/100.53047). ([Screenshot](https://u.cubeupload.com/xwindows/aqmS0f.png))
- Right-click at the middle of the map, [choose "Query features"](https://www.openstreetmap.org/query?lat=13.74684&lon=100.53047#map=19/13.74684/100.53047).
- You would see an error message on the sidebar instead of a list of components in the area ([screenshot](https://u.cubeupload.com/xwindows/JcEpUV.png)):
	
	> **Query Features**
	>
	> **Nearby features**
	>
	> Error contacting https://overpass-api.de/api/interpreter: No Transport
	>
	> **Enclosing features**
	>
	> Error contacting https://overpass-api.de/api/interpreter: No Transport

This affects "Query features" command accessed from right-click menu as well as the one from right sidebar menu; all with the same error message. There is only one seemingly-unrelated JavaScript warning appeared on browser's console:

	[14/3/2561 13:01:58] JavaScript - https://www.openstreetmap.org/query?lat=13.74684&lon=100.53047
	console.warn
	Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. w([arguments not available])@https://www.openstreetmap.org/assets/application-e0d605b1da68dac958f74d4bc3e91a674f0900018a9113ce11b921b72b7b3880.js:4
	<anonymous function: y.extend>([arguments not available])@https://www.openstreetmap.org/assets/application-e0d605b1da68dac958f74d4bc3e91a674f0900018a9113ce11b921b72b7b3880.js:5
	@https://www.openstreetmap.org/assets/application-e0d605b1da68dac958f74d4bc3e91a674f0900018a9113ce11b921b72b7b3880.js:1

Other messages in the console beside this are all CSS warnings/errors&mdash; which are not likely to be related to the problem.

**Note:** this is not a TLS issue, since I'm able to access the same Overpass endpoint over HTTPS and key in the query by hand within the same browser and get [a more-or-less correct result in machine-readable form](https://overpass-api.de/api/interpreter?data=node%28around:20,13.74684,100.53047%29%3Bout%3B).

Browser: Opera 11.64 (Win32)  
System: Microsoft Windows XP Professional (SP3)

**Comment by tomhughes** [comment]
I'm not quite sure what we can do about this - even if we can reproduce it the error is coming from the browser by the looks of it so is outside out control.

It sounds like it is saying it doesn't want to do https for that XHR or something but if there's nothing in the console to indicate why then there is little we can do to debug it.

**Comment by tomhughes** [comment]
I suspect that https://stackoverflow.com/a/8419601/80563 is the answer - you are using a prehistoric browser that doesn't support cross origin requests using the CORS protocol.

Apparently Opera 12 does support it so you probably need to upgrade.

**Comment by Zverik** [comment]
Also, there is [no reason to not upgrade](https://en.wikipedia.org/wiki/History_of_the_Opera_web_browser#Release_compatibility): Opera 12.18 (the last true Opera) supports Windows XP.
