### ISSUE TITLE
Footway/Pedestrian Areas Hide Details

### ISSUE THREAD

**Issue by cwmke** [openstreetmap/openstreetmap-website#1787]
When tagging an area with either `highway=footway` or `highway=pedestrian` and `area=yes`, the website currently hides details such as `building(:part)=roof` and `barrier=retaining_wall`. I believe it is better to display this information similarly to apps such as OSMAnd+. Below you can see what it looks like on the website vs OSMAnd+.

![screenshot from 2018-03-19 13-13-58](https://user-images.githubusercontent.com/1923967/37614964-184c511a-2b7a-11e8-9b67-f94b8441acb1.png)
![screenshot_osmand _20180319-131103](https://user-images.githubusercontent.com/1923967/37614965-185e532e-2b7a-11e8-845d-5fb5eb3ccd95.png)

**Comment by tomhughes** [comment]
I'm entirely clear what you're suggesting but this sounds like a style sheet issue not a web site issue.

**Comment by tomhughes** [comment]
For the record you can find the style sheet that controls the map rendering at https://github.com/gravitystorm/openstreetmap-carto/.

**Comment by cwmke** [comment]
Sorry about that! I'll head over there. Thanks.
