### ISSUE TITLE
Directions drops place names upon sharing

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1789]
Entering Directions From Here and Directions too here looks great!

Until you share the URL. (OK I mean copy the URL from the URL bar and give it to your friend.)

Whereupon the names disappear, and one is just sharing directions between two coordinate points.

Yes everything still stays the same, except the White House now becomes a mere coordinate.

**Comment by tomhughes** [comment]
This is already being discussed in #1754.
