### ISSUE TITLE
Directions: "Sorry - couldn't find that place": Say WHICH place

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1790]
Kindly when ever saying "Sorry - couldn't find that place",
be sure to say if it was the From place,
or if it was the To place that was bothering it.
And / or print the place that was causing the trouble.'
No it is NOT always 100% obvious.
We might have tried entering various things in both boxes etc.
![0](https://user-images.githubusercontent.com/1230959/37870893-e039552c-3013-11e8-8ab3-17a37bba39ee.jpg)

**Comment by jidanni** [comment]
OR, given that we clearly see it has "found" both points as you can see above,
maybe it is trying to say "Sorry - couldn't find that **route**"
In which case please say so!

**Comment by jidanni** [comment]
Also note that whenever a "Sorry - couldn't find that place" is generated, the internal data is polluted,
and the form will no longer work properly no matter which parts one replaces.

The only way to proceed is to close Directions with an X, refresh the page, and then click Directions again and fill in your two fields again.

**Comment by tomhughes** [comment]
Can you give an example of how to trigger this (in a way that is confusing) because I assume it relies on somehow providing both start and end points simultaneously - perhaps via the url?

**Comment by tomhughes** [comment]
Mind to be fair the whole using an alert box to report the error thing isn't really very elegant.

**Comment by mmd-osm** [comment]
It's a geocoding issue, one of {start, end} could not be found. It has nothing to do with a route that couldn't be found - see directions.js:

```
      $.getJSON(OSM.NOMINATIM_URL + 'search?q=' + encodeURIComponent(endpoint.value) + '&format=json', function (json) {
        endpoint.awaitingGeocode = false;
        endpoint.hasGeocode = true;
        if (json.length === 0) {
          alert(I18n.t('javascripts.directions.errors.no_place'));
          return;
        }
```


Just put in some random (unknown) destination, like "zzzzzzzzzzzz", which triggers the alert box both when setting a new start position via the context menu on the map - or - simply hit the "Go" button.

![grafik](https://user-images.githubusercontent.com/5842757/37873596-221e0850-3020-11e8-920a-9bbd2b980ba4.png)

**Comment by tomhughes** [comment]
Yes I know it's a geocoding issue, but in the routing geocoding.

The point is, under what circumstances do both start and end get geocoded simultaneously so that you wouldn't know which one the error was referring to?
