### ISSUE TITLE
Directions: allow A to B to C ... multiple destinations

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1792]
On Directions, allow more than one stop,
```
From [                              ] X
To   [                              ] X
To   [                              ] X
To   [                              ] X...
```

**Comment by jidanni** [comment]
Note one would start with just A and B, and add more via a "+" button.

**Comment by tomhughes** [comment]
We're not trying to provide a google clone - routing is just there to help find connectivity issues that that doesn't need via points.
