### ISSUE TITLE
Directions: Allow grabbing the route and changing it

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1793]
Allow grabbing the route and changing it. E.g., Directions tells us to
take bridge A but we want to tell our friends to take bridge B.

```
        +---A---+
--------+       +---------
        +---B---+
```

And be sure any URL put in the URL bar will remember our changes so we
can confidently share it with our friends, knowing that it won't snap
back to A causing their car to collapse the bridge, etc.

**Comment by tomhughes** [comment]
This is just a version of #1792 and the same argument applies.
