### ISSUE TITLE
Argument 7 doesn't contain a value after the '=' (ie. name=value).

### ISSUE THREAD

**Issue by Karmadon** [openstreetmap/openstreetmap-website#1803]
I've installed all according [manual](https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md)
Next using Configuration [manual](https://github.com/openstreetmap/openstreetmap-website/blob/master/CONFIGURE.md) 
First command 
```
osmosis --read-pbf greater-london-latest.osm.pbf \
  --write-apidb host="localhost" database="openstreetmap" \
  user="openstreetmap" password="" validateSchemaVersion="no"
```
fails with error 
`Argument 7 doesn't contain a value after the '=' (ie. name=value).`

**Comment by mmd-osm** [comment]
Have you tried https://lists.openstreetmap.org/pipermail/dev/2016-June/029284.html?

_What you've tried looks correct to me.  If you don't specify a password parameter, the default value is an empty password. What error are you getting when you leave out the password?_

**Comment by tomhughes** [comment]
This doesn't appear to be anything to do with openstreetmap-website. If you have a problem with osmosis you should report it in the osmosis issue tracker.

**Comment by Karmadon** [comment]
THX a lot!
`sudo -u postgres psql -c "alter role openstreetmap with password 'openstreetmap'"`
```
osmosis --read-pbf greater-london-latest.osm.pbf \
  --write-apidb host="localhost" database="openstreetmap" \
  user="openstreetmap" password="openstreetmap" validateSchemaVersion="no"
```
