### ISSUE TITLE
Avoid hand-crafting urls

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#1817]
In `app/controllers/diary_entry_controller.rb#rss` there are three links that are "hand-crafted", e.g.

```
@link = "#{SERVER_PROTOCOL}://#{SERVER_URL}/user/#{user.display_name}/diary"
```

These should instead use a helper, such as `url_for`.

**Comment by rajdeep26** [comment]
Hi @gravitystorm , 
I would like to fix this issue. Will raise a PR for this soon.

**Comment by gravitystorm** [comment]
@rajdeep26 Great! Let me know if you have any questions, otherwise I look forward to your PR.

**Comment by rajdeep26** [comment]
Thanks @gravitystorm. Just setting up my machine. Will let you know if I need help with anything.
