### ISSUE TITLE
Warning of unlocatable place doesn't dissappear when it's corrected

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/openstreetmap-website#1819]
In #1800 a feature to highlight an unlocatable place in routing mode was introduced. However when changing the corresponding place, the warning does not dissappear. Can this please be changed, as it might result in confusion for the user?

**Comment by tomhughes** [comment]
You to explain more about how you are correcting it, as any typing in the field clears the highlight, so you are presumably using some other means?

If you are doing it by typing and the highlight isn't disappearing then we need to know what browser you are using as it certainly gets cleared in Firefox in my experience.

**Comment by hikemaniac** [comment]
Ah, sorry for not expressing myself very clearly. I performed a right click and pressed "route from here" for replacing the value. This didn't remove the highlighting. 
I'm using macOS 10.13.4 and Firefox 59.0.2.
