### ISSUE TITLE
Sort points and areas in data layer by size

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/openstreetmap-website#182]
It is often impossible to select POIs in the data layer, because the underlying landuse was added later and covers all other areas: [example](http://www.openstreetmap.org/?lat=59.442003&lon=24.738448&zoom=18&layers=M). I propose to sort all areas by size (that is, smaller areas should be selectable at all times if they are inside larger areas), and nodes should be always on top.

This issue is similar to [#169](https://github.com/openstreetmap/openstreetmap-website/issues/169#issuecomment-10709086).

(inb4 yes, I know about "hide areas" button. But if the data layer is unusable without it, shouldn't we try to fix it?)

**Comment by gravitystorm** [comment]
I believe this problem is fixed. I tried the example area posted by Zverik and I could click on all the points that were inside a landuse area.

**Comment by Zverik** [comment]
Yes, I believe so too. Closing this.
