### ISSUE TITLE
Change Windows Live to Microsoft Account

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#1828]
I found this request [from one of the Translatewiki translators](https://translatewiki.net/wiki/Thread:Translating_talk:OpenStreetMap/Change_Windows_Live_to_Microsoft_account) and it seems reasonable to me!

---

The Windows Live brand has been long discontinued. You can find a list of what Windows Live services were renamed to [here](https://en.wikipedia.org/wiki/Windows_Live#Renamed_services).

I believe the replacement word should be 'Microsoft account'. Please update the icon on [the login page](https://www.openstreetmap.org/login) and the following strings to reflect this change: `user.login.auth_providers.windowslive.title` and `user.login.auth_providers.windowslive.alt`

**Comment by tomhughes** [comment]
I'm not clear what change they are asking for where the icon is concerned? As far as I can tell other sites are using the "Microsoft Account" wording but are still using the windows flag icon like us...

**Comment by gravitystorm** [comment]
We're using an old Windows logo ([Vista or Windows 7 I think](http://logos.wikia.com/wiki/Microsoft_Windows)), whereas the Microsoft logo now includes [the coloured squares without the wave effect](http://logos.wikia.com/wiki/Microsoft). I would go for the coloured squares part of the Microsoft logo since that's what's shown on the following page.

**Comment by tomhughes** [comment]
Well that's an interesting question...

Probably yes, despite that fact that the "windowslive" name also appears throughout the code.

The only other thing we might want to do is change the provider name, so the URLs don't have it in, but they only appear briefly and changing that will mean running a migration and also starts to make the source inconsistent unless we change it everywhere.

**Comment by tomhughes** [comment]
I mean that the code is littered with that text especially in the tests.

The provider name is the value with goes in the database to identify which auth provider is in use for a given user, and which appears in the auth and callback urls.

**Comment by neboduus** [comment]
Ok all clear! I will try to solve this little issue and do a pull request. If I will need suggestions I will use this issue discussion to ask. If you everyone have others things to be taken into consideration let me know.

**Comment by noloman** [comment]
hi! is this issue still up for grabs? I'd like to start collaborating! 
Thanks!

**Comment by tomhughes** [comment]
Yes it is still up for grabs.

**Comment by SachitSankhe** [comment]
Hi, is this issue still up for resolving

**Comment by faebebin** [comment]
Also stumbled across and would like to implement this. Think the logo is already updated:
![image](https://user-images.githubusercontent.com/21113500/174648518-175f8751-9cd8-4bf3-a008-238d7aacc636.png)
So do we still want to change the repo strings [.*windowslive > .*microsoftaccout etc] and other relicts?

**Comment by konrad-wila** [comment]
I don't think it's a good idea to replace all instances of "windowslive" with "microsoft" in the code. Even though the branding for Windows Live has been discontinued by Microsoft, the omniauth-windowslive library we're using still makes sense to keep references to "windowslive". This will make it easier to replace the library if needed in the future.

Instead of updating the code, I suggest that we focus on changing the user-facing text, such as "Sign in with Windows Live" or "Login with a Windows Live Account".

**Comment by konrad-wila** [comment]
[I have had a look at the library we are using. Properly moving from windows live social sign-in to Microsoft account sign-in would involve moving oauth from login.live.com (old) to login.microsftonline.com (new). The ominiauth-windowslive library is basically a URL encoder for Microsoft's implementation of OAuth 2.0 on their old domain.

A probable deduction of mine is that the two domains could be interchangeable with the right encoding. However, I'm not entirely certain and could be something that could be put forward to Microsoft. @tomhughes @wtrbtl03

If true this would involve rewriting the ominiauth-windowslive for this new domain + encoding or finding another ruby library out there somewhere.

Sources:

old: [https://web.archive.org/web/20170711195343/http://msdn.microsoft.com/en-us/library/hh243647.aspx](url)

new: [https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow](url)

**Comment by tomhughes** [comment]
I wouldn't worry about it for now - like you say they're almost certainly redirecting the URLs and if they ever stop then the omniauth provider will likely get fixed or a new one written or we can easily fork it if necessary.

There is actually omniauth-microsoft-office365 already which uses the new URLs and would probably work.

**Comment by HolgerJeromin** [comment]
Can be closed?
