### ISSUE TITLE
ID editor not working after install according manual

### ISSUE THREAD

**Issue by Karmadon** [openstreetmap/openstreetmap-website#1829]
```
NameError in Site#edit
Showing /home/osm/openstreetmap-website/app/views/site/_id.html.erb where line #4 raised:

uninitialized constant ActionView::CompiledTemplates::ID_KEY
```
![1](https://user-images.githubusercontent.com/4281848/38987904-1017b6e2-43da-11e8-99d8-7c049687cff4.png)

**Comment by tomhughes** [comment]
User error - you haven't configured an OAuth application for iD.

**Comment by tomhughes** [comment]
See https://github.com/openstreetmap/openstreetmap-website/blob/master/CONFIGURE.md#oauth-consumer-keys.

**Comment by Karmadon** [comment]
My bad
Sorry
THX
Closed
