### ISSUE TITLE
Inaccurate street name 

### ISSUE THREAD

**Issue by tonydm** [openstreetmap/openstreetmap-website#1831]
Hello, new to Openstreet Maps and just learning this is open source.  I don't yet know how to fix the issue I found.  But there is an inaccurate street name Civic Dr which should be Loos Dr.  Prescott Valley, AZ 86314.  Please See http://gis.yavapai.us/v4/  The fact is I'm finding a number of mapping software with the incorrect street name as well.  I live here, it is Loos Dr.  Thank you

**Comment by HolgerJeromin** [comment]
https://www.openstreetmap.org/fixthemap has a list of option for that. Try it  :)

**Comment by Firefishy** [comment]
This issue tracker is for fixing bugs with the website software. Hope you come right with the fixthemap link above.
