### ISSUE TITLE
Query Feature says Bad Request

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/openstreetmap-website#1843]
Since some days now, the Query Feature feature consistently fails with `Error contacting https://overpass-api.de/api/interpreter: Bad Request`.

The query it appears to be sending is (split on multiple lines and indented):
```javascript
[timeout:10][out:json];
(
  node(around:10,40.68925,-74.04454);
  way(around:10,40.68925,-74.04454)
);
out+tags+geom(40.688320248612015,-74.04532760381699,40.69015880670406,-74.04373168945312);
relation(around:10,40.68925,-74.04454);
out+geom(40.688320248612015,-74.04532760381699,40.69015880670406,-74.04373168945312);
```

**Comment by tomhughes** [comment]
Unfortunately that service is outside our control - all we can do is send it queries and hope.

**Comment by tomhughes** [comment]
So I assumed you meant a general failure of the overpass service but actually it's only one of the queries that is failing, and it is actually reporting an error if you dig a bit deeper in the inspector:

```
Error: line 1: parse error: ';' expected - ')' found.
Error: line 1: parse error: Unexpected end of input.
Error: line 1: static error: Element "print" cannot be subelement of element "union".
Error: line 1: static error: Element "print" cannot be subelement of element "union". 
```

I have no idea what it means though... I assume that the initial segment is the "union" but I have no idea which item is the "print" it is complaining about.

**Comment by tomhughes** [comment]
Ah I think it wants a semicolon after the second entry in the union.

**Comment by mmd-osm** [comment]
Yes, the semicolon was missing. Roland deployed version 0.7.55 on one of the two production servers earlier today, and this version has a slightly more restrictive syntax check with regards to the union statement. The other server currently still runs on 0.7.54, so there's like a 50% chance you would hit this issue today.

**Comment by M1dgard** [comment]
> So I assumed you meant a general failure of the overpass service

Err yeah, my bad, I wasn't clear. I had seen the more detailed error messages but I had forgotten to write about them.

**Comment by westnordost** [comment]
Hmm, if 0.7.55 introduces changes that make previously-working queries fail, shouldn't it be named 0.8.0 then?

**Comment by mmd-osm** [comment]
Overpass uses a different versioning schema: this is really a change from 0.7.54.13 to 0.7.55 (.0).

**Comment by drolbr** [comment]
I'm sorry. If was of course not intended to break things.

However, the omission of the semicolon never was intended as valid syntax. And I never checked that that worked and that anybody used that. I'm sorry for the inconvenience. Thank you, M1dgard for reporting the thing and thank you, Tom, for fixing it.
