### ISSUE TITLE
Integrate the high-performance GPX importer

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#1852]
For a long time the OSMF has used a [high performance GPX importer](https://github.com/openstreetmap/gpx-import) to process uploaded traces. This runs as a separate daemon on the servers, unrelated to this code.

This has a number of drawbacks:

* There is a lot of ruby code in this repo for importing traces that is [unused and bitrotting].(https://github.com/openstreetmap/openstreetmap-website/issues/281)
* The emails sent by the GPX importer [are not translated](https://github.com/openstreetmap/gpx-import/tree/master/templates).
* There is no queue management for pending traces, so only one import process (on one server) can run at any time.
* The daemon needs its own installation and configuration, its own connections to the database, and its own ability to send mail.

Having a daemon running background tasks is fairly standard in the modern rails world. So I'd like to propose some changes:

* We use the [ActiveJob](http://guides.rubyonrails.org/active_job_basics.html) framework for managing the queue of traces that need importing.
* We rework the C code as a ruby gem, so that we can declare a dependency in the Gemfile and it gets installed and compiled for 'free' with bundler.
* We refactor so that only the parsing of the trace files is handled by the C code, and the email notifications and any other scaffolding comes from this rails app. This will allow us to support translations.
* We ensure that as many worker processes as are necessary can be run in parallel, to improve import speeds.

I'm not familiar at all with the C code, nor the operations of it in production, so any advice on this proposal is welcome!

**Comment by mmd-osm** [comment]
Out of curiosity, what was the main bottleneck motivating the switch to a C implementation?

Inserting gps_points is notoriously slow to the use of single insert, but would probably benefit quite a bit from a bulk insert operation via `activerecord-import `(-> affects https://github.com/openstreetmap/openstreetmap-website/blob/master/app/models/trace.rb#L292-L307). So this part could be covered by some Rails code with decent performance.

I'm not sure if parsing GPX files as such is really an issue. Once I disable `tp.save!` in trace.rb, processing traces via gpx_import.rb is really fast.

The calculation of the `tile` value is already exposed via another Gem (native implementation), and is only duplicated in the GPX importer.

Then there's some image generation which I don't know much about. Could this be the only thing left worthwhile keeping in a native gem?

**Comment by gravitystorm** [comment]
I had a conversation with @zerebubuth two weeks ago, and he was also suggesting that it might not be worth keeping the C implementation, and instead just refactoring the ruby version to be performant.

**Comment by tomhughes** [comment]
Well I suspect `activerecord-import` didn't exist, or we didn't know of it's existence.

**Comment by tomhughes** [comment]
First version of `activerecord-import` is from 2010 and our C version of `gpx-import` already existed by November 2008 at least (that is when git starts but it was imported from a bzr repo).

**Comment by mmd-osm** [comment]
> (perhaps this is what activerecord-import helps with?).

Yes, it seems to be effective. I'm currently playing around with the same tricks employed in the diff_upload pr, i.e. a combination of turning off pointless checks for each gps point, as well as combining multiple inserts into one large insert. Perhaps someone much more familiar with Rails should review, if this all makes sense.

One my test GPX with 4000 points this reduces runtime from 20+s down to some 200ms. 

```
D, [2018-10-03T16:49:57.057361 #20880] DEBUG -- :   Trace Load (0.1ms)  SELECT  "gpx_files".* FROM "gpx_files" WHERE "gpx_files"."id" = $1 LIMIT $2  [["id", 21], ["LIMIT", 1]]
D, [2018-10-03T16:49:57.057420 #20880] DEBUG -- :   ↳ app/models/trace.rb:314
D, [2018-10-03T16:49:57.057880 #20880] DEBUG -- :   User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, [2018-10-03T16:49:57.057956 #20880] DEBUG -- :   ↳ app/models/trace.rb:314

```


```
--- a/app/models/trace.rb
+++ b/app/models/trace.rb
@@ -28,6 +28,8 @@
 class Trace < ActiveRecord::Base
   self.table_name = "gpx_files"
 
+  attr_accessor :skip_uniqueness
+
   belongs_to :user, :counter_cache => true
   has_many :tags, :class_name => "Tracetag", :foreign_key => "gpx_id", :dependent => :delete_all
   has_many :points, :class_name => "Tracepoint", :foreign_key => "gpx_id", :dependent => :delete_all
@@ -37,7 +39,7 @@ class Trace < ActiveRecord::Base
   scope :visible_to_all, -> { where(:visibility => %w[public identifiable]) }
   scope :tagged, ->(t) { joins(:tags).where(:gpx_file_tags => { :tag => t }) }
 
-  validates :user, :presence => true, :associated => true
+  validates :user, :presence => true, :associated => true, :unless => :skip_uniqueness
   validates :name, :presence => true, :length => 1..255
   validates :description, :presence => { :on => :create }, :length => 1..255
   validates :timestamp, :presence => true

```
```

--- a/app/models/tracepoint.rb
+++ b/app/models/tracepoint.rb
@@ -25,9 +25,10 @@ class Tracepoint < ActiveRecord::Base
 
   self.table_name = "gps_points"
 
+  attr_accessor :skip_uniqueness
   validates :trackid, :numericality => { :only_integer => true }
   validates :latitude, :longitude, :numericality => { :only_integer => true }
-  validates :trace, :associated => true
+  validates :trace, :associated => true, :unless => :skip_uniqueness
   validates :timestamp, :presence => true
 
   belongs_to :trace, :foreign_key => "gpx_id"


```

```
    tps = []
    gpx.points do |point|
      if first
        f_lat = point.latitude
        f_lon = point.longitude
        first = false
      end

       tp = Tracepoint.new
       tp.lat = point.latitude
       tp.lon = point.longitude
       tp.altitude = point.altitude
       tp.timestamp = point.timestamp
       tp.gpx_id = id
       tp.trackid = point.segment
       tp.skip_uniqueness = true
       tps << tp
    end
    
    Tracepoint.transaction do
      Tracepoint.import(tps)
    end
```

**Comment by tomhughes** [comment]
I don't understand what that does - you seem to have declared a `skip_uniqueness` attribute and then used that to disable user validation, but nothing ever sets that attribute?

I assume you have something in the import daemon code which sets it? But then what validates the relationships? If it is "pointless" as you suggest then why not get rid of it?

Certainly that "solution" looks like a pretty horrid hack...

**Comment by mmd-osm** [comment]
>  but nothing ever sets that attribute

Well, skip_uniqueness actually gets set for each tracepoint we add to `tps` by setting `tp.skip_uniqueness = true`.

> If it is "pointless" as you suggest then why not get rid of it

Pointless was more meant in a sense, that we're running the following 2 SELECTs for _each single GPS point_. Obviously this is a bit of a waste, as the trace file id, as well as the users id will be identical all the time. Assuming `tp.gpx_id = id` uses the correct id, there's no point checking this over and over.

```
SELECT  "gpx_files".* FROM "gpx_files" WHERE "gpx_files"."id" = $1 LIMIT $2  [["id", 21], ["LIMIT", 1]]
SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
```

By the way, maybe the change to trace.rb above will not be needed, once the _tracepoint --> trace_ validation is disabled.

**Comment by tomhughes** [comment]
So the bulk inserter doesn't have the brains to batch up the checks I take it... Given that there is only actually one trace ID and one user ID to check for everything...

I really dislike it being an attribute that is set on each point... One option might be to validate (using a custom validation context) and then save with validation disabled and use `:on` on the validation to suppress it in the custom validation context. Annoyingly `:on` is a whitelist and there is no blacklist version of it, so we would have to list the contexts where we wanted it to work which I think is just `:create` and `:update` as the defaults.

**Comment by mmd-osm** [comment]
https://github.com/zdennis/activerecord-import/wiki/Examples seems to suggest a different way of selectively turning off validations for the bulk insert:

```
# without validations
Book.import books, :validate => false

```

 This may be a more idiomatic approach as it avoids adding some artifical attributes via attr_accessor

**Comment by mmd-osm** [comment]
After a bit more testing... Once gem "activerecord-import" gets added to the Gemfile,` trace.rb` `import` method could be enhanced to use bulk inserts via the following code. I also added the `tile` field, which wasn't included in the original source yet. If I'm not missing anything, this should really be all. SELECT for validation purposes also won't show up in the trace.

```ruby
    # If there are any existing points for this trace then delete them
    Tracepoint.where(:gpx_id => id).delete_all

    tps = []
    gpx.points do |point|
      if first
        f_lat = point.latitude
        f_lon = point.longitude
        first = false
      end

      tp = Tracepoint.new
      tp.lat = point.latitude
      tp.lon = point.longitude
      tp.altitude = point.altitude
      tp.timestamp = point.timestamp
      tp.gpx_id = id
      tp.tile = QuadTile.tile_for_point(point.latitude, point.longitude)
      tp.trackid = point.segment
      tps << tp
    end
    
    Tracepoint.import tps, :validate => false
```

**Comment by tomhughes** [comment]
The `tile` field should get filled in automatically on save - the `Tracepoint` model includes `GeoRecord` which adds a `before_save` handler to set it.

**Comment by tomhughes** [comment]
You're aware of the `lib/daemons/gpx_import.rb` code I take it? That's likely where any transaction should go if it doesn't just go in the `import` method itself?

That said the daemon code may well just need a rewrite - it was based around an ancient rails feature for running daemons that I suspect is long since abandoned and we likely want something based on `ActiveJob` or something now.

**Comment by mmd-osm** [comment]
Yes, I'm using gpx_import.rb for testing, which sort of works ok. I did some some minor tweaks to "Trace.find(:all,...", which somehow failed all the time.

Curiously, tile was always NULL, that why I even considered adding it in the code. So instead of calling  Quatile directly, I could also get the same done  via `tp.update_tile`. I just don't get any tile number by running Tracepoint.import alone:

```ruby
      tp = Tracepoint.new
      tp.lat = point.latitude
      tp.lon = point.longitude
      tp.altitude = point.altitude
      tp.timestamp = point.timestamp
      tp.gpx_id = id
      tp.trackid = point.segment
      tp.update_tile
      tps << tp
    end
```

**Comment by mmd-osm** [comment]
> That said the daemon code may well just need a rewrite - it was based around an ancient rails feature for running daemons that I suspect is long since abandoned and we likely want something based on ActiveJob or something now.

I tried the following for ActiveJob:

`rails generate job GPXUpdater`

Moved some of the code from gpx_import.rb to one of the newly generated file gpx_updater_job.rb:

```ruby
logger = ActiveRecord::Base.logger

class GpxUpdaterJob < ApplicationJob
  queue_as :default

  def perform(id)
    ActiveRecord::Base.logger.info("GPX Import daemon wake @ #{Time.now}.")

    trace = Trace.find(id)

    begin
      gpx = trace.import

      if gpx.actual_points.positive?
        Notifier.gpx_success(trace, gpx.actual_points).deliver
      else
        Notifier.gpx_failure(trace, "0 points parsed ok. Do they all have lat,lng,alt,timestamp?").deliver
        trace.destroy
      end
    rescue StandardError => ex
      print (ex.to_s)
      logger.info ex.to_s
      ex.backtrace.each { |l| logger.info l }
      Notifier.gpx_failure(trace, ex.to_s + "\n" + ex.backtrace.join("\n")).deliver
      trace.destroy
    end
  end
end
```

and finally added one line to the traces_controller.rb run run `GpxUpdaterJob.perform_later(trace.id)`

```ruby
          # Pass the exception on
          raise
        end
      end

      GpxUpdaterJob.perform_later(trace.id)
    end
  
    # Finally save the user's preferred privacy level
    if pref = current_user.preferences.where(:k => "gps.trace.visibility").first
      pref.v = visibility
      pref.save
    else
```

Creating icons didn't work for whatever reason, and I had to comment them out in trace.rb:

**Comment by mmd-osm** [comment]
Before switching all GPX import processing to background jobs, we should also re-validate, if current processing times for a typical / maximum sized GPX file still warrant such an approach.

Assuming that an import takes less than 5 seconds, we could as well do everything in a synchronous way. At the same time, we could get rid of the email notification (which ends up in the spam folder anyway) and show the user a flash message with the success/failure status right away. Very large GPX file could still be redirected to some kind of job processing, depending on file size.

**Comment by gravitystorm** [comment]
> Assuming that an import takes less than 5 seconds, we could as well do everything in a synchronous way.

I don't think this is a good idea. If a group of people upload a burst of gpx files in parallel (e.g. 1000 files) and each takes 5 seconds of CPU time, then that can tie up all the threads on the servers for a while. We already have a system to prevent people from having too many queued for processing. Best to keep the  queue, so that they can be processed in the background, even if there's a spike of activity.

With proper integration into the site, we can show the user the number of their uploads that are pending, display a notification on the site when they are done, etc. I'm just not in favour of doing anything synchronously that could be done in the background.

**Comment by tomhughes** [comment]
That's all the upload does anyway - store whatever file the user provides.

Everything else is done during the import.

**Comment by gravitystorm** [comment]
Time has moved on, and this issue has been superseded. With #2120 and #2131 it's no longer necessary to integrate the gpx-import code itself, since we now have a reasonable method to import traces using lib/gpx.rb and ActiveJob, and further effort would be better spent on that code rather than the original idea presented here.
