### ISSUE TITLE
Allow users to close their own accounts

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#1853]
The current procedure for closing an account [is cumbersome](https://wiki.openstreetmap.org/wiki/FAQ#How_can_I_close_my_account.3F):

> Send an email to the support address and an administrator will disable your account and remove your details from the OpenStreetMap database. Your email address will usually be retained in the event that an OpenStreetMap administrator needs to contact you in the future. 

It's not even linked to from the website, you need to find these instructions yourself! Moreover, it leads to the sysadmins having to verify that the email address that they receive the request from isn't being spoofed, and that there's no shenanigans going on, be sufficiently multilingual and other administrivia.

Instead, users should be able to close their own accounts.

There could be an appropriate link in the settings page, which then leads to a page explaining exactly what will happen (what will be removed, what things will remain) and the consequences, and finally allow them to close their account. I think everything regarding account closure is automated already, but if not we should add the missing links.

**Comment by simonpoole** [comment]
Unluckily directly self closing accounts is not going to fly as it allows hit and run vandalism and other mischief that can't be analysed reasonably by the community without the user information, particularly considering that we will be setting the anonymous flag on such accounts going forward. That doesn't mean that there shouldn't be a button that initiates deletion, just that it does need to be reviewed.

This is however not a concern for accounts that have no associated activity, these could be removed without any further action.    

@woodpeck ^^^

**Comment by gravitystorm** [comment]
@simonpoole OK, sounds like it's even more necessary to automate some of this! In that case, we could put the request into a queue, and someone (e.g. moderators or site admins) could review the closure requests before actioning them.

Do you see any need for users to explain why they want their account closed? Or would pushing the button be enough?

**Comment by simonpoole** [comment]
No strong feelings on this. As this is something that we are offering the users as part of balancing our interests vs. theirs and not based on the "right to be forgotten" we are free to do what ever we believe is reasonable. That said, the ability to add a comment to a deletion request would seem to be good, but not as a hard requirement.

**Comment by mmd-osm** [comment]
Some providers use a multi step approach: deleting the account deactivates access to all services, after some time (=weeks), the account will be permanently deleted.

Example:  https://support.microsoft.com/en-us/help/12412/microsoft-account-how-to-close-account

**Comment by gravitystorm** [comment]
@mmd-osm good suggestion! I'd be happy with that, so that accounts will get closed without requiring administrators to do busywork, but still giving the opportunity to review things.

**Comment by neboduus** [comment]
I am new in OSM, so I don't know what kind of business you follow (even because i am just a developer :))), anyway, I think that being more explicit with the users, even just by giving more information about why they could be contacted it would be good in both directions. Anyway if this topic will turn in some dev-modifications to be applied to the sw, it could look like something I could do, so I will follow the discussion

**Comment by pnorman** [comment]
I'd like to see this, as deleting accounts is one of the common tasks that requires sysadmin time.

I was thinking for vandalism tracking purposes we could make sure that the account gets renamed to something with a synthetic user name so any vandalism would appear under that user name. We then have the separate issue that it's hard to go from user ID to user name or get the page of a user ID.

I was thinking that, but I'm not sure how the vandalism tracking issues are any worse than someone who renames their account and then leaves.

**Comment by tomhughes** [comment]
@pnorman all we need is the UI work - the underlying technology already exists and takes care of renaming the account etc.

**Comment by julianfairfax** [comment]
I'm also looking forward to this feature. I really appreciate when a site lets me delete an account myself with a click of a button.

**Comment by tomhughes** [comment]
This was implemented by #3398.
