### ISSUE TITLE
don't require verbose user-agent header

### ISSUE THREAD

**Issue by ilf** [openstreetmap/openstreetmap-website#1855]
The website requires a user-agent header that's really verbose.

Using a user-agent header like "Mozilla/5.0" results in map tiles not being displayed, even in current browsers like Chrome 66, Firefox 60 and Firefox ESR 52.

Verbose user-agent headers reveal a lot of information and can be used for fingerprinting. Plese allow a minimalist user-agent header like "Mozilla/5.0.

Thanks, and keep up the good work!

**Comment by Firefishy** [comment]
The issue we have is abuse tile scrapers use faked User-Agents like just "Mozilla/5.0".

**Comment by ilf** [comment]
@Firefishy: Do you have data on those scrapers?

I would think that a scraper that gets an error with a simple user agent just re-tries with a more sophisticated one. If someone really wants to scrape, that's minimal effort.

On the other hand, this measure prevents legitimate users from viewing the tiles (and therefore, the very essence of OSM itself). In fighting spam, those false positives should ideally be zero, even if it means the false negatives go down a little.

**Comment by tomhughes** [comment]
This is a tile server issue not a web site issue in any case - the web site doesn't care what user agent you send.

**Comment by ilf** [comment]
@tomhughes: What's the correct place to file an issue against the tile server?

**Comment by tomhughes** [comment]
Well https://github.com/openstreetmap/operations/ probably but this has been done very deliberately and I think we're unlikely to change it - there are just too many fake user agents that look like that and they far outweigh the tiny number of people who deliberately configure a genuine browser to look like that.
