### ISSUE TITLE
Make wiki.openstreetmap.org faster

### ISSUE THREAD

**Issue by tordans** [openstreetmap/openstreetmap-website#1856]
Please make wiki.openstreetmap.org faster.
The page load time is very bad. 
It makes looking up knowledge unnecessary bothersome.

For reference, two pages that are not used often
- Wikipedia: [81 of 100 Speed points in PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwiki.openstreetmap.org%2Fwiki%2FLandcover&tab=desktop)
- OSM Wiki: [47 of 100 Speed points in PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwiki.openstreetmap.org%2Fwiki%2FLandcover&tab=desktop) with the first being "make the server respond faster".

(I don't know if this is the right place, please redirect me if not.)

**Comment by tomhughes** [comment]
This repository is for web site issues - the wiki is out of scope here.

**Comment by tomhughes** [comment]
BTW most speed problems with the wiki come down to people creating crazy template transclusions that means a "page" actually rendering about 500 templates.

**Comment by tomhughes** [comment]
If you really want to raise this then https://github.com/openstreetmap/operations/ is probably the place but there isn't really anybody looking after the wiki so I wouldn't expect much.
