### ISSUE TITLE
Vector Tiles on osm.org

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/openstreetmap-website#1875]
I've been reviewing the [Top 10 Tasks list](https://wiki.openstreetmap.org/wiki/Top_Ten_Tasks), and noticed that several of the issues reference **vector tiles** as a possible way forward.
* Localized Map Rendering - https://github.com/osmlab/osm-planning/issues/9
* Clickable POIs - https://github.com/osmlab/osm-planning/issues/16

This is also something that pops up for discussion sometimes here in this repo (#1672 #1623 #1316)

Let's start a discussion about what it would look like to add a vector tile option to openstreetmap.org! Even if it's just a trial or staged rollout available only in some areas, I think it would be great to explore vector tiles as a path forward on some of these issues.  

I think we all agree that if something is on the Top 10 Tasks list, it's important to enough to people that it's worth doing.  It's time!  ✨

**Comment by tomhughes** [comment]
This isn't (oddly enough) a web site issue, it's an operations issue.

Yet another discussion really isn't going to get us anywhere though - we need somebody to maintain a stylesheet and somebody with relevant expertise to tell me what toolchain to setup. The two are of course likely linked.

**Comment by bhousel** [comment]
This issue was moved to openstreetmap/operations#214

**Comment by bhousel** [comment]
> This isn't (oddly enough) a web site issue, it's an operations issue.

Ok, no problem.. I moved the issue.
