### ISSUE TITLE
Add a "report inaccurate data / map feature" menu item

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1887]
Add a "report inaccurate data / map feature" menu item.

Not all users want to or are prepared to make a full edit,
so this would, just like Google has, a way to just report map errors.

**Comment by tomhughes** [comment]
That's exactly what notes are for - icon on the right hand side:

![](https://screenshotscdn.firefoxusercontent.com/images/0ce8d921-5a18-4d22-99c3-024f0a5ff04f.png)
