### ISSUE TITLE
vagrant up failing due to permission issue and more

### ISSUE THREAD

**Issue by mikehwang** [openstreetmap/openstreetmap-website#1888]
I cloned latest from master and ran `vagrant up`.  Running into the following issue:

```
...
    default: Successfully installed bundler-1.16.2
    default: Parsing documentation for bundler-1.16.2
    default: Installing ri documentation for bundler-1.16.2
    default: Done installing documentation for bundler after 4 seconds
    default: 1 gem installed
    default: /srv/openstreetmap-website /home/vagrant
    default: There was an error while trying to write to
    default: `/srv/openstreetmap-website/.bundle/config`. It is likely that you need to grant
    default: write permissions for that path.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I think the problematic line in the provision.sh script is:

```
# do bundle install as a convenience
sudo -u ubuntu -H bundle install --retry=10 --jobs=2
```

I made an attempt to fix this by doing `vagrant ssh` into the VM and ran:

```
vagrant@ubuntu-xenial:/srv$ sudo chmod -R 777 openstreetmap-website
```

I got further but not much.  Now I have the following error:

```
vagrant@ubuntu-xenial:/srv/openstreetmap-website$ sudo -u ubuntu -H bundle install --retry=10 --jobs=2
Fetching gem metadata from https://rubygems.org/...........
Fetching rake 12.3.1
Installing rake 12.3.1
Errno::EPERM: Operation not permitted @ chown_internal - /tmp/bundler20180530-22084-xy0qt9rake-12.3.1/bin
An error occurred while installing rake (12.3.1), and Bundler cannot continue.
Make sure that `gem install rake -v '12.3.1' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  annotate was resolved to 2.7.3, which depends on
    rake
```

Help.  Thank you.

**Comment by tomhughes** [comment]
Please, please, never ever do a recursive chmod 777 like that!

**Comment by tomhughes** [comment]
I believe I'm right in saying (the vagrant stuff is not something I have much to do with) that the /srv/openstreetmap-website directory in the guest is actually bound in from the host?

I suspect that you really need to fix the permissions on that directory in the host or something but as I say I'm no expert and I'm not sure we really have anybody using the vagrant stuff.

**Comment by tomhughes** [comment]
@geohacker encountered the same problem in #1876 but I don't know if he ever figured it out

**Comment by mikehwang** [comment]
Thanks @tomhughes for replying!  Regarding the permission issue, I think this is a bug in the Vagrantfile that was introduced by this commit https://github.com/openstreetmap/openstreetmap-website/commit/89ba5eab46ae6c2ecb30af538604ed17a13f4994

The fix seems to be to update the Vagrantfile to:

```
override.vm.box = "ubuntu/xenial64"
override.vm.synced_folder ".", "/srv/openstreetmap-website",
    owner: "ubuntu", group: "ubuntu"
```

Another possible change is to revert the use of the `ubuntu` user in the `provision.sh` script.  Would be helpful for @Firefishy to explain why this switch (from use of the `vagrant` to `ubuntu`) was made.

The change above gets me past the permission issue and now I'm hitting the rake dependency issue...

**Comment by tomhughes** [comment]
Well sure, but I don't really know enough to review it... My main question surrounds the need to sudo to ubuntu in the guest - what user is the ssh running as in the guest before you do that?

**Comment by mikehwang** [comment]
> what user is the ssh running as in the guest before you do that?

```
$ vagrant ssh
Welcome to Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-127-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


Last login: Thu May 31 15:55:30 2018 from 10.0.2.2
vagrant@ubuntu-xenial:~$ whoami
vagrant
```

Also when you mount the host folder, the permissions are for `vagrant:vagrant` so I'm not sure why things were changed to `ubuntu` in that commit I pointed out.

**Comment by tomhughes** [comment]
Right, so why not bind in the files as the vagrant user rather than binding them in as ubuntu and then having to sudo in the guest?

**Comment by mikehwang** [comment]
> then having to sudo in the guest?

Sorry I didn't understand this part.  The provision script currently does this:

```
sudo -u ubuntu -H bundle install --retry=10 --jobs=2
```

What is the change you are suggesting?

**Comment by tomhughes** [comment]
I was referring to where it now starts the server as ubuntu.

I'm playing with it now but using a different ubuntu image that doesn't actually have an ubuntu user! It does have the advantage of working across all the differerent providers though rather than just on virtualbox.

**Comment by tomhughes** [comment]
I've attempted to fix things up in https://github.com/openstreetmap/openstreetmap-website/commit/619fa7d802d3731f04d0029e7fc73bc67567cc3f so please give that a go and see if it works better for you - all my testing was with the libvirt driver so you may have slightly different issues with virtualbox.

**Comment by mikehwang** [comment]
Thanks @tomhughes .  I just tried your changes but I got the following error:

```
==> default: Mounting shared folders...
    default: /srv/openstreetmap-website => /home/mhwang/workspace/labs/mw/3rd-party/openstreetmap-website
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 srv_openstreetmap-website /srv/openstreetmap-website

The error output from the command was:
```

I think `generic/ubuntu1604` doesn't have the virtualbox guest additions installed which is needed to share a directory on the host to the guest.  Replacing `generic/ubuntu1604` with `ubuntu/xenial64` worked.

**Comment by tomhughes** [comment]
Damn. That sounds like the generic/ubuntu1604 doesn't have the relevant vbox extensions.

Can't say I blame them, but still it's annoying for people that have been persuaded to use vbox...

Does it work if you change Vagrantfile to use the same box as before (the ubuntu/ one) for Vagrant?

**Comment by mikehwang** [comment]
Yes replacing `generic/ubuntu1604` with `ubuntu/xenial64` in the Vagrantfile worked.

**Comment by tomhughes** [comment]
Thanks. I've pushed that change in https://github.com/openstreetmap/openstreetmap-website/commit/b6c36c85456efa4a5e7884a4e6332db07589e770 so I think we can close this now.

**Comment by mikehwang** [comment]
Great!  I'm using the latest off master now.  Thanks for helping me on this issue.

**Comment by geohacker** [comment]
Oh this is amazing, I didn't dig further but got around by switching users inside the container. 
Thank you for fixing @tomhughes @mikehwang!
