### ISSUE TITLE
Getting 404 NotFound for POST api/0.6/gpx/create

### ISSUE THREAD

**Issue by HarelM** [openstreetmap/openstreetmap-website#1889]
I'm getting a new error message when trying to upload a trace using the API:
I'm sending a POST request with all the relevant data to http://www.openstreetmap.org/api/0.6/gpx/create
and I'm getting back a 404.
This request has all the relevant headers as far as I can see, I don't want to share it due to security reasons.
I'm getting the same 404 both in the production and dev environments.
Delete gpx trace is working using a similar code I wrote with almost the same headers so I tend to think this is not something in my code.
Can someone confirm?
Thanks ahead!

**Comment by tomhughes** [comment]
How is anybody supposed to confirm? Only you have access to your machine and your code so nobody else can possibly confirm what you are seeing.

What I can confirm is that nobody else has reported this, so it it likely unique to your code/environment.

As a starting point, change your URL to use https.

**Comment by tomhughes** [comment]
Further to that I can say that every POST request to that URL logged on one of our three production servers has a 200 response - all the 404 responses are for GET requests.

**Comment by tomhughes** [comment]
Judging by the logs on the dev api you are trying a POST over http and getting a redirect to https then doing the redirected request as a GET instead and getting a 404 response.

**Comment by HarelM** [comment]
Thanks for the info and the quick response!
Seems that I had some code that was converting the address from https to http for some reason which I don't remember why. Removing this code seems to solve the issue.
Is the redirect from http to https relatively new?

**Comment by tomhughes** [comment]
Well it's been there for a week or two now but relatively new, yes.

**Comment by HarelM** [comment]
OK, this explains the behavior change, thanks a lot!
