### ISSUE TITLE
Most Standard layer tiles empty today

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1890]
Today most  Standard layer tiles are just empty.
![1](https://user-images.githubusercontent.com/1230959/40895586-f018a43c-67e2-11e8-989b-9f8123f1f74e.jpg)
The user has to hit CTRL+Refresh each time just to see all the tiles.

**Comment by gravitystorm** [comment]
@jidanni any problems with the maps provided by the OSMF should be reported to the Operations Working Group at https://github.com/openstreetmap/operations . This makes sure that the right people are aware of the problem.
