### ISSUE TITLE
Add "measure distance"

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1891]
Directions are great, however the site forgot a more basic functionality: measure straight line distance from point A to B.

**Comment by tomhughes** [comment]
Nobody "forgot" anything. 

Either nobody has suggested such a feature, it has been suggested but nobody has stepped forward to implement it, or it has been suggested and we have decided it is not appropriate.

I have no idea which, but the idea that there is some mandatory set of features that are so obvious that only a complete idiot wouldn't have implemented it and that we must have forgotten to do so is just silly.

For what it's worth I would say that this is an end user feature of limited use to mappers and hence out of scope. Frankly I don't even see that it's great use to end users - do many other sites offer this?

**Comment by jidanni** [comment]
https://mashable.com/2014/07/09/google-maps-measure-distances/
Please combine with #1941.

**Comment by jidanni** [comment]
On #1941 I supplied the answer to "do many other sites offer this?" and in fact find that apparently all other sites offer this.

And if it were combined with Directions as an additional option other than Grasshopper, etc. right in the same menu, voila, you would have a way to supply permalinks to straight lines on the map, beating all services except Google Static Maps... but also having the distance shown. Beating them all!

**Comment by HolgerJeromin** [comment]
> beating all services except Google Static Maps

This is not the goal of osm.org website.

**Comment by jidanni** [comment]
Don't forget to toss in the azimuth while you are at it... rivaling even http://www.offline-maps.net/en/help/orientation .

Don't worry. You aren't beating them yet.
