### ISSUE TITLE
Make non-https remote josm possible

### ISSUE THREAD

**Issue by gorn** [openstreetmap/openstreetmap-website#1896]
For 4 years joism is struggling with nonfunctional remote control over https with some browsers. See https://josm.openstreetmap.de/ticket/10033#no3

Before it is solved it would be great to be able to use http (without s) for remote control. Please consider adding an option "Remote control via http" to "Preferred editor" on  page https://www.openstreetmap.org/user/xxxx/account

**Comment by tomhughes** [comment]
This just isn't possible in general because browsers won't allow an http load from https like that - where it is possible (on newer Chrome and Firefox) we already do it by default.

**Comment by tomhughes** [comment]
Specifically the code is https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/javascripts/index.js#L253 and if you know of browsers (other than chrome >= 53 and firefox >= 55) where this will work then please let us know and we can add them.

**Comment by gorn** [comment]
I do not know if it would work, but the current solution *does not work* in Firefox 60 either, so we have to find solution. What about opening the http link in new tab, and opening JOSM from there. I understand it is not optimal, but in Firefox 60 current solution does not work at all, so it is still better. For some reason it workis in Chromium 66. 

The problem is apparently with certificate. I am able manually put https://localhost:8112 and it gives me the "JOSM page". The reason might be that it does not consider the page secure - reason givens it "Could not verifz this certificate becase the issuer is unknown:
![snimek obrazovky porizeny 2018-06-18 13-58-58](https://user-images.githubusercontent.com/19652/41534744-db9f913c-72ff-11e8-8d7c-a30a7e0e3a51.png)

**Comment by tomhughes** [comment]
But if you're using firefox 60 it will use the http URL not the https one so the certificate is not relevant.

**Comment by tomhughes** [comment]
There does seem to be some sort of issue - we are setting `http://127.0.0.1:8111/load_and_zoom` as the URL on the iframe but firefox is actually trying to load `https://127.0.0.1:8111/load_and_zoom` for some reason.

**Comment by tomhughes** [comment]
Chrome is working but firefox 60 seems to be being silly :-(

**Comment by gorn** [comment]
Ok, than there is some sort of a mistake in the url, maybe the Firefox is wrongly detected. How can I help with this? I am using Firefox Quantum 60.0.2.

**Comment by tomhughes** [comment]
See my later comments, there is some sort of odd bug/behaviour in firefox that I don't currently understand.

**Comment by gorn** [comment]
Ok, if you can reproduce it, than my help is not needed. Hopefully this can be resolved, it slows down mapping substantially.
