### ISSUE TITLE
[Request] Forbid new users from creating diary entries

### ISSUE THREAD

**Issue by jc86035** [openstreetmap/openstreetmap-website#1898]
Similar to Wikipedia's [autoconfirmed](https://en.wikipedia.org/wiki/Wikipedia:User_access_levels#Autoconfirmed_users) permission, maybe new editors could be prevented (for anti-spam purposes) from creating diary entries; for example, while the user has fewer than ten (non-empty?) changesets and the account is less than four days old. Currently diary entries can be created by new accounts.

**Comment by tomhughes** [comment]
We already spam score on this basis, and a surprising number of users do post genuine diary entries without ever contributing to the map.
