### ISSUE TITLE
Standard Layer Rendering been awfully slow for the last month

### ISSUE THREAD

**Issue by ADepic** [openstreetmap/openstreetmap-website#1912]
A lot of the time, when I zoom in to small zooms, the tiles don't load (at all) leaving me with a blurry image. This happens with both osm-carto (standard) and the humanitarian layer.

It NEVER hapenns will cyclemap and transport map - both of which are faster at rendering anyway.

Why is this?

Can't osm-carto be as fast as cyclemap????

**Comment by tomhughes** [comment]
This is an operations issue rather than a web site issue but we're having some issues with some of the tile caches which we are working to resolve.

**Comment by ADepic** [comment]
When do you think the tile cache issue will be solved?

**Comment by tomhughes** [comment]
I don't have a timescale - just to check can you go to http://tile.openstreetmap.org/cgi-bin/debug and tell me which cache server it says you are using?

**Comment by ADepic** [comment]
tile.openstreetmap.org debug
Server Stats

Cache Server: saphira.openstreetmap.org

Render Server: orm.openstreetmap.org
Load Average: 23.25
File Status

world_boundaries-spherical.tgz last modified: Tue Jun 4 11:59:57 2013
simplified-land-polygons-complete-3857.zip last modified: Sun Jun 10 08:04:39 2018
ne_110m_admin_0_boundary_lines_land.zip last modified: Tue Jun 4 12:00:51 2013
land-polygons-split-3857.zip last modified: Sun Jun 10 08:05:13 2018
antarctica-icesheet-polygons-3857.zip last modified: Sun Jun 24 07:04:16 2018
antarctica-icesheet-outlines-3857.zip last modified: Sun Jun 24 07:04:30 2018
Browser Request Headers

CONTEXT_DOCUMENT_ROOT: /srv/tile.openstreetmap.org/cgi-bin/
SERVER_SOFTWARE: Apache/2.4.18 (Ubuntu)
CONTEXT_PREFIX: /cgi-bin/
SERVER_SIGNATURE:
Apache/2.4.18 (Ubuntu) Server at tile.openstreetmap.org Port 443

REQUEST_METHOD: GET
SERVER_PROTOCOL: HTTP/1.0
QUERY_STRING:
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HTTP_USER_AGENT: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
HTTP_CONNECTION: keep-alive
SERVER_NAME: tile.openstreetmap.org
REMOTE_ADDR: 185.73.44.30
HTTP_VIA: 1.1 saphira.openstreetmap.org:3128 (squid/2.7.STABLE9)
SERVER_PORT: 443
SERVER_ADDR: 193.63.75.98
DOCUMENT_ROOT: /srv/tile.openstreetmap.org/html
SCRIPT_FILENAME: /srv/tile.openstreetmap.org/cgi-bin/debug
SERVER_ADMIN: webmaster@openstreetmap.org
SCRIPT_URI: https://tile.openstreetmap.org/cgi-bin/debug
HTTP_DNT: 1
HTTP_HOST: tile.openstreetmap.org
SCRIPT_URL: /cgi-bin/debug
HTTPS: on
HTTP_UPGRADE_INSECURE_REQUESTS: 1
HTTP_CACHE_CONTROL: max-age=518400
REQUEST_URI: /cgi-bin/debug
HTTP_ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
GATEWAY_INTERFACE: CGI/1.1
HTTP_X_FORWARDED_FOR: 80.189.200.188, 127.0.0.1
SCRIPT_NAME: /cgi-bin/debug
REMOTE_PORT: 48352
HTTP_ACCEPT_LANGUAGE: en-US,en;q=0.5
REQUEST_SCHEME: https

**Comment by ADepic** [comment]
Places such as cotton green, mumbai just don't load at all if you zoom out a bit.

**Comment by tomhughes** [comment]
Oh saphira should be fine - it must be a network issue between you and us.
