### ISSUE TITLE
Add wilderness_hut icon to changeset view (browse.scss)

### ISSUE THREAD

**Issue by gaddman** [openstreetmap/openstreetmap-website#1913]
The tag `tourism=wilderness_hut` doesn't show any icon in the changeset view, while similar tags do (such as `tourism=alpine_hut` and `amenity=shelter`). It renders fine on the map, this is just related to the list of objects updated in a changeset, such as [#60107869](https://www.openstreetmap.org/changeset/60107869).
Are there limits to what is included in [browse.scss](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/stylesheets/browse.scss#L124)?
Also see discussion [here](https://help.openstreetmap.org/questions/64335/missing-icon-in-changeset-view-for-tourismwilderness_hut).

**Comment by tomhughes** [comment]
The limits are that we show what people submit entries for.

**Comment by gaddman** [comment]
Sweet. Does opening this issue count as submitting an entry, or do you mean I should fire through a PR?

**Comment by tomhughes** [comment]
No, this is just making a request.

Now you can just sit back and wait and maybe some day somebody will feel like doing it, but if you really want it a pull request will get you there a lot quicker.
