### ISSUE TITLE
Unable to zoom past level 19, users miss critical stairway

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1919]
Unable to zoom map past level 19, users miss critical stairway
https://www.openstreetmap.org/?mlat=24.62137&mlon=120.99124#map=19/24.62137/120.99124
and think that the road that it connects to is more accessible that it appears.

**Comment by tomhughes** [comment]
Not a web site issue.

**Comment by SomeoneElseOSM** [comment]
@jidanni If you'd like to render tiles at higher zoom levels, you're probably better off asking on https://help.openstreetmap.org (there's at least one similar question with answers there already).

**Comment by tomhughes** [comment]
Well I don't think this even needs higher zooms, it needs the road to be thinner - it's insanely wide at z19 really.

**Comment by jidanni** [comment]
I'm just saying the average public, using the website, will miss
critical gaps, cliff drops, etc.

I'm not saying the whole world needs tiles ready at every zoom level. It
is OK if there is a slight delay while tiles are being cooked up and
cached for users zooming higher.

**Comment by tomhughes** [comment]
None of which changes the fact that it's a matter for the style sheet in the first instance, and then for the operations team. The only role for the web site team would be to change 19 to 20 once the tiles were available.

**Comment by c933103** [comment]
However OSM-Carto already allow rendering up to zoom level 22:
https://github.com/gravitystorm/openstreetmap-carto/issues/3686#issuecomment-465779394
