### ISSUE TITLE
Multi Fetch GET for user details

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/openstreetmap-website#1921]
The API currently lets us fetch [details for a single user](https://wiki.openstreetmap.org/wiki/API_v0.6#Details_of_a_user) like this:
```
GET /api/0.6/user/#id
```

It would be nice to be able to fetch details for several users with a single call, similar to how we can do for [other OSM objects](https://wiki.openstreetmap.org/wiki/API_v0.6#Multi_fetch:_GET_.2Fapi.2F0.6.2F.5Bnodes.7Cways.7Crelations.5D.3F.23parameters):

```
Multi fetch: GET /api/0.6/[nodes|ways|relations]?#parameters
```
☝️ add to above things like.. `users`  `notes`

### why?
The reason I'm requesting this for `users` is because soon iD will start showing OSM notes:

<img width="960" alt="screenshot 2018-07-06 01 25 07" src="https://user-images.githubusercontent.com/38784/42361261-7ae1f76c-80bb-11e8-8487-b910b37672dd.png">

I'd like to include the user's profile pictures next to their comments.  So we currently just fire off a bunch of single user GET calls and cache the results, but would be nice to fetch many at a time.

---
related: 
https://github.com/openstreetmap/operations/issues/222
https://github.com/openstreetmap/openstreetmap-website/issues/1921
https://github.com/zerebubuth/openstreetmap-cgimap/issues/148

**Comment by mmd-osm** [comment]
Wiki documentation update: https://wiki.openstreetmap.org/wiki/API_v0.6#Details_of_multiple_users
