### ISSUE TITLE
User API call returns image in original size

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#1923]
User https://www.openstreetmap.org/user/Angkor%20Wat%20Putt has somehow managed to upload a huge 4160x3120 pixel avatar image. While this isn't shown on the user profile page, the user API call https://api.openstreetmap.org/api/0.6/user/1000005 returns an img URL for the original size. This may seriously screw up tools like OSMCha or iD which want to show a small avatar image next to a user. 

```XML
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="OpenStreetMap server">
  <user id="1000005" display_name="Angkor Wat Putt" account_created="2012-10-23T21:55:57Z">
    <description>Angkor Wat Putt is a fantastic and fun, 14 hole Miniature Golf Course in Siem Reap.Come and knock a ball under and around 9 accurate replicas of the world famous Angkor Temples. Including Angkor Wat, Ta Prohm, Bayon, Banteay Srei, Preah Vihear and the Terrace of the Elephants.Perfect for all the family, young and old. If you need a break from the actual temples to have a bit of fun then do it guilt free.The course is set in a large, well maintained garden with a bar and seating area. So come and spend a few hours and relax with us.</description>
    <contributor-terms agreed="true"/>
    <img href="https://api.openstreetmap.org/attachments/users/images/001/000/005/original/efd82f5510d48e4616c3feeb5b0712f1.jpg"/>
    <roles>
    </roles>
    <changesets count="6"/>
    <traces count="0"/>
    <blocks>
      <received count="0" active="0"/>
    </blocks>
  </user>
</osm>

```

There are 2 questions here:

* Would it make sense to limit the avatar image size to something reasonable during upload?
* Should we return a "large" image in the /api/0.6/user call, rather than the original image size?

Original vs Large:

https://api.openstreetmap.org/attachments/users/images/001/000/005/original/efd82f5510d48e4616c3feeb5b0712f1.jpg (6.28MB)
https://www.openstreetmap.org/attachments/users/images/001/000/005/large/efd82f5510d48e4616c3feeb5b0712f1.jpg (60KB)

**Comment by tomhughes** [comment]
I think it's entirely appropriate to return the best available image.

I have no object to returning the other alternatives as well.

**Comment by bhousel** [comment]
Thanks for raising this @mmd-osm  - yeah it would make me very happy if the image returned were one suitable to use as a thumbnail.  (see #1921)

It would also be ok if there were several urls, and I could pick an appropriate one to use.

**Comment by tomhughes** [comment]
After some investigation it turned out that there was a great deal of confusion and inconsistency here so I just fixed it to return the "large" image which is 100x100.
