### ISSUE TITLE
retina tile fails

### ISSUE THREAD

**Issue by mrx23dot** [openstreetmap/openstreetmap-website#1927]
retina tile fail:
https://b.tile.openstreetmap.org/18/125108/83543@2x.png

Not Found
The requested URL /18/125108/83543@2x.png was not found on this server.

Apache/2.4.18 (Ubuntu) Server at tile.openstreetmap.org Port 443

standard tile works:
https://b.tile.openstreetmap.org/18/125108/83543.png

**Comment by HolgerJeromin** [comment]
I am pretty sure tile.osm.org never had retina tiles  :)
