### ISSUE TITLE
Disallowing the creation of duplicate notes

### ISSUE THREAD

**Issue by hashtagdeamon** [openstreetmap/openstreetmap-website#1929]
I propose to implement a check before a note is added to the database to avoid duplicate notes. By "duplicate note" I mean two notes (A and B) with A already in the database and B to be created with the following properties:
- A's comment = B's comment (possibly ignoring capitalization)
- A's position (lat, lon) = B's position

There is no reason for a second note B to be added to the database. The [osm-wiki's guidelines](https://wiki.openstreetmap.org/wiki/Notes#Using_notes) allow/suggest to close B right away anyway. But as there are more than 10000 such notes in the db already and there are constantly new ones created, I suggest a check as part of the API/website. 

This would mostly affect maps.me, but as it is a general issue and maps.me itself has proven to be unable to fix it ([mapsme issue #4663](https://github.com/mapsme/omim/issues/4663)), I suggest a change on this side now.

**Comment by tomhughes** [comment]
This sounds like a ridiculous workaround for a bug that clearly lies somewhere else.

In the real world nobody is ever going to add a second note with both text and location that is an exact match so clearly this is a broken automated process somewhere and that is what should be fixed.
