### ISSUE TITLE
fail to vagrant up after I download the "openstreetmap-website"  file  according to the step

### ISSUE THREAD

**Issue by dog1993** [openstreetmap/openstreetmap-website#1930]
I use vagrant and VirtualBox Built a virtual environment on my Mac，and download the "openstreetmap-website"  file  according to the step. when i  vagrant up，default: make: *** No rule to make target '`/root`', needed by 'quadtile.o'.  Stop.   How do i fix it? Thanks.

**Comment by tomhughes** [comment]
No idea I'm afraid.

Sounds like maybe it was a problem installing the `quad_tile` gem but would need more context to be sure.

**Comment by tomhughes** [comment]
I'd add that I know nothing much about vagrant or macs so I may not be the best person to help anyway ;-)

**Comment by gravitystorm** [comment]
I can think of many different ways to solve this, but I'm not sure what would be best.

* Avoid installing the gems as root in the first place
* Complain to bundler about stdout vs stderr outputs!
* Change the Makefile to handle the garbled output better
* Probably many more options too

**Comment by dog1993** [comment]
I did the same thing on the Ubuntu system，and the error disappeared. So I decided to abandon vagrant.Maybe it's because I'm not unfamiliar with vagrant. Thank you very much

**Comment by dog1993** [comment]
@gravitystorm      I build up the “openstreetmap-website” on the Ubuntu system to avoid the error result of vagrant up. I hope I can succeed. Thank you very much

**Comment by dog1993** [comment]
@tomhughes  Thank you all the same.Maybe it's because I'm unfamiliar with vagrant.

**Comment by gravitystorm** [comment]
@dog1993 Just to be more clear - you have found a bug in our code, and this issue is now where we are trying to fix this bug. You did nothing wrong.

**Comment by gravitystorm** [comment]
> Complain to bundler about stdout vs stderr outputs!

https://github.com/bundler/bundler/issues/6067 - apparently will be fixed in bundler 2.0, but that doesn't help us here.
