### ISSUE TITLE
Sort order of https://www.openstreetmap.org/issues?status=open appears random

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/openstreetmap-website#1935]
Sort order of https://www.openstreetmap.org/issues?status=open appears to be random.

Not such a problem now with only a dozen or so issues, but will become more of one later.

Being able to vary the sort order (e.g. by clicking on column headings) would also be useful .

**Comment by tomhughes** [comment]
If you've got more issues than that showing then randomness is the least of our problems and we will need to start paging the results...

**Comment by SomeoneElseOSM** [comment]
(following numerous changes since 2018) the order is no longer random, and on https://www.openstreetmap.org/issues?status=open the selection criteria allow easier finding of particular issues.
