### ISSUE TITLE
500 if client OAuth ID is invalid

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/openstreetmap-website#1937]
I accidentally added a space after my OAuth client ID. The server responded with 500 Internal Server Error, this should really be 400 Bad Request.

**Comment by tomhughes** [comment]
It's an upstream bug in the OAuth library we use that's outside our control.

**Comment by M1dgard** [comment]
Okay, not a big deal.

**Comment by mmd-osm** [comment]
@M1dgard : for which URL did you encounter the http 500 error? Just to double check this isn't something in cgimap instead.
