### ISSUE TITLE
Remove hosting reference to Imperial College

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/openstreetmap-website#1944]
We've moved the site away from there. `partners_ic` is the name of the string.

**Comment by tomhughes** [comment]
This is tricky to fix because of the way the interpolation works... We really need to fix it in all languages simultaneously :-(

**Comment by tomhughes** [comment]
Oh sorry, didn't mean to close it - must have hit the wrong button.

**Comment by pnorman** [comment]
> This is tricky to fix because of the way the interpolation works... We really need to fix it in all languages simultaneously :-(

Ya, this is why I didn't just go and edit it, I couldn't easily figure it out.

> To show a bit of goodwill, I'm wondering if IC could be moved to some kind of "Alumni" partner section, e.g. partners, who have supported OSM over many years in the past.

They're listed on the hardware thanks page at https://hardware.openstreetmap.org/thanks/ but the main place the website shows the list is to new users in the notice box, where space is *very* limited.

![image](https://user-images.githubusercontent.com/1190866/43714170-017a6448-9931-11e8-815b-12317aaa0151.png)

**Comment by mmd-osm** [comment]
> the main place the website shows the list is to new users in the notice box, where space is very limited

Ok, I think I didn't quite get your original intent somehow. I really had the _about page_ in mind, which also uses that same  `partners_ic` text: https://www.openstreetmap.org/about . There's also a direct link from the osm main page.
