### ISSUE TITLE
GPX tracks don't delete.

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/openstreetmap-website#1945]
About seven months ago, I deleted some of my GPX tracks from OpenStreetMap.  The message that they were now scheduled for deletion appeared.  They are still showing up in the GPX Tracks layer of the main page as of August 9th, 2018.

**Comment by tomhughes** [comment]
As @simonpoole says the tracks layer is completely separate and deleting the track doesn't "unrender" it from the tracks layer, which is just a set of tiles rendered from the tracks by a third party program on a separate server using the public APIs to fetch tracks as they are uploaded.

**Comment by SomeoneElseOSM** [comment]
I suspect that https://github.com/ericfischer/gpx-updater might be the place to mention this.

**Comment by simonpoole** [comment]
@SomeoneElseOSM if you look at the script it simply consumes the RSS feed of uploaded GPS tracks (didn't know we actually had that) and I don't think we publish deletions similarly.
