### ISSUE TITLE
Changeset metadata download to include number of changes

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#1947]
For statistical reasons, it might be interesting to also include the number of changes (field "num_changes" in changesets table) in the changeset(s) result. This way it would be possible to easily identify empty changesets, or avoid downloading large changesets only to find out how many changes are included. Also, editors like JOSM could display this additional column in the Changeset Manager.

If this is ok, I would create an accompanying issue for cgimap as well. 

<details>

```
diff --git a/app/models/changeset.rb b/app/models/changeset.rb
index 502637c2a..1aa1e1fd3 100644
--- a/app/models/changeset.rb
+++ b/app/models/changeset.rb
@@ -232,6 +232,7 @@ class Changeset < ActiveRecord::Base
     bbox.to_unscaled.add_bounds_to(el1, "_") if bbox.complete?
 
     el1["comments_count"] = comments.length.to_s
+    el1["changes_count"] = num_changes.to_s
 
     if include_discussion
       el2 = XML::Node.new("discussion")

```

</details>

**Comment by tomhughes** [comment]
You know github has a convenient way of attaching a patch to an issue, called a pull request...

**Comment by mmd-osm** [comment]
Sure, I can do that. The only issue at the moment is that my local unit tests don't work, and it will probably fail miserably on Travis. Let's see...

**Comment by mmd-osm** [comment]
Closing, as #1948 got merged. The respective cgimap patch is in https://github.com/zerebubuth/openstreetmap-cgimap/commit/2931c8d62b2a2c2f79d458f2ff4bbfe3b6645acf
