### ISSUE TITLE
Better quotation style

### ISSUE THREAD

**Issue by lxbarth** [openstreetmap/openstreetmap-website#195]
@samanpwbb - there's basically no quotations style right now in diary comments (not sure about elsewhere), I think we should do something very subtle.

![](http://cl.ly/image/3715082O2H3C/Screen%20Shot%202013-01-18%20at%2010.27.54%20AM.png)

**Comment by jgpacker** [comment]
It seems this issue is resolved nowadays.

**Comment by samanpwbb** [comment]
Ya, this was fixed ages ago:
![screen shot 2015-01-12 at 10 47 12 am](https://cloud.githubusercontent.com/assets/108094/5705585/69ee8a72-9a48-11e4-992c-d60bb8a192e0.png)
