### ISSUE TITLE
Put "apply viewbox" on homepage, turn on by default

### ISSUE THREAD

**Issue by ADepic** [openstreetmap/openstreetmap-website#1957]
Put "apply viewbox" from nominatim.openstreetmap.org on homepage and turn it on by default. This will be helpful for searching. **Optional and questionable**: Place map on the right country/state using IP address.

Another thing you can do, if results are not found in the area you are searching, is to search bigger areas incrementally. Currently if no results are found in the viewbox, nominatim searches the whole world. Instead, if you could search the district which encompasses the viewbox, then the state, and then country, and then continent and then world . You can do this by using admin_level. First search the viewbox, then search, lets say, admin_level=6, then admin_level=5 etc.

**Comment by tomhughes** [comment]
It is already turned on for all searches done form the main web site - see https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/geocoder_controller.rb#L88 for the code.

Incremental search is something you would need to raise against Nominatim itself at https://github.com/openstreetmap/nominatim/issues.
