### ISSUE TITLE
Connexion with yahoo

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/openstreetmap-website#1966]
I wanted to connect with a yahoo count. But when I click on the logo of Yahoo, I received a red line "Échec de la connexion au fournisseur d’authentification" (I will try to translate to "Impossible to connect to the authentification server")
Best regards

**Comment by tomhughes** [comment]
Do yahoo still support openid? It wouldn't surprise me if they have dropped it...

**Comment by tomhughes** [comment]
I'm struggling to find any vaguely recent references to Yahoo and traditional OpenID which is what that button uses.

They do seem to support OpenID Connect (which is really OAuth) but switching to that is a major undertaking for a relatively niche authentication provider :-(

**Comment by mmd-osm** [comment]
While we're at it, **aol.com** and **wordpress.com** seem to be unavailable for authentication as well.

**Comment by tomhughes** [comment]
According to https://en.support.wordpress.com/settings/openid/ it is no longer supported on new wordpress instances and I guess they may have removed the responder on wordpress.com that referred you to blog specific endpoint.

**Comment by tomhughes** [comment]
As a data point we currently have 195681 with openid authentication enabled of which 18774 are yahoo, 254 aol and 156 wordpress.

**Comment by tomhughes** [comment]
Oh and 172850 still have a google openid on them which is basically just people that haven't been upgraded to OAuth because they haven't logged in with google for several years.

**Comment by mmd-osm** [comment]
Yahoo was removed in https://github.com/openstreetmap/openstreetmap-website/commit/4a45092e27607f37843edbabbeda67919049e11b

Closing here.
