### ISSUE TITLE
Searching  street names in spanish (calle de xxx vs calle xxx)

### ISSUE THREAD

**Issue by dapgo** [openstreetmap/openstreetmap-website#1967]
Many times I had problems looking for streets because there is not an standard to name streets so depending of the place you can have a "Calle San Pedro" or "Calle de San Pedro"

For people both names means the same, so it is quite common that shops in a same street are writing in a different way. 

However, openstreetmaps search requires the part "de" to find the result.
As Google manage this type of mistakes better, most users will not realize about the problem but they will thing that the street is not in OSM.

In my opinion words like "de", "del", "la", "las", "lo", "los", "el" should be removed from the search or at least removed from a second search attempt.
It applies to every country using Spanish language and I suppose other latin languages are affected too.

**Comment by gravitystorm** [comment]
The search results are provided by [Nominatim](https://github.com/openstreetmap/Nominatim), and issues regarding the results should be reported on that repository.

It appears to me to be already reported at https://github.com/openstreetmap/Nominatim/issues/679
