### ISSUE TITLE
Translation in french

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/openstreetmap-website#1969]
Hi,
a few days ago, when I was using the traces https://www.openstreetmap.org/traces, everything was in french.
Now, the first line is in french (Modifier, Historique, Exporter, and so on), the lines under the grey part are in french (Nouvelles traces, Page 1, Anciennes traces and the list of the tracks)

But the part in grey is in english (lines 2 and 3). Example (because sometimes the text in this part is not always the same. But always in english) :
Public GPS traces
Browse recent GPS trace uploads    Upload a trace    See my traces

mmd-osm, on ID github, said to me it was maybe because of #1964 : so my issue, if useful, is just to tell you not  to forget the translations.

Best regards

**Comment by tomhughes** [comment]
As you can see in #1964 the necessary information has already been given for @Nikerabbit to do the translation renames and he did so in d792a3bab59cd2f171c49d8d63937db3cbc9b0bc so this will be fixed next time we deploy.

**Comment by Mahabarata** [comment]
OK, perfect !
So many to read in 1964 I was a little lost, sorry to have disturb you.
Best regards
