### ISSUE TITLE
reporting a comment should copy the details to the reporter

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/openstreetmap-website#1971]
It would be useful if after reporting inappropriate contributions a message would be sent to the reporter with a copy of the details s/he reported and maybe an identifier number. Maybe unless it is reporting for spam, or it could be a checkbox whether you wanted a copy or not.

**Comment by tomhughes** [comment]
In and of itself that doesn't achieve much - what might be useful is to allow subscription to reports so that people get updates on them.

**Comment by dieterdreist** [comment]
it could provide an email address where you could post follow ups. There’s just the report system and no email address, but after the user gets deleted there is no report function any more to get in contact.

**Comment by gravitystorm** [comment]
@dieterdreist can you explain more about your last point? If I report a user, and that user gets deleted, then isn't that the end of the matter? Why would I need to report them again? Just asking so that I understand the situation better.

**Comment by SomeoneElseOSM** [comment]
Currently there's no automatic feedback to the user that their request has even gone anywhere.  Where there's a conversation to be had I've been (with a DWG hat on) sending a PM to users saying what we're doing, and suggesting what the person who complained should be doing next, if anything (often "please explain in changeset discussion comments what the problem is").  I've been manually pasting these PMs to and fro into an OTRS ticket (see https://github.com/openstreetmap/openstreetmap-website/issues/1903 for more on that).

**Comment by tomhughes** [comment]
Yes that explains why letting reports see the conversation on the ticket may be useful, but not why you would want further contact after a user had been deleted.

Obviously is we were to make reports public, or at least make them visible to the reporters, that has implications from a data protection point of view.

**Comment by dieterdreist** [comment]
> 
> @dieterdreist can you explain more about your last point? If I report a user, and that user gets deleted, then isn't that the end of the matter?
> 


if the user gets deleted you would not have to bring more details on the table, but maybe there are still comments by this user that should be removed. As I understand, it was a bug leading to the specific case, when the user got deleted but his comment remained visible), which is fixed now.


someoneelse has a point that there should be a kind of feedback that your request has been received (and what you have stated), a trace
