### ISSUE TITLE
/welcome accessible to authenticated users only

### ISSUE THREAD

**Issue by Nakaner** [openstreetmap/openstreetmap-website#1977]
If I remember correctly, `/welcome` has been accessible to all users in the past (a few months ago). I just discovered that it is now accessible to authenticated users only. Is that intended (to make things easier to developers) or is it a side-effect of another change?

It's not a serious bug but I don't understand which sensitive information is available on that page.

Feel free to close this bug without fixing it.

**Comment by tomhughes** [comment]
You remember wrongly I think - login appears to have been required since 24422a3bafaf0f81f2417f30d896a859f6cb0ff2 which is part of the original PR introducing that page I think.

**Comment by tomhughes** [comment]
Specifically https://github.com/openstreetmap/openstreetmap-website/commit/24422a3bafaf0f81f2417f30d896a859f6cb0ff2#diff-786806b5990351fd9c17e697b242bf5fL7 introduced it.

**Comment by Nakaner** [comment]
Thank you for your response.
