### ISSUE TITLE
Max zoom is always 20 when gps traces are shown

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/openstreetmap-website#1978]
osm-carto on OSMF machines renders till zoom 19:
https://github.com/openstreetmap/openstreetmap-website/blob/e14476f52df3582bd565145638fe0edcd2bb1b0c/vendor/assets/leaflet/leaflet.osm.js#L15-L20

but i can zoom in into 20.
Transport and cycle layers have no max zoom defined, and i can reach non working 19+20.

HOT has max 20 and this is really the end of zoom.

**Comment by tomhughes** [comment]
Works fine for me - the maximum I can get to is:

* 19 for carto
* 18 for cycle and transport
* 20 for humanitarian

**Comment by HolgerJeromin** [comment]
This was vivaldi browser on win 7. Will recheck in the next days. Working on Android Opera...

**Comment by mmd-osm** [comment]
Unable to reproduce this on Vivaldi 1.15 on Ubuntu 18.04. How did you come to the conclusion that you can zoom into level 20? Can you post the full URL for that case?

**Comment by hikemaniac** [comment]
@HolgerJeromin Is it possible, that you had the GPS traces overlay active? Everything works fine for me, unless I have the overlay enabled. I can then also zoom in to zoomlevel 20.

**Comment by gravitystorm** [comment]
Good work @hikemaniac in figuring this out.

I would say there's a bug here - the map should only zoom into the maximum limit of the background layer, or the overlay, whichever comes first.
