### ISSUE TITLE
CSP directive blocks access to Overpass server

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#1993]
Chrome 69 refuses to access Overpass API due to:

https://github.com/openstreetmap/openstreetmap-website/blob/1285bcbd712044720c15e2de2e6bacaf4b0b0a92/app/controllers/application_controller.rb#L416

Error message: 
Refused to connect to 'https://lz4.overpass-api.de/api/interpreter' because it violates the following Content Security Policy directive: "connect-src 'self' piwik.openstreetmap.org nominatim.openstreetmap.org overpass-api.de router.project-osrm.org graphhopper.com".

-> Both `lz4.overpass-api.de` and `z.overpass-api.de` need to be added here as well. `overpass-api.de` is just an alias for those two production servers.

**Comment by tomhughes** [comment]
Well we work on the basis of hostnames so it shouldn't matter how many servers they resolve to, or are you saying that `overpass-api.de` is actually redirecting to those names?

**Comment by tomhughes** [comment]
It looks to me like they are just two DNS entries and there is no redirection going on. Certainly the query tool seems to be working for me in Firefox.

**Comment by tomhughes** [comment]
And in Chrom(ium) as well.

**Comment by mmd-osm** [comment]
Which Chrome version are you on? I'm getting this error since today on Version 69.0.3497.92 (Official Build) (64-bit)

**Comment by mmd-osm** [comment]
Ah, sorry for the noise, that's _Switcheroo_ extension triggering this Javascript error... Closing here.
