### ISSUE TITLE
Suggestion: Sort friends and nearby users based on last edit time

### ISSUE THREAD

**Issue by iriman** [openstreetmap/openstreetmap-website#1994]
I use the list of friends and nearby users to monitor new changes in my area. These lists may become long after a while and this makes it hard to find the newest changes by a look. A sort option could bring the newest ones up and put the others bellow them out of our sight.

**Comment by iriman** [comment]
yes, it would. thanks

**Comment by lectrician1** [comment]
I would still be for implementing this. 

Sometimes it's just nice to see what friends are active and what they're working on (without having to go to OSMcha).

The nearby-users list seems to have the intent of helping a user find new friends in their area, yet it doesn't make sense to list them in their current order when many of the users by me haven't contributed in 5+ years. It wouldn't make sense to be friends with someone who isn't even active.
