### ISSUE TITLE
Sharing SVG image from standard layer gives a bitmap

### ISSUE THREAD

**Issue by turepalsson** [openstreetmap/openstreetmap-website#1998]
When using the "share" feature to get an SVG image from the standard layer, the resulting SVG file is just a thin wrapper around a raster image. I seem to remember that one used to get a "proper" vector image (and I am not alone: https://help.openstreetmap.org/questions/65497/is-thereany-change-in-svg-exports).

**Comment by tomhughes** [comment]
It certainly should be, but it's mostly up to mapnik... we just ask it for an svg...

**Comment by tomhughes** [comment]
This seems to be explained in https://github.com/mapnik/mapnik/issues/3749 and is apparently a result of some of the operations used in the style sheet :-(

Not sure there's much we can do, and it's not technically an issue with the web site but rather with the style sheet and/or the export script on the render servers.
