### ISSUE TITLE
Lack of international borders endangers users' lives

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2002]
Don't you think the lack of international borders might endanger users' lives?
It is not just a problem with one layer either,
https://www.openstreetmap.org/#map=13/42.3139/130.6470&layers=T
https://www.openstreetmap.org/#map=13/42.3139/130.6470&layers=C

**Comment by jidanni** [comment]
I'm saying the website has some responsibility for the layers it is hosting.
At least they will have to show up in court if they get sued over someone's death.

**Comment by jidanni** [comment]
https://www.worldatlas.com/articles/the-most-dangerous-borders-in-the-world.html

**Comment by tomhughes** [comment]
It's not actually @gravitystorm running it these days but as @woodpeck says this is a matter that should be raised against the style sheet at https://github.com/gravitystorm/openstreetmap-carto/issues and isn't something we can reasonably change here.

**Comment by tomhughes** [comment]
Oh actually those are the Thunderforest layers, so that is a matter for @gravitystorm. If you really feel there is a reason they're not appropriate for the main page then you should petition OWG to have them removed as that is where the decision on what layers to show on the front page lies per the guidelines at https://wiki.openstreetmap.org/wiki/Featured_tile_layers/Guidelines_for_new_tile_layers.

That is mostly about how layers are added but logically I think the process follows in reverse for removal.

**Comment by HolgerJeromin** [comment]
> At least they will have to show up in court if they get sued over someone's death.

Do you **really** think someone will be shot because he ran into a border fence (only) because he was looking only on a (secondary!) map layer on osm.org?

Yes, there are people driving into a harbour listening only to a navigation device, but this is a different thing.

**Comment by jidanni** [comment]
- https://en.wikipedia.org/wiki/Deaths_along_the_Bangladesh%E2%80%93India_border
- ['''Small''' demarcated portions of the border are fenced on both sides.](https://en.wikipedia.org/wiki/Bangladesh%E2%80%93India_border)
- The current or previous browser user might have been a cycle
enthusiast or perhaps taking a bus (transport layer) thus leaving the
fatal browser cookie around even months ago.

Plus it would be [better to know](https://www.theguardian.com/us-news/2018/may/02/fatal-encounters-97-deaths-point-to-pattern-of-border-agent-violence-across-america) if one were even [anywhere near](https://en.wikipedia.org/wiki/Migrant_deaths_along_the_Mexico%E2%80%93United_States_border#Vigilante_killings) a border. 

OK I added https://wiki.openstreetmap.org/wiki/Talk:Featured_tile_layers/Guidelines_for_new_tile_layers#International_borders_are_a_must.2C_to_prevent_accidental_deaths and will petition OWG to require international borders.
