### ISSUE TITLE
Tamil letters are broken in iD

### ISSUE THREAD

**Issue by mohamedmahir** [openstreetmap/openstreetmap-website#2004]
Hi
Found Tamil characters are broken in OSM. Have a look at this.
https://www.openstreetmap.org/edit?node=1988392636#map=16/10.3314/79.3727

East Coast Road = கிழக்கு கடற்கரைச் சாலை

Please help to fix.

Thanks

**Comment by mmd-osm** [comment]
What exactly do you mean by "broken"? [Way 154241578](https://www.openstreetmap.org/way/154241578) already includes the Tamil name as name:ta = கிழக்கு கடற்கரைச் சாலை, like you have written.

Also, this is the wrong repository to report issues with iD, you need to head over to https://github.com/openstreetmap/iD
