### ISSUE TITLE
Unable to open changeset in new browser tab when there's no comment

### ISSUE THREAD

**Issue by DaveF63** [openstreetmap/openstreetmap-website#2005]
Hi

I'm unsure if this is a website or iD editor problem
https://www.openstreetmap.org/user/jdselby/history#map=2/-12.8/-33.1
As you can see there the comments section is blank, which makes it impossible to open the changeset in a new browser tab. When editing in P2, a (no comment) comment is added. Is this added by the website or P2?

**Comment by tomhughes** [comment]
It's added by us, but in there case there is a comment. The "." is the comment - that is literally the text the user supplied. So we don't add anything because there actually is something already.

The solution here is really to persuade this user to be a but more social!

**Comment by tomhughes** [comment]
You can actually just about middle click on the "." at least in firefox. Unfortunately emulating middle click for the rest of the element would be at best hard or quite likely impossible so I'm not sure there's much we can do here.

**Comment by DaveF63** [comment]
I require glasses & a more accurate mouse.
Thanks.
