### ISSUE TITLE
Minimum size for changeset box

### ISSUE THREAD

**Issue by boothym** [openstreetmap/openstreetmap-website#2008]
If a changeset is only an edit of a single node, then it's basically impossible to select this changeset from the map. There should be a minimum 10-20px padding on the changeset box around the node so that it can be clicked on.

It's a problem especially when viewing a user's edits list and you see this small orange dot - but you can't click on it. (I did manage eventually when using the zoom function at 200%)

Would also be useful to fix in conjunction with #1515 to make changesets more obvious.

**Comment by jguthrie100** [comment]
Is there any chance you could link to some example changesets?

**Comment by boothym** [comment]
I was looking at a user's history and zoomed in to this one where the number 31 address node is: https://www.openstreetmap.org/user/Azureoak/history#map=19/56.22609/-3.42020 (https://www.openstreetmap.org/changeset/55571675 if you can't access it.) 

For #1515 anywhere there is lots of changesets on top of each other, especially if they are similarly sized - e.g. https://www.openstreetmap.org/user/Azureoak/history#map=14/56.2753/-3.7404 - then a different colour is need than orange for the highlighted changeset.
