### ISSUE TITLE
[API] PROTOCOL ERROR for HEAD request on changeset with non-existent user

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [openstreetmap/openstreetmap-website#2017]
URL: `https://api.openstreetmap.org/api/0.6/changesets?display_name=username`

Performing `GET` request on the above url for non-existent user returns `Object Not Found` while for existent user returns the changeset XML.

Performing `HEAD` request on the existent users returns 200 while on non-existent user PROTOCOL ERROR is raised.

> curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)

**Comment by tomhughes** [comment]
Can you point at the documentation that says that HEAD is a supported method for that API endpoint?

**Comment by tomhughes** [comment]
Seems to work over HTTP/1.1 and return 505 so this looks an issue in apache or possibly passenger and not something that is in our control.

**Comment by tomhughes** [comment]
Seems to show as a normal "successful" completion as 404 Not Found in the rails log when performed over HTTP/2 and there's nothing in the apache error log so my best guess is that it might be a passenger bug.

**Comment by tomhughes** [comment]
Any issue here looks to be operational rather than a code issue and is likely outside out control anway.
