### ISSUE TITLE
Deleting a relation (and just that) creates a changeset without a bounding box

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/openstreetmap-website#2020]
Example: https://master.apis.dev.openstreetmap.org/changeset/134392 https://master.apis.dev.openstreetmap.org/api/0.6/changeset/134392/download

While there are conceivably relations for which it is not possible to determine a geometry (for example empty ones), most do have an easily determinable one, and on creation this doesn't seem to pose an issue, see for example https://master.apis.dev.openstreetmap.org/changeset/134395

This behaviour would seem to be inconsistent with the behaviour shown for the deletion of other elements, and makes it impossible to retrieve such changesets with a bounding box based API call (it likely causes other issues in QA tools and similar applications that consume changesets, but I haven't investigated further).

**Comment by tomhughes** [comment]
This is most likely deliberate because determining a bounding box for a relation can be very expensive - as I recall relations are never considered in determining a changeset bounding box.

**Comment by tomhughes** [comment]
Actually it does consider top level ways and nodes but doesn't recurse into relations. The code is https://github.com/openstreetmap/openstreetmap-website/blob/master/app/models/relation.rb#L373. Still trying to understand exactly what members it considers in the case of a deletion.

**Comment by simonpoole** [comment]
If I understand the code correctly the problem is simply with the logic  that if tags are changed we use the current members of the relation to determien the bounding box, but in this case that list is actually empty and we should be using the list of changed members, see https://github.com/openstreetmap/openstreetmap-website/blame/master/app/models/relation.rb#L387

**Comment by simonpoole** [comment]
@mmd-osm I was just going to do that.

@zerebubuth any opinion?

**Comment by simonpoole** [comment]
@mmd-osm looks good https://upload.apis.dev.openstreetmap.org/user/SimonDev/history#map=19/47.39142/8.37422 

Being lazy and not looking at the code: do you recurse in to child relations when determining bounding boxes or does the cgi-map code skip that too? Not related to this specific bug, but I think it is worth discussing if we want to go at least one level deep to at least to have a boundingbox for nearly all reasonable use cases. I just don't like it that it is currently possible to "stealthy" delete borders and similar if they only have relations as members.

**Comment by mmd-osm** [comment]
I believe this is editor specific. iD as an example provides all previous relation members even for the delete call (although it wouldn't be necessary at all). This tricks the logic in Rails to believe there's no change... 


```
<osmChange version="0.6" generator="iD"><create/><modify/><delete if-unused="true"><relation id="80000000303" version="1"><member type="way" role="from" ref="4000212050"/><member type="way" role="to" ref="4000212051"/><member type="node" role="via" ref="5003081799"/><tag k="restriction" v="no_right_turn"/><tag k="type" v="restriction"/></relation></delete></osmChange>
```

@simonpoole : thanks a lot for testing! If people find recursing down relations one level helpful, I think this could also be added.

**Comment by simonpoole** [comment]
@mmd-osm iD requires you to delete all members from a relation before deleting the relation which causes the behaviour you are seeing.

**Comment by zerebubuth** [comment]
I think the intention was probably that the deleted relation would have no members, so all the (non-relation) previous version members would be used to create the bounding box. The logic is pretty convoluted in an attempt to not overexpand the bounding box for local membership changes, so that could be hiding any number of bugs, including this one.

**Comment by mmd-osm** [comment]
tags_changed is true here (tags are about to be removed), while self.members is already empty (a to be deleted relation doesn’t have any members). Which means that update_members will be empty in this case.

Probably a lot of the delta analysis logic could be skipped in case of deletions by just considering the old members for bbox calculation.

**Comment by simonpoole** [comment]
@mmd-osm btw patching the problem isn't the problem did that locally days back, wrapping my head around how the (new) test system works and writing a test is :-)
