### ISSUE TITLE
How to edit boundaries to include their associating labels (as a relation)?

### ISSUE THREAD

**Issue by neverwiredhouse** [openstreetmap/openstreetmap-website#2021]
For instance Australia and the UK are both missing their connecting labels... I was going to fix this but I for the life of me can't figure it out. I found about 200 of these cases total, and programmatically I fix them, but I would like the map itself to be accurate for other people and am willing to do the work.

Can you give me step my step instructions?

**Comment by tomhughes** [comment]
Please use https://help.openstreetmap.org/ for questions about using OpenStreetMap - this tracker is for reporting bugs in the web site not for general support,
