### ISSUE TITLE
Performance: Optimizing database for map structure query, perhaps using PostGIS?

### ISSUE THREAD

**Issue by sunapi386** [openstreetmap/openstreetmap-website#2048]
Are there any plans to use the support of PostGIS in PostgreSQL? So that we may optimize querying times for answering questions like 
● How many features lie within 100m?
● What is the total length of a given road?
● What is the total area of water in my city?
https://wiki.postgresql.org/images/c/c5/PostGISPGUK.pdf

It may be a major effort but would pay off at larger scales. We're storing map data in our own custom format, as defined in https://github.com/openstreetmap/openstreetmap-website/blob/master/db/structure.sql.

**Comment by tomhughes** [comment]
There are plenty of third party APIs like overpass for doing this sort of thing. The main database is optimised for editing not querying and postgis is not necessary for that - if it were required we would of course be happy to use it as we do in other database like our rendering and geocoding databases.
