### ISSUE TITLE
Font errors on load in Chrome

### ISSUE THREAD

**Issue by talllguy** [openstreetmap/openstreetmap-website#2055]
Chrome 70 is through a lot of `data:font/woff` errors when trying to load the main webpage, as well as on the iD embedded site.

![image](https://user-images.githubusercontent.com/1827881/48362359-7a28fe80-e671-11e8-9c8b-29bcab7fed30.png)

**Comment by tomhughes** [comment]
As far as I know we don't load any fonts from data URLs (to be honest I can't imagine who would - isn't a font far too large to embed like that?) so I suspect this is something an extension is injecting in which case this is expected behaviour.

**Comment by tomhughes** [comment]
No sign of any such errors in firefox 63 or chromium 69 or of such a URL anywhere in our source so I'm pretty such this is our security policy correctly detecting an attempt by something to tamper with the site, most likely an extension you have installed.
