### ISSUE TITLE
422 error when posting changeset comments

### ISSUE THREAD

**Issue by willemarcel** [openstreetmap/openstreetmap-website#2057]
Hi! I'm getting 422 error when trying to post comments to changesets with the endpoint: `/api/0.6/changeset/#id/comment`

I confirmed that the changesets are closed. The code that post comments had worked for months, but now it's failing. Could you check if there is some problem in the API or tell me if some API rule changed?

One of the changesets that I tried to post comments is: 64337024.

Thank you very much!

**Comment by willemarcel** [comment]
Thanks, @gravitystorm ! I think you linked the wrong PR, the correct seems to be this: https://github.com/openstreetmap/openstreetmap-website/pull/2050

**Comment by tomhughes** [comment]
@gravitystorm I was trying to work out whether removing that was valid before I merged it but came to the conclusion that it was because those methods are not API are are only used via the web site.

**Comment by tomhughes** [comment]
Ah no some of them are API so that is definitely needed then.
