### ISSUE TITLE
Problem with deny_access and request formats during tests

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2064]
I'm attempting to refactor changeset_comments_controller to use CanCanCan, and there's a problem with how our tests run, and how they interact with with our `deny_access` handler, and API request format handling in general.

Until now, you can call `post "api/0.6/changeset/comment/:id/hide"` with any request format you like, either html or xml or plain text or whatever, and since there's no payload it doesn't really matter very much. The action ignores the request format and always responds with XML (`render :xml => comment.changeset.to_xml.to_s`).

We take advantage of this in our tests, which are mostly of the format `post :destroy, :params => { :id => comment.id }` which is sending a text/html request behind the scenes. You can see the difference between "accept anything, always respond in XML" and "only accept XML requests" if you change the controller action to e.g.

```ruby
    # Return a copy of the updated changeset
    respond_to do |format|
      format.xml { render :xml => comment.changeset.to_xml.to_s }
    end
```
This would now throw an error on any request that's not XML, including the requests from the test suite.

The immediate problem is that our `deny_access` handler now uses the request format to decide whether to redirect requests to the login page (for html requests, assumed to be website requests) or not (for any other type of request). So when porting these API methods to CanCanCan, instead of receiving a 403 response (when you're logged in but don't have permissions, e.g. not a moderator) you get redirected to an html error page instead. This is because the test suite makes all its requests as text/html by default. Previously that hasn't mattered, but now it does.

Possible solutions include:

* Just change the test suite and accept the redirects. For example,
   ```diff
       # not a moderator
       post :restore, :params => { :id => comment.id }
  -   assert_response :forbidden
  +   assert_response :redirect
  +   assert_redirected_to :controller => :errors, :action => :forbidden
  ```
  But I think this is very misleading, since that's not how we're designing the XML API. I don't think it's a good idea to add in the redirect for real API responses either, since not all libraries follow redirects.

* Just change the test suite. For example, 
  ```diff
       # not a moderator
  -    post :restore, :params => { :id => comment.id }
  +    post :restore, :params => { :id => comment.id, :format => "xml" }
       assert_response :forbidden
  ```
  This could be tedious and repetitive though. A variation would involve e.g. `api_post` as a wrapper around `post` to set the format, perhaps. Although it makes the tests pass, any real-world API user sending text/html (are there any? Who knows?) would still be affected and get a redirect.

* Set a default format in a `before_action` handler in the controller
   ```diff
     class ChangesetCommentsController < ApplicationController
      skip_before_action :verify_authenticity_token, :except => [:index]
  +  before_action :set_default_request_format, :only => [:create, :destroy, :restore]
      before_action :authorize_web, :only => [:index]
     ...
  +  def set_default_request_format
  +     request.format = "xml"
  +  end
  ```
  This needs to be done in a `before_action`, because `deny_access` can get called before any code in the action has been run. However, unless you know the intricacies of what we're doing, it could appear meaningless to other developers. 

* Doing something even more clever with `deny_access` to figure out the appropriate redirect/status response choice. I haven't figured anything out that would avoid having to mark particular actions as "this action is part of the API and is going to respond in XML, so don't redirect to the login page, even if the request happens to be in html format".

* Do something more fundamental, like refactoring api methods into their own namespace, and giving them a different `deny_access` handler. Perhaps the cleanest solution?

(I'm not going to suggest addressing the underlying topic of accepting any request format, by using `respond_to` in actions, since that has the potential to break existing API clients who might be sending requests in any old format. But I'll call this a candidate solution for a future API change.)

**Comment by tomhughes** [comment]
My immediate inclination is that the tests should be fixed - if a test is testing the API then it should request the kind of format a real API client would. That said, given these are controller tests, it's all a bit fake anyway.

Setting a default format is not a bad idea - the default format for our API is really XML and that is what we would likely want to send to a client that didn't request anything else anyway.

I think there's a better way than using `before_action` though, by attaching the default to the routes - we already do that for the notes routes and a few others.

Better separation of API and web site methods would of course also be good but I think that's a larger, and really separate, problem.

**Comment by tomhughes** [comment]
Specifically it looks like adding `:defaults => { :format => "xml" }` to the api scope in the routes will set the default. Should probably add it to the special `/api/capabilities` route as well.

**Comment by gravitystorm** [comment]
Setting the default format in the routes isn't enough on its own to fix this problem with the tests, since the controller tests are testing the controller methods directly, not going via the routing engine.

**Comment by tomhughes** [comment]
Ah right. I suspect we should still make that change though, to avoid sending HTML responses to API clients.

As far as the tests go I'm inclined to revert to saying the tests should be fixed one way or another, as if they are testing a controller method it is their responsibility to invoke it in the same way that rails for an actual client?

**Comment by gravitystorm** [comment]
Given all the complications around format handling and routing, I've tried out the "different deny_access handlers" approach in #2073 - albeit without additionally refactoring all the controllers!
