### ISSUE TITLE
edit date is not right 

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/openstreetmap-website#2081]
Looking at an object that was modified 2 days (minus 6 hours) ago, i.e. 3 Dec. 9 PM, the "convenient" text shows "1 Day ago". It should round correctly, or at least acknowledge that people think days as the opposite of night, i.e. if you slept 2 nights in between, it is 2 days ago, not 1.

Maybe it would be better to just show date and time as it was done until some years ago. It could show "beautified" versions on mouse hover.

![screen shot 2018-12-05 at 14 55 43](https://user-images.githubusercontent.com/581288/49518268-84b86b80-f89e-11e8-8261-12433f4c2610.png)
![screen shot 2018-12-05 at 14 56 14](https://user-images.githubusercontent.com/581288/49518269-84b86b80-f89e-11e8-8a8b-4d1b0e8d3edd.png)

**Comment by tomhughes** [comment]
Showing the beautified version on hover would be ridiculous - the idea is to show the beautified version and provide additional detail via the hover. Reversing that makes no sense - once the full date is show there it no point in making the other version available.

The actual algorithm for the test comes from rails (https://api.rubyonrails.org/classes/ActionView/Helpers/DateHelper.html#method-i-distance_of_time_in_words) and we don't have any control over it but rounding anything over 24 hours to a number of days doesn't seem unreasonable to me anyway.

I think we'll have to agree to disagree on this one - clearly there's no objectively correct answer and this is a matter of subjective preferences where we're never going to please everybody.

**Comment by dieterdreist** [comment]
Thank you for the pointer. It generally seems ok, but there is one rule that should be tweaked:
`23 hrs, 59 mins, 30 secs <-> 41 hrs, 59 mins, 29 secs                     # => 1 day`
I'll try to convince them.
