### ISSUE TITLE
Add total page number to notes

### ISSUE THREAD

**Issue by boothym** [openstreetmap/openstreetmap-website#2089]
On a user's notes page it has **« Previous | Page 1 | Next »** - this should be changed so that it is Page 1 of X (where x is the total number of pages).

**Comment by tomhughes** [comment]
Sorry, but this isn't going to happen - in fact we probably need to get rid of the page number completely as computing the page numbers is very inefficient as it requires finding and counting the total number of matching records.

As a general rule we don't accept anything which adds page counts to next/previous controls and we are looking in due course to get rid of those which already exist.
