### ISSUE TITLE
Geolocation marker color now black

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/openstreetmap-website#2093]
I am not sure, but i am pretty sure that the central circle of the marker was not black.

![rps20181231_071829_168](https://user-images.githubusercontent.com/2410353/50555412-62aedf00-0ccc-11e9-8509-6efb82b3baf2.jpg)

**Comment by tomhughes** [comment]
Well as far as I know nothing has changed recently...

**Comment by tomhughes** [comment]
As far as I can see that dot has no styling at all so it is just inheriting the default body colour - maybe there has been a recent change in browsers to make them inherit colours from HTML into an SVG element?

**Comment by tomhughes** [comment]
Ah no this is an upstream change in `Leaflet.locate` which was merged in to our code a couple of months ago (https://github.com/openstreetmap/openstreetmap-website/commit/fde98f7ead8b85a6a2b3ed748ca6f5a199a8e09f#diff-553fba9048416e7d29b3a167a39d676fL104).

**Comment by tomhughes** [comment]
Actually I think the bigger problem is the CSP blocking inline styling...
