### ISSUE TITLE
Map tiles are not updating?

### ISSUE THREAD

**Issue by jc86035** [openstreetmap/openstreetmap-website#2095]
I'm not really sure what software this is a bug in, so I've put it here because it's definitely on the OSM website. I made [changeset 65785749](https://www.openstreetmap.org/changeset/65785749) a week ago, and for some reason the map hasn't updated yet (except for zoom level 19). I'm guessing it might be because I deleted both a relation and the only member at the same time, but I'm not sure. This has never happened before for me, and the map tiles actually updated before reverting back to the original tiles (I think).
<img width="270" alt="default" src="https://user-images.githubusercontent.com/3948362/50574142-3bb3f280-0e1d-11e9-8b9b-425994dca699.png">
Normally if I hard refresh the map tiles update in minutes, but it's been almost a week and nothing has changed here. The image shows the data overlay – the object has clearly been deleted, but for some reason the tile server has no idea. It's not a cache issue on my end; it happens in Tor Browser as well.

**Comment by tomhughes** [comment]
For performance reasons we use a simplified algorithm for tile dirtying which (as you have guessed) means that updates which only change a relation do not cause tiles to be rerendered.

This is deliberate, to stop changes to large boundary relations having to dirty, and then rerender, very large numbers of tiles.

As you've also guessed it's really anything to do with this repository - the actual code is https://github.com/openstreetmap/chef/blob/master/cookbooks/tile/files/default/bin/expire-tiles-single#L18.

**Comment by jc86035** [comment]
@tomhughes: I've tried editing the area to update the tiles, but now it's thrown up something else.
<img width="766" alt="2" src="https://user-images.githubusercontent.com/3948362/50574709-d9f98580-0e28-11e9-8317-3d2e7f82ef53.png">
The map has rendered with the new wetland area over the old coastline. The wetland area is supposed to be behind the coastline (i.e. rendered on land), but for some reason Mapnik is doing... whatever this is.

**Comment by tomhughes** [comment]
Please don't make fake edits to force a rerender - it will rerender on the next style change so just be patient.
