### ISSUE TITLE
Short links to controlled names at OSM website

### ISSUE THREAD

**Issue by ppKrauss** [openstreetmap/openstreetmap-website#2099]
"[URN resolver](https://tools.ietf.org/html/rfc2169)" is an old technical name that can be reused here with some adaptations...  The main goal is to avoid confusion with "free text searches". URNs are controlled names, like the [ISO&nbsp;3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) codes for country names (AR=Argentina, BR=Brazil, FR=France, etc.) and its subdivisions  (e.g. BR-AM, BR-SP, BR-PA are subdivisions defined by [ISO&nbsp;3166-2:BR](https://en.wikipedia.org/wiki/ISO_3166-2:BR)).

There are many ways to define a syntax for namespaces or controlled names, suppose the `urn:lex` schema for jurisdiction names... Examples: 

* [`osm.org/urn:lex:FR`](https://www.openstreetmap.org/relation/7408) would be a short and reliable link to the **France** map.

* [`osm.org/urn:lex:FR-37`](https://www.openstreetmap.org/relation/7408), as defined by [ISO 3166-2:FR](https://en.wikipedia.org/wiki/ISO_3166-2:FR), would be a short and reliable link to the **France/Indre-et-Loire** map.

* [`osm.org/urn:lex:BR-SP-SaoPaulo`](https://www.openstreetmap.org/relation/298285),  to the **Brasil/São Paulo/São Paulo** map.

* [`osm.org/urn:lex:BR-PA-Altamira`](https://www.openstreetmap.org/relation/185554),  to the **Brasil/Pará/Altamira** map.

* [`osm.org/urn:lex:BR-PA`](https://www.openstreetmap.org/relation/185579), to the **Brasil/Pará** map.

* ... each link, with its judistiction code, would be a short and reliable link to each full name.

**Short, reliable and persistent** way to link OSM administrative  boundaris.

------

With this **same infrastructure** of redirecting controled names, we can add location identifiers, as the OLC code discussed at #1807  or another relevant one, like Geohash. Examples:

* `http://osm.org/geo:{geoUriValue}`  a resolver for the [RFC 5870's](https://tools.ietf.org/html/rfc5870) strings, the  `geo` URI protocol.

* `http://osm.org/olc/{olcCode}`  for original OpenLocationCode 8+N digits geocodes, without context.

* `http://osm.org/ghs/{geohashCode}`  for original [Geohash](https://en.wikipedia.org/wiki/Geohash), without context. PostGIS, at OSM server, offers [ST_PointFromGeoHash()](https://postgis.net/docs/ST_PointFromGeoHash.html).

* ...

* `http://osm.org/pluscode/{context}/{olcShortCode}`  for PlusCode-like  short-OpenLocationCode, with 6+N digits geocodes. The **context** can be resolved by the URN schema described above (e.g. context "FR-37" for France/Indre-et-Loire, context "BR-PA-Altamira" for Brasil/Pará/Altamira).

**Comment by tomhughes** [comment]
We already have a system of short links, and I don't see how something that requires users to manually construct an obscure URL helps anything.
