### ISSUE TITLE
Nested lists are incorrectly displayed in user messaging interface

### ISSUE THREAD

**Issue by nachanon** [openstreetmap/openstreetmap-website#2103]
I ran into this problem when I was writing a rather long reply to another mapper's message. I have drafted my message with [original Markdown][1]; but when I previewed the message before sending, I found several problems with [OpenStreetMap.org](https://www.openstreetmap.org/)'s Markdown implementation around its interpretation of nested numbered/bullet list.

This resulted in me having fumble for several minutes to find _partial_ workaround (see below), before I could actually send the message in a relatively unmangled form.

Exact steps to reproduce:

- Start a browser with a new private browsing session (or with cookies cleared) and JavaScript enabled.
- Visit your own OSM user page as anonymous user.
- Click _Send Message_.
- You will be prompted to log in: enter your OSM user and password.
- <q>Send a new message</q> page will appear.
- Enter `These are nested lists...` in the _Subject_ field.
- **Copy** text from [this Gist](https://gist.githubusercontent.com/nachanon/320b8a0473ac0658a8f2fe8ddd9da6c7/raw/8c94d376792af491c71795a2f225e5212ed046eb/nestedlist.md) **and paste** it into the _Body_ field. (Warning: Tab indentation on blank lines are totally intended)
- Click the _Preview_ button.

The preview would show something like this:
![](http://u.cubeupload.com/xwindows/ZMoga4.png)

Then, compare it to an output from [the original Markdown][1]:
![](http://u.cubeupload.com/xwindows/0qf3OL.png)

You would see that on OSM messaging interface...

- _Bullet_ lists that are nested inside numbered list **are mistakenly displayed as _numbered_ lists**. **(No workaround)**
- Sub lists with _equally-indented_ blank lines before and after them **are mistakenly displayed as code snippet _and_ excluded from the list**. (Workaround: remove these lines before sending the message)

Please investigate and fix.

Browser: Opera 11.64 (Win32)  
System: Microsoft Windows XP Professional SP3

### Notes ###

- This is not specific to preview: the same message sent to myself also exhibit the same problem when viewed in the on-site inbox.
- This is not specific to browser: result obtained from Pale Moon 25.8.1 (GNU/Linux 32-bit) is the same.  
- The word _Markdown_ on the messaging page's help panel actually links to [the original Markdown][1]. So, compatibility is expected.

[1]: https://daringfireball.net/projects/markdown/

**Comment by tomhughes** [comment]
We use https://rubygems.org/gems/redcarpet for our markdown formatting so any issues with it are largely outside our control.

**Comment by tomhughes** [comment]
The actual implementation in our code is https://github.com/openstreetmap/openstreetmap-website/blob/master/lib/rich_text.rb#L83 which as you can see pretty much just calls Redcarpet to render it.

Also everybody knows that there is no "one" markdown - what we link to is just a convenience for some hints because there is no definitive spec.

If you have a suggestion for something better to link to then please do let us know.

**Comment by gravitystorm** [comment]
> We use https://rubygems.org/gems/redcarpet for our markdown formatting so any issues with it are largely outside our control.

Unfortunately redcarpet appears to be largely unmaintained, and it contains multiple unfixed bugs regarding parsing markdown lists (e.g. https://github.com/vmg/redcarpet/issues/655 and https://github.com/vmg/redcarpet/issues/623).

> Also everybody knows that there is no "one" markdown - what we link to is just a convenience for some hints because there is no definitive spec.

Indeed, but there's a difference between different interpretations of markdown, and bugs in the parsing library. For example, the gist posted by @nachanon renders fine with the original markdown, and also the commonmark parser at https://spec.commonmark.org/dingus/ - so I think that our broken parsing is something that we should try to fix.

Jekyll (and therefore github pages) no longer use redcarpet but instead use [kramdown](https://github.com/gettalong/kramdown) as their default markdown parser. Perhaps we could do the same?
