### ISSUE TITLE
Add geo tag to OSM website search options

### ISSUE THREAD

**Issue by ppKrauss** [openstreetmap/openstreetmap-website#2104]
The [geo URI](https://en.wikipedia.org/wiki/Geo_URI_scheme) standard is free, is neutral  and is a consensus... By other hand  the only consensual feature at issue #1807 is to point a "location context" for the search... All users will be happy with the approximated lat-long coordinates. Summary: 

Search string box today | With `geo:`|Effect with `geo:`
-------------------|-----------------------|----
Pronto Socorro Maria | Pronto Socorro Maria geo:-23.55,-46.63| The result will be near São Paulo center, even when user is not browsing at Brasil 
Pronto Socorro Maria | Pronto geo:-23.55,-46.63 Socorro Maria|  (identical)
Champs-Élysées | Champs-Élysées geo:48,2 | Ensures the Paris reference

**Illustrative Scenario**: suppose an user of the Openstreetmap's website   entering a string "Pronto Socorro Maria". It is  a `http://OSM.ORG/search?query=Pronto+Socorro+Maria`  query.  The result is something-aleatory, any hospital can be showed.  Now suppse the same user have some positional reference to say "nearst this point", how to say to the search engine?  

The syntax to say is using the tag `geo:` with coordinates. If the user need to check the neighborhoods of `geo:-23.55,-46.63`  (that is a standard RFC 5870 string) can concatenate this string into the query,   `http://OSM.ORG/search?query=Pronto+Socorro+Maria+geo:-23.55,-46.63`. Simple, only it.

The [javascript regular expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) for `geo:` tag is 

```
/(^|\s)geo:(\-?\d+(?:\.\d*)?,\-?\d+(?:\.\d*)?)(\s|$)/
```

## Step2. option to geocodes as OLC

After implemented the `geo:`  tag and OSM community accepted the new feature.... We can suggest a little adaptation, the `geo:{geocodeSchema}:`. The main motivation is to entering pluscodes, that   is, the [OLC geocode-schema](https://github.com/google/open-location-code/wiki/Supporting-OLC-in-your-app), but not only it: there are an "open door" to implement in the future other geocode-schemas, without any privilege for Google's preferred scheme.

Will be a new consensus process, the "step2 consensus", if sucess the `geo:olc:{olcCode}`  will be implemented ([the implemetation is near ready](https://github.com/openstreetmap/openstreetmap-website/pull/1818)!) .  The javascript regular expression for OLC (named "global codes") is 

```
/(^|\s)geo:olc:([23456789C][23456789CFGHJMPQRV][23456789CFGHJMPQRVWX]{6}\+[23456789CFGHJMPQRVWX]{2,3})(\s|$)/
```

## Step3. Option for loose-OLC

A testing feature can be solicitated,  to interpretate and expand a loose OLC.  For example  “588MC9X8+RC” in the search box text will be expanded to “geo:olc:588MC9X8+RC” in the real search. At implementation in  the search engine, it  can be a [pre-parsing](https://en.wikipedia.org/wiki/Preprocessor) to simplify the work.

Will be a new consensus process, the "step3 consensus",  and only a "testing mode" feature to be implemented... Suggesting "step4 consensus" to be definitive implementation.

**Comment by tomhughes** [comment]
URIs are not something that you search for though, they are something a browser resolves!

**Comment by ppKrauss** [comment]
> URIs are not something that you search for though, they are something a browser resolves!

The  " `geo:`  protocol" (the real name because it is the prefix)  is not a [*De facto* standard](https://en.wikipedia.org/wiki/De_facto_standard) for browsers (not exist in Firefox or Chrome because is not popular for this function), but **it is a *De facto* standard for geotagging and metadata**. Is what we need in the search string, a simple tag to avoid syntax confusion and ideologic dilemas.

So, `geo:{something}` can be viwed in this proposal as  "only a mark" for detection in the search engine.... You was very fast to close (30 minutes!)...<br/>  **Please reopen** for OSM communitie's appreciation (at least for a few days).

**Comment by tomhughes** [comment]
It's commonly used on mobile browsers I believe, just not on desktop. I believe we already support it there, or if not there is already a ticket asking us to do so.

**Comment by tomhughes** [comment]
Also I really don't appreciate you trying to sneak OLC in via the back door when it's already being discussed elsewhere.

**Comment by lonvia** [comment]
Also, searching for [pronto socorro -23.10,-48.92](https://www.openstreetmap.org/search?query=pronto socorro -23.10%2C-48.92) already works. No need for some strange prefix nobody can remember. The search radius may be a bit small but that would be something to discuss on the Nominatim issue tracker, not here.

**Comment by ppKrauss** [comment]
> Also, searching for [pronto socorro -23.10,-48.92](https://www.openstreetmap.org/search?query=pronto socorro -23.10%2C-48.92) already works (...)

Hi @lonvia, thanks, it is a good news for me (!)... Perhaps good news for many other users (you can check statistics at server log), because `a,b` is  ambigous syntax (and `a,%2Cb` is ugly).  The prefix "geo:" is easy to remember, is like a tag in any search engine. Of course, the direct detection of "a,b" is good for little and non-complex searches, but it is ambiguous... So "a,b" is not a command  from user to search engine, is only a "nonsolicitaed intelligence". 

About your assertion *"prefix nobody can remember"*... do you have statistics? <br/>Lets [stay open for some days](#issuecomment-452670798) to check real community opinion.

**Comment by danieldegroot2** [comment]
_Duplicate of #1123 ._
