### ISSUE TITLE
Searching for an emergency location by name and latlong, not permited?

### ISSUE THREAD

**Issue by ppKrauss** [openstreetmap/openstreetmap-website#2113]
Searching for an emergency location by name and LatLong, as in <br/>&nbsp;[`openstreetmap.org/search?query=pronto+socorro+-23.5,-46.65`](https://www.openstreetmap.org/search?query=pronto+socorro+-23.5%2C46.65) <br/>is a valid query... Or not?

The [osmfoundation.org/Terms_of_Use](https://wiki.osmfoundation.org/wiki/Terms_of_Use#III._Unlawful_and_other_unauthorized_uses) **says that it is not allowed**:  this is the interpretation of @simonpoole, @SK53  and perhaps others, explained on this  [this wiki-talk page](https://wiki.openstreetmap.org/wiki/Talk:Proposal_Open_Location_Code#Restriction_of_use:_emergency_services).

------

A typical scenario to illustrate the problem: <br/>I am looking for the location of an emmergence service, and I type in the search-box the string  "Pronto Socorro" or "Pronto Socorro -23.5,-46.65"   ... The OSM.ORG Service shows a location... Then I go there imagining that it is the Pronto Sorcorro nearst my home — but it is not, and the whole process causes me to waste time, and causes more,  I lose my life with a heart attack.

## Important
* important interpretation of the Terms of Use
* important an answer/position of the administrators 
* and community consensus  about this kind of interpretation

**Comment by tomhughes** [comment]
What on earth are you talking about?

We just send queries to Nominatim - if it able to resolve that then you will get results. If it can't then you won't. If you want to suggest improvements then you should do so in the Nominatim issue tracker not here.

I have absolutely not idea why you think it has anything to do with terms of use.

**Comment by woodpeck** [comment]
The terms of use say: "You may not operate dangerous businesses such as emergency services or air traffic control, where the use or failure of the Services could lead to death, personal injury or significant property damage". 

The reason for this is that we cannot guarantee that OSM is correct and complete. If someone used our data in a life-threatening situation and then someone dies because of an error in the data, we do not want to be responsible. We want to be able to say: "Sorry, you contravened our terms of use."

If someone uses our data in a life-threatening situation a live is saved by it, we don't intend to sue them.

This is a very common way of disclaiming liability in terms-of-use legalese. Making the query is allowed; but letting a life depend on the outcome of the query is not.

**Comment by tomhughes** [comment]
Right, but that doesn't make it unlawful for an end user to enter that search string. It just means we don't accept liability if you create an "emergency help kiosk" that uses our search or something similarly daft.

**Comment by dieterdreist** [comment]
sent from a phone

> On 13. Jan 2019, at 01:10, Frederik Ramm <notifications@github.com> wrote:
> 
> The terms of use say: "You may not operate dangerous businesses such as emergency services or air traffic control, where the use or failure of the Services could lead to death, personal injury or significant property damage".
> 
> The reason for this is that we cannot guarantee that OSM is correct and complete. If someone used our data in a life-threatening situation and then someone dies because of an error in the data, we do not want to be responsible. We want to be able to say: "Sorry, you contravened our terms of use."
> 
> If someone uses our data in a life-threatening situation a live is saved by it, we don't intend to sue them.
> 



we have been discussing this same paragraph on the italian mailing list some months ago, and the interpretation was that it refers to “services”, not “data”

quote:
. In particular these are:

the openstreetmap.org website and associated services and APIs,
the OpenStreetMap data distribution,
the OpenStreetMap wiki and help websites,
the OpenStreetMap mailing lists and forums.
(together, the “Services”).



end quote 



and above the paragraph you quoted it says: “You may not use the Services to:”

note it says “data distribution”, not data.
