### ISSUE TITLE
Document process for updating and changing nominatim geocoder strings

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2119]
@tomhughes points out in #1151 that some of our geocoder strings come from Nominatim, which I was unaware of. This throws up a number of things we should address:

* Let's document that this happens in one of our .md files, so that others don't make the same mistake that I did
* Where is the ultimate upstream for this, so that we can point people towards that instead? Is it in the nominatim repository, or on the osm wiki, or somewhere else?
* Is the process automated? Could we run the updates more frequently?

**Comment by lonvia** [comment]
The process is currently as follows: from time to time I run statistics over the Nominatim database and manually update the list. Key/values which are under a certain threshold (somewhere around 300 occurrences) are removed and those which are over a threshold (around 1000 occurrences) are added. The descriptions are then made up by me.

I've always meant to look into an external source for these tables, preferably have Nominatim serve language-specific .json files that can be used by other websites as well. @simonpoole's [preset project](https://github.com/simonpoole/beautified-JOSM-preset) might be a candidate.

**Comment by mmd-osm** [comment]
More and more tagging tagging related info gets moved to Wikibase these days: e.g. https://wiki.openstreetmap.org/wiki/Item:Q5825

**Comment by lonvia** [comment]
I'm happy for you to merge description changes like in #1151. They will be preserved over the updates. The situation would be a bit more difficult for PRs that add or remove key/value pairs. They would be subject to the thresholds on a subsequent update. I would prefer sticking with a half-way objective count of occurrences over getting into notability discussions.

In any case, you can always poke me if you feel the list has gone too far out of date. I'll look into providing an update in the next couple of days.
