### ISSUE TITLE
Various parts of website broken in older browsers, errors in console

### ISSUE THREAD

**Issue by Shepard** [openstreetmap/openstreetmap-website#2124]
A recent change seems to have introduced some problems with the website when using it with older browsers, like IE11. Features like searching, add note and query features don't work. Opening the browser console reveals some error messages:

```
Uncaught TypeError: n.findIndex is not a function
Uncaught TypeError: Cannot read property 'route' of undefined
Unrecognized Content-Security-Policy directive 'worker-src'.
jQuery.Deferred exception: n.findIndex is not a function TypeError: n.findIndex is not a function
```

It seems like commit 48e886784e742ec28e33c32b3a0e0bf7cf6d21e7 might be at least partly responsible for the errors seen in the console. According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex `findIndex` is not supported in IE11.

**Comment by Shepard** [comment]
This error reappeared: "Uncaught TypeError: n.findIndex is not a function".
Should I open a new ticket?

**Comment by tomhughes** [comment]
What browser?

**Comment by Shepard** [comment]
Sorry for the late response. This was on Chromium 43.

**Comment by HolgerJeromin** [comment]
Using a four year old browser seems not a good idea.

**Comment by tomhughes** [comment]
Just too old as well. By the looks of it 45+ would work... I've pushed https://github.com/openstreetmap/openstreetmap-website/commit/d74dd80540824b86fc93fc9573f412bbbcaefbc4 now to tighten things up a bit.
