### ISSUE TITLE
couldn't find some messages of website [for translation]

### ISSUE THREAD

**Issue by iriman** [openstreetmap/openstreetmap-website#2128]
I searched translatewiki for openstreetmap website, but couldn't find this:

![screenshot_2019-02-01 openstreetmap](https://user-images.githubusercontent.com/8467903/52137536-068b0200-2660-11e9-8e2b-424434e727a2.png)

**Comment by tomhughes** [comment]
I suspect that comes from a plugin and may not be translatable, at least in our repository.

**Comment by tomhughes** [comment]
Yes - it comes from https://github.com/validates-email-format-of/validates_email_format_of which only has a couple of locales.

It might be possible to just add those keys in our locale file though... I will investigate.
