### ISSUE TITLE
Is it possible to integrate an additional layer into the map?

### ISSUE THREAD

**Issue by gmbo** [openstreetmap/openstreetmap-website#2130]
Is it possible to integrate an additional layer into the map?
In my opinion it would be nice and feasible to change one of the existing layers into a user defined layer.
Then someone could add another layer like satellite images of one and another a leisure map. If the browser stores these data of a WMS or Tileserver everyone could use his favorite style.

Greetings
Gisbert

translated from german:
Ist es möglich einen zusätzlichen Layer in die Karte zu integrieren?
Meiner Meinung nach wäre es schön und machbar einen der jetzt vorhandenen Layer in einen User definierten Layer zu ändern.
Dann könnte jemand einen anderen Layer wie Satellitenbilder von einem und ein anderer eine Freizeitkarte. Wenn der Browser diese Daten eines WMS oder Tileservers speichert könnte jeder seinen Lieblingsstiel nutzen.

Grüße
Gisbert

**Comment by tomhughes** [comment]
It's theoretically possible for sure, but I think it's too technical for our typical users - anybody that has the skill to do that kind of thing probably has the skills to throw up a simple site of their own with whatever layers they want.

**Comment by gmbo** [comment]
For the typical user the default layer would be fine. 
But also they ask again and again why for example no aerial photo is possible. 
The question came at an OSM summer camp after extending the standard map with additional tile and WMS layers.
Since you can't do it all right, an editable selection of one of the layers would be a good alternative.  
And yes a simple map with its own layer works for some, but entering a tile server should be easier, so that many more can be achieved and could be well described with examples.

In order to avoid wrong entries a list of possible layers could be offered, which can also be used by newcomers.


Translated with www.DeepL.com/Translator von

Für den typischen Benutzer wäre da ja der voreingestellte Layer in Ordnung. 
Aber auch die fragen immer wieder mal warum zum Beispiel kein Luftbild geht. 
Die Frage kam bei einem OSM-Sommercamp nach Erweiterung der Standardkarte um zusätzliche Tile und WMS-Layer.
Da man es aber nicht allen Recht machen kann, wäre eine editierbare Auswahl eines der Layer eine gute Alternative.  
Und ja eine einfache Karte mit eigenem Layer geht für einige, aber das Eintragen eines Tileservers dürfte einfacher sein, damit viele mehr erreichen und ließe sich ja mit Beispielen gut beschreiben.

Auch könnte um Fehleingaben zu vermeiden eine Liste der möglichen Layer angeboten werden, die dann auch von Neulingen genutzt werden können.

**Comment by gravitystorm** [comment]
> But also they ask again and again why for example no aerial photo is possible.

There are some reasons why we don't show an aerial photo layer. Firstly, there are no providers of aerial imagery layers who have ever offered their layers for viewing on our website. All of our agreements with aerial providers only permit use in our editing software. So everything else doesn't really matter.

Secondly, the main purposes of the maps on openstreetmap.org are for showing what information OpenStreetMap contains (that's why we have different layers, showing different things, too) and to help mappers choose where in the world they want to edit. Having an aerial imagery layer on the main page doesn't help explain what OSM contains, nor does it help mappers, who can access multiple aerial imagery layers within the editors. So finding and negotiating access to aerial imagery for non-editing purposes is not a priority for us.

As for the general point, I would welcome lots more different map layers, although [that's a decision for OWG](https://wiki.openstreetmap.org/wiki/Featured_tile_layers/Guidelines_for_new_tile_layers), not for this issue tracker. We could have 8-10 layers, all showing different features from OpenStreetMap.

**Comment by gmbo** [comment]
I think it helps a user, who only knows the big G ode B for the search and its map services, to show the richness of detail of the OSM map. Many people use the habit of switching to aerial photography. If I can show them in most cases that what he wants to see in the aerial photograph is already visible on the large part of the map, and they can even improve the area where something is inaccurate. Often one sees even more on our maps, like footpaths, then he will not use the aerial photos so often any more. 

My inquiry is to be seen also only as food for thought, and I am the opinion that if the user uses the aerial image layer, this is permitted with most services, they would not be offered thereby by the web page operator.

My thought-provoking impulses were:
http://tools.geofabrik.de/mc/#15/49.0143/8.4025&num=4&mt0=mapnik&mt1=here-map&mt2=wanderreitkarte&mt3=here-satellite
and the WP plugin https://github.com/bozdoz/wp-plugin-leaflet-map 

But many thanks for the answers and of course thanks again to all who maintain this site.
Greetings
Gisbert


Translated with www.DeepL.com/Translator from
Ich glaube schon, dass es hilft so etwas einem Benutzer, der bisher nur das große G ode B für die Suche und deren Kartendienste kennt, den Detailreichtum der OSM-Karte aufzuzeigen. Viele nutzen  gewohnheitsmäßig die Umschaltung auf Luftbilder. Wenn ich denen in den meisten Fällen zeigen kann, dass das was er im Luftbild sehen will auf dem großen Teil der Karte schon längst sichtbar ist, und sie da wo etwas ungenau ist, selbst den Bereich verbessern können. Oft sieht man auf unseren Karten sogar mehr, wie Fusswege, dann wird er die Luftbilder nicht mehr so oft nutzen. 

Meine Anfrage ist ja auch nur als Denkanstoß zu sehen, und ich bin der Meinung, dass wenn der Benutzer den Luftbildlayer einsetzt, dies bei den meisten Diensten erlaubt ist, sie würden ja dadurch nicht vom Webseitenbetreiber angeboten.

Meine Denkanstöße dazu waren:
http://tools.geofabrik.de/mc/#15/49.0143/8.4025&num=4&mt0=mapnik&mt1=here-map&mt2=wanderreitkarte&mt3=here-satellite
und das WP-Plugin https://github.com/bozdoz/wp-plugin-leaflet-map 

Aber vielen Dank für die Antworten und natürlich noch einmal Danke an alle die diese Seite aufrechterhalten.
Gruß
Gisbert
