### ISSUE TITLE
Simply also put URL in side panel, to make Share also work with Directions

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2139]
Please grey-out the right "share" panel or even "share" button itself,
when the user has computed directions.

Else the user will surely think he is sharing the directions, only e.g.,
to be told a week later by the boss that they got lost because all he
sent them was a single point.

With Google Maps "share" always really means share what one thinks one
is sharing, not something else.

Furthermore, when one day OSM does implement sharing directions, how to
explain the sudden different behavior of the share button?

Anyway, indeed it would be quite simple to make share work correctly
with directions, just put the same thing that is in the URL bar above,
into the URL bar on the right side! That's (almost) all there is to it!

![0](https://user-images.githubusercontent.com/1230959/52608262-4948a780-2eb4-11e9-9c89-9678b5a475c3.jpg)

**Comment by jidanni** [comment]
> "But Short Link wouldn't work right"
Well grey it out for now. The point is to avoid the user thinking he is sharing something that he isn't.

**Comment by tomhughes** [comment]
There's already a ticket about sharing and directions.
