### ISSUE TITLE
Add branding to Site Busy message

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2140]
On the

> This website is under heavy load (queue full)
> We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.

message, it would be best to still add some "branding" (logo) at the
top. (I'm sure it wouldn't add that much load.)

In fact from all we can tell, maybe we are actually being connected to
some different (broken) site. At least mention the word "Openstreetmap"...

Indeed, looking at the HTML,
```
<h2>This website is under heavy load (queue full)</h2>
<p>We're sorry, too many people are accessing this website
at the same time. We're working on this problem. Please try again later.</p>
```
there isn't even a proper `<head>`!

(And perhaps also add contact info at the bottom. "(If this problem persists,
call Ralph Norrbs at +1-312-555-...)")

**Comment by tomhughes** [comment]
Well you should never see that really, and it's an operational issue, not something that can be fixed in this repository.

**Comment by mmd-osm** [comment]
As a side note: people on the US slack channel repeatedly mention this as an issue, and it seems getting worse and worse over the last weeks, with at least 1-2 reports per week at the moment. I didn't see anything conclusive on munin stats.
