### ISSUE TITLE
make possible an overview of shops in a certain area

### ISSUE THREAD

**Issue by Rik44444** [openstreetmap/openstreetmap-website#2141]
hi all,
a feature request: in OsmAnd (the app), when you search for a shop type and a city name, eg Hairdresser Amsterdam or coffee London, the app gives you an overview of a certain area with all the hairdressers or coffee places highlighted. Openstreetmap.org does not do this; it does list them on the left side, but they do not show on the map. This is one of the features i use most often (previously on Google Drive, and now that I've moved to Openstreetmap.org and OsmAnd here). Do you agree this would be a nice feature to have, i mean to have the search results show up on the map on openstreetmap.org, just like in OsmAnd?
keep up all the great work!! 
best
Rik

**Comment by tomhughes** [comment]
We are not aiming to provide that sort of consumer facing web site - our site is aimed at supporting mappers rather than end users.

**Comment by stephan75** [comment]
@Rik44444 
Alternatively have a look at http://openpoimap.org/ or https://www.openstreetbrowser.org
