### ISSUE TITLE
URL for user with non-ASCII character in name says user missing

### ISSUE THREAD

**Issue by RalphCorderoy** [openstreetmap/openstreetmap-website#2142]
https://www.openstreetmap.org/way/670075817#map=19/50.90226/-1.33848 was done by user `Åndrew`. Clicking the link provided on that page to https://www.openstreetmap.org/user/%C3%85ndrew returns a 404: 'Sorry, there is no user with the name Åndrew'. It seems the Unicode U+C5 upsets the look-up. Brief discussion of this on #osm 2019-02-13 15:21 +0000.

**Comment by gravitystorm** [comment]
Interesting. I can't recreate the problem on my local instance. There's nothing fancy in the byte sequence returned from the XML output for that changeset ("c3 85" is just a regular unicode character, not a combining glyph or anything) and so my only guess is that there's some non-xml-compatible characters in the database for that username.

I can't think of any way to diagnose further without checking what's really in the database for this user.

**Comment by RalphCorderoy** [comment]
'c3 85' is the UTF-8 encoding of U+C5, yes. I wondered if the username uses a combining diacritical, i.e. U+030A, but tried 'A' followed by that, https://www.openstreetmap.org/user/Åndrew, and it gives a similar result. It could well be Andrew does something fancy with his Unicode username and it's being canonicalised, or otherwise altered, before ending up in the URL that's faulty.

**Comment by tomhughes** [comment]
It looks like a corrupt index - it works if I force a sequential scan but fails on an indexscan.

**Comment by RalphCorderoy** [comment]
Rather than the index being corrupt, perhaps the parties reading and writing it disagree on how to represent and sort Åndrew and therefore it appears to be missing? It's an area with some thorns. https://en.wikipedia.org/wiki/Unicode_equivalence

**Comment by tomhughes** [comment]
See above discussion - the data in the database is encoded as expected.

**Comment by tomhughes** [comment]
Both the lowercase and non-lowercase indexes seem to be affected and it looks to have been corrupt for some months as we have 36 duplicate users that shouldn't exist as a result :-(

**Comment by tomhughes** [comment]
Indexes have been rebuilt and that user can now be found.

**Comment by RalphCorderoy** [comment]
Thanks very much. Will there be an issue to consider a check of some sort that should be periodically run to check the indexes aren't corrupt?

**Comment by katpatuka** [comment]
I don't know if the status changed in the meantime but I didn't have problems in Opera 12.17 or Firefox 52.9.0 with pasting either https://www.openstreetmap.org/user/Åndrew or https://www.openstreetmap.org/user/%C3%85ndrew in the address field. Which operating system do you use?

**Comment by tomhughes** [comment]
Well it shouldn't happen, and it's hard to know what form such a check would take. You would have to take every single user and try doing an index lookup on them...

**Comment by RalphCorderoy** [comment]
I was hoping for some DB-equivalent of fsck that would spot the problem. Otherwise, it's extract all the names in the supposedly-sorted order of the index, and then check with code outside the database that they are indeed sorted by the expected criteria and there's no adjacent duplicates. Just wondering if the corruption can happen again, and how to notice it as detecting it soon after it happens might help narrow down the cause.
