### ISSUE TITLE
Join is incorrect between key and value

### ISSUE THREAD

**Issue by abhinavsagar** [openstreetmap/openstreetmap-website#2143]
Both visible_nodes and changeset_cache variables should be updated as the key and values change.

**Comment by tomhughes** [comment]
Context please. What code exactly are you referring to?

**Comment by gravitystorm** [comment]
Hi @abhinavsagar unfortunately I can't figure out what part of the codebase you are referring to either, so there's nothing further that we can do here. If you can explain in more detail what the problem is, then I would be happy to reopen this issue.
