### ISSUE TITLE
Copyright page needs explicit text direction

### ISSUE THREAD

**Issue by iriman** [openstreetmap/openstreetmap-website#2148]
As we can view copyright page in any language with any given locale of website interface, it should have appropriate text direction (and alignment) for both RTL and LTR languages.

For example, Persian is right-to-left;
* If someone has set the interface to en, then [Persian version of copyright](https://www.openstreetmap.org/copyright/fa) looks like:

  ![lang_fa-locale_en](https://user-images.githubusercontent.com/8467903/53003564-73661080-3444-11e9-9faf-ca9072f10350.png)

  which should be right-to-left and right-aligned.

* Or, if someone has set the interface to fa, then [English version of copyright](https://www.openstreetmap.org/copyright/en) looks like:

  ![lang_en-locale_fa](https://user-images.githubusercontent.com/8467903/53003747-ecfdfe80-3444-11e9-9934-4d726eaf859c.png)

  which should be left-to-right and left-aligned.

**Comment by tomhughes** [comment]
I can easily add the `dir` and `rtl` attributes to a div wrapping that text but that doesn't actually solve it because all the CSS rules need to be reversed as well and that's going to be hugely complicated :-(

**Comment by iriman** [comment]
Thanks for the quick fix. This was really needed, because in Persian community we are directing users of OpenStreetMap data to respect OpenStreetMap copyright by linking to this page. 

But yes, I'm aware of its complication.
