### ISSUE TITLE
Dev site has inconsistent data

### ISSUE THREAD

**Issue by b-jazz** [openstreetmap/openstreetmap-website#2154]
Repro:
1) Visit https://master.apis.dev.openstreetmap.org/#map=18/44.04193/-123.07140
2) Query any of the objects (e.g. Hayward Field)
3) Click on the "Hayward Field" link in the left rail (https://master.apis.dev.openstreetmap.org/way/660988929)
4) Receive the error message, "Sorry, way #660988929 could not be found."

I expected to see the tags for that object appear along with the last comment and the list of nodes that make up the way.

**Comment by tomhughes** [comment]
The dev sites have totally separate databases so yes, most things on the map won't be there. Only anything that people have added on the dev site will be present.

**Comment by gravitystorm** [comment]
To expand further on what @tomhughes said - the dev apis start from empty databases, and their databases are occasionally emptied again. But they dev apis still use the normal third-party services, such as tileservers, nominatim, overpass etc which are all using "production" data, not the data within the dev api databases. So anything that uses a third-party service (like the query tool) will return production data, not the data from the dev apis.

Resolving this would be a tremendous amount of work. For every dev api, we would need a full set of tileservers, geocoding, minutely replications feeds, overpass servers, routing servers etc etc if we wanted full consistency between the different parts of the system. It's not really worth the effort.

**Comment by woodpeck** [comment]
To expand further on what @gravitystorm said - while it is not "worth the effort" for the people currently involved in running the system, it would certainly be nice to have. I have [posted about that in 2016](https://lists.openstreetmap.org/pipermail/dev/2016-November/029557.html) ("I'm now looking for a small team of people who have the time and energy to plan and install such a sandbox together.") offering to make the necessary server(s) available, but haven't had any takers. The offer still stands.
