### ISSUE TITLE
Content Security Policy violations

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2155]
Use Developer tools (F12) visiting e.g., https://www.openstreetmap.org/#map=13/24.3577/120.9286
The page loads fine, but in the Console I see
In Firefox:
> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). www.openstreetmap.org:1:1 

In chromium:
> Refused to load manifest from 'https://www.openstreetmap.org/assets/manifest-63908e2….json' because it violates the following Content Security Policy directive: "manifest-src 'none'".

**Comment by tomhughes** [comment]
Simple solution - don't go poking around in the console and worrying about things that aren't a problem.

If you notice something actually failing to work because of an error in the security policy then please do feel free to report it.
