### ISSUE TITLE
Basic Auth Password $ Character does not validate

### ISSUE THREAD

**Issue by alexkavon** [openstreetmap/openstreetmap-website#2172]
I am using curl commands to test the v0.6 API:

```curl
curl -umyusername:$ecretpa$$word -XPUT 'https://master.apis.dev.openstreetmap.org/api/0.6/changeset/create' -d'<osm><changeset></changeset></osm>'
```

If the password contains a `$` then the API endpoint will fail to authenticate properly.

**Comment by tomhughes** [comment]
If it contains a $ then you will need to single quote it (or escape the $ signs with a backslash) otherwise your shell will expand it as a variable.

Short version - this is an error in how you have written your test, not a bug in the server.
