### ISSUE TITLE
login fails if space are present b/c no trimming is done on email

### ISSUE THREAD

**Issue by soig** [openstreetmap/openstreetmap-website#2173]
Hi
Login on osm.org fails if spaces are present b/c no trimming is done on email
eg:
Login as "foo@bar.com " will fail (trailing space)
Whereas the same password will succeeds if using "foo@bar.com" (no trailing space)

The solution is simple remove spaces at beginning & end of entered email as login.
Thanks

**Comment by tomhughes** [comment]
Yes it's simple until you find some lunatic has created a user with significant whitespace in their name...

I know that can't work for email but we allow either username or email for login and it's not completely trivial to trim one and not the other.

We don't currently allow leading or trailing whitespace for usernames but I need to check if that has always been the case ;-)

**Comment by tomhughes** [comment]
As I feared we have 65 users with at least one leading space and 690 with at least one trailing space :-(

**Comment by soig** [comment]
Thanks

**Comment by HolgerJeromin** [comment]
> As I feared we have 65 users with at least one leading space and 690 with at least one trailing space :-(

Wow. Did they logged in more than once?
