### ISSUE TITLE
Addition of Spanish national mapping agency attribution on osm.org/copyright

### ISSUE THREAD

**Issue by dorotheakazazi** [openstreetmap/openstreetmap-website#2179]
Hello :)

- Can the following text be added on [osm.org/copyright](https://www.openstreetmap.org/copyright)?

 **Spain**: Contains data sourced from the Spanish National Geographic Institute
([IGN](http://www.ign.es)) and National Cartographic System ([SCNE](http://www.scne.es)) licensed for reuse under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).

1. The board has [approved](https://wiki.osmfoundation.org/wiki/Board/Minutes/2019-0320#2019.2FRes14_Allow_attribution_on_osm.org.2Fcopyright_page) this addition, with the understanding that attribution may be moved in the future.
2. The text was suggested by Santiago Crespo, who initially [contacted the board](https://lists.openstreetmap.org/pipermail/talk-es/2018-November/016446.html) about the issue, and was seen by board members.

Thank you.

**Comment by tomhughes** [comment]
I'm pretty sure there's already a ticket about this and it's pending on an LWG decision.

**Comment by pnorman** [comment]
> I'm pretty sure there's already a ticket about this and it's pending on an LWG decision.

I thought so too, but can't find it. And yes, the request came from the LWG, so it should go back to them.

**Comment by simonpoole** [comment]
For all practical purposes this was an appeal of a LWG decision, so while it is formally correct that it for that reason probably should go back to the LWG and then to the OWG/ops, I think we can skip that bit.
