### ISSUE TITLE
Transit route planning?

### ISSUE THREAD

**Issue by dansgithubuser** [openstreetmap/openstreetmap-website#2183]
Hey there,

I've recently switched from Google Maps to OSM and noticed a lack of trip planning with transit -- particularly TTC (Toronto).

Independently, I've been annoyed with the shortcomings of TTC's ability to predict where their vehicles are going to be. Multiple times I've skipped one bus for a faster one that never shows up. I'm interested to create something that collects vehicle locations and makes its own predictions about the plausibility of various routes.

What I'm wondering is where transit integration is for you. While I'm interested in the above project regardless, it'd be great to integrate here. Is there some standard(ish) manner in which you integrate transit into OSM? I'd love to conform to it if so.

I realize the most realistic way for OSM to work with Toronto transit may be to integrate directly with the nextbus API. But just thought I'd reach out.

**Comment by tomhughes** [comment]
We're not really aiming to provide an end user route planning service - the presence of routing on our web site is really to help mappers debug connectivity problems.
