### ISSUE TITLE
Tracktype

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/openstreetmap-website#2193]
Hi,

I put here a copy (after the $$$) of a comment I just add about tracktype on ID's github. I think you should think, alone or with ID's team, to find a better way to solve this problem because otherwise I'm pretty sure that this problem will be here forever.

Best regards
 
$$$$$$$$$$$

Hi,

I really don't know how big this problem is but, since KeepRight was included in ID, it's cleary the most important problem I can see (maybe because I'm working on maps in south America and there are a lot of very small roads with highway=track).
For me there are so many "bugs" in OSM that it will be not possible to solve all before a very long time.
The first reason is that these roads need to be "seen" to be able to put the correct value : but a lot of roads in south America are on OSM because of satellite view (Bing or others) and a very few people drive on these very small roads to see the grade.

So I think that to wait that a nice guy correct all the missing tracktype is just a big dream.

You really should think about a new solution : 
- when I create a new way, I don't need to indicate that it has 2 lines or that oneway=no : they are the default values. Why not to do the same and to suppose that tracktype=grade2 when there is no indication of the tracktype ?
- when I indicate a tunnel or a bridge, ID automatically adds "layer=-1" or "layer=1" even if a lot of time unnecessary (because not crossing another road) : when I create a highway=track, you could automatically add tracktype=grade2.

I clearly prefer the first solution because the second solution is included in it and because it will solved all the bugs in OSM that nobody will never changed (I'm sure of that : if you do nothing, I will be back here in 2 years to show you I'm right).

For your informations, when I drive on roads (track or others), I never put tracktype but smoothness and maxspeed to tell that the road is ok for normal car or that you need a 4x4 car (for examples) and to tell that the road can be drive at 50 miles per hour or at 10 miles per hour, informations clearly more relevant than the tracktype.

Up to now, when I saw a tracktype missing, I changed the highway=track to highway=unclassified+surface=unpaved to be able to close the KeepRight. But now I will do nothing because the missing tracktype is clarly a false problem.

I put a copy of this message on OSM because I understand that this issue is not really an ID's issue.

**Comment by gravitystorm** [comment]
> I put a copy of this message on OSM because I understand that this issue is not really an ID's issue.

I'm sure the people who manage the iD issue tracker will be able to deal with this. It's a combination of editing with iD and warnings shown by Keepright, and as such, is not related to this codebase. So I am closing this issue, and discussion can continue in the relevant places.

**Comment by Mahabarata** [comment]
Hi,

happy to see that this bad rule is not coming from you.
Best regards

**Comment by Mahabarata** [comment]
Hi,

happy to see that this bad rule is not coming from you.
Best regards
