### ISSUE TITLE
Safari 12 [Mac] wipes login cookie in some circumstances

### ISSUE THREAD

**Issue by systemed** [openstreetmap/openstreetmap-website#2194]
I kept on getting logged out of OSM for no apparent reason, and have narrowed it down to this:

1. Log into openstreetmap.org with Safari 12
2. In a new window/tab, go to osm.org (_not_ openstreetmap.org)
3. Return to the original window/tab and refresh
4. You are now logged out

It appears to be a Safari 12 thing. Safari 10 is ok, Chrome/Chromium and Firefox too. My guess is that this is a side effect of one of Safari's anti cross-site-tracking behaviours but who knows.

I realise this is probably difficult to debug without access to a Mac, so am posting the issue mostly in case anyone else encounters it and can see what's going on. Happy to provide request/response details from the console if useful.

**Comment by dieterdreist** [comment]
It could be something else, I tried to do what you describe and I didn't
experience the issue on Safari 12.1 (13607.1.40.1.5)
Actually, in your step 2, when I go to osm.org I get instantly redirected
to openstreetmap.org

**Comment by tomhughes** [comment]
I can conceive of no reasonable explanation for this (in particular for why osm.org vs openstreetmap.org would make a difference) so to be honest this sounds like a bug in Safari.

As @dieterdreist says osm.org will redirect and the cookie will only be sent on the redirected request just as it would be if you had entered openstreetmap.org in the first place. Presumably that window is logged in correctly in both cases?

**Comment by systemed** [comment]
I'm on 12.0.3; I see 12.1 was released a couple of days ago so I'll try updating.

**Comment by systemed** [comment]
Weirdly it's still doing it on 12.1 for me (extensions disabled). I'll look into it some more.

**Comment by mmd-osm** [comment]
Safari 12.x isn't the most recent version anymore. Is this still relevant today, or we can close this issue?

**Comment by systemed** [comment]
Closing. It's still an issue for me but I'm pretty convinced it's a Safari issue rather than an OSM problem.

**Comment by mmd-osm** [comment]
On Slack, a few Chrome users reported that they have to re-login very frequently lately. Sometimes that's even daily.
