### ISSUE TITLE
googleapis.com: No response received

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2199]
User uses
https://chrome.google.com/webstore/detail/change-geolocation/njjpmclekpigefnogajiknnheheacoaj

But clicking on "Show My Location" on osm.org still gives
> "Geolocation error: Network location provider at
'https://www.googleapis.com/' : No response received.."

https://mylocation.org/ 's Browser Location gives the correct intended location.

**Comment by tomhughes** [comment]
The phrase "still gives" suggests that you see this without the extension, so I don't understand how the extension is relevant or why you expected it to change anything.

Perhaps you should start from the beginning and explain your real problem?

**Comment by mmd-osm** [comment]
Just don't waste your time on this. The extension's support site is full of reports that it's broken and not working at all.

**Comment by mmd-osm** [comment]
By the way, chrome developer tools let you fake the GPS position without any need for an extension, see https://www.techjunkie.com/fake-location-google-chrome/ -> "Fake your location in Google Chrome"

This is getting way off topic here...

**Comment by jidanni** [comment]
Yes, the issue remains, extension installed or not
```
$ chromium --temp-profile https://osm.org/
```
gives the above API error message.

```
$ firefox --private-window https://osm.org/
```
zooms in on the location.

**Comment by pnorman** [comment]
Does https://leafletjs.com/examples/mobile/ request permission for your location then show it on the leaflet map?

**Comment by jidanni** [comment]
Same thing. A request pops up. I say Allow. And then the error.
![Q_1](https://user-images.githubusercontent.com/1230959/55530094-38a7f700-56d7-11e9-9aa7-fb44323b2af2.jpg)

**Comment by pnorman** [comment]
The problem is with your setup. Perhaps you've blocked www.googleapis.com, which is what your **browser** is using to geolocate. In any case, the problem doesn't appear to be anything that can be resolved in this repository.

**Comment by jidanni** [comment]
https://stackoverflow.com/questions/41137594/network-location-provider-at-https-www-googleapis-com-returned-error-code

**Comment by jidanni** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=753242

**Comment by AlbertEinsteinGlitchPoint** [comment]
Hi guys

which support team do we need to reach out in order to update our geolocation from our IPv4 block ip ? as its showing somewhere else across the globe, we are in south america, and the IPv4 geolocation from openstreemap is displyaing out in europe ...

**Comment by tomhughes** [comment]
@AlbertEinsteinGlitchPoint your question has absolutely nothing to do with this ticket.
