### ISSUE TITLE
Rails based GPX Import failure on /api/0.6/gpx/create endpoint

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#2200]
JOSM DirectUpload plugin lets you upload GPX traces from within JOSM by using the API 0.6 /api/0.6/gpx/create endpoint. This currently works on production (external GPX importer), but fails on the master dev instance (Rails based GPX importer).

The upload itself succeeds with HTTP 200. However, the GPX file stays in the queue forever, and no success/failure notification email gets sent out.

Maybe there's still something missing here for the API endpoint, and not all parameter values get passed on?

On the rails console, some lengthy stack traces appear, which indicate that the trace importer tries to process something which isn't there:

```
[ActiveJob] [TraceImporterJob] [x] undefined method `import' for nil:NilClass
[ActiveJob] [TraceImporterJob] [x] openstreetmap-website/app/jobs/trace_importer_job.rb:5:in `perform'
```

**Comment by gravitystorm** [comment]
I've seen this happen where the gpx directories in settings.yml do not exist. You can override them with entries in config/settings/development.local.yml (or production.local.yml) without interfering with the tests.

Can you confirm whether this is the problem? If so, we can look at making the error messages better.

**Comment by mmd-osm** [comment]
Unfortunately, that didn't help. I found various gpx files in my gpx trace directory, which probably means that the directory setting was already in place before.

https://master.apis.dev.openstreetmap.org/ currently has the same issue, so maybe you could take a look there?
