### ISSUE TITLE
params[:user] is possible to be nil, and will cause unhandled exception.

### ISSUE THREAD

**Issue by jwjwyoung** [openstreetmap/openstreetmap-website#2202]
https://github.com/openstreetmap/openstreetmap-website/blob/36817f777c502a5a044e82fc3e3ca55f5433d66f/app/controllers/users_controller.rb#L452

Reproduce in /users page 
![image](https://user-images.githubusercontent.com/42279873/55848376-4a8ffc80-5b12-11e9-803a-350a7462b79c.png)

When I don't select any user and click "Confirmed Selected User" button, I will get an error saying params[:user] is nil as bellows.

![image](https://user-images.githubusercontent.com/42279873/55848362-406dfe00-5b12-11e9-86af-92d117cee51b.png)

Better error handler should be provided here, such as enforce at least choose one user.

**Comment by tomhughes** [comment]
What action is this? Please probe proper context when reporting a problem...

**Comment by tomhughes** [comment]
Oh I see - that's a slapped together admin page that I am basically the only user of. Not a major issue at all if it doesn't cope with user error ;-)

**Comment by jwjwyoung** [comment]
I agree it will not affect users other than the administrators. But I will be happy to post a pr if you need.

**Comment by mmd-osm** [comment]
I'm closing this one, because the page is accessible for administrators only, and it's not worth the effort really.
