### ISSUE TITLE
link to user is case sensitive while user display name is case insensitive

### ISSUE THREAD

**Issue by jwjwyoung** [openstreetmap/openstreetmap-website#2203]
I am using the postgresql database.

When I have a user name "ABC", then I can access it through the link `/user/ABC`, while I cannot access it through` /user/abc`, or any other combination of the mixed-case link. It's caused by the code https://github.com/openstreetmap/openstreetmap-website/blob/36817f777c502a5a044e82fc3e3ca55f5433d66f/app/controllers/users_controller.rb#L372, which will parse the original form of parameters.

I guess we could change the code to:
`@this_user = User.where('lower(display_name) = ?', params[:display_name].downcase).first`

which make /user/abc and /user/ABC refer to the same person.

**Comment by tomhughes** [comment]
Our user names are case sensitive, with the exception of some special casing in login relating to the fact that they were case insensitive at one point.

**Comment by tomhughes** [comment]
In particular although we don't allow it for new users there are historic user records which differ only in case.

**Comment by jwjwyoung** [comment]
Thanks for your quick response.

I believe the code here https://github.com/openstreetmap/openstreetmap-website/blob/36817f777c502a5a044e82fc3e3ca55f5433d66f/app/models/user.rb#L94 set the display_name as case insensitive.

**Comment by gravitystorm** [comment]
@jwjwyoung yes, but only when the display name changes (see the link above). As @tomhughes mentioned, the main openstreetmap database contains legacy case-sensitive user names.

**Comment by jwjwyoung** [comment]
Thanks a lot for your clarification.
