### ISSUE TITLE
Adopt crosshairs feature

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2206]
https://github.com/openstreetmap/iD/issues/6173 is a great crosshair feature that would be good for the OSM website too.
Currently a marker is only shown when the pointer is hovering over a search result, but then disappears when one does any other action.

**Comment by tomhughes** [comment]
Referencing your own unresolved issue is no way to support your case...

I don't see any in scope use case for this I'm afraid.

**Comment by jidanni** [comment]
Here we know the center of the screen, the crosshair,
https://skyvector.com//?ll=43.45047,-79.20066&zoom=1
Here we there is the same center, but not shown to the user:
https://www.openstreetmap.org/#map=11/43.45047/-79.20066
Workaround: add marker:
https://www.openstreetmap.org/?mlat=43.45047&mlon=-79.20066#map=11/43.45047/-79.20066

**Comment by HolgerJeromin** [comment]
This issue is still lacking a proper use case...
