### ISSUE TITLE
Problem with db:create

### ISSUE THREAD

**Issue by kostjaz** [openstreetmap/openstreetmap-website#2212]
Trying to install openstreetmap-website on Ubintu 16.04 with the INSTALL.md
I've got such messege after **bundle exec rake db:create**

_pngcrush worker: `pngcrush` not found; please provide proper binary or disable this worker (--no-pngcrush argument or `:pngcrush => false` through options)
advpng worker: `advpng` not found; please provide proper binary or disable this worker (--no-advpng argument or `:advpng => false` through options)
optipng worker: `optipng` not found; please provide proper binary or disable this worker (--no-optipng argument or `:optipng => false` through options)
pngquant worker: `pngquant` not found; please provide proper binary or disable this worker (--no-pngquant argument or `:pngquant => false` through options)
jhead worker: `jhead` not found, `jpegtran` not found; please provide proper binary or disable this worker (--no-jhead argument or `:jhead => false` through options)
jpegoptim worker: `jpegoptim` not found; please provide proper binary or disable this worker (--no-jpegoptim argument or `:jpegoptim => false` through options)
jpegtran worker: `jpegtran` not found; please provide proper binary or disable this worker (--no-jpegtran argument or `:jpegtran => false` through options)
gifsicle worker: `gifsicle` not found; please provide proper binary or disable this worker (--no-gifsicle argument or `:gifsicle => false` through options)
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
Created database 'openstreetmap'
Created database 'osm_test'_

So, I tried to google that, and read that it's a problem with image_optim.
I have 0.26.3 version

$ **bundle exec image_optim --info**
_image_optim v0.26.3
config:
  verbose: true
nice: 10
threads: 2
pack: false
skip_missing_workers: false
allow_lossy: false
cache_dir:
cache_worker_digests: false
PATH: /var/lib/gems/2.5.0/bin:/home/openstreetmap/bin:/home/openstreetmap/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/var/lib/gems/2.5.0/gems/image_optim-0.26.3/vendor
Resolved jpegrescan 1a762f62 at /var/lib/gems/2.5.0/gems/image_optim-0.26.3/vendor/jpegrescan
Bin resolving errors:
pngcrush worker: `pngcrush` not found; please provide proper binary or disable this worker (--no-pngcrush argument or `:pngcrush => false` through options)
pngout worker: `pngout` not found; please provide proper binary or disable this worker (--no-pngout argument or `:pngout => false` through options)
advpng worker: `advpng` not found; please provide proper binary or disable this worker (--no-advpng argument or `:advpng => false` through options)
optipng worker: `optipng` not found; please provide proper binary or disable this worker (--no-optipng argument or `:optipng => false` through options)
pngquant worker: `pngquant` not found; please provide proper binary or disable this worker (--no-pngquant argument or `:pngquant => false` through options)
jhead worker: `jhead` not found, `jpegtran` not found; please provide proper binary or disable this worker (--no-jhead argument or `:jhead => false` through options)
jpegoptim worker: `jpegoptim` not found; please provide proper binary or disable this worker (--no-jpegoptim argument or `:jpegoptim => false` through options)
jpegtran worker: `jpegtran` not found; please provide proper binary or disable this worker (--no-jpegtran argument or `:jpegtran => false` through options)
gifsicle worker: `gifsicle` not found; please provide proper binary or disable this worker (--no-gifsicle argument or `:gifsicle => false` through options)
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
/var/lib/gems/2.5.0/gems/image_optim-0.26.3/lib/image_optim/worker/class_methods.rb:73:in `create_all'
/var/lib/gems/2.5.0/gems/image_optim-0.26.3/lib/image_optim/worker/class_methods.rb:44:in `create_all_by_format'
/var/lib/gems/2.5.0/gems/image_optim-0.26.3/lib/image_optim.rb:88:in `initialize'
/var/lib/gems/2.5.0/gems/image_optim-0.26.3/lib/image_optim/runner.rb:54:in `new'
/var/lib/gems/2.5.0/gems/image_optim-0.26.3/lib/image_optim/runner.rb:54:in `initialize'
/var/lib/gems/2.5.0/gems/image_optim-0.26.3/bin/image_optim:17:in `new'
/var/lib/gems/2.5.0/gems/image_optim-0.26.3/bin/image_optim:17:in `<top (required)>'
/usr/local/bin/image_optim:23:in `load'
/usr/local/bin/image_optim:23:in `<main>'_

Which version of image_optim should I install?

**Comment by kostjaz** [comment]
OK, my solution for that:

vi Gemfile
gem "image_optim", "~> 0.25"
gem "image_optim_pack", "= 0.2.3"

sudo gem install image_optim
sudo gem install image_optim_pack
sudo apt install -y npm nodejs

sudo npm install -g svgo
sudo ln -s /usr/bin/nodejs /usr/bin/node

**Comment by tomhughes** [comment]
Those are just warnings and you can ignore them.
