### ISSUE TITLE
<iframe> scrolling attribute not supported in HTML5

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2214]
In the **Share** panel
```
paste HTML to embed in website
```
produces an <iframe> with scrolling attribute which is not supported in HTML5. "Use CSS instead."

Also looking in the browser console, we see

> embed-3828c...js:1 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by HolgerJeromin** [comment]
Both are not related

**Comment by jidanni** [comment]
OK, next time I will file two separate bugs.

**Comment by tomhughes** [comment]
In this case you don't need to as the second one is coming from leaflet I think so outside our control.

It's just a performance hint anyway, and I believe in this case probably not relevant as there shouldn't be any scrolling but it's a matter for https://github.com/Leaflet/Leaflet/issues anyway.

**Comment by mmd-osm** [comment]
I cannot find a scrolling attribute in the generated iframe html code:

```
<iframe width="425" height="350" src="https://master.apis.dev.openstreetmap.org/export/embed.html?bbox=36.80516749620438%2C-1.2689673473685381%2C36.80974334478379%2C-1.2646125045500682&amp;layer=mapnik" style="border: 1px solid black"></iframe><br/><small><a href="https://master.apis.dev.openstreetmap.org/#map=19/-1.26679/36.80746">View Larger Map</a></small>
```

**Comment by AntonKhorev** [comment]
The attribute was removed in https://github.com/openstreetmap/openstreetmap-website/pull/4120
