### ISSUE TITLE
OpenStreetMap listens on TCP not on HTTP

### ISSUE THREAD

**Issue by YuriiNskyi** [openstreetmap/openstreetmap-website#2220]
I am using Ubuntu 18.04.2 LTS.

I have executed:

    git clone  https://github.com/openstreetmap/openstreetmap-website.git osm-repo
    cd ./osm-repo
    vagrant up

Despite the fact that something was wrong with Vagrant's SSH [(here's an example)](https://github.com/hashicorp/vagrant/issues/1659), I can successfully execute `vagrant ssh`, and now I'm in the OSM's VM.

Here's what happens when executing `bundler exec rails server`:

> => Booting Puma
> => Rails 5.2.3 application starting in development 
> => Run `rails server -h` for more startup options
> pngcrush worker: `pngcrush` not found; please provide proper binary or disable this worker (--no-pngcrush argument or `:pngcrush => false` through options)
> advpng worker: `advpng` not found; please provide proper binary or disable this worker (--no-advpng argument or `:advpng => false` through options)
> optipng worker: `optipng` not found; please provide proper binary or disable this worker (--no-optipng argument or `:optipng => false` through options)
> pngquant worker: `pngquant` not found; please provide proper binary or disable this worker (--no-pngquant argument or `:pngquant => false` through options)
> jhead worker: `jhead` not found, `jpegtran` not found; please provide proper binary or disable this worker (--no-jhead argument or `:jhead => false` through options)
> jpegoptim worker: `jpegoptim` not found; please provide proper binary or disable this worker (--no-jpegoptim argument or `:jpegoptim => false` through options)
> jpegtran worker: `jpegtran` not found; please provide proper binary or disable this worker (--no-jpegtran argument or `:jpegtran => false` through options)
> gifsicle worker: `gifsicle` not found; please provide proper binary or disable this worker (--no-gifsicle argument or `:gifsicle => false` through options)
> svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
> Puma starting in single mode...
> * Version 3.12.1 (ruby 2.5.1-p57), codename: Llamas in Pajamas
> * Min threads: 5, max threads: 5
> * Environment: development
> * Listening on tcp://localhost:3000
> Use Ctrl-C to stop

That's the problem. Correctly, there are two problems:

1. What should I do with those workers?
2. Why OSM listens on TCP? Absolutely every source says that it must listens on HTTP protocol, not on TCP. Maybe it is connected with these workers.

**Comment by gravitystorm** [comment]
The workers are optional, so don't worry about them for now.

The message from Puma is perhaps misleading. Have you tried visiting http://localhost:3000? Does that work?

**Comment by mmd-osm** [comment]
This is pretty much working as documented: https://guides.rubyonrails.org/kindle/command_line.html#rails-server

I also have no idea why they put tcp in there, even the port supports http on the application level.

**Comment by YuriiNskyi** [comment]
@gravitystorm no, that's the problem, http://localhost:3000/ doesn't work.

**Comment by mmd-osm** [comment]
Did you try the Vagrant container‘s ip rather than localhost?

**Comment by YuriiNskyi** [comment]
@mmd-osm I tried to determine IP with `ifconfig`:

> enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
>         inet6 fe80::79:31ff:fe3f:e183  prefixlen 64  scopeid 0x20<link>
>         ether 02:79:31:3f:e1:83  txqueuelen 1000  (Ethernet)
>         RX packets 512  bytes 49437 (49.4 KB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 391  bytes 49811 (49.8 KB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         inet6 ::1  prefixlen 128  scopeid 0x10<host>
>         loop  txqueuelen 1000  (Local Loopback)
>         RX packets 46  bytes 22765 (22.7 KB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 46  bytes 22765 (22.7 KB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

But unfortunately it doesn't work.

**Comment by mmd-osm** [comment]
Ok, localhost should work if you follow the steps in https://github.com/openstreetmap/openstreetmap-website/blob/master/VAGRANT.md

I think you forgot about the —binding parameter.

**Comment by YuriiNskyi** [comment]
Amazing, it works, thanks a lot!

Maybe add this parameter to [this article](https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md)?
