### ISSUE TITLE
Creating tiles with the rail port

### ISSUE THREAD

**Issue by kostjaz** [openstreetmap/openstreetmap-website#2230]
Hello.
I made the installation with the INSTALL.md, loaded the database with Osmosis and so on.
Can I create png tiles now or should install something else?

**Comment by simonpoole** [comment]
The rails-port is the code for the openstreetmap.org website, that is the UI and the editing API, not for generating map tiles which is a completely separate process. 

See https://switch2osm.org/serving-tiles/ and https://switch2osm.org/serving-tiles/ for more information.
