### ISSUE TITLE
API is giving incorrect history

### ISSUE THREAD

**Issue by nrg100** [openstreetmap/openstreetmap-website#2234]
When a way is viewed on the website, for example:

[https://www.openstreetmap.org/way/23014327/history](https://www.openstreetmap.org/way/23014327/history)

the correct tag history is shown.  Meanwhile, 

[https://www.openstreetmap.org/api/0.6/way/23014327/history](https://www.openstreetmap.org/api/0.6/way/23014327/history)

is showing the current set of tags duplicated for every version of the way instead of the correct history.

This is also affecting josm's history viewer, see: https://josm.openstreetmap.de/ticket/17760

**Comment by tomhughes** [comment]
Actually a cgimap issue (https://github.com/zerebubuth/openstreetmap-cgimap/issues/181) but worked around in production.
