### ISSUE TITLE
Hybrid map display layer, satellite plus OSM layer

### ISSUE THREAD

**Issue by Sowa1980** [openstreetmap/openstreetmap-website#2242]
Сделайте, пожалуйста, на сайте гибридный слой отображения карты, спутник плюс слой OSM, и что бы этот слой был доступен без регистрации при просмотре карты.

Please make on the site a hybrid map display layer, a satellite plus an OSM layer, and that this layer be available without registering when viewing the map.

**Comment by tomhughes** [comment]
We don't have imagery available for that, and even if we did it would be out of scope of the project - our goal is to support mapping, not to provide an end user google maps clone.
