### ISSUE TITLE
Filters display a particular information on the site

### ISSUE THREAD

**Issue by Sowa1980** [openstreetmap/openstreetmap-website#2251]
Filters display a particular information on the site. Let me explain, for example, I want to see only roads + landscapes + rivers, noting these two points I would only see this information and no other on the site. Very lacking at the moment of this tool.

Фильтры отображения той или иной информации на сайте. Поясню я хочу к примеру видеть только дороги + ландшафты + реки, отметив два эти пункта мне на сайте выводилась бы только эта информация и никакая другая.  Очень не хватает на данный момент данного инструмента.

**Comment by tomhughes** [comment]
This is not something that we are able to do with bitmap tiles - it might be possible if and when we ever move to vector tiles.

That said, it's not clear to me that there is any use for such a feature that fits with our mission of supporting mapping - it sounds more like a feature for end users.
