### ISSUE TITLE
Add tests for multiple gpx files in archives

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2254]
This was fixed in https://github.com/openstreetmap/openstreetmap-website/commit/ee458b6ee25b9a34ca0cb9841b17b6e155ebcc87 , but since it was a hotfix it didn't contain tests. We should add some tests to prevent the same problem from happening again in the future, and so I'm adding this ticket in order that we don't forget.

**Comment by tomhughes** [comment]
Yeah that was already on my to do list ;-)

It proved a bit more complicated than I would have liked because both the libarchive wrapper and the zlib reader are doing the file access directly from C and bypassing `FakeFS` so we have to partially work on the real filesystem
