### ISSUE TITLE
GPX Upload from Basecamp fails

### ISSUE THREAD

**Issue by woodpeck** [openstreetmap/openstreetmap-website#2258]
The following was received in an email by DWG from OSM user LightSpirit:

Since 13. Jun. 2019 the function of uploading of a exported GPX-File
from Garmin BaseCamp (V4.62 de) is broken. The OSM-Servers says in a
e-mail  "[OpenStreetMap] GPX-Import Fehler".

If i uploaded new a old GPX-File, that i have uploaded earlier days
successfully, i get the same error in a e-mail from OSM "[OpenStreetMap]
GPX-Import Fehler".

Can you fix the Problem.

I use a Garmin Oregon 700.

**Comment by tomhughes** [comment]
There's no point you copy and pasting the report - much better to refer them here so that we can interact with them.

There is nothing actionable here - we would need a copy of the trace to investigate and for that we need the person that is reporting the problem, not a proxy.

**Comment by woodpeck** [comment]
I have (referred them here), and asked them to participate in this discussion. I just found it more polite to already paste their report here, rather than just tell them "go to this other place and repeat everything there". That way I was able to give them a concrete ticket URL rather than a hand-wavy "please open a ticket on Github".

**Comment by tomhughes** [comment]
I'll reopen it for now then we but really need to know what the error was - the email should have had some details in the body - and also a copy of a trace we ca use to reproduce it.

**Comment by gravitystorm** [comment]
I've sent a (friendly) OSM message to the user, thanking them for reporting the problem and a) asking for the content of the email (in case it contains a backtrace) and b) asking for them to share a sample gpx file with me privately so that I can look at the problem.

**Comment by mmd-osm** [comment]
I could reproduce the issue:

Demo data: https://gist.githubusercontent.com/mmd-osm/578da03912f6b70d08131eaa13884090/raw/5a9c9ec7ed4ea4831a67678c92de573d750114b2/a.gpx

Error message:


> undefined method `type' for nil:NilClass /srv/www.openstreetmap.org/rails/lib/gpx.rb:54:in `rescue in points' /srv/www.openstreetmap.org/rails/lib/gpx.rb:47:in `points' /srv/www.openstreetmap.org/rails/app/models/trace.rb:287:in `each' /srv/www.openstreetmap.org/rails/app/models/trace.rb:287:in `each_slice' /srv/www.openstreetmap.org/rails/app/models/trace.rb:287:in `import' /srv/www.openstreetmap.org/rails/app/jobs/trace_importer_job.rb:5:in `perform' /var/lib/gems/2.5.0/gems/activejob-5.2.3/lib/active_job/execution.rb:39:in `block in perform_now' /var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks' /var/lib/gems/2.5.0/gems/i18n-0.9.5/lib/i18n.rb:268:in `with_locale' /var/lib/gems/2.5.0/gems/activejob-5.2.3/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>' /var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `instance_exec' /var/lib

**Comment by gravitystorm** [comment]
Yeah, I'd tracked it down to the Mimetype detection failing, but I was still waiting on getting the raw file to figure out what was triggering it. A byte order mark will definitely do it:

```
$ bundle exec rails console
Loading development environment (Rails 5.2.3)
irb(main):001:0> MimeMagic.by_magic(StringIO.new("<?xml>")).type
=> "application/xml"
irb(main):002:0> MimeMagic.by_magic(StringIO.new("\xEF\xBB\xBF<?xml>")).type
Traceback (most recent call last):
        1: from (irb):2
NoMethodError (undefined method `type' for nil:NilClass)
irb(main):003:0> 
```

**Comment by tomhughes** [comment]
So just make it `&.type` maybe? So we assume it's straight XML if we can't get the type?

**Comment by gravitystorm** [comment]
> So just make it `&.type` maybe? So we assume it's straight XML if we can't get the type?

Seems reasonable. It would be better if the mime type detection wasn't fooled by a BOM, but I haven't found any discussions on https://github.com/minad/mimemagic/ or in the upstream shared-mime-info to guide me towards better options.
