### ISSUE TITLE
HTML document can never receive a 304 Not Modified

### ISSUE THREAD

**Issue by alexkemp9** [openstreetmap/openstreetmap-website#2261]
*Background*    
Conducting a simple refresh (f5) on a recently downloaded [test map page](https://www.openstreetmap.org/way/17236956) causes only half (10 out of 21) of the files to give a `304 Not Modified`. Obviously *Not Good* both for the user (slow) plus OSM (increased bandwidth + load).

Some of those files may well be dynamic, but some are clearly static. Because of the wide range of *Response Header* symptoms + my ignorance these are individual file-type reports to allow those with a working knowledge of the code to decipher it all.

*The meat*    
An HTML doc based on a map *way*.    

- `Last-Modified`: not present    
- `eTag`: weak
- `Expires`: not present
- Request: `If-None-Match` (no match, so no 304)    
(I've checked that the way is unchanged & yet the `eTag` changes on every refresh. BUG!!!)

*Related*    
The tiles supplied by *toothless* (eg https://b.tile.openstreetmap.org/18/130245/85447.png) are also all dynamic yet all have a strong `eTag` (matched by the `If-None-Match`) + `Expires` and thus get cached + a 304.

*Extra*    
See bottom of [this Diary page](https://www.openstreetmap.org/user/alexkemp/diary/368814) for fuller details.

**Comment by alexkemp9** [comment]
Would it be possible to produce the html file as a static disk file (essentially a cached file), then let Apache serve it up in the ordinary fashion? Restrict such files to nodes/ways/relations with actual tags & yes, a lot of files, but that means nothing in these days of multi-terabyte disks.

**Comment by alexkemp9** [comment]
I forgot to make a note that since the tests mentioned were conducted the [`Last-Modified` value](https://github.com/openstreetmap/operations/issues/305) has been re-enabled & `eTag` disabled.

**Comment by tomhughes** [comment]
I have no idea what you're trying to report here that is different from your previous issue.
