### ISSUE TITLE
Certain Static (?) files can never receive a 304 Not Modified

### ISSUE THREAD

**Issue by alexkemp9** [openstreetmap/openstreetmap-website#2262]
*Background*    
Conducting a simple refresh (f5) on a recently downloaded [test map page](https://www.openstreetmap.org/way/17236956) causes only half (10 out of 21) of the files to give a `304 Not Modified`. Obviously *Not Good* both for the user (slow) plus OSM (increased bandwidth + load).

Some of those files may well be dynamic, but some are clearly static. Because of the wide range of *Response Header* symptoms + my ignorance these are individual filetype reports to allow those with a working knowledge of the code to decipher it all. Please also note that since these tests the [`Last-Modified` value](https://github.com/openstreetmap/operations/issues/305) has been re-enabled & `eTag` disabled.

*The meat*    
A disparate bunch of (probably) static files.    

- 3 x CSS    
eg [https://www.openstreetmap.org/assets/screen-ltr-….css](https://www.openstreetmap.org/assets/screen-ltr-56c86771fc241440e36145999d4069209b6ea9ce7e508d48090ae525920df422.css)
- 1 x GIF    
eg [https://www.openstreetmap.org/assets/searching-….gif](https://www.openstreetmap.org/assets/searching-d2110831ff86cb780e0911cd005e82482bfc71a0c626b56812ece6d52db2e6e0.gif)
- 3 x JS    
eg [https://www.openstreetmap.org/assets/application-….js](https://www.openstreetmap.org/assets/application-7dc66b028055a8a9bfe43cf7d19b6a06b3a64a54efcbb1ae996f40ae3d5209c1.js)
- 7 x PNG    
eg [https://www.openstreetmap.org/assets/directions-….png](https://www.openstreetmap.org/assets/directions-40b86df47e67e386cb848cb45095c340f45a8283778f9205e3ae9cc1b371dc65.png)
- 2 x SVG    
eg [https://www.openstreetmap.org/assets/osm_logo-….svg](https://www.openstreetmap.org/assets/osm_logo-0e91a8acd0a92c1bf14204322322e57c65c2a7e318fec6907252fed929b7d6d3.svg)

- `cache-control`: max-age=31536000
- `eTag`: not present    
- `Expires`: Mon, 15 Jun 2020 13:46:41 GMT
- `Last-Modified`: not present    
- Request: (no IM, INM, IMS, etc. so no 304)    

*Related*    
The tiles supplied by *toothless* (eg https://b.tile.openstreetmap.org/18/130245/85447.png) are all dynamic yet all have a strong `eTag` (matched by the `If-None-Match`) + `Expires` and thus get cached + a 304.

*Extra*    
See bottom of [this Diary page](https://www.openstreetmap.org/user/alexkemp/diary/368814) for fuller details.

**Comment by alexkemp9** [comment]
Just as with the [HTML doc report](https://github.com/openstreetmap/operations/issues/306) I missed out the value for the `cache-control` header. Here it is (same for all files AFAICT):

- cache-control | max-age=31536000

That is the header that should have been (but is not) on the HTML file. These files have everything that they need except for an `eTag` and/or `Last-Modified`.

**Comment by tomhughes** [comment]
Look if you have something sensible to report then please do so in a clear way.

**Comment by alexkemp9** [comment]
I edited the missing bits into the body of the report for clarity, but also added them as a comment so that it would be clear for you that there had been a change. As a newbie to these pages I'm doing the best that I can to get up to speed.

Now if you cannot stop being insulting I shall report these insults to attempt to get you removed. I've noticed that you go out of your way to insult every new person that comes along, so it is hardly surprising that you stop most people from getting involved.

You need to take yourself by the collar, walk yourself outside & sort yourself out. You are better than this, and this affair cannot afford someone in your position to behave in the way that you are currently behaving to me.

**Comment by tomhughes** [comment]
Look those are all static assets where we send a one year expiry (and now an irrelevant last modified).

There is nothing stopping your browser caching them so if it doesn't please complain to whoever write it, not to us.

I really don't don't know what you are asking me to do, and you're are not clearly stating what you expect me to do. Instead you are starting every report with a copy and pasted block of text instead of getting straight to the point of explaining how this report differs from all the others.

**Comment by tomhughes** [comment]
BTW as I explained we have etags disabled because that is what the authors of the framework we use reccomend.

I suspect that enabling them would be a bad idea because I think apache uses the inode as part of the etag and we are serving from multiple servers that would generate different etags.

**Comment by alexkemp9** [comment]
I'm going to assume that you are tired.

Yes, the server sends a `cache-control` + `expiry` but It does not matter, since it never sends either an `eTag` nor `Last-Modified` which means that the browser has no value to include with an `If-None-Match` nor an `If-Modified-Since` nor anything else.

> TomH
> (and now an irrelevant last modified).

If the server does not send a `Last-Modified` value, how the heck is the browser supposed to know what value to add to it's `If-Modified-Since` header?!!!

As I said at the top, I'm going to assume that you are tired.

**Comment by iandees** [comment]
The server sets a `date` header and a `cache-control` header, which is enough for the browser to cache with. For example, my browser sends an `if-modified-since` request header when reloading those links you include, causing the server to respond with a 304 regularly.

**Comment by alexkemp9** [comment]
Thanks for the info, *iandees*.

Did you investigate the headers under *Network* to see whether you had received the `Last-Modified` Response header? I'm sure that you noticed my notice of update under *Background* stating that TomH had re-enabled `Last-Modified` *after* my testing. After all, as I said in my response to Tom 20 minutes ago, your browser is going to have a hard time knowing what value for `Last-Modified` to include within `if-modified-since` unless the origin server had sent it. Which is the whole point of this series of reports.

Good to know that now it works. Hooray!
