### ISSUE TITLE
A Static (?) XML file can never receive a 304 Not Modified

### ISSUE THREAD

**Issue by alexkemp9** [openstreetmap/openstreetmap-website#2264]
*Background*    
Conducting a simple refresh (f5) on a recently downloaded [test map page](https://www.openstreetmap.org/way/17236956) causes only half (10 out of 21) of the files to give a `304 Not Modified`.

Some of those files may well be dynamic, but some are clearly static. Because of the wide range of *Response Header* symptoms + my ignorance these are individual filetype reports to allow those with a working knowledge of the code to decipher it all. Please also note that since these tests the [`Last-Modified` value](https://github.com/openstreetmap/operations/issues/305) has been re-enabled & `eTag` disabled.

*The Meat*    
(probably) a static XML file. This is similar (but different) to the [HTML file problem](https://github.com/openstreetmap/operations/issues/306)    

1 x XML    
eg https://www.openstreetmap.org/api/0.6/way/17236956/full

- `cache-control`: max-age=0, private, must-revalidate 
- `eTag`: none    
- `Expires`: none
- `Last-Modified`: none    
- Request: (cache, but no `eTag` nor `Last-Modified`, so no request headers, so no 304)    

*Related*    
The tiles supplied by *toothless* (eg https://b.tile.openstreetmap.org/18/130245/85447.png) are all dynamic yet all have a strong `eTag` (matched by the `If-None-Match`) + `Expires` + `Cache-Control` and thus get cached + a 304.

*Extra*    
See bottom of [this Diary page](https://www.openstreetmap.org/user/alexkemp/diary/368814) for fuller details.

**Comment by tomhughes** [comment]
API responses are not in any way static - they will vary as the underlying object is edited.
