### ISSUE TITLE
Provide GPX file url parameter the same way iD does

### ISSUE THREAD

**Issue by MRVDH** [openstreetmap/openstreetmap-website#2275]
When going to the iD editor you can supply a gpx url parameter that loads a custom pink-colored trace into the editor. The HOT tasking manager and mappingnorthkorea.com use this.

I'd like to see this as a feature for the regular map as well. (or another way to supply a trace)

Example:
https://www.openstreetmap.org/edit?editor=id&#map=13/40.43086/124.85977&gpx=https://mappingnorthkorea.com/api/sector/generate/5c93aebb02ed1b2be46dbcfe.gpx

![image](https://user-images.githubusercontent.com/6686385/59981548-40f03e00-9605-11e9-93de-9fbe7d6f2948.png)

**Comment by tomhughes** [comment]
The goal of the web site is to assist users in mapping the world - can you explain how this feature would further that goal?

Note that the web site explicitly does not aim to support end users, in other words just to be a useful way of displaying general geodata.

**Comment by MRVDH** [comment]
For a similar reason as to why you can link to OpenStreetMap with a marker. https://www.openstreetmap.org/?mlat=40.4566&mlon=124.9024#map=13/40.4566/124.9024&layers=N

But instead of pointing to a specific location you point to an area. Useful for tools like the HOT tasking manager, mappingnorthkorea and probably other tools like it where you want to show an area with all nodes, ways etc inside a specific polygon.

**Comment by mmd-osm** [comment]
Something similar was already requested here: #387

**Comment by tomhughes** [comment]
Closing as a duplicate then.

**Comment by MRVDH** [comment]
@mmd-osm @tomhughes 
Actually, that is not a duplicate, that is a different feature. This is not a request for displaying existing GPS traces, this is a request for providing a gpx file to the map. Not for uploading but just for viewing boundaries.

**Comment by tomhughes** [comment]
It's asking for the ability to display a trace overlaid on the map, which is what you're asking for I think?

**Comment by tomhughes** [comment]
Oh you mean a trace from a third party server? I think that is definitely out of scope.

Even the ability to link to the map with a marker that you referred to is pretty dubious in terms of our mission - it's not clear it has any use as a mapping tool and is mostly used by people wanting to publish OSM maps with a marker on.

The only place it might make sense I guess is in the embed tool, which is specifically aimed at displaying maps on third party sites.

**Comment by MRVDH** [comment]
Fair enough! :)
