### ISSUE TITLE
Display a link for wikimedia_commons keys

### ISSUE THREAD

**Issue by Hjart** [openstreetmap/openstreetmap-website#2277]
I'm often using [wikimedia_commons](https://wiki.openstreetmap.org/wiki/Key%3Awikimedia_commons) as an alternative to the source tag.

As an example, I had discovered [this image](https://commons.wikimedia.org/wiki/File:Sylter_Rad.jpg), but didn't know the exact position of the wheel. 2 weeks later I notice someone [mapping it](https://www.openstreetmap.org/node/6551616404/history) with an incorrect name and then correct/complement his edits and link to the image as proof.

Right-clicking on an wikimedia_commons tag in JOSM will show an option to open the image in a browser (which I find really usefull) and Overpass Turbo will show links with this tag, but of course far from everyone are familiar with these options, so I'm thinking an option to just click a link on the website would be really nice.

**Comment by tomhughes** [comment]
There are only about 16000 such tags in the entire OSM database. I'm really not sure that rises to the level of deserving special case treatment in the user interface.

**Comment by Hjart** [comment]
Well, I was hoping :-). I am aware that I'm a fairly advanced mapper in this respect and that the majority of the ~1000 tags in [Denmark](https://www.openstreetmap.org/relation/50046) alone were added by me, but I am starting to see other mappers add these tags too and the tags on [this tram museum](https://overpass-turbo.eu/s/Kfg) (added a few days ago) really appears to have sparked another mappers interest, so I thought it might be time to have a go at it.

**Comment by pyrog** [comment]
key [image](https://wiki.openstreetmap.org/wiki/Key:image) show link (for URL only, not for Wikimedia Commons filenames or groups).

Adding a link to all "pictures" tags will help new (and experimented) users to check the value, see easily and quickly the picture itself.

See also  #986, [Photo linking](https://wiki.openstreetmap.org/wiki/Photo_linking) on the wiki.

**Comment by matkoniecz** [comment]
Implemented in 2014 in not yet reviewed, merged or rejected #834

**Comment by 7tonin** [comment]
OpenStreetBrowser manages to display Wikimedia Commons filenames https://www.openstreetbrowser.org/

**Comment by dktue** [comment]
+1

Would love to see this on the openstreetmap.org-Website

**Comment by mstock** [comment]
I've rebased the branch from my pull request #834 which implements this today on the current `master` branch, and it still seems to work.

**Comment by pyrog** [comment]
See also #2405

**Comment by pyrog** [comment]
@tomhughes It's not a problem of **quantity**, but **quality** 😉 

More, if OSM website display a link for `wikipedia` and `wikidata`, why it can't display a link for `wikimedia_commons` ?

Also the number grow every month [18 739](https://taginfo.openstreetmap.org/keys/wikimedia_commons) in november vs **16000** in june.

See [w62280106](https://www.openstreetmap.org/way/62280106)

Because `wikimedia_commons` are not linked, OSM contributors add a redondant `image` with a long and human unreadable URL:
* image=https://upload.wikimedia.org/wikipedia/commons/6/68/Entr%C3%A9e_Station_M%C3%A9tro_JF_Kennedy_Rennes.jpg
* wikimedia_commons=[File:Entrée Station Métro JF Kennedy Rennes.jpg](https://commons.wikimedia.org/wiki/File:Entr%C3%A9e%20Station%20M%C3%A9tro%20JF%20Kennedy%20Rennes.jpg)

See [n3240845997](https://www.openstreetmap.org/node/3240845997)

**Comment by Bibi56** [comment]
@pyrog is right: if we want to keep the database tidy, we should remove the `image` tag. But as long as normal contributors won't see that `wikimedia_commons` refer do an image or want to be able to see the images they will add the duplicate again and again... something @mstock commented on 15 Nov 2014 in his PR... The 5-year anniversary is nearing!

**Comment by pyrog** [comment]
@Bibi56 I don't want to **remove** `image` tag 😉 
It is useful for pictures on other web site than wikimedia, mapillary…

But yes, if `image` contain link to wikimedia, flickr, mapillary… I suggest to use the appropriate tag :ami

**Comment by woodpeck** [comment]
I think the right logic to apply is *not* "OSM already displays links for X and Y so why not also display links for Z" but "the constant addition of new link targets shows that this is unmaintainable, so let us stop showing *any* links", and remove those we already have. This will also stop the nonsense link addition mentioned by @pyrog.

**Comment by pyrog** [comment]
> so let us stop showing any links

No links is clearer than some links 😉 

> the constant addition of new link targets shows that this is unmaintainable

In one hand, maintenance of software is difficult…
In the other hand, maintenance of the database is more difficult.

Yes, adding links to the software is difficult, but…

- contributors could send PR
- software could use a repository of pairs of regex/url to avoid rewriting the code each time a new link is needed
- this repository could be shared by several project (i.e. OSM, Overpass-Turbo, Osmose, Map of historical objects…)
- new links are not needed every days 😉 

>This will also stop the nonsense link addition

Adding link have **sense**.

[Again](https://github.com/openstreetmap/openstreetmap-website/issues/2405#issuecomment-544248520), it:
* lower the maintenance of OSM database
* help contributors and users to understand keys
* help to find POI on the field (i.e. fire hydrant)
* help to check mapping… 

PS: Adding link could be discussed/voted by the community.

**Comment by Hjart** [comment]
My primary reason for adding wikimedia_commons links is that they help build confidence in our data (well, at least I often feel more confident in our data, when i can easily find images showing the objects represented in our data). I think makíng it easier to show other mappers what some data object is supposed to represent, actually helps OSM.

**Comment by Bibi56** [comment]
> I think the right logic to apply is _not_ "OSM already displays links for X and Y so why not also display links for Z" but "the constant addition of new link targets shows that this is unmaintainable, so let us stop showing _any_ links", and remove those we already have. 

@woodpeck , please have a look at a [possible solution mentioned in #2405](https://github.com/openstreetmap/openstreetmap-website/issues/2405#issuecomment-548917729): that _would_ be a nightmare if it wasn't already maintained by others.

**Comment by tomhughes** [comment]
Pointing at a table in wikidata is not a "solution" at least not until somebody writes a pile of code to do something with it... History tells me not to rely on such things anyway as they invariably go away or change their API so every time you try and refresh from them you wind up having to rewrite the code that pulls from them.

**Comment by Bibi56** [comment]
Right, not fully maintenance free. But to be on the safe side you can store the result so when the automatic update would fail you could still use old format until it's updated.
Anyway the table can be saved as JSON or CSV and maintained locally if updating the mechanism is too work-intensive.

On the other hand, using a curated list (mentioning OSM tags) can help preserving the used format/data.

**Comment by tomhughes** [comment]
I really think it's a red herring - it's a table with a dozen or so entries and it doesn't really save anything over just hand coding the ones we want.

The real problem is that it outsources the decision about what we will or won't link to to a third party which I don't think is appropriate.

At the end of the day you can all talk as much as you want here but regardless of anything else nothing it going to happen until somebody steps up to write some code.

**Comment by Bibi56** [comment]
> nothing it going to happen until somebody steps up to write some code.

@tomhughes, when I see a [5-years old PR](https://github.com/openstreetmap/openstreetmap-website/pull/834) solving this request I doubt the main issue is writing the code.

> The real problem is that it outsources the decision about what we will or won't link to to a third party which I don't think is appropriate.

Here it's delegated to code maintainers. Is it better or worse than a community decision?

Please note that the table takes into account the fact that a tag exists in OpenStreetMap and tags creation under OpenStreetMap is a community decision made by OpenStreetMap contributors.

If you prefer a manual update just export the request in CSV or JSON and re-sync the file from time to time.

**Comment by tomhughes** [comment]
I'm not sure what the history of that PR is to be honest. I don't remember it and I don't appear to have looked at it for some reason. Most likely it came in at a time when I wasn't able to look at it and then it got forgotten about.

That said this has always been a controversial area because the more of these you add the more people will want and we probably want some sort of policy to avoid having to maintain code to add links for every obscure tag that could be linked.

**Comment by tomhughes** [comment]
Closed by merging #834.

**Comment by pangoSE** [comment]
> @Bibi56 I don't want to **remove** `image` tag 
> It is useful for pictures on other web site than wikimedia, mapillary…
> 
> But yes, if `image` contain link to wikimedia, flickr, mapillary… I suggest to use the appropriate tag

See https://wiki.openstreetmap.org/wiki/Automated_edits/pangoSE#Key:image for an suggestion to clean this up. There are [>80,000 image= tags with links to wikimedia_common](http://overpass-turbo.eu/s/Q1Z)s where 50,000 of them is in Germany alone.

**Comment by Bibi56** [comment]
@pangoSE, yes we are on the same page.
