### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by caduguedess** [openstreetmap/openstreetmap-website#2284]
Hi, in the cloning step I'm having this error:
`git clone git@github.com:openstreetmap/openstreetmap-website.git`

```
Cloning into 'openstreetmap-website'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Anybody knows how to adress this issue?
Thanks

**Comment by tomhughes** [comment]
Don't use ssh unless you have have a valid ssh key on file with github, use https instead.

**Comment by caduguedess** [comment]
Sorry if its a newbie question, but how I use https?

**Comment by tomhughes** [comment]
See https://help.github.com/en/articles/cloning-a-repository.
