### ISSUE TITLE
attempting to login using previously unused gmail account gives application error 500

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#2286]
Discovered during UX testing of one of OSM editors.

Screenshot after attempted login on a mobile Chrome: https://user-images.githubusercontent.com/899988/60381621-d3566e80-9a57-11e9-9e73-60bca2d24b7c.png

I (and user) would expect redirect to a registration page with prefilled data.

Reloading page revealed prefilled registration form.

**Comment by tomhughes** [comment]
This is an operational issue caused by an IPv6 routing bug. I'll patch it up again.
