### ISSUE TITLE
Simpler login page for people using login via Google, especially on mobile

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#2287]
Someone deciding to log in via Google account is assuming (at least among people that I tested) to skip most of registration form and use Gmail email as email, to not fill password.

Even selecting displayed user name may be surprising.

Would it be possible to offer simpler registration form for someone deciding to use a third party provider? For example there is no need to ask about email for someone registering via Google account, there is no need for them to create password (the may still reset password to setup one if it would be required for some purpose).

Discovered to be a major barrier during UX testing of one of OSM editors. My sample size is extremely small but people were extremely surprised to see password, email, username form after deciding to authenticate with Google.

note that on mobile unneeded forms take valuable screen space - see https://user-images.githubusercontent.com/899988/60381710-6e9c1380-9a59-11e9-98e5-d5a7ee4005dc.png

**Comment by tomhughes** [comment]
We do prefill things based on the OAuth, including the email for trusted providers like gmail, and setting a password is optional in that case.

**Comment by deevroman** [comment]
It seems that the results of the study were ignored https://github.com/streetcomplete/StreetComplete/issues/1470
I especially recommend paying attention to the comment https://github.com/streetcomplete/StreetComplete/issues/1470#issuecomment-526317818
I can also confirm from the experience of my friends that the current behavior is annoying. https://www.openstreetmap.org/user/TrickyFoxy/diary/399621

And I did not understand what the problem is to ask the user only the nickname and not show a huge form that the user does not expect.

**Comment by matkoniecz** [comment]
> It seems that the results of the study were ignored https://github.com/streetcomplete/StreetComplete/issues/1470

Given that it was small scale, was not requested by developers here and was not very rigorous, this is not too surprising by itself.

**Comment by tomhughes** [comment]
I'm not sure why we would even be expected to be aware of it given as far as I know it was never bought to our attention, or why UX testing of an unrelated app would be relevant to us.

**Comment by deevroman** [comment]
Translated it inaccurately. Let's mark the conversation about this as an offtop and get back to the problem.

**Comment by deevroman** [comment]
Stop-stop:) Return my first message. I corrected the translation error about the study. This did not cancel the question.

**Comment by tomhughes** [comment]
Make up your damned mind. This is a closed bug anyway and the explanation given when it was closed still applies.

**Comment by deevroman** [comment]
> We do prefill things based on the OAuth

"And I did not understand what the problem is to ask the user **only the nickname** and not show a huge form that the user does not expect."

**Comment by tomhughes** [comment]
Maybe we could cut down on the hyperbole?

There are exactly six fields on this "huge" form and the only ones not prefilled when signing up via google are the username (kind of important) and the password.

**Comment by deevroman** [comment]
Six fields or one 🤔 Especially on the phone

> Maybe we could cut down on the hyperbole?

Maybe. 
Three fields are not filled in, two can be edited. And the form is also inconvenient https://github.com/openstreetmap/openstreetmap-website/issues/3546

One inscription with mail and a nickname input field. That's all you need.

I also quote a comment: https://github.com/streetcomplete/StreetComplete/issues/1470#issuecomment-526317818

```
Main problem with registration form is not layouts bugs but massive length.

There is a good reason why registration on a typical site is quite simple (at least in cases where organization want people to register). Especially people using "Login with X" are not expecting to see massive registration form. Yes, many of fields are optional, but it is not clear to people registering.

One of main complaints was about selecting password anyway after using "register with X"
```

**Comment by deevroman** [comment]
And let's see what it looks like on the phone.

1. not "huge"? But you still need to scroll to the Register button
2. How should the user understand that a password is not required?

<img src="https://user-images.githubusercontent.com/25708359/180648277-f3b46b83-567e-4bd0-9aca-13965e1506f4.png" width=30% height=30%>

**Comment by AntonKhorev** [comment]
"With third party authentication a password is not required, but some extra tools or server may still need one." - what are those "extra tools or server"?

**Comment by tomhughes** [comment]
Well we want to phase it out but for the moment HTTP basic authentication is still supported for API clients and there are tools which use it, and that requires a password.
