### ISSUE TITLE
Hide header image on registration form on mobile

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#2288]
On my phone over 1/3 of the screen on registration form is taken by image not needed there.

It would be better to hide it on the mobile - https://user-images.githubusercontent.com/899988/60381710-6e9c1380-9a59-11e9-98e5-d5a7ee4005dc.png

Tested with Chrome on Xiaomi Redmi 4.

**Comment by simonpoole** [comment]
I've tried to recreate the obvious layout brokenness with three different browsers (including chrome) on Android and didn't see anything that looked like your screenshot. Do you have any font size or zoom settings that are non-standard?

While the image is large, there isn't that much to fill out and at least for me there is no problem in using the form at all.

**Comment by matkoniecz** [comment]
I used Chrome from Google Play, on my phone. It is possible that my cheap "smart"phone is broken in a new exciting way, but the same layout was on phone of my fiend during UX testing (what triggered my bug reports).

**Comment by matkoniecz** [comment]
> While the image is large, there isn't that much to fill out and at least for me there is no problem in using the form at all.

The sad reality is that typical user has problems with scrolling. Significant part of people appear to be unable to reach parts of website that require scrolling. Note, my test had hilariously small sample size of 7, but it seems to echo public reports of larger UX tests. Note also that signup page of typical website has significantly less clutter than our form.

And in this case I suspect that it is not because because OSM website design is superior, unlike some other differences.

**Comment by westnordost** [comment]
I have a Sony Xperia Z1 Compact and it looks like this on my phone (Firefox)

**Landscape**
<img height="300px" src="https://user-images.githubusercontent.com/4661658/63966563-d42d7000-ca9b-11e9-8fb7-70028af206aa.png"/>

**Portrait**
<img width="300px" src="https://user-images.githubusercontent.com/4661658/63966570-d7c0f700-ca9b-11e9-96e4-7f9de8ab2552.png"/>

**Comment by AntonKhorev** [comment]
Shouldn't be happening after https://github.com/openstreetmap/openstreetmap-website/commit/523565fb21ba5fbbae50a1d1274ce3d00e164d36.

**Comment by matkoniecz** [comment]
closing then

**Comment by westnordost** [comment]
cool
