### ISSUE TITLE
E: Unable to locate package nodejs

### ISSUE THREAD

**Issue by caduguedess** [openstreetmap/openstreetmap-website#2289]
When I run the following command:
`sudo apt-get install libmagickwand-dev libxml2-dev libxslt1-dev nodejs`
It gives me the error at the tittle.
I'm using Ubuntu Bash in Windows 10 Home 64 bits.

**Comment by Firefishy** [comment]
@caduguedess Make sure you are running Ubuntu 18.04 ([WSL download is here](https://docs.microsoft.com/en-us/windows/wsl/install-manual)). Then make sure you run `sudo apt-get update` before running the `sudo apt-get install` command.

Tested and works for me. Re-open if still broken.

**Comment by caduguedess** [comment]
> 
> 
> @caduguedess Make sure you are running Ubuntu 18.04 ([WSL download is here](https://docs.microsoft.com/en-us/windows/wsl/install-manual)). Then make sure you run `sudo apt-get update` before running the `sudo apt-get install` command.
> 
> Tested and works for me. Re-open if still broken.

Thanks, it worked!
I suggest to put it in the INSTALL.md instructions, for the begginer Linux users (like me).

**Comment by trillionclues** [comment]
I was having this error too but a quick Google search brought me here. Thanks, this worked for me too

**Comment by nihatalluri** [comment]
"Thanks, it worked for me! Your contribution is greatly appreciated."
