### ISSUE TITLE
The Rails Port login

### ISSUE THREAD

**Issue by caduguedess** [openstreetmap/openstreetmap-website#2290]
Does The Rails Port have a login system like OSM, allowing several people to map together or its only for standalone purposes?

**Comment by woodpeck** [comment]
This is not a Q&A site but an issue tracker, where you report problems or request enhancements to the software. Go to help.openstreetmap.org or the "dev" mailing list at lists.openstreetmap.org/listinfo/dev if you want to ask questions about using the software. "The rails port" (an old name for this project here, openstreetmap-website) *is* the software that drives the OSM website, so yes, it has exactly the same login system as OSM.
