### ISSUE TITLE
Error in rake yarn:install

### ISSUE THREAD

**Issue by caduguedess** [openstreetmap/openstreetmap-website#2291]
![yarn2](https://user-images.githubusercontent.com/51020710/60389538-551abc00-9a99-11e9-8243-883066ad82c7.png)
In the following command:
`bundle exec rake yarn:install`
It gives me the error in the image.
I'm running Bash Ubuntu on Windows 10.

**Comment by tomhughes** [comment]
The documentation is a bit out of date - you need to install `libarchive-dev` and `libbz2-dev` with `apt-get`.

**Comment by caduguedess** [comment]
I did it, and now when I execute ` bundle exec rake yarn:install` it gives me:
`Yarn executable was not detected in the system.
Download Yarn at https://yarnpkg.com/en/docs/install`
Should I follow the bash instructions?

**Comment by tomhughes** [comment]
Installing yarn on Ubuntu is bit of a pain and hasn't been documented yet. Try this:

```
sudo apt-get install npm
sudo npm install -g yarn
```

**Comment by caduguedess** [comment]
Still didn't work.
But I found a solution at https://stackoverflow.com/questions/54087856/cant-find-gem-bundler-0-a-with-executable-bundle-gemgemnotfoundexceptio/54088452

I had to run `gem update --system`, then `bundle install` worked

**Comment by basilstr** [comment]
I have a similar problem.
I followed your recommendations, but nothing has changed.
what could be the problem? 
Help me, please

**Comment by gravitystorm** [comment]
@basilstr Please open a new issue, and describe exactly what problem you are seeing (please include any error messages).
