### ISSUE TITLE
Document yarn installation in install notes

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2295]
Refs #2209 and #2291 

We need to document how to install yarn on Ubuntu.

Neither of the currently in use LTS releases (16.04 and 18.04) comes with yarn as a package. There is a apt repo available (as per the [official yarn install notes](https://yarnpkg.com/en/docs/install#debian-stable) ) but it warns that the nodejs that comes with 16.04 is too old for yarn to work. So we might need to bump our minimum version of Ubuntu to 18.04 in order to avoid cascading complexity.

**Comment by tomhughes** [comment]
Even if we bump the requirement documenting how to install and use the apt repo is an awful lot of complication that I would prefer to avoid having to document :-(

The alternative is just to suggest npm installation of yarn?

**Comment by gravitystorm** [comment]
Fixed by 6e55d4c70dd664ca2c5225357eb3dff6c1af2837 (and some semi-deliberate ignoring the problem until the instructions became much easier!)
