### ISSUE TITLE
Email notifications should be RTLed

### ISSUE THREAD

**Issue by yarons** [openstreetmap/openstreetmap-website#2297]
Currently the text is a mess and the icons and lines are in the opposite direction.

The current message directionality:
![image](https://user-images.githubusercontent.com/406826/60573546-87ba0280-9d80-11e9-9216-14ab664925fb.png)

The desired message directionality:
![image](https://user-images.githubusercontent.com/406826/60574229-e3d15680-9d81-11e9-81b7-2ef892a125e5.png)

Please notice this is relevant to Hebrew, Arabic, Farsi and some other RTL languages.

**Comment by yarons** [comment]
Thanks a lot @tomhughes!
Is there a way I can try and send myself a test mail to see it's aligned correctly?

**Comment by tomhughes** [comment]
Not easily, no. I did send myself a load when implementing it though.

Actually I think if you use `https://www.openstreetmap.org/message/new/<user>` then you probably can - it's not a link you'll find anywhere on the site but I think it does work.

**Comment by yarons** [comment]
LOL Almost:
![image](https://user-images.githubusercontent.com/406826/60593439-6cb0b800-9dab-11e9-9998-e46729aae1c5.png)

The labels should be RTL (in CSS: `direction: rtl`) aligned (The punctuation is reversed, it looks like `?What` to us).

Also the logo has drifted away from the text and the user icon is on the other side.

**Comment by tomhughes** [comment]
I don't know what's going on there - the ones I sent myself (which admittedly where changeset and diary comment notifications) don't look like that.

There is a small glitch with the spacing between the logo and the word `OpenStreetMap` in my ones but nothing like that. The `rtl` is already specified by the `dir` attribute on the top level `html` element just as we do on the main site so I think whatever client you're using must be ignoring that :-(

**Comment by yarons** [comment]
@tomhughes 
LOL, most certainly, it's Google Web Interface :)

**Comment by tomhughes** [comment]
Not sure how you get the images at all then as I didn't think gmail would show inline images - it certainly doesn't seem to for me:

![image](https://user-images.githubusercontent.com/147741/60594439-e42b1b00-9d9c-11e9-91a0-02611e15caf8.png)

**Comment by tomhughes** [comment]
Not sure how you get the images at all then as I didn't think gmail would show inline images - it certainly doesn't seem to for me:

![image](https://user-images.githubusercontent.com/147741/60594564-26ecf300-9d9d-11e9-8de4-b23619f81db0.png)

**Comment by yarons** [comment]
I got the images, notice it's still in the wrong direction (not only the images, all the text is LTR yet left-aligned, which are different from one another).

I saw your changes, is there a way I can test some changes of my own without causing any chaos?

**Comment by tomhughes** [comment]
Setting the direction in CSS does seem to work in gmail:

![image](https://user-images.githubusercontent.com/147741/60594688-6a476180-9d9d-11e9-9cd7-5f02550153ae.png)

**Comment by yarons** [comment]
I'm sending another one, just a sec.

**Comment by tomhughes** [comment]
The latest changes aren't deploy yet - that test was with my dev box ;-) Just pushing them now but they'll take about half an hour to deploy.

**Comment by yarons** [comment]
Ohhh, I see.

Can you send it to my address as well so I can help you right on the spot?

Thanks :)

**Comment by yarons** [comment]
Merged? We're all good?
