### ISSUE TITLE
Bundle Install update

### ISSUE THREAD

**Issue by caduguedess** [openstreetmap/openstreetmap-website#2299]
Seems like the INSTALL.md part that says about bundle install is outdated.
With the `bundle install` command it gives an error
But using `gem install bundle` command it works.
![bundle](https://user-images.githubusercontent.com/51020710/60609843-f5722880-9d98-11e9-93f3-516a13a2b4d8.png)

**Comment by tomhughes** [comment]
Those are totally different commands that do different things - you need to install bundler and then use it to install the bundle.

I assume we are expecting it to have been installed from an OS package but that seems to have been missed out in the Ubuntu instructions (it is there in the Fedora ones) but maybe it used to be a dependency of ruby or something.

**Comment by tomhughes** [comment]
So `sudo apt-get install bundler` is what's missing. I'll add it.

**Comment by caduguedess** [comment]
Still didn't worked.
I found a solution at [](https://stackoverflow.com/questions/54087856/cant-find-gem-bundler-0-a-with-executable-bundle-gemgemnotfoundexceptio/54088452)

I had to run `gem update --system`
Then `bundle install` worked
