### ISSUE TITLE
broken date formatting

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#2301]
I opened https://www.openstreetmap.org/way/418346662 in Firefox 67.0.4 (64 bity) in language set to Polish, on Windows 10 computer

>  Edytowane {{PLURAL:10|miesiąc|10 miesiące|10 miesięcy}} temu przez David Reik 

has obviously broken text generation

**Comment by tomhughes** [comment]
Well that's something that needs to be taken up with TranslateWiki - they will have provided that to us.

**Comment by tomhughes** [comment]
@Nikerabbit can you investigate?

**Comment by tomhughes** [comment]
I see a number of places where these have "escaped" into our translations though not, oddly, that one. What I see is:

```
config/locales/ast.yml:      traces_waiting: '{PLURAL|one=Tien %{count} traza esperando pa xubir. Considere
config/locales/ja.yml:      description_with_count: '{{%{user}|GPX ファイルによる地 %{count}件と%{user}による地点%{count}件を含む{PLURAL|one=GPX
config/locales/nl.yml:      reports: '{{PLURAL | zero = Geen rapporten | één = 1 rapport |%{count} rapporten}}'
config/locales/tr.yml:      x_seconds: '{{PLURAL|one=1 saniye önce|%{count} saniye önce}'
config/locales/uk.yml:      traces_waiting: '{{PLURAL|one=%{count} ваш трек очікує завантаження на сервер.
```

Which I suspect are the result of people putting incorrect syntax on the TranslateWiki side which stopped it converting them to rails format properly during the export.

**Comment by Abijeet** [comment]
> @Nikerabbit can you investigate?

Hi @tomhughes,

Thanks for bringing this to our notice. Your suspicion is right. 

@Nikerabbit and I will take a look at this issue, and try to add some validations that will stop people from pushing incorrect plural translations.

Are there any other validations that you'd like us to add?

Ref issue: https://phabricator.wikimedia.org/T224025

**Comment by tomhughes** [comment]
A way to limit what things can be translated to would be food - the `html.direction` resource being translated to something other than `rtl` or `ltr` for example.

That and adding in variables in the translation that don't exist in english (often by translating the variable name).

**Comment by gravitystorm** [comment]
I think @tomhughes 3 suggestions cover everything that I can think of, namely:

* Avoiding incorrect templating ending up in the translations
* Restricting html.direction
* Preventing translation of variable names

I would also like to comment here that it would be nice to develop a workflow that involves translatewiki changes coming through as pull requests so that our test suite runs, rather than committing directly to master. I'd be happy to see such pull requests automatically merged when the tests pass. We've had a few times recently where problems with translations are automatically committed to master, causing CI failures, and this has knock-on effects when developers clone a non-working master; master needs fixing before any other work can be done, etc etc.

**Comment by Nikerabbit** [comment]
With regards to your last comment, we do not currently support pull requests. We have a mode where updates are pushed on a different branch that is also rebased on top of the source branch on every push.

**Comment by gravitystorm** [comment]
> We have a mode where updates are pushed on a different branch that is also rebased on top of the source branch on every push.

Do you have the ability to trigger a merge to master automatically after the CI passes for the branch? 

If not, then I think we can live with the current setup for the moment. I don't want to create lots of hassle manually merging the branch, just to avoid the occasional problem with the translations.

**Comment by Nikerabbit** [comment]
Hopefully, with the improved checkers we can avoid build-breaking issues in translations.

Our current model is that we execute a script that does exports en masse. It would require changing the model to able to wait or react to external events. That would be a much bigger change than adding in code that, after push, calls the GitHub API to create the pull request.
