### ISSUE TITLE
Warn user's commenting on notes when they are not logged in

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2303]
Please, do like Wikipedia does, warn the user they are "not logged in. Really proceed?" for various actions that are recorded in the database.
E.g., unintentional cases of #1543 would never happen again.

**Comment by gravitystorm** [comment]
Is there anything other than notes that this applies to?

**Comment by tomhughes** [comment]
I don't see how - is there anything else you can do while not logged in?

It would have helped if @jidanni had explained the context of his request in the original report because I had no idea until you mentioned notes. I realise the link would probably had made it clear but I hadn't got that far and it's always best to explain (succinctly) the background to a request.

**Comment by tomhughes** [comment]
The obvious problem here is that notes deliberately allow anonymous contributors and we don't want people to feel pressured into signing up.

That said, for follow up comments (as against opening notes) it is probably reasonable.

In fact I'd be inclined to say that only the initial opening of a note should allow anonymous contributions as followups are hopefully always by mappers - it  unlikely that an original anonymous contribute will come back with a followup.

**Comment by jidanni** [comment]
Yes please... even we with the best intentions only realize we screwed up when we get a mail:  
`Subject: [OpenStreetMap] An anonymous user has commented on a note you are interested in`

**Comment by pnorman** [comment]
I'd also agree with restricting anonymous users to new notes. In practice, I've not seen useful intentional comments from anonymous users, only people not logged in to their account or vandalism.

**Comment by HolgerJeromin** [comment]
The whole thing was discussed in #1543

**Comment by AntonKhorev** [comment]
What's left to do here? Add a warning when creating a note anonymously that you might want to login / sign up?

**Comment by mmd-osm** [comment]
Anonymous user see a yellow warning when they're trying to create a new note:

![image](https://github.com/openstreetmap/openstreetmap-website/assets/5842757/670503b8-5d42-4300-9709-c2e275192ad2)

Posting comments as anonymous user isn't supported anymore, and we're showing a message explaining the situation:

![image](https://github.com/openstreetmap/openstreetmap-website/assets/5842757/664c9331-5894-472f-9b7f-896a80ef4655)

-> nothing left to do. I'm closing this one.
