### ISSUE TITLE
OSM Forum: Allow log in via GitHub like main website

### ISSUE THREAD

**Issue by Chaz6** [openstreetmap/openstreetmap-website#2309]
I am creating an issue here because https://github.com/openstreetmap/openstreetmap-forum does not have an Issues tab.

When logging in at https://forum.openstreetmap.org/login.php it would be useful to be able to log in via GitHub (or any of the methods supported by the main website).

**Comment by tomhughes** [comment]
Something not having an issue tracker doesn't mean you can just randomly pick a different tracker and open a ticket there...

If the forum software supported it then https://github.com/openstreetmap/operations/issues would be the place to ask for it to be enabled but as far as I know the forum software doesn't support it so this is essentially an impossible request.

In addition there was a deliberate decision to tie forum and web site accounts together and this would break that link so would probably be unacceptable from a policy point of view anyway.

**Comment by tomhughes** [comment]
What is really needed of course is for the forum to use OAuth so that you can use github to login to the main site and have that carry over but again that is dependent on what the forum software supports.

**Comment by Chaz6** [comment]
I didn't mean to break the link between the website and the forum account, I meant so that signing in the website also signed you into the forum automatically.

**Comment by Chaz6** [comment]
I have opened an issue on the site you mentioned https://github.com/openstreetmap/operations/issues/312

**Comment by Chaz6** [comment]
By the way, you do have the facility to move bug reports within GitHub if it has been opened in the wrong place: https://help.github.com/en/articles/transferring-an-issue-to-another-repository
