### ISSUE TITLE
GPX Import success email should link to the trace 

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2310]
Let's have a look at the mail sent upon the upload of a trace,
> From: OpenStreetMap <web@noreply.openstreetmap.org>
> Subject: [OpenStreetMap] GPX Import success
> To: jidanni@jidanni.org
> Date: Mon, 15 Jul 2019 06:21:59 +0800
> 
> [1. text/html]
>     OpenStreetMap   OpenStreetMap
>      Hi,
> 
>      It looks like your GPX file Jun_25__2019_10_09_38_2019_06_25_10_09_38.gpx with the description s and the following tags: osmtracker loaded successfully with 28 out of a possible
>      28 points.
>    OpenStreetMap
> OpenStreetMap
> 
> [2. image/png; logo.png]

Let's take a look at those hyperlinks.

```
$ mech-dump --all file.htm 
--> Headers:
Content-Length: 2685
Content-Type: text/html
Last-Modified: Mon, 15 Jul 2019 07:46:26 GMT
Client-Date: Mon, 15 Jul 2019 07:50:42 GMT
X-Meta-Charset: UTF-8

--> Forms:

--> Links:
https://www.openstreetmap.org/
https://www.openstreetmap.org/
https://www.openstreetmap.org/

--> Images:
cid:5d2bab076ce95_3f302b1c623585b4100290@spike-08.openstreetmap.org.mail


```

Suggestions: Instead of three identical general links,
how about having links to
- https://www.openstreetmap.org/user/jidanni/traces
- https://www.openstreetmap.org/user/jidanni/traces/3047592
- https://www.openstreetmap.org/?mlat=24.228791&mlon=120.79456966#map=14/24.228791/120.79456966
- https://www.openstreetmap.org/edit?gpx=3047593
- etc.

**Comment by tomhughes** [comment]
It's kind of impossible to tell from your report exactly what it was that had those links but I suspect it was a logo or something in which case linking to the home page is kind of normal and appropriate.

It is of course a perfectly good idea to enhance the email with other useful links.

**Comment by jidanni** [comment]
Yes it was [image/png; logo.png]
P.S, I'm not getting notifications about your comments. Nor I suppose you of mine.
P.S.S., at least add a link to https://www.openstreetmap.org/traces .
