### ISSUE TITLE
Roll back host override on user avatar urls

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2319]
With 40ac2aa5280f46c0c8cf3676596334269ec2f696 I get a test failure, since `Settings.server_url` (used in the code) != `test.host` (expected by the tests).

With the parent of that commit, it works fine. I think the problem described in the comments in #2296 was fully fixed by the change from `url_for` to `polymorphic_url` in b911b45961165d64fba577d4cb87740d89ec6784. I found a ticket (https://github.com/rails/rails/issues/32948#issuecomment-390817882) that describes that `url_for` is expected to give relative urls (which is a documented quirk) whereas `polymophic_url` should give fully-qualified urls.

Since we us fully-qualified urls all over the place, without needing `Settings.url` each time, I think it will be safe to remove.

**Comment by tomhughes** [comment]
The reason for the second change was to make sure the links are to `www.openstreetmap.org` even if the API call is made to `api.openstreetmap.org`.

Why is `server_url` not `test.host` in your test environment? It is in mine...

**Comment by tomhughes** [comment]
Well actually it isn't but I'm sure the tests were getting that. Unless I forgot to run them after the second change?

**Comment by gravitystorm** [comment]
> The reason for the second change was to make sure the links are to `www.openstreetmap.org` even if the API call is made to `api.openstreetmap.org`.

Ah, understood.
