### ISSUE TITLE
Tool for tracking rollbacks of editing packages.

### ISSUE THREAD

**Issue by Sowa1980** [openstreetmap/openstreetmap-website#2323]
Please do.
Need a tool to control the package of edits.
Verification for each user, the packages of edits that he made according to his profile
the presence of each package in the OSM database, which are not listed would be displayed.
Those who will not be found, a message is displayed who rolled back, the reason: DWG or username from OSM.
Now there is no worthy tool that would allow you to follow the rolled back edits, who was rolled back and the cause of the rollback, in many cases, vandals and disagreeable users use this.
This information should be available on the site for each user.

Сделайте, пожалуйста.
Нужен инструмент контроля пакета правок.
Сверка по каждому пользователю, пакеты правок, которые он вносил согласно его профиля
на присутствие каждого пакета в базе OSM, каких нет выводился бы список.
Те которых будут не найдены, выдается сообщение кто откатил, причину: DWG или ник юзера из OSM.
сейчас нет достойного инструмента который позволял бы следить за откаченными правками, кем был совершен откат и причину отката, этим пользуются во многих случаях вандалы и не согласные пользователи в тихую.
Данная информация должна быть доступна на сайте по каждому пользователю.

**Comment by mmd-osm** [comment]
I'd say this is technically not feasible, as objects could be marked as invisible on the database (they never get deleted), although they haven't been reverted. Also, you could do partial reverts, further complicating this situation.

Some revert tools (e.g. https://github.com/woodpeck/osm-revert-scripts) already leave a comment in the changesets they have reverted.

If you want something similar for other tools like the JOSM reverter, you should create an issue on the JOSM trac instead.
