### ISSUE TITLE
Problem with rake db:migrate

### ISSUE THREAD

**Issue by kostjaz** [openstreetmap/openstreetmap-website#2324]
I'm trying to install a railport on my ubuntu 16.04 server, and got such a problem:

_rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedColumn: ERROR:  column users.active does not exist
LINE 1: SELECT  "users"."email", "users"."id", "users"."active", "us..._

How can I fix that?

[log_dbmigrate.log](https://github.com/openstreetmap/openstreetmap-website/files/3403821/log_dbmigrate.log)

**Comment by tomhughes** [comment]
I have no idea because it doesn't happen for us - every travis run does a migration from a clean database so we will soon know if something isn't working.

You need to figure out why your database doesn't have that column, because one of the earlier migrations should have created it.

**Comment by tomhughes** [comment]
Oh that's nothing to do with the `active` column so I have no idea why it's saying that - you just need to update your checkout is all.
