### ISSUE TITLE
App private key/value pairs for "Preferences of a logged on user"

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#2326]
https://wiki.openstreetmap.org/wiki/API_v0.6#Preferences_of_the_logged-in_user provides a mechanism to create/modify/delete user preferences in a (single user assigned) public key/value store.

Currently, there's no way to shield different apps from each other, i.e. one app could fetch details from another app, or even change/delete them.

I'm proposing to enhance User preferences by an "app private" flag with the option to store key/value pairs that are only accessible by a given app (via a registered OAuth key).

Existing key/value pairs need to be marked as  "public" by default. For new entries, the app can decide, if entries should be public or "app private".

When using Basic auth, only public key value pairs are accessible, while on OAuth, both public and "app private" key/value pairs are accessible, possibly with an additional attribute to indicate a "public/app private" status.

**Comment by simonpoole** [comment]
Considering that there are only a low one digit number of applications that use the facility at all (and I delvelop one of them and have unsuccessfully tried to motivate an other reasonably popular OSM app, maproulette, to use it for its API key), I find it a bit surprising that anybody is even considering spending time on expanding a facility nearly nobody uses.

**Comment by mmd-osm** [comment]
>  I find it a bit surprising that anybody is even considering spending time on expanding a facility nearly nobody uses.

I use this feature in overpass turbo to store at least 70 different queries, and find it pretty bad that just about any other app with access to user preferences can do just about anything with that data, including wiping all of it.

**Comment by tomhughes** [comment]
No comment on whether this is a good idea, but I'm not sure you need a flag - just a nullable column storing an application id which, if set, means that only that application can touch it.

You could even make it scope the names so that different applications could use the same names.

**Comment by simonpoole** [comment]
So you could have given this as a use case to start with. Not that I'm convinced that there is a big issue as the idea of a rogue app in our context would seem to be rather far fetched.

Note that the concept of per app prefs would not work imho (as in: be secure) it would have to be per client key.
