### ISSUE TITLE
GET api/0.6/user/:id causes internal server error

### ISSUE THREAD

**Issue by pa5cal** [openstreetmap/openstreetmap-website#2329]
When sending an API request for getting user information (https://www.openstreetmap.org/api/0.6/user/10141202) the server responses with a 500 internal server error.

Response header:
error: ActionView::Template::Error: ActiveStorage::InvariableError

So far, this only happens for the mentioned id.

I think this should be the following contributor:
https://www.openstreetmap.org/user/grabtaxi20

**Comment by tomhughes** [comment]
Yeah it's a known bug - it happens it the user has added a "picture" that isn't a real picture or is in an obscure format that Active Job doesn't know how to resize.

**Comment by tomhughes** [comment]
Yes they have an SVG image... I'll have a look and see what we can do about it.
