### ISSUE TITLE
User's profile image can break the access to OpenStreetMap

### ISSUE THREAD

**Issue by jgrocha** [openstreetmap/openstreetmap-website#2334]
Hi,

One user uploaded his photo as an *.eps image. There is no mechanism to prevent users from uploading *.eps images.

But afterwards, the user was not able to login (either in the desktop or mobile) and his account was not reachable.

Only with the support from @tomhughes we were able to see that an *.eps image was used in the profile.

May we prevent users from uploading this kind of problematic file formats? Can we restrict just to *.jpg, *.gif and *.png?

**Comment by tomhughes** [comment]
This was already fixed in 1addc078c0809ef591057980a7ab6cdab9891e44 as you are well aware.

**Comment by tomhughes** [comment]
Also as far as I know it won't have stopped them logging in, though most pages will have failed to render because once logged in it will try and put the user image in the top right.

Access via the API should certainly still have worked other than the user details call.

**Comment by jgrocha** [comment]
Wow! I didn't image that you already changed and merged the code! Too fast for my standards.

**Comment by tomhughes** [comment]
It is true that paperclip (which we were using for the images) had a validation to restrict the content type to genuine image types (though EPS was allowed as it is an image) but I'm not aware of any easy way to do that with Active Storage at the moment.
