### ISSUE TITLE
Support requests regarding bulgarian language

### ISSUE THREAD

**Issue by Abijeet** [openstreetmap/openstreetmap-website#2335]
There are a few support requests on Translatewiki.net regarding the Bulgarian language,

1. https://translatewiki.net/wiki/Support#About_.5B.5BOsm:Browse.created_html.2Fbg.5D.5D_56516
2. https://translatewiki.net/wiki/Support#About_.5B.5BOsm:Browse.closed_html.2Fbg.5D.5D_56517
3. https://translatewiki.net/wiki/Support#About_.5B.5BOsm:Browse.deleted_by_html.2Fbg.5D.5D_56518
4. https://translatewiki.net/wiki/Support#About_.5B.5BOsm:Browse.closed_by_html.2Fbg.5D.5D_56519

They are of similar nature. Example,

> What exactly is being closed here? Some unfortunate languages has genders for stuff that English does not have.

**Comment by tomhughes** [comment]
This is something that should be dealt with on TranslateWiki.

**Comment by Abijeet** [comment]
Hello @tomhughes 

Thank you for response. I opened an issue here since the [Reporting issues section](https://translatewiki.net/wiki/Translating:OpenStreetMap#Reporting_issues) on the [project page guides](https://translatewiki.net/wiki/Translating:OpenStreetMap) users to report issues here.

Regards,

**Comment by simonpoole** [comment]
I believe the question is where/what the object is on the website that is being created / closed / deleted so that the translators know which gender to use. I believe that is potentially a bit difficult without context.

**Comment by Abijeet** [comment]
> I believe the question is where/what the object is on the website that is being created / closed / deleted so that the translators know which gender to use. I believe that is potentially a bit difficult without context.

Indeed. Updating the message documentation (`qqq`) to clarify what the subject is in those messages should resolve the translator's doubt.

> Thank you for your response. I opened an issue here since the [Reporting issues section](https://translatewiki.net/wiki/Translating:OpenStreetMap#Reporting_issues) on the [project page guides](https://translatewiki.net/wiki/Translating:OpenStreetMap) users to report issues here.

After typing that out, I realized that this probably does not qualify as an issue per say.
