### ISSUE TITLE
"bundle exec rake test:db" failure

### ISSUE THREAD

**Issue by Legolash2o** [openstreetmap/openstreetmap-website#2337]
Hi, I've installed the latest Ubuntu release (18.04) and when running the "bundle exec rake test:db", I keep getting thrown the error below for each test.

I followed the guide to the letter. I did have to update gems as the "make" commands didn't work.
https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md

```
bin/rails test test/system/report_diary_entry_test.rb:37

E

Error:
ReportDiaryEntryTest#test_missing_report_params:
ArgumentError: The detector #<struct Cliver::Detector command_arg=nil, version_pattern=nil> failed to detect theversion of the executable at '/usr/bin/phantomjs'
    test/application_system_test_case.rb:25:in `block in <class:ApplicationSystemTestCase>'

Error:
ReportDiaryEntryTest#test_missing_report_params:
ArgumentError: The detector #<struct Cliver::Detector command_arg=nil, version_pattern=nil> failed to detect theversion of the executable at '/usr/bin/phantomjs'
```

![OSM Error](https://user-images.githubusercontent.com/34819291/62409511-8c1c4a00-b5d0-11e9-8c20-3f350c809868.png)

**Comment by tomhughes** [comment]
Seems like you have a broken phantomjs.

**Comment by tomhughes** [comment]
What does `phantomjs --version` say?

**Comment by Legolash2o** [comment]
It wouldn't display as it could find a screen ("X") to display. 

I removed phantomjs and then reinstalled after running:

sudo apt-get install build-essential chrpath
sudo apt-get install libfreetype6 libfreetype6-dev
sudo apt-get install libfontconfig1 libfontconfig1-dev phantomjs

Now it works apart form a few undefined is not a function jQuery error message.

**Comment by tomhughes** [comment]
Ah that's because Ubuntu's phantomjs is a bit broken and is built to require X for some silly reason.
