### ISSUE TITLE
Save map note overlay between edits

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/openstreetmap-website#2338]
Although not necessary, it would save some time and a few clicks if the main site saved the state of the map note overlay when editing things in iD Editor so the overlay would still be open when exiting the editor to browse the overlay on the main page again. Otherwise, it's a hassle to reactive notes repeatedly when doing minor quick edits.

**Comment by tomhughes** [comment]
Issues with iD need to be reported at https://github.com/openstreetmap/iD/issues not here.

**Comment by Adamant36** [comment]
My bad. I figured because the note system is activated before entering iD Editor and is reset on the styles side, instead of inside of iD Editor, that it would be a main site thing.

**Comment by tomhughes** [comment]
Well maybe I have misunderstood what you mean? Are you talking about the notes layer on the main site?

That is normally pretty sticky for me - usually I have the opposite problem and I'm constantly having to turn it off!
