### ISSUE TITLE
"bundle exec rake test:db" warnings

### ISSUE THREAD

**Issue by Legolash2o** [openstreetmap/openstreetmap-website#2339]
Following in from a previous issue which is now resolved.

I've just installed everything on Ubuntu 18.04, following the guide. During the test I receive many "undefined is not a function" messages and mentions of jQuery from the same file/method.

I can upload a screen later if required when I'm on my laptop.

![OSM Error2](https://user-images.githubusercontent.com/34819291/62419898-60f23300-b682-11e9-9366-0e881fc661e2.png)

**Comment by tomhughes** [comment]
Yeah that happens sometimes but I've never managed to figure out why. It's probably a test ordering thing as it doesn't always happen but it doesn't actually seem to cause any problems.

**Comment by Legolash2o** [comment]
It seems to be from the same file and method. I've attached a screenshot anyway.

**Comment by tomhughes** [comment]
I think what has happened is that a recent update to the bowser gem has changed the feature detection in some way... so it is causing noise when an ES6 method is used because phantomjs doesn't support it but we haven't loaded the polyfill.
