### ISSUE TITLE
Road with covered tag not rendered as underground

### ISSUE THREAD

**Issue by SuperFlomm** [openstreetmap/openstreetmap-website#2341]
Greetings, there is a road that has the covered=arcade tag:

https://www.openstreetmap.org/way/179451263
https://www.openstreetmap.org/way/702472365

However it does not render as an underground road. I tried to fix this by using the location=underground tag and connecting the road to the grass on top. This didn't work either.

It might work if I use tunnel=avalanche_protector instead, but that would technically be wrong as [there is literally a sign that calls it an arcade](https://images.mapillary.com/XmytaDZAb_9jBAB8ufWzlw/thumb-2048.jpg) (Galerie in German) and there are no avalanches to protect from.

**Comment by mmd-osm** [comment]
You're reporting this in the wrong repo. OSM Carto style which is handling the tile rendering rules is being discussed here: https://github.com/gravitystorm/openstreetmap-carto

**Comment by dieterdreist** [comment]
sent from a phone

> On 5. Aug 2019, at 02:36, SuperFlomm <notifications@github.com> wrote:
> 
> there is literally a sign that calls it an arcade (Galerie in German)


regardless this is the wrong place for the question, it is also factually wrong, an arcade in German is called Arkade or Bogengang and should generally have “arcs” (Bögen), i.e. its typically vaulted (gewölbt)
