### ISSUE TITLE
highway not used for route

### ISSUE THREAD

**Issue by paolobenve** [openstreetmap/openstreetmap-website#2351]
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=44.41202%2C8.90013%3B44.41662%2C8.85427#map=15/44.4140/8.8773 makes me pass through roads with a lot of traffic.

The correct route should use the "via Guido Rossa" (below), which is a highway, like in https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=44.40836%2C8.90264%3B44.41524%2C8.85077#map=15/44.4122/8.8767

**Comment by tomhughes** [comment]
We don't run the routing engine so you would need to report this to the people that do (in this case hat appears to be https://routing.openstreetmap.de/).

Most likely it's just an error in the data somewhere in which case sign up to edit the map and you can help fix it!
