### ISSUE TITLE
Progressive Web App Support

### ISSUE THREAD

**Issue by YeQais** [openstreetmap/openstreetmap-website#2361]
Please add PWA Support In OpenStreetMap Web Site
Thank you for your hard work

**Comment by tomhughes** [comment]
Well it might be more likely if you explained what "PWA support" is exactly...

**Comment by YeQais** [comment]
Progressive web applications (PWAs) are a type of mobile app delivered through the web, built using common web technologies including HTML, CSS and JavaScript. They are intended to work on any platform that uses a standards-compliant browser. Functionality includes working offline, push notifications, and device hardware access, enabling creating user experiences similar to native applications on mobile devices. Since they are a type of webpage or website known as a web application, there is no requirement for developers or users to install the web apps via digital distribution systems like Apple App Store or Google Play.

While web applications have been available for mobile devices for as long as mobile devices have existed, they generally lag behind native apps in terms of speed, features, and user adoption, especially on mobile devices. Among other features, the ability to work offline, previously only available to native apps, allows PWAs to perform much faster and to provide more features to help close the gap with native apps.

PWAs do not require separate bundling or distribution. Publication of a progressive web app is as it would be for any other web page. PWAs work in any browser, but "app-like" features such as being independent of connectivity, install to home screen and push messaging depend on browser support. As of April 2018, those features are supported to varying degrees by the Microsoft Edge, Google Chrome, Mozilla Firefox and Apple Safari browsers, but more browsers may support the features needed in the future.

**Comment by tomhughes** [comment]
Right, but that's a pretty vague description - marketing hype for the most part.

Is there some concrete change you are looking for? I mean taking the broad list of functionality there we have:

* Works on any platform that uses a standards-compliant browser, which is already pretty much the case.
* Works offline, which doesn't make much sense in the case of OpenStreetMap.
* Push notifications, which are extremely contentious in any case, but we can certainly look at that if you have a concrete proposal for where they would be useful.
* Device hardware access, which we do where it makes sense, like accessing device location on request, but again if you have concrete suggestions for changes we can consider them.

I think in summary this ticket is too vague to be useful, but if you have concrete suggestions for specific changes then please do raise them.

**Comment by HarelM** [comment]
Sorry to comment on a closed issue, do let me know if you prefer that I open a new one.
But I believe that the question if one want's to add OSM to the home screen on a mobile app should be disabled for the login screen/flow as this is used by third party apps and created a weird user experience.

**Comment by 1ec5** [comment]
Hi Harel, I’m confused about your comment. This issue seems to be asking us to add PWA support, whereas in IsraelHikingMap/Site#2164 you’re saying you want it to be removed. If you’re experiencing a specific workflow issue with the website as it exists, a separate issue would help us understand you better.

**Comment by HarelM** [comment]
I'll open a different one then. Thanks for the input.

**Comment by HarelM** [comment]
- I've opened the following issue: #6406
