### ISSUE TITLE
SOTM 2019 banner has text under 'x'

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/openstreetmap-website#2365]
The top-right corner of the image needs to be kept clear for the x.

![image](https://user-images.githubusercontent.com/1190866/64135165-89ad3b80-cd9a-11e9-9e42-2c77eacd52f2.png)

cc @Nakaner

**Comment by Andygol** [comment]
This looks like an obsolete issue. SotM 2019 has already taken place
