### ISSUE TITLE
Installation: couldn't find file 'settings.local.yml'

### ISSUE THREAD

**Issue by tordans** [openstreetmap/openstreetmap-website#2372]
I am following https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md#macosx and got to "Running the tests" https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md#running-the-tests which tells me:

```
Error:
BrowseControllerTest#test_read_node:
ActionView::Template::Error: couldn't find file 'settings.local.yml'
Checked in these paths: 
```

So following https://github.com/openstreetmap/openstreetmap-website/blob/c162c065c6f6db5dc584599f5639b296b627a165/config/initializers/config.rb#L9 I added an empty file in `config/settings.local.yml` which resolved the issue.

Should I check this file in or add a line to create it to the installation instructions?

**Comment by tomhughes** [comment]
Yes this is a known issue, but it's not clear what the best solution is - what you did certainly works but ideally it shouldn't be necessary and we're still looking for a way to resolve that. There are already tickets about this I believe.

**Comment by HolgerJeromin** [comment]
> There are already tickets about this I believe.

ref #2185
