### ISSUE TITLE
Add link to read changeset comment notifications

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2377]
1. User gets notification that "XYZ has commented on one of your changesets"
2. User clicks the link and replies to the comment.
3. Days later, User wants to take a second look, but nowhere on the website is a list of such read notifications kept. He has no way to get back to that changeset other than sifting through his hundreds of changesets, hoping he remembers which one too.

**Comment by gravitystorm** [comment]
See my comment at https://github.com/openstreetmap/openstreetmap-website/issues/2102#issuecomment-474798118

**Comment by aawiseman** [comment]
I think this would be a big improvement.

**Comment by danieldegroot2** [comment]
Duplicate of #1387

**Comment by mmd-osm** [comment]
Closing as duplicate of #1387.
