### ISSUE TITLE
8-Digit Hex Colour Code

### ISSUE THREAD

**Issue by guylamar2006** [openstreetmap/openstreetmap-website#2378]
Adding support for 8 digit HEX color codes to the colour, building:colour, and roof:colour tags so it'll show in the color preview.

**Comment by HolgerJeromin** [comment]
#1779 implemented 3 or 6 digit hex code. 
Not sure if the 8 digit (added alpha transparency) code should be supported. 
It is not mentioned on the [Wiki page](https://wiki.openstreetmap.org/wiki/Key:colour).

**Comment by mmd-osm** [comment]
This is still pretty niche at this time. We have less than 50 objects worldwide that use a 8 digit hex code. Query: https://overpass-turbo.eu/s/NIy

**Comment by mmd-osm** [comment]
Let's close this. The number of ways hasn't changed at all in the last 3 months, there's basically no adoption of this schema in any way.
