### ISSUE TITLE
Authorization through Google does not work

### ISSUE THREAD

**Issue by petrovnn** [openstreetmap/openstreetmap-website#2379]
It is currently not possible to log in to the site using Google (new users or existing ones)

![image](https://user-images.githubusercontent.com/1567284/65866228-2acce900-e37d-11e9-8374-e13811c2069d.png)

Tested on multiple devices and different accounts

**Comment by mmd-osm** [comment]
Press F5 (page reload) in your browser, when you see the "Application error" screen. If reload doesn't work the first time, try again. Sometimes it takes 5-10 attempts.

I'm aware that's a work around only. There's some weird issue here that needs to be properly fixed.

**Comment by tomhughes** [comment]
It's usually caused by routing issues over IPv6 to Google's authentication server.

@petrovnn Are you the same person that reported this to the operations address?

**Comment by tomhughes** [comment]
Actually on this occasion it looks to be a DNS issue resolving `oauth2.googleapis.com` but it appears to be intermittent and I'm not sure what the cause is or if it's something we can do anything about.

**Comment by petrovnn** [comment]
> @petrovnn Are you the same person that reported this to the operations address?

yes.

We are developing an application that you can enter using OpenStreetMap. But our users usually do not have an OSM account. 

I recommended users to go through Google. However, none of the users could do this and had to register (this is a very bad situation when you register on the project and cannot do this because of an error).

Maybe for now, disable authentication through Google?
Why is it needed if it does not work? Such authorization brings users only problems.

**Comment by petrovnn** [comment]
Google authorization still does not work. Will we temporarily disable this type of authorization?

**Comment by mmd-osm** [comment]
I tried twice in two different browsers today, and it always worked the first time.

**Comment by mmd-osm** [comment]
@petrovnn : is this problem still occurring on your end, can we close this issue? I'm still unable to reproduce it most of the time.

**Comment by petrovnn** [comment]
> @petrovnn : is this problem still occurring on your end, can we close this issue? I'm still unable to reproduce it most of the time.

The problem no longer reproduces. Google login works fine
