### ISSUE TITLE
Use created_at instead of updated_at for searching notes through the API

### ISSUE THREAD

**Issue by ENT8R** [openstreetmap/openstreetmap-website#2380]
Is there a specific reason why in
https://github.com/openstreetmap/openstreetmap-website/blob/83983bfc6a31c2da0af6f18137cd31ba40519191/app/controllers/api/notes_controller.rb#L301
the notes (via the `/api/0.6/notes/search` call) are sorted by their `updated_at` value?
Actually I can't really think of any reason right now as sorting it by `created_at` sounds a lot more plausible to me and that was actually the behaviour I would expect from that API call...

If there is a reason why `updated_at` is rather used than `created_at`, maybe it would be feasible to add another parameter specifying the wanted sorting value?

**Comment by tomhughes** [comment]
It's done so that notes which have been recently commented on rise to the top - basically so that the most recently active notes are returned.

**Comment by ENT8R** [comment]
I understand the use case for the main openstreetmap website, but there might be potentially other data consumers which rather want only to get notes sorted by their created_at value. 
So, would it maybe feasible to add another parameter to the API call specifying whether to sort the notes by their created_at value rather than updated_at?

**Comment by tomhughes** [comment]
Well of course it's feasible - patches welcome.
