### ISSUE TITLE
Strip leading blanks from search string

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2384]
If the user enters
```
 24.186781,120.876259
```
instead of
```
24.186781,120.876259
```
into the search box, search can't find it.

**Comment by mmd-osm** [comment]
Cannot reproduce here. Even with a dozen leading blanks, I'm still seeing the same search result as before:

![search1](https://user-images.githubusercontent.com/5842757/66255873-0318bf00-e789-11e9-892c-ae3d1465f5a6.png)

**Comment by tomhughes** [comment]
Agreed, this is not reproducible.

**Comment by Zverik** [comment]
<img width="345" alt="Screenshot 2019-10-06 at 14 45 57" src="https://user-images.githubusercontent.com/766031/66268637-0626b480-e848-11e9-9e85-1a009ad9c1ce.png">

I entered a non-breaking space instead of a regular one. I guess stripping code should account fo different kinds of spaces.

**Comment by jidanni** [comment]
Hmm, OK, at least
U+3000 IDEOGRAPHIC SPACE
wrecks it.
https://www.openstreetmap.org/search?query=%E3%80%8024.18169%2C120.86617
