### ISSUE TITLE
"GPS Traces" option on osm.org is not working

### ISSUE THREAD

**Issue by maraf24** [openstreetmap/openstreetmap-website#2388]
When clicked, https://www.openstreetmap.org/traces gives the following error:

"Application error
The OpenStreetMap server encountered an unexpected condition that prevented it from fulfilling the request (HTTP 500)

Feel free to contact the OpenStreetMap community if your problem persists. Make a note of the exact URL / post data of your request.

This may be a problem in our Ruby On Rails code. 500 occurs with exceptions thrown outside of an action (like in Dispatcher setups or broken Ruby code)"

**Comment by tomhughes** [comment]
Works fine for me.

**Comment by tomhughes** [comment]
Looks like it only fails in the polish locale - a translator has submitted a bad translation that the tests didn't catch.

**Comment by Zverik** [comment]
I get the same with /user/new page: maybe an issue with Russian translation?

**Comment by maraf24** [comment]
> Looks like it only fails in the polish locale - a translator has submitted a bad translation that the tests didn't catch.

Indeed - with en-US locale problem disappeared.
Thanks for workaround :)

**Comment by mmd-osm** [comment]
Error message is: translation data {:one=>"1 punkt", :few=>"%{count} punkty", :many=>"%{count} punktów"} can not be used with :count => 3,354. key 'other' is missing.

The translator needs to add another key "other" in the Polish translation:

```
    trace:
      pending: OCZEKUJE
      count_points:
        one: 1 punkt
        few: '%{count} punkty'
        many: '%{count} punktów'
        other: '%{count} punktów'          <<< missing (punkty or punktów?)  
```
See Polish plularization rules: https://github.com/svenfuchs/rails-i18n/blob/master/rails/pluralization/pl.rb

**Comment by tomhughes** [comment]
It's more complicated than that and I'm still looking into it - to start with for some reason I can't reproduce it in the console.

Also if you read those rules then `other` should never actually be triggered because every value will match one of the other rules first.

**Comment by tomhughes** [comment]
Aha. The count being passed when we do the lookup is a string so it fails all the tests and falls back to `other`.

**Comment by mmd-osm** [comment]
so that's like running the following on the console:

`I18n.with_locale('pl') do I18n.t('traces.trace.count_points', count: '123') end`

**Comment by tomhughes** [comment]
...and it's a string because we're trying to insert commas into it.

Which is why other locales don't treat it as a pluralisable string but somebody has added the subkeys to polish.

**Comment by mmd-osm** [comment]
I found the respective change in translatewiki: https://translatewiki.net/w/i.php?title=Osm%3ATraces.trace.count_points%2Fpl&type=revision&diff=9026163&oldid=8095532

**Comment by mmd-osm** [comment]
Doesn't inserting a thousands separator depend on i18n settings, too? I mean, some locales would probably want to insert a dot rather than a comma.

**Comment by tomhughes** [comment]
Yes indeed - just adding commas every three digits is not good. Looking at options for that...

**Comment by tomhughes** [comment]
The commafication goes all the way back to 9f8952b6ef681a544b9f817483ac21edda0961c7 but I don't see an easy way to localise it so I think I'll get rid of it for noe.
