### ISSUE TITLE
Cannot register a new user

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/openstreetmap-website#2389]
Russian locale, firefox 69 on fedora linux 30 and on macos. Clicking "register" on the website, entering whatever@mailinator.com for an email, long gibberish for a usename, and qwerty12 for a password. Expected: email confirmation sent. Actual: it prints "We cannot create an account for you. Please contact the webmaster."

**Comment by simonpoole** [comment]
isn't mailinator.com a throwaway mail site? If yes then it is likely simply in the black list, using it to sign up for OSM would be a violation of the ToU in any case.

**Comment by tomhughes** [comment]
Yes this is the expected behaviour for a blacklisted email domain.

**Comment by HolgerJeromin** [comment]
Perhaps the message can be optimised
