### ISSUE TITLE
Extend GPX API to allow user specific downloads in a bounding box

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/openstreetmap-website#2395]
Opening this to gauge interest (or objections :-)).

For the background see https://github.com/MarcusWolschon/osmeditor4android/issues/980

**Comment by MikeParfitt** [comment]
While exploring the UK, GPS traces are recorded on my tablet.  I also upload them from the tablet and update OSM using Vespucci from whatever hotel or B&B I am staying at - hence #980 referred to by Simon.  Sometimes I find that the pre-rendered GPS traces are too cluttered with other people's traces to easily spot my own - particularly if there is a feature that I want to add, or correct on OSM.

**Comment by mmd-osm** [comment]
Also reported in https://trac.openstreetmap.org/ticket/4054:

> As a note to anybody thinking about implementing this I would point out there are serious performance issues that need to be considered as each point has to be joined to the files table to find out who uploaded it.

**Comment by MikeParfitt** [comment]
As a retired SQL-server developer I understand the importance of not degrading the performance of everybody elses use of the existing tool.  If the track point retrieval tool is implemented via a stored procedure, then can an optional parameter can be added to supply a user id ?  If so, then the presence of a value in this parameter can be used to switch to  a new query whose optimisation is different and is driven from the files table by user before joining to the trackpoints table.  If the database server cannot accept optional parameters, then clone the existing query and create a new one.

**Comment by mmd-osm** [comment]
I just copied the text over from trac so that I can close the other issue. I wasn't expecting any implementation level discussion really.

**Comment by mmd-osm** [comment]
According to https://github.com/MarcusWolschon/osmeditor4android/issues/980#issuecomment-1059727857, this has been implemented in Vespucci in the meantime. I haven't checked the implementation. For anyone interested, please check the code for details or reach out to @simonpoole.

I guess we can close this issue.
