### ISSUE TITLE
Possible points needs pluralisation

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2397]
From https://trac.openstreetmap.org/ticket/5296

`notifier.gpx_notification.success.loaded_successfully` cannot be properly translated, since it doesn't allow plural forms. In the original ticket, Tom notes that there are two number interpolations in this string, although that might not be an issue since there's only one object ("points") that needs to be pluralised.

loaded_successfully: loaded successfully with %{trace_points} out of a possible %{possible_points} points.

**Comment by rubynho** [comment]
Hey @gravitystorm, I'd like to solve this issue!

**Comment by gravitystorm** [comment]
> Hey @gravitystorm, I'd like to solve this issue!

Great! Please make a pull request, and feel free to ask any questions.

**Comment by gravitystorm** [comment]
Fixed by #2431
