### ISSUE TITLE
/copyright/LANG works but /about/LANG doesn't

### ISSUE THREAD

**Issue by rory** [openstreetmap/openstreetmap-website#2402]
The copyright page (`/copyright`) can be translated into other languages with a URL. i.e. https://www.openstreetmap.org/copyright/de is it in German. But the About page ( `/about`) doesn't support this feature.

Is it possible to add that, so that one can provide a language specific 'about OSM' link?

**Comment by tankhiwale** [comment]
https://github.com/openstreetmap/openstreetmap-website/pull/2444
