### ISSUE TITLE
Add CORS header to trace/XX/data API ?

### ISSUE THREAD

**Issue by nlehuby** [openstreetmap/openstreetmap-website#2407]
For now, it is not possible to download a trace from osm.org inside a js application : calling `https://www.openstreetmap.org/trace/<trace_id>/data` in the browser won't succeed because CORS header 'Access-Control-Allow-Origin' is missing.

Is there a reason to forbid that ? The endpoint is already public and works even without authentication.

**Comment by tomhughes** [comment]
Well that is not API because if it was it would be a `/api/...` URL and then it would allow cross origin access.

Uae the API method instead and you'll be fine.

**Comment by tomhughes** [comment]
That's `/api/0.6/gpx/NNN/data` by the way.
