### ISSUE TITLE
Purpose of user.nearby database column?

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2417]
We currently have a "nearby" column in the users table, added in 2007:

```
#  nearby              :integer          default(50)
```
https://github.com/openstreetmap/openstreetmap-website/commit/0a8c26e596b40da6d428a5c91db0d815d13c89e4#diff-10aaef61b133f90c8313930f89fe7dac

Is this required for anything? The `User.nearby` code [doesn't appear to use it](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/models/user.rb#L199).

**Comment by gravitystorm** [comment]
Closed by https://github.com/openstreetmap/openstreetmap-website/pull/2439

**Comment by mmd-osm** [comment]
Related https://trac.openstreetmap.org/ticket/436
