### ISSUE TITLE
wikimedia_commons=Category:xxxx#/media/File:yyyy don't display image

### ISSUE THREAD

**Issue by pyrog** [openstreetmap/openstreetmap-website#2425]
Hi,

The link display the category page, try to open the image in media viewer but can't.

Example: [n4841942392](https://www.openstreetmap.org/node/4841942392)
* `wikimedia_commons=`[Category:Natural monument 6.33.831 in Wahlsburg#/media/File:Naturdenkmal_Landkreis_Kassel_6.33.831_2018-06-16_b.JPG](https://commons.wikimedia.org/wiki/Category:Natural%20monument%206.33.831%20in%20Wahlsburg#/media/File:Naturdenkmal_Landkreis_Kassel_6.33.831_2018-06-16_b.JPG?uselang=fr)

To fix this issue, remove `?uselang=#{I18n.locale}` at the end of the url string.

* `wikimedia_commons=`[Category:Natural monument 6.33.831 in Wahlsburg#/media/File:Naturdenkmal_Landkreis_Kassel_6.33.831_2018-06-16_b.JPG](https://commons.wikimedia.org/wiki/Category:Natural%20monument%206.33.831%20in%20Wahlsburg#/media/File:Naturdenkmal_Landkreis_Kassel_6.33.831_2018-06-16_b.JPG)

Regards,

https://github.com/openstreetmap/openstreetmap-website/blob/816ee8ec92735b5c80b382857953ac4325096a71/app/helpers/browse_tags_helper.rb#L119

**Comment by tomhughes** [comment]
Well no that is not the fix, the fix is to parse the URL and insert the parameter properly instead of assuming it can be appended.

**Comment by pyrog** [comment]
See Overpass-Turbo code 😉

**Comment by gravitystorm** [comment]
> KISS: See Overpass-Turbo code wink

This comment is too cryptic to understand. Could you provide some links or a fuller explanation please?

**Comment by pyrog** [comment]
KISS: [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) 😄

**Comment by gravitystorm** [comment]
> KISS: [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) smile

Thanks, but I knew that bit already. I'd really appreciate it if you could explain what you mean by "See Overpass-Turbo code", and also explain why your proposed change in #2426 is in direct conflict with what Tom has requested.

**Comment by pyrog** [comment]
Open the same node with OverpassTurbo: https://overpass-turbo.eu/s/NVM

Click on the `wikimedia_commons` link: It works 😎 
So I think that my fix is a fix 😉 

Of course it's possible to add `uselang=` parameter at the good place (before the `#`), but the code will be more complicated…
And without this parameter, wikimedia commons website also detect the user language 😉 

So please, don't break the KISS principle 😄

**Comment by pangoSE** [comment]
I propose we close this. I don't see any problems with the current behavior on osm.org. The links open just fine for me from both the node page and from the example on overpass. None of them have /#media/ in the url and this is also not desireable. We link to the commons page and from there you can open the media viewer/slideshow without problems AFAICS.

**Comment by pyrog** [comment]
> None of them have /#media/ in the url and this is also not desireable. 

👍
