### ISSUE TITLE
How to config Rails Log by current date for name

### ISSUE THREAD

**Issue by cuongnc5** [openstreetmap/openstreetmap-website#2436]
Now My log file very big(~ 18GB). I want to config to write log 1 file/1 day. How to i config them?

**Comment by tomhughes** [comment]
That's a question for rails people, not us.

It may also depend on the application/web server you are using and what log rotation tools your operating system provides.

There is nothing builtin to rails to do log rotation as far as I know - you just need to arrange to rename the file and then tell rails to restart so it opens a new log.
