### ISSUE TITLE
ActiveRecord::ConnectionTimeoutError (all pooled connections were in use)

### ISSUE THREAD

**Issue by nguyenhoangnhon** [openstreetmap/openstreetmap-website#2437]
Dear all,
When many users access to Openstreetmap, we get a following issue, Please help me fix this problem .
Thanks many .

ActiveRecord::ConnectionTimeoutError
could not obtain a connection from the pool within 5.000 seconds (waited 5.003 seconds); all pooled connections were in use

Extracted source (around line #201):

 msg = "could not obtain a connection from the pool within %0.3f seconds (waited %0.3f seconds); all pooled connections were in use" %
                  [timeout, elapsed]
                raise ConnectionTimeoutError, msg
              end
            end
          ensure

**Comment by nguyenhoangnhon** [comment]
This is my picture captured problem. 
https://ibb.co/n8myP08

**Comment by gravitystorm** [comment]
Unfortunately we only provide support for setting up your development environment. We don't have enough people here to offer support for production and scaling queries. 

You can ask your question on stackoverflow or similar online support forums, or check google for solutions related to this error message.
