### ISSUE TITLE
Edit with Remote Control blocked in Safari

### ISSUE THREAD

**Issue by pyrog** [openstreetmap/openstreetmap-website#2445]
Editing with remote editor failed. It display the following message:
>Editing failed - make sure JOSM or Merkaartor is loaded and the remote control option is enabled

JOSM is running. It works fine with Firefox and Chrome.
Clicking directly on the following link work too (display Ok).

Console display this error message:
>Unrecognized Content-Security-Policy directive 'worker-src'.
>[blocked] The page at about:blank was not allowed to display insecure content from http://127.0.0.1:8111/load_and_zoom?left=-70.6644307209015&top=41.95700512499653&right=-70.65615190734864&bottom=41.95621870428267.

Safari Version 13.0.2 (14608.2.40.1.2) macOS Mojave (10.14.6)

See also https://github.com/hotosm/tasking-manager/issues/927

**Comment by tomhughes** [comment]
Sounds like a bug in Safari to me - the `worker-src` directive (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src) specifies valid sources for Worker, SharedWorker, or ServiceWorker scripts and as we don't use any of those we set it to `none`.

I have no idea why Safari has decided to apply it to an iframe load - we do add `http://127.0.0.1:8111` to both `frame-src` and `child_src` in our security policy which is the policy that should be used for such loads (`frame-src` is a newer replacement for `child-src`).

**Comment by tomhughes** [comment]
Note that the error message reported at https://github.com/hotosm/tasking-manager/issues/927#issuecomment-557806742 is different to what you have quoted here, namely:

> [blocked] The page at about:blank was not allowed to display insecure content from http://127.0.0.1:8111/load_and_zoom?left=-70.6644307209015&top=41.95700512499653&right=-70.65615190734864&bottom=41.95621870428267.

That message is refusing to do an http load from an https page which is also a bug/limitation in Safari - other browsers specifically exempt 127.0.0.1 from that restriction.

**Comment by mmd-osm** [comment]
Someone on the forum suggested, that Safari is keeping a HSTS pinning list, and once you've visited a localhost address via HTTPS, localhost will be added to that list. From that point onwards, Safari enforce HTTPS in the future and you will no longer be able to access localhost via HTTP.

The following blog posts describes a way to remove localhost in the HSTS pinning list. I haven't tried it, so ymmv: https://dev.to/tuacker/clear-saved-hsts-pinnings-in-safari-and-macos-9hd

**Comment by pyrog** [comment]
It doesn't work on my mac, even if I close Safari before, and even with `sudo`.

But it seem that the website coud disabled HSTS, for a particular website.
The server must send this header:
```php
header( 'Strict-Transport-Security: max-age=0;' );
```
See:
* **max-age set to 0** in [HTTP strict transport security: five common mistakes and how to fix them](https://www.scip.ch/en/?labs.20190214)
* [HTTP Strict-Transport-Security](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security)

**Comment by pyrog** [comment]
> Note that the error message reported at [hotosm/tasking-manager#927 (comment)](https://github.com/hotosm/tasking-manager/issues/927#issuecomment-557806742) is different to what you have quoted here, namely:

This a the same message. I just didn't copied the first error line (which seem not related to HSTS/Remote control  issue)

**Comment by tomhughes** [comment]
Neither of those error messages has anything to do with HSTS and in any case we're certainly not going to disable HSTS for everybody just so Safari can launch remote control requests!

**Comment by mmd-osm** [comment]
Hm, yes, the reasoning in that forum post seems a bit weird, and probably won't apply. After all, we're linking to 127.0.0.1, rather than localhost.

**Comment by pyrog** [comment]
Tom, please stay cool 😀

I just try with mmd-osm to understand what happened and how we could fix it.
Not for me, but for "basic" OSM contributors that couldn't understand what to do 😉

So if I understand, this header must be send by the remote editor (JOSM…)

**Comment by tomhughes** [comment]
Well the fundamental issue is that it's impossible to do unless the browser co-operates.

We can either load the remote control using https over port 8112 but then the browser will complain about the certificate that JOSM presents as it is not issued by an official certificate authority, or we can load using http over port 8111 but that will only work if the browser allows http loads to 127.0.0.1 from an https page.

Now we do in fact attempt to only use 8111 for Firefox and Chrome by the looks of it, and use 8112 for other browsers which don't exempt 127.0.0.1 from the mixed content checks, so I'm not entirely sure why you are seeing it load 8111 here.

**Comment by tomhughes** [comment]
If you know how you could try going to a javascript console on openstreetmap.org and evaluating this:

```
bowser.check({ chrome: "53", firefox: "55" })
```

and tell us what it says...

**Comment by pyrog** [comment]
On macOS:

Browser | message on the console
--|--
Firefox | `true`
Safari | `ReferenceError: Can't find variable: bowser`
Chrome | `Uncaught ReferenceError: bowser is not defined`

**Comment by tomhughes** [comment]
That's very strange. Were you on the front page each time? I've upgraded `bowser` now anyway, so could you try this:

```
bowser.getParser(window.navigator.userAgent).satisfies({ chrome: ">=53", firefox: ">=55" })
```

and this:

```
JSON.stringify(bowser.getParser(window.navigator.userAgent).parsedResult)
```

**Comment by pyrog** [comment]
Now I'am in https://www.openstreetmap.org

Browser | bowser.getParser
--|--
Firefox | true
Safari | undefined
Chrome | true

Browser | JSON.stringify
--|--
Firefox | "{\"browser\":{\"name\":\"Firefox\",\"version\":\"70.0\"},\"os\":{\"name\":\"macOS\",\"version\":\"10.14\",\"versionName\":\"Mojave\"},\"platform\":{\"type\":\"desktop\",\"vendor\":\"Apple\"},\"engine\":{\"name\":\"Gecko\",\"version\":\"20100101\"}}"
Safari |"{\"browser\":{\"name\":\"Safari\",\"version\":\"13.0.2\"},\"os\":{\"name\":\"macOS\",\"version\":\"10.14.6\",\"versionName\":\"Mojave\"},\"platform\":{\"type\":\"desktop\",\"vendor\":\"Apple\"},\"engine\":{\"name\":\"WebKit\",\"version\":\"605.1.15\"}}"
Chrome | "{"browser":{"name":"Chrome","version":"78.0.3904.108"},"os":{"name":"macOS","version":"10.14.6","versionName":"Mojave"},"platform":{"type":"desktop","vendor":"Apple"},"engine":{"name":"Blink"}}"

**Comment by tomhughes** [comment]
That all looks good then and I would expect it to use port 8112 for remote control on Safari, but that will provoke warnings about the certificate.

**Comment by tomhughes** [comment]
Hmm actually I think JOSM has stopped listening on 8112 in recent versions so we should maybe get rid of that fallback!

**Comment by grischard** [comment]
Yeah, JOSM doesn't listen on https anymore, as that was difficult to maintain, a source of many errors, and not required anymore in all modern browsers except Safari.

Safari still has a bug, but it will be fixed soon hopefully:

https://bugs.webkit.org/show_bug.cgi?id=171934

In the meanwhile, I'd use another browser that follows web standards.

**Comment by tomhughes** [comment]
I guess we should change https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/javascripts/index.js#L259 then to just unconditionally use http...

**Comment by gy-mate** [comment]
> Safari still has a bug, but it will be fixed soon hopefully:
> 
> https://bugs.webkit.org/show_bug.cgi?id=171934

IIUC Apple [doesn't want to remove this block](https://bugs.webkit.org/show_bug.cgi?id=171934#c96) due to security reasons until the [Private Network Access specification](https://wicg.github.io/private-network-access/) is accepted.
