### ISSUE TITLE
error 404 trying to delete my uploaded gpx-file.

### ISSUE THREAD

**Issue by magu01** [openstreetmap/openstreetmap-website#2453]
I try to delete a gpx-file i uploaded, from this URL.
https://www.openstreetmap.org/user/magu01/traces/3160302

Clicking "Delete this trace" redirects to 
https://www.openstreetmap.org/traces/3160302?method=delete

there i see error 404 file not found.

I think this POST method in HTML form in first URL-is missing /user/magu01/

Tryed it from Chrome and Internet Explorer in Windows 10. Same result.

I hope you can fix this.

**Comment by gabrielbaldao** [comment]
Can I try fix this?

**Comment by magu01** [comment]
I guess the function needs to be fixed, but what i really trying to do is to remove this track from the track-layer. But i found this closed issue. :(
https://github.com/openstreetmap/openstreetmap-website/issues/1945

**Comment by tomhughes** [comment]
It was a new issue introduced earlier today by 44c6fdc27340ead5e88ca60558978babf4baf2d9 which I have just pushed a fix for. It should be live in about half an hour.

**Comment by magu01** [comment]
Fixed and closed in 50 minutes! Respect :)

**Comment by gravitystorm** [comment]
> It was a new issue introduced earlier today by [44c6fdc](https://github.com/openstreetmap/openstreetmap-website/commit/44c6fdc27340ead5e88ca60558978babf4baf2d9) which I have just pushed a fix for. It should be live in about half an hour.

Sorry, that's completely my fault. I should have tested it manually, rather than relying on the test suite, since our tests don't involve actually pushing the buttons (or filling in the forms) on the site.
