### ISSUE TITLE
Remember me: be more forthcoming about how many days 

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2457]
On the login page there is a checkbox "[ ] Remember me".

OK but for how many days is a big secret.

Add a mouseover saying for how many days.

If the user knew it was supposed to remember for X days, but it didn't, then he could report a bug with confidence it was a bug.

**Comment by jidanni** [comment]
Else with no clarification, it means "remember me forever".

**Comment by jidanni** [comment]
One finds a cookie, _osm_session
Created Sunday, December 8, 2019 at 7:36:15 PM
Expires Sunday, January 5, 2020 at 7:48:20 PM
Therefore the mouseover should say "Remembers you for four weeks."

**Comment by jidanni** [comment]
So apparently, even if one opens their browser every day and browses the site, after the four weeks are up, one will find oneself suddenly logged out, perhaps. Anyway all this should be made clear in the mouseover, or nearby help button.

**Comment by jidanni** [comment]
As this is **Open**streetmap, one would expect all this to be out in the open.

**Comment by tomhughes** [comment]
I think it's actually broken. I think originally it was four weeks from the last time you used the site but the refresh of the expiry seems to have got lost and it is now four weeks from login.

**Comment by SilentSpike** [comment]
I can confirm that lately I've been getting logged out frequently with this checked (weirdly after even less than four weeks).

**Comment by tomhughes** [comment]
That is not related. I suspect that we're starting to run low on memory in the memcache store which will cause sessions to be evicted.

**Comment by jidanni** [comment]
@tomhughes: van you please turn my notifications back on. I am only getting notified about other peoples comments, not yours.

**Comment by gravitystorm** [comment]
> That is not related. I suspect that we're starting to run low on memory in the memcache store which will cause sessions to be evicted.

Is there anything we can do in this repo? Or should we move the ticket to operations?

**Comment by jidanni** [comment]
> I can confirm that lately I've been getting logged out frequently with this checked (weirdly after even less than four weeks).

Now it seems down to about a couple of days!

**Comment by tbertels** [comment]
> That is not related. I suspect that we're starting to run low on memory in the memcache store which will cause sessions to be evicted.

So the session keys aren't saved in the DB, only in memory?

**Comment by mmd-osm** [comment]
I think this is not actionable in this repo. In case there's still a need to bump the memcache size, please create a new issue on the operations repo instead: https://github.com/openstreetmap/operations

**Comment by jidanni** [comment]
Thanks, but which
https://github.com/openstreetmap/operations/issues/new/choose
category should I use?

**Comment by mmd-osm** [comment]
Open blank issue.

**Comment by jidanni** [comment]
OK but there they say:
> I definitely see the issue that you are referring to but I am unable it as all evidence says it shouldn't be down to memcache.

So maybe I should just be happy with however many days it remembers and give up trying to get it stablized.

**Comment by gy-mate** [comment]
_This issue is continued at https://github.com/openstreetmap/operations/issues/1107._
