### ISSUE TITLE
Fallback to english with missing translations

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/openstreetmap-website#2465]
I (german locale) just deleted a gps trace and got this success message:

translation missing: de.traces.destroy.scheduled_for_deletion:

![image](https://user-images.githubusercontent.com/2410353/70943061-3f518100-2050-11ea-8762-fa1d42c84da8.png)

Perhaps we should (additionally?) fall back to english text string.

**Comment by tomhughes** [comment]
We do - everything falls back to english.

**Comment by tomhughes** [comment]
That message doesn't exist in any locale.

**Comment by tomhughes** [comment]
Broken in 44c6fdc27340ead5e88ca60558978babf4baf2d9 when `delete` was renamed to `destroy`.

**Comment by gravitystorm** [comment]
@HolgerJeromin @tomhughes My apologies and my thanks for the fix.

@Nikerabbit this issue has highlighted a translation key renaming:

* `traces.delete.*` -> `traces.destroy.*`

**Comment by Abijeet** [comment]
Thanks for bringing this to our notice. This rename has been performed. 

We also recommend that you ping @translatewiki, when you would like to get our attention.
