### ISSUE TITLE
h2 smaller than h4 on info panel

### ISSUE THREAD

**Issue by Jez-C** [openstreetmap/openstreetmap-website#2467]
Example:
![h2_example](https://user-images.githubusercontent.com/42827689/71135706-43b99d80-21fa-11ea-8c2a-39cd5603cc06.png)

**Comment by gravitystorm** [comment]
Thanks for reporting, I’ll fix this shortly.

**Comment by Nakaner** [comment]
That's not the only case where the bug occurs. It's related to headings (h1, h2) in general, see https://www.openstreetmap.org/user/Nakaner/ for example.
