### ISSUE TITLE
Error 503 - Server unavailable

### ISSUE THREAD

**Issue by thomaskessler** [openstreetmap/openstreetmap-website#2468]
I have been trying to upload about 170 new or modified features and keep getting this error. I can download without problems. Prior to these recent problems, I have had no problem uploading (after ensuring to used secure URL that is).

Thx

**Comment by mmd-osm** [comment]
A few questions: Which editor are you using? What is your osm user name you used for uploads?

**Comment by thomaskessler** [comment]
Arcgis son editor v10.7.1 

Userid is tomk1932

Thx

On December 19, 2019, at 11:20, mmd <notifications@github.com> wrote:

A few questions: Which editor are you using? What is your osm user name you used for uploads?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/openstreetmap/openstreetmap-website/issues/2468?email_source=notifications">https://github.com/openstreetmap/openstreetmap-website/issues/2468?email_source=notifications</a>\u0026email_token=AGG66RO7NLEBSBSRBQLXWQ3QZPCQNA5CNFSM4J5M7MGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHKUU7Y#issuecomment-567626367", "url": "<a href="https://github.com/openstreetmap/openstreetmap-website/issues/2468?email_source=notifications">https://github.com/openstreetmap/openstreetmap-website/issues/2468?email_source=notifications</a>\u0026email_token=AGG66RO7NLEBSBSRBQLXWQ3QZPCQNA5CNFSM4J5M7MGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHKUU7Y#issuecomment-567626367", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]
