### ISSUE TITLE
Travis build failing on erblint

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2472]
I'm not sure why, but travis is failing on the erblint checks. The error messages are similar to this:

```
bundle exec erblint .
warning: parser/current is loading parser/ruby25, which recognizes
warning: 2.5.7-compliant syntax, but you are running 2.5.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

Linting 150 files with 12 linters...

Exception occured when processing: app/views/export/embed.html.erb
If this file cannot be processed by erb-lint, you can exclude it in your configuration file.
unrecognized cop Performance/RegexpMatch found in .erblint-rubocop20191219-5676-1lhc30m, unrecognized cop Rails/BulkChangeTable found in .erblint-rubocop20191219-5676-1lhc30m, unrecognized cop Rails/HasAndBelongsToMany found in .erblint-rubocop20191219-5676-1lhc30m, unrecognized cop Rails/HelperInstanceVariable found in .erblint-rubocop20191219-5676-1lhc30m, unrecognized cop Rails/NotNullColumn found in .erblint-rubocop20191219-5676-1lhc30m, unrecognized cop Rails/OutputSafety found in .erblint-rubocop20191219-5676-1lhc30m, unrecognized cop Rails/TimeZone found in .erblint-rubocop20191219-5676-1lhc30m
/home/travis/build/openstreetmap/openstreetmap-website/vendor/bundle/ruby/2.5.0/gems/rubocop-0.78.0/lib/rubocop/config_validator.rb:113:in `alert_about_unrecognized_cops'
/home/travis/build/openstreetmap/openstreetmap-website/vendor/bundle/ruby/2.5.0/gems/rubocop-0.78.0/lib/rubocop/config_validator.rb:44:in `validate'
/home/travis/build/openstreetmap/openstreetmap-website/vendor/bundle/ruby/2.5.0/gems/rubocop-0.78.0/lib/rubocop/config.rb:39:in `check'
/home/travis/build/openstreetmap/openstreetmap-website/vendor/bundle/ruby/2.5.0/gems/rubocop-0.78.0/lib/rubocop/config.rb:32:in `create'
/home/travis/build/openstreetmap/openstreetmap-website/vendor/bundle/ruby/2.5.0/gems/rubocop-0.78.0/lib/rubocop/config_loader.rb:54:in `load_file'
/home/travis/build/openstreetmap/openstreetmap-websit
...
```

When I run erblint locally, it prints warnings about the unrecognised cop names, but it doesn't throw errors like this.

I haven't found any bug reports, and it's not clear to me why this started occuring. Suggestions welcome!

**Comment by gravitystorm** [comment]
Ah, I was testing on an outdated master branch locally, that explains the discrepancy.

https://github.com/openstreetmap/openstreetmap-website/commit/aa7256d617748e94d1b6295debc58a14819f0eae included an update to rubocop 0.78, which [changes unrecognised cops from a warning to an error](https://github.com/rubocop-hq/rubocop/commit/ff811f0ca7971a6d121e53882130ee9fdee6d705). So a quick workaround would be to pin rubocop to 0.77 for now (and revert https://github.com/openstreetmap/openstreetmap-website/commit/09defac787a33f94579bb8afb43fd7dfda4ed311 for the moment too).

The deeper problem is that erblint doesn't appear to recognise the `Rails/*` and `Performance/*` directives. This is probably a consequence of them being moved out into separate projects. I suspect, but haven't yet tested, that erblint doesn't process [the 'require' directives in the rubocop config](https://github.com/openstreetmap/openstreetmap-website/blob/281d7992f857e7e7c64947a06470898c35035bb6/.rubocop.yml#L3-L5).

**Comment by tomhughes** [comment]
Yes I was assuming it was an erblint issue which is why I wasn't worrying too much about it.

It obviously does sort of know about them because it includes them in the config it generates, but then bombs when actually trying to use that config.

**Comment by tomhughes** [comment]
The problem is that erblint tries to do the inheritance from `.rubocop.yml` to `.rubcop_todo.yml` itself - so it sees the `inherit_from` and tries to load `.rubcop_todo.yml` using `RuboCop::ConfigLoader.load_file` but that won't load on it's own as it doesn't require the plugins.

Duplicating the requires in `.rubcop_todo.yml` works around it...
