### ISSUE TITLE
More compact URL for marker at center of map

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2478]
Maybe there could be a more compact way of writing URLs where the
lat,long of the marker is the same as the center of the map, and thus
repeated exactly, e.g.,
https://www.openstreetmap.org/?mlat=24.182383&mlon=120.874524#map=17/24.182383/120.874524
has unfortunate repetition it it as created via right panel "share".
Perhaps could be written in a way with each coordinate only mentioned once:
...```etmap.org/#map=17/24.182383/120.874524```**/m** ... I don't know.

Sure there are https://osm.org/go/... short URLs one can select. However they don't expose the lat,long in them so are "proprietary" and depend on the website still existing and cannot be salvaged later if not etc. etc.

**Comment by mmd-osm** [comment]
If you want a compact representation, simply use https://www.openstreetmap.org/?mlat=24.182383&mlon=120.874524

There's no need to provide the #map ... parts, it gets automatically added once you open up the map.

**Comment by eehpcm** [comment]
@mmd-osm 

> If you want a compact representation, simply use https://www.openstreetmap.org/?mlat=24.182383&mlon=120.874524

If you want an even shorter link, click on the "Short Link" button and get [https://osm.org/go/5ia_MGu--?m=](https://osm.org/go/5ia_MGu--?m=)

**Comment by jidanni** [comment]
> If you want a compact representation, simply use https://www.openstreetmap.org/?mlat=24.182383&mlon=120.874524
> 
> There's no need to provide the #map ... parts, it gets automatically added once you open up the map. By the way, the map gets centered on the marker's lat/lon value.

OK. Then that is what should be offered by the Share button!
P.S., @mmd-osm, please turn my comment notifications for you back on. Thanks.

**Comment by jidanni** [comment]
> If you want an even shorter link, click on the "Short Link" button and get https://osm.org/go/5ia_MGu--?m=

(Yes, but that has the proprietary problem mentioned earlier.)

**Comment by tuckerrc** [comment]
I am going to close this issue as resolved. 

A more compact URL can be generated by clicking "Share" and selecting "Short Link"

![image](https://user-images.githubusercontent.com/4624530/106682672-02688680-6591-11eb-86ee-420ff35cd973.png)

![image](https://user-images.githubusercontent.com/4624530/106682728-1ad8a100-6591-11eb-970f-ddec2f613a99.png)

**Comment by jidanni** [comment]
> If you want a compact representation, simply use https://www.openstreetmap.org/?mlat=24.182383&mlon=120.874524

Warning: Zoom level 12!
