### ISSUE TITLE
Add "just looking at maps" as legitimate choice on welcome message

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2479]
Upon first encounter with osm.org website,  users see: 
![X4](https://user-images.githubusercontent.com/1230959/71453383-f4f5a000-27c5-11ea-8b73-865fd3916e99.jpg)
This actually needs a third choice: "I just came here to look at some maps." (Which is in fact what the "X" at upper right is for. But it would be nice if it were somehow made explicit. So users could be assured they are using the site as intended, and not just "X"ing-away important instructions.)
No I don't know how to word it.
"Explore"? No, that seems like it will show you some volcanoes or Las Vegas. Maybe a good fourth choice.
"Browse" or "Just browse" seems better.

**Comment by tomhughes** [comment]
Well people who "just came to look at some maps" are explicitly not the target audience.

**Comment by gravitystorm** [comment]
Thanks for the suggestion @jidanni . However, we don't intend to make any changes along these lines.
