### ISSUE TITLE
голосования, за предложенные теги идеи на https://www.openstreetmap.org

### ISSUE THREAD

**Issue by Sowa1980** [openstreetmap/openstreetmap-website#2483]
голосования, за предложенные теги идеи на https://www.openstreetmap.org

Еще раз прошу рассмотреть данный вариант, так как на вики голосуют от силы 1% от всего числа пользователей, это нельзя назвать голосованием, многие даже не заходят в нее и не хотят разбираться , что и как там нужно сделать, что бы проголосовать, опять же , там нужна регистрация, что усложняет , вопрос голосования.
Прошу не закрывать данный билет. А рассмотреть ее более детально взвешенно и обдуманно.

**Comment by mmd-osm** [comment]
automated translation via deepl.com:

> voting for the proposed idea tags at https://www.openstreetmap.org.
> 
> Once again, please consider this option, because on wikis vote by force 1% of the total number of users, it can not be called a vote, many do not even go into it and do not want to understand what and how to do there to vote, again, there needs registration, which complicates the issue of voting.
> Please do not close this ticket. I'm asking you to consider it in more detail and deliberation.
> 
> Translated with www.DeepL.com/Translator (free version)

**Comment by mmd-osm** [comment]
Wiki votes and tagging belong to the wiki and probably the tagging mailing list. I don't see how this is relevant to the openstreetmap-website repo.
