### ISSUE TITLE
Headings are way too large

### ISSUE THREAD

**Issue by Prince-Kassad** [openstreetmap/openstreetmap-website#2492]
We had the opposite problem (headings were way too small) up until today. Now they are way too large. This affects all pages where headings are used (i. e. history, user page, etc.)

Using latest Firefox on Win7.

**Comment by dieterdreist** [comment]
sent from a phone

> On 3. Jan 2020, at 10:48, Prince-Kassad <notifications@github.com> wrote:
> 
> We had the opposite problem (headings were way too small) up until today. Now they are way too large. This affects all pages where headings are used (i. e. history, user page, etc.)


does this apply to large screens only? On mobile current heading size seems ok to me.

**Comment by Prince-Kassad** [comment]
Please see the attached screenshot:

![websitebug1](https://user-images.githubusercontent.com/48839736/71771656-2cd7b280-2f3f-11ea-83b3-971a64229a8e.png)

* The changeset comment should not be rendered as a heading
* The font size for the normal text is disproportionate compared to the font size used for the changeset attributes
* The large font means changeset comments can exceed the width of the left pane, overflowing into nothingness where you can't read the changeset comment
* The text container attributes are also wrong and result in lots of unnecessary padding (try using the query tool and you will see what I mean)

As you can see from the top pane (which is unchanged) this is not a DPI/system setting problem. It is a CSS bug in the website itself.

**Comment by gravitystorm** [comment]
Yes, there are a few obvious problems here and I intend to fix them:

* The use of h2 on the sidebars is often too big, but the layout of the sidebar explicitly depends on the first thing being a header, and it being specifically h2. For example, if you use h3 then padding and margins aren't applied. I intend to refactor this so that we can choose headings as we see fit, by making the whole of the sidebar content within a padded div.
* I've no idea why the changeset comment tag was ever in a heading. Previously the heading was changed to the same size as the normal text and made bold. I don't know why a header was therefore used. I think it would be better as regular text.

I will also look into the changeset comments problem. 

>     * The text container attributes are also wrong and result in lots of unnecessary padding (try using the query tool and you will see what I mean)

Can you explain this further please; I don't understand what you are referring to here.

**Comment by Prince-Kassad** [comment]
Please see this second screenshot:

![websitebug2](https://user-images.githubusercontent.com/48839736/71778712-88428880-2fb1-11ea-8341-a800932323db.png)

Pretty sure this didn't happen before. The query results has a lot more (unnecessary) padding than e. g. the history page.

**Comment by gravitystorm** [comment]
Thanks, I agree there's too much padding there.

**Comment by mmd-osm** [comment]
This site still serves the „old“ style: https://www.openhistoricalmap.org

**Comment by gravitystorm** [comment]
These issues have been mostly resolved by #2497, #2504 and #2509 so I'm closing this. 

Further work on restyling the sidebar, particularly refactoring to use a padded div instead of padding on individual elements, would be useful at some point to allow free choice of elements.

**Comment by mmd-osm** [comment]
Would those changes already appear on https://master.apis.dev.openstreetmap.org/history ? I don't seem see any difference to, say a week ago, and headings are still rather larghish.

**Comment by gravitystorm** [comment]
> Would those changes already appear on https://master.apis.dev.openstreetmap.org/history ? I don't seem see any difference to, say a week ago, and headings are still rather larghish.

#2497 was merged a week ago and fixed the excessive padding in those lists, so nothing has changed there in the last week. The text for each changeset comment tag is smaller than before that PR was merged. The overall sidepanel heading is still <h2> and that can't be changed until further refactoring is completed, but I don't think that's the highest priority anyway.

**Comment by mmd-osm** [comment]
Ok, thanks for clarifying. I wasn't exactly sure what to expect, i.e. if the layout should be like back in the days (see openhistoricalmap for reference).

It seems Github formatting messed up your last sentence a bit. I guess you really wanted to say `The overall sidepanel heading is still <h2> ... `

**Comment by gravitystorm** [comment]
> It seems Github formatting messed up your last sentence a bit. I guess you really wanted to say `The overall sidepanel heading is still <h2> ... `

fixed, thanks!
