### ISSUE TITLE
Add right click menu.

### ISSUE THREAD

**Issue by ponychicken** [openstreetmap/openstreetmap-website#251]
I really like the gmaps right click functionality. 

It could have the following items:
Zoom in
Zoom out
Center map here

Edit
Report an issue

I'd be happy to implement this if there is some consensus

**Comment by javiribera** [comment]
I'm bumping this proposal now that we have routing capabilities for the end user.

When wanting to select a source and destination for routing, manually typing the addresses is not always feasible (one may not know it and just see it on the map). By now the only way to select as source/address a given point (coordinates) is dragging the green/red marker, which is not very handy (specially for touchpads).

Having a right-click menu "Routes from here" / "To here" (or maybe others as well) would be appreciated.

The native right-click menu of the browser, would be overwritten, yes. But I don't see the use of any of its options available when clicking on the tiles.

**Comment by HolgerJeromin** [comment]
I use right click "open tile image in a new window" often. There i can force a refresh after an edit.

**Comment by javiribera** [comment]
It would be a win-win situation to have such option in the new "custom" right click menu. It could also be made more explicit for non-power users.

**Comment by Rezonansowy** [comment]
@javiribera @HolgerJeromin A good solution would be to call the normal browser menu by pressing e.g. Ctrl + right click. It's better than merging the "map menu" and browser-specific menu.

**Comment by javiribera** [comment]
@Rezonansowy That's also a good idea!

**Comment by HolgerJeromin** [comment]
nobody would find that functionality... 8-/

**Comment by Rezonansowy** [comment]
@HolgerJeromin We can mention this in the documentation.

**Comment by danstowell** [comment]
@HolgerJeromin the (current) right-click menu options on the slippymap are only of interest to advanced users. Document it properly, we'll be fine. I like the Ctrl+RightClick suggestion

**Comment by HolgerJeromin** [comment]
Even i have never read (or want to read) the documentation of an interactive map website...

BTW which documentation of the osm mainpage do you mean? 
http://wiki.openstreetmap.org/wiki/Browsing probably...

**Comment by neiljp** [comment]
If a regular menu, the ctrl-right-click *could* be indicated at the bottom (ie. where people don't look as much, and requiring further movement).

Re content of the menu, the graphhopper routing menu from right-click is perhaps pertinent?

**Comment by tomhughes** [comment]
People, you can bikeshed what options should be on the menu as much as you like, but nothing is going to happen until somebody steps up to actually write the damned thing.

**Comment by Rezonansowy** [comment]
@tomhughes We know it. It's open-source and everyone can do. Don't worry about too much work. ;)

**Comment by Rezonansowy** [comment]
@tomhughes  I see that @danstowell implemented the right-click menu in his fork – see https://github.com/openstreetmap/openstreetmap-website/issues/251#issuecomment-47629056

**Comment by danstowell** [comment]
@Rezonansowy that fork is old, I think @neiljp gave a good clue of how to implement it better - considering doing it

**Comment by danstowell** [comment]
Here you go, a first draft of a context-menu for osm.org using leaflet.contextmenu:
https://github.com/danstowell/openstreetmap-website/tree/leafletcontextmenu
Might work on it more this weekend

**Comment by HolgerJeromin** [comment]
Share this position could be added.
