### ISSUE TITLE
[Feature] Private notes

### ISSUE THREAD

**Issue by Atrate** [openstreetmap/openstreetmap-website#2513]
After a brief conversation with some people newly involved with OSM they say that a feature like "private notes" that would be only visible to the person that created them would be beneficial because of it being always synced across multiple platforms so I'd also suggest adding that.

For example make a checkbox like "make this note private" while on the osm.org website and an option when uploading notes from various clients

**Comment by mmd-osm** [comment]
I think this isn't what notes were designed for. The idea is to exchange with other mappers, not so much as your personal scribble pad. See https://wiki.openstreetmap.org/wiki/Notes:

> Don't use notes for yourself in a way which is useless to others. Although you can use notes as a reminder to yourself, you are also inviting others to look at it. Descriptions must make sense to other people.

**Comment by simonpoole** [comment]
> 
> 
>... because of it being always synced across multiple platforms so I'd also suggest adding that.

I'm not quite sure I understand this, could you explain this a bit more? Mainly because if the notes are private they by definition wouldn't able to be synced with any 3rd party platform.

**Comment by mmd-osm** [comment]
> a third party platform could, given corresponding authorisation, retrieve such notes naturally

Obviously, this wouldn't work for any file based replication, such as https://planet.openstreetmap.org/notes/ . On the API side, neither do notes have any kind of "private" flag, nor do any of the API methods require authorization or would behave differently upon providing any credentials.

**Comment by ferdinand0101** [comment]
> Obviously, this wouldn't work for any file based replication, such as https://planet.openstreetmap.org/notes/ . On the API side, neither (as of today) do notes have any kind of "private" flag, nor do any of the notes API endpoints require authorization or would behave differently upon providing valid credentials.
Who says that they can not be inside the planet file ? I mean the main purpose is to not show them on the map they are private but not secret

**Comment by mmd-osm** [comment]
Ok, let's take a step back. What issue do you really want to solve? Too many notes cluttering the map?  Missing filtering options? Something different maybe?

**Comment by mmd-osm** [comment]
By the way, private notes have also been proposed here: https://github.com/openstreetmap/openstreetmap-website/issues/486#issuecomment-27671895 (issue is still open).

This would make this issue a duplicate of #486.

**Comment by Atrate** [comment]
> [](https://github.com/openstreetmap/openstreetmap-website/issues/486).

Yes, it seems JBosm had formulated it in a better way and more clearly. I'll close this.

**Comment by simonpoole** [comment]
> Who says that they can not be inside the planet file ? I mean the main purpose is to not show them on the map they are private but not secret

Because people would not understand such a fine differentiation and we would be running around removing personal stuff the whole time.
