### ISSUE TITLE
Monastery preset self-conflicting

### ISSUE THREAD

**Issue by tohaklim** [openstreetmap/openstreetmap-website#2518]
The monastery preset has the description of "Monastery grounds", yet the icon background is that for a building preset, and indeed a building value is added to the area when the preset is applied.
I think the [wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dmonastery) does in fact prescribe that the tag is used on the grounds. (of course, this being osm, the first paragraph makes it sound like you can tag a building as well)

**Comment by tomhughes** [comment]
Presets are nothing to do with this repository - you will need to contact whichever editor it is whose presets you want to change. Probably one of:

* https://github.com/openstreetmap/iD/issues
* https://josm.openstreetmap.de/wiki/Presets
* https://vespucci.io/help/en/Presets/
