### ISSUE TITLE
Minify JavaScript assets

### ISSUE THREAD

**Issue by grischard** [openstreetmap/openstreetmap-website#2522]
I'm surprised by this, so maybe I'm missing something?

It looks like we can save 187KB in total on an initial page load by minifying our javascript assets.

| name | url | Current weight | Minified | Gain |
| ---- |-----|----------------|----------|------|
| jquery | https://www.openstreetmap.org/assets/application-4934642fec473bcc983ced35b73efef8351ec964bb0a54a03db5f2b83f34b838.js | 238 KB (gzipped)|100 KB (gzipped)|-137 KB|
| everything else | https://www.openstreetmap.org/assets/index-f670501149e6de4638186c162f9755c3575c983eff2d88ba95a2dd589ec35de3.js | 37.7 KB (gzipped) | 23.6 KB (gzipped) | -14.2 KB |
| Polyfill | https://www.openstreetmap.org/assets/es6-cbef4846488dea91524dfb095136e8f00afb8e62082286a75691f60e0c2b52ed.js | 48.6 KB (gzipped) | 17.9 KB (gzipped) | -30.7 KB |
| piwik | https://piwik.openstreetmap.org/piwik.js | 22.8 KB (gzipped) | 20.2 KB (gzipped) | -2.6 KB |
| i18n | https://www.openstreetmap.org/assets/i18n/en-US-da3d0840212b2392116f574a7f20fbcb0658d1ac6ed0ca43cd69cfec475ed2f8.js | 8.8 KB (gzipped) | 8.1 KB (gzipped) | -676 bytes |

**Comment by tomhughes** [comment]
The assets pipeline should already be doing that - piwik is separate obviously but I would expect upstream to distribute that appropriately minified and we have no way to influence that.

**Comment by tomhughes** [comment]
Specifically https://github.com/openstreetmap/openstreetmap-website/blob/master/Gemfile#L22 is the minifier which sprockets should then be picking up.

**Comment by grischard** [comment]
Thank you Tom!
