### ISSUE TITLE
Update Github authentication mechanism

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2528]
I received a warning email from Github regarding the "OpenStreetMap Authentication" application. As far as I can tell, this is an application registered under the "OpenStreetMap" organization, and is used by the main www.osm.org site for allowing people to log in with their github id.

I would normally log this with the OSMF OWG, but I think it needs some source code changes to resolve so I'm opening it here. If I'm mistaken in any of this, please feel free to move this issue!

> your application (OpenStreetMap Authentication) used an access token (with the User-Agent Faraday v1.0.0) as part of a query parameter to access an endpoint through the GitHub API.
> https://api.github.com/user
> Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.
>[...]
>Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

**Comment by tomhughes** [comment]
Well it's an upstream issue I assume but yes I got the same and was going to have a look at `omniauth-github` later.

**Comment by tomhughes** [comment]
Already raised upstream as https://github.com/omniauth/omniauth-github/issues/83 in fact.

**Comment by gravitystorm** [comment]
> Already raised upstream as [omniauth/omniauth-github#83](https://github.com/omniauth/omniauth-github/issues/83) in fact.

Great! I wasn't sure if it needed a patch upstream or just a configuration change, and it turns out I was checking the wrong issue list too.

**Comment by tomhughes** [comment]
Fixed in 6a92187e1d468250305551d9a47926c3f478ccfa.
