### ISSUE TITLE
Welcome message hiding X to close

### ISSUE THREAD

**Issue by boothym** [openstreetmap/openstreetmap-website#2530]
The X link to the close the welcome message is hidden by "Welcome to OpenStreetMap" on both Chrome and Firefox on Win10. 
![Screenshot_2020-02-10 OpenStreetMap](https://user-images.githubusercontent.com/16965772/74193142-c1c08080-4c4e-11ea-9738-af2a08e6c401.png)

Noticed a couple of people (presumably new users) mention this on twitter: 

https://twitter.com/ericghill/status/1226633066723962880

https://twitter.com/leftistthot420/status/1226198567087415296

**Comment by bezdna** [comment]
https://github.com/openstreetmap/openstreetmap-website/pull/2537

**Comment by Beep6581** [comment]
June 2020, Google Chrome 80.0.3987.149
![screenshot_20200526_001200](https://user-images.githubusercontent.com/5844619/82845621-8f791d00-9ee5-11ea-80a7-e4201491c466.png)

**Comment by boothym** [comment]
Someone else on twitter has posted about being unable to close the box - https://twitter.com/EugenesDIYDen/status/1276804381132812291

**Comment by dieterdreist** [comment]
is it clickable?

**Comment by boothym** [comment]
@dieterdreist Yes, but as you can see from the examples people either can't see it or don't realise it can be clicked.

**Comment by fgnievinski** [comment]
I hope designers don't think it's the users fault for the bad design

**Comment by tomhughes** [comment]
Has anybody suggested that? Not that we actually have any "designers" to start with...
