### ISSUE TITLE
No mouseover highlight if changeset has no bounding box

### ISSUE THREAD

**Issue by Prince-Kassad** [openstreetmap/openstreetmap-website#2541]
A changeset can have no bounding box if it only contains empty relations (i. e. relations with no members).

When looking at a user's contributions (these changesets will never show up in the history pane due to a lack of a bbox), hovering over these particular changesets will not trigger the mouseover highlight. It works for changesets that have a bbox. It's a purely visual bug - clicking still works. I'm pretty sure this worked before, so it's a regression.

**Comment by mmd-osm** [comment]
I'm too lazy to find some example, can you name one?

**Comment by tomhughes** [comment]
Please, when you're reporting something like this, try and include a URL for a failing example.

**Comment by tomhughes** [comment]
Are relations with no members even valid? I think iD at least will delete a relation automatically if you remove the last member?

**Comment by simonpoole** [comment]
@tomhughes I believe so (empty relations are valid) they used to be fairly common place. Now days all of the editors I have 1st hand experience with will at least pop-up a warning if not outright delete them on upload.

**Comment by Prince-Kassad** [comment]
> they used to be fairly common place.

The current planet.osm has on the order of 55,000 empty relations. Most of them are probably people who ignore the JOSM warnings or failed imports.

**Comment by simonpoole** [comment]
> 
> 
> > they used to be fairly common place.
> 
> The current planet.osm has on the order of 55,000 empty relations. Most of them are probably people who ignore the JOSM warnings or failed imports.

But you still haven't provided a link to a changeset containing one, which makes this a bit non-actionable.

**Comment by Prince-Kassad** [comment]
Links to user contributions on the live OSM server are volatile by nature and will eventually disappear in the sea of contributions which is a bit problematic for a bug report. It should probably be replicated on the test server (i. e. master.apis.dev.openstreetmap.org) simply by creating an empty relation in one changeset and deleting it in the next.

**Comment by tomhughes** [comment]
The point is that creating one is easier said than done! I tried earlier which is why I questioned why they were legal...

**Comment by tomhughes** [comment]
...and now that I have managed to create one using the API the highlight is working fine for me :-(

**Comment by tomhughes** [comment]
I'm guessing that because the changeset in question removed the members from the relation it got a bounding box from the old version...

**Comment by Prince-Kassad** [comment]
Observe: https://master.apis.dev.openstreetmap.org/user/Prince%20Kassad/history

No highlight here.

**Comment by tomhughes** [comment]
Yes I've reproduced it now - the changeset has to have no bounding box because none of it's members have any geographic coordinates in either their old or new versions.

So it has to be an edit of a relation that already had no members and still has none afterwards, which is a pretty odd thing to do.

The highlight is really there to indicate which changeset you are highlightinhg on the map and as such a changeset has no highlight on the map it doesn't get a highlight in the list either.
