### ISSUE TITLE
Replace PhantomJS

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2544]
We currently use PhantomJS for our system tests. It's a headless webbrowser that supports javascript. The dependency is quite indirect, namely:

```
System Tests -> Capybara -> Poltergeist -> PhantomJS
```

PhantomJS last had a release in 2016, and was officially abandoned in 2017. We're starting to feel its age, since the javascript features it supports are falling a long way behind what is now used in browsers.

In recent years, both firefox and chrome have gained support for running in headless mode, which means we could use one or other of them for our tests instead. Additionally, a standard for "driving" these has emerged, known as the webdriver API. This, along with selenium, would replace the poltergeist part as the glue between the testing framework and the browser binary itself. So we would end up with:

```
System Tests -> Capybara -> Selenium -> (Webdriver API) -> Gecko
```

**Comment by HolgerJeromin** [comment]
There is [some life](https://github.com/ariya/phantomjs/issues/15398) in the project again.

But my projects switched to headless chrome, too.
Firefox had some problems with updates. The headless browser wants some interaction with the non existing user to confirm an update or something like that. But YMMV.

**Comment by bhousel** [comment]
For what it's worth - I've found it useful to keep PhantomJS around for running the iD tests because it is very similar to IE11.

**Comment by hiddewie** [comment]
It seems this issue is done in 8773ec6e57bfcd2e3c316ae5bdbb36fec2a3f104
