### ISSUE TITLE
Stats by browser and system

### ISSUE THREAD

**Issue by bezdna** [openstreetmap/openstreetmap-website#2546]
https://piwik.openstreetmap.org/
There is analytics on the site, and I would like to know a little statistics on the use of the site, which browsers and which systems people use, so that the development of the frontend is better and focused on the end user

**Comment by tomhughes** [comment]
If you have a specific question then we can of course attempt to answer it but this appears to be too vague to be actionable.

In any case you should be trying to make things as portable as possible - if there is something that you want to do that really requires a specific capability then we can of course look at the statistics to see what the impact might be.

**Comment by bezdna** [comment]
What browsers is the project trying to support?
What users is the site targeted to?

**Comment by simonpoole** [comment]
> What users is the site targeted to?
May I respectfully point out that that is a strategy/policy decision that you should be asking the OSMF board (board@osmfoundation.org) and not operations.

**Comment by tomhughes** [comment]
Our golden rule is that the site is targeted at mappers and definitely not at end users - we are specifically not trying to provide a google maps clone for the general public.

As to browsers, as many as possible within reason. At a minimum a recent version of any of the mainstream browsers.

**Comment by bezdna** [comment]
> > What users is the site targeted to?
> > May I respectfully point out that that is a strategy/policy decision that you should be asking the OSMF board ([board@osmfoundation.org](mailto:board@osmfoundation.org)) and not operations.

If I want to make my contribution to the development of the project, I would not want to throw the code in a black box and get information of the type from there, "the code does not meet our tasks" or "the code does not work for the users we are focused on"

**Comment by bezdna** [comment]
> As to browsers, as many as possible within reason. At a minimum a recent version of any of the mainstream browsers.


vy zhe programmist, a ne deputat, chto za rasplyvchatyye i poverkhnostnyye otvety.
Mozhno konkretiku, chto-to tipa takogo
IYe ne podderzhivayem
desktop posledniye 5 versiy Khroma fayerfoksa
desktop posledniye 2 versiy safari
mobil'nyye ne nasha tselevaya uditoriya,
Развернуть
246/5000
You are a programmer, not a deputy, what kind of vague and superficial answers.
You can specifics, something like this:
IE do not support
desktop last 5 versions of Chrome, Firefox
desktop last 2 safari versions
desktop last 2 EDGE versions
mobile is not our target audience
