### ISSUE TITLE
Deleted GPX tracks remain shown

### ISSUE THREAD

**Issue by joriswu** [openstreetmap/openstreetmap-website#2549]
When a GPX track is uploaded it displays correctly on the map. Yet, after deleting it, it remains shown forever. Main issue is that erratic tracks cannot be deleted from a map viewer perspective, cluttering the map.

I uploaded it 18 Feb 2020, saw the erratic recordin g and deleted it Then removed the erratioc points and uploaded the shortened track under the same name.

"It looks like your GPX file local_20200206_hw_street.gpx with the description Mount Nebo village local streets and the following tags: mount_nebo loaded successfully with 1993 out of a possible 1993 points."

**Comment by woodpeck** [comment]
Can you clarify *where* the GPX track "remains shown" - am I right in assuming that you are speaking of the GPX background in the ID editor?

**Comment by tomhughes** [comment]
Yes I assume he is talking about the tiles from https://gps-tile.openstreetmap.org/ which consumes traces as soon as they are uploaded and renders them to tiles - it uses public apis and deleting traces will no effect on it just as it will have no effect on any other user of the api that has already downloaded a trace before it is deleted.

**Comment by SomeoneElseOSM** [comment]
A related issue is https://github.com/ericfischer/gpx-updater/issues/1 (see also some of the discussion on the linked ticket).

**Comment by joriswu** [comment]
> Yes I assume he is talking about the tiles from https://gps-tile.openstreetmap.org/ which consumes traces as soon as they are uploaded and renders them to tiles - it uses public apis and deleting traces will no effect on it just as it will have no effect on any other user of the api that has already downloaded a trace before it is deleted.

So erratic traces cannot be deleted from the tiles. I think they should be, otherwise you can never get rid of errors. For example, by periodically refreshing the tiles.

**Comment by tomhughes** [comment]
Unfortunately the whole system that generates those tiles is basically unmaintained, plus as I think that other ticket says there is no way for it to detection deletions anyway.

**Comment by FabianInostroza** [comment]
mm, I wanted to delete some traces that I uploaded by error before editing them (they show "exactly" where I live). No way the traces tiles could be regenerated from zero for an area?

**Comment by johantiden** [comment]
https://github.com/openstreetmap/gpx-updater/issues/4
