### ISSUE TITLE
Allow voting up blog entries

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2551]
https://www.openstreetmap.org/diary entries should offer buttons to vote them up and down, and even report them.

And then another link should be offered to see "top ranked blog entries" / ordered by votes.

**Comment by jidanni** [comment]
And don't allow voting on one's own entry.

**Comment by jidanni** [comment]
Also for comments on blog entries, at least allow users to "Like" them, with a tally of likes too.

**Comment by gravitystorm** [comment]
Thanks for the feature suggestion. However, I don't think it's worth the extra complexity involved in implementing it.
