### ISSUE TITLE
Abrupt end of forested tiles

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2553]
The abrupt end of forested tiles seen in
https://github.com/hotosm/hotosm-website/issues/638
also affects all four map layers.

**Comment by Firefishy** [comment]
This is not a website issue. Closing.

**Comment by jidanni** [comment]
Anybody know where I should post it to?

**Comment by jidanni** [comment]
Wait! https://www.openstreetmap.org/relation/7356099

**Comment by jidanni** [comment]
OK I added a comment to https://www.openstreetmap.org/changeset/49815601 .
