### ISSUE TITLE
unable to use oAuth 

### ISSUE THREAD

**Issue by hthouse** [openstreetmap/openstreetmap-website#2554]
I installed OpenStreetMap-Website (The Rails Ports) for development using the INSTALL.md and CONFIGURE.md. However,  could not get JOSM link to the server using OAuth.  I was able to use manual entry of consumer key and secret to get it to work (download and upload data/tags).
Is there a missing configuration instruction or a bug standing up a custom dev install of The Rails Port in AWS ec2 instance?
Please help?

**Comment by tomhughes** [comment]
Well you will need to create a client application for JOSM and configure JOSM with the appropriate key but it should work once you do that.

Hard to say more without some specific details of the problem you are experiencing.

**Comment by mmd-osm** [comment]
This is totally expected and no bug whatsoever. JOSM default settings will only work with the main website openstreetmap.org. You always need to set your own consumer key and secret for OAuth to work on your own instance.

**Comment by fazlerabbi37** [comment]
just a thought, would it be helpful this repo had an issue template, asking the user to check the help.osm.org site first and mention that this is an **issue tracker** not a QA system? first time I didn't know the different and asked a lot of irrelevant questions.

cc @tomhughes
