### ISSUE TITLE
"bundle exec rake test:db" errors

### ISSUE THREAD

**Issue by GSYIWEN** [openstreetmap/openstreetmap-website#2556]
I used the latest Ubuntu release (18.04) on Vritual Box, I followed the guide https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md to install all dependencies. and when running the "bundle exec rake test:db", I keep getting thrown the error below for each test.

```
1. 
Error:

ReportDiaryEntryTest#test_it_works:
ActionController::MissingExactTemplate: UsersController#login is missing a template for request formats: text/html
    config/initializers/compressed_requests.rb:27:in `call'
    config/initializers/cors.rb:9:in `call'**

2.
Failure:
Api::PermissionsControllerTest#test_permissions_oauth [/home/gs/Projects/C++/OSM/openstreetmap-website/test/controllers/api/permissions_controller_test.rb:42]:
Expected response to be a <2XX: success>, but was a <406: Not Acceptable>
Response body: 

3.
UserCreationTest#test_user_create_submit_duplicate_username:
ActionView::MissingTemplate: Missing template users/new, application/new with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
  * "/home/gs/Projects/C++/OSM/openstreetmap-website/app/views"
  * "/var/lib/gems/2.5.0/gems/actiontext-6.0.2.1/app/views"
  * "/var/lib/gems/2.5.0/gems/actionmailbox-6.0.2.1/app/views"

    app/controllers/users_controller.rb:247:in `create'
    config/initializers/compressed_requests.rb:27:in `call'
    config/initializers/cors.rb:9:in `call'
    test/integration/user_creation_test.rb:66:in `block (4 levels) in test_user_create_submit_duplicate_username'
    test/integration/user_creation_test.rb:65:in `block (3 levels) in test_user_create_submit_duplicate_username'
    test/integration/user_creation_test.rb:64:in `block (2 levels) in test_user_create_submit_duplicate_username'
    test/integration/user_creation_test.rb:63:in `block in test_user_create_submit_duplicate_username'
    test/integration/user_creation_test.rb:60:in `each'
    test/integration/user_creation_test.rb:60:in `test_user_create_submit_duplicate_username'

4.
Error:
UserCreationTest#test_user_create_success:
ActionView::MissingTemplate: Missing template notifier/signup_confirm with "mailer". Searched in:
  * "notifier"

    app/mailers/notifier.rb:19:in `block in signup_confirm'
    app/mailers/notifier.rb:203:in `block in with_recipient_locale'
    app/mailers/notifier.rb:202:in `with_recipient_locale'
    app/mailers/notifier.rb:14:in `signup_confirm'
    app/controllers/users_controller.rb:109:in `save'
    config/initializers/compressed_requests.rb:27:in `call'
    config/initializers/cors.rb:9:in `call'
    test/integration/user_creation_test.rb:106:in `block (4 levels) in test_user_create_success'
    test/integration/user_creation_test.rb:105:in `block (3 levels) in test_user_create_success'
    test/integration/user_creation_test.rb:104:in `block (2 levels) in test_user_create_success'
    test/integration/user_creation_test.rb:103:in `block in test_user_create_success'
    test/integration/user_creation_test.rb:84:in `each'
    test/integration/user_creation_test.rb:84:in `test_user_create_success'
```
there are 57 failures, 352 errors. Has anyone encountered the same problem?

**Comment by gravitystorm** [comment]
@GSYIWEN I've investigated this today with a fresh VirtualBox VM (using our Vagrantfile) and I can't reproduce the problem that you have - I can only do so by actually deleting the template files, in which case I see the same error messages.

How have you set up your VirtualBox VM? Using vagrant, or by hand? Are you using a windows machine underneath? Is the openstreetmap-website directory really within the virtual machine, or is it on the host and mounted into the VM?

**Comment by GSYIWEN** [comment]
> 
> 
> @GSYIWEN I've investigated this today with a fresh VirtualBox VM (using our Vagrantfile) and I can't reproduce the problem that you have - I can only do so by actually deleting the template files, in which case I see the same error messages.
> 
> How have you set up your VirtualBox VM? Using vagrant, or by hand? Are you using a windows machine underneath? Is the openstreetmap-website directory really within the virtual machine, or is it on the host and mounted into the VM?

**Comment by GSYIWEN** [comment]
@gravitystorm，I set up VirtualBox VM by hand, and the openstreetmap-website directory actually within virtual machine

**Comment by gravitystorm** [comment]
@GSYIWEN Thanks for the information. The only suggestion that I have is to check that the files in app/views are still there - maybe run `git status` just to check nothing has changed on disk?

Anyone else got a better suggestion, or any ideas to try?

**Comment by gravitystorm** [comment]
Sorry @GSYIWEN , it appears that nobody has any suggestions for ideas to try. My only remaining suggestion is to try to use our Vagrant setup.

If you make any progress, or solve this issue yourself, please let us know!
