### ISSUE TITLE
Spam users

### ISSUE THREAD

**Issue by iriman** [openstreetmap/openstreetmap-website#2559]
Hello. Today I noticed that there are hundreds of spam users on osm.org just to advertise themselves. They are in different langs but nearly all of them are similar on this aspect: Sharing a link to the advertised thing and having no edits. For example take a look at [these indexed results](https://www.google.com/search?q=%22www.%22+%22edits+0%22+%22Send+Message%22+inurl:OpenStreetMap.org/user) from google.

I reported a bunch of them, but cleaning all of them needs a more smart solution.

Also I found some spam accounts that share the same website on their profile to buy some downloadable things. It may help to detect fake accounts or to stop some website owners from spamming on OSM.org.

I think some restrictions (like link sharing) on "Profile Description" for a while after account creation or before reaching "x" changesets could reduce these spamming behaviors in future.

**Comment by tomhughes** [comment]
There already are restrictions on link sharing.
