### ISSUE TITLE
correct meters/feet translation

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#2564]
These strings
https://github.com/openstreetmap/openstreetmap-website/blob/7a81258ddc7ece9e9f641083acfbc555bdedc009/config/locales/en.yml#L2475-L2477
should be rewritten so they can be translated including plural forms.

**Comment by tomhughes** [comment]
You're right of course but depending on how they are used that might not be possible without changing code that might not be under our control.

**Comment by tomhughes** [comment]
As I thought this is down to how [leaflet-locatecontrol](https://github.com/domoritz/leaflet-locatecontrol) works - specifically it is that control, not us, that does the substitution.

That was recently changed by https://github.com/domoritz/leaflet-locatecontrol/pull/258 to support a callback function but for some reason the corresponding PR on our end (#2475) doesn't actually use it despite being referenced.
