### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#2565]
I found some strings that are in English but can't be translated into local languages because they're not on Translatewiki.
 
- "None" on the profile settings page https://www.openstreetmap.org/user/USER_NAME/account
![None](https://user-images.githubusercontent.com/57260466/77174062-c59eb880-6ac0-11ea-8082-171e729c21fc.png)
- When changing to a different layer (Cycle Map, Transport Map, Humanitarian), on the bottom some of the text is in English:
	-"Tiles courtesy of"
	-"© autorzy OpenStreetMap. Tiles style by Humanitarian OpenStreetMap Team hosted by OpenStreetMap France. Warunki użytkowania"
- When reporting a diary entry, the button on the bottom.
https://www.openstreetmap.org/reports/new?reportable_id=390680&reportable_type=DiaryEntry
There is neither "Utwórz" nor "Report" on Translatewiki.
![Utwórz_Report](https://user-images.githubusercontent.com/57260466/77174107-d51e0180-6ac0-11ea-9f58-96d7314c0f7a.png)

**Comment by tomhughes** [comment]
You there is a reporting mechanism on TranslateWiki were you can ask questions right?

Asking multiple questions in one ticket is also a bad idea because it makes them hard to close.

**Comment by tomhughes** [comment]
The first one is not currently translatable (only the first one would make any sense to translate in any case).

**Comment by tomhughes** [comment]
The copyright strings are also not translatable currently.

**Comment by tomhughes** [comment]
Likewise the third one.

**Comment by tomhughes** [comment]
I'm going to close this - there are three separate issues here of varying degrees of complexity and we can't reasonably track them all on one ticket.

If you want these resolved please open a separate ticket for each issue.

**Comment by maro-21** [comment]
Are you serious about opening separate tickets?

**Comment by tomhughes** [comment]
It would certainly make life a lot easier.... I mean I can reopen this one but it means you're going to be waiting for somebody that is able to sit down and deal with all these in one go before you see any action.

**Comment by gravitystorm** [comment]
We could fix them one by one with this ticket - using e.g. "refs #2565" in each commit. And we could add a [task list](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) to the initial description to track progress. Or we can split them into different issues. I don't mind which approach we take.

**Comment by maro-21** [comment]
I added checkboxes.

**Comment by maro-21** [comment]
- The second one works fine. I translated it and it was updated.
- Unfortunately the first one doesn't work. I still can see "None" although it was translated and updated ten days ago. How about other language versions? Can you see it translated into your language?
- The third one doesn't work at all - they're just two separate strings but I don't see any connection in the code. And they shouldn't be separate words because it's a phrase "Report issue". "Report" in English can be a noun or a verb so for translation it should be in one phrase.
- On https://www.openstreetmap.org/reports/new?reportable_id=390680&reportable_type=DiaryEntry I still can see "Utwórz Report", but how is possible if the word "Utwórz" is neither on Translatewiki nor in the code?

**Comment by gravitystorm** [comment]
>  Unfortunately the first one doesn't work. I still can see "None" although it was translated and updated ten days ago. How about other language versions? Can you see it translated into your language?

This works for me now - I see 'brak' when I set my language to Polish.

> I still can see "Utwórz Report"

There are many parts to this, since the button label is created automatically and there are many ways that the i18n system can generate button labels. 

First the "Report" bit - either `activerecord.models.#{model_name}` or if that doesn't exist, then `model_name.capitalize`. Tom added `activerecord.models.report` in the above commit, but it hasn't been translated yet into Polish on translatewiki.

Second part - the "Create/Utwórz %{model}" comes from the rails-i18n project, specifically [this line](https://github.com/svenfuchs/rails-i18n/blob/26f1bd90c2cd9e7192fbf84d64a5415e6a2fc977/rails/locale/pl.yml#L177). This means we don't need to have repeat translations for every model. For some situations where this doesn't fit (like "Add comment" instead of "Create Issue Comment") we have specific translations, under the `helpers.submit` hierarchy (e.g. `helpers.submit.issue_comment`).

I hope this helps!

**Comment by maro-21** [comment]
> I hope this helps!

For "Utwórz Report" yes. Thanks! I didn't translate it before because I thought that if untranslated, it should appear in English. I've just translated it and we'll see if it works after update.

Regarding "None": it still doesn't work, but I made a new issue for it.
