### ISSUE TITLE
OAuth token CORS error

### ISSUE THREAD

**Issue by MRVDH** [openstreetmap/openstreetmap-website#2572]
When I redirect the user to the login URL I get the following CORS error.
![image](https://user-images.githubusercontent.com/6686385/77825320-bf37be80-7108-11ea-9b45-bcfca25680ef.png)

However, if I look at the openstreetmap-website ruby source code it looks like it should accept the request.
https://github.com/openstreetmap/openstreetmap-website/blob/c672a73de3f376d0981c5bec9cdc3e97d5d0f9b7/config/initializers/cors.rb
![image](https://user-images.githubusercontent.com/6686385/77825340-e42c3180-7108-11ea-8038-1c4e84e4aec0.png)

Am I doing something wrong or is it something with redirects that the openstreetmap-website server can't handle?

**Comment by tomhughes** [comment]
Well you're not redirecting them to it, you're doing an XHR call to it and our CORS policy doesn't allow that.
