### ISSUE TITLE
Report network and ref for route relations, not name

### ISSUE THREAD

**Issue by AndrewHain** [openstreetmap/openstreetmap-website#2573]
Following the conversation starting at https://lists.openstreetmap.org/pipermail/tagging/2020-March/051787.html, it is pointed out that mappers enter descriptions in the name= tag of route relations to show up in the side panel. This inhibits rendering and searches of genuine names. This can be tackled by not reporting the name= tag of route relations, maybe reporting the network= and ref= tags instead.

**Comment by tomhughes** [comment]
Alternatively we could just stop all the clever arse object specific rendering in the side panel and just show raw tags.

**Comment by tomhughes** [comment]
More seriously I think there is no evidence at all that it is the side panel specifically that is causing this - in fact it is vanishingly unlikely.

It's far more likely that people are doing it to get the name to render how they want on the map.

**Comment by systemed** [comment]
I don't think it's that either - route relation names don't render on osm-carto or OCM. I think it's probably the JOSM relations panel, to be honest. If you look at https://josm.openstreetmap.de/wiki/Help/Relations then it seems to be just showing the name.

**Comment by woodpeck** [comment]
I happen to have JOSM installed and quickly tried - it shows the "name" if one is given, otherwise shows the "ref", and if neither are present it will just show "route 12345" (the relation id).

**Comment by lonvia** [comment]
I suspect that people actually had the side panel of waymarkedtrails.org in mind here. I don't think there's any need to add special cases here on osm.org.
