### ISSUE TITLE
Download of osmChange file blocked in iD editor

### ISSUE THREAD

**Issue by c7hm4r** [openstreetmap/openstreetmap-website#2582]
The current Content Security Policy HTTP header of https://www.openstreetmap.org/edit (iD editor) prevents using the "download osmChange file" link in Firefox. The link is accessible when clicking on the "save" button. Clicking on the link currently triggers no change in the GUI but an error message in the browser console is logged:
 
    Content Security Policy: The page’s settings blocked the loading of a
    resource at blob:https://www.openstreetmap.org/<uuid> ("frame-src").
 
The current CSP is:
 
    default-src 'self'; ... frame-src 'self'; ...
 
I propose that `blob:` should be added after `frame-src`.

**Comment by grischard** [comment]
PR at https://github.com/openstreetmap/openstreetmap-website/pull/2583

**Comment by tomhughes** [comment]
For those us not familiar with every obscure corner of iD can you explain where to find this option?

**Comment by c7hm4r** [comment]
> The link is accessible when clicking on the "save" button.

The link appears below the list of changed objects on the left panel.

**Comment by mmd-osm** [comment]
![grafik](https://user-images.githubusercontent.com/5842757/78896949-aec10580-7a71-11ea-925b-f4bc50966deb.png)
