### ISSUE TITLE
No colored edge upon clicking "Edit"

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2593]
If we click Export, the Export button gets a colored edge.
If we click History, the History button gets a colored edge,
![30710-7](https://user-images.githubusercontent.com/1230959/79539212-6f6d6700-80b8-11ea-98b1-943c0dddc93f.jpg)
So far, so good... but not if we click Edit! No colored edge.

**Comment by jidanni** [comment]
By the way, not only should Edit get its colored edge, but which editor we are currently using,
![31416-6](https://user-images.githubusercontent.com/1230959/79539456-f02c6300-80b8-11ea-963d-ab47891f7bc4.jpg)
should stay highlighted or otherwise indicated in the menu.

**Comment by AntonKhorev** [comment]
Buttons don't get colored edges when clicked anymore.

**Comment by AntonKhorev** [comment]
Those edges show currently focused elements when using keyboard controls. If you tab through the buttons they all will have edges when focused.

If they used to behave differently, maybe it was changed in some browser or Bootstrap update.
