### ISSUE TITLE
502 Proxy error on changeset download API

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/openstreetmap-website#2594]
When repeatedly querying the changeset download API, rarely but sometimes the following HTTP error 502 is returned:

![image](https://user-images.githubusercontent.com/4661658/79670238-d0349680-81c1-11ea-83ff-cb2e23bc1b4d.png)

With the reason given: **DNS lookup failure for: rails3**

### How to reproduce

I could reproduce it by opening an url like https://api.openstreetmap.org/api/0.6/changeset/80149421/download in the browser and repeatedly reload the page, lots of times, until the error appears.

**Comment by westnordost** [comment]
Okay no matter how often I press reload now, I can't reproduce it anymore. Looks like this was some hickup. Feel free to reopen if you think otherwise.

**Comment by tomhughes** [comment]
...and this would be the wrong place to raise it in any case ;-)
