### ISSUE TITLE
Re-enable javascript unit tests

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2595]
In 62247da244740d6d79e8ea8e29a710ce6ccc8e1b the last traces of [konacha](https://github.com/jfirebaugh/konacha) were removed, which means that the contents of `test/javascripts` is being ignored.

We can test some of our javascript indirectly using the system tests, but that's quite different from more unit-test-y stuff that was originally written with konacha.

I have no experience of doing this kind of tests in Rails, and the abandonment of konacha suggests it's not the approach that most people are taking anyway! With rails 6, and the deeper integration of more javascripty things (like yarn), we should find out what the best way to run these tests are, and refactor as necessary.

**Comment by tomhughes** [comment]
Just to be clear those tests were already not running right?

**Comment by gravitystorm** [comment]
> Just to be clear those tests were already not running right?

Yep, as far as I'm aware, they haven't been running for a long time.

**Comment by tomhughes** [comment]
I believe that 9e929de53091ab5db24be602546e525a72548dbd is the commit that actually disabled them, by removing the konacha gem from the bundle.

The background here is that I was experimenting with switching the system tests to use selenium instead of phantomjs last night and noticed those apparently unused references to konache while I was working on that.

I also have a branch from some time ago where I experimented with using yarn to manage our javascript dependencies but as only some of them are available via npm it wasn't clear to me how useful it was at the moment.

**Comment by tomhughes** [comment]
A special shout out to Google for https://bugs.chromium.org/p/chromium/issues/detail?id=775911 which explains why I've spent the last two days trying to figure out why I can't control `Accept-Language` in headless chrome, not helped by https://github.com/rails/rails/pull/37792 meaning that it didn't work in non-headless chome either!

**Comment by gravitystorm** [comment]
I've had a look at this today, with partial success. Some notes:

* I thought it might be possible to run the mocha/chai tests directly, i.e. keep everything in the nodejs ecosystem and avoid any integration with rails. But due to the use of compiled assets needed for the code under test, that's definitely swimming against the tide. So I've looked into alternatives to konacha (last commit 2016).
* The requirements are that the test framework has some level of rails integration (to get the assets from app/javascripts, vendor/assets, etc all pulled together easily) and can run mocha tests with chai assertions.
* https://github.com/jejacks0n/teaspoon fits the bill, although that was last updated in early 2021. I've [got a branch which works locally](https://github.com/gravitystorm/openstreetmap-website/tree/teaspoon), but I haven't yet got it working on github-ci.
* [jasmine-rails](https://github.com/searls/jasmine-rails) has been deprecated (2020) and so has the [Jasmine ruby gem](https://github.com/jasmine/jasmine-gem) (2022), but these were apparently in popular use after the konacha era. The suggested replacement for these is running the nodejs version of jasmine. That's rather like point 1 though, but also requires refactoring the tests away from mocha/chai.

If anyone has any suggestions then I'm all ears!

**Comment by kcne** [comment]
I would like to dig into this deeper, so i cherry picked your commits related to integrating `teaspooon`. I'm not sure if there is some progress on this afterwards, but I will try to test this & make some progress on github-ci side as well. Thank you.

**Comment by gravitystorm** [comment]
Fixed by @kcne in #5216
