### ISSUE TITLE
Correct dates in Polish

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#2602]
On the OSM website I found dates written in four different formats:

1 - "25.04.2020", (on https://www.osm.org/diary)
2 - "25 kwi 2020" (on https://www.osm.org/history)
3 - "Mapuje od: kwiecień 25, 2020" (on the user's profile page)
4 - "25 kwiecień 2020 o 13:30" (messages and other places)

The first one and the second one are correct in Polish, but the 3rd and 4th are not.

"kwiecień 25, 2020" looks like an American date format filled in with Polish words, but in Polish we never start a date with a month.

There is a list of months
https://github.com/svenfuchs/rails-i18n/blob/26f1bd90c2cd9e7192fbf84d64a5415e6a2fc977/rails/locale/pl.yml#L45-L58

It is indeed a list of months but... in nominative case and for dates we use genitive case, so if these names of months are used only for dates (I suppose so), they should be changed to:
```
    - stycznia
    - lutego
    - marca
    - kwietnia
    - maja
    - czerwca
    - lipca
    - sierpnia
    - września
    - października
    - listopada
    - grudnia
```

Please correct also:
https://github.com/svenfuchs/rails-i18n/blob/26f1bd90c2cd9e7192fbf84d64a5415e6a2fc977/rails/locale/pl.yml#L25
to "maja".

So the correct format for dates in 3 and 4 is:
25 kwietnia 2020

**Comment by tomhughes** [comment]
The date formatting is not under out control - as you seem to have already figured out it from from rails, and specifically from the rails-i18n project so that is the place you need to go if you want it fixed

**Comment by maro-21** [comment]
Looks like it won't be possible to fix - there's no one there on rails-i18n project. Would it be possible to change it manually here?

Besides that, the fix over there won't fix the word order mentioned in the 3rd point: "3 - "Mapuje od: kwiecień 25, 2020" (on the user's profile page)". This word order is for American English and is defined somewhere here. I mean, I don't know how to change the word order because the one defined there
https://github.com/svenfuchs/rails-i18n/blob/26f1bd90c2cd9e7192fbf84d64a5415e6a2fc977/rails/locale/pl.yml#L41-L44
is correct.
https://github.com/openstreetmap/openstreetmap-website/blob/a13b40ace9c98dd2271ef05811b448e28af1751a/app/views/users/show.html.erb#L152
