### ISSUE TITLE
Give non-logged-in users a hint about OSM on edit link

### ISSUE THREAD

**Issue by Phyks** [openstreetmap/openstreetmap-website#2608]
Hi,

I'm using the "edit" link (https://www.openstreetmap.org/edit#map=19/48.81476/2.32304 for instance) to provide OSM users a quick and easy way to edit the current view of the map. This can be seen on clicking the "edit" icon on the left toolbar on https://cyclosm.org/ for example.

I've just noticed that when users are not logged into their OSM account, this link sends them to the logging form. They can register from there but there are absolutely no hints about what this account will effectively do and that they can edit the map. Something which is present in https://www.openstreetmap.org/about for example.

What about having a special "edit" link which could be used in third-party maps to let users edit the map with the specific behavior :
- if user is logged in, they are redirected to the edit view and can directly edit the map.
- if user is not logged in, they get a hint about what OSM is with a link to https://www.openstreetmap.org/about with possibility to create / log in as currently.

Best,

**Comment by tomhughes** [comment]
That's what /welcome is for - it has an introduction and a big "Start Mapping" button and if you pass it lat and lon it attaches those to the button, for example:

https://www.openstreetmap.org/welcome?lat=10&lon=20

**Comment by Phyks** [comment]
Hi,

The `/welcome` link seems to not be exactly what I was looking for. The textual content is a perfect match. However:
- When user is not logged in, they are greeted with the login form before being able to see the `/welcome` page. I would have expected a user experience such as `/welcome` > click on "start mapping" > requirements to have an account (login form).
- When user is already logged in (and an active OSM user for example), they are greeted with the welcome text every time, which introduces one extra step before editing the map.

My proposal would be some user experience like: click the "OSM edit" link on a third-party website. Then:
* If user is logged in, directly send them to the editor. 
* Otherwise, send them to `/welcome` for an introductory text. Click on "start mapping" will lead to the login / account creation form.

Best
