### ISSUE TITLE
Load tiles in spiraling orb fashion, instead of row 1, row 2...

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2609]
One notes Google Maps loads tiles spiraling outward from the center of the screen, sort of like an [orb web](https://en.wikipedia.org/wiki/Spider_web#Orb_web_construction). This is much better than simply
- row 1 tile 1 tile 2 tile 3... 
- row 2 tile 1 tile 2 tile 3...
- ...

as the user is more likely focused on the center of the map, waiting for it to fill in.
Users with high speed Internet connections will never know the difference, but the rest of us will benefit.

**Comment by tomhughes** [comment]
We're not in control of the tile loading - that is all done by [leaflet](https://leafletjs.com/).

That said it almost certainly kicks off all the loads in parallel, at least up to some limit, so the order in which the loads complete will not be strictly defined.
