### ISSUE TITLE
Some tests still rely on fixtures

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2614]
Some of our tests are written in a way that despite the fixtures being removed (in https://github.com/openstreetmap/openstreetmap-website/pull/1556) they still pass. For example:

* [api/ways_controller_test#test_full](https://github.com/openstreetmap/openstreetmap-website/blob/8b588ee1f9eef3ee1ae7deddf05a3914185c8d5c/test/controllers/api/ways_controller_test.rb#L66-L90) - this test iterates over `Way.all` but there are no ways in the database, so this does nothing.
* [changesets_controller_test#test_index](https://github.com/openstreetmap/openstreetmap-website/blob/8b588ee1f9eef3ee1ae7deddf05a3914185c8d5c/test/controllers/changesets_controller_test.rb#L33-L47) - this checks to ensure that some changesets have rendered, but there are none in the database and checking against an empty `Changesets.all` returns no errors
* similar for `test_index_xhr`, `test_index_bbox`
* `test_index_max_id` - I can't even figure out what this is doing, but it involves checking the id of changesets without any being in the database.

I think the common thread is these tests are all using database queries to build the list of expected objects, instead of stating them explicitly. This allows empty databases to pass (since the list of items shown on the page == list of items in query == 0). It's much better to be explicit about which items to expect.

So we should fix the above tests. And we should double-check if there are any other tests that involve queries to build the list of expected objects. I've grepped around a bit but maybe there's a better way.

**Comment by mmd-osm** [comment]
One easy approach is to review code coverage reports. ways_controller's _full_ method has basically zero percent code coverage when running test cases:

![codecov](https://user-images.githubusercontent.com/5842757/81329579-141f0b00-909f-11ea-8f02-b5016fc923ed.png)

**Comment by tomhughes** [comment]
That tells us what isn't being tested, not what is being tested in broken ways.

There's some overlap for sure - it may even be a strict superset - but it certainly isn't anything like an exact match.

**Comment by mmd-osm** [comment]
Agreed. That's what I meant with potential candidates, there may be some more and/or even others. 

Controller code that isn't executed at all should raise a red flag and needs a closer look. Chances are that the previous code refactoring (removing fixtures) resulted in a decreased code coverage back then.
