### ISSUE TITLE
Minor stylistic issue

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/openstreetmap-website#2619]
While investigating something else (that uploading GPX traces doesn't seem to produce a proper error message when something is wrong) I noticed that do_create(file, tags, description, visibility) in controllers/traces_controller.rb seems to be identical with the do_create method in controllers/api/traces_controller.rb likely one or the other should be removed.

**Comment by tomhughes** [comment]
Well no, because both controllers need it as both the web site and the API have controller methods to create traces.

**Comment by mmd-osm** [comment]
Looks like there was no follow up comment or question -> closing
