### ISSUE TITLE
Sunset web based Potlatch by end of 2020

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#2622]
I'm creating this issue as placeholder for follow up activities for https://wiki.openstreetmap.org/wiki/Talk:Microgrants/Microgrants_2020/Proposal/Potlatch_2_for_desktop

Activitites:

-  [ ] Maybe let mappers know ahead of time so they can switch to another editor
- [ ] *Revisit the "undelete" API topic** 
- [ ] Removal of ActionScript artefacts
- [ ] Removal of AMF controller on Rails port

**Comment by tomhughes** [comment]
How can it be a followup to a grant request that might or might not be approved? and what does creating a desktop version of potlatch 2 have to do with sunsetting the web version of potlatch 1?

Now I understand that the general removal of flash support from browsers might be a reason to remove both versions of potlatch I just don't see what it has to do with that grant request.

**Comment by mmd-osm** [comment]
I guess I should have added a bit more details to my reasoning.

I think It's clear that Potlatch 1 & 2 will be no longer usable as a web version due to the Flash EOL end of 2020. In the microgrant, @systemed proposed to have at least Potlatch 2 survive as a desktop app.

I was curious how this would impact Potlatch 1. As mentioned on that wiki page, Potlatch 1 will have no future (regardless of the outcome of the microgrant), hence I've created this issue. I think this really boils down to the undelete topic, which would need some alternative moving forward.

**Comment by tomhughes** [comment]
Well neither of them has a future as part of the web site, but I'm not sure having this sit here for six months stating the blatantly obvious is entirely helpful.

Most likely we'll have forgotten about it by the time it matters and it will have sunk off the first page of the bugs and in three years time somebody will go "oh we removed that years ago" and close it ;-)

**Comment by mmd-osm** [comment]
Undelete topic also mentioned in https://trac.openstreetmap.org/ticket/3068

**Comment by c933103** [comment]
While Adobe have said they will stop updating and making available the Flash to users, Microsoft have said Flash support on Edge and IE will be removed thrpugh Windows Update, Google have said Flash support on Chrome will be dropped and Firefox have been said as it will refuse to load the plugin, people who are using old software without autoupdating their browsers or OS can still use Flash after the end of 2020 EOL

**Comment by systemed** [comment]
Desktop-based Potlatch is now ready at https://www.systemed.net/potlatch/ .

I'd suggest that a way forward for osm.org might be:

## Potlatch 1

- [ ] Remove P1 and amf_controller entirely.

## Potlatch 2

- [ ] Remove P2 from Edit menu.
- [ ] Rename "Edit with Remote Control (JOSM or Merkaartor)" to "Edit with Remote Control (JOSM, Potlatch, Merkaartor)".
- [ ] For users who have P2 set as their default editor, clicking Edit could bring up a message like:

> Your default OpenStreetMap editor is set as Potlatch. Because Adobe Flash Player has been withdrawn, Potlatch is no longer available to use in a web browser.
>
> You can still use Potlatch by [downloading the desktop application for Mac and Windows](https://www.systemed.net/potlatch/).
>
> Alternatively, you can set your default editor to iD, which runs in your web browser as Potlatch formerly did. [Change your user settings here.](/something/or/other)

**Comment by simonpoole** [comment]
I've always found the English text for the editing options rather weird. The German version is "Edit with external editor (JOSM or Merkaartor)", which is a bit better, but not good. Requiring knowledge that is completely irrelevant for the task at hand (that JOSM has a remote control facility of which starting a download of data for a specific area is just one of many options). Not to mention the irrationality of mentioning Merkaartor.

"Edit area in external editor" or "Load area in external application" would seem to be less confusing and doesn't require the OSMF to play favourites.

**Comment by SomeoneElseOSM** [comment]
One question here about Linux support:

We know that non-Wine support via running an Air file directly is still an aspiration, and running under Wine is problematic at best (see e.g. [here](https://forum.openstreetmap.org/viewtopic.php?pid=813231#p813231) and numerous Potlatch 3 issues [here](https://github.com/systemed/potlatch2/issues)).

Flash plugins supported by Adobe will stop working soon, but my understanding is that the Linux flash plugin hasn't been supported for many years.  Mainstream browsers may of course block flash from that side, but I suspect that there are a number of OSM Linux Potlatch 2 users who will not be directly affected by that.

Surely the change to the edit options at osm.org should be Windows And Mac only?

**Comment by tomhughes** [comment]
The problem is that all recent flash plugins, for values of recent that include the last linux releases I believe, have a builtin kill switch which Adobe intend to trigger in a few days time. After that they will all refuse to function unless you have a version that predates the addition of the kill switch.

**Comment by systemed** [comment]
I've created https://github.com/systemed/potlatch3/issues/2 to track possible ways of running AIR on Linux.

**Comment by c933103** [comment]
People can still use Flash after today, either through old browsers in virtual machine or through the dedicated Chinese version Flash Player that Adobe's partner will continue supporting into 2021 and beyond, there're no need to rush removing it

**Comment by mmd-osm** [comment]
Are you talking about the 2144 distribution for China? I've seen lots of reports like [this one](https://community.adobe.com/t5/flash-player/chinese-version-of-adobe-flagged-as-malware/td-p/10765253?page=1). Not sure this is something we would recommend here. Also, running old software opens up doors to all sorts of security issues.

**Comment by AndrewHain** [comment]
In 2012, when we stopped mappers from editing without accepting the ODBL, we overlooked amf_controller; the refusers found out about this and for a short time continued to edit with Potlatch 1. Have there been any other incidents like that since?

**Comment by gravitystorm** [comment]
Ah, this is a hard decision. I was a big user of Potlatch 1, and a developer for Potlatch 2 (albeit quite a few years ago now). So I'm sad to see them go.

But having been following the fate of alternative flash players over the last decade (e.g. gnash, lightspark, ruffle), I know that there's no realistic possibility of Potlatch 2 ever working in any of them. Even back in the day when tens of thousands of business applications were using Flex, lightspark went nowhere, and Flex itself went nowhere either. Even back then, there wasn't the money or developer-years available to make a dent in anything. So even if ruffle (the current alternative-player favourite) gets serious momentum, it would be years before it can support P2 (or P3), if ever.

P1 is an even harder decision, since removing the API makes it final - even with an alternative player it will no longer work. But it had to happen at some point, and probably should have happened years ago anyway.

So I'll raise a glass to P1 and P2, and wish P3 the best of luck.

**Comment by mmd-osm** [comment]
@1ec5 hosted a "goodbye P1 editing session" on Zoom last night and will probably upload it to youtube shortly...

**Comment by stephankn** [comment]
https://trac.openstreetmap.org/ticket/3068 states that this issue here is about tracking to add a query for undelete ways to main API. This seems to be a mistake. IMHO we still have no way to query deleted ways from API. You have to use 3rd party websites like osmcha or overpass history.

**Comment by mmd-osm** [comment]
That's exactly what "Revisit the "undelete" API topic" in the initial post was about.
