### ISSUE TITLE
Disk IO Performance

### ISSUE THREAD

**Issue by Legolash2o** [openstreetmap/openstreetmap-website#2623]
Hi,

I currently have the latest OpenStreetMap clone running on a VM on Azure - with the PostgreSQL on it's own server outside the VM (works fine). Currently running in Development as I haven't had chance to change to production yet.

I have to keep restarting the VM server hosting Rails every so often so it starts doing a big disk IO. From the Azure overview panel it shows that it was trying to read a large file with 100% Disk operations/sec.

Does the current implementation write to the disk (part from logs)? i.e. caching. I would have thought it would have been done in memory.

**Comment by tomhughes** [comment]
We can't really help you debug operational issues like this as we have no access to your environment.

At the very least we would need more information about what triggers the I/O before we could even begin to guess at the problem - the web site code does nothing at all except in response to user requests when a page is loaded.

You haven't even said what process is doing the I/O that you're seeing - maybe it's the database manager doing a background vacuum or something?

**Comment by Legolash2o** [comment]
I don't even know where to being to find that information out as I get locked out of the PuTTY. 

The database is on a completely separate server. I only thing on the VM is the Rails application.

**Comment by tomhughes** [comment]
Sounds to me like you don't have enough memory and the VM is swapping itself to death.
