### ISSUE TITLE
Publish data relating to radio signal strength

### ISSUE THREAD

**Issue by danjde** [openstreetmap/openstreetmap-website#2627]
HI Devs,
I do not know whether this is the correct place to such a request, possibly forgive me.
We are an Italian association and we intend to collect data on electromagnetic pollution, especially for 5G.

Openstreetmap has this feature? Or can it be implemented?

Many thanks!

**Comment by tomhughes** [comment]
This bug tracker is for issues relating to the OpenStreetMap web site code, not for general enquiries about OpenStreetMap.

That said no, of course OpenStreetMap doesn't have anything like that. We map the real physical world.

**Comment by tomhughes** [comment]
There is of course nothing stopping you building a radio signal mapping tool on an OSM base map but that sort of data wouldn't be in any way suitable for storing in the OSM database - the data model is totally wrong.
