### ISSUE TITLE
Where can I translate strings of OAuth creation form?

### ISSUE THREAD

**Issue by BANOnotIT** [openstreetmap/openstreetmap-website#2628]
![image](https://user-images.githubusercontent.com/11363215/82124352-3f90ac80-97a7-11ea-9171-a96aa550d467.png)
Looks like this form fully translated automatically. Where I can find tools or sources for russian strings for this form and original english strings?

**Comment by mmd-osm** [comment]
https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/en-GB.yml#L1847-L1873

https://translatewiki.net/wiki/Translating:OpenStreetMap

**Comment by BANOnotIT** [comment]
@mmd-osm translatewiki.net gives no context of a string usage. Will somebody accept a PR for changing ru.yaml?

**Comment by mmd-osm** [comment]
>  translatewiki.net gives no context of a string usage

Can you please sort that out with translatewiki folks. I'm sure they can guide you to the right place.

> Will somebody accept a PR for changing ru.yaml?

Probably not, TranslateWiki is the leading translation system, and your PR changes would get overwritten next time we fetch new translations.

**Comment by tomhughes** [comment]
@mmd-osm is correct - all translations need to be done through TranslateWiki and PRs on the translations will not be accepted.
