### ISSUE TITLE
Disable changeset history

### ISSUE THREAD

**Issue by Legolash2o** [openstreetmap/openstreetmap-website#2632]
Is it currently possible to only store the latest nodes/ways/etc when updating information via JOSM? I know this would result in not being able to revert any changes.

Currently, if you have a lot of tags on an edge and you upto a lot. It seems to want to copy all tags regardless if only one has changed for that edge. Causing a big slowdown.

Thanks.

**Comment by tomhughes** [comment]
It's certainly not possible to avoid storing them, nor should it be.

That doesn't seem to be what you're really asking for though - what you really seem to want is to be able to avoid uploading details for unchanged objects. That is already possible - if a node has moved then it has to be uploaded in full with all it's tags but if you're uploading a way to change it's tags then you don't need to upload the details of the nodes that make it up.

Whilst in theory you could have some way to allow partial uploads of objects the gain seems small for all but the most insane objects and it would introduce some additional complication as you would have to have a way to indicate that a tag should be removed.

**Comment by mmd-osm** [comment]
I think what @Legolash2o is reporting here is copying of all tags from `current_{nodes,ways,relations}` tables to their respective history tables on the Rails port. Indeed that's quite time consuming as tags are copied one by one, rather than using bulk operations. This happens every time a new object version is uploaded.

It's a known issue with existing solutions - one outside of the Rails port (CGImap), and another one as stale pull request (#1995) to address the issue on the Rails port.

**Comment by tomhughes** [comment]
Then I believe we can close this as this doesn't state a problem that arises in the osm.org deployment.

**Comment by Legolash2o** [comment]
> I think what @Legolash2o is reporting here is copying of all tags from `current_{node,way,relation}_tags` tables to their respective `{node,way,relation}_tags` history tables on the Rails port. Indeed that's quite time consuming as tags are copied one by one, rather than using bulk operations. This happens every time a new object version is uploaded.
> 
> It's a known issue with existing solutions - one outside of the Rails port (CGImap), and another one as stale pull request (#1995) to address the issue on the Rails port.

Yes, this is the issue. I don't understand why you have to install an additional item (CGImap) and not have it implemented in the main project.

**Comment by tomhughes** [comment]
Precisely because rails is a terrible way to do bulk data manipulation.
