### ISSUE TITLE
created an OpenStreetMap account w/ oauth only - hung on confirmation email

### ISSUE THREAD

**Issue by jawz101** [openstreetmap/openstreetmap-website#2633]
I used my github account for oauth credentials to create an OpenStreetMap account- didn't use any personal email address to register.  Now, when I try to log in it says it's waiting for my response from the confirmation email.  Since I didn't tie the account to an email address, where is the email sent?  How do I log in?

The account was literally created with ...mygithubusername...@users.noreply.github.com which is clearly not going to receive an email from openstreetmap

**Comment by tomhughes** [comment]
There is no such thing as an account that isn't tied to an email address - if you gave an address that is not valid then you will have to contact support@openstreetmap.org for assistance.

**Comment by jawz101** [comment]
When you create one with oauth- Github it uses the above email so yeah, technically you're correct but the email tied to Github oauth accounts is clearly not meant for use.  I consider this a quirk that it automatically uses Github's noreply email addrses.

**Comment by tomhughes** [comment]
Well that entirely depends on whether you have told github to use a sensible email or have let it use it's anonymous one.

We give you the option to change it, so we don't exactly hide the address we're going to use...

**Comment by jawz101** [comment]
It won't let me change at this stage because it states that it's waiting on me to respond.  If it could ask me to change where it sends the confirmation email I could get my oauth linked to an email with which I can respond.  I dunno.  It seems like a quirky scenario.

**Comment by tomhughes** [comment]
Nobody here can help you with that though - as I said you need to contact support@openstreetmap.org to get that fixed.

**Comment by jawz101** [comment]
Thank you
