### ISSUE TITLE
Language variant support in OSM website.

### ISSUE THREAD

**Issue by c933103** [openstreetmap/openstreetmap-website#2636]
Currently, I have set my OSM account's "preferred language" as follow:
zh-HK zh-hk zh-Hant zh-hant zh-TW zh-tw zh zh-yue yue yue-Hant yue-HK yue-Hans zh-classical lzh ja-Hani ko-Hani ko_hanja vi-Hani ja-hani ko-hani vi-hani en-HK en-hk en-SG en-sg en-GB en-gb en-US en-us en ja

And language setting in my browser is as follow:
Chinese (Hong Kong), Chinese (Traditional), Chinese, English (US), English, Japanese

However, when I head to OpenStreetMap website and view a feature or search result, for example when I click on https://www.openstreetmap.org/relation/4103379 , what it display is for the name of the relation is:
Relation: 渡岛综合振兴局 (4103379)

With "渡岛综合振兴局" being the value for "name:zh=\*" in the openstreetmap feature, instead of the value of "name:zh-Hant=\*" which is "渡島綜合振興局", despite zh-Hant have been set to have higher preference both in my OSM account setting and in my browser setting.

Please fix the support for the language variant in the OSM website.

**Comment by tomhughes** [comment]
This is currently tied to the web site locale - when choosing which title to display it prefers a locale which matches the locale being used for other UI elements which is this case is zh-TH I think.

What we would need to do is enhance https://github.com/openstreetmap/openstreetmap-website/blob/master/app/helpers/browse_helper.rb#L2 to work out what locales are available from the name tags and then match that against the user's preferred locales.

It's an open question whether that's really correct or if the current system (which tries to be consistent in what it displays) it better I guess.

**Comment by c933103** [comment]
> This is currently tied to the web site locale - when choosing which title to display it prefers a locale which matches the locale being used for other UI elements which is this case is zh-TW I think.
> 
> What we would need to do is enhance https://github.com/openstreetmap/openstreetmap-website/blob/master/app/helpers/browse_helper.rb#L2 to work out what locales are available from the name tags and then match that against the user's preferred locales.
> 
> It's an open question whether that's really correct or if the current system (which tries to be consistent in what it displays) it better I guess.
> 

Under my current setting, other UI elements are currently being displayed in English.

**Comment by tomhughes** [comment]
So you're not seeing `name:zh` at all, you are seeing the fallback to `name` which just happens to be the same.

**Comment by c933103** [comment]
> So you're not seeing `name:zh` at all, you are seeing the fallback to `name` which just happens to be the same.

No, what I mean is, while the name of OSM object fallback to name:zh, other UI elements like those "Download XML · View History" buttons are displayed in English.
value for the "name" is different.

**Comment by tomhughes** [comment]
I don't understand how that can happen unless you have somehow got `I18n.locale` set to `zh` which shouldn't be possible...

Hmm I suspect you may be tripping over a similar bug to one I encountered the other day which will also be why you are getting english language strings. The problem is caused where rails has translations for a locale (like `zh`) that we don't have translations for and that is enough for us to treat it as a valid locale.

What I don't have yet is a good fix...

**Comment by tomhughes** [comment]
Hmm rails doesn't have `zh` but it does have `zh-HK` so we are likely selecting that as `I18n.locale` but I don't understand how that gets you that name...

**Comment by tomhughes** [comment]
I also made a separate fix in https://github.com/openstreetmap/openstreetmap-website/commit/bf22c69286f97f72625c79d64e7c1a5cb6e95710 which means you should now get the zh-HK UI instead of the english one...

**Comment by c933103** [comment]
Now it is even more weird.
Yes UI language have been changed to something like `zh-HK` (although that trabslation needs to be work on)
However the place name still stay as `zh` instead of `zh-Hant` (It is now displayed as `關聯：渡岛综合振兴局4103379`)
Moreover, in map query result, what used to be displayed in `zh` are now being displayed in `en` (i.e. it is now showing `Region Boundary Oshima Subprefecture` when I query there

**Comment by tomhughes** [comment]
Are you logged in?

**Comment by c933103** [comment]
> Are you logged in?

Yes

**Comment by tomhughes** [comment]
In that case I don't understand what is happening. I setup a test in my local database with an object with the same names and set my language preference to match yours and verified that it was correct.

**Comment by c933103** [comment]
Ah sorry, while that incorrect result was zone logged in, it was done on my phone browser woth different language setting.

The situation on my desktop browser with language setting as listed above is now:

Feature name when the feature is selected: `zh-Hant`
Name of feature when as a role of other feature relation or when as a member of a changeset: `zh-Hant`
Search result from Nominatim: `zh`
Search result from GeoNames: `zh`
Map query result: `zh`

So apparently,
1. It depends on browser instead of user account setting
2. The search result and query result are still not being displayed correctly

**Comment by c933103** [comment]
Also, another problem: https://www.openstreetmap.org/node/263099367 this node shows up as Korean instead of Japanese on my desktop browser despite all my preferences have Japanese higher than Korean...

**Comment by tomhughes** [comment]
I've made some more improvements in d6f518f6279ddd8e07d8f78577b1414567fc6a5c to apply the new algorithm for non-logged in users.

Map query works client side so that's not able to use the full selection code without a lot of work to duplicate the algorithm in javascript - currently we just send it the UI locale.

Search is nothing to do with this repository - that's down to Nominatim which is responsible for generating the results. It does allow us to pass the locale but as as far as I know it can only accept a single locale so again we send the UI locale.

**Comment by tomhughes** [comment]
Oh no actually we send the full preferred language list to Nominatim: https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/geocoder_controller.rb#L121
