### ISSUE TITLE
Feature request: Separate UI language setting and map data language setting on website.

### ISSUE THREAD

**Issue by c933103** [openstreetmap/openstreetmap-website#2643]
It's sometimes desirable to use dofferent languages for buttons or description texts on the website versus text for place names in the website.
Please consider separating the two language preferences.

**Comment by tomhughes** [comment]
I really don't think such a niche feature that would only ever be used by a handful of people is worth spending time on - as it is I suspect very few people ever customise their language setting at all beyond what we pick up from their browser when they register.

We show all the names anyway (assuming you're referring to the data browser here) so you're only really talking about which one is shown at the top.
