### ISSUE TITLE
Changing layout of history

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/openstreetmap-website#2646]
Hi there.

When consulting some element's history, it's always a bit difficult to navigate the changes with all the nodes listed.
Would it be possible to hide the nodes list by default with a "+" sign or something similar? That way, we would be seeing just the tags part and we could click on the "+" to see the nodes changed if we wanted.

Regards.

**Comment by gravitystorm** [comment]
This was fixed a while ago ago by #2837
