### ISSUE TITLE
Missing brackets after localization

### ISSUE THREAD

**Issue by c933103** [openstreetmap/openstreetmap-website#2649]
Normally, in OSM website, node/way/relation should display like this [aka NAME (ID)]:
![image](https://user-images.githubusercontent.com/1525293/84136753-52349380-aa7e-11ea-8329-9693da68c38b.png)

However, after localized, node/way/relation are being displayed like this [aka NAMEID]:
![image](https://user-images.githubusercontent.com/1525293/84137320-1b12b200-aa7f-11ea-8014-927e7e890b2e.png)

It is causing confusion, please consider fixing this.
And I don't see anything wrong in relevant strings on translatewiki.net so it's probably not that.

**Comment by tomhughes** [comment]
That's entirely down to the translations which are managed via [TranslateWiki](https://translatewiki.net/wiki/Translating:OpenStreetMap) and we're not able to fix those here.

Specifically it is the translation of [printable_name.with_name_html](https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/zh-TW.yml#L188) causing the problem.

**Comment by c933103** [comment]
> That's entirely down to the translations which are managed via [TranslateWiki](https://translatewiki.net/wiki/Translating:OpenStreetMap) and we're not able to fix those here.
> 
> Specifically it is the translation of [printable_name.with_name_html](https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/zh-TW.yml#L188) causing the problem.

Can you point out which exact entries would I need to edit to fix that? As I cannot locate it

**Comment by tomhughes** [comment]
I gave the name of the entry! It's `printable_name.with_name_html`.

**Comment by tomhughes** [comment]
It's https://translatewiki.net/w/i.php?title=Osm:Printable_name.with_name_html/zh-hant&action=edit I think but I'm not really sure if you're supposed to edit it via that interface. I'm not a regular TW user...

**Comment by c933103** [comment]
> It's https://translatewiki.net/w/i.php?title=Osm:Printable_name.with_name_html/zh-hant&action=edit I think but I'm not really sure if you're supposed to edit it via that interface. I'm not a regular TW user...

Ah I see, and I have edited it
apparently this is not the most commonly used interface but editing here also works
Now it need to wait till the translation being sync toward this repo and then update being make toward production for it to take effect right?

**Comment by tomhughes** [comment]
Yes - that normally happens once or twice a week.
