### ISSUE TITLE
Coordinate edit button zoom level with current default editor

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2650]
Browse https://www.openstreetmap.org/#map=10/23.7068/120.8936

The edit button is disabled and just says "Zoom in to edit the map".

Same at zoom levels 11, and 12.

Finally at [level 13](https://www.openstreetmap.org/#map=13/23.7068/120.8936) the edit button will let us push it.

But... then now it is iD that says "+ Zoom in to edit".

So apparently the OSM website is configured for a previous default editor that
allowed editing starting at level 13, but now needs to be coordinated
with the current default editor. @quincylvania

Note one cannot pick a different editor with the V button,
![29473-0](https://user-images.githubusercontent.com/1230959/84173909-7d37db00-aab0-11ea-9ad5-ac305653c104.jpg)
as the V button is locked too.

**Comment by quincylvania** [comment]
@jidanni This issue is with the [openstreetmap-website](https://github.com/osmlab/openstreetmap-website) project and not with iD.

**Comment by tomhughes** [comment]
I don't think your conclusion holds.

The web site is configured for a general idea of what is the largest area one would reasonably want to load in an editor - that is influenced by various factors like how large a map request we allow to the API and just what seems plausible.

The iD authors make their own judgement about how large an area their editor can handle and they happen to think it's smaller.

That's no reason for us to change the web site though - iD is not the only editor.

**Comment by jidanni** [comment]
All I know is the user pushes the button labeled "Edit", and it is the responsibility of the website to be sure that what happens next does not embarrass OSM.

Currently (2024):
Looking at
https://www.openstreetmap.org/?mlat=39.29514&mlon=105.4995758#map=12/39.2953/105.4996
The edit button is in faint colors and its mouseover says "Zoom in to edit the map."
Now click "+", bringing us to zoom level 13. Upon which we can now click the edit button.
OK, now we are on
https://www.openstreetmap.org/edit#map=13/39.2953/105.4996
which also says "+ Zoom in to edit."
OK, we hit that "+", landing on
https://www.openstreetmap.org/edit#map=16/39.2953/105.4996
where we can finally edit.

**Comment by AntonKhorev** [comment]
This will require two different disable conditions:
- One for iD, zoom >= 16
- One for remote control, where you'd have to guess the most likely condition.

The most straightforward way is to keep the existing condition for remote control and add zoom >= 16 check for iD.
