### ISSUE TITLE
Feature request: Let user add a few custom tile server when they use the OSM website while logged in.

### ISSUE THREAD

**Issue by c933103** [openstreetmap/openstreetmap-website#2652]
The OSM website is a easy to use page that can let user query and check detail on the web-based map they are navigating, and then users can edit it on-the-fly.
However, to ordinary users, for now the OSM website can only be used together with the four default styles, which make it difficult to complete the above simple process of navigate-query-edit with alternative map style which might present different features on the map for users with different focus/interest.
This issue can be solved by allowing user to input and let the website to load from web address of tile server of other origin, so that it can more properly suit the need of different users when browsing the map, which can also help improve the mapping of different features. Since these tiles would be loaded directly from users' browser, I think it wouldn't add extra load/copyright concern onto OSM website server?
I am aware of the situation that iD allow alternative imagery source, but that's only for editing not navigate and query.

**Comment by prusswan** [comment]
Allowing users to add region-specific tile layers (that may not have worldwide coverage) do have some practical benefit for review purposes, and reduce the need to switch between applications.

**Comment by HolgerJeromin** [comment]
> Allowing users to add region-specific tile layers (that may not have worldwide coverage)

Do you have an example (which supports mapping)?

**Comment by prusswan** [comment]
It can be any of the tile layers provided at national/regional level (and possibly contain details not included in the default osm layers, as @SomeoneElseOSM described), that users can switch freely regardless of view/edit mode. Currently, search works differently on View and Edit modes, so users cannot leverage custom tile layers in View mode (where they can search by address, but only rely on OSM layers as visual reference), and under Edit mode they can't search by address.
