### ISSUE TITLE
Feature request: Add switch projection feature

### ISSUE THREAD

**Issue by c933103** [openstreetmap/openstreetmap-website#2656]
Currently, the tile map in OpenStreetMap website is rendered with the Mercator projection, which distorted high-altitude area and make the area near the pole left unrendered.
TO facilitate the mapping of polar area, It can be fixed by rendering and displaying the map in polar stereographic projection, which will probably need fewer tile/server resource because it cover less area than a full new global map style.
According to my understanding, while the default Mapnik style does not support polar projection by default, from other styles forked from Mapnik like https://github.com/GeoSensorWebLab/awm-styles it seems the mapstyle itself can be relatively easily adopt to display polar projection?
While simply adopting mapnik into polar projection would result in less than optimal rendering, but I guess doing so could encourage stylesheet to improve according to the rendering result.
Other than rendering map tile in sterographic projection, to add support for it it would also be necessary for the website to be able to correctly determine coordinate in sterographic projection and have buttons that enable such switch if it is to be implemented.

**Comment by tomhughes** [comment]
This project is about the web site and it can only display the tiles that other projects make available - with server side bitmap tiles like all our current layers use questions of projection are outside of our control.

As and when there are tiles available in other projections you are welcome to propose adding those layers through the normal mechanisms which I believe I have already pointed out to you on another ticket.

**Comment by c933103** [comment]
Where can I contact eith those responsible for maintaining tile server?
