### ISSUE TITLE
Cannot query lake

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2662]
https://www.openstreetmap.org/query?lat=23.80115&lon=121.23297 cannot find the lake in the middle of the map.

**Comment by jidanni** [comment]
https://www.openstreetmap.org/way/780736264

**Comment by jidanni** [comment]
However with a bigger lake,
https://www.openstreetmap.org/query?lat=23.9306&lon=121.5113
the query finds it.

**Comment by tomhughes** [comment]
There are two different searches - one for "nearby features" which look for things which overlap the search radius and one for "enclosing features" which looks for things which surround it.

It sounds like you want to be looking at the second, which does seem to find the lake here correctly.
