### ISSUE TITLE
Asset was not declared to be precompiled in production errors

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/openstreetmap-website#2663]
When running the installation steps in [INSTALL.md](https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md) I get errors on `bundle exec rake test:db`

```
rails test test/system/issues_test.rb:25

.......................................................................................................................................
......................................E

Error:
UserCreationTest#test_user_create_submit_duplicate_username:
ActionView::Template::Error: Asset `i18n/ba.js` was not declared to be precompiled in production.
Declare links to your assets in `app/assets/config/manifest.js`.

  //= link i18n/ba.js
and restart your server
    app/views/layouts/_head.html.erb:8
    app/views/layouts/_head.html.erb:1
    app/views/layouts/site.html.erb:3
    app/controllers/users_controller.rb:247:in `create'
    config/initializers/compressed_requests.rb:27:in `call'
    config/initializers/cors.rb:9:in `call'
    test/integration/user_creation_test.rb:66:in `block (4 levels) in test_user_create_submit_duplicate_username'
    test/integration/user_creation_test.rb:65:in `block (3 levels) in test_user_create_submit_duplicate_username'
    test/integration/user_creation_test.rb:64:in `block (2 levels) in test_user_create_submit_duplicate_username'
    test/integration/user_creation_test.rb:63:in `block in test_user_create_submit_duplicate_username'
    test/integration/user_creation_test.rb:60:in `each'
    test/integration/user_creation_test.rb:60:in `test_user_create_submit_duplicate_username'



``

**Comment by tomhughes** [comment]
Because you haven't built  the translations with `bundle exec rake i18n:js:export` first.

**Comment by spilth** [comment]
I am also encountering this issue from a fresh check out and trying to run the test suite locally.

It seems like either `bundle exec rake i18n:js:export` or `rake assets:precompile` alleviates this issue.

Is there any interest in getting these (and other) steps into `bin/setup`?

**Comment by tomhughes** [comment]
No because neither should be necessary in a development environment - they are only required when running in production as far as I know.

Whether you have actually precompiled an asset has nothing to do with whether it is listed as needing precompilation anyway.

**Comment by mmd-osm** [comment]
Related issue https://github.com/openstreetmap/openstreetmap-website/pull/2664 was closed as abandoned. Closing here.
