### ISSUE TITLE
Status of plural translations

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2666]
We recently had a plural translation that was missing the "other" key, which [caused errors in production](#2645).  We [now run tests](a221aabe3c65ed5a71914f52fe959983f8afde72) to make sure that every translation has the "other" key.

However, there are still some wrinkles to be ironed out, and I'm not sure what the status is of these:

* @translatewiki commits directly to master, so we end up with a failing test in master and then other pull requests (like #2664) end up failing too.
* It's not clear to me if @translatewiki are updating their system to prevent missing "other" keys in plural translations, or if that has been done already.
* It's also not clear to me what the situtation is for e.g. Polish translators, where for integers we only need the one/few/many keys (other is used for decimals, afaik). Will translatewiki automatically duplicate the "many" key into "other" when they push? Or will translators have to manually duplicate it? Or should we be building a list of such situations and ignoring the missing other key for specific languages in our tests?

**Comment by tomhughes** [comment]
As far as I know Polish is the language where it's an issue and I'm not really interested in making a special case for it, especially as you'd have to consider whether any of the translations allowed non-integer values.

On top of that if you don't require `other` then you have to require all the other keys instead, as it will back to other if one of those is missing and you will still get an error rather than it falling back to english.

**Comment by Nikerabbit** [comment]
1) If you'd like we can start sending pull requests instead. Basically we need a branch with force push rights, and our scripts will automatically create a pull request for each commit, or update the open pull request if it is not merged yet.
2) We have deployed validators that prevent new translations without all defined plural forms.
3) I filed [a task](https://phabricator.wikimedia.org/T256225) which proposes a new syntax to signal repetition of forms. It is not scheduled yet. Feedback is welcome (I can relay there if you leave it here). We are also soon deploying a quick fix which will fill the key `other` with latest available translation (in the canonical order of plural keywords) that is provided.

**Comment by tomhughes** [comment]
@Nikerabbit there's a handful of legacy ones (https://github.com/openstreetmap/openstreetmap-website/commit/a2620bddfefab8bc3341f12e5572df20de693d97) that I keep having to remove - could you flush those on the TW side or something to force retranslation?

**Comment by Nikerabbit** [comment]
See above, in the next export after the deployment the quick fix, those should have `other` form present.

**Comment by gravitystorm** [comment]
>     1. If you'd like we can start sending pull requests instead. Basically we need a branch with force push rights, and our scripts will automatically create a pull request for each commit, or update the open pull request if it is not merged yet.

Do we have the ability to make a PR that gets merged automatically if all the tests pass?

**Comment by gravitystorm** [comment]
I mean, I like the idea of creating a PR so that we don't commit things directly to master without running the tests, but at the same time, I'm not offering to keep on top of all the additional PRs given that things run smoothly 99% of the time. So if we can run the tests, and then commit if they pass, that would work for me.

**Comment by tomhughes** [comment]
We can probably write an action to automate it.

**Comment by maro-21** [comment]
>It's also not clear to me what the situtation is for e.g. Polish translators, where for integers we only need the one/few/many keys (other is used for decimals, afaik). Will translatewiki automatically duplicate the "many" key into "other" when they push? Or will translators have to manually duplicate it? Or should we be building a list of such situations and ignoring the missing other key for specific languages in our tests?

I've recently added `other` key to all pluralizable Polish translations. So there's no need to worry about it. I had to add it because without it the translations wouldn't appear, although this key isn't necessary because the argument of a function is always an integer and `other` is used for decimal numbers.

But there is some problem with Translatewiki - you've [changed](https://github.com/openstreetmap/openstreetmap-website/commit/05858662021553ce0b86720dd62ccbd08788979f) the text of copyright information, but Translatewiki doesn't inform about it like it used to in the past.

The information about outdated translation is visible when I enter this translation, but it's not it the section "Outdated".

**Comment by Nikerabbit** [comment]
> The information about outdated translation is visible when I enter this translation, but it's not it the section "Outdated".

Thanks for notifying about this issue. We have corrected it manually and investigating the the cause.

**Comment by gravitystorm** [comment]
Everything has been working smoothly recently, and so I'm reluctant to make unnecessary work.

>  If you'd like we can start sending pull requests instead. Basically we need a branch with force push rights, and our scripts will automatically create a pull request for each commit, or update the open pull request if it is not merged yet.

... and ...

> We can probably write an action to automate it.

... would be my preferred approach, if we ever need to change things in the future.

**Comment by maro-21** [comment]
> 2\. We have deployed validators that prevent new translations without all defined plural forms.

See #3997
