### ISSUE TITLE
New polygons containing natural = * and landuse = * tags are not being rendered

### ISSUE THREAD

**Issue by Edwrom** [openstreetmap/openstreetmap-website#2677]
New polygons containing natural = * and landuse = * tags are not being rendered

**Comment by lonvia** [comment]
Please provide an example.

**Comment by tomhughes** [comment]
Also this is not a web site issue, it's either an issue with the style (https://github.com/gravitystorm/openstreetmap-carto/) or with the data importer (https://github.com/openstreetmap/osm2pgsql/) or some sort of operational issue (https://github.com/openstreetmap/operations/) but if you can provide an example then we can figure out which.
