### ISSUE TITLE
Provide link to RapiD in edit drop down menu

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/openstreetmap-website#2708]
I'm sure this is probably going to get a lot of cynical replies "because Facebook," but it would be cool if there was a link to or at least mention of the RapiD editor in the edit drop down menu. As it's been an extremely useful editor to people, including myself, in helping map less mapped areas and it doesn't seem like a lot of people know about it. Which I'm sure some people reading this will be grateful of, but there's links to/mentions of JSOM and Merkaartor (whatever that is) already and OSM is better served by listing the options instead of playing favorites IMO. 

In the case of RapiD, it serves a particular niche and divergent enough from iD Editor to justify it being mentioned so people will know about it and can use it if they want to. Regardless of who owns it. Statistically RapiD is currently the 8th most used editor. Which is only two behind the popularity of Potlatch 2. Whereas, Merkaartor is the 14th most used. It really doesn't make sense to mention Merkaartor when it's that low and not also mention RapidiD.

**Comment by HolgerJeromin** [comment]
This would at least need an OK from the developers and/or hoster of the software.

**Comment by Adamant36** [comment]
> This would at least need an OK from the developers and/or hoster of the software.

Good call. I hadn't thought of that. I can ask about it on their Github repository if you think that would be best. Or maybe @bhousel can OK it since he works for them now.

**Comment by woodpeck** [comment]
Random recent post from the imports mailing list:

"Since RapID is used as an editor in OSM and the buildings were directly available via RapID, our team mistakenly assumed that no additional documentation would be needed to kick-start the process. During the implementation of the second workflow, the DWG flagged the exercise and informed our team that adding AI-generated building footprints to OSM is considered an import and, because no discussions were facilitated about the import through the mailing list, this exercise was in violation of the import guidelines"

if RapID were added as an "official" editor, we would have to make sure that only those external data sets for which the import process has been cleared are available in it, to avoid all-too-frequent misunderstandings like the above. This is probably not too difficult, but we'd have to maintain a fork of RapID where we control what is offered, rather than the developers of RapID who might have their very own perspective on OSM community standards.

**Comment by SomeoneElseOSM** [comment]
Should any new editor be globally available?  Currently that's the case for new tiles layers: https://wiki.openstreetmap.org/wiki/Featured_tile_layers/Guidelines_for_new_tile_layers .  US sanctions mean that all the data data that RapiD uses isn't avaiilable everywhere (see https://github.com/facebookincubator/RapiD/issues/58 ).  It may be that "having the editor available without some underlying data" is an option I guess.

**Comment by Adamant36** [comment]
> we'd have to maintain a fork of RapID where we control what is offered, rather than the developers of RapID who might have their very own perspective on OSM community standards.

That's a ridiculous standard that you know they aren't going to go for it. Anyway, if that's the bar for being mentioned on the website then it should apply to every other piece of software the website mentions. There's nothing special about how RapiD does things compared to any of the other editors functionality wise and the "perspective" of the developers really shouldn't be relevant to this. 

Last time I checked JOSM is the defacto software for problematic imports and no one ever chalks it up to the perspective of it's developers. Even though it's repeatedly been involved in large areas of the map being damaged since it was created. What RapiD does isn't even on the same level. It's almost a joke to call what it does is an import that the developers are responsible for. Anyway, it sounds like they are doing their part to remedy things and that there wasn't any bad intent behind the mistake. Which should be the important thing. Mistakes happen sometimes. Maybe try assuming good faith once in a while.

**Comment by tomhughes** [comment]
You're perhaps unaware of the background but there has been considerable agitation in the community recently around the way in which decisions made by the authors of popular editors can become de facto community standards.

As a result there are moves (which are nothing to do with the maintainers of this repository) to exert control over the way in which decisions are made around what means of mapping and tagging are promoted to users of those editors.

That I believe is the background to the suggestion that care is needed here.

**Comment by grischard** [comment]
@Adamant36 Calling people ridiculous is never a good idea. You can express yourself here without insulting others.

**Comment by Adamant36** [comment]
> @Adamant36 Calling people ridiculous is never a good idea. You can express yourself here without insulting others.

The I said standard is ridiculous. It should be pretty obvious to everyone, including Woodpeck, that standards aren't people. Thanks for calling me out for nothing though...:clap:...:clap:...:clap:.....:man_shrugging:

**Comment by gravitystorm** [comment]
This conversation became unconstructive really quickly. I'm going to politely but firmly suggest to everyone to take a break for a day or two, and then come back to it with a more collegiate attitude.

**Comment by simonpoole** [comment]
Just an additional fact, assuming providing more data for making a considered decision is not out of line: using RapId currently requires accepting Facebooks Terms of Service and Privacy Policy (yes this is not properly made clear in the corresponding plugin for JOSM either, but two wrongs don't make a right). A simple link would clearly not fulfill GDPR requirements on transparency and control of personal data.

**Comment by Adamant36** [comment]
> ou're perhaps unaware of the background but there has been considerable agitation in the community recently around the way in which decisions made by the authors of popular editors can become de facto community standards.

I'm semi-aware of it. Although, I don't follow the minutia of the faux outrage conversations that seem to take place regularly on the mailing list around the topic. From the experience I have had dealing with it though, things seem to be mostly overblown and based on faulty assumptions about the motivations of the people who have developed the tools a small minority of the community have a problem with. 

Not that I wan't to get into a huge conversation about it either, but there is no good shared definition of what an automated edit is. Which often leads to a lot of unfounded accusations and wastes of everyone's time. I don't put it on the developers of the editing software that the DWG (or whoever it is) can't came to an agreement on what exactly the meaning of or rules around these things are. I've seen plenty of instances where even people in the DWG can't agree. 

For instance I see it happen all the time that one of them threatens to block someone for something that another member says is perfectly fine. IMO the systemic dysfunction really needs to be worked out and there needs to be solid shared definitions of the things people have problems with before anyone can  justifiably point the finger at any one person or piece of software. That goes for certain people involved in this discussion also. 

In the meantime I don't see a problem with listing RapiD when it has the same problems JOSM does. As was pointed out by Simonpoole before his message was deleted. Otherwise, remove the recommendation to use JOSM from the site until they fix their issue. 

> As a result there are moves (which are nothing to do with the maintainers of this repository) to exert control over the way in which decisions are made around what means of mapping and tagging are promoted to users of those editors.

That said, I'm not saying care shouldn't be taken. But as far as I know the way RapiD currently works they aren't "promoting" any tags. Since they are only using the defaults that everyone is already using to map buildings and roads. I guess that could change in the future though, but maybe if you listed RapiD editor on the main site with the cavet that it will be removed when they do start promoting tags it would incentives them not to. I'd image a lot of traffic would be sent their way because of it listed on site and it's not like it's that hard to remove a link to something if it violates your terms. That's just a basic thing websites deal with and I fail to see what's special about it here. 

I don't think just because you have a link to somewhere that it means your endorsing, or responsible for, everything it does. For instance you advertise OSM meetings and conferences all the time when you have zero control over what takes place at them or who is suggesting what at the conference. I'm not up on my GDPR nuances, but I didn't think it extended to just linking to something. I'd image plenty of companies in the United Kingdom link to Facebook though.

**Comment by woodpeck** [comment]
It appears you have an axe to grind with people on the mailing lists ("faux outrage", "overblown"), or with the DWG ("systemic dysfunction"). However, this is not the place for that; what you're doing here is classic trolling, and not for the first time. Your message is carefully calculated to generate maximum agitation while superficially "only asking innocent questions", just as you frequently do on the Wiki and when discussing with other mappers.

**Comment by Adamant36** [comment]
> It appears you have an axe to grind with people on the mailing lists ("faux outrage", "overblown"), or with the DWG ("systemic dysfunction"). However, this is not the place for that;

I have zero axe to grind. I was just making an observation that a lot of people seem to get angry about things that nothing ever gets done about it, because someone else brought it up. Otherwise, I could really care less. What a few people get angry about on the mailing list isn't really relevant to anything anyway IMO. Since their opinions clearly don't represent the wider communities in most cases. It's relevant to this though because @tomhughes brought it up. That's all. I don't how you can legitimately claim me responding to someone else's message about a topic I didn't even bring up in the first place is trolling or trying to cause maximum agitation about something. Opening the issue wasn't about either of those things either. Asking for a link to RapiD be added to the main site is a completely legitimate question. Plus, it's just a fact that there's no standard or agreement on what an automated edit is. 

> Your` message is carefully calculated to generate maximum agitation while superficially "only asking innocent questions", just as you frequently do on the Wiki and when discussing with other mappers.

Yet your the one that always seems to have a bad attitude in most of the conversations I've seen you involved in. Most of your replies are overly aggressive and don't serve purpose except to make the other person look bad. So it seems more like your the one doing the trolling and trying to generate maximum agitation. Just like the message I'm responding to and your first one. Everyone here knows the faults of the developers. There was zero reason to point it out. Expect to push the buttons of people who disagree with you and feed the "everything and everyone related to iD Editor is evil" narrative. 

Also, maybe you should stop stalking my messages and edits everywhere to find things to nitpick or attack me over. Because it's been a repeated thing with you since I started editing and I'm pretty sick of it at this point. I have better things to spend my time on. I can only conclude that the way your acting now is just more of the same.

**Comment by gravitystorm** [comment]
I appreciate that people took a step back, but it appears that this conversation has again immediately become unproductive. For the sake of the work being done elsewhere in this repository, and everyone else who is subscribed to notifications, I'm closing this issue.

I make no judgement as to whether RapiD should be included or not. My judgement is only that this particular conversation is unproductive and unfortunately shows no sign of improving.
