### ISSUE TITLE
Edit dropdown is hard to use on touch devices. 

### ISSUE THREAD

**Issue by ponychicken** [openstreetmap/openstreetmap-website#271]
The target area is quite small.

**Comment by docljn** [comment]
Hello the team. This is a particularly old issue (!) and I wondered if it was still open for a reason, or had been missed?

**Comment by tomhughes** [comment]
Because nobody has volunteered a fix.

**Comment by docljn** [comment]
Thanks @tomhughes : I wanted to make sure it was still a relevant issue that the team would like help with...

**Comment by mmd-osm** [comment]
It's not clear if this still applies. The OP didn't post any screenshots, nor details about the touch device. Closing for now.

**Comment by nenad-vujicic** [comment]
Here are 2 screenshots about this:

![portrait](https://github.com/openstreetmap/openstreetmap-website/assets/25298521/0d023c20-d0c6-4a9f-8db4-e579c2a8e43a)
![landscape](https://github.com/openstreetmap/openstreetmap-website/assets/25298521/38501968-ba03-42a7-a8bc-f0b4fa4b1737)

I agree it's a little bit hard to do it (select combo's arrow) on my 6.6" smartphone. But, I'm not sure I would dare to map anything using this device :-)

Another problem (not sure if it classifies as a problem) is about missing 3 buttons in portrait orientation. During page loading, they are visible (take a look at below screenshot), but at some point disappear (probably covered up by something). Perhaps they could be moved to the same group with "GPS Traces, User Diaries, .. " or inside of new menu which could open when user pushes OpenStreetMap logo?

![loading_time](https://github.com/openstreetmap/openstreetmap-website/assets/25298521/34fa9834-01e0-4590-b68a-451eab0a0e87)

**Comment by mmd-osm** [comment]
I don’t recall if there’s already an issue out there for the second issue. If not, maybe you could create a new one. Adding new stuff in closed issues will likely not get much attention.

**Comment by AntonKhorev** [comment]
second issue: #4854
