### ISSUE TITLE
Policy about closing and blocking discussion on "controversial" topics

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/openstreetmap-website#2713]
Follow up to #2708. While I agree that topics should stay topic to a degree, it seems rather unfair to people who open issues if it can be closed by someone coming along and attacking them for opening it. Shouldn't the problem causer just be dealt with instead? By not dealing it with that, your just inviting more people to act the same way. 

On my end, I took a few days off and was just responding to what @tomhughes said about there being agitation in the community when it comes to things iD Editor does. it's not fair to me or other people that might have wanted there to be a link to RapiD on the main site that my issue isn't going to be addressed now because @woodpeck decided to derail it with his bad attitude. Your just encouraging him to act that way more in the future. Is there any way the issue can be re-opened and he just be told to shove off since he has a history of doing this kind of thing or can I open a similar one in the future or something?

**Comment by dieterdreist** [comment]
I do not understand why there should be a link to rapiD on the homepage, it
seems to be a tool for expert editors, even if it could technically be used
by everyone, there are so many potential problems that a fair share of
experience in editing OSM should be expected. These expert editors do not
need a prominent link, they know that they have to follow the automated
edits guidelines, and they know where to find it.
It is definitely not a tool you would want someone to use who make their
first steps in editing.

**Comment by Adamant36** [comment]
> It is definitely not a tool you would want someone to use who make their
first steps in editing.

@dieterdreist, Compared to JOSM though? Come on. Anyway, I didn't open this issue to re-litigate the other one at this point. I'd just like to know the best way to move forward on it in the future and I wanted to make a point about the merits of closing the issue due to the bad attitude of one person who was clearly trying to derail it.

**Comment by gravitystorm** [comment]
I have no opinion as to whether the original topic is controversial or not, as I said in the original issue.

But I can, and I will, block unproductive discussions on this issue tracker. I read every part of that issue, and almost every sentence was entirely irrelevant to any form of decision making about the topic. That's not what this issue tracker is for.

**Comment by Adamant36** [comment]
> But I can, and I will, block unproductive discussions on this issue tracker. I read every part of that issue, and almost every sentence was entirely irrelevant to any form of decision making about the topic. That's not what this issue tracker is for.

That's fair.
