### ISSUE TITLE
Must scroll left side  panel all the way back to the top to access the X closer button

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2715]
If he has scrolled down, the user cannot close the Search Results panel...

![26167-0](https://user-images.githubusercontent.com/1230959/87846830-7dc05e80-c905-11ea-8473-fa5a1d7d39a3.jpg)

without first scrolling all the way back to the top, to access the X closer button,

![25230-1](https://user-images.githubusercontent.com/1230959/87846859-a9dbdf80-c905-11ea-9ba2-bb127157b8a1.jpg)

Recommendation: have the X float above the results, always available at the top.

**Comment by jidanni** [comment]
Same problem with e.g., https://www.openstreetmap.org/relation/9170457 .

**Comment by mmd-osm** [comment]
Isn't that the same thing you've already reported in #2174?

**Comment by tomhughes** [comment]
Closing as duplicate of #2174.
