### ISSUE TITLE
Change a link to Wiki

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#2738]
I suggest changing the link to Wiki in

`Osm:Traces.index.empty html`

`Nothing here yet. <a href='%{upload_link}'>Upload a new trace</a> or learn more about GPS tracing on the <a href='https://wiki.openstreetmap.org/wiki/Beginners_Guide_1.2'>wiki page</a>.`

from https://wiki.openstreetmap.org/wiki/Beginners_Guide_1.2
to https://wiki.openstreetmap.org/wiki/GNSS_tracelog
There is more information about GPS tracing on the latter.

**Comment by mmd-osm** [comment]
I hope you don't mind that I deleted a somewhat derailed discussion on the GNSS_tracelog talk page: https://wiki.openstreetmap.org/w/index.php?title=Talk%3AGNSS_tracelog&type=revision&diff=2016418&oldid=1616321

**Comment by gravitystorm** [comment]
I'm not sure that "more information" is a compelling reason for me! I'd rather keep linking to the beginners guide, since it is less likely to be overwhelming for people who are unfamiliar with the subject.
