### ISSUE TITLE
Correct redirect links

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#2739]
- [ ] `Osm:Users.account.contributor terms.link`

from: https://www.osmfoundation.org/wiki/License/Contributor_Terms
to: https://wiki.osmfoundation.org/wiki/Licence/Contributor_Terms

- [ ] `Osm:Help-help.newMembers`

`<p><b>+ For new members</b>, please visit <a href="http://www.openstreetmap.org/user/new" target="_blank">http://www.openstreetmap.org</a> to create an account, log in, then return here to allow access to Potlatch 2 and begin editing.</p>`

add https:// to links

- [ ] `Osm:Help-help.addingFeaturesText`

add https:// to links

- [ ] `Osm:Help-help.editingFeaturesAdvText`

add https:// to links

- [ ] `Osm:Help-help.taggingFeaturesText`

correct the link from
http://wiki.openstreetmap.org/wiki/Map_features
to
https://wiki.openstreetmap.org/wiki/Map_Features

**Comment by tomhughes** [comment]
If you want to be helpful then open a PR to correct them... I don't even really know what `Osm:Help-help.taggingFeaturesText` even refers to - it doesn't look like anything that exists in our source code.

**Comment by tomhughes** [comment]
I think those are potlatch2 messages you are referring to, which would need to be raised at https://github.com/systemed/potlatch2/issues not here.

**Comment by tomhughes** [comment]
The `Osm:Help-help.taggingFeaturesText` one for example is here https://github.com/systemed/potlatch2/blob/master/l10n/locale/en_GB/help_dialog.properties#L36.

**Comment by maro-21** [comment]
These were the variables from TranslateWiki, I thought they're the same in the code.
I've rewritten the first post, please reopen.

**Comment by tomhughes** [comment]
It doesn't matter how much you rewrite it - those strings are from the potlatch2 project not this project.

**Comment by tomhughes** [comment]
The Translatewiki project covers both this repository and the potlatch2 one - the strings you are interested in live in the potlatch2 repository, not this one.
