### ISSUE TITLE
Flash support for :alert

### ISSUE THREAD

**Issue by openbrian** [openstreetmap/openstreetmap-website#2743]
These days it seems there are two conventional types of flashes: notices and alerts.  After switching one of my notices to an alert, I noticed it did not appear on the following page.

It looks like app/views/layouts/_flash.html.erb only handle :error, :warning, and :notice.

I actually like :error and :warning better than :alert.

Do you think we should add support for :alert in _flash.html.erb, or should I just use the types of flashes we have defined.  The only downside I see is code becomes a little more verbose.

```ruby
      redirect_to @thing, :flash => { :error => "It failed." }
```
vs
```ruby
      redirect_to @thing, :alert => "It failed."
```

:alert and :notice become somewhat conventional in gems/actionpack-6.0.4.2/lib/action_controller/metal/flash.rb line 11, though other flashes are supports on line 54.

**Comment by tomhughes** [comment]
We can actually add new types with `add_flash_types` which would then behave the same as the built-in ones.

**Comment by openbrian** [comment]
Cool.
