### ISSUE TITLE
Add banner for OSM16 events. 

### ISSUE THREAD

**Issue by naveenpf** [openstreetmap/openstreetmap-website#2745]
![OpenStreetMap_16th_birthday_v2](https://user-images.githubusercontent.com/12662835/89138479-5bf7e600-d559-11ea-9c61-ae08c046a582.jpg)

Link:- https://wiki.openstreetmap.org/wiki/OpenStreetMap_16th_Anniversary_Birthday_party

Till Aug 9, 2020

**Comment by gravitystorm** [comment]
Implemented by #2752.
