### ISSUE TITLE
iD's json resources are not being served with gzip

### ISSUE THREAD

**Issue by jleedev** [openstreetmap/openstreetmap-website#2762]
The following resources are not being served with gzip:

```
  'https://www.openstreetmap.org/iD/data/discarded.min.json',
  'https://www.openstreetmap.org/iD/data/languages.min.json',
  'https://www.openstreetmap.org/iD/data/locales.min.json',
  'https://www.openstreetmap.org/iD/data/imagery.min.json',
  'https://www.openstreetmap.org/iD/data/preset_categories.min.json',
  'https://www.openstreetmap.org/iD/data/preset_defaults.min.json',
  'https://www.openstreetmap.org/iD/data/preset_presets.min.json',
  'https://www.openstreetmap.org/iD/data/preset_fields.min.json',
  'https://www.openstreetmap.org/iD/data/keepRight.min.json',
  'https://www.openstreetmap.org/iD/data/qa_data.min.json',
  'https://www.openstreetmap.org/iD/data/deprecated.min.json',
```

i.e. everything under `https://www.openstreetmap.org/iD/data/`.

It looks like these are about 5.2 MiB and could gzip down to 0.95 MiB.

**Comment by tomhughes** [comment]
The real problem here is actually that the files aren't being served through the assets pipeline and whilst I can easily add them to the files the asset pipeline handles that won't help until iD adds a way for us to give it the asset names.

@quincylvania is there a  way for us to give iD alternate paths for these files like we do for the local files?

**Comment by tomhughes** [comment]
I suspect the same is true for the files in `mapillary-js` and `pannellum-streetside`.

**Comment by tomhughes** [comment]
So we do actually have a generic asset map that we give to iD and I've added all these things to the served assets and while mapillary and streetside do now appear to be loading via the asset pipeline the JSON files aren't so I think that will need a change to iD to make it use the asset map when loading them.
