### ISSUE TITLE
Red marker not displayed on embedded html map

### ISSUE THREAD

**Issue by BrunoGGM** [openstreetmap/openstreetmap-website#2763]
Red marker not displayed on embedded html map

Embedded map
`<iframe scrolling="no" marginheight="0" marginwidth="0" src="https://www.openstreetmap.org/export/embed.html?bbox=-92.1376,18.0906,-92.1376,18.0906&amp;layer=mapnik&amp;marker=18.0906,-92.1376" width="100%" height="300" frameborder="0"></iframe>`

Result
![map](https://user-images.githubusercontent.com/21027151/89747805-fc806580-da85-11ea-9ed0-5f056ca55ce3.PNG)
![osm error](https://user-images.githubusercontent.com/21027151/89747836-1ae66100-da86-11ea-93d6-84fe80e7ac96.PNG)

**Comment by matteoquintiliani** [comment]
From a link like this

https://www.openstreetmap.org/export/embed.html?bbox=10.130946976728%2C46.800271357633%2C11.189053023272%2C47.519728642367&layer=mapnik&marker=47.16%2C10.66

the following 2 icons are not accessible:

https://www.openstreetmap.org/images/marker-icon.png

https://www.openstreetmap.org/images/marker-shadow.png

The error returned is:

> 500 Internal Server Error
> If you are the administrator of this website, then please read this web application's log file and / or the web server's log file to find out what went wrong.

**Comment by HolgerJeromin** [comment]
ref #2759
