### ISSUE TITLE
Display node/way id in feature editor

### ISSUE THREAD

**Issue by convissor** [openstreetmap/openstreetmap-website#2771]
In the iD editor's "Edit feature" pane, it would be helpful to be able to see the id number of the feature being edited.

Sure, one can exit edit mode and then do a query of surrounding features. But that takes time and is a bit clumsy.

Would help me when I want to download specific items into JOSM. May help others in various ways.

I can make a pull request if someone points me where to look in the code.  Cloned it and did some ack'ing, but didn't turn up an obvious spot.

**Comment by tomhughes** [comment]
You can report iD issues in the iD repository at https://github.com/openstreetmap/iD/issues.

**Comment by bhousel** [comment]
Either the Measurement or History panes will display the OSM id of the selected feature:

<img width="693" alt="Screen Shot 2020-08-13 at 5 23 48 PM" src="https://user-images.githubusercontent.com/38784/90188616-cabf1580-dd89-11ea-9ecc-8b66bd0a227c.png">


<img width="449" alt="Screen Shot 2020-08-13 at 5 24 57 PM" src="https://user-images.githubusercontent.com/38784/90188717-f17d4c00-dd89-11ea-9a9a-e7a60c825ece.png">

Please do not open issues in the iD repository just to have questions answered about how to use the software.  iD is currently unmaintained.  

You can ask your questions through any of the many other chat channels in OSM, or ask on https://help.openstreetmap.org/

**Comment by convissor** [comment]
Oh, thank you @bhousel for that pro tip. Will be helpful for me in the future.

(I humbly suggest that keyboard incantations is sub-optimal UX design.)

**Comment by bhousel** [comment]
> (I humbly suggest that keyboard incantations is sub-optimal UX design.)

At the time it the keyboard incantation was a compromise between me and someone who didn't want iD to have this feature at all.

The latest version of iD has some checkbox somewhere to turn these on and off.

**Comment by convissor** [comment]
Ah, the joys of collaboration. :)

**Comment by HolgerJeromin** [comment]
I always use the link on the left bottom of the edit pane.
![image](https://user-images.githubusercontent.com/2410353/90253041-d3beee00-de40-11ea-9b7e-788afe36560c.png)

**Comment by mikelmaron** [comment]
**Correction: it is quite ok to report iD issues in the iD repository at https://github.com/openstreetmap/iD/issues**

@quincylvania is iD's maintainer. While it's true his role is not currently supported, but the OSM Foundation is actively [discussing](https://lists.openstreetmap.org/pipermail/osmf-talk/2020-August/006997.html) and looking for funds for this role. 

In any case, even if @quincylvania can't answer now, someone else from the community might.
