### ISSUE TITLE
Failing styling of button classes a.button.{sign-up,learn-more,load_more}

### ISSUE THREAD

**Issue by mikini** [openstreetmap/openstreetmap-website#2774]
For some days I've noticed something was looking odd in the OSM UI. Seems like the styling is broken for at least the classes mentioned, they would usually have blue filled outlined around them (like buttons in "Share" and "Export" which are not using the "button" class).

I see this in both English and Danish locale using Firefox/Linux, Chromium/Linux, Firefox/Windows, IE 11/Windows.

Both [learn-more](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/stylesheets/common.scss#L467) and [load_more](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/stylesheets/common.scss#L713) are referenced in common.scss but sign-up isn't present at all. I haven't got enough CSS and Sass knowledge to analyse further.

# Screenshots with element inspections using Firefox

![a button sign-up](https://user-images.githubusercontent.com/1330166/90227522-018e3d80-de15-11ea-948b-06d02bb154bd.png)
![a button learn-more](https://user-images.githubusercontent.com/1330166/90227524-0226d400-de15-11ea-9384-143a070bf933.png)
![a buttton load_more](https://user-images.githubusercontent.com/1330166/90227525-02bf6a80-de15-11ea-9c4d-06389943f278.png)

**Comment by tomhughes** [comment]
When you say a "few days" do you have any idea how long?

Is this just with the "new user" panel, or are you seeing it anywhere else?

**Comment by gravitystorm** [comment]
I think it's a problem with buttons that aren't inside standard-forms. That change was made in 627f2493faa77336e7dcb13abb92dc547ee4db9f and merged on the 5th as part of the bootstrap forms work.

My preferred solution is to change these buttons to use the bootstrap button classes. I'll look at that next week unless someone beats me to it.

**Comment by mikini** [comment]
@tomhughes Didn't note exactly when first seeing it, thought it might be a temporary fluke caused by the bootstrap work that would be picked up quickly. "A few" might be an understatement, so the 5th would also be plausible.

The last screenshot is an ordinary Nominatim search ([this one](https://www.openstreetmap.org/search?query=Esbjerg) actually).

A quick tour of the website also finds that class "load_more" is used and not styled on the [changset history page](https://www.openstreetmap.org/user/mikini/history).
