### ISSUE TITLE
Missing map key in the bicycle layer for violet bicycle ways

### ISSUE THREAD

**Issue by Sovxx** [openstreetmap/openstreetmap-website#2785]
Hi,
There is no explanation for what violet way is :
![violet](https://user-images.githubusercontent.com/12556923/90828916-2287ee80-e33f-11ea-8d8c-6cae7210c62c.png)

**Comment by mnalis** [comment]
I would be interested to make PR to fix those colors in legend as identified by @systemed, any objections?
