### ISSUE TITLE
Vagrant setup not working

### ISSUE THREAD

**Issue by strct** [openstreetmap/openstreetmap-website#2793]
Following the instruction in [VAGRANT.md](https://github.com/openstreetmap/openstreetmap-website/blob/master/VAGRANT.md) leads to the following error message and a non-working setup.

```
$ vagrant up
...
    default: /usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe'
    default: : 
    default: can't find gem bundler (>= 0.a) with executable bundle
    default:  (
    default: Gem::GemNotFoundException
    default: )
    default: 	from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
    default: 	from /usr/local/bin/bundle:23:in `<main>'
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
$
```
[full log](https://gist.github.com/strct/39124d1ea72b2dcd04008940a103a595)

Using Ubuntu 20.04 and libvirt

**Comment by tomhughes** [comment]
It's probably still installing bundler 1.x or something - it's not really maintained.

**Comment by tomhughes** [comment]
No idea if it will help but I've pushed e9483dcc5d51e034a9ef37446df1894cbdc57ee5 to try and modernise things.

**Comment by strct** [comment]
Thanks for this fast response and fix! With that change valgrant works for me.
