### ISSUE TITLE
Coordinate search giving lat,lon and lon,lat result has unhelpful zoom level

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/openstreetmap-website#2798]
A coordinate search, giving lat,lon and lon,lat results, have clickable map locations which retains the current zoom level.

If zoomed out to a low zoom level, e.g. 5, as starting maps will be, this gives a particularly unhelpful result.

I suggest this instead be changed to 16, when the zoom level is below that, as that probably gives a reasonable balance for city/town and rural areas.

![Screen Shot 2020-08-28 at 17 39 05](https://user-images.githubusercontent.com/361423/91591808-6a1d0480-e955-11ea-8179-d15e022081e2.png)

**Comment by tomhughes** [comment]
No, a coordinate search preserves the current zoom level.

**Comment by mvl22** [comment]
(Thanks, Tom. Yes, indeed. I edited my original posting when I realised, probably just before you posted a reply. However, the behaviour still remains undesirable.)

**Comment by mmd-osm** [comment]
Closing in favor of #5028 (duplicate)
