### ISSUE TITLE
Mention diary entry last update time, not just creation time

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2801]
A [typical diary entry](https://www.openstreetmap.org/user/jidanni/diary/392371) says just e.g.,

`Posted by Nibblesome on 3 March 2014 in English (English)`

But as there is an edit button, the user might have updated it 88 times making it 99% bigger, etc. So be sure to also say

`Last updated 31 August 2020`

**Comment by harry-wood** [comment]
_"88 times making it 99% bigger"_.  They might have done that, or radically changed the diary entry in any other way. e.g. You might link to something you agree with, but then later find it was edited to be something you disagree with. So it _might_ be useful to you, or to folks following link, to know that it was "last edited at x time".

(I think we don't have the data on the fact that a diary was edited 88 times if that's what you mean)

This suggestion has to be weighed against just that extra bit of UI clutter. Also we must ask ourselves, is it an undue annoyance to the person who is writing a diary entry, that they can no longer fix a typo without it displaying that they have edited it? Probably not. I think I agree with this suggestion.

Should it be on the diary list page https://www.openstreetmap.org/diary too, or only when displaying a single diary entry?

**Comment by jidanni** [comment]
> Should it be on the diary list page https://www.openstreetmap.org/diary too, or only when displaying a single diary entry?

Well the former is so fresh (that it even shows entries that the user isn't finished fixing the formatting) so it is no big deal.
