### ISSUE TITLE
JOSM cannot upload new features to Rails local database

### ISSUE THREAD

**Issue by harry-wilson** [openstreetmap/openstreetmap-website#2819]
We've developed a Rails port to create a local instance of OpenStreetMap. The process is accomplished by importing a planet OSM file in country extent (3GB) using osmosis and then start editing. The problem is when we edit or delete existing features, upload process is successful but for new features with negative Ids in JOSM it keep retrying and the upload failed with following error:

`josm reported an internal server error. This is most likely a temporary problem. Please try again later.`

Then we've check the Rails log file errors as follow:

`Node Create (1.0ms)  INSERT INTO "current_nodes" ("latitude", "longitude", "changeset_id", "visible", "timestamp", "tile", "version") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["latitude", 357024772], ["longitude", 513655556], ["changeset_id", 9], ["visible", true], ["timestamp", "2020-09-07 09:14:37.601015"], ["tile", 3441741884], ["version", 1]]
  ↳ app/models/node.rb:248:in block in save_with_history!'
   (0.1ms)  ROLLBACK
  ↳ app/controllers/api/changesets_controller.rb:86:in upload'
API threw unexpected ActiveRecord::RecordNotUnique exception: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "current_nodes_pkey1"
DETAIL:  Key (id)=(39) already exists.`

As there is id = 39 in original file. shouldn't Rails check for not existing ids for new features in JOSM?

**Comment by tomhughes** [comment]
Did you load data into your database via some sort of back door? If you did then you need to reset the sequences in the database so that it knows where to start allocating new IDs or else it will try and allocate IDs that overlap with the data you loaded.

**Comment by harry-wilson** [comment]
I've used osmosis to load osm file into Rails database. How can reset sequence of database? Does the existing osm_id of features change with resetting sequence?

**Comment by tomhughes** [comment]
No the IDs of existing features won't change, this is just about resetting the "next ID" counters in the database.

You should ask the omosis developers how to tell it to reset them I guess.

**Comment by harry-wilson** [comment]
I think this is related to sequence of IDs in database and not osmosis.

**Comment by tomhughes** [comment]
Yes but osmosis made incomplete changes to your database - it added new data but didn't modify the sequences to reflect that. That is a bug in osmosis.

If you change the database other than using our code then you get to keep the pieces, or the people that wrote the broken tools you used to do so do.

If you want to fix it yourself then you will need to use the [ALTER SEQUENCE](https://www.postgresql.org/docs/12/sql-altersequence.html) command:

```
ALTER SEQUENCE changesets_id_seq RESTART WITH n;
ALTER SEQUENCE current_nodes_id_seq RESTART WITH n;
ALTER SEQUENCE current_ways_id_seq RESTART WITH n;
ALTER SEQUENCE current_relations_id_seq RESTART WITH n;
```

Choosing values for `n` that are higher than any existing objects.

**Comment by harry-wilson** [comment]
Thanks for your clarification about the bug. I guessed for new features it uses the vacant Ids in database.

**Comment by migurski** [comment]
My best guess is that the change should be made near here: https://github.com/openstreetmap/osmosis/blob/master/osmosis-apidb/src/main/java/org/openstreetmap/osmosis/apidb/v0_6/impl/ChangeWriter.java#L1001-L1006

Harry I’m lightly maintaining Osmosis and I’d be happy to fix this if you can supply a minimal test case.
