### ISSUE TITLE
View History of ways - make nodes of each version collapsed

### ISSUE THREAD

**Issue by francwalter** [openstreetmap/openstreetmap-website#2823]
Hallo
I was looking into the [Way History: 611803221](https://www.openstreetmap.org/way/611803221/history) which has at the moment 31 versions. Each version has many, many Nodes, e.g.:

![grafik](https://user-images.githubusercontent.com/927269/92700060-aafe1b80-f34e-11ea-94a4-a9c340a2be94.png)
 
... and so on...
And to get to the next version number it is a lot of scrolling. 

It would be great if each version would be by default collapsed, at least the nodes section, so in scrolling I would first see only the versions with the Nodes maybe as a "[Collapsible](https://www.w3schools.com/howto/howto_js_collapsible.asp)".

Example:

![grafik](https://user-images.githubusercontent.com/927269/92702774-ddf5de80-f351-11ea-9039-4e5f78d14ff7.png)

Only a click on the "Nodes" would expand them (I edited the source to show it like that, obviously beside the "Nodes" some Icon to uncollapse would be neccessary).

Is this possible or would it be too much Browser-Rendering? Already now the loading of all versions takes a good bit of time.
Thanks.
frank

**Comment by dieterdreist** [comment]
> Only a click on the "Nodes" would expand them (I edited the source to show it like that, obviously beside the "Nodes" some Icon to uncollapse would be neccessary).
> 


it could show „34 Nodes“, i.e. include the amount

**Comment by tordans** [comment]
The html-tags <details> and <summary> might be a way to solve this without a lot of extra css/js. More at https://css-tricks.com/quick-reminder-that-details-summary-is-the-easiest-way-ever-to-make-an-accordion/ for example.

And in case Bootstap 4 + the needed JS is present, https://getbootstrap.com/docs/4.0/components/collapse/ could help.
