### ISSUE TITLE
no-break spaces showed HTML-encoded in my profile

### ISSUE THREAD

**Issue by JulienPalard** [openstreetmap/openstreetmap-website#2829]
In https://www.openstreetmap.org/user/sizeof I see:

     Dernière modification (il y a environ 1 an)&nbsp;: "Created a restaurant" 

the `&nbsp;` is an HTML-encoded no-break space, I bet this comes from french translation. but I have no rights to edit those (yet).

**Comment by mmd-osm** [comment]
Translations are managed exclusively on https://translatewiki.net/wiki/Translating:OpenStreetMap

"latest edit" would be respective key you need to change on Translatewiki according to: https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/fr.yml#L2524

**Comment by tomhughes** [comment]
Yes we can't take changes to translations here, they need to go via TranslateWiki I'm afraid.
