### ISSUE TITLE
JSON for user details API endpoint

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#2835]
Copying over from https://github.com/openstreetmap/operations/issues/377#issuecomment-687853795 so it doesn't get lost

Proposed implementation similar to: https://github.com/mmd-osm/openstreetmap-website/commit/0fb725ea611e7788a05bcb39bbf65ccdfe7ae505

@tomhughes probably needs to fill in a bit more details here, I have no idea what Discourse actually needs here.

**Comment by tomhughes** [comment]
It doesn't care much - it just wants to fetch something and you can optionally tell it to fish out certain keys from the JSON and use them as the username, email etc. The only mandatory attribute is some sort of unique ID which is fine.

Full documentation is https://meta.discourse.org/t/oauth2-basic-support/33879.

**Comment by mmd-osm** [comment]
I don’t think we expose the user’s email in XML. It this train needed or would some fake address do as well?

**Comment by tomhughes** [comment]
The email is entirely optional - if it's there discourse can use it. If it's not then that's fine as well.

**Comment by simonpoole** [comment]
> The email is entirely optional - if it's there discourse can use it. If it's not then that's fine as well.

Good, as exposing the email would require larger policy changes and have rather far reaching consequences.

**Comment by gravitystorm** [comment]
> Proposed implementation similar to: [mmd-osm@0fb725e](https://github.com/mmd-osm/openstreetmap-website/commit/0fb725ea611e7788a05bcb39bbf65ccdfe7ae505)

Could your implementation be made into a pull request, or is there some reason to take a different approach?

**Comment by mmd-osm** [comment]
I didn't have enough time for unit tests, and the JSON result might need some further tweaking. I moved the code to a pull request now, but it still needs some more polishing.
