### ISSUE TITLE
shift+drag map zoom not working on safari

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/openstreetmap-website#2836]
I just noticed that shift+drag does not open a zooming window on the map in Safari Version 13.1.2 (15609.3.5.1.3)
It works on Firefox (same machine).

**Comment by mmd-osm** [comment]
Try on https://leafletjs.com/, if you encounter the same issue there, it's an upstream issue with Leaflet and has nothing to do with this repo.

**Comment by dieterdreist** [comment]
you're right, it is an upstream issue. Sorry.
