### ISSUE TITLE
Missing cannonical URL for search engines on blog index pages

### ISSUE THREAD

**Issue by tordans** [openstreetmap/openstreetmap-website#2851]
Hi, unfortunately I don't have the time to fully debug this, but I will post my findings and maybe someone can pick it up.

**Issue:**

I was looking for this blog post https://www.openstreetmap.org/user/Supaplex030/diary/393423 via the Google Image Search https://www.google.com/search?q=supaplex+parkpl%C3%A4tze+openstreetmap&sxsrf=ALeKk02JDhRGUouiU8tP9ztjwoVIuWM0tg:1601064638585&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi8ta3IjoXsAhWC_KQKHd9vBt8Q_AUoAXoECAwQAw&biw=1403&bih=798 which shows the image of the blogpost that I am looking for. 

But: The search links me to this page https://blogs.openstreetmap.org/?viewType=Print&viewClass=Print

I don't know what this page is, but its not the blogpost details page and it looks like some special case page that should not be in the index.

**Thoughts:**

As I said, I did not debug further, but IMO the ideal case would be:

1. make sure google only sees the show-, not the index-views:

  * IMO the best practice would be, to have the blog-index pages on `<meta name="robots" content="follow,noindex">`
  * Only the show-pages should be `<meta name="robots" content="follow,index">` (which is the default)

2. make sure google understands the relation between outputs that show the same content and only has the primary output in the index:

  * All non-primary-output formats, should have a `<link rel="canonical" href="https://example.com/kleider/gruene-kleider"/>` to the primary output format
https://support.google.com/webmasters/answer/139066?hl=de

Update: In this case, this seems to boil down to informing google that those params `?viewType=Print&viewClass=Print` should not be in the search result.

Maybe https://search.google.com/search-console can help understanding an debugging this.

Update: Maybe this can also be solved via this https://support.google.com/webmasters/answer/6080548?hl=de

**Comment by tomhughes** [comment]
If you have a problem with what Google link their search results to maybe you should complain to Google.

At least if you're going to complain to us try and explain what it is you want us to change and why. You use a lot of words here which I'm sure mean something to you but are entirely meaningless to me, not that I have any great inclination to alter our output to panders to Google's latest desires anyway.

**Comment by tomhughes** [comment]
I'm particularly unclear what the index pages have to do with anything since you presumably wanted it to take you to the detail page not the index page?

**Comment by tomhughes** [comment]
I mean the page with that image literally has what you ask for in the title of this issue, a canonical URL in the header:

```
<link href="https://www.openstreetmap.org/user/Supaplex030/diary/393423" rel="canonical" />
```

It's hardly our fault if Google ignore that and do their own shit!

**Comment by tordans** [comment]
I looked into this some more and created two PRs to fix the issue.

Those PR tell google to follow all links on the index pages but not put those index-pages in the google index. Instead, the actual blogpost will be added to the index.

This is the recommended SEO practise for those situations.

The part in my initial Issue about canonical tags is obsolete since the noindex will solve the issue of params indirectly.

**Comment by harry-wood** [comment]
I wonder what's the best practice with index pages (pages containing multiple blog posts which each have a more canonical url elsewhere). I wouldn't mind betting we'd be better off just leaving google to figure it out.

The thing is google may decided not to index an individual diary entry at all. Given a choice between this being findable in google via a confusing index page, or _not findable at all_, we'd be better off leaving index pages to be indexed. Meanwhile if a diary entry is popular enough, people will tend to link to the canonical URL and google will know to put it first.

It's weird that https://blogs.openstreetmap.org would outrank the canonical https://www.openstreetmap.org/diary which it links to. I suspect this may be symptom of the way google will aggressively _downrank websites which are hosting spam_. Hopefully our rankings improved since the "Report" features, but we still do have bits of lingering spam (I just found some using... google!)

**Comment by tordans** [comment]
@harry-wood this is the best practise for this situation. 

Right now, Google needs to figure out by itself whether to put the content of a blogpost into the search index and link to the index page or the details page. This is my initial issue above. Having google link to the index pages is always a bad idea. For example, the post will move away from whatever page google has it one after a while and google will link to the wrong page. It's also a problem of "duplicate content" where the ranking is not ideal, since Google has the same content on two pages.

This change will allow google to visit all index pages and follow the links on it; but only index the blogpost-details-pages.

I am not aware of any recommendations in the SEO community that suggest otherwise. (With the exception of manually crafted and SEO optimised index-pages for online shops and such.)

See also https://www.searchenginejournal.com/noindex-category-archive-pages/374867/ or https://yoast.com/which-pages-noindex-or-nofollow/
