### ISSUE TITLE
incorrect key in legend

### ISSUE THREAD

**Issue by limes11** [openstreetmap/openstreetmap-website#2860]
Hi all,

access=destination is clearly rendered with grey circles on the way for hw=residential and other roads. One can find this here 

[https://wiki.openstreetmap.org/wiki/LinesTab#Miscellaneous_roads](url)

or simply by checking it anywhere on the map.

This rendering is not reflected in the legend, where the symbol looks similar to the one for private but in a different color. (It is at the bottom of the legend, second to last key.) 

Personally, I never look at this legend but for inexperienced user, consistency is important. It would be nice if this could be fixed. 

Thanks, Limes

**Comment by tomhughes** [comment]
Lots of things aren't reflected in the legend - it would be about 50000 pixels long if it included everything. It basically only includes the most common/significant things.

**Comment by limes11** [comment]
@tomhughes: 

I am fully aware of the fact that the legend cannot be complete. I wasn't asking to add anything. I pointed out an incorrect key. The fix would be to replace this incorrect symbol by the correct one. This leaves the size of the legend invariant.

Thanks, Limes

**Comment by tomhughes** [comment]
Sorry I thought you were saying there was no entry in the key for `access=destination`?

**Comment by limes11** [comment]
The entry is there (second to last, between "Private access" and "Roads under construction"). It is just an incorrect symbol. 
It should be grey dots and not these blueish? (can't really tell what color that is) dashed lines.
