### ISSUE TITLE
I have setted up osm for india on my machine using docker ! how can i edit the osm map of india which is in pbf file

### ISSUE THREAD

**Issue by deveshbamola** [openstreetmap/openstreetmap-website#2861]
i want to edit the osm file of india which is .pbf format and add some custom text or custom location on the map on my local machine! "how can i achieve that"

**Comment by Firefishy** [comment]
Sorry, but we do not offer end-user support of this nature. Please try help.openstreetmap.org, forum.openstreetmap.org or similar.
