### ISSUE TITLE
Changeset comments show italics for non-Latin scripts

### ISSUE THREAD

**Issue by fqdb** [openstreetmap/openstreetmap-website#2869]
1. There are not supposed to be italic Chinese characters, and probably the same goes for the majority of non-Latin scripts
2. It's extremely difficult to read, especially because it breaks anti-aliasing in some browsers
3. At least in my experience even the Latin italics are less legible than normal text, not sure why this was changed at all.

![image](https://user-images.githubusercontent.com/2826336/94788541-006c9c00-03d4-11eb-85dd-fbf7afcc5950.png)

**Comment by tomhughes** [comment]
Well you will find the history in #580 and #2838.

**Comment by schuetzm** [comment]
Maybe the `font-synthesis` property [1] would help here? But it seems it's still a proposal only supported by FF and Safari, and could have the side-effect of disabling italics with some Latin fonts, too.

[1] https://developer.mozilla.org/en-US/docs/Web/CSS/font-synthesis

**Comment by HolgerJeromin** [comment]
I really like font-synthesis. 
Here we have the relevent issue in chromium for missing support in Chrome, Edge, Vivaldi, Opera
https://bugs.chromium.org/p/chromium/issues/detail?id=509989

**Comment by Dimitar5555** [comment]
As a partial workaround, you can set a custom font for specific alphabets via Firefox's preferences and force websites to use it. You can't fine tune it to a specific website, but it's better than nothing and makes the text a lot more readable.

![image](https://github.com/openstreetmap/openstreetmap-website/assets/19364673/427a9cec-b260-40e3-9d29-0b8bed060114)

**Comment by AntonKhorev** [comment]
Italics replaced with larger font in #4813.
