### ISSUE TITLE
Add New Note button secret side effect of clicking a layers button for us

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2883]
Accidentally (or not) press the Add New Note button,
![X4](https://user-images.githubusercontent.com/1230959/95871637-77c10900-0da0-11eb-9269-347369b92cb0.jpg)

OK, now try to restore the map to what it used to look like as best you can.

Ah ha, you can't get rid of the
![X3](https://user-images.githubusercontent.com/1230959/95871823-b0f97900-0da0-11eb-8a9c-cfb3d1725deb.jpg)
icons that have "spread like a pox upon the map."

That's because secretly in the Layers menu, "Map Notes" has been clicked for you!
So unless you happen to dig around there, well, get used to the "pox"!

I propose the
![X4](https://user-images.githubusercontent.com/1230959/95871637-77c10900-0da0-11eb-9269-347369b92cb0.jpg)
icon change colors (to e.g., green) until clicked again, whereupon everything would return to the initial state.

If they wanted to add a second note they could click it a third time.

**Comment by tordans** [comment]
For me, this is not a problem that needs fixing. The proposed solution is not better than the status quo since it introduces new but different, unexpected behaviour.

**Comment by mmd-osm** [comment]
> For me, this is not a problem that needs fixing. 

I would agree to that.
