### ISSUE TITLE
LibreJS compatibility

### ISSUE THREAD

**Issue by TechnologyClassroom** [openstreetmap/openstreetmap-website#2886]
It would be nice if OSM became [LibreJS](https://www.gnu.org/software/librejs/) compliant.

Instructions:
- [Setting your JavaScript free](http://www.gnu.org/software/librejs/free-your-javascript.html)
- [Setting your JavaScript free from the LibreJS manual](https://www.gnu.org/software/librejs/manual/html_node/Setting-Your-JavaScript-Free.html)

**Comment by tomhughes** [comment]
Is there some javascript on our web site that you think is not under an open source license? I'm not aware of any.

**Comment by TechnologyClassroom** [comment]
I hope not.  This license tag change would affect users of the [LibreJS extension](https://www.gnu.org/software/librejs/).

**Comment by tomhughes** [comment]
Perhaps if you explain exactly what it is you want instead of expecting me to read thousands of words of polemic it might be easier to assess your request.

**Comment by TechnologyClassroom** [comment]
With LibreJS installed, I have to whitelist two external scripts, reload, whitelist a third script, and reload before the page works.  Exact instructions would require a better understanding of how the JavaScript is served.  Maybe weblabels would be the best approach.

An simple example of a script tag would look like this:

```
<script>
// @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&dn=gpl-2.0.txt GPL-2.0
var myString = "Hello World!";
alert(myString);
// @license-end
</script>
```

**Comment by tomhughes** [comment]
There are probably a hundred or more different pieces of javascript and they're changing all the time - we're not going to go round trying to catalogue them with some esoteric labels just because you're chosen to shoot yourself in the foot.

**Comment by TechnologyClassroom** [comment]
Can you provide some insight into how JavaScript is handled by the project?  Is JavaScript bundled by an upstream project?

This is my first time interacting with the git, but I have promoted OSM, used the map daily, and have contributed changes to the OSM database for several years.

**Comment by mmd-osm** [comment]
iD editor which is included in this repo has 74 direct dependencies: https://github.com/openstreetmap/iD/network/dependencies and many more indirect ones. Tagging those in the source code doesn’t seem feasible at all.

**Comment by TechnologyClassroom** [comment]
Right.  Manually tagging all of these would be impractical.  Some of those dependencies might be on the backend and would not need tagging.  A programmatic approach would be best.

iD's ARCHITECTURE.md says [rollup.js](http://rollupjs.org/) is used as a bundler.  Is that the piece that minifies JS?
