### ISSUE TITLE
translatewiki.net: error saving plural string with key "Browse.way.nodes count"

### ISSUE THREAD

**Issue by mikini** [openstreetmap/openstreetmap-website#2897]
translatewiki.net displays an error and disallows saving when editing the current plural object of [Browse.way.nodes count](https://github.com/openstreetmap/openstreetmap-website/blob/bb2ffab9ec0ce6ff4c2ee69ddfa57e4f75963685/config/locales/en.yml#L274-L275) with its only member being "other":

https://github.com/openstreetmap/openstreetmap-website/blob/bb2ffab9ec0ce6ff4c2ee69ddfa57e4f75963685/config/locales/en.yml#L273-L276

Below are screen-shot of the [inline editor for the Danish translation](https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=browse.way.nodes_count&group=out-osm-site&language=da&filter=&optional=1&action=translate) showing the warning. Using [the full editor](https://translatewiki.net/w/i.php?title=Osm:Browse.way.nodes_count/da&action=edit) doesn't display any error/warning but silently discards the save.

The [All Translations page for the key](https://translatewiki.net/wiki/Special:Translations?message=Osm%3ABrowse.way.nodes+count&namespace=1222) show that some translations have been made without "one" (probably from outside of translatewiki.net?) while others have added a "one" member and some also "few" and "many" members.

This seems to be the only plural string without a "one".

# Screen-shots
In-line editor in the default view after translating the English string, not able to save/publish.
![Screenshot from 2020-10-20 14-35-48](https://user-images.githubusercontent.com/1330166/96589009-9bc2a400-12e4-11eb-8295-4168ed088fb9.png)

Adding a "one" member with some value enables save/publish:
![Screenshot from 2020-10-20 15-02-55](https://user-images.githubusercontent.com/1330166/96589691-666a8600-12e5-11eb-9f39-86f926fc9d96.png)

**Comment by tomhughes** [comment]
If you have a problem with TranslateWiki then you will have to ask them about it - we have nothing to do with it and no control over it.

**Comment by gravitystorm** [comment]
It seems like it's probably a bug in translatewiki, but this is probably also an edge case in the way that we're using it. It's unusual for one of our translations to only have an 'other' key in en.yml, but in this case we know that there are always at least two nodes in a way.

I think the easiest way for me to fix this is to add the missing 'one: 1 node' to the en.yml and that should resolve it.

I don't know why some translations are erroring and some aren't, that would be something for translatewiki to answer.

**Comment by danieldegroot2** [comment]
Resolved in #4097.
