### ISSUE TITLE
Tile Calculate

### ISSUE THREAD

**Issue by Legolash2o** [openstreetmap/openstreetmap-website#2900]
Hi, 

This is not a bug, but how do you calculate which tile a new node belongs in please? I'm needing a way to add a batch of new nodes directly in the postgresql

**Comment by tomhughes** [comment]
There's a postgres function in `db/functions` to do it.

**Comment by Legolash2o** [comment]
Hi Tom, thanks for the reply.

I managed to find that but I'm not sure if it's 'maptile_for_point' or the 'tile_for_point' function. What is the difference please?

Thanks again.

**Comment by tomhughes** [comment]
It's `tile_for_point`.
