### ISSUE TITLE
wikimedia_commons uselang English forced upon user

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2904]
On https://www.openstreetmap.org/way/862950938
`wikimedia_commons	File:Historical_Power_Tower_Foundation_Corner.jpg`
we see "?uselang=en" is being forced upon us in the link.

Please just rely on the defaults and don't override assuming all users want English instead of what default is detected on Commons.

**Comment by tomhughes** [comment]
We don't assume all users want English, we assume they want the same language they are using on OSM.

**Comment by gravitystorm** [comment]
I'm happy with the current situation too.

**Comment by jidanni** [comment]
But target sites are smart enough these days to make language choices without such tips. Such tips would interfere with their best choice algorithms.

E.g., User Billy lands on Facebook. Facebook has spent years perfecting the best language to greet Billy with depending on if he is logged in, or what IP address he is coming from, or what cookies he has. So no help needed.
