### ISSUE TITLE
Support for Google Maps & Syntax

### ISSUE THREAD

**Issue by SethiPandi** [openstreetmap/openstreetmap-website#2913]
I learned recently that Google Maps has a pretty neat feature where you can specify & between two roads to get taken to the point where the roads intersect or meet.

For example:
`Avondale Road & Kenilworth Road` (`and` also works)

![image](https://user-images.githubusercontent.com/22801583/97283893-afb85980-1840-11eb-9cd8-49afb9bfacaf.png)

My partner uses this feature a lot for work, so I wanted to suggest it for OpenStreetMap.

**Comment by lonvia** [comment]
There is a (still open) feature request in https://github.com/osm-search/Nominatim/issues/123 already.

**Comment by SethiPandi** [comment]
Ahh! Sorry about that, I'll just close this one then and +1 it.
Thanks for the heads up.
