### ISSUE TITLE
Use Labels for Issues on this Repo

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/openstreetmap-website#2927]
I'm having a hard time going through this repo's issues regarding ones that deal with changesets (there are a lot). I notice that most issues do not have labels. Could the maintainers please label the New and Open issues?

Quincy in the iD repo labels Issues very well. I can easily find what I'm looking for. 

There is already a good selection of labels created. I think more specific labels could be created as well (there seems to be a lot of unique feature requests).

**Comment by tomhughes** [comment]
This does not appear to be reporting an issue in the software contained in this repository, or an issue with any definitive end point.

**Comment by lectrician1** [comment]
I would have contacted you Tom through another way about this request, but I couldn't find a other contact method so I decided to just make this an issue. 
I understand that this has no definitive end point, but can my request for a commitment to labeling be guaranteed in any way?

**Comment by tomhughes** [comment]
No of course it can't - you're asking volunteers to do work. We have no way to force anybody to do anything so no way to guarantee anything.

**Comment by gravitystorm** [comment]
> I'm having a hard time going through this repo's issues regarding ones that deal with changesets (there are a lot). I notice that most issues do not have labels.

Hi Seth - Out of interest, what would labelling issues like this help you with? I'm curious as to why you are looking for issues related to changesets, and I want to know more about what kind of situation you are trying to solve.

I do label issues and pull requests from time to time, but generally with either high-level labels (like 'dx' or 'changes requested') and generally not with a label for the particular feature that it corresponds to.

**Comment by tomhughes** [comment]
I have to say I'm curious about that as well - thinking about this more overnight my main inclination would actually be to get rid of many of our labels, which are mostly historic and have unclear meaning, and keep only a few like `support` and `changes request` that have a clear meaning and add others as needed and as we have an objective meaning for them.

But I am interested in how labels are perceived to help contributors as I've always thought of them mostly as a tool for maintainers to use to divide up issues - that might sometimes include a label that is used to publish a list (like `good first issue`) to contributors but it's not immediately obvious that they are more generally useful to contributors.

**Comment by tuckerrc** [comment]
Labels for the specific components in the application such as diaries, notes, map, admin/moderation, and changesets would help contributors find things they would be comfortable working on. When I learn a new codebase I usually pick a specific area (such as "changesets") and branch out from there.

A "has pull request" label would help reduce duplicate work and Pull Requests. The iD team has documentation in their "[CONTRIBUTING.md](https://github.com/openstreetmap/iD/blob/develop/CONTRIBUTING.md#issue-labels)" file about the labels for their repo.

I would be happy to volunteer some time in triaging the issues and pull requests for this repo (I would need at least the "triage" permission to help though).

**Comment by lectrician1** [comment]
Sorry I never got back to this. 

What I originally was looking for was https://github.com/openstreetmap/openstreetmap-website/issues/2973, which I created. 

About looking for issues relating to Changesets, I just noticed there were a lot of issues about changesets and wanted to look into/differentiate the different ones. Basically just curious.

I agree some of the labels could be deleted. Also, the labels you decide to keep should have Descriptions (most don't right now).

As tuckerrc is suggesting he could help with triaging issues, I could as well. 

I wasn't sure if I had the time to, but after my full-dive into and now-obsession with the OSM community in the past month, I definitely have the time. 
I have been fully Watching this repo and the iD repo for almost 3 weeks, so I'm well accustomed to what types of issues usually come up.
I also check my email a bit too much.
The only downside is that I don't know Ruby (only Node.JS). Though if I'm just labeling, this shouldn't be an issue since I'm accustomed to the environment and structure of web applications.

**Comment by gravitystorm** [comment]
@tuckerrc @lectrician1 I've invited you both as collaborators to this repository, with the Triage role, as requested. @tomhughes and I are both happy to experiment with having you label issues, and we'll see how it goes. In particular:

* We'll review this experiment in six months, and see whether it is working. In particular, I'm interested to see if it leads to more successfully merged pull requests.
* Please work collaboratively with everyone else in the repo. In particular, discuss any major changes before implementing them, and please ask as many questions as needed! You can open fresh issues, for example if you have a proposed set of tags, or want to ask for views on anything.
* Please let me know if I can help with anything else! And thanks in advance for your help.

**Comment by tuckerrc** [comment]
@gravitystorm Another possible metric to track could be duplicate issues created. If the issues are easier to search hopefully you get fewer duplicates.
