### ISSUE TITLE
BUG api preferences

### ISSUE THREAD

**Issue by jonycoo** [openstreetmap/openstreetmap-website#2928]
Hello, 
short thank you for working on improving Open Street Map on the Software part.

to the Bug:

the endpoints
- xml update PUT /api/0.6/user/preferences
- single update PUT /api/0.6/user/preferences/<mypref>

return always HTTP 500 Internal server error

the endpoint
- get single GET  /api/0.6/user/preferences/<mypref>

returns HTTP 404 Not Found with and without authentication

The DELETE endpoint I haven't tested 
all this was only tested on the development website 
I used BasicAuth for this tests

more information can be found in https://github.com/jonycoo/py-osmapi/commit/9452df175fb49bfbfdcddc6843c854f06aba7ea9 module `osm-api.py` section `USER` line 630

Thanks, 
jonycoo

**Comment by tomhughes** [comment]
There are existing applications using this functionality so you have probably made a mistake in your implementation, or this is an operational issue with the dev api.

To start with you probably want `/api/0.6/user/preferences` not `/api/0.6/user/preferences/`.

**Comment by tomhughes** [comment]
Also a "single update" should be to `/api/0.6/user/preferences/key` not `/api/0.6/user/preferences/`.

**Comment by tomhughes** [comment]
I've tested fetching preferences from the dev api with:

```
curl --user TomH:password https://master.apis.dev.openstreetmap.org/api/0.6/user/preferences
```

and it works just find so I'm pretty sure this is an implementation issue on your part.
