### ISSUE TITLE
Sports pitches no longer show an icon.

### ISSUE THREAD

**Issue by sekerob** [openstreetmap/openstreetmap-website#2940]
Noticed on Nov.05, 2020 that the icons have disappeared from sports pitches. In ID editor mode they show fine, but in standard map view they only show green squares. Went to visit places I knew it showed them including the soccer pitches lining, but it's all gone, sample from Silvi Marina, Italy https://www.openstreetmap.org/history#map=19/42.53916/14.13013 . The other sample has 4 different sports in the Riseis park in Pescara, Italy, just showing squares, no distinction  https://www.openstreetmap.org/history#map=19/42.53916/14.13013 . Viewed in various browser, but all the same.

**Comment by gravitystorm** [comment]
The map styles shown on osm.org are all separate projects, not part of this repository. For the "standard" layer, please see https://github.com/gravitystorm/openstreetmap-carto

**Comment by sekerob** [comment]
Thanks for the reply. I'll pick up me things and move on.

**Comment by HolgerJeromin** [comment]
The default style osm-carto nevered had pitch icons.
ref https://github.com/gravitystorm/openstreetmap-carto/issues/844

**Comment by sekerob** [comment]
Oh well, I drew a new one next to an existing one, both with astroturf and it drove me nuts that the new one would not render the same, including lining as the old. Guess I was looking in editor mode all the time, one with imaging while WIP. Thanks for enlightening me, case closed.
