### ISSUE TITLE
test:db error due to improper yarn installation

### ISSUE THREAD

**Issue by JustinSingleton303** [openstreetmap/openstreetmap-website#2945]
While setting up the development environment several members of our team got to the test:db section there were hundreds of errors thrown due to an improper installation of the yarn application.  It seems that the command "bundle exec rake yarn:install" does not work for everyone.  However a manual reinstallation of yarn is sufficient to fix these errors.  We propose an added message in the INSTALL.md file to reflect this. It would probably save future users some time.

**Comment by JustinSingleton303** [comment]
we have the appropriate changes ready for a PR if you agree with our proposal.

**Comment by tomhughes** [comment]
You mean like #2936 that you opened and then closed a few days ago?

No that doesn't look reasonable at all - if there's a problem then lets find the cause and fix it properly not just add cargo cult instructions to the instructions.

**Comment by JustinSingleton303** [comment]
okay so then when the "bundle exec rake yarn:install" command runs, what would I do to investigate the improper install?  Other wise a simple reinstall of yarn fixes the problem.  As for the prior ticket I opened and closed, I apologize, I didn't have my repository correctly setup and I wanted to avoid making a mess.  I'm not super confident yet contributing to open source projects. Thanks for the feedback.

**Comment by tomhughes** [comment]
Well if a reinstall of yarn fixes the problem then that implies your install of yarn was broken, and that's nothing to do with us.

The `bundle exec rake yarn:install` command doesn't install yarn, it uses yarn to install the node modules, so if it doesn't work and reinstalling yarn fixes it then it seems your yarn install was broken. How had you installed yarn?

**Comment by gravitystorm** [comment]
> Well if a reinstall of yarn fixes the problem then that implies your install of yarn was broken, and that's nothing to do with us.

It might well be something we need to fix, if the installation instructions are incorrect. I can see for example https://github.com/openstreetmap/openstreetmap-website/commit/78ecc76067e434856358e609fa883619d316ffc4 added yarn, but only to the Fedora instructions, not to Ubuntu. So perhaps that's the root cause?

**Comment by tomhughes** [comment]
Well the root cause is that there's no good/easy way to install yarn on Ubuntu ;-)

**Comment by tomhughes** [comment]
Oh actually I think there is now in 20.04 as it is packaged now

**Comment by tomhughes** [comment]
I've pushed https://github.com/openstreetmap/openstreetmap-website/commit/6e55d4c70dd664ca2c5225357eb3dff6c1af2837 to add `yarnpkg` to the Ubuntu install instructions.

**Comment by gravitystorm** [comment]
@tomhughes thanks!

@JustinSingleton303 were you using Ubuntu originally? It would be great to hear more details about what caused the yarn problem in the first place. If you were using Ubuntu, then I think the above will have fixed it. But if you were using something else, then perhaps we have another problem to resolve.

**Comment by JustinSingleton303** [comment]
I was.  I think the issue that is causing it is that ubuntu has an executable called cmdtest preinstalled on it that makes yarn installation on 20.04 and 18.04 a non-trivial task.  I believe a standard "sudo apt-get install yarn" will get redirected to install cmdtest somehow

**Comment by tomhughes** [comment]
The ubuntu package is actually called `yarnpkg` not `yarn` so that is what you need to install.
