### ISSUE TITLE
Map key for OpenCycleMap not showing green dashed lines

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/openstreetmap-website#2956]
Green dashed lines are a feature of OCM but they are not listed in the map key.

https://www.openstreetmap.org/#map=15/51.1787/-0.4648&layers=C

I realise it can't list absolutely everything of course...

**Comment by lectrician1** [comment]
Mountain bike routes too.

**Comment by mmd-osm** [comment]
I think this has been fixed by @AntonKhorev in #4448. Closing here.

![image](https://github.com/openstreetmap/openstreetmap-website/assets/5842757/b59f73e5-9d81-469d-94d0-84b1b29610e2)
