### ISSUE TITLE
problematic reference node sequence

### ISSUE THREAD

**Issue by jiawei92** [openstreetmap/openstreetmap-website#2961]
Is the sequence of reference nodes in a way always consistent with that in real word? When looking at .osm file from openstreetmap, I found it is true for almost all cases. But, there are still some exceptions.

```
 <way id="106620126" visible="true" version="9" changeset="62223600" timestamp="2018-09-02T16:44:15Z" user="JokerAustin" uid="6121636">
  <nd ref="1226548270"/>
  <nd ref="4895447212"/>
  <nd ref="4897240420"/>
  <nd ref="4897291294"/>
  <nd ref="1226548304"/>
  <nd ref="5876423061"/>
  <nd ref="4895408377"/>
  <nd ref="5876423285"/>
  <nd ref="4895448835"/>
  <nd ref="4895409377"/>
  <nd ref="1226548274"/>
  <tag k="highway" v="residential"/>
 </way>
```

For the way information I attached above, I found the sequence of node 4895447212 and 4897240420 should be reversed after check their positions in map. It seems the nodes sequence is automatically generated by osm, and cannot be edited by users.

**Comment by tomhughes** [comment]
Nonsense, the order is as it was uploaded - if it's wrong then upload a corrected version.

**Comment by gravitystorm** [comment]
> Nonsense

That's a bit harsh @tomhughes - not everyone knows how everything works!

@jiawei92 As @tomhughes has briefly explained, the order of nodes in a way is determined by the mapper, and sometimes they make mistakes. The API will always return the nodes in strictly the same order as they were uploaded.

For general questions about the OSM format, and how editing software is used to model the real world and how the editors interact with the OSM API to do so, you can also ask your questions at https://help.openstreetmap.org where there are a lot more people around who have expertise in different parts of the ecosystem.

**Comment by jiawei92** [comment]
Got it. Thanks for your kind reply. @gravitystorm
