### ISSUE TITLE
Design of inbox/outbox links

### ISSUE THREAD

**Issue by arianit** [openstreetmap/openstreetmap-website#2962]
Hi, 

_My Inbox/outbox_ links in the comments page ([photo](https://imgur.com/OJXZT1i)) are poorly designed and is confusing. Could you please have a look. 

Thanks,
Arianit

**Comment by tomhughes** [comment]
Well it would probably help if you explained what you think is confusing about them - we're unlikely to make them better if we have to guess what the problem is.

**Comment by arianit** [comment]
It's not clear which one is active. Using links to mark which one is active is probably a bit outdated. Using buttons would be helpful. Not a visual person myself so I can't help much on how it can be improved. Thanks!

**Comment by gravitystorm** [comment]
I would be interested to see if navigation tabs works for this - e.g. https://getbootstrap.com/docs/4.6/components/navs/#tabs
