### ISSUE TITLE
Support more than 1 diary language

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/openstreetmap-website#2974]
Sometimes diary authors are bilingual+ and want to make their diary entries available in more than one language. 

Currently you can only select one language per diary entry.

You could make two posts with each language, but this is a bit counterintuitive to the idea of a "single entry".

**Comment by gravitystorm** [comment]
I appreciate the problem, but I think this proposal will create more problems than it solves. If you have one diary entry with two languages, it's not possible to record which parts are in which language. So if you follow a language-specific feed, the user will see text not in the language that they want to see, which defeats the point.

Another option would be for each diary entry to contain multiple blocks of text, and each block of text can have an assigned language. That way, for language specific feeds, you can show only the block of text with the correct language. But that opens more cans of worms - trying to ensure that the different blocks of texts are about exactly the same subject, etc etc.

So having to post two diary entries is a limitation (mainly that it splits comments, but also that the entries aren't linked in any way) but also has its advantages (in language-specific feeds). So it appears the proposal has some unwanted side effects.

Given this, and that it is a problem only affecting a small number of diary entries, I think the work involved outweighs the benefits, and so I'm going to close this issue.
