### ISSUE TITLE
 Google search results look terrible

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2977]
Here we see the website is not optimized to make it look good in Google search results:
![Screenshot_20201123-185533](https://user-images.githubusercontent.com/1230959/99954426-ada0d680-2dbd-11eb-88eb-38f5934c4daa.jpg)

**Comment by HolgerJeromin** [comment]
Same on desktop:
![image](https://user-images.githubusercontent.com/2410353/99955757-28013480-2d85-11eb-8edd-74ddaa8eae46.png)

**Comment by tomhughes** [comment]
What kind of mad mad searches for a domain name? Searching for something normal like "OpenStreetMap" works fine, and what Google chooses to display for a search is up to them, not us. Given that "OpenStreetMap" works they obviously know what to show and they're just being stupid.

**Comment by jidanni** [comment]
It's called an omnibox. Get used to it.
![Screenshot_20201123-201354](https://user-images.githubusercontent.com/1230959/99960997-a29f7380-2dc8-11eb-9cb8-abb7f848a3b5.jpg)

**Comment by jidanni** [comment]
https://www.computerhope.com/jargon/o/omnibox.htm

**Comment by tomhughes** [comment]
It's not good saying "please compare" because yes I can see the picture is different but I have no idea why and I have no way to tell.

If you can actually point at something concrete that we can change that would improve this then please do so but just pointing us at pictures of a third party system is useless as we have no idea how Google are deciding what to display there.

**Comment by SomeoneElseOSM** [comment]
For completeness, searching for osm.org works just fine in other search engines such as DDG:

https://duckduckgo.com/?t=ffsb&q=osm.org&ia=web

**Comment by jidanni** [comment]
![Screenshot_20201124-045440](https://user-images.githubusercontent.com/1230959/100014986-33e70800-2e12-11eb-9d92-d10347090b67.jpg)
![Screenshot_20201124-050005](https://user-images.githubusercontent.com/1230959/100015079-5711b780-2e12-11eb-9fe0-2fd641a764ac.jpg)

**Comment by jidanni** [comment]
https://search.google.com/search-console/about are all the tools you need to get to the bottom of the problem.

**Comment by jidanni** [comment]
(Re: DDG,  I didn't see any actual item that links to osm.org in the whole first page of the results.)
