### ISSUE TITLE
Turn off dependabot?

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2992]
I find the dependabot PRs to be distracting and a little annoying, due to the way that they work. Dependabot makes a PR for every patch release of every dependency, not just security updates. However, Dependabot [currently has no support for grouped requests](https://github.com/dependabot/dependabot-core/issues/1190), so every gem or node module update gets its own PR. Since we have over 80 gems and (120 node modules), and some of them are updated frequently (e.g. AWS), the stream of PRs is never ending. The PRs are also mostly unimportant.

Some tallying shows that of the 222 PRs opened since we enabled dependabot in June, 137 (62%) are dependabot, and 85 by other people. As well as annoying me, I worry that the endless stream of (unimportant) dependabot notifications might cause other people to turn off notifications entirely and stop being involved in this repo.

So I would like to turn them off, at least until support for grouped requests is available. In the meantime, we can run `bundle update` or `yarn upgrade` every week or two if we want to keep up with the patch releases.

**Comment by grischard** [comment]
There are definitely a lot of these PRs.

I see that dependabot can be configured to run at certain times. Could we run `bundle update` and `yarn update` automatically with a github action shortly before, or is that a crazy idea, or both?

**Comment by gravitystorm** [comment]
> Could we run `bundle update` and `yarn update` automatically with a github action shortly before

If we automate running a (grouped) update ourselves, then we have no need for dependabot to run after. But I suspect automating the updates with a github action will mean that we more-or-less end up re-implementing the whole of dependabot ourselves. I'm keen to avoid doing that!

**Comment by tomhughes** [comment]
I've disabled it for ruby but left it enabled for npm which are far less common.

**Comment by larouxn** [comment]
👋 Considering Dependabot has since added support for [groups](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference?learn=dependency_version_updates#groups--) and much more since 2020, is it worth considering enabling Dependabot for Ruby? Understandable that the noise can be a lot but it's also a long-term risk to fall behind on dependency upgrades, even non-security related ones.

**Comment by tomhughes** [comment]
I normally update the bundle at least weekly, and we still get dependabot alerts for anything it knows to have security issues in between.
