### ISSUE TITLE
Not working properly in Safari

### ISSUE THREAD

**Issue by Pegasus21272** [openstreetmap/openstreetmap-website#2995]
Since few weeks I've got problem with not full functionality on Safari: especially right-hand menu, layers is not working.
Any thoughts?

**Comment by gravitystorm** [comment]
Probably the same problem as described in #2811 - let me know if not!

**Comment by Pegasus21272** [comment]
Yes!
Any solution?

**Comment by tomhughes** [comment]
Other than pelting the leaflet developers with rotting fruit you mean?

I guess at some point I'll have to give in and revert it, but we kind of assumed they would treat this as a pants-on-fire emergency.
