### ISSUE TITLE
Mistranslations are breaking the build

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2998]
The latest commit from @translatewiki has broken the build, since it appears to have messed up some translations.

#2993 made, among other things, the following change:

```diff
 user_mailer:
   message_notification:
-    subject_header: "[OpenStreetMap] %{subject}"
+    subject: "[OpenStreetMap] %{message_title}"
     hi: "Hi %{to_user},"
```

However, f8f327179c3241159cf3fd13fd064512fe13994d has made a bunch of changes like this:

```diff
 user_mailer:
   message_notification:
+    subject: '[OpenStreetMap] %{user} het ''n nuwe boodskap aan u gestuur'
     hi: Hallo %{to_user},
```

```diff
 user_mailer:
   message_notification:
-    subject_header: '[OpenStreetMap] %{subject}'
+    subject: '[OpenStreetMap] %{user} je ći nowu powěsć pósłał'
     hi: Witaj %{to_user},
```

This is surprising, since they appear to be correct translations for "%{user} has sent you a new message", which is not a string we have in `en.yml`. It's also not a copy+paste from another translations that have `subject` as the key.

Digging into this, and going a long way back through the git history, I think I've found the cause. It appears that over 10 years ago, [we deleted the key `user_mailer.message_notification.subject`](https://github.com/openstreetmap/openstreetmap-website/commit/eefb42334f6d928081d5d5edbb92e75813666dbb), but it has lingered somewhere in the translatewiki database. And since #2993 has accidentally reused the key, the "zombie" translations appear to have been resurrected after all this time!

@translatewiki could you please delete all the `user_mailer.message_notification.subject` values which contain the `%{user}` variable? This can then let them be re-translated with the up to date variable and content, and will fix the build.

**Comment by Nikerabbit** [comment]
1985142ff hopefully fixes this.

**Comment by tomhughes** [comment]
Confirmed fixed.

**Comment by gravitystorm** [comment]
@Nikerabbit Thanks! And thanks for sorting it out so quickly, much appreciated.
