### ISSUE TITLE
Alternative to Travis

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3000]
I've become aware that our Travis CI configuration will stop working soon. This is because they are switching off travis-ci.org (which we use) on December 31st.

https://travis-ci.community/t/extremely-poor-official-communication-of-the-org-shutdown/10568

https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/

Theoretically, we can move to travis-ci.com as they offer open source credits. However, it seems that there are [some limitations with their own ability to hand out credits](https://twitter.com/james_hilliard/status/1336081776691843072), and I'm not sure it's worth the hassle. I have no idea where this repo stands with regards to a non-recurring 10,000 minute quota, since I can't find anything useful on travis-ci.org, but I suspect we'd be having to ask frequently, and I wouldn't want to just run out one day and not be able to get more.

So I think we have a few choices:

* Switch to travis-ci.com and hope they give us enough credits
* Switch to using github actions
* Switch to another CI system, for example [Gitlab CI](https://about.gitlab.com/solutions/github/), without moving the repo

**Comment by tomhughes** [comment]
I do already have a branch somewhere that uses github action...

**Comment by tomhughes** [comment]
Yes https://github.com/tomhughes/openstreetmap-website/tree/actions is the branch though it needs bringing up to date I expect.

**Comment by migurski** [comment]
Would it be an option to pay Travis commercial rates?

Glad you have a GH Actions branch in your back pocket, Tom!

**Comment by gravitystorm** [comment]
Fixed by #3002
