### ISSUE TITLE
No way to close the search box fully

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3001]
Here we see the user is trying to compose a screenshot containing the OSM logo,

![20201210T010404](https://user-images.githubusercontent.com/1230959/101661860-bfec6700-3a83-11eb-9ff8-10d8700da357.jpg)

Alas, there is no X or V or <  to make the search box just go away or roll up, or compress to the side.

**Comment by tomhughes** [comment]
Why should there be? Search is a fundamental feature. Taking nice screenshots isn't. I mean you'd still have all the other UI controls anyway! If you want a picture then use export.
