### ISSUE TITLE
Multiple accounts (i.e. import accounts) require too many unique email addresses

### ISSUE THREAD

**Issue by Nate-Wessel** [openstreetmap/openstreetmap-website#3003]
Over several years of editing I've created, I think, four different accounts - one main account and three used each for various imports. Creating each account has required using a new email each time and I'm now at the point where I have more accounts (three of them inactive) than I have emails that I actually check. I'm trying to change the email associated with my main, active account to what is now my primary email address but I can't because that address is already taken by one of the other accounts. 

I tried changing the email associated with one of the secondary accounts to something I don't check, and then the email on the main account to the email that I thought I had thus freed up, but still no luck. I get the following error:

![Screenshot_2020-12-12 Edit account OpenStreetMap](https://user-images.githubusercontent.com/7830465/101999553-471c2380-3cac-11eb-9f81-1880c6eebfe0.png)

How can I change the email on this account to an email that is already recognized as (having been) associated with another account?

**Comment by Nate-Wessel** [comment]
Actually, perhaps the problem is that I was incorrectly informed that my email had been changed on the inactive account? I logged back into that to confirm that it had changed, and I see the previous email still there - I can't change it. 

(Does it also recognize the email I'm trying to switch to but not know to report the error?)

**Comment by tomhughes** [comment]
If you're having a problem with your account on www.openstreetmap.org then please contact support@openstreetmap.org with all the details.

**Comment by Nate-Wessel** [comment]
@tomhughes I've sent them an email, though it's not clear to me why this was not the right place to post this issue. Can you please explain? Aren't user accounts (and the UI used to manage them) part of the website?

**Comment by tomhughes** [comment]
Well if there's a bug in the code then this would definitely be the right place but we haven't established that (to be honest I don't fully understand what you're saying) and if it's an operational issue with the production database then this isn't the place to deal with.

In any case determining what is going on will require knowing details of the accounts which can't really be discussed in a public forum.

**Comment by mmd-osm** [comment]
Easiest way to have multiple osm accounts all share the same email inbox is to use a plus email suffix: https://www.cs.rutgers.edu/~watrous/plus-signs-in-email-addresses.html
