### ISSUE TITLE
Update wiki links cache

### ISSUE THREAD

**Issue by jdhoek** [openstreetmap/openstreetmap-website#3004]
If I understand the comment on #2853 correctly, there is a job that can be run to update the links to tags and keys on the wiki. It looks like this job has not been run in quite a while (a year perhaps?); can this task be run?

That is, I would like to see these tags and keys linked to their respective-pages, if available:

![Screenshot from 2020-12-13 12-24-57](https://user-images.githubusercontent.com/683699/102010453-62377380-3d3e-11eb-9e88-dfe61dd2df3b.png)

In this case [`Tag:parking=street_side`](https://wiki.openstreetmap.org/wiki/Tag:parking%3Dstreet_side) and [`Key:parking:orientation`](https://wiki.openstreetmap.org/wiki/Key:parking:orientation).

Or is there something I should do on the wiki to get them to show up as links?

**Comment by mmd-osm** [comment]
Looks like a good candidate for a GitHub action based cron job to create a pull request on a monthly basis.

**Comment by tomhughes** [comment]
This was updated by #3044.
