### ISSUE TITLE
Authentication fails when google drive is down

### ISSUE THREAD

**Issue by pietervdvn** [openstreetmap/openstreetmap-website#3006]
In the huge outage of google services today, I noticed it is not possible to login.

Could it be that - because of the outage - a request to google fails, which brings down the entire login flow? Are similar bugs possible, e.g. if github, facebook, microsoft or any other such is down one day?

**Comment by tomhughes** [comment]
Just a coincidence, and nothing to do with Google but we had a problem at the same time.
