### ISSUE TITLE
Make fhrs:id tag value a link

### ISSUE THREAD

**Issue by UKChris-osm** [openstreetmap/openstreetmap-website#3012]
I've noticed that when you right-click on OSM and use "_query features_", you can see a small selection of what's near-by, such as a shop, road, etc.

If then selecting an item, such as a restaurant, the tags associated with it are displayed to the left.

I see that some of the tag values are linked (wikidata, phone number, web site, etc), and wanted to suggest that the value of "_fhrs:id_" is also linkable. I think this is done via "_/app/helpers/browse_tags_helper.rb_"

The value of "_fhrs:id_" in the UK refers to the unique food rating ID the establishment has been assigned, for example:

[https://ratings.food.gov.uk/business/en-GB/](https://ratings.food.gov.uk/business/en-GB/){fhrs:id}
[https://ratings.food.gov.uk/business/en-GB/1083925](https://ratings.food.gov.uk/business/en-GB/1083925)

A Welsh language version is also available by changing the "_en-GB_" part of the URL to "_cy-GB_":

[https://ratings.food.gov.uk/business/cy-GB/](https://ratings.food.gov.uk/business/en-GB/){fhrs:id}
[https://ratings.food.gov.uk/business/cy-GB/1083925](https://ratings.food.gov.uk/business/cy-GB/1083925)

... but this is also achievable on the actual web site itself, so if language / locale selections aren't possible via the OSM web site it isn't a big problem.

Is making the "_fhrs:id_" value a link an option?

**Comment by mmd-osm** [comment]
This is already covered in #2621

**Comment by mmd-osm** [comment]
Let's close is, there's nothing left to do here.

**Comment by gravitystorm** [comment]
> Let's close is, there's nothing left to do here.

@mmd-osm - you have a github invite to get 'Triage' access on this repo, and I've sent you an OSM message a few days ago too. :-)

**Comment by mmd-osm** [comment]
You're right, but I'll stick to the Contributor way of life for the time being... more to come.

**Comment by gravitystorm** [comment]
> This is already covered in #2621

Closing as per @mmd-osm .
