### ISSUE TITLE
User language preferences do not cascade to website

### ISSUE THREAD

**Issue by JimKillock** [openstreetmap/openstreetmap-website#3025]
A website user will generally choose their language preferences at the level of their Operating system, or browser user preferences. These are sent in http requests and can be recognised by the OSM website; eg that I am expecting map content in UK English, German, Welsh, Gaelic etc, if available.

The website behaviour, as I see it, is to default to the "country language", rather than the "user language". 

Thus, all towns in England and Wales are displayed in English; all towns in france, in French, etc.

This poses two problems:

- For the casual user, they get information which is novel and sometimes unusable, eg cyrillic script names when they have no knowledge of Cyrillic
- It makes it impossible to access minority language map content without logging into the website

If the current approach is preferred, then perhaps a request for the user to choose "show local language names" versus "show user lang (per http request) names" can be made and a cookie set?

**Comment by tomhughes** [comment]
It's unclear what you are referring to/// Are you talking about text that forms part of the user interface? or about place names that are rendered as part of the map image?

**Comment by JimKillock** [comment]
Edited to be slightly clearer: yes, I mean map content. 

- Chrome: the user interface seems to respect language preference in Chrome; the map data however defaults to country-language
- Safari Mac: neither the user interface nor the map data respect the user language preference (I have set this to DE to test, and I am getting an English interface and country-specific language map data)

**Comment by tomhughes** [comment]
So map content is not really an issue for this tracker - we just display the tiles that are made available by other projects.

The default tiles are provided by the [operations team](https://github.com/openstreetmap/operations/) using the [carto style](https://github.com/gravitystorm/openstreetmap-carto/) and while the operations team would love to be able to provide a multilingual map that is not currently possible.

The map is made up of bitmap images that are shared by all users so there is no way to provide different images for different people - we don't have the resources to render and store tens or hundreds of versions of each tile.

The solution is to use vector tiles where the actual image is composed on the fly as it is viewed but as of yet nobody has created a vector tile stack that we can use.

**Comment by tomhughes** [comment]
Previous discussions around vector tiles:

https://github.com/openstreetmap/openstreetmap-website/issues/1875
https://github.com/openstreetmap/operations/issues/214

I thought there was a more recent ticket but I can't find it right now...

**Comment by HolgerJeromin** [comment]
> Safari Mac: neither the user interface nor the map data respect the user language preference (I have set this to DE to test, and I am getting an English interface and country-specific language map data)

Prio 1 locale is from the logged in user. Perhaps this was the reason for your observation.

**Comment by JimKillock** [comment]
@HolgerJeromin I am getting English on the web interface whether logged in or not (see screenshot). I have just tried clearing cookies and no change; I will try again with a fuller cache flush etc and report back.

<img width="728" alt="Bildschirmfoto 2021-01-01 um 14 38 43" src="https://user-images.githubusercontent.com/369665/103440642-36255900-4c3f-11eb-92bf-5dd03fd91833.png">

**Comment by tomhughes** [comment]
Cookies are not important (other than the session cookie) in the language selection.

If you are logged in then it will use the language preferences in your user settings and if you're not logged in it will use whatever the browser sends.

What accept-language header are you sending? It has been known to make suboptimal decisions about the best language with very complicated preference lists but for most people it gets it right.

**Comment by tomhughes** [comment]
I found your OSM account and copied your language preferences to my account and it switch to welsh as it should so I don't see why it wouldn't work for you.

**Comment by JimKillock** [comment]
Yes, I think I have located the problem:

- If I set language preferences at MacOS level (and reboot) to DE, CY, LA then I get pages in DE
- If I set language preferences at MacOS level (and reboot) to LA, CY, DE, then I get pages in EN

I can't say whether that is because MacOS is sending a thin request ("LA") or whether OSM's website isn't parsing through the preferences I am sending. I'll see if I can work out how to see the request from Safari on.
