### ISSUE TITLE
Map of country still not yet updated

### ISSUE THREAD

**Issue by MoroccanGeek** [openstreetmap/openstreetmap-website#3027]
Hello, it appears the country Morocco borders is still not yet updated after USA's recognition of Morocco's Sovereignty Over Western Sahara. Can you please update the map please !

**Comment by SomeoneElseOSM** [comment]
This isn't a website issue.

For more details about how OpenStreetMap handles disputed territories, please read https://wiki.osmfoundation.org/w/images/d/d8/DisputedTerritoriesInformation.pdf .  If after reading that you still believe these international borders are mapped incorrectly please email OSM's Data Working Group - see https://wiki.osmfoundation.org/wiki/Data_Working_Group for details.

Andy (from the DWG)
