### ISSUE TITLE
Allow to have publicly visible preferences

### ISSUE THREAD

**Issue by pietervdvn** [openstreetmap/openstreetmap-website#3039]
Hey everyone,

It would be really useful if some preferences would be able to made public, so that some information can be shared amongst programs. It would enable some cool usescases, e.g. to share editor preferences among users, to quickly share overpass queries, to publicly visualize some stats, to have badges, to expose an OSM-team that they are part of...

The idea is that the api would have the endpoint `/SomeOtherUser/preferences` (or `/SomeOtherUser/public-preferences`) and which would return those features.

**Comment by tomhughes** [comment]
I don't understand how this is "preferences" really. It sounds like just want us to store random blobs of data and serve them up again on request and I really don't see how that fits with our mission.

Then again you're also asking for other stuff like groups, badges etc which seems to have nothing at all to do with preferences and for which there are already open tickets.

I really think you're trying to cram a whole lot of unrelated ideas into a single unstructured endpoint which sounds like a terrible idea to me.

**Comment by pietervdvn** [comment]
You saw right through me!

Indeed, I am asking for a generic, somewhat unstructured and free to use space. Just like elements on OSM, this would allow the applications to interpret these tags and allow innovation on that front, and to make 'unofficial' parts of the website. One frontend could pop up which uses this endpoint to show badges of users, another which shows an advanced profiles wrt teams, ... Then this would all become possible without having to change the rails port.

**Comment by tomhughes** [comment]
Sorry, but we're not here to provide a public data store for third party applications.
