### ISSUE TITLE
Banner for the OSMF Board's community survey?

### ISSUE THREAD

**Issue by rory** [openstreetmap/openstreetmap-website#3042]
The OSMF Board, in preparation for it's weekend long meeting, will run [a survey of the OSM communities](https://lists.openstreetmap.org/pipermail/talk/2021-January/085912.html), like previous years. The survey isn't ready yet. When it ready, would it be possible to have a banner on OSM.org asking for people to fill it in?

**Comment by pnorman** [comment]
The [banner policy](https://operations.osmfoundation.org/policies/banner/) is concerned with event banners. I'd defer to the CWG on something like this.
