### ISSUE TITLE
Make right column map fixed positioned

### ISSUE THREAD

**Issue by samanpwbb** [openstreetmap/openstreetmap-website#305]
Th right column map is now fixed positioned on http://www.openstreetmap.org/browse/changesets

Lets do the same thing on other pages that follow the same layout pattern:
- [ ] user profile
- [ ] browse pages

**Comment by gravitystorm** [comment]
The user profile page now has a responsive layout. It might be nice to use some kind of `position: sticky` to keep the map in view when it's in two-column layout, however, the current version of bootstrap doesn't offer responsive positioning and so a sticky map would look bad in the single-column view.

I think this is a low enough priority that, in the meantime, this issue can be closed.
