### ISSUE TITLE
Switching to a mode of transport for which a path exists does not return a path

### ISSUE THREAD

**Issue by mateuszmp** [openstreetmap/openstreetmap-website#3050]
When a user selects a path between two points for which there is no path by car and then uses the drop down to select walking then the message "Couldn't find a route between those two places." will still be displayed, even though a path exists for walking. 

Steps for reproduction:

1. Open https://www.openstreetmap.org/directions?engine=graphhopper_car&route=58.924%2C43.726%3B50.062%2C19.937
2. As you can see there is no path by car which connects these two points.
3. Use the dropdown in the top left corner to select any walking directions.
4. Observe the message "Couldn't find a route between those two places."
5. Press the blue "Go" button and notice that a path by foot does in fact exist.

**Comment by tuckerrc** [comment]
Using the link you provided graphhopper and OSRM both found a route for walking. It's possible that the new route had not been imported into graphhopper or OSRM when you did your tests.

**Comment by mateuszmp** [comment]
There is a path for walking. However it does not find it before pressing the blue button after just changing the dropdown. This is in contrast to scenarios where a path exists and then switching does not require the blue button, but simply changing the dropdown.

**Comment by mateuszmp** [comment]
Normally the user selects two points and a path is found. Then they can change the dropdown and a new path is calculated for the desired method of transport / provider. This does not require clicking the blue button.
What I'm pointing out is that when a path is not found for the first method of transport / provider, then changing the dropdown does not recalculate the path and pressing the blue button is required.

**Comment by tuckerrc** [comment]
I see the issue now. Once the search reports "Couldn't find a route between those two places." the only way to display a new route is to search again with a mode of transport that does have a route.

GraphHopper returns a 400 error. The `polyline` is removed from the map and the event function has a catch to not run if the `polyline` is not on the map.
