### ISSUE TITLE
Search does not find features named using emojis

### ISSUE THREAD

**Issue by mateuszmp** [openstreetmap/openstreetmap-website#3051]
When naming a map feature with an emoji and later searching for it the feature is not found.

See: https://www.openstreetmap.org/way/340612933
It is named with an emoji, however searching for 🍑 in the top left search bar does not return any results.

**Comment by tomhughes** [comment]
Search is implemented by nominatim, not by the code in this repository.

**Comment by tomhughes** [comment]
I would also add that is completely inappropriate behaviour to conduct "tests" like this in the production datrabase.

**Comment by tomhughes** [comment]
You can report nominatim issues at https://github.com/osm-search/Nominatim/issues but as it's unlikely that there would be a genuine reason to name an object in this way (as against artificial tests) it's unlikely to be high priority.

**Comment by mateuszmp** [comment]
Sorry, new to this and excited. 
Haven't modified the database in any other way (except for legitimate changes).

**Comment by SomeoneElseOSM** [comment]
(not that its relevant to this repository but) interestingly, Nominatim does find https://www.openstreetmap.org/way/243532655 which is a name that does contain an emoji.  Whether that name is "correct" is another matter; it's what's on the sign, but may not be what they've registered the business as.

**Comment by TurnrDev** [comment]
@SomeoneElseOSM `♥` is pre-emoji unicode so that could be why whereas `🍑` was introduced as emoji.

I would say there are examples when an emoji might be used as I've seen "cute and hip" places use emoji in their names.
