### ISSUE TITLE
When external editor is not installed the alert disappears too soon

### ISSUE THREAD

**Issue by mateuszmp** [openstreetmap/openstreetmap-website#3054]
Tested on Chrome on Windows 10.

I do not have JOSM installed on my computer.
I selected the option to edit in an external editor.
A javascript alert showed up but disappeared before I could read it.

Full reproduction:
https://user-images.githubusercontent.com/19210834/104812465-93ee9f00-5802-11eb-844d-186fc984617e.mp4

**Comment by tuckerrc** [comment]
Reproduced on Chrome Fedora Linux. The alert never shows up it just fails quietly.

Tested with Firefox on Linux and the alert shows and requires me to close it before I can do anything else (probably the expected behavior).

Duplicate #1920

**Comment by tomhughes** [comment]
It's a javascript alert so how it is displayed and how long for is entirely a matter for the browser and outside our control.
