### ISSUE TITLE
Suggestion: Redirect osm.org/© to https://www.openstreetmap.org/copyright

### ISSUE THREAD

**Issue by InsertUser** [openstreetmap/openstreetmap-website#3056]
I'm mostly suggesting this because I tried osm.org/© expecting it to redirect although it may provide a more compact attribution under extreme space constraints.

**Comment by tomhughes** [comment]
Why would you try that? Do you have a habit of making up URLs and hoping they work?

I wouldn't expect anybody to use the URL as the text of the attribution anyway - the URL is what you link to not what you display to the user...

**Comment by InsertUser** [comment]
I've never come across a clickable link on a printed leaflet where this may provide an alternative to miniscule-bordering-unreadable text, or omitting attribution altogether.  It isn't entirely unheard of for OpenStreetMap.org to be mentioned in Tweets, Toots, or other platforms with character limits either. 

As on Windows osm.org/© is slightly less typing and fewer characters than osm.org/copyright I thought I'd give it a go as that seemed to be the whole point of the alternate domain. 

As I said, just a suggestion.

**Comment by tomhughes** [comment]
Right but nobody would print that URL on a leaflet because only one person in a thousand would actually know how to type it!

**Comment by migurski** [comment]
FWIW, I think this is a great idea: compact attribution with a meaningful URL will make it easier to formalize workable attribution requirements. Osm.org/c might be an easier-to-type variant.

**Comment by dieterdreist** [comment]
Am So., 17. Jan. 2021 um 18:39 Uhr schrieb Michal Migurski <
notifications@github.com>:

> FWIW, I think this is a great idea: compact attribution with a meaningful
> URL will make it easier to formalize workable attribution requirements.
> Osm.org/c might be an easier-to-type variant.
>


these are just links though, the link text (attribution) would have to
state OpenStreetMap in the long form, this is our trademark, and the name
of the project. "osm" is nothing when it comes to attribution.
