### ISSUE TITLE
Coordinates in the form of integers automatically converted to a different address

### ISSUE THREAD

**Issue by kpadewski** [openstreetmap/openstreetmap-website#3058]
Using "directions from here" option, whether you input coordinates in the form of integers or zoom out enough and manually set a point clicking on a map - you get coordinates in the form of integers in one of the input fields, which very quickly change into an address. But it's not the closest possible address to the point described by those coordinates, but a totally different address with for example one of the coordinates as a street number.

https://user-images.githubusercontent.com/34411976/104849375-9aa41180-58e9-11eb-97e2-aed1bff9860a.mp4

**Comment by tomhughes** [comment]
Well it should be whatever Nominatim returns - the same as you would get if you selected "Show address" from the right click menu at that location and in turn that should be what Nominatim thinks is the closest address.

As you haven't provided an example I can't investigate further, but if you think it's a problem with Nominatim then you can report it at https://github.com/osm-search/Nominatim/issues and if you think that we're not using what Nominatim returns for that location then please provide an example and we can reopen this.
