### ISSUE TITLE
I18n message with trailing whitespace

### ISSUE THREAD

**Issue by Nikerabbit** [openstreetmap/openstreetmap-website#3064]
Translatewiki.net does not support trailing whitespace in messages. Those should be removed if not needed or another workaround to be found if cannot be removed (but do note translations already do not have the space, so they are broken in that sense).

```
Osm:Javascripts.share.image size/en
'Image will show standard layer at '   | 'Image will show standard layer at'   
```

In this case this looks like a lego message which should have a parameter for flexible word order.

**Comment by tomhughes** [comment]
The space isn't actually needed because the code adds a space before the image dimensions, but it is a bit of a lego translation yes.
