### ISSUE TITLE
User diary - invalid date format

### ISSUE THREAD

**Issue by kudlav** [openstreetmap/openstreetmap-website#3067]
Visit https://www.openstreetmap.org/user/kudlav/diary/393208 in Czech laguage.
Date of creation and last update doesn't make sense.

> Zapsal kudlav **1. 492. 2020** v jazyce Czech (Česky). Naposledy aktualizováno **8. 327. 2020** 

Correct format should be _day. month. year_, for example _31. 12. 2020_

**Comment by tomhughes** [comment]
Translation errors need to need to be fixed at Translatewiki, not here - see https://wiki.openstreetmap.org/wiki/Website_internationalization#How_to_translate for more information.

In this case it's possible that it's actually a rails-i18n issue with date formatting - that would need to be raised at https://github.com/svenfuchs/rails-i18n/issues.

**Comment by tomhughes** [comment]
Yes that date is formatted with `I18n.l` so this is a rails-i18n issue.

**Comment by tomhughes** [comment]
No it's an issue in our translations - that date uses the `blog` format which is a custom formation in out translations - the `time.formats.blog` translation needs to be fixed on Translatewiki as it currently uses `%L` which is the miiliseconds component of the time... The formation characters are shown at https://apidock.com/ruby/DateTime/strftime.

**Comment by kudlav** [comment]
Hi I cannot report it at rails project as I has no knowledge how is the `I18n.l` used or where it is located in the code.

And it is actually issue of OSM web as THIS web is broken and when you just close it, no one will deal with it anymore. I think this issue is closed at the moment of deploying new fixed version of rails and after verifying that this really fixed it.

**Comment by tomhughes** [comment]
It can't be fixed in this repository and the maintainers of this repository have no knowledge of the Czech language which is why we rely on volunteer translators using the Translatewiki site. I've given details of the string which needs to be fixed but there isn't much more I can do.
