### ISSUE TITLE
marker in openstreetmap iframe not showing

### ISSUE THREAD

**Issue by thomasgermain** [openstreetmap/openstreetmap-website#3070]
I'm trying to have an interactive map when clicking on a device tracker tiles:

tile:
```javascript
{
             position: [0, 2],
             type: TYPES.DEVICE_TRACKER,
             id: 'device_tracker.thomas_phone',
             title: 'Thomas',
             map: 'yandex',
             states: {
                home: "Présent",
                not_home: "Absent",
             },
             zoomLevels: [13, 13],
             hideEntityPicture: true,
             slidesDelay: 2,
             url: "https://www.openstreetmap.org/export/embed.html?bbox=4.300460815429688%2C50.82290895637673%2C4.372129440307618%2C50.846814255780124&amp;layer=mapnik&amp;marker=50.8348631366327%2C4.336295127868652",
             action: function(item, entity) {
                        this.$scope.openPopupIframe(item, entity);
                     },
  
}
````
When using `openPopupIframe`, it showing this (note the missing marker):
![image](https://user-images.githubusercontent.com/12560542/105767084-ea728080-5f5a-11eb-83dc-64287f6033db.png)

I tried to embed the iframe directly in the `index.html` and here is the result (see the marker):
![image](https://user-images.githubusercontent.com/12560542/105767220-15f56b00-5f5b-11eb-8836-8ee0196fd8b6.png)

as far as I can see, when rendering the "hardcoded in index.html" iframe, the browser is querying the maker (png file). But when rendering the iframe with `openPopupIframe` it doesn't.

I'm using chrome Version 87.0.4280.141 (Official Build) (64-bit) (also tried with edge Version 88.0.705.50 🤓) 

Any idea how to fix it ?

**Comment by tomhughes** [comment]
We're not able to help you debug your web site, no.

**Comment by thomasgermain** [comment]
Oh sorry, wrong repo :confounded:
