### ISSUE TITLE
Missing translation for location point

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/openstreetmap-website#3072]
I was using a device with GPS to access the web map at [https://openstreetmap.org](https://openstreetmap.org).  Turned on GPS.  Pressed the location button.  Got the expected point/disc showing my location.  Touched the point, didn't get the expected co-ordinates/accuracy but instead got a pop-up error message about a missing en-GB translation.  Touched the disc and an area at the bottom of the window cleared in order to display a message but no message appeared.

**Comment by tomhughes** [comment]
I can't reproduce this. I'm using en-GB and I get the expected message in english saying I had denied location access.

**Comment by eehpcm** [comment]
@tomhughes 

> I get the expected message in english saying I had denied location access.

In which case you're not reproducing the situation.  I **allowed** location access.  Which is why the point within a disc appeared (as expected).  It is when I touch the location point that I get the missing translation error rather than the expected co-ordinates and accuracy.

**Comment by tomhughes** [comment]
But there is no popup when you allow access - the only popup is the one when you deny access.

Oh you're touching the actual blue circle on the map? I have no idea what that does and I'm not on a touchscreen device...

**Comment by tomhughes** [comment]
Ah OK a mouse click will reproduce it.

The en-GB translation is a bit of a massive crock so it's not entirely surprising...

**Comment by tomhughes** [comment]
Actually that key doesn't exist even in the master file so something is obviously wrong in the code...

**Comment by tomhughes** [comment]
Yes 587a1b0754 changed the way that string is handled but only one of the two uses of the locate control was changed...

**Comment by eehpcm** [comment]
@tomhughes 

It **used** to work.

It used to be the case that clicking on the darker blue central point popped up co-ordinates and accuracy (if my memory isn't letting me down).  It used to be that clicking within the lighter-blue disc (avoiding the central point) gave some lesser information (but I can't remember exactly what).
