### ISSUE TITLE
the look of notes

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#3075]
You've recently changed the look of buttons on Notes.
But the buttons are now too big and they don't fit on the screen:
![notes](https://user-images.githubusercontent.com/57260466/106171418-ccdb2c00-6191-11eb-8636-e4b9de686745.png)

When adding a new note everything is fine:
![notes2](https://user-images.githubusercontent.com/57260466/106171504-e4b2b000-6191-11eb-8438-2f4babdf5c74.png)

**Comment by tomhughes** [comment]
Well that does fit, it just wraps to a new line when it has to, which is dependent on the language you're using - as translations might be arbitrarily long there's no way to make a design which never does that.

**Comment by mxdanger** [comment]
![image](https://user-images.githubusercontent.com/32040254/107301376-3b40a980-6a30-11eb-9473-65a00de4420e.png)
This can be fixed by appending the bottom margin bootstrap class to the buttons.
