### ISSUE TITLE
2021 OpenStreetMap Community Survey: Say number of questions before email registration

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3076]
We see https://www.openstreetmap.org/assets/banners/banner_community_survey_200124-55a2b305b580a7c445a4dcc0dbe4069e22aaa9d2626357a7102847cf21a9e1ea.png
And go to https://osmf.limequery.org/281662 .
And need to submit an email.
And then get a reply.
And then back to a URL.
Only then do we even learn "There are 18 questions in this survey."
Many users would have probably quit earlier.

**Comment by jidanni** [comment]
In fact, why not first show the entire survey. And if the user, seeing they are interested, wishes to participate, then they could send the email etc. Whereupon the buttons would unlock.

**Comment by jidanni** [comment]
Sure, it might entail choosing a different survey package, but I bet you would have 50% more participants.

**Comment by jidanni** [comment]
OK, you don't have to switch packages. Just add a preview of the questions to the first page the user encounters.

**Comment by tomhughes** [comment]
The survey is run by the OSMF and is nothing to do with the web site maintainers. We just provide an advert for it in line with our [banner policy](https://operations.osmfoundation.org/policies/banner/).
