### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3080]
So immediately after merging #2409 , the build is now failing with:

```
Run docker-compose build
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Building db
Sending build context to Docker daemon  57.68MB

Step 1/3 : FROM postgres:11
11: Pulling from library/postgres
unauthorized: authentication required
Service 'db' failed to build
Error: Process completed with exit code 1.
```

@migurski any thoughts?

**Comment by gravitystorm** [comment]
Never mind - seems to have been a transient failure!

**Comment by Firefishy** [comment]
Yes, likely just a transient issue.

`postgres:11` is from here https://hub.docker.com/_/postgres and is an official base image.
hub.docker.com recently introduced rate limits, but unlikely this was the reason: https://docs.docker.com/docker-hub/download-rate-limit/

**Comment by migurski** [comment]
Hope it remains just transient; I’ll keep an eye on Docker-related things here.
