### ISSUE TITLE
Address post-merge Docker Compose cleanup issues

### ISSUE THREAD

**Issue by migurski** [openstreetmap/openstreetmap-website#3081]
Tom H identifies a few desired changes in https://github.com/openstreetmap/openstreetmap-website/pull/2409#pullrequestreview-582662631:

- [ ] Investigate alternative to Postgres sleep
- [x] Update checkout to v2
- [ ] Investigate bootsnap-related pollution in Rails setup files
- [ ] Move DB functions to either `lib` or `share`
- [ ] Determine if a DB password is needed when using trust auth
- [ ] Investigate whether `yarnpkg install` can move under `bundle exec`

I’ll look at each of these in a follow up PR and determine which needs a followup change vs. just an explanation.

**Comment by tomhughes** [comment]
The good news is that it all seems to work using `podman-compose` in place of `docker-compose` in Fedora 33.

**Comment by mmd-osm** [comment]
Re " Move DB functions to either lib or share" : /changes endpoint was removed yesterday, we don't need those DB functions anymore.

**Comment by tomhughes** [comment]
Also #3082 has bumped the checkout action version.

**Comment by gravitystorm** [comment]
> Re " Move DB functions to either lib or share" : /changes endpoint was removed yesterday, we don't need those DB functions anymore.

I know you'll have seen my comment, but just for other people's reference, we still need the function for the migrations: https://github.com/openstreetmap/openstreetmap-website/pull/2409#discussion_r570115583
