### ISSUE TITLE
Atom/RSS history of a user is broken

### ISSUE THREAD

**Issue by mnalis** [openstreetmap/openstreetmap-website#3085]
when opening a history of some user, for example:

```
https://www.openstreetmap.org/user/Matija%20Nalis/history
```

it contains a HTML Atom reference:
```
      <link rel="alternate" type="application/atom+xml" title="ATOM" href="{&quot;display_name&quot;=&gt;&quot;Matija Nalis&quot;, &quot;max_id&quot;=&gt;nil, &quot;xhr&quot;=&gt;nil, &quot;action&quot;=&gt;:feed}" />
```

which indicate I can get Atom feed for that page, which would be great.

It is however broken; if I try to open that URL (`https://www.openstreetmap.org/user/Matija%20Nalis/%7B%22display_name%22=%3E%22Matija%20Nalis%22,%20%22max_id%22=%3Enil,%20%22xhr%22=%3Enil,%20%22action%22=%3E:feed%7D?bbox=undefined`) in my RSS/Atom reader, I get following error:

```
File not found

Couldn't find a file/directory/API operation by that name on the OpenStreetMap server (HTTP 404)

Feel free to contact the OpenStreetMap community if you have found a broken link / bug. Make a note of the exact URL of your request.
```

**Comment by mmd-osm** [comment]
The link seems broken, but you can use `https://www.openstreetmap.org/user/Matija Nalis/history/feed` for the time being.
