### ISSUE TITLE
URL change

### ISSUE THREAD

**Issue by momohappy** [openstreetmap/openstreetmap-website#3093]
Hello,
Thanks for this useful repo.
I initialized my local website on this address       'example.ir/edit_road'   
I used proxy_pass in Nginx to route the above address to the project that is run on port 3000.
but now all static page and requests read from example.ir/   not from example.ir/edit_road.
I am not sure if there is a way to set something as a config. 
thanks in advance for your reply.

**Comment by tomhughes** [comment]
No, there is not.
