### ISSUE TITLE
Is OSM a map or a database?

### ISSUE THREAD

**Issue by natrius** [openstreetmap/openstreetmap-website#3099]
Its a dumb question, yes, but:
I read all the time, it is a database and not a map. On the other side it is named "OpenStreetMap" and the first thing people see, when connecting to https://www.openstreetmap.org is - a map. No further information, just a map. 

I'm asking, because depending on the outcome it may be good to change what the first-time-visitor is seeing right now. Or should this be asked somewhere else?

**Comment by gravitystorm** [comment]
> Or should this be asked somewhere else?

Feel free to discuss this elsewhere, such as in the forums or the mailing lists or the discussion venue of your choice.

This is not a discussion that will be productive in this issue tracker.
