### ISSUE TITLE
Export of messages from internal message system

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/openstreetmap-website#3106]
Both from a practical (see https://github.com/openstreetmap/openstreetmap-website/issues/3105) and legal POV (GDPR data portability requirement) there should be a way to export the contents of a users in- and outboxes in some kind of portable format. 

@woodpeck do you remember if we added this to the de facto defunct GDPR requirements list?

**Comment by tomhughes** [comment]
I fail to understand what #3105 has to do with wanting to export messages.

I mean we can leave this open but I can't imagine anybody rushing to implement a feature that approximately nobody will use anytime soon.

What format would we use anyway? Is there some EU standard for portable private messages that I'm not aware of?

**Comment by simonpoole** [comment]
Well if there was an "export and maybe delete" function, I could export the messages from the internal mail system for archival purposes, and reduce the number of messages down to a level where pagination doesn't matter (say once per year).

**Comment by kmpoppe** [comment]
Good evening,
just today, as I was wondering whether an archive of messages on the website would make sense (you being able to move In- and Outbox messages there), I came across this issue - and while I am not 100% sold on the neccessity that one would have to remove messages from the server would be a specific GDPR requirement, if it ever came up that OSM.org would not be allowed _by law_ to save these conversations for more than say 1 year or something, it would be extremely great to be able to export the messages to keep as a backup should you so wish.

> What format would we use anyway? Is there some EU standard for portable private messages that I'm not aware of?

No, there's no such format to my knowledge, but what if this took the approach that's ALMOST already there. We already get an email when a new message arrives. What if me made an export as an .eml message possible? The From: and To:-addresses could be something like "OSM USERNAME" <>, essentially giving it empty addresses that will never work from within an email client, but will display correctly. There already is an engine to convert Markdown into HTML to display it, so this could easily feed an text/html MIME part of the .eml file with the text/plain part being either "you need an HTML-enabled client to view this message" or just use the engine that creates the text/plain part of the message for the email we already get nowadays.

I would have created a showcase but it seems there's no API access to messages (apart from the `received`, `unread` and `sent`-counts in `/user/details` which wouldn't help here) - if there was we could even create an IMAP- or POP3-endpoint for the messages to retrieve them to your local machine.

Granted, fantasy might have gone a little wild here, but there would be ways to solve this. Magically finding people who code these otoh will be the obvious issue...

**Comment by mmd-osm** [comment]
#4509 might provide the technical foundation to build such a tool (even outside of this repo).

**Comment by mmd-osm** [comment]
My proposal would be to use some shell script as follows:
