### ISSUE TITLE
External Authentication setting is not working

### ISSUE THREAD

**Issue by ypcyc** [openstreetmap/openstreetmap-website#3114]
When I select anything except "None" and try to save, I get error. I have turned off Ablocks in Chrome, tried in Incognito mode and with fresh Firefox install and also on Chrome Android. 
![image](https://user-images.githubusercontent.com/1402005/109777427-5dcb7a00-7c0c-11eb-99f9-d856eff181fb.png)
Error on save:
![image](https://user-images.githubusercontent.com/1402005/109777451-66bc4b80-7c0c-11eb-9181-d3edbbd5802a.png)

**Comment by Firefishy** [comment]
What page or URL is this for?

**Comment by ypcyc** [comment]
https://www.openstreetmap.org/user/XXXXX/account aka "My settings" -> "External Authentication" change to any from "None" -> "Save"

**Comment by tomhughes** [comment]
It's the setting page @Firefishy. I can reproduce it but unfortunately it's likely to be very hard to fix it.

**Comment by tomhughes** [comment]
Actually we might just get lucky... Let me see what I can do.

**Comment by ypcyc** [comment]
@tomhughes Thanks for quick fix! It's now working on Desktop and I was able to set Google in settings and login with Google account, but it still gives error in Chrome on Android!
![image](https://user-images.githubusercontent.com/1402005/109794690-cae80b00-7c1e-11eb-9619-5ab69387d60e.png)

**Comment by tomhughes** [comment]
That appears to be a picture of the login screen and therefore unrelated to this bug which is about enabling external authentication from the settings screen.
