### ISSUE TITLE
Use rails test:all (rails 6.1+)

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3116]
Rails doesn't run system tests by default, so [we have modified the `rake test` command](https://github.com/openstreetmap/openstreetmap-website/blob/2233edbcfa15d532c2232e5e71a2a2495e3a72eb/lib/tasks/testing.rake), so that it runs our system tests as well. But this only works when running e.g. `bundle exec rake test`, and not `bundle exec rails test` (n.b. `rake` vs `rails`)

The `rails test` alternative is subtly different, since it supports some additional niceties like running individual test files or all files in a directory. So I would like to update our documentation, but then we lose out on running the system tests via our patch.

Rather than delving into how to make the system tests run by default via `rails test`, I think we can drop our patch and just use the new `rails test:all` in our documentation and CI scripts. That way it's less code, only slightly more typing, but also in line with normal rails practices.

Blocked by #3021

**Comment by openbrian** [comment]
Thank you!  This was a hurdle in my development of openstreetmap-website!
