### ISSUE TITLE
Do not display user profile of someone who made 0 edits - to hide spam

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#3128]
Is there any good reason at all to display user profile text for people who have 0 edits?

I know I can report user profiles with spam (I just did it with several, they will become soon deleted like previous group of reports), but maybe that kind of busywork can be avoided by not displaying such profiles at all? And laziest spam would never become visible to anyone.

[search for casino alone](https://www.google.co.uk/search?q=site:openstreetmap.org+inurl:user+casino&ei=17xLYOfqNIKykwW84KWoAw&start=80&sa=N&ved=2ahUKEwinspPSuqvvAhUC2aQKHTxwCTUQ8tMDegQIBRBT&biw=1920&bih=919) reveals plenty of spam profiles.

See also other spammy keywords: https://wiki.openstreetmap.org/wiki/Spam/Report_user (casino, dating, mortgage ones can be all reported - I have not went through them today)

**Comment by tomhughes** [comment]
Sure, there are lots of users who never edit but who post diary entries (legitimate ones) or upload traces etc, etc.

**Comment by matkoniecz** [comment]
What about showing user profile of such users only to other logged in users?

Or show profile if user performed any other activity except editing profile? Maybe it would make spam profiles a bit more useless and discourage their creation a bit?
