### ISSUE TITLE
Rate limit sending PMs for people who never were sending them or have active "block user" reports?

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#3135]
Maybe that would help a bit with growing number of spam PMs linking to porn sites?

**Comment by tomhughes** [comment]
We rate limit all PMs already.

**Comment by matkoniecz** [comment]
I know, but I though about stricter limits (1 message in 20 minutes or similar) for accounts with higher spam risk.

**Comment by matkoniecz** [comment]
From asking other mappers - it seems that ongoing porn/scam site spam attack is not sophisticated, link to `https://go.cm-trk4.com/` domain seems shared by spam PMs.

Maybe starting from blacklist of terms that would vastly increase consumption PM quota would be viable start? Blacklist will fail against sophisticated spam attacks, but this one seems to not be come complicated one, they are not even using domain pool.

**Comment by berrely** [comment]
Perhaps also blocking URLs in [these datasets](https://github.com/rlilojr/Detecting-Malicious-URL-Machine-Learning) might be useful as well.

**Comment by matkoniecz** [comment]
Note that current porn/"dating" spam/scam attack continues using the same website `https://go.cm-trk4.com/` - maybe starting some blacklist of strings which would cause severe exhaustion of PM quota would be useful?

Or outright blocking messages containing `https://go.cm-trk4.com/` string?

Yes, that would start whack-a-mole but maybe they would switch to some other softer target?
