### ISSUE TITLE
search result

### ISSUE THREAD

**Issue by istefanos** [openstreetmap/openstreetmap-website#3150]
When I'm searching for 'teaching center wien', the results are:

- https://www.openstreetmap.org/node/1466988216
- https://www.openstreetmap.org/way/247495121

I would expect to get this result:

- https://www.openstreetmap.org/way/452432519

**Comment by tomhughes** [comment]
The search is provided by https://github.com/osm-search/Nominatim and there's nothing we can do to change it locally.
