### ISSUE TITLE
routing to the the entrance

### ISSUE THREAD

**Issue by istefanos** [openstreetmap/openstreetmap-website#3151]
When I'm looking for a route to 'Universitätszahnklinik', I don't get a suggestion to get to the entrance:

- https://www.openstreetmap.org/relation/2053358

I would expect a route to the entrance, when there is an entrance added, like this:

- https://www.openstreetmap.org/node/5508672717

Where should a route lead to? To the centre of a point, to the main entrance?

**Comment by tomhughes** [comment]
You will need to contact the provider of whichever routing engine you are using - we don't actually provide any routing ourselves but instead just provide access to several third party engines that use our data.

**Comment by systemed** [comment]
To expand slightly, the placename lookup is done by Nominatim. That currently doesn't return the lat/lon for entrances, only for a centroid:

https://github.com/osm-search/Nominatim/issues/536

As and when someone can enhance Nominatim to return entrance co-ordinates, then openstreetmap.org can use this information to send to the routing engine. But it requires a change in Nominatim first.

**Comment by istefanos** [comment]
Thanks for the quick responses and sorry for the wrong adressee.
