### ISSUE TITLE
Registering in the 'login with OSM-screen' is broken

### ISSUE THREAD

**Issue by pietervdvn** [openstreetmap/openstreetmap-website#3156]
Hey everyone,

As the author of MapComplete, I noticed that the flow to register is broken:

To reproduce:

1. Go to https://mapcomplete.osm.be/aed - make sure you are logged out, e.g. in private navigation
2. Click 'login with OpenStreetMap'
3. Click the register-now button in the login flow provided by OSM.org

When clicking the register-button, the user is redirected to the normal login-screen immediately again.

Kind regards and thanks for the good work!

**Comment by tomhughes** [comment]
Please describe your problem in terms of the OpenStreetMap web site rather than third party applications which are not maintained by us.

**Comment by pietervdvn** [comment]
Hey, this is about the OAuth part, which _is_ provided by the OSM-website. However, you need to go via any third-party site to test this.

**Comment by gravitystorm** [comment]
I can see the problem - I'll fix it shortly. It's got nothing to do with OAuth.

**Comment by pietervdvn** [comment]
@gravitystorm Great! Thanks for the reply. It is indeed not an OAuth-bug, but rather something in the "login with OSM to get a token"-flow (which is OAuth related)

**Comment by tomhughes** [comment]
I just tried it and assuming that "register now" is the signup link in top right then it seems to work fine for me.

**Comment by tomhughes** [comment]
I'm more wondering why I got OSM in Italian to be honest, at least I think it was Italian.

**Comment by pietervdvn** [comment]
No, it is about this link: 
![image](https://user-images.githubusercontent.com/1466478/112847689-9fcecb00-90a7-11eb-8f0e-f977139a3f22.png)

**Comment by pietervdvn** [comment]
Seems like the link is indeed also broken in the login form, not only when logging in for OAuth.

Smells like a duplicate of #3157

**Comment by gravitystorm** [comment]
Yes - this is why I said it wasn't related to OAuth - the "Register now" link on the Login page is broken for all users. This is because of some refactoring that I did last week, where I overlooked that link, combined with having no tests that follow it.

I've fixed the link and added a test in #3157

**Comment by pietervdvn** [comment]
Thanks for the quick fix! I can confirm it works.
