### ISSUE TITLE
Deletion of a comment with confidential information on a changeset.

### ISSUE THREAD

**Issue by SHARCRASH** [openstreetmap/openstreetmap-website#3161]
Hello! I was discussing about an issue on a changeset and without paying attention i wrote a confidential information.  So I need my comment to be deleted on that changeset, (not the description of the changeset). The other user hasn't replied yet so in terms of historic comment it won't put any discontinuity. 
I've already contacted an OSM moderator without any response. Can someone here help me, please?

**Comment by tomhughes** [comment]
No, we develop the code for openstreetmap.org but we don't run the site.

The people that can help are probably the [Data Working Group](https://wiki.osmfoundation.org/wiki/Data_Working_Group).

**Comment by SomeoneElseOSM** [comment]
(for the avoidance of doubt).  Moderators (i.e. the DWG) can hide "changeset discussion comments" (added to a changeset afterwards) but not the original changeset comment that was added when a changeset was saved.
-- Andy (from the DWG)
