### ISSUE TITLE
emergency=yes tag regarded as a feature instead of an access tag

### ISSUE THREAD

**Issue by 501Ghost** [openstreetmap/openstreetmap-website#3170]
When querying features on osm.org, OSM seems to regard features tagged with emergency=yes as emergency features instead of other features that simply have access for emergency services. I request a change to ignore emergency=yes when describing the feature, and instead focus on other main tags such as highway=*.

A good example is the Hoogstraat in Wageningen, which is a pedestrian highway:

With emergency=yes: https://www.openstreetmap.org/way/297710230
https://user-images.githubusercontent.com/11884358/114218430-ad1e6c00-9969-11eb-856c-7e18bf3b5589.png

Without emergency=yes: https://www.openstreetmap.org/way/6921808
https://user-images.githubusercontent.com/11884358/114218441-b1e32000-9969-11eb-89c1-3adf3b405b8b.png

Kind regards,
Casper & Vakonof

P.s. This has already been posted at Nominatim as well as Overpass. We were sent here and I hope we've found the right recipient this time:
https://github.com/osm-search/Nominatim/issues/2257
https://github.com/drolbr/Overpass-API/issues/616

**Comment by tomhughes** [comment]
There isn't really any "classification" code at all, just a long list of key/value pairs and translatable names for them.

If there is more than one tag on an object that exists in our translations then it's basically random which one is used in the list.

I believe https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/javascripts/index/query.js#L80 is the relevant code and as you can see it just searches the keys at https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/en.yml#L505 and takes the first match it finds.

**Comment by tomhughes** [comment]
I'd just add that those strings are used for other things like formatting search results so we can't easily just remove "emergency: yes" from them without studying what the overall effect would be.

**Comment by 501Ghost** [comment]
Thank you for the quick and informative reply.

From my perspective, the overall effect of skipping emergency=yes/no would be that an access tag gets ignored in favour of other tags which are more likely to be features (such as highways). OSM would then describe features according to these other tags instead of defining features by an access tag. 

What else do you think would be needed to study the effect of such a change?

**Comment by lonvia** [comment]
It's fine to remove. Nominatim doesn't send results with `emergency=yes`. I thought I had used the "yes" as a fallback for unknown values but apparently that was an idea that got never implemented.

**Comment by 501Ghost** [comment]
Since I'm not a programmer myself, could you implement this change, please?
