### ISSUE TITLE
leisure=horse_riding is not showing

### ISSUE THREAD

**Issue by Nic787** [openstreetmap/openstreetmap-website#3171]
Hi,

I don't know if it's a bug or not, but when using leisure=horse_riding on an area or a node, the name is not showing on the final render. We can search and find the horse riding facility with the search bar on OSM, but the name is just not there. I don't know if it's the same for other leisure. I know you can instead name a farmyard, but sometime there is just no clear border of where the farmyard start or finish.

Thank you

**Comment by tomhughes** [comment]
It may or may not be a bug but what it definitely isn't a bug in the web site code.

The web site displays map tiles from a number of providers but it doesn't do any map rendering itself.

Assuming you are referring to the default style then you want https://github.com/gravitystorm/openstreetmap-carto/issues.
