### ISSUE TITLE
The way "shop=agrarian" are displayed

### ISSUE THREAD

**Issue by Asteliks** [openstreetmap/openstreetmap-website#3175]
For some reason agrarian shops are displayed only as dots on the map. There is no icon and name. See this for reference: https://www.openstreetmap.org/node/2706322467

**Comment by tomhughes** [comment]
The web site displays map tiles from a number of providers but it doesn't do any map rendering itself.

Assuming you are referring to the default style then you want https://github.com/gravitystorm/openstreetmap-carto/issues.

**Comment by Asteliks** [comment]
thanks will move this issue there
