### ISSUE TITLE
Account for teachers (SNT class in France)

### ISSUE THREAD

**Issue by tykayn** [openstreetmap/openstreetmap-website#3176]
Since a few years, France has introduced the SNT class in which, contributing to OSM is an important part.
But nothing exists to share an account with a class, and have the ability to administrate it with an other account.
The goal is to give access to an account to a whole class but not give them the ability to change the ownership of the account, and the ability to target vandalism changeset and revert them easily.

Outside school classes, this would be useful to animate teaching spaces so that everyone does not have to create their own account. The DB would benefit to have less unused accounts for all the people who do not contribute at all after the mapping party or teaching shop.

I guess many other needs exists, inputs are very welcomed on this idea.

**Comment by mmd-osm** [comment]
This seems to be very similar to #1823

**Comment by tykayn** [comment]
it is, sorry for inconvenience, we should continue talking in #1823
