### ISSUE TITLE
Question: What path finding algorithm is used?

### ISSUE THREAD

**Issue by McCrafterIV** [openstreetmap/openstreetmap-website#3178]
I would want to know which algorithm osm uses to calculate a route. It would be great if someone could provide a link to the source code or the official docs. Sadly I couldn't find something myself.

**Comment by woodpeck** [comment]
This repository contains the code running the OSM web site. The route finding is not part of this web site or repository; instead, routing requests are delegated to other routing engines, namely GraphHopper https://github.com/graphhopper/graphhopper and OSRM https://github.com/Project-OSRM/osrm-backend . Both engines support "contraction hierarchies" and other routing algorithms.

**Comment by McCrafterIV** [comment]
Thanks for the quick reply and the links! Closing since my question is answered :)
