### ISSUE TITLE
Update editor-layer-index independent of a new iD release

### ISSUE THREAD

**Issue by rbuffat** [openstreetmap/openstreetmap-website#3179]
Currently, it looks as the version of iD deployed to the OSM homepage updates the imagery index only with a new release. At the moment it seems to be normal that there are [multi-month long gaps between releases of iD](https://github.com/openstreetmap/iD/releases).  The long delay of ELI updates causes some issues, e.g.:  https://github.com/osmlab/editor-layer-index/issues/1112  Thus, would it be possible to update the editor-layer-index in the iD version of the OSM homepage more often (e.g. weekly or bi-weekly).

Rebuilding iD with an up-to-date version of editor-layer-index is not complicated:

```
rm -rf node_modules/editor-layer-index/
cp -r up/to/date/editor-layer-index/ node_modules/
npm install
npm run imagery
npm run all
npm start
```
CC @quincylvania

**Comment by gravitystorm** [comment]
The version of iD, including any node_modules that iD depends on, is managed by the iD developers. When they want to update any part of it, including things like the editor layer index or the tagging presets or any other part of iD, they send us a pull request.

It's unlikely in the extreme that we would start overriding any iD dependencies ourselves. There are all kinds of edge cases (e.g, if the editor index changes some internal data structure or somesuch) that they know about and have tests for, and we don't. I wouldn't be happy with us changing any of their dependent node_modules beyond what they send us during each update.

So for the moment I would suggest the best solution to this is to suggest more frequent point releases to the iD developers, and see what they think.

**Comment by tomhughes** [comment]
I agree with @gravitystorm I don't think we want to get into making downstream modifications to iD.

If nothing else we would have to patch the version number in some way to make it clear it's not the original upstream release which immediately complicates the rebuild process described above.

**Comment by rbuffat** [comment]
I understand your point of view.  

It is just that with regular releases of iD this would not be that of an issue as it is at the moment. But in 2021 the number of commits to iD seems to have significantly dropped: https://github.com/openstreetmap/iD/graphs/commit-activity I don't know what's the reason for this, but this is not a good sign that it is likely that there will be more frequent releases in the future. 

The format of the imagery.geojson of ELI should remain stable and the quality of the imagery sources included in ELI are checked by extensive tests. Thus, the risk that something breaks should be quite low.

**Comment by rbuffat** [comment]
[According to recent news](https://blog.openstreetmap.org/2021/04/26/joint-statement-from-quincy-morgan-and-the-osmf-board/), it looks as there is at the moment no developer of iD left. This probably means no new iD releases in the near future and thus no updates of the imagery. 

I hope you also consider it an issue if the editor "which 80% of OpenStreetMap users contribute to the common edifice" uses outdated imagery.  Are there any plans to bridge the gap until new developers are found? 

With some guidance from @quincylvania, I should be able to create PRs of the current release of iD with an updated ELI until there are new developers found if this is of any help. 

CC @grischard

**Comment by bhousel** [comment]
For what it's worth, we have lots planned for [RapiD](https://github.com/facebookincubator/RapiD), and our team will continue to make releases about once or twice a month that will have the latest imagery from ELI and string translations from Transifex. 

I can also publish data releases anytime to other ancillary datasets like [osm-community-index](https://github.com/osmlab/osm-community-index) and [name-suggestion-index](https://github.com/osmlab/name-suggestion-index).  Current releases of RapiD will automatically fetch compatible versions of these projects.

Anyone who wants an iD-like editing experience can use RapiD at either of these sites:
https://mapwith.ai/rapid
https://ideditor.org/latest-rapid

Have fun and happy mapping!  ✌️
