### ISSUE TITLE
Using Github for login: How can I login to {help,forum}.openstreetmap.org?

### ISSUE THREAD

**Issue by dreua** [openstreetmap/openstreetmap-website#3181]
I'd like to reply to questions on "help" occasionally but can't login. Needs fixing or better documentation imo.

**Comment by woodpeck** [comment]
Frankly I don't know where you get the idea that you could use Github to log in to either of these sites? An OpenStreetMap user name and password (https://www.openstreetmap.org/user/new) will get you into help and forum. 

Note that this repository here is for software that drives the OSM website at www.openstreetmap.org and questions regarding either help.openstreetmap.org or forum.openstreetmap.or are off topic; the openstreetmap/operations issue tracker is the best place for that kind of discussion. See also https://github.com/openstreetmap/operations/issues/149 where we discuss replacing the somewhat broken system behind help.openstreetmap.org.

**Comment by tomhughes** [comment]
As @woodpeck says this doesn't seem to have any obvious link to this repository.

@dreua if you're having trouble using your OSM account to login to help,openstreetmap.org then please contact support@openstreetmap.org for assistance.

**Comment by dreua** [comment]
> Frankly I don't know where you get the idea that you could use Github to log in to either of these sites?

I can use my Github to login to the [main site](https://www.openstreetmap.org/login), i.e. editing the map, creating, editing and closing notes is all tied to my Github Account. (Or, as I just found out, technically an OSM account of the same name?)

I found the solution: Set a password on my account in the settings and use that to login to the other service. Thank you for the replies and sorry for creating this issue in the wrong repository.

I still think the UX could be improved for Github users like me, but I understand that this is a non-profit project driven by hobbyists which can not polish each use case.

**Comment by lectrician1** [comment]
@dreua In what way do you think the UX should be improved so that this doesn't happen again?

**Comment by tomhughes** [comment]
To repeat everything said earlier, discussing the UX of help.openstreetmap.org here is not appropriate - this track is for www.openstreetmap.org only.

There is no realistic prospect of changes to help.openstreetmap.org anyway as it runs on third party technology that is pretty mush dead upstream which is why we are looking to replace it.

Any replacement will likely use OAuth which means that any means of logging in to osm.org will work - the password proxying system used by help.osm.org and forum.osm.org was never a good idea and we would not look to use it in future.

**Comment by dreua** [comment]
@lectrician1 Ideally there would be a single sign on (as in SSO) page for everything using the osm account. This would also improve security as users are less likely to enter their credentials into any third party pages when you refrain from teaching them that it is fine and necessary to enter them on a bunch of very different looking pages in the first place.

I think I was especially confused because the ["help" login page](https://help.openstreetmap.org/account/signin/) login page shows a total of 12 sign in methods (yes, 12 at once, this could easily become a negative example in UX books) but Github was not among them. Some similarity to the [main site login page](https://www.openstreetmap.org/login) would be a good idea and a Github-logo bearing button pointing me to the workaround stated above would have easily prevented me from creating this issue.

**Comment by lectrician1** [comment]
@tomhughes I accidentally thought they were taking about the UX of osm.org.
