### ISSUE TITLE
Add Mapillary and Kartaview map layers

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/openstreetmap-website#3190]
As an active user of the site and iD, I often find myself wanting to verify the placement, tagging, or up-to-date-ness of OSM map features by looking at street level imagery. 

This requires me to either:
1. Wait for iD to open and then select Mapillary or Kartaview map layers
2. Go to Google Maps or Mapillary's site (which I usually do)

Clearly this is not optimal and could be solved by providing the services as map layers on osm.org.

It is known that because these services provide their data for OSM voluntarily for editing purposes, we don't provide imagery directly on the site.

**_However,_ what if we only provided the map layers for logged-in users?** This would limit access to "editors" and limit the usage of the resources.

Allowing the map layers for logged-in users could also possibly apply for aerial imagery as well (#974).

**Comment by tomhughes** [comment]
Please see https://wiki.openstreetmap.org/wiki/Featured_tile_layers/Guidelines_for_new_tile_layers for our policy on tile layers and how to propose new layers.
