### ISSUE TITLE
Current layer not marked obviously enough in Layers Panel

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3196]
Takes a rather sharp eye,
![e](https://user-images.githubusercontent.com/1230959/118061006-ababed80-b3c6-11eb-8713-b03d6ce88205.jpg)
to tell which layer is selected.

**Comment by polarbearing** [comment]
The frame in the layer panel is quite obvious for me, and of course I see the chosen style applied in the main part of the window. 
Your example shot looks downsized, what device/screen resolution is that from?

**Comment by jidanni** [comment]
I am emulating how it looks to older users.
Thin green is bad because, well as you see lots of the world is green according to those maps.
Thick orange would be better.

**Comment by jidanni** [comment]
Or some other color... Blue would be bad because most of the world is ocean.

**Comment by nitramwin** [comment]
This is an excellent idea @jidanni

**Comment by AntonKhorev** [comment]
https://github.com/openstreetmap/openstreetmap-website/pull/3674 changes it to blue

> Blue would be bad because most of the world is ocean

but usually you are not looking at the map of the ocean

**Comment by AntonKhorev** [comment]
#4674 made the frame blue but also twice as wide, it should be visible enough now
