### ISSUE TITLE
On element info tag has no link to wiki

### ISSUE THREAD

**Issue by hubaishan** [openstreetmap/openstreetmap-website#3197]
I created  a wiki pages for import tags GNS:id, GNS:dsg_code but when browsing as OSM element the keys have not a link to wiki pages

**Comment by lectrician1** [comment]
That's because the script that gets wiki pages and stores them for the website to reference needs to be run: 
https://github.com/openstreetmap/openstreetmap-website/blob/master/script/misc/update-wiki-pages
