### ISSUE TITLE
Link to nominatim including search query

### ISSUE THREAD

**Issue by andrewharvey** [openstreetmap/openstreetmap-website#3205]
Search results include "Results from OpenStreetMap Nominatim" which links to https://nominatim.openstreetmap.org/. To help mappers debug search results to determine if unexpected search results are OSM data issues or not, it can be handy to inspect the full search results output available at nominatim.openstreetmap.org.

To make this easier for mappers we should directly link including the search query, via `https://nominatim.openstreetmap.org/ui/search.html?q=`.

Either this URL could replace the "Results..." link or we could add another link "View search on Nominatim" at the bottom which includes the full query included link.

![2021-07-02_11-22](https://user-images.githubusercontent.com/117278/124207004-d3e2dd80-db27-11eb-8062-3dce4ce245e6.png)

**Comment by lectrician1** [comment]
Could you rewrite your the first sentence of your issue? It's really hard to understand what you're asking because it runs on.

**Comment by tomhughes** [comment]
I understand perfectly well what he wants, but it's not that easy because we use the API so we never actually have the URL he's asking for.

**Comment by andrewharvey** [comment]
> Could you rewrite your the first sentence of your issue? It's really hard to understand what you're asking because it runs on.

I've tried to improve the readabality.

> I understand perfectly well what he wants, but it's not that easy because we use the API so we never actually have the URL he's asking for.

Wouldn't it just be `https://nominatim.openstreetmap.org/ui/search.html?q=${encodeURIComponent(query)}` ?

**Comment by lonvia** [comment]
The URL should include all parameters (including bbox and language) to get exactly the same result. You can simply use the API URL with `format=xml` replaced with `format=html`. There are redirects in place towards the UI.
