### ISSUE TITLE
"Zoom in to query features" stays visible if you click the query button then zoom in

### ISSUE THREAD

**Issue by EdLoach** [openstreetmap/openstreetmap-website#3207]
Latest stable Opera browser on Windows 10. Logged in to website (haven't tested when not logged in).

Steps to reproduce:

- Zoom out
- Hover over query features button - message appears
- Click the button - message remains when you mouse off the button
- Zoom in - message remains even once you are able to query features until you actually do.

Only a minor issue if you are actually trying to query features, as querying clears the message, but I'd clicked the button by mistake and ended up refreshing the page to get rid of the message.

**Comment by mmd-osm** [comment]
Clicking anywhere on the map makes the popup go away here.

**Comment by EdLoach** [comment]
So it does. How did I not try that? Ignore me - I'll close this.
