### ISSUE TITLE
User block duration is displaying incorrectly for some blocks

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/openstreetmap-website#3210]
Example, https://www.openstreetmap.org/user_blocks/3092 shows as:

    {:one=>"1 hour", :other=>"%{count} hours"}

https://www.openstreetmap.org/user_blocks/5089 shows as:

    10 hours

(although that one was a 0-hour block)

**Comment by polarbearing** [comment]
I observed the ```{:one=>"1 hour", :other=>"%{count} hours"}``` case when I had edited a block.
