### ISSUE TITLE
Stray <br/> in 'confirmation email resent'-message

### ISSUE THREAD

**Issue by pietervdvn** [openstreetmap/openstreetmap-website#3215]
I created a new account on master.dev.apis. As the email confirmation didn't come through, I clicked the 'resend confirmation email'. The message I got then got an extra <br/><br/> (see screenshot)

![image](https://user-images.githubusercontent.com/1466478/121197049-44704480-c871-11eb-9f8f-41a4b1b00efa.png)

**Comment by tomhughes** [comment]
Are you saying this only happens on that test instance?

**Comment by tomhughes** [comment]
Ah no I can reproduce it on my test instance.

**Comment by pietervdvn** [comment]
> Are you saying this only happens on that test instance?

No, I'm saying that I only tested it there - but I didn't try any other instance.

**Comment by gravitystorm** [comment]
I wasn't aware of this particular error, but I've wrestled with html in our flash messages before and it's a bit of a nightmare. 

Rails flash [only allows](https://api.rubyonrails.org/classes/ActionDispatch/Flash.html) `String`, `Array` and `Hash` as flash objects, notably not `SafeBuffer`. So if we output the raw string (via `raw` or marking it as `.html_safe`) then we get problems like https://github.com/openstreetmap/openstreetmap-website/issues/1027 . If we let rails escape the `String`, then we get problems like this issue.

I'm not sure what the best approach is, so any suggestions are welcome.

**Comment by mmd-osm** [comment]
This second paragraph was added back in 2009, and in case confirmation emails are longer relevant to a majority of users in 2021, we might as well just drop it.

**Comment by tomhughes** [comment]
That's an interesting theory - shame it has no obvious basis in reality.

Do you know something I don't about what proportion of users use a social login from a provider where we accept the email without verification?

**Comment by mmd-osm** [comment]
Well, in that case, we could rephrase the last sentence to something like "In case of issues, make sure to add support@osm to your safe senders list", which would be shorter, thereby avoiding the line break issue and hopefully is still to the point.

**Comment by mmd-osm** [comment]
As a side note, why is the flash message even mentioning support@openstreetmap.org as an email address? Maybe I'm missing something here, but the automated confirmation links are currently sent out using "web@noreply.openstreetmap.org".
