### ISSUE TITLE
1-to-1 link parity support between Google Maps and Open Street Maps

### ISSUE THREAD

**Issue by IniUe** [openstreetmap/openstreetmap-website#3218]
### Why is it important?

We see OpenStreetMap as great alternative to google maps and other popular services in most aspects. Everyone know that google map services widely in use and comes as built-in with some operating systems, apps, softwares and other business platforms.

### Problem

It's not possible to use as a *substitute, *quick replacement, *forward links to OSM or *make a switch; means everyone have to use OSM service as almost from the begining with manual procedure or individually. Furthermore, any company or project unable to use OSM as simple replacement at all (to clarify, will have to use OSM as default and only the one option).

**Is there any example use cases?**

**Communication services**
_**What's more?**_
_If has 1-to-1 link parity support then even someone send GMap link; the app able to replace it to OSM (actually, no any significant coding work; just only necessary to modify the domain automatically)_
_If has 1-to-1 link parity support then those apps able to offer an open/privacy respective map **toggle option** for interested customers/users to display,view, generate every possible location related contents including above, maps in chat groups and mobile devices/user locations share etc with OSM to end users)_

Threema
https://threema.ch/en/blog/posts/threema-android-fresh-look-and-even-more-privacy
(Currently it use OSM but if user send a GMap link then it cannot replace link to OSM)

Wire
https://github.com/wireapp/wire-webapp/issues/723 (Don't use Google for maps, use Open street map instead)
https://github.com/wireapp/wire-android/issues/734 (Switch to open source map service)

Telegram
https://github.com/telegramdesktop/tdesktop/issues/5345 (Shared location copy link should use OSM)
https://github.com/telegramdesktop/tdesktop/issues/2787 (Using OSM instead of Google Maps)

**Web Apps**

Whoogle

https://github.com/benbusby/whoogle-search/issues/284 (Replace G Maps with OpenStreetMap)
https://github.com/benbusby/whoogle-search/issues/182 (FEATURE - OpenStreetMaps)

>This has come up a few times before. OpenStreetMap doesn't provide 1-to-1 link parity between Google Maps and their service, so it unfortunately isn't a viable alternative. There would need to be development of a separate "OSM link conversion" tool for the app, which would need to be separate from Whoogle.

### Suggestion

OpenStreetMaps able to keep existing URL format by default and add additional support for parity (1-to-1) with google maps[1] and other popular map services later.

**Someone else able to start separate link conversion project, Why open street maps must do it?**

Even someone develop covert tool; so far will be limited to particular project that developed it for and it may be not possible to use for everyone, every type of projects, deployment difficulties etc.. then that's why it's better OSM support for it

Above are considerable example use cases However i have seen various projects try to use OSM as replacement, forward Gmap URLs especially since many years. after a long while, today decided to inform that to openstreetmaps then i added few projects that came to mind quickly then i'm not sure if those give enough motivation.

I don't know how OSM developers may see about this feature request and according to your own point of view however it'll be better if able to address this problem somehow.

**Comment by tomhughes** [comment]
It is explicitly not the goal of openstreetmap.org to be an end user replacement for google maps, or any other mapping site.

Our goal is to provide an interface for mappers to use to create the data that can be use to provide end user experiences.
