### ISSUE TITLE
Overpass API

### ISSUE THREAD

**Issue by KshitijaKP** [openstreetmap/openstreetmap-website#3228]
Whenever I try to use quick OSM, there is an error saying "Bad request overpass API" kindly help

**Comment by tomhughes** [comment]
What is "quick OSM" exactly? It doesn't sound like anything to do with us...

**Comment by tomhughes** [comment]
Are you referring to https://plugins.qgis.org/plugins/QuickOSM/ perhaps? That isn't written by us and uses overpass, not the main OSM API that is maintained here.

**Comment by KshitijaKP** [comment]
Yes. I was referring to the plugin.  Thank you.
