### ISSUE TITLE
SotM Banner keeps returning

### ISSUE THREAD

**Issue by amandasaurus** [openstreetmap/openstreetmap-website#3231]
When I turn off uBlock Origin, I see the SotM 2021 banner. Cool. But when I click the little ❎ (which is really hard to see BTW!), then banner goes away. Cool.

But when I refresh the page, the banner comes back! I expect that if I click the ❎ that the banner _stays hidden_. This happens if I'm logged in, or not logged in. When I am not logged in, i.e. in a private browsing mode, there is correctly a "welcome to OSM" banner as well. But when I click that ❎, that stays away, but the SotM banner comes back.

What's going on? Is the SotM banner supposed to always come back? If so, can it please _not_ come back?

Edit: [imgur link to the an animated gif showing the bug](https://imgur.com/a/cEao3DG). [Originally uploaded file](https://user-images.githubusercontent.com/1547/123104085-eb8ad980-d436-11eb-9626-26361d2ee988.gif)

**Comment by tomhughes** [comment]
No it is supposed to go away permanently.

**Comment by tomhughes** [comment]
Please, please, don't post animated image to tickets!

**Comment by bhousel** [comment]
looks like it regressed around these commits:
https://github.com/openstreetmap/openstreetmap-website/commit/e15c00dc2cfdc220be15ce1392d29b238b3d6991
https://github.com/openstreetmap/openstreetmap-website/commit/49edb79711b8fad5cc7a702c6f982644f34bbd83

There is a click handler on the close button that is supposed to add "hide" to the banner cookie id.

**Comment by amandasaurus** [comment]
> Please, please, don't post animated images to tickets! It's incredibly annoying for people that need to have the ticket open to work on it...

🤣 OK, I've uploaded it to imgur ( https://imgur.com/a/cEao3DG ) for those who want to see it.

**Comment by gravitystorm** [comment]
> Please, please, don't post animated images to tickets! It's incredibly annoying for people that need to have the ticket open to work on it...

I find the animated images really useful. But if you dislike them, we can create an issue template to request that they aren't used.

**Comment by tomhughes** [comment]
Well in principle they can be useful when it's necessary to show something in action though in this case a description was more than sufficient.

The problem is that (at least in Firefox) they autoplay and can't be stopped so you have this constant distracting motion as long as the tab is visible.

**Comment by amandasaurus** [comment]
That appears to be fixed for me now, thanks. 🙂
