### ISSUE TITLE
Changesets no longer show deleted ways with strikethrough

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/openstreetmap-website#3234]
e.g. on https://www.openstreetmap.org/changeset/106941782 way 737163179 was deleted but does not have a strikethrough.

![image](https://user-images.githubusercontent.com/1190866/123470779-b783f580-d5a9-11eb-814c-153c1721d2a6.png)

**Comment by tomhughes** [comment]
Are you saying this is a recent change?

**Comment by tomhughes** [comment]
Yes it was c8f0a81eb7043c297e050c1f3ff8a8cf7ff613bc which has removed the `browse-section` class which means none of the data browser styling is triggering...
