### ISSUE TITLE
Light base layer

### ISSUE THREAD

**Issue by cosmo-kray** [openstreetmap/openstreetmap-website#3244]
Hi everyone 👋

First of all, I'm a big fan of osm and I think this is an incredible tool, thanks for everyone who took part of it. It's quite amazing to be able to discover that tons of cartographic informations. But on a regular basis, I usually browse the map to navigate and find my way in the city and I feel it's a bit noisy and overwhelming.

It could be interesting to develop a base layer more suitable for all kind of user, more minimalist and sober, to be able to navigate and find your bearings easily. This also could provide more information about buildings, businesses, interesting points but a bit "later" on map zoomed.

On this screenshot of my city (217k inhabitants), I zoomed to include all the city center ("centre-ville" in french, placed in the middle). On the left is the default osm base layer, on the right, I've designed a mock-up of this idea of light and more spacious base layer.

![osm-renderings-test](https://user-images.githubusercontent.com/50275995/124260132-9aae6b80-db2f-11eb-9cb9-b2b12ac4b60e.jpeg)

**Buildings** • I believe buildings shape are not necessary on this scale and scramble the lisibility.
**Parks** • I choose more vivid colors to contrast with the greyish ground of the city.
**Rivesr** • Same as parks, I think it's a powerful way to locate a spot on the map
**Facilities and private places** • Yellow and reds are emphasized and help locations in my opinion.
**Neighborhoods** • I really enjoy that neighborhoods are placed on osm, maybe it could be a bit more clear
**Ground** • Grey have been lightened to contrast with everything and give a bit more shiny feeling to the map that I feel today a bit drab.
**Tiny simbols, red dotted lines and others** • I've disabled some tiny elements that I feel are not revelant for large perspectives.

Let me know what you think !

**Comment by SomeoneElseOSM** [comment]
> It could be interesting to develop a base layer more suitable for all kind of user

The advantage of OSM data over other date sources is that there's nothing stopping you doing that yourself, right now!

The website at https://www.openstreetmap.org/ currently has 6 layers available, and many more are available on other sites.  The map style that you're talking about isn't developed in this repository but instead over at https://github.com/gravitystorm/openstreetmap-cartohttps://github.com/gravitystorm/openstreetmap-carto .  There are various links there that might help you modify a version of it for your own and other people's use it in line with your desires.  Other ways to make maps are also available - lots of information in the [OSM wiki](http://wiki.osm.org).  It might also be worth looking through related questions on the [help site](http://help.osm.org).

(disclaimer - I'm not involved with either the development of this web site or the OSM Carto map style, but have done the sort of thing that you're asking about for a specific use case of OSM data).

**Comment by tomhughes** [comment]
The procedure for proposing new tile layers is documented at https://wiki.openstreetmap.org/wiki/Featured_tile_layers/Guidelines_for_new_tile_layers and that needs to be followed rather than making a request here.

**Comment by cosmo-kray** [comment]
Ok thanks for information !
