### ISSUE TITLE
How to permanently implement a new map layer in iD editor?

### ISSUE THREAD

**Issue by rene78** [openstreetmap/openstreetmap-website#3248]
I know this is not the place to ask questions but I don't know where else to get this information from. So sorry for the inappropriate location in advance.

Canton Aargau and Zurich have recently updated aerial imagery. [JOSM already implemented them](https://josm.openstreetmap.de/wiki/Maps/Switzerland#KantonAargau20cmAGIS2020). Now I would like to do the same for iD editor. It looks like as if the change has to be done in [this file](https://github.com/openstreetmap/openstreetmap-website/blob/master/vendor/assets/iD/iD/data/imagery.min.json), but I would need some guidance on how to actually do it.

**Comment by tomhughes** [comment]
The iD editor is not maintained in this repository, it is maintained at https://github.com/openstreetmap/id but it gets it's imagery information from https://github.com/osmlab/editor-layer-index.
