### ISSUE TITLE
Changeset date not visible on mobile

### ISSUE THREAD

**Issue by InsertUser** [openstreetmap/openstreetmap-website#3249]
In the current display of Changesets and element histories on opentreetmap.org an approximate age of the Changeset is shown with detailed timestamps for the Changeset displayed on hover. 

When I have tried to get this information on a mobile device there doesn't seems to be a way to get this information without downloading XML (not an easy read). 

Could this information be shown when a user taps or clicks on the approximate time period?

Attempts to view this information were made on:
Firefox 89.1.1
and
Chrome 91.0.4472.120 
Android 10

**Comment by mmd-osm** [comment]
Pretty much the same comment as in https://github.com/openstreetmap/openstreetmap-website/issues/631#issuecomment-210361610

**Comment by gravitystorm** [comment]
I'm going to merge this into #631 since it's the same underlying problem.
