### ISSUE TITLE
Missing CORS header for /trace/*/data endpoint

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#3252]
User on Slack reported, that they cannot download gpx traces from osm.org website when using the iD editor on an external site: https://ideditor.netlify.app/#background=EsriWorldImagery&disable_features=boundaries&gpx=https://www.openstreetmap.org/trace/2788683/data

Error message: 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.openstreetmap.org/trace/2788683/data. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

This seems like a valid use case to me.

**Comment by tomhughes** [comment]
When using a remotely hosted iD - using the one on osm.org will obviously work.

**Comment by mmd-osm** [comment]
Yes, exactly, I added that bit after I posted the original text.

**Comment by tomhughes** [comment]
I mean you have to go to a lot of trouble to actually do it - to find the trace and then manually manipulate the URL and copy and paste it. Hard work compared to clicking the link to launch it on osm.org...

But yes I don't see any obvious reason not to allow it.

I also noticed that we allow access to `/oauth/*` but not to `/oauth2/*` which seems like we should change that as well?

**Comment by tomhughes** [comment]
To the token endpoints at least, maybe not some of the others.

**Comment by mmd-osm** [comment]
The ideditor.netlify.app site is where the current iD development version is deployed. People can try out new features which are not yet available on osm.org. So it's not completely unexpected that mappers want to import gpx traces on an external site.

I've also noticed the /oauth/ vs. /oauth2 difference in the cors.rb initializer file. At the moment I would almost tend to wait for other devs to complain about it.
