### ISSUE TITLE
iD release endpoint auth land page not found

### ISSUE THREAD

**Issue by mbrzakovic** [openstreetmap/openstreetmap-website#3254]
I've noticed that in [iD editor](https://github.com/openstreetmap/iD) in case when user is prompted to authorize before saving their work (this happens if we hit iD release endpoint directly) authorization is not completed as landing page shows 'Page not found'.

Why am I putting issue here:
- iD auth uses [osm-auth](https://github.com/osmlab/osm-auth) and communicates with openstreetmap endpoint for token handshake. iD hasn't had any changes in auth protocol while this repo had recent changes so this felt like a good place to start investigation. :) 

When this started happening: 
- ~2-3days ago

Where this started happening: 
- https://ideditor-release.netlify.app + when running iD locally during development (localhost:8080)
(weirdly I couldn't reproduce this on https://ideditor.netlify.app/) 

Repo steps:
1. Go to https://ideditor-release.netlify.app/
2. Make some edit
3. Click Save
4. When prompted enter credentials.
5. Grant Access
![image](https://user-images.githubusercontent.com/78906108/125090740-fd73aa00-e0cf-11eb-991d-744b5bfedfde.png)
6. Page Not Found
![image](https://user-images.githubusercontent.com/78906108/125090991-4a578080-e0d0-11eb-8042-4f2111601bf7.png)

@tomhughes for visibility.

**Comment by tomhughes** [comment]
If your setup is properly configured you will never be asked to authorise when using the internal iD as it will have been pre-authorised.

If that is not working then it means you haven't configured the application ID for iD in the settings.

**Comment by mbrzakovic** [comment]
Hi @tomhughes thanks for the quick response.
Just to clarify, I am not raising an issue for osm website with included internal iD.
I am raising an issue as I am suspicious that a change in osm website auth mechanism impacted the **stand-alone iD**.
For release endpoint linked above, pre-auth is not mandatory, and the prompted auth before saving worked correctly for quite some time now.
I can provide additional context if needed.

**Comment by mmd-osm** [comment]
FYI: @mbrzakovic is currently working as interim iD maintainer, and in case this blocking his progress on a next iD release, any time spent on this is probably a good invest.

**Comment by tomhughes** [comment]
Well a bug report against the web site needs to describe what the problem is with the web site and how to reproduce it, not to point me at a third party site and expect me to work it out somehow...

Nothing has changed in the OAuth 1 flows that should be visible to iD. The only change relates to submission of the authorisation form and when OAuth is done properly (as iD does as far as I know) that doesn't impact the authorising site at all as it is between the form we generate and the backend that interprets the result.

Just to clarify, given that the example appears to be using the test site, does this affect the production site or only the dev site?

**Comment by mbrzakovic** [comment]
I agree, this isn't strictly speaking an issue on the website, but more of an investigation starting point. I appreciate help on this regardless.

I managed to reproduce this in both dev and prod.

**Comment by tomhughes** [comment]
I just tried it against the dev server and everything seems to have worked normally. I authorized the app and our server recognised that, issued a token, and redirected to the URL it had been asked to redirect to.

This was the original request that came in to us:

```
/oauth/authorize?oauth_callback=https%3A%2F%2Fideditor-release.netlify.app%2Fland.html&oauth_token=SVtPfo0bUeA3lKXJmljHL4DyshzonRKzdL9vm254
```

and we then redirected back to https://ideditor-release.netlify.app/land.html?oauth_token=SVtPfo0bUeA3lKXJmljHL4DyshzonRKzdL9vm254 as requested.

**Comment by tomhughes** [comment]
So presumably you are expecting it to redirect back to somewhere else, but where? and why is it sending the wrong callback URL to us?

**Comment by mmd-osm** [comment]
I was giving my local iD instance a try. Everything seems to work as expected on the dev instance. I had to log on, confirm all permissions, redirect worked ok. Later upload was also good: https://api06.dev.openstreetmap.org/changeset/218143

**Comment by mbrzakovic** [comment]
@tomhughes This part is working correctly on your side.
The redirect is also as expected (idea is for pop-up land window to request access token based on oauth token, persist it and close)

Thanks for this info @tomhughes, @mmd-osm, I will look into this more on my side and if needed will reach out to you.
