### ISSUE TITLE
Strange rendering of suburb name over town name in CycleMap layer at low zoom levels

### ISSUE THREAD

**Issue by ewmjc** [openstreetmap/openstreetmap-website#3255]
The screen shot below shows a place=suburb "Garnett Wharfe" apparently rendering as a town and, the reason for reporting, replacing the town "Otley" of which it is a part. Neither node have been editted in several years.

At this view coordinates, the rendering of "Garnett Wharfe" behaves erratically at different zoom levels only in the CycleMap layer:

https://www.openstreetmap.org/node/4954984826#map=13/53.9102/-1.6894&layers=C   Bad - Cycle Map
https://www.openstreetmap.org/node/4954984826#map=13/53.9102/-1.6894 Good - standard layer

Here are the nodes:
https://www.openstreetmap.org/node/4954984826  "Garnett Wharfe"
https://www.openstreetmap.org/node/20940471 "Otley"
https://www.openstreetmap.org/node/2354936300 "Newall" (another suburb which is well behaved)
https://www.openstreetmap.org/node/27402102 "Weston Estate"  (another suburb which is well behaved)

The only other explanation I can think of is that someone added then deleted entirely different node and we are seeing the residual effects of that in cache.

Thanks, Mike Collinson

![GarnettWharfe_Suburb_Rendering_As_Town](https://user-images.githubusercontent.com/3492648/125350708-6d4b9400-e35f-11eb-8c51-9040184e635d.png)

**Comment by tomhughes** [comment]
As I'm sure you're aware this repository has nothing to do with the rendering style, something which goes double for the cycle map layer which is a third party layer that isn't provided by OpenStreetMap.

**Comment by tomhughes** [comment]
If this had been an issue in the standard layer run by OSM then https://github.com/gravitystorm/openstreetmap-carto/issues would be the correct place to report it - for the third party thunderforest provided layers like cycle map you want to look at https://www.thunderforest.com/contact/ for contact information
