### ISSUE TITLE
Communities page

### ISSUE THREAD

**Issue by atomoil** [openstreetmap/openstreetmap-website#3256]
Hi,

I’m a member of the Local Chapters and Communities Working Group and this issue is to say hi and open a discussion over some work we’d like to undertake on the site (to be clear we intend to do the hands on dev work for this).

We’d like to add a “Communities” top level navigation link, which points to a new Communities page on the site. 

![Combined](https://user-images.githubusercontent.com/184608/125505558-629f88bb-dde9-411a-82ef-d11718273986.jpg)

The Communities page will list local chapters and provide links to the wiki for other groups. The local chapters list would ideally be data driven, and osm-community-index could be useful in this regard.

![Screenshot 2021-06-28 at 16 59 10](https://user-images.githubusercontent.com/184608/125504582-57c1731c-447c-41e3-a491-edf47368e145.jpg)

Looking to the future, when Microcosms is ready to be released there would be an additional block containing relevant microcosms with a link to find more (see mocked up images). This has been discussed with Brian who is leading Microcosms development.

![Screenshot 2021-06-28 at 17 08 45](https://user-images.githubusercontent.com/184608/125504586-7b14f163-b8df-4f27-8f0e-6c471aff2aa4.jpg)

We’re trying to keep the scope of this work small and targeted, so are not proposing to remove or replace other links or otherwise restructure the existing navigation (as that should probably include a review of existing usage and a wider consultation on changes which we don’t have the resource to do at this time).

This is my first PR on the site, so I’d particularly like to know any systems or patterns or technical things we should bear in mind to help long term maintenance and the eventual PR gain approval (eg is there a particular way you’d prefer we interface with osm-community-index or a better way of achieving this goal).

This piece of work has been discussed on the Local Chapters and Communities Working Group GitLab (https://gitlab.com/osmfoundation/lccwg/-/issues/14) so you can find more thinking and discussion there.

Thanks in advance for any thoughts or guidance you (or anyone reading this issue) can share.

Adam

**Comment by tomhughes** [comment]
You might want to start by reviewing previous discussion about adding new top level links there - given how limited that space is you're going to need to make a very good case.

Examples of how it works in English aren't very useful - try it with something like German where the translations are much longer ;-)

How would a data driven solution work? I understand you have a geocoded index, but what would you use as the key? The current map position? For a map that's not longer displayed once you switch to the community tab? The user's home location?

**Comment by atomoil** [comment]
Hi @tomhughes,

Thanks for the speedy reply!

> You might want to start by reviewing previous discussion about adding new top level links there - given how limited that space is you're going to need to make a very good case.

We're aware of Andy's recommendations here - https://github.com/openstreetmap/openstreetmap-website/issues/3041#issuecomment-780445950 - are there any other specific conversations we should be aware of?

> Examples of how it works in English aren't very useful - try it with something like German where the translations are much longer ;-)

Haha yeah good point - we'll take a look 🚀 

> How would a data driven solution work? I understand you have a geocoded index, but what would you use as the key? The current map position? For a map that's not longer displayed once you switch to the community tab? The user's home location?

The key reason for a data driven solution is to support the ideal of a single source of truth and therefore reduce ongoing maintenance effort.

There are currently 17 Local Chapters, so there isn't a need to have a particularly fancy or clever listing of them - showing an alphabetical list would be sufficient (certainly for an initial release). Saying that tho - are there other areas on the site where data is displayed differently depending on location and does that then set a precedent for expected behaviour for a communities page?

Are there other examples of external data such as osm-community-index being loaded into the site (so that we can follow a similar pattern)? This data does not change very often, so there would be no need to refresh it more often than every 24 hours.

**Comment by tomhughes** [comment]
Sorry I thought you were proposing using `osm-community-index` to find communities local to the user and was wondering how you proposed to decide where the user was?

**Comment by atomoil** [comment]
> Sorry I thought you were proposing using `osm-community-index` to find communities local to the user and was wondering how you proposed to decide where the user was?

Oh gosh no, certainly not for an initial release. That's potentially a great idea for some future version tho', but definitely not for now.

**Comment by gravitystorm** [comment]
> Are there other examples of external data such as osm-community-index being loaded into the site (so that we can follow a similar pattern)?

Not, not at the moment. But we have everything set up to use node modules (via packages.json and yarn) so we're good to go on that front. For loading the data I see two main approaches - either load it using an initializer, or create a model and load it via a memoization approach. See https://stackoverflow.com/questions/20913353/what-is-the-rails-way-to-quickly-access-static-data-at-runtime for some discussion. I lean slightly towards the model, since I suspect you'll want to write some code around that for returning records in a particular order.

Of course, if we start looking at ordering by user location (or map location) that might change the way we do things, perhaps by loading the data into the db in order to use postgres queries. We do something similar in the Language model, which essentially loads some static data into the db for further use. But in turn that opens up more discussions, like whether we should be using PostGIS for non-Node location-based queries, and that might be left for another time!

**Comment by tomhughes** [comment]
> > Sorry I thought you were proposing using `osm-community-index` to find communities local to the user and was wondering how you proposed to decide where the user was?
> 
> Oh gosh no, certainly not for an initial release. That's potentially a great idea for some future version tho', but definitely not for now.

So you're just going to lookup "global" communities for now then?

**Comment by joostschouppe** [comment]
> So you're just going to lookup "global" communities for now then?

No, the idea is to just show all official Local Chapters first. To find local communities where those don't exist, the text refers to the Communities wiki page, where the wider community can and does further refer to the osm-community-index and some other tools.

**Comment by atomoil** [comment]
> > Are there other examples of external data such as osm-community-index being loaded into the site (so that we can follow a similar pattern)?
> 
> Not, not at the moment. But we have everything set up to use node modules (via packages.json and yarn) so we're good to go on that front. For loading the data I see two main approaches - either load it using an initializer, or create a model and load it via a memoization approach. See https://stackoverflow.com/questions/20913353/what-is-the-rails-way-to-quickly-access-static-data-at-runtime for some discussion. I lean slightly towards the model, since I suspect you'll want to write some code around that for returning records in a particular order.

Thanks @gravitystorm that's excellent and exactly what I was looking for. I'd definitely prefer the model approach as it encapsulates the functionality in a clear and open way.

I'm glad to hear node modules are supported - are there any good examples in the codebase that we can look at for best practise / to ensure consistency?

> Of course, if we start looking at ordering by user location (or map location) that might change the way we do things, perhaps by loading the data into the db in order to use postgres queries. We do something similar in the Language model, which essentially loads some static data into the db for further use. But in turn that opens up more discussions, like whether we should be using PostGIS for non-Node location-based queries, and that might be left for another time!

That's definitely an interesting idea, but I'd prefer to engineer for what we know we're planning as we can always refactor/adapt the approach if the requirements change to need user or map location.

**Comment by gravitystorm** [comment]
> I'm glad to hear node modules are supported - are there any good examples in the codebase that we can look at for best practise / to ensure consistency?

No, not at the moment.

**Comment by tomhughes** [comment]
Well `js-cookie` among other things would be an example, but basically `node_modules` is on the load path, so you can tell sprockets to pull in any file relative to that with a normal asset directive.

**Comment by atomoil** [comment]
Hey, it's been a little while, so I thought I'd send over an update. I have a version of the code up and running but there are a few things I am not totally happy with and am seeking advice on before I'm ready to create a PR. Are you open to receiving draft PRs or would you prefer my work to be "complete" before I raise one?

On that note, currently I have no tests 😱 - I presume you'd expect tests, so please can you give me any pointers on what kind of things you'd like me to test? (apologies in advance if I failed to rtfm adequately)

I just realised I made but didn't post the image of the site in german, so here that is. Do you have any questions or concerns over this? I am up for trying it in other languages, if you can suggest which languages to try.

![example of site with communities header in german](https://user-images.githubusercontent.com/184608/129492283-64bd8f65-e81b-47b3-a527-ef2da2c4e28e.jpg)

**Comment by fredao** [comment]
On the subject of the German translation, perhaps an excerpt from weeklyOSM's glossary would be helpful ;-)

![grafik](https://user-images.githubusercontent.com/1868849/129625920-39908be2-ac2a-440b-8b07-85598fe39f19.png)

**Comment by gravitystorm** [comment]
> Are you open to receiving draft PRs or would you prefer my work to be "complete" before I raise one?

Absolutely - it's the easiest way to review work in progress, so I'm happy to see a draft PR.

> I presume you'd expect tests, so please can you give me any pointers on what kind of things you'd like me to test?

That's easier to answer when we see the proposed code changes, but in general any new model will need tests, and then either controller tests (since we use these extensively already) and/or system tests. Each of these types of test can be found in the corresponding directory under `test`, and you can have a look at similar models/controllers to see what's been done before.

**Comment by SomeoneElseOSM** [comment]
Re the naming:

> We’d like to add a “Communities” top level navigation link, which points to a new Communities page on the site.

We already have  https://openstreetmap.community/ (run externally to OSMF, but very useful),  https://community.openstreetmap.org/  (from OSMF, and in use) and I've heard "communities" suggested as one potential name for https://github.com/openbrian/osm-microcosms .

How will this new "communities" page avoid confusing users who may think they're getting one of the 2 established OSM "community" sites?

**Comment by gravitystorm** [comment]
Fixed by #3301
