### ISSUE TITLE
links to wikipedia section having diacritics do not work

### ISSUE THREAD

**Issue by fgnievinski** [openstreetmap/openstreetmap-website#3269]
I've tried to add a link to
https://pt.wikipedia.org/wiki/Tristeza_(Porto_Alegre)#Pórtico

when the non-ASCII character "ó" is escaped, the URL correctly becomes:
https://pt.wikipedia.org/wiki/Tristeza_(Porto_Alegre)#P%C3%B3rtico

but OSM is replacing the percent signs for dots:
https://pt.wikipedia.org/wiki/Tristeza_(Porto_Alegre)#P.C3.B3rtico

which mediawiki won't recognize when you click on a feature.

related issue: #967

**Comment by mmd-osm** [comment]
Cannot reproduce here: https://master.apis.dev.openstreetmap.org/note/27515

What exactly do you mean by "OSM is replacing the percent signs for dots". In which application did you see this. How can it be recreated?

**Comment by tomhughes** [comment]
I assumed this was about the autolinking of wikpedia tags on objects?

**Comment by mmd-osm** [comment]
Right, it’s in the following object: https://www.openstreetmap.org/way/426134360

**Comment by fgnievinski** [comment]
Right, the original case was:
https://www.openstreetmap.org/way/426134360

An additional case is:
https://www.openstreetmap.org/way/486400381

Thank you.

**Comment by dieterdreist** [comment]
both wp links work for me on mobile safari

**Comment by fgnievinski** [comment]
Re: "both wp links work for me on mobile safari" (from: dieterdreist)

The Wikipedia article opens fine, but the HTML anchors do not.

I.e., the webpage is not displayed at the intended part, e.g.:

https://pt.wikipedia.org/wiki/Tristeza_(Porto_Alegre)#Pórtico

![image](https://user-images.githubusercontent.com/5018500/127210173-13bc14db-34e4-4a76-a47c-1469a6ee3cab.png)

**Comment by mmd-osm** [comment]
> Re: "both wp links work for me on mobile safari" (from: dieterdreist)

Cannot confirm, with Wikipedia native app installed, all you get is an errror message that the page cannot be loaded.

**Comment by gravitystorm** [comment]
This is a conflict between the way we generate links to wikipedia sections, and manually specific anchors within the page itself.

We convert the anchors to the "dot" version, and have done for many years. You can see from the html sources that wikipedia automatically inserts anchors with the "dot" version of the section header:

![Screenshot from 2021-07-28 15-19-39](https://user-images.githubusercontent.com/360803/127339240-18bf8257-d634-4c81-b182-e34cf06d95c7.png)

This works fine for section headers. However, the anchor in question is a manually specified anchor:

![Screenshot from 2021-07-28 15-24-04](https://user-images.githubusercontent.com/360803/127339568-a680e423-f378-4327-b066-24a889ebff67.png)

From the [English version of the "Template:Anchor"](https://en.wikipedia.org/wiki/Template:Anchor) page: "You can define one or more anchor names, separated by |." We can see that when we look at these anchors in the html source:

![Screenshot from 2021-07-28 15-19-53](https://user-images.githubusercontent.com/360803/127339851-6c5b7a26-697e-4fee-8e2d-60a3fe43648a.png)

So for manually specified anchors, wikipedia doesn't automatically add a "dot" version, unlike the section headers. And our logic - of automatically converting all fragments to the "dot" version, therefore breaks down.

**Comment by gravitystorm** [comment]
If I had to guess, I would say that the "dot" fragments are an old way of doing things, and at some point wikipedia (i.e. the mediawiki software) updated to use full-unicode fragments while keeping the "dot" versions for compatibility with existing links. Perhaps there's less cross-browser problems now than back when they came up with the "dot" encoding. 

If anyone has anything to back that up, like issues from the mediawiki tracker or links to the source code that would be very useful.

If so, it might be the case that we can just drop the "dot" encoding from the fragments and rely on the non-dot versions that appear to also be available.

**Comment by gravitystorm** [comment]
Turns out I'm good at guessing: 

 * https://phabricator.wikimedia.org/T152540 
 * https://phabricator.wikimedia.org/T176828 (clearer summary)

So we should remove the dot-encoding from our code, since it a) isn't required any more and b) breaks on some manually-specified anchors

**Comment by fgnievinski** [comment]
thank you all
