### ISSUE TITLE
user enable error

### ISSUE THREAD

**Issue by alenigrelli** [openstreetmap/openstreetmap-website#3272]
Hello good evening! I am getting the following error when I want to change the state of a user to active. What could be the problem?
![Captura de pantalla de 2021-07-26 20-39-56](https://user-images.githubusercontent.com/15861031/127072765-e42b09b4-73da-4e9b-9586-d5600097358e.png)

**Comment by tomhughes** [comment]
It looks like you don't have your database connection configured correctly - it is trying to connect to host `db` but apparently there is no such host in your environment.
