### ISSUE TITLE
Error 403 when logging in with my editor

### ISSUE THREAD

**Issue by alenigrelli** [openstreetmap/openstreetmap-website#3280]
When I log in with my osminedit editor after granting me access, it gives me the following error in the console. Can you give me an indication of where the problem comes from?
![Captura de pantalla de 2021-07-28 15-44-22](https://user-images.githubusercontent.com/15861031/127391062-a24478bd-7edb-4133-bfea-0be0686034f4.png)
![Captura de pantalla de 2021-07-28 15-43-14](https://user-images.githubusercontent.com/15861031/127391069-1dc1a2f0-3c87-4b0f-96ea-93a4404bd441.png)

**Comment by tomhughes** [comment]
Well you haven't given your client application the correct permissions - you should ask the developers of that application what permissions it needs and make sure you include those permissions when creating the OAuth application.

Specifically you are missing the `read_prefs` permission here, but it's best to check with the authors of the app (or its documentation) to find out everything that is needed or you may just run into other issues.
