### ISSUE TITLE
Unable to fetch all the Boroughs

### ISSUE THREAD

**Issue by pyJain108** [openstreetmap/openstreetmap-website#3283]
Hello, 

I am unable to fetch all the boroughs of Berlin, Germany. There are a total of 12 Boroughs, and using the Tag as `tags = {'place':'borough'}`, I am just able to fetch 10 out of the 12 Boroughs. I checked on the OSM, but I can see both the missing Boroughs are correctly classified as `place-boroughs`. 

2 Missing Boroughs -> **Friedrichshain-Kreuzberg** and **Pankow** 

![image](https://user-images.githubusercontent.com/75158219/127840640-e6597cd9-589a-4ce8-9c4a-c6668bbab17e.png)

**Comment by mmd-osm** [comment]
Please use https://help.openstreetmap.org for general questions, which are unrelated to the osm.org website.

**Comment by dieterdreist** [comment]
this is not a suitable forum to discuss tagging, but generally there are no “boroughs” in Berlin, looking at your example it seems you are looking for “Bezirk”, which is an administrative classification and can be found looking for boundary=administrative and admin_level=9.

There is no point in duplicating this with a borough place tag. There is already “name:prefix=Bezirk” which is specific.
Also have a look here: https://wiki.openstreetmap.org/wiki/Talk:Tag:place%3Dborough

sent from a phone

**Comment by mmd-osm** [comment]
Follow up https://help.openstreetmap.org/questions/81166/unable-to-fetch-all-the-boroughs

please continue the discussion there
