### ISSUE TITLE
Remove `xid_to_int4` from compiled shared library database functions (or `libpgosm.so` altogether)

### ISSUE THREAD

**Issue by hummeltech** [openstreetmap/openstreetmap-website#3288]
We should get rid of `xid_to_int4` now anyway, and I'm not sure the other one actually gets much use in our production deployment now that the API largely goes through cgimap.

_Originally posted by @tomhughes in https://github.com/openstreetmap/openstreetmap-website/issues/3286#issuecomment-893873363_

**Comment by tomhughes** [comment]
I was just about to push change to do this so it didn't really need an issue ;-)

**Comment by hummeltech** [comment]
Oops, sorry. Haha alright!
