### ISSUE TITLE
Wrong link when home location is not set

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/openstreetmap-website#3290]
The link that is shown when home location is not set links to the "Settings page". It should be linking to https://www.openstreetmap.org/profile/edit
![image](https://user-images.githubusercontent.com/19364673/128732535-968179dd-0502-476c-bd39-a25f335ffbdd.png)

**Comment by MarshMello0** [comment]
I think this is the line but I don't know how to fix it.

https://github.com/openstreetmap/openstreetmap-website/blob/f1935b1c5786de8f27bee9b6b2da2f28f650468f/app/views/users/show.html.erb#L194
