### ISSUE TITLE
"Application error" when viewing note

### ISSUE THREAD

**Issue by scaidermern** [openstreetmap/openstreetmap-website#3295]
Opening https://www.openstreetmap.org/note/428387 leads to:

> **Application error**
> 
> The OpenStreetMap server encountered an unexpected condition that prevented it from fulfilling the request (HTTP 500)

**Comment by Dujebai** [comment]
after closing the note (again) on OsmAnd, it reappears
same issue is on note https://www.openstreetmap.org/note/428380 (which I left untouched ;-) )

**Comment by tomhughes** [comment]
Duplicate of  #2146.
