### ISSUE TITLE
context menu kaput in chrome

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3309]
Broken in chrome desktop. OK in Firefox.

1. Browse osm.org
2. Right click
3. All menu items don't work.

![20210903T011541](https://user-images.githubusercontent.com/1230959/131888242-a0c10689-cc60-41e2-8733-c31d1bcc67d4.jpg)

Google Chrome	95.0.4621.4 (Official Build) dev (64-bit)
OS	Linux

**Comment by tomhughes** [comment]
Works fine for me in Chrome 91 so presumably recent breakage but I don't have anything more recent available right now.

**Comment by tomhughes** [comment]
There is a 92 build for Fedora but it seems to be crashtastic so I can't test it. As 93 was only released a couple of days ago it hasn't been built yet and 95 is dev channel so that's some way off.

It may well just be a bug in Chrome given it's not even a beta version...

**Comment by pnorman** [comment]
92 on Windows works

**Comment by mmd-osm** [comment]
Tested the exact same version 95.0.4621.4 on Ubuntu. Issue could not be reproduced here.
I'd suggest to close this issue as invalid unless additional details are provided.

**Comment by jidanni** [comment]
Sounds like I am the victim of a "Variation", but as you see on chrome://version, I have eliminated most of them.
```
Google Chrome	95.0.4621.4 (Official Build) dev (64-bit)
Revision	f3ec7202e53150731e6fd47a818e877e3f2e74b7-refs/branch-heads/4621@{#7}
OS	Linux
JavaScript	V8 9.5.50
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4621.4 Safari/537.36
Command Line	/usr/bin/google-chrome-unstable --no-first-run --no-default-browser-check --disable-extensions --no-experiments --user-data-dir=/tmp/tmp.EXD0Kcb5Fn_10516_UDD --enable-crashpad osm.org
Executable Path	/opt/google/chrome-unstable/google-chrome-unstable
Profile Path	/tmp/tmp.EXD0Kcb5Fn_10516_UDD/Default
Variations	c4c83305-6ce6e1ee
```

**Comment by mmd-osm** [comment]
I'm running the same commit here: f3ec7202e53150731e6fd47a818e877e3f2e74b7-refs/branch-heads/4621@{#7}
Even with -disable-extensions --no-experiments command line paramters, variations lists about 142 entries,  which I don't want to post here (too much detail).

I general, selected entries in the popup window are quite difficult to see due to the light grey background. That however hasn't really changed across recent Chrome versions.

**Comment by jidanni** [comment]
Hmm, working fine on my other computer...
So closing for now.

**Comment by jidanni** [comment]
I am trying to figure out why this happens only on one of my computers, via noticing a difference 
in also how imagemagick behaves. https://github.com/ImageMagick/ImageMagick/discussions/4153

**Comment by jidanni** [comment]
Yes, sounded like https://answers.themler.io/questions/58271/when-click-to-drop-down-menu-it-disappear-or-unable-to-click
