### ISSUE TITLE
Anchors already defined

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3314]
https://github.com/htacg/tidy-html5 spotted these problems:
```
OpenStreetMap.html:205:13: Warning: <input> anchor "query" already defined
OpenStreetMap.html:226:9: Warning: <input> anchor "route_from" already defined
OpenStreetMap.html:234:9: Warning: <input> anchor "route_to" already defined
```
etc.

OpenStreetMap.html is the saved (CTRL+S in most browsers) web page on disk.

**Comment by tomhughes** [comment]
Yes it's deliberate - the form has two versions, one for the normal site and one for the mobile site, but only one version is ever shown at a time.
