### ISSUE TITLE
Error contacting https://overpass-api.de/api/interpreter: Too Many Requests

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3319]
Can't query nearby features anymore.
```
Query Features
Click on the map to find nearby features.

Nearby features
Error contacting https://overpass-api.de/api/interpreter: Too Many Requests
Enclosing features
Village Boundary Nanshi Village
...
```
Happens on about 2 out of 3 queries.

**Comment by tomhughes** [comment]
Yes overpass (which isn't run by us) is busy. There's not a lot we can do about that.

Now you know why I dislike relying on third party services...

**Comment by jidanni** [comment]
It even has differing messages:
`Error contacting https://overpass-api.de/api/interpreter: Gateway Timeout`

**Comment by jidanni** [comment]
http://overpass-api.de/ says you can install your own copy.
