### ISSUE TITLE
Download link on a deleted object results in an HTTP error

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3325]
On deleted nodes, `https://www.openstreetmap.org/node/9999999999999...`
please grey out the Download XML link,
as clicking it will give an HTTP error.

**Comment by tomhughes** [comment]
Instead of reporting a suggested solution it's better just to report the error - greying out the link is ony one possible way that the problem might be fixed.

**Comment by jidanni** [comment]
I would have thought that 4xx is a good code for things that don't exist anymore.
E.g.,
```<a href="osm.org/node/12345">Nerdsburg Cheese Museum</a>```
and after it got demolished, linkcheckers could tell the stale link.

But then thinking more, it would be better to have some page still show a proper explanation.

So I agree with you.

P.S., you are blocking my notifications. So I don't know you replied above.
