### ISSUE TITLE
Ideas for dashboard page

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3326]
In #3167 I discussed splitting the original profile page in two - to keep the pubic-facing user profile information separate from stuff that other people don't see when viewing your profile (like your friends list). This was implemented in #3297 and we now have a dashboard that is private to each mapper and currently contains the stuff that was moved from the profile page.

I have my own plans for things to add to the dashboard in the future, but I'd also like to hear suggestions from other people. In particular, I'd like to hear suggestions that are:

* Focussed on mappers, or things that would encourage people to become mappers, or that would help or inspire existing mappers do more things. 
* Preferably don't involve integrating any third-party services at this stage.
* Aren't just duplicating menu information. For example, having a box saying "you have 5 unread messages" duplicates the "My messages" menu item so doesn't need to go on the dashboard.

**Comment by gravitystorm** [comment]
Here's an example of something I could see being useful to mappers:

* Show the 10 most recent Notes within 5km of the home location

**Comment by gravitystorm** [comment]
@yellow-wood thanks for the suggestions! If you have any more, please let me know.

**Comment by gravitystorm** [comment]
Since this issue has been open for a few months now, I'm going to close it so that it doesn't just sit on our open issue list forever. But please feel free to either add new ideas here, or in new issues, if you have any!

**Comment by yellow-wood** [comment]
The dashboard page could contain "The private notebook". It works like "Profile" (plain text), but other people don't see it. The users could use it for: the hyperlinks to OSM Wiki or to Map, the descriptions of the OSM tags , the private "to do list" and so.
