### ISSUE TITLE
Directions wrong translation in Greek

### ISSUE THREAD

**Issue by skarmoutsosv** [openstreetmap/openstreetmap-website#3328]
There is a duplicate entry when selecting route provider. More specific the text "Με τα πόδια (GraphHopper)" appears twice in the list.

**Comment by gravitystorm** [comment]
Thanks for reporting. Our translations are managed by Translatewiki, so it needs to be fixed there:

https://translatewiki.net/wiki/Translating:OpenStreetMap

I can see that there is a duplicate translation for car and foot, so it looks like one of the existing translators made a mistake. 

![Screenshot from 2021-09-17 10-22-27](https://user-images.githubusercontent.com/360803/133759939-6e209d82-339f-4983-be2a-2c07b855a7d6.png)
