### ISSUE TITLE
"Edit with Remote Control (JOSM, Potlatch, Merkaartor)" should say "you forgot to plug in the..."

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3329]
"Edit with Remote Control (JOSM, Potlatch, Merkaartor)" should say "you forgot to plug in the..." instead of doing nothing in such cases.
![20210925T212401](https://user-images.githubusercontent.com/1230959/134773168-91cd9a5f-3cfe-4fe8-a40c-7a761e45b950.jpg)

**Comment by tomhughes** [comment]
It doesn't do nothing, it gives an error after a timeout - that's the best we can do as there is no way to detect if there is anything suitable available. All we can do is try and connect and give an error if we get no response after a number of seconds.

**Comment by mmd-osm** [comment]
In addition, some JOSM users might have to confirm a popup first before the browser receives a response. Let’s close this issue, it isn’t going anywhere.

**Comment by jidanni** [comment]
Well, it should "say waiting for connection" before it gives an error. Otherwise it appears to do nothing. Or maybe the timeout is 1 hour, and I didn't wait that long to find out. Who knows?

**Comment by tomhughes** [comment]
No the timeout is 1s: https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/javascripts/index.js#L270

It's not the most robust thing though because if the browser gets any sort of success response to the HTTP request it makes then it will assume the edit has started.

**Comment by mmd-osm** [comment]
And even if you're getting an error message on osm.org, it doesn't mean that the whole thing failed. JOSM may be simply waiting for you to accept the remote connection request, ad then happily continue downloading some data.

Option to change this on osm,org are fairly limited after all.

**Comment by jidanni** [comment]
P.S., @tomhughes, @mmd-osm could at least one of you stop blocking my notifications? Else I can't tell if you replied. Thanks.
