### ISSUE TITLE
Trace animation should have start/stop buttons

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3337]
The current trace animation loops immediately.

It should take a little rest between each loop.

Imagine that we have jogged around a school's exercise track, making exactly one lap.

OK, but looking at the animation, one cannot tell if we started and ended in the southeast corner, or southwest corner, etc.

Yes, it should still pause, even if #3322 is implemented.

**Comment by jidanni** [comment]
"The natives I traveled with said the first river I hit was river A,
and the second was river B, but now I can't tell which was first and
which was second, just looking at the trace, so must defer naming."

"The historic marker was at where we started and ended walking the loop
trail, but now all I see is the trace of the loop and can't tell where
we started and ended."

If there was a pause, both mysteries could be solved without further ado.

**Comment by jidanni** [comment]
Yes, but one needs to reload the page several times to be sure...
And still can't be sure, because of network / caching / browser / CPU conditions.

**Comment by lectrician1** [comment]
Why not just have a pause/play button for the animation?

**Comment by HolgerJeromin** [comment]
> Why not just have a pause/play button for the animation?

Because this is a pre-rendered gif with animation. They are not stoppable via buttons.
I also do not see how this will help jidannis issue finding start/end...

**Comment by lectrician1** [comment]
> Because this is a pre-rendered gif with animation. They are not stoppable via buttons.

Well then ditch that system and instead convert the gps trace into a svg and controllably animate it that way.

> I also do not see how this will help jidannis issue finding start/end...

#3322 will help finding start/end. I'm just proposing that the animation should be changed in a different way.
I should have probably made a new issue. 
@jidanni if you agree, close this issue and make a new one proposing for animation start/stop buttons.

**Comment by HolgerJeromin** [comment]
> Well then ditch that system and instead convert the gps trace into a svg and controllably animate it that way.

Feel free to make a PR. No one is paid to change the websites code.

**Comment by jidanni** [comment]
I got an idea: I just step back and let the pros take care of this.

**Comment by HolgerJeromin** [comment]
Having a start stop button is
* implementation effort
* does not help with the written problem:
> one cannot tell if we started and ended in the southeast corner, or southwest corner, etc.

So this issues is now nonsense

**Comment by jidanni** [comment]
OK maybe merge it with #3322 .
Anyway it seems my issue is becoming a mess.
So I'll close it.
Perhaps somebody could make a refocused replacement issue if they see the need.
