### ISSUE TITLE
Possibility for speed improvement ?

### ISSUE THREAD

**Issue by mtk11** [openstreetmap/openstreetmap-website#3342]
I am looking at one project for potential further development [Sensor.Community Map](https://github.com/opendata-stuttgart/feinstaub-map-v2) which seems to be based on [OpenStreetMap](https://github.com/openstreetmap). However the map, update, rendering seems to be quite slow and clumsy. Possibility for improvement or to look at other projects ?

**Comment by mtk11** [comment]
@tomhughes  Probably you should look more closely what was inquired including the usernames … one more issue. Searching. Let say search for: london downtown, it provides many results … shouldn’t be a map of the area ? Also in Bulgarian/Cyrillic is actually horrible. When write the city name and after a name of a street … it gives first streets in other cities.

**Comment by tomhughes** [comment]
What "usernames" are you referring to?

Search is not handled by the website - that just calls out to nominatim.openstreetmap.org which has an issue tracker at https://github.com/osm-search/Nominatim/issues.

**Comment by mtk11** [comment]
@tordans, to some extent one of the questions is, if there is no native way to make such maps with configurable objects ? Also the representation of information including the search form is not so good. The search form takes quite a lot from the screen space, does not look so good .... Possibility for smaller pop-up windows ?
