### ISSUE TITLE
Send a message and a scroll bar appears at the bottom of the screen

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/openstreetmap-website#3351]
I've noticed with other things that cause the green bar to appear (e.g. report a user) as well.

![screenshot_102421_122556](https://user-images.githubusercontent.com/5311740/138592088-13cbca33-673d-4e35-be5e-d47dbfd17bff.PNG)

The display settings for this desktop are 1920x1080 - the browser window's taken up 75% or so of that.  I've noticed in Firefox 93 and Chrome 95.

**Comment by gravitystorm** [comment]
Nice catch! I don't know how I failed to spot this at any point in the last 5 months :smile:
