### ISSUE TITLE
Is this wiki page still up to date? Is it welcome/helpful?

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#3366]
Is

>  Despite its prominence in some communities and relatively large user-base, the OpenStreetMap Rails Port has seen very little development and has a small developer base relative to similar open-source projects. This means that some designs that were thought to be temporary have lasted through the years and been accepted as 'the design', and much of the effort that is spent on the project is fixing bugs rather than making core improvements or adding features. This page attempts to be an overview of high-level issues from a technical and practical perspective, and potential actions. 

from https://wiki.openstreetmap.org/wiki/Improving_OpenStreetMap still true?

I see that years ago it was used by some still active contributors.

It was written by Tmcw quite long time ago and I am unsure should it be 

- moved to a different title
- moved to a different title and marked as archived page with no relevance to a current situation
- start redirecting to generic https://wiki.openstreetmap.org/wiki/How_to_contribute (content would be kept in history, inaccessible to a typical user)
- kept as it
- in addition, some content may be resued in https://wiki.openstreetmap.org/wiki/Web_front_end or https://github.com/openstreetmap/openstreetmap-website/blob/master/CONTRIBUTING.md

Is there an existing equivalent considered as canonical by maintainers of  openstreetmap / openstreetmap-website ?

There is also https://wiki.openstreetmap.org/wiki/Develop/Improvements

---------------------------------------------------------

I am asking as I am a quite active OSM Wiki contributor and someone raised issue of this pages.

My initial plan was to archive/redirect them as they appear to be outdated, unused and not maintained but I prefer to avoid losing something used/resusable, so I prefer to ask before edits.

**Comment by gravitystorm** [comment]
My view would be to get rid of those pages (along with https://wiki.openstreetmap.org/wiki/Front_Page_Design which was linked from the Improving OpenStreetMap page). 

There's plenty of stuff on the pages that is still true, to varying extents, but plenty which is unsurprising out of date. Nearly a decade has passed since anyone really worked on those pages. And I don't think anyone gains anything from having more out-of-date information on the wiki since it pollutes search results, and makes the who wiki seem unreliable.

The history will still be there if someone wants to do some social archaeology, but otherwise my recommendation (as with most things on the wiki) is to be bold at removing this kind of was-useful-at-the-time-but-not-nowadays text.

**Comment by tomhughes** [comment]
Well it looks like the first one has already been redirected!

**Comment by tomhughes** [comment]
Ah that was @matkoniecz a few minutes ago. I concur with @gravitystorm anyway.

**Comment by matkoniecz** [comment]
BTW, maybe https://github.com/openstreetmap/openstreetmap-website/blob/master/CONTRIBUTING.md can/should be more inviting? Maybe start from something like "You are welcome to contribute(...)"

One thing that seemed nice on this outdated pages that there were more kind of personal/living.

-------------------------------------------------------

I redirected https://wiki.openstreetmap.org/w/index.php?title=Improving_OpenStreetMap&oldid=742487 and https://wiki.openstreetmap.org/w/index.php?title=Develop/Improvements&oldid=1780468 (links to old version so one can see what was there), changed target of https://wiki.openstreetmap.org/w/index.php?title=Front_Page&redirect=no nominated https://wiki.openstreetmap.org/wiki/My_Account/Improvements for deletion etc.

https://wiki.openstreetmap.org/wiki/Front_Page_Design also needs to be detangled but this will take more effort

**Comment by matkoniecz** [comment]
I redirected also https://wiki.openstreetmap.org/w/index.php?title=Site_Design_and_Workflow&oldid=819873 (also looks dead and outdated)
