### ISSUE TITLE
Remove html5shiv?

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3367]
I think we could remove the `html5shiv` javascript library. My motivation is because it keeps randomly failing the CI builds because of some issue that I haven't tried to debug. Although removing it might just uncover the same issue with a different file, so it's not guaranteed to be the solution.

I'd also like to remove it because I don't think it's necessary any more. [It was added in 2013](https://github.com/openstreetmap/openstreetmap-website/commit/b92cb5b7729287d0256bbe915bfb99ef27d7b940) to support [IE8](https://en.wikipedia.org/wiki/Internet_Explorer_8), which was originally released in 2009 and superseded by IE9 in 2011. Widespread IE8 support was ended in January 2016 and completely ended in 2019 for POS systems (tills, self-service checkouts etc). So ignoring those, it's been almost 6 years since it was supported and over 11 years since IE9 was released.

CanIUse shows that html5 semantic elements (which is what we use it for, I believe) is [universally supported nowadays](https://caniuse.com/html5semantic).

I'd like to hear if anyone thinks that it's still worth supporting IE8, and also to see if the sysadmins have any usage stats for this era of browsers. If not, I can make a PR to remove `html5shiv`, along with the `es5` shim that has the [same range of detected browsers](https://github.com/openstreetmap/openstreetmap-website/blob/ad0cfee788a18704d7924d6b4ea7d2f27ad1934c/config/initializers/browser.rb#L4-L10) (and support via [caniuse](https://caniuse.com/es5)) and therefore the same reasoning as above.

**Comment by grischard** [comment]
IE8 [can't connect to openstreetmap.org anymore](https://github.com/openstreetmap/operations/issues/363) anyway.

**Comment by tomhughes** [comment]
Piwik confirms IE 11 was the only IE version seen yesterday.

**Comment by tomhughes** [comment]
Sadly it doesn't seem to fix the issue of the random test failures - they just move to complaining about `es5.js` instead which (despite what the error says) is pulled in by the previous line in the manifest just as html5shiv was.

**Comment by gravitystorm** [comment]
> Sadly it doesn't seem to fix the issue of the random test failures

Yeah, I thought that might happen

> they just move to complaining about `es5.js` instead

My plan was to remove that too, since that's covering the same browser versions that we no longer support. Of course, it'll complain about es6.js next, but we can work on that separately

Also can we remove the related code from config/initializers/browser.rb ?

**Comment by tomhughes** [comment]
I've dropped es5 and the browser test predicates as well now.
