### ISSUE TITLE
i18n "Comment"

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/openstreetmap-website#3368]
Does "comment" mean "a description" or "a reply" here? (btw I assume these are headers, not buttons)
https://translatewiki.net/wiki/Osm:Changesets.changesets.comment/en
https://translatewiki.net/wiki/Osm:Diary_entries.comments.comment/en

I have personally made changes to the documentation of these strings, but would like clarification. If possible, describe or link to where these strings can be found on the website/RSS/download.

I could expand this question to "comments" and "changeset comments" strings just to be sure about them, but right now the above is most important.

**Comment by tomhughes** [comment]
I think those are these resources:
* https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/en.yml#L392
* https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/en.yml#L511
I'm not sure that the first is actually used, at least I can't find any use of it, and the second is the heading on the third column at https://www.openstreetmap.org/user/TomH/diary/comments.

**Comment by danieldegroot2** [comment]
Never knew there was a log page for diary comments. Thank you Tom.
