### ISSUE TITLE
Enable paved/unpaved selection when finding directions

### ISSUE THREAD

**Issue by Engenia** [openstreetmap/openstreetmap-website#3370]
On https://www.openstreetmap.org/directions when asked to find directions from -35.1352, 149.1963 to -35.1094, 149.2467, using Bicycle (OSRM) chooses an 11km route while Car (OSRM) [and curiously Bicycle (GraphHopper)] chooses the more direct 5.7km route.
The reason appears to be the shorter route was (incorrectly) unpaved. A directions selection of paved/unpaved could reveal this anomaly, as it is not clear in OSM what the cause is. It is only by editing the map that it becomes clear what is happening.
(I have since corrected the error on OSM - just waiting for it to filter through)

**Comment by tomhughes** [comment]
We don't actually run any routing engines, we just provide an interface to several third party engines. Requests for enhancements would, in the first instance, need to be directed at the operators of those engines.
