### ISSUE TITLE
CyclOSM layer currently unavailable (grey)

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/openstreetmap-website#3371]
It seems to be redirecting to OSM's standard tiles, but the attempt to fetch e.g.   https://a.tile.openstreetmap.org/19/87764/204638.png results in a "418 I'm a teapot" on the tile fetch.

(for ref https://github.com/openstreetmap/openstreetmap-website/pull/2994 was where it was added)

**Comment by SomeoneElseOSM** [comment]
Now appears to be fixed - thanks to whoever it was!

**Comment by tomhughes** [comment]
Well it wasn't anybody here because we don't run the CyclOSM layer and have no power over it - in future if there's a problem with it then reporting it to whoever runs it will be more likely to get a quick response.
