### ISSUE TITLE
Navbar items not vertically centered

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/openstreetmap-website#3372]
![image](https://user-images.githubusercontent.com/22477298/142734040-7ed80a9f-1020-455f-a886-02efa9e7180c.png)

The navbar items' text is not vertically centered like the other items.

**Comment by ZhengLin-Li** [comment]
Do you mean that the position of **User Diaries** is a little bit higher than other items? I do think so. 

![image](https://user-images.githubusercontent.com/63448884/206469389-88f49398-8482-4559-b1d9-af303eeb566a.png)

BTW, have you tried to fix this issue? I am new to the open source community and am willing to fix this bug.

**Comment by lectrician1** [comment]
No, I mean: 
![image](https://user-images.githubusercontent.com/22477298/206491577-b9e0a7da-4f75-4cdc-a23e-c788ec4b1845.png)

**Comment by HolgerJeromin** [comment]
Can this be closed after merge of #4828 ?

**Comment by gravitystorm** [comment]
Closed, thanks!
