### ISSUE TITLE
Is there a way to report security vulnerabilities?

### ISSUE THREAD

**Issue by existXFx** [openstreetmap/openstreetmap-website#3374]

**Comment by HolgerJeromin** [comment]
I think the fastest way was done in this issue:

https://github.com/openstreetmap/openstreetmap-website/issues/3089#issuecomment-774986314

**Comment by existXFx** [comment]
Ok, thanks for response.

**Comment by tomhughes** [comment]
You can also use security@openstreetmap.org which will go to the operations team.

**Comment by gravitystorm** [comment]
We could/should put a SECURITY.md file in here too https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

**Comment by Firefishy** [comment]
A `security.txt` file (similar to robots.txt) in the root of the site is another popular way to detail the contacts for security reports. https://securitytxt.org/
