### ISSUE TITLE
In some layes, tile borders are very visible.

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3383]
In some layes, tile borders are very visible. In other layers, thankfully, they are barely seen.
![20211125T224108](https://user-images.githubusercontent.com/1230959/143461760-1f0c9d2b-2e72-43c4-bd66-74181eba2806.jpg)
![20211125T224154](https://user-images.githubusercontent.com/1230959/143461786-a41a2311-20b5-41d2-b2c6-bae4cd7ba960.jpg)
![20211125T224247](https://user-images.githubusercontent.com/1230959/143461816-618a646c-1a2b-410d-9e05-51cebec07c25.jpg)
![20211125T224308](https://user-images.githubusercontent.com/1230959/143461845-674319ea-7fe4-4887-9c74-a5b03cbf80d1.jpg)
![20211125T224342](https://user-images.githubusercontent.com/1230959/143461885-ed93f476-4247-4f2a-9dd9-ec94e45e3022.jpg)
24.12578/120.87253

**Comment by mmd-osm** [comment]
Sorry, this is totally off topic. All styles are managed outside of this repo.

**Comment by gravitystorm** [comment]
It's regarding gaps between tiles, not the contents of the images, so it's probably on topic.

![Screenshot from 2021-11-25 15-09-24](https://user-images.githubusercontent.com/360803/143465368-dd25dd03-abe0-4c32-9246-77f13e95de38.png)


@jidanni you'll need to give us some more information, since it doesn't happen for me and I suspect it doesn't happen for most people. Browser version, operating system, whether you see the same problem on multiple different devices, whether you have any browser zoom settings, etc.

**Comment by gravitystorm** [comment]
(Of course this is also possibly a Leaflet issue, since Leaflet controls the positioning of map images, but let's see if we can find out some more details first in case it's an interaction with our own code / css).

**Comment by systemed** [comment]
I encounter this fairly frequently with Leaflet maps on Webkit/Blink-based (Mac) browsers.

Both Safari and Chrome exhibit this on cycle.travel, for example. Currently Chrome appears to show it on osm.org but Safari doesn't (on the default osm-carto layer at least... switching layers, together with most other UI interactions, is obviously long-term broken on Safari).

**Comment by gravitystorm** [comment]
@systemed Thanks for the additional info. Since it's happening on multiple sites, I'm going to say it's probably this upstream bug: https://github.com/Leaflet/Leaflet/issues/3575

The question is then if we want to use one of the workarounds from that issue, or wait (hope) it gets fixed upstream.

**Comment by jidanni** [comment]
Google Chrome	98.0.4710.4 (Official Build) dev (64-bit)
Revision	63479af5a84bdf7e47ed34e56cc31f91b93535f0-refs/branch-heads/4710@{#8}
OS	Linux
JavaScript	V8 9.8.55
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4710.4 Safari/537.36

**Comment by mmd-osm** [comment]
> It's regarding gaps between tiles, not the contents of the images, so it's probably on topic.
Apologies, I didn't pay enough attention to the topic, and missed this detail. :(  removed my comment...

**Comment by tomhughes** [comment]
Leaflet 1.8.0 has now been deployed on openstreetmap.org - could somebody please check if this is still an issue?

**Comment by verhovsky** [comment]
Still an issue:

<img width="712" height="664" alt="Image" src="https://github.com/user-attachments/assets/266ebe70-8960-4dd9-bc7a-e2db2148c538" />

Chrome 144.0.7559.110 on macOS with 90% zoom.

**Comment by verhovsky** [comment]
https://github.com/Leaflet/Leaflet/issues/3575
