### ISSUE TITLE
OSM map no longer loads in IE11

### ISSUE THREAD

**Issue by RemySijbom** [openstreetmap/openstreetmap-website#3387]
### URL

https://www.openstreetmap.org/

### How to reproduce the issue?

1: start IE11
2: open https://www.openstreetmap.org/
3: the map doesn't load

### Screenshot(s) or anything else?

The HTML console shows a syntaxis-error (index-082bdf22ac1acb0b592af44c07db66f0510f4716d509dd00e3f126a4c4365396.js (8,249)). 

The issue started this week. 

![OSM website](https://user-images.githubusercontent.com/95346586/144212893-85dcde64-a033-4091-93a2-1ac70971d1bd.png)
![OSM syntaxiserror HTML console](https://user-images.githubusercontent.com/95346586/144213056-90c167fd-8b10-4983-ad38-b04f3b980b96.png)

**Comment by gravitystorm** [comment]
I don't have an IE11 VM to do any bisection testing, but my first suspicion would be [the locatecontrol upgrade](https://github.com/openstreetmap/openstreetmap-website/pull/3385) since there was some ES6-related upgrades a few days ago in https://github.com/domoritz/leaflet-locatecontrol/commit/6df3c2a78f506a83f08d6dad134839223f4570e1 . Perhaps there's some stuff in there that the es6 shim isn't fixing on IE11?

Otherwise, I don't see anything obvious in the recent history, so we would need to do some bisecting to narrow this down.

**Comment by tomhughes** [comment]
I've got a VM with IE11 but I don't know that there's any good way to get more information than that console error...

If 8249 is meant to be the byte offset in the file then I don't see anything obvious at that position.

**Comment by tomhughes** [comment]
It's this line which is using an arrow function :-(
```
    const LDomUtilApplyClassesMethod = (method, element, classNames) => {
```

**Comment by gravitystorm** [comment]
It also uses template strings, which according to https://github.com/Financial-Times/polyfill-service/issues/900 can't be polyfilled either.

**Comment by gravitystorm** [comment]
I've opened #3388 as a workaround while we make the bigger decision on IE11 support.

As far as I understand it, we can do two things:

1) Keep using the latest versions of locatecontrol, and drop support for IE11 completely. This also means we can remove the es6 shim, and start using es6 things in our own JS code.
2) Set up a transpilation pipeline (e.g. via webpacker) to convert the es6 code into es5 code before it's sent to the browser.

I think 2) sounds like a lot of work for a small number of end users, but I don't know how small that number is. I think 1) would be my medium-term goal, but then we need to decide if that happens either now, in the medium term (e.g. mid 2022?) or in the long term (after all, we supported ie8 etc for quite some time after they were obsolete).

So I'm interested in what other people think about a) the options and b) the timeline.

**Comment by bhousel** [comment]
These days I think dropping support for IE11 is reasonable.

On some of my projects, I use this snippet of code at the beginning of the `body` to show a warning from [browser-update.org](https://browser-update.org/) (which I have reviewed and I trust) to tell users of old browsers that things might not work properly and they need to upgrade.  You can customize the messages or the browser versions.

```html
<body>
<script>var $buoop={required:{i:15,e:-4,f:-3,o:-3,s:-1,c:-3},reminder:0,noclose:true,no_permanent_hide:true,insecure:true,api:2021.06};</script>
<script src='https://browser-update.org/update.js'></script>
...
```

**Comment by tomhughes** [comment]
Current trajectory of IE visits to the site:

![image](https://user-images.githubusercontent.com/147741/144250159-2fd5826b-6e2d-499f-8f48-d22aa499c9b0.png)

I'm reluctant to rework the asset pipeline to use webpack at the moment given it's all changing again in rails 7...

**Comment by tomhughes** [comment]
Well iD may kind of make the decision for us in part if I'm reading the runes in https://github.com/openstreetmap/iD/pull/8774 right.

**Comment by HolgerJeromin** [comment]
I think more people are browsing the map and than changing the map. So IMO it is not super important what iD does.
But I would drop ie11 support soon, too.

**Comment by controversial** [comment]
> encourage any IE11 users to consider alternatives, and expect our support to end some time in 2022

@gravitystorm @tomhughes does openstreetmap-website have a current policy on what the browser support target is for JavaScript? This was the only issue I was able to find

**Comment by HolgerJeromin** [comment]
@controversial 
#5421 has some discussion (es 2021 is the minimal browser support we need)
