### ISSUE TITLE
How use a .json URL suffix.

### ISSUE THREAD

**Issue by assoft89** [openstreetmap/openstreetmap-website#3401]
### Description

Hello how use a .json URL suffix. in GET API 
https://wiki.openstreetmap.org/wiki/API_v0.6#General_information
Retrieving map data by bounding box: GET /api/0.6/map
https://api.openstreetmap.org/api/0.6/map?bbox=76.36808519471933,64.41713173392363,76.75875957883649,64.50167155517451
return xml

**Comment by tomhughes** [comment]
The best place to ask questions about using OpenStreetMap is https://help.openstreetmap.org/ where a large community of fellow users will be able to advise on simple questions like this.
