### ISSUE TITLE
Hardware support thanks is inconsistent

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/openstreetmap-website#3406]
### Description

- The welcome dialog at the upper-left corner of the mapview says that hosting is supported by Fastly but Fastly is not attributed at https://hardware.openstreetmap.org/thanks/
- Bytemark is attributed twice on https://hardware.openstreetmap.org/thanks/

**Comment by mmd-osm** [comment]
https://github.com/gravitystorm/osmf-server-info would be the right place to report anything regarding hardware.osm.org

**Comment by tomhughes** [comment]
I would just add that hardware.openstreetmap.org is not really a public facing site - it's mostly a tool for the admins. I'm not really sure why that "thanks" page is even there as the page on the main site is where we thank our supporters. I didn't even realise there was a duplicate on hardware.osm.org.
