### ISSUE TITLE
Scientific notation in lat/lon

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/openstreetmap-website#341]
Nodes very close to the equator or greenwich meridian will produce a lat or lon in scientific notation.

This is true of both the rails port API and website. cgimap does not have this issue.

See http://lists.openstreetmap.org/pipermail/talk/2012-December/065457.html

Although both are correct, cgimap and the rails port handle decimal places differently with cgimap having a fixed number of places by padding with zeros and the rails port stripping trailing 0s up to 1.0.

**Comment by gravitystorm** [comment]
I've done some preliminary work on this, but it'll be much easier to write thorough tests after I've converted the nodes fixtures to factories.
