### ISSUE TITLE
Add revoke endpoint for OAuth2

### ISSUE THREAD

**Issue by Robbendebiene** [openstreetmap/openstreetmap-website#3412]
### Description

Currently there is no way to [revoke an access token](https://oauth.net/2/token-revocation/). Applications who want to provide a proper logout option rely on such functionality. If they just "throw away" the access token then in theory the token can still be (ab)used.
The standard doorkeeper configuration uses the `/oauth2/revoke` endpoint, but it seems like it is not enabled for openstreetmap?

**Comment by tomhughes** [comment]
I'm not sure I agree that "logout" necessarily requires revoking the token, but it rather depends on what you mean.

Are you talking about an application "logging out" of access to openstreetmap.org? or are you (ab)using oauth2 as a login scheme for your own site and you're talking about logging out of your site?

**Comment by Robbendebiene** [comment]
Sorry for not making my self clear. I'm not using OSM oauth2 as a login scheme for a personal site. I'm working on some kind of OSM-Editor (native App) who provides the option to upload edits via an OSM account. The authentication is managed/done via OAuth2. So I'm talking about

> an application "logging out" of access to openstreetmap.org

I'd agree that logout doesn't **necessarily** require token revoking. I guess it is the same debate about just clearing a session cookie / removing it from the browser or doing an actual "logout" request to the server which cleans and revokes the session on the server side. One might argue that the latter is more clean and potentially more secure.

**Comment by Robbendebiene** [comment]
@AntonKhorev Thanks for the info. I just tested it again on our App and it worked 🥳
