### ISSUE TITLE
Vendorer fails due to new GitHub security improvements

### ISSUE THREAD

**Issue by dakotabenjamin** [openstreetmap/openstreetmap-website#3415]
### Description

I was building openstreetmap-website using [OSM Seed](https://github.com/developmentseed/osm-seed/) and received an error while running the vendorer. 

```
/var/.gem/ruby/gems/vendorer-0.2.0/lib/vendorer.rb:92:in `run': Failed: git clone git://github.com/aratcliffe/Leaflet.contextmenu.git /tmp/d20220111-9-1y7dtc1 2>&1 (RuntimeError)
Cloning into '/tmp/d20220111-9-1y7dtc1'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

The Vendorer file contains references to github repos using the git:// protocol, which is not supported anymore. I tested changing them all to `https://` instead and that worked for me. I don't know if the Vendorer is used in production, but I am happy to make a PR if that would be worthwhile.

**Comment by tomhughes** [comment]
There's no need to run vendorer unless you're trying to update the vendored files. I'm not sure what OSM Seed is but I doubt it needs to run it - only developers who are trying to update the version of a vendored item in the repository need to to that.

**Comment by tomhughes** [comment]
Anyway I though it was only write access via the git protocol that was disabled, and vendorer only ever reads?

**Comment by tomhughes** [comment]
Ah this seems to be a second phase that started today of disabling it for read as well.
