### ISSUE TITLE
User online/offline status

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/openstreetmap-website#3421]
### Description

It would be cool to have a user online/offline status that would show indicate if a user is online/mapping or not.

**Comment by tomhughes** [comment]
How exactly are we supposed to know?

**Comment by HolgerJeromin** [comment]
And why?
[GDPR](https://gdpr.eu) is probably against it, too.

**Comment by lectrician1** [comment]
> How exactly are we supposed to know?
