### ISSUE TITLE
Minor layout annoyance

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/openstreetmap-website#3435]
### How to reproduce the issue?

The element detail display for example https://www.openstreetmap.org/way/393891731#map=18/47.29938/8.39203 lists last change date, author and changeset number/link on one line that is line wrapped. Depending on the length of the components this can lead to a visually rather sub-optimal layout (see screen shot). 

IMHO it would be better to split at least the changeset reference on to its own line.

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/1011860/150670836-807e58a3-7583-40e5-a9fa-26940168077d.png)

**Comment by mxdanger** [comment]
While the whole side menu is in need of a refresh, a simple stopgap solution could just be doing something like this: removing the dot space before changeset and adding `</br>`.

### Before:
![image](https://user-images.githubusercontent.com/32040254/157397962-91583deb-7bc7-45cd-a559-ba8609e47482.png)
### After:
![image](https://user-images.githubusercontent.com/32040254/157397840-462085ea-52ed-4eb9-95e1-5551d4d27ec1.png)

**Comment by mmd-osm** [comment]
Link: https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/browse/_common_details.html.erb#L19
