### ISSUE TITLE
Add last edited date to user profile

### ISSUE THREAD

**Issue by boothym** [openstreetmap/openstreetmap-website#3437]
Mockup of the user profile page below, which would show the date a user last edited alongside the date they joined osm.org.

I feel this would be useful as it basically indicates when the user was last active, as sometimes you go to a profile to check their edits, before realising they haven't been active for a long time.

![lastedited](https://user-images.githubusercontent.com/16965772/151213826-63160540-1200-4862-9e62-401ecd1e929b.png)

**Comment by mmd-osm** [comment]
Since this would be shown on a user profile page, "Last edited" might be somewhat misleading, as it could also refer to the last time the user profile page has been updated.

**Comment by boothym** [comment]
I suppose "Last changeset" might be better then.

**Comment by mmd-osm** [comment]
Changeset sounds a bit too technical for people unfamiliar with OSM. Maybe call it "Last map edit" or so.

**Comment by matkoniecz** [comment]
> I feel this would be useful as it basically indicates when the user was last active, as sometimes you go to a profile to check their edits, before realising they haven't been active for a long time.

I do it very very often and such change would be really helpful.
