### ISSUE TITLE
"Map Notes" page is very slow to load

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/openstreetmap-website#3443]
### URL

https://www.openstreetmap.org/user/Boulevard1/notes

### How to reproduce the issue?

1. Open any user profile
2. Click on "Map Notes"

**Comment by mmd-osm** [comment]
Takes 2.7 seconds here. What is "very slow to load" in your case?

**Comment by Dimitar5555** [comment]
The best result that I got is 2.6 seconds. Most of the tries it was 2.8 - 2.9 seconds and a single case of 3 seconds (out of 20 total tries). "Very slow to load" compared to any other page on the website.

**Comment by matkoniecz** [comment]
Thank you! I just wanted to say that OSM website has a very nice performance, on many pages this load time would be normal - not something worth reporting as a bug and then fixed.
