### ISSUE TITLE
Add a confirmation dialog/page when you click on "Unfriend"

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/openstreetmap-website#3444]

**Comment by tomhughes** [comment]
Perhaps you could provide some context for why you think this is important?

**Comment by gravitystorm** [comment]
In general there's no need for confirmation steps for changes that are easy to undo. So in this example, you can add the user as a friend again, and no information would be lost.

I think you'll need to add more details to persuade me to add a confirmation step here.

**Comment by Dimitar5555** [comment]
(Assuming that you are not planning to rename the friending functionality to "Follow" as suggested in https://github.com/openstreetmap/openstreetmap-website/issues/3310#issuecomment-912880292.)
The idea is that it's possible to accidentally click that button (which happened to me). Sure it is easy to friend them again, but this will send them an email about it. I'm also not sure if the other user also receives an email notification when somebody unfriends them.

**Comment by mmd-osm** [comment]
> I'm also not sure if the other user also receives an email notification when somebody unfriends them.

The other user won't receive a notification in that case. ([ref](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/friendships_controller.rb))

**Comment by Dimitar5555** [comment]
> > I'm also not sure if the other user also receives an email notification when somebody unfriends them.
> 
> The other user won't receive a notification in that case. ([ref](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/friendships_controller.rb?rgh-link-date=2022-02-02T12%3A53%3A11Z))

That's true, but after accidentally clicking "Unfriend" you will (most likely) click "Friend" which will send a notification. Then the other user might wonder why the first person has unfriended them in the first place.

**Comment by mmd-osm** [comment]
This seems like a rather pessimistic way at looking at it, and it seems a bit far fetched to me.
