### ISSUE TITLE
Add building=cowshed and building=sty to en.yml

### ISSUE THREAD

**Issue by Hufkratzer** [openstreetmap/openstreetmap-website#3449]
### Description

Add [building=cowshed](https://wiki.openstreetmap.org/wiki/Tag:building%3Dcowshed) and [building=sty](https://wiki.openstreetmap.org/wiki/Tag:building%3Dsty)  to en.yml so that they can be translated. ([building=stable](https://wiki.openstreetmap.org/wiki/Tag:building%3Dstable) is already there).

**Comment by mmd-osm** [comment]
You could add this on your own by navigating to https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/en.yml#L832 then clicking on the edit icon, adding the new entry, then create a pull request.
