### ISSUE TITLE
Edit map Dropdown and tooltip text remain displayed after zooming out.

### ISSUE THREAD

**Issue by zanguian** [openstreetmap/openstreetmap-website#3456]
### URL

https://www.openstreetmap.org/

### How to reproduce the issue?

MacOS 12.0.1
Chrome 98.0

See screenshot. I zoom in somewhere to edit an area. This enables the Edit button and the dropdown button next to it. I then click the dropdown to see two options available. I click the dropdown button again to close it and then zoom back out. This is supposed to disable the dropdown button as it was when I was initially zoomed out but when I click the dropdown now I'm still seeing the options available. Clicking either option doesn't seem to do anything, so these shouldn't be displayed to the user when they zoom back out.

### Screenshot(s) or anything else?

<img width="791" alt="EditDropdown" src="https://user-images.githubusercontent.com/51209380/153730391-8e95cbb6-d874-43ab-97cb-397407dd393b.png">

**Comment by lectrician1** [comment]
I was also able to reproduce this on Firefox 97.0 and Windows 11.

**Comment by tomhughes** [comment]
Were you expecting not to be able to? Nobody has disputed that the bug as described exists...
