### ISSUE TITLE
Firefox: Mouse wheel scrolling results in 2 step zoom

### ISSUE THREAD

**Issue by KommX** [openstreetmap/openstreetmap-website#3463]
### URL

https://www.openstreetmap.org

### How to reproduce the issue?

1. Open Firefox
2. Go to https://www.openstreetmap.org
3. Use your mouse wheel to change the zoom factor.

In Chrome the zoom factor changes in steps of 1, e.g. 10 -> 11. But in Firefox the behavior lately changed, so that the zoom factor changes in steps of 2, e.g. 10 -> 12.
Zooming via the "+" and "-" buttons in the top right corner still works as expected.

**Comment by tomhughes** [comment]
You're talking about zoom the map I assume? That will be an issue with Leaflet that would need to be raised at https://github.com/Leaflet/Leaflet.

**Comment by tomhughes** [comment]
In fact see the discussion at https://github.com/Leaflet/Leaflet/issues/7403 where there is already an issue open - it starts with Chrome but Firefox is discussed further down the thread.
