### ISSUE TITLE
Map Data highlight stuck on multiple selections (visual bug)

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/openstreetmap-website#3465]
### URL

&layers=D

### How to reproduce the issue?

1. Enable Map Data overlay
2. Select an object
3. Select another object while info tab of the first object is still open
4. Select yet another object while info tab of the previous object is still open
5. and so on.. (bold blue highlight stays on 2nd+ selection until tiles are unloaded)

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/67521919/155023125-a5d8af49-00a8-453d-b0e1-eccdd2fee9a3.png)

**Comment by tomhughes** [comment]
Probably a leaflet issue - the data is just a leaflet layer and the selection logic is all provided by leaflet as far as I know.

**Comment by tomhughes** [comment]
Hmm maybe not as it seems to be related to us hooking the layer to show the sidebar. To be honest I'd forgotten we did tthat as can't remember when I last used the data layer as it's pretty much useless with the amount of data we have now.

We should really just get rid of the data layer - the query tool provides a much better way to achieve what is was designed for these days.

**Comment by gravitystorm** [comment]
> I doubt anybody much uses the data layer these days

FWIW, I use it extensively. It's helpful when investigating multiple features (e.g. addresses on a row of houses). It's easy to zoom in so "too much data" isn't a problem for me. It has the advantage that you can click on the feature that you want, and then a second, and then a third. With the query tool you click on the first, but then you have to click back, wait for the list to reload, move the mouse up and down the list until the thing you want is highlighted, click on that, then click back, wait for the list to reload, move the mouse up and down the list until the third is highlighted, etc etc.

Neither is particularly great UI, but the two tools do have different strengths and are to some extents complimentary.

**Comment by tomhughes** [comment]
I've got rid of the wide blue highlight in 97bb13595750d2ba5d03a5abe2ede7cd11a8a481 and used 398a39dd0ae687eddac914490a4616bed4f42f69 to make sure the orange highlight from the sidebar is kept on top when the data layer is updated.

So hopefully now there should be a single consistent highlight for the selected object.
