### ISSUE TITLE
Add `inverse_of` to various model associations

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3471]
Normally Rails can autodetect bi-directional associations. This has two advantages:
* Saves memory. If you do e.g. `issue.reports.first.issue` you get the same object back, without having to load `issue` fresh from the database (or duplicate it from the query cache).
* Makes validations easier. If you have a new `issue`, with a new `report`, then the validation will pass even though `report.issue_id` is currently blank - rails knows it will be filled in later.

However, [Rails can't autodetect this bi-directional association whenever a `foreign_key` is specified](https://guides.rubyonrails.org/association_basics.html#bi-directional-associations). The solution is to specify the `inverse_of` on certain relationships where the autodetection fails. Unfortunately for us, we have a lot of explicitly specified `foreign_key` options!

Rubocop can find these cases for us, without making us specify them on everything. So we should enable [Rails/InverseOf](https://github.com/openstreetmap/openstreetmap-website/blob/172a71e3f242f74a6eb1f7bb45fb4d5f3ddff5e7/.rubocop.yml#L58-L59) ([cop docs](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsinverseof)) and add the inverse relationships.

**Comment by faebebin** [comment]
Shouldn't this issue be `closed` ?

**Comment by mmd-osm** [comment]
This was addressed in  #3472, I think we can close this one.
