### ISSUE TITLE
openstreetmap-carto

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/openstreetmap-website#3473]
### Description

Hi,

sometimes I wanted to report a problem with rendering. And I never found where because in the repositories of openstreetmap, nothing seems to be the good one.
Then one day I found [this one](https://github.com/gravitystorm/openstreetmap-carto) : I don't know if it is the official place for the rendering we can see on ID for example.

But if it is, it should be great to have at least a link to it in the repositories of openstreetmap. Or any way to find it easily when we are on [this page](https://github.com/openstreetmap).

Same thing for others repositories working on osm, if any.

Best regards

**Comment by tomhughes** [comment]
This is what I'm referring to:
![image](https://user-images.githubusercontent.com/147741/155548715-c131025d-a3bd-47fa-aa48-8d677e67a5dd.png)

**Comment by tomhughes** [comment]
All of which is precisely why we added that menu, to direct bugs relating to major components which have are maintained elsewhere to the correct locations.

As far as I know there is no significant component of openstreetmap.org maintained under systemed these days.

**Comment by gravitystorm** [comment]
> Even if I opened this issue with only one example (= the title), we find some other things about osm in [gravitystorm](https://github.com/gravitystorm), in [systemed](https://github.com/systemed) and probably in others I've never heard of.

Sure, and that's not a problem. It's up to the maintainers of each piece of software where they want to store the source code. Some of the projects want to put it under the OpenStreetMap github organisation, but others don't. Some maintainers will choose other hosting outside of github, if they want. It doesn't matter and it doesn't all need to be in the same place.

In addition, there's no restriction as to what software OSMF want to run on their servers. So we don't need to have every repo under the openstreetmap organisation either.

**Comment by gravitystorm** [comment]
But in any case, it's nothing to do with this project where other people run their own projects, so this is definitely the wrong repository to be discussing this topic!

**Comment by Mahabarata** [comment]
Yes, I know that, the good place for my question should be "https://github.com/openstreetmap" or "https://github.com/orgs/openstreetmap/repositories" but impossible to open an issue there.

My question is now : what are the "https://github.com/orgs/openstreetmap/projects" and "https://github.com/orgs/openstreetmap/projects?type=beta", 2 pages with nothing in it ?

Is it not the good place to put links to things not in "https://github.com/openstreetmap" but elsewhere ?

**Comment by tomhughes** [comment]
Well that isn't something that github offers - there is no way to add arbitrary links to those pages.

**Comment by tordans** [comment]
> My question is now : what are the "https://github.com/orgs/openstreetmap/projects" and "https://github.com/orgs/openstreetmap/projects?type=beta", 2 pages with nothing in it ?

This is something like Trello for Github-Projects. So it's not a good place to link to other projects.

If no one uses those for the openstreetmap orga, an admin could hide them AFAIK https://docs.github.com/en/organizations/managing-organization-settings/disabling-project-boards-in-your-organization

> Well that isn't something that github offers - there is no way to add arbitrary links to those pages.

It would be possible to use https://github.blog/changelog/2021-09-14-readmes-for-organization-profiles/ for that. Which would require to manage the content of that page, of course.

**Comment by Mahabarata** [comment]
I'm not sure that we need someone to manage this page : imagine that someone wants to develop something new for osm. But he still has a page for its other projects (I mean a page like this one "https://github.com/gravitystorm"). So he wants to create its new idea in a new repository on his own page. But he also wants that other people know its work. So he puts a link on the page you talk on the "https://github.com/openstreetmap".

What we need now is that someone create the page, put some links as a beginning and wait for developpers to add their own links if they want to improve the visibility of their work.

Or (another idea) : someone manages the page, when the developer of the new project wants to add a link, he send a message to the manager. Not a lot of work, a few seconds is needed to add a link so maybe someone will be agree to do that ?

**Comment by tomhughes** [comment]
Creation of some kind of index page for OSM related software is not anything to do with the repository or this issue tracker - this issue tracker is for issues related to the software that runs openstreetmap.org and nothing else.
