### ISSUE TITLE
is there a way to customize layers in preview mode ?

### ISSUE THREAD

**Issue by cmoffroad** [openstreetmap/openstreetmap-website#3475]
### Description

It would be great for sharing purposes to be able to customize the layer in OSM object preview mode.

Example: https://www.openstreetmap.org/way/1031096561/#map=14/19.0667/98.5260&layers=Y

In the layers menu, only a fixed list of renderers is made available.

It would be great if the selection could be customizable at least through a query or hash parameter, as the editor 

### Screenshots

<img width="353" alt="Screen Shot 2565-02-28 at 07 28 48" src="https://user-images.githubusercontent.com/2485196/155906782-2192a97e-c52a-460d-bfc7-db884edcdc79.png">

**Comment by tomhughes** [comment]
Can you explain what you mean? Are you asking to be able to add layers other than those in the layer chooser?

**Comment by cmoffroad** [comment]
> Are you asking to be able to add layers other than those in the layer chooser?

Exactly. Added a screenshot above showing the list is limited and fixed.
I understand an exhaustive list will never satisfy everyone, so if there was a way to pass a query parameter like in ID, it would be perfect :)

e.g. https://www.openstreetmap.org/way/1031096561/#map=14/19.0667/98.5260&layers=custom:https://{switch:services,server}.arcgisonline.com/arcgis/rest/services/World_Topo_Map/MapServer/tile/{zoom}/{y}/{x}

**Comment by tomhughes** [comment]
Then no I don't think we'll be doing that - our goal is to support building the map not to provide a general purpose maps interface.
