### ISSUE TITLE
OSM opensearch config uses an old/ugly logo

### ISSUE THREAD

**Issue by endim8** [openstreetmap/openstreetmap-website#3478]
### URL

https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/opensearch/osm.xml

### How to reproduce the issue?

- open openstreetmap.org on Firefox
- click in the search bar
- press the OSM logo with the green '+', under the section titled 'This time, search with:'

### Screenshot(s) or anything else?

<img width="211" alt="Screenshot 2022-02-28 at 11 11 15" src="https://user-images.githubusercontent.com/26939824/155973557-4d3b4569-b581-424a-bb1a-a7f3cdf479ea.png">

**Comment by simonpoole** [comment]
The licence statement and list of geocoders needs updating too.

But does anybody actually use this? At least the facility in FF is geared towards searching "the Internet" not a specific geo search.

**Comment by endim8** [comment]
> The licence statement and list of geocoders needs updating too.
> 
> But does anybody actually use this? At least the facility in FF is geared towards searching "the Internet" not a specific geo search.

There must be some people who use it. It might as well be kept as it's not exactly much to maintain

**Comment by endim8** [comment]
ooh, i should add that this is usable by any browser that supports [opensearch](https://developer.mozilla.org/en-US/docs/Web/OpenSearch), not just Firefox:
>OpenSearch is supported by (at least) Firefox, Edge, Internet Explorer, Safari, and Chrome.
