### ISSUE TITLE
Improve Nominatim search to handle British Saint/St alias

### ISSUE THREAD

**Issue by PinkDuck** [openstreetmap/openstreetmap-website#3480]
### URL

https://www.openstreetmap.org/search?query=saint peters street%2C norwich

### How to reproduce the issue?

Search for "saint peters street, norwich" on the OSM website. Note no results found from OSM Nominatim installation.

Search for "st peters street, norwich" and results are found.

Ideally search results should not depend on the user knowing the precise expanded/contracted form.

This could be achieved by creating a custom sanitizer during import stage. [lonvia](https://github.com/lonvia) has said an easier means of setting up such a sanitiser is being looked into.

In Great Britain and Northern Ireland street names beginning "St " or "St. " are sometimes considered de-facto or are legally defined as such by the road naming authorities.

**Comment by lonvia** [comment]
For reference https://github.com/osm-search/Nominatim/issues/2618

**Comment by gravitystorm** [comment]
I was about to close this and refer you to the nominatim repository, but it looks like that's been done already. However, as far as I can tell, this repository isn't the right place for this discussion. This codebase takes what you type into the search, sends it to the OSMF-hosted nominatim servers, and then displays the results.

So I would recommend either:

a) continuing the discussion in the nominatim repository, if you think that software changes are required, or
b) continuing the discussion with the OSMF OWG, if you think that an import or runtime configuration change to the OSMF-hosted nominatim servers is required, or
c) continuing the discussion with the GB/UK mapping community, if you think their mapping conventions are incorrect.
