### ISSUE TITLE
OSM.org SVG logo has unneeded data outside the canvas

### ISSUE THREAD

**Issue by endim8** [openstreetmap/openstreetmap-website#3481]
<img width="407" alt="Screenshot_2022-02-28_at_15 34 48" src="https://user-images.githubusercontent.com/26939824/156034386-3b95b25c-0852-41bd-96df-25887e3bd045.png">

It also seems that the SVG can be compressed quite a bit/metadata etc removed. Considering this icon is loaded _every_ time someone uses openstreetmap.org, it'd probably be a good idea to optimise it as much as possible.

(MXX on the OSM Discord noticed that this might be an issue, so thanks to them)

**Comment by mmd-osm** [comment]
The compressed SVG file is 13.85 KB, about half the size of a single map tile, and is cached in the browser for a year. Other files like application.js are 10 times bigger already. It is not very likely that the proposed change will have much impact.
