### ISSUE TITLE
Add a reply button to a send email

### ISSUE THREAD

**Issue by tordans** [openstreetmap/openstreetmap-website#3497]
### Description

UseCase: I send an email and want to send a follow up as a reply to that email. In other workflows, I would open the previous mail, click reply to follow up on the email.

However, in OSM message such a button is missing. I need to write an independent message, loosing the context (or I have to manually re-create the context).

Possible solution: Adopt the reply button from incoming mails to outgoing mails and pre-fill a message to the recipient with the previous mail as comment (just with incoming mail-replies).

This is the page I am referring to.
Route example: at https://www.openstreetmap.org/messages/1016723
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/111561/158005701-501a6535-10b9-45e8-97f2-39f8f090977c.png">

**Comment by mmd-osm** [comment]
#2644 is somewhat similar.
