### ISSUE TITLE
Allow usage of object filter path as alternative to object ID

### ISSUE THREAD

**Issue by saerdnaer** [openstreetmap/openstreetmap-website#3499]
### Description

Right now users use URLs with IDs to reference individual objects on osm.org, e.g. https://www.openstreetmap.org/relation/23092 – which might break when the object changes, especially when used for nodes or ways instead of relations.

We could allow addressing via other attributes like `ref`, `network` etc – e.g. for the object above one could think about an URL like `https://www.openstreetmap.org/relation/[ref=A+555][network=BAB]`,  or `https://www.openstreetmap.org/relation/network=BAB/ref=A+555`, or `https://www.openstreetmap.org/relation/?network=BAB&ref=A+555`

Right now such an URL leads to a 404, but we could modify the rails app to delegate such a request to `query.openstreetmap.org` which find the corresponding object(s) and redirects the user back osm.org, now with the current ID of that object.

Actually query.openstreetmap.org alreasy [has a feature](https://wiki.openstreetmap.org/wiki/Overpass_API/Permanent_ID) which can be reused for that:

`https://query.openstreetmap.org/query-features?data=[out:custom];{insert-query-from-url-here};out;`
e.g. 
[https://query.openstreetmap.org/query-features?data=[out:custom];relation[ref="A+555"][network=BAB];out;](https://query.openstreetmap.org/query-features?data=[out:custom];relation[ref="A+555"][network=BAB];out;)
which redirects to
https://www.openstreetmap.org/relation/23092

What's your opinion? 
Which your structure would you prefer?
Is it worth to create a pull request implementing the corresponding changes in the rails app?

**Comment by mmd-osm** [comment]
As a side note: permanent ids have been around on Overpass API since many years, but somehow this idea never really took off. There’s only very little use of the feature, and I’d certainly expect even fewer usage for what is being proposed here.

**Comment by tomhughes** [comment]
There's also no plausible way (with reasonable performance) to implement such a thing with the API database schema so I'm afraid it's a hard no.

It sounds like a job for something like overpass.

**Comment by mmd-osm** [comment]
Implementation wise one might define an Apache rewrite rule to redirect non-numeric relation numbers to the Overpass endpoint. This is all a horrible hack, and people should simply use the respective Overpass endpoint instead if they see the need for it.

**Comment by tomhughes** [comment]
Well they shouldn't use query.openstreetmap.org because that is an internal implementation detail of the web site and not supported or available for general use.

The whole scheme doesn't work anyway - a query which happens to return one object today might change at any time to return multiple objects.

**Comment by mmd-osm** [comment]
In case of multiple hits Overpass returns a list all matching objects: https://overpass-api.de/api/interpreter?data=%5Bout%3Acustom%5D%3Brel%5Bref%3D%22A+555%22%5D%3Bout%3B

**Comment by tomhughes** [comment]
Yes I know - my point is that this doesn't function as a scheme to create permanent identifiers for objects.
