### ISSUE TITLE
[Feature] Add a way to overlay speed limits.

### ISSUE THREAD

**Issue by moom0o** [openstreetmap/openstreetmap-website#3500]
### Description

I'd prefer to not use openstreetbrowser as it's very slow. I believe there should be an option to overlay speedlimits with colors corresponding to each speed on roads. If no speedlimit data has been entered, don't display an overlay.

Openstreetbrowser example: https://www.openstreetbrowser.org/?categories=car_maxspeed (zoom in for it to work, it takes a very long time to load.)

### Screenshots

![image](https://user-images.githubusercontent.com/48740106/158234619-047ae81c-c7df-4eca-bb78-06e8554c32b4.png)

**Comment by tomhughes** [comment]
What would the purpose of this be?

**Comment by moom0o** [comment]
> What would the purpose of this be? Specifically who do you seeing using this, and what for?

The data is already there for most roads, so why not make it possible to view it on the map. It would be great for people who want to see speedlimits when going on roadtrips. It's not possible to view on google maps, so it would be nice to have it here.

**Comment by tomhughes** [comment]
That was precisely what I was trying to determine - whether you viewed this as a tool for mappers or for end users.

The goal of www.openstreetmap.org is to support mappers and to provide tools to help them map the world - it is specifically not to offer a full service google maps replacement for end users so I'm afraid this seems to be out of scope.

**Comment by systemed** [comment]
This is the sort of thing that _may_ ultimately be possible when OpenStreetMap offers vector tile rendering, on which early exploratory work has started.

**Comment by tordans** [comment]
> I believe there should be an option to overlay speedlimits with colors corresponding to each speed on roads. If no speedlimit data has been entered, don't display an overlay.

In case you are just using this for your mapping or some smaller community, you could use something like this https://twitter.com/tordans/status/1482325001474875396. While working on this, I realized how bad the `maxspeed` data is (even) in Berlin. I think a big part of this is, that is is nearly invisible so no one notices.

> What would the purpose of this be? Specifically who do you seeing using this, and what for?

I was looking into this recently. My UseCase is: We have a few datasets in OSM that is quite invisible but very important. `maxspeed` is one example, `surface`/`smoothness` is one. The `parking:lane` tags are another. One could create a full map style for this…; but I see this more as a utility layer on top of a (grayed out?) (pixel?) basemap.

Right now, we are looking for a way to scale the (quite manual) data parking lane data from https://supaplexosm.github.io/strassenraumkarte-neukoelln/?map=parkingmap#18/52.48048/13.42856 to all of Berlin by moving the logic into lua scripts in https://github.com/gislars/strassenraum-berlin.

It would be great, if the OSM ecosystem could provide a way for such projects to create their own specific vector tile datasets. And once those are mature, they could be shown on osm.org.

It looks like https://github.com/openstreetmap/operations/issues/565 is more focussed on creating a basemap style (and the vector data needed for that). However, this would require special data processing like the parking data example shows.
