### ISSUE TITLE
Improve resolution on high detail (retina) displays

### ISSUE THREAD

**Issue by xplosionmind** [openstreetmap/openstreetmap-website#3504]
### Description

As pointed out in #850, not only the icons, but all of the maps in OSM look very ugly and low resolution, as if they were a screenshot taken from a very old computer, rather than vector images.

It would be very nice (also to expand the use of OSM to more mainstream users) if the resoultion could be independent from he screen, but rather always sharp and nice to look at.

### Screenshots

As you can see, the nav bar writings have definitely more resolution than the ones in the map.
<img width="1440" alt="Screenshot 2022-03-20 at 11 29 05 AM" src="https://user-images.githubusercontent.com/42862428/159158169-d2ae39bd-acc6-4bf4-a28b-bc36a7e67ea7.png">

**Comment by tomhughes** [comment]
If you a tile layer with retina support that you would like to propose then the process for doing so can be found at https://wiki.openstreetmap.org/wiki/Featured_tile_layers/Guidelines_for_new_tile_layers.

The web site team do not produce any map renderings themselves and are only able to add those which exist.

**Comment by tomhughes** [comment]
Note that the operations team (who provide the existing default tile layer) are actively trying to encourage the development of a vector tile style that would offer support arbitrary resolutions.

That are not in a position to offer retina bitmap tiles alongside the existing tiles due to resource constraints.

**Comment by xplosionmind** [comment]
Thanks a lot for your remarks. I am far from being a developer, hence I do not fully understand your points. Nevertheless, I will be waiting for some improvements on this front.

Thanks a lot!

Best,  
Tommi
