### ISSUE TITLE
openstreetmap api, download gpx data as blob

### ISSUE THREAD

**Issue by strukturart** [openstreetmap/openstreetmap-website#3507]
### Description

Hello,

I'm trying to load the content of a file with, but I'm getting a 302 error.

`TypeError: NetworkError when attempting to fetch resource. `

is it only possible to download the file and not just load the content of the file with .blob() ?

```

  let osm_server_load_gpx = function (id) {
    let n = "Bearer " + localStorage.getItem("openstreetmap_token");

    const myHeaders = new Headers({
      Authorization: n,
    });

    return fetch("https://api.openstreetmap.org/api/0.6/gpx/" + id + "/data", {
      method: "GET",
      headers: myHeaders,
      redirect: "follow",
    })
      .then((response) => response.text())
      .then((data) => {
        console.log("data:" + data);
      })

      .catch((error) => {
        alert("error: " + error);
      });
  };
```

**Comment by strukturart** [comment]
I checked the status again, I get status 0. What's weird is that I can call up the endpoint` details` without a problem.

https://github.com/strukturart/o.map/blob/02dc8d711e4e3918712050644ebd2c4629af6a38/application/index.js#L392

**Comment by tomhughes** [comment]
Because the details call doesn't redirect - the GPX data one does.

I can't help you anymore because I know nothing about the framework you're using. You need to consult the documentation for the library you're using to find out how to tell it to follow redirects.

**Comment by tomhughes** [comment]
Note that it will actually redirect several times so you will need to follow the whole chain, which should look like this:
* https://api.openstreetmap.org/api/0.6/gpx/.../data
* https://api.openstreetmap.org/rails/active_storage/blobs/redirect/...
* https://www.openstreetmap.org/rails/active_storage/blobs/redirect/...
* https://openstreetmap-gps-traces.s3.dualstack.eu-west-1.amazonaws.com/...

**Comment by strukturart** [comment]
> ... know nothing about the framework you're using..

I don't use a framework only JavaScript in the browser (KaiOs)

**Comment by strukturart** [comment]
I have researched further and get an isTrusted:true error message from the amazone server, could it be that amazone has a problem with an outdated browser? my app runs under KaiOs, which uses firefox 48.

https://stackoverflow.com/questions/44815172/log-shows-error-object-istrustedtrue-instead-of-actual-error-data

**Comment by tomhughes** [comment]
I have no idea - you would have to ask Amazon about that.

**Comment by tomhughes** [comment]
That SO question is about executing javascript though so I don't see what it has to do with Amazon?

Whatever problem you're having is in your code and we're not able to help debug everybody's client - that is the job of whoever is writing your code. It's clear that our code is working as expected and is able to deliver the data to a correctly written client.

Using something as old as Firefox 48 is almost certainly a terrible idea for many other reasons of course!

**Comment by strukturart** [comment]
I don't expect you to review my code either, I'm just trying to understand why I'm not getting any data. the authorization is successful, the redirects are followed. does it need certain headers that i have to send along with the query and is the url of the query correct?

`"https://api.openstreetmap.org/api/0.6/gpx/" + id + "/data";`

**Comment by HolgerJeromin** [comment]
The best way to solve this would be a network dump (which is a bit hard because of https).
Or a trace captured with devTools, but this is also hard because this seems to be a mobile browser.

**Comment by tomhughes** [comment]
That is a valid URL yes, whether it's the correct URL for what you want depends on what you want.

I repeat though that it is up to you to debug your client, or to find somebody that is capable of doing so if you do not have the requisite skills yourself. I'm not going to try and debug a javascript client that I have no access to on an ancient version of firefox that I have no access to!

At this point I really don't think there is anything more we can do to help you I'm afraid.

**Comment by tomhughes** [comment]
Just to be clear to anybody reading this in the future this is absolutely not a problem of "security" on the server.

The only problem here appears to be either a very old client or, more likely, an inability to properly debug and understand the client end. It's possible that Firefox 48 is just too old but I can't think of anything off the top of my head that would be needed that it couldn't do so I think it's more likely that you just don't have the tools and/or experience to debug your client properly.

**Comment by strukturart** [comment]
now it worked, the following header was missing: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept

```JS
const headers = new Headers({
      Authorization: n,
      Accept: "application/gpx+xml",
    });
```

maybe it would be useful for other developers to store the information in the documentation of the api.

thank you for your help.
