### ISSUE TITLE
automatic comment in a changeset

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/openstreetmap-website#3513]
### Description

Hi,

I received an automatic comment for a changeset : https://www.openstreetmap.org/changeset/118927040

Several problems :
- the comment is in polish, I'm french, which is visible in my "preference" : maybe you could use the language of the user who created the changeset rather than the language of the place where is the changeset ?
- I didn't change any address : there is an address in the way 964546568 but I just add 2 nodes to this way because I add 2 piers and connected them to the way : if no tag addr is changed, maybe you could not to send any message ?
- the message says that the address is incorrect, I suppose it is because the housenumber is 44A and your automat wanted only a number. But I assume that this "number", with a letter, is correct.

Best regards

**Comment by tomhughes** [comment]
That comment wasn't created by us - there is no code in this repository that adds automatic comments to changesets.

**Comment by tomhughes** [comment]
To be clear that comment was added by the user it is attributed to - whether they used a bot or not I don't no.

Given it was a comment by a polish user about an edit in poland I'm not sure why you think it's unreasonable for them to comment in polish? They have no way of knowing where you are from or what languages you speak.

**Comment by danieldegroot2** [comment]
@Mahabarata Best practice:
- Is there a discussion? **Yes**, they have provided a link in their comment, you can use a translator like DeepL ( https://deepl.com/translator ) or Google Translate ( https://translate.google.com/ ) => **leave a reply on the [dedicated forum thread](https://forum.openstreetmap.org/viewtopic.php?pid=681873)**.
- Can you contact this user? **Yes,**... **but** they do not have any contact info on [their profile](https://www.openstreetmap.org/user/abakus_uploader). And, the user "[abakus](https://www.openstreetmap.org/user/abakus)" does not look active  => You can contact the user "abakus", but **they may not reply**.
-- You can use the 'direct message' button on the profile of "abakus" to send them a message.
- Does this look like spam, vandalism or harassment? **No**, => You do **not** need to report the user.
-- For spam vandalism or harassment, you can use the "Report user" button on the profile of "abakus_uploader". It is recommended you contact them first before reporting them.
-- See also [Reporting spam](https://wiki.openstreetmap.org/wiki/Spam)
- Can you contact the local community? **Yes**, use one of the [contact channels](https://wiki.openstreetmap.org/wiki/Contact_channels). Use a translator to create a copy of your message in Polish, so everyone understands what you are discussing.
- Is it a _technical issue_ with the OpenStreetMap website itself? **No**, messages you receive in comments are not generated by the website. They are always from people or bots - they are never from the website itself. This GitHub repository "OpenStreetMap Website" is for the website itself, i.e. buttons, text style, API, software etc. It is **not** for reporting or discussing individual users.
-- Moderators of the website have a blue star on their OpenStreetMap profile. Note, moderators are also volunteers.

**Comment by Mahabarata** [comment]
Ok, thanks for all these informations.
Best regards
