### ISSUE TITLE
Add rendering for natural=tree_group

### ISSUE THREAD

**Issue by FinixFighter** [openstreetmap/openstreetmap-website#3517]
### Description

The tag natural=tree_group is not much used right now, but I think it is very useful and could be become very used if it is added to the wiki (https://wiki.openstreetmap.org/wiki/Key:natural), so that mappers can find it more easily. 
I often happen to map areas within a city where there are a lot of trees, but these areas are not parks, nor managed forests, and natural=tree_group is the best tag I could find.
A couple of examples are 1)https://www.openstreetmap.org/way/904760959 (more than one group of trees), and 2)https://www.openstreetmap.org/way/1043580038.
A possible rendering could be a light green (same as grass) with trees symbols on it (as on natural=wood).

**Comment by tomhughes** [comment]
When you opened this ticket you were presented with a menu.

One item on that menu was for reporting rendering issues.

Had you chose that item then you would have opened this in the right place.

Sadly you didn't so it's in the wrong place.

**Comment by tomhughes** [comment]
The option you wanted is this one:

![image](https://user-images.githubusercontent.com/147741/160843981-267d23fd-0a32-4b8d-b191-f562f74615e9.png)

If there's something we can do to make that clearer then we'd certainly like to hear about that here.

**Comment by FinixFighter** [comment]
> The option you wanted is this one:
> 
> ![image](https://user-images.githubusercontent.com/147741/160843981-267d23fd-0a32-4b8d-b191-f562f74615e9.png)
> 
> If there's something we can do to make that clearer then we'd certainly like to hear about that here.

OK, I didn't choose that item cause of the "issue" word (I intended it as "bug"/"problem"), I thought this was more like a feature request. Sorry.
