### ISSUE TITLE
Add an Administration Panel 

### ISSUE THREAD

**Issue by A0x01** [openstreetmap/openstreetmap-website#3525]
### Description

Hi OpenstreetMap Team , 
i hope you can add an administartion panel 
where the Admin can add ,edit,delete,give permissions to other users also can change the system setting like the Layers editors etc 
for local organizations 
is this possible ? 
Thank you for the wrok you have dome

**Comment by mmd-osm** [comment]
You're already proposing a solution. Can you describe what problem you're trying to solve here?
* What is a "local organiation"? 
* What permissions are you talking about?
* Who would be an administrator in your case?
* Are you talking about openstreetmap.org or some other site?
* Why do we need this at all?

**Comment by tomhughes** [comment]
This seems to be leaping ahead - until there is something to administer there is no need for an administration panel.

I assume what you're really asking for is something that you would like an administrator to be able to change but in that case that is what you should be opening a ticket about - the way of administering it would simple be an implementation detail of the feature.
