### ISSUE TITLE
Unclear API error message when db is unavailable

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#3530]
For this issue, I wanted to find out what kind of error message a user would get when calling an API endpoint in case the database is unavailable.

Due to #3529, I changed `api_ability.rb `to include an additional check on status "database_readonly"

```
    if Settings.status != "database_offline" &&   Settings.status != "database_readonly"
```

and added `status: "database_readonly"` to my settings.local.yml

When one of the API endpoints http://localhost:3000/api/0.6/node/5004451611, I was expecting to see to error message about an unavailable database. Instead, I'm getting repeated requests to authenticate, which always fails with a HTTP 401 error.

Eventually, the whole process would return a "Couldn't authenticate you" error message without any additional details.

**Comment by tomhughes** [comment]
Well did you authenticate or not?

**Comment by mmd-osm** [comment]
I tried a number of times, both with correct and incorrect credentials, and it would always come back with HTTP 401.

**Comment by mmd-osm** [comment]
Thanks for the fix! API response looks fine now, I'm getting HTTP 503 "Database offline for maintenance". :+1:
