### ISSUE TITLE
Allow querying and requesting deletion of GPS traces

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/openstreetmap-website#3533]
### Description

Currently there a few dozen places where GPS traces have turned into "hairballs". Is it possible to make a feature which allows mappers to query for them (for example by showing them in the sidebar when the user queries for elements and if the GPS layer is enabled or by adding a special option to the context menu just for GPS traces)? Additionally a "Request deletion" button should be added on https://www.openstreetmap.org/user/{user}/traces/{trace_id}.

### Screenshots

https://www.openstreetmap.org/#map=16/42.6848/23.4060&layers=G
![image](https://user-images.githubusercontent.com/19364673/163730553-b5768399-2830-4a48-a970-33d8acf00814.png)
https://www.openstreetmap.org/#map=14/33.0352/-116.9003&layers=G
![image](https://user-images.githubusercontent.com/19364673/163730566-bf2b8b40-6534-4860-9441-6f633e939e2f.png)

**Comment by mmd-osm** [comment]
Even deleting those traces won't help, as changes aren't propagated to the GPS layer yet, see https://github.com/openstreetmap/gpx-updater (there are a few user reports about deleted traces still showing up).

**Comment by tomhughes** [comment]
Firstly we're not about to allow people to delete other people's GPX traces and secondly as @mmd-osm says it makes no difference to the trace layer anyway as it has no way to know that traces have been deleted and even if it did it has no way to drop the data from it's tiles.

**Comment by Dimitar5555** [comment]
The issue with not removed GPS traces which appear on the tiles can be resolved by adding a way to automatically drop cached tiles and regenerate them (or by using vector tiles).

I didn't say that one user should be able to delete another's GPS trace. The text explicitly says "request deletion".

**Comment by tomhughes** [comment]
Well the implication of requesting deletion is that the traces will then be deleted surely? Or are you saying it would send a message to the trace owner asking them to delete it?

Those kind of noise areas are not usually separate traces anyway - typically those are just part of a larger trace where a user has stood still for a while.

**Comment by Dimitar5555** [comment]
It depends on the trace. If it's just "hairball" of points, then yes deletion is the best solution. If only a part of it is like that, the uploader can change it (iirc there was an option to edit traces).

**Comment by tomhughes** [comment]
There are no tools on the web site for editing traces - you can edit the description and tags but not the trace data.

So in summary you want us to implement something to send a request to trace owners asking them to delete or edit their traces, which most of them will probably ignore, in the hope that somebody will then volunteer to take over the long abandoned code for the trace tiles and somehow find a way to rebuild them when a trace is deleted, which would also require us to publish some sort of feed of deleted/edited traces that it could react to.
