### ISSUE TITLE
MinervaNeue skin has issues with ValueDescription template (maybe other things too)

### ISSUE THREAD

**Issue by endim8** [openstreetmap/openstreetmap-website#3538]
### URL

https://wiki.openstreetmap.org/wiki/Tag:building%253Dhouse

### How to reproduce the issue?

1. change your wiki skin to MinervaNeue in preferences
2. go on a page that uses the ValueDescription template

MinervaNeue is overriding the `float: right` for some reason.

### Screenshot(s) or anything else?

<img width="298" alt="Screenshot 2022-04-28 at 22 55 48" src="https://user-images.githubusercontent.com/26939824/165854563-dea87a96-4756-45fd-9f4b-2e03b90c1599.png">
<img width="569" alt="Screenshot 2022-04-28 at 22 05 36" src="https://user-images.githubusercontent.com/26939824/165854861-f497971d-a7ce-486a-a067-f0471ed69310.png">

**Comment by tomhughes** [comment]
This repository is for www.openstreetmap.org not wiki.openstreetmap.org - the wiki runs on the third party mediawiki software (the same software as wikipedia) so the technical details of the code are outside our control and would need to be reported to the appropriate mediawiki bug tracker.

**Comment by tomhughes** [comment]
As this is an operational issue I'm going to move it to the operations tracker.
