### ISSUE TITLE
Vertical black bar(s) when escaping text input while typing

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/openstreetmap-website#3541]
### URL

_On any (menu / sidebar) window_

**Expected behaviour**
No element focus is shown when escaping an element. I personally don't see the element focus being very useful to the user.
The window they were looking at was not closed, so they can easily continue typing / interacting with it, without having to worry where it is located.
- This behaviour does not happen when closing a note.
- If a developer wants to inspect a specific element, they can right click => inspect on said element.

**Observed behaviour**
It seems like escaping an element causes element focus to be shown on the parent element(s).

### How to reproduce the issue?

Happens in general if holding any key (you are not required to be in a text input), or if after clicking on the map any key is pressed. Also on changesets, map notes and the URL bar (aka any text input), clicking the map while typing will make (a) vertical black bar(s) appear alongside -on the side of the map- any open (changeset, map notes, history, layers) window. Clicking anywhere will make it/them disappear. Both when browser window is max and not maximized.
Does _not_ appear if no window is open (aka to the right of the browser window's edge). Both when browser window is max and not maximized.
Does _not_ disappear by zooming in/out.
Does _not_ appear on openhistoricalmap.org deployment. (I'm aware this is seperate, just checking)

Simple way to reproduce it is by holding down a single key to keep typing and then clicking on the map.

![image](https://user-images.githubusercontent.com/67521919/166309054-fbe770d5-094b-4435-a96d-b50304aa28ca.png)

- This also happens when F12 (dev console) is pressed.
- If a note is open and F12 is toggled on/off, the note will occasionally be highlighted*
(* this is the same behaviour as if the user has navigated to it using the keyboard (with `TAB`) to focus on the element.)

![image](https://user-images.githubusercontent.com/67521919/197539271-cdf76c48-8c3c-4431-889f-15322922fd61.png)

Browser(s): Chrome

**Comment by mmd-osm** [comment]
I don’t see how this is impacting real end  users. I vote for closing.

**Comment by danieldegroot2** [comment]
In case something similar comes up, there was a PR in regular Leaflet which should prevent it from happening.
https://github.com/Leaflet/Leaflet/pull/9393
