### ISSUE TITLE
Welcome message buttons don't adjust to long translations

### ISSUE THREAD

**Issue by deevroman** [openstreetmap/openstreetmap-website#3545]
### URL

openstreetmap.org

### Screenshot(s) or anything else?

![SCR-20220508-pdo](https://user-images.githubusercontent.com/25708359/167303094-4724428f-c707-498a-8afc-a8f733a3ec07.png)

**Comment by gravitystorm** [comment]
It might be possible to improve this using bootstrap button groups, but that will need some experiments.
