### ISSUE TITLE
Ability to change the language of the map

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [openstreetmap/openstreetmap-website#3547]
### Description

I want to see the map in Persian and the names of countries, cities, POIs and streets should also be displayed in Persian, those that do not have a Persian name (tag name: fa) should be displayed in their local language

**Comment by HolgerJeromin** [comment]
This is the wrong repo here.
With the many languages we need vector tiles for that.
See https://github.com/gravitystorm/openstreetmap-carto/issues/3201 for more information
