### ISSUE TITLE
Move third-party login to top

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/openstreetmap-website#3550]
### Description

I think that the third-party login methods should be moved above the standard login fields because users are more-likely to have such accounts and therefore login and proceed to edit OSM with them. This is also important because on mobile they are even less-noticeable in their current position.

### Screenshots

![image](https://user-images.githubusercontent.com/22477298/168452520-bc24541c-5ed7-4202-a4aa-a8b16b3a2c68.png)

**Comment by dieterdreist** [comment]
I don’t know whether people are more likely to have these accounts, but we should not make it appear as if these were the preferred login options. For our users it is best to use a dedicated OpenStreetMap login so that their login habits are not shared with a third party

**Comment by lectrician1** [comment]
Today, I had a friend create an OSM account and I literally pointed out to them that they could create one with Google and they didn't see the logo until I physically pointed it out to them out the existence of it on the login page. It's clearly not in a visible place.

We should run an A/B test seeing if putting the login logos above yields a greater number of account creations than at the bottom.

**Comment by tomhughes** [comment]
We do not have any ability to run A/B tests currently, so adding that would be a major undertaking before we could run any specific test.

I tend to agree with @dieterdreist though - there are other things that are important beyond getting the maximum number of signups and we're not a startup that needs to juice fake numbers for the next investment round.

**Comment by pnorman** [comment]
Since we're looking at the login form, we could look at existing accounts.

**Comment by tomhughes** [comment]
Look at them for what?

**Comment by lectrician1** [comment]
To see what proportion of active accounts have linked third party accounts.

**Comment by tomhughes** [comment]
How do we determine what is an "active" account exactly? If you just mean accounts that are currently open then:

```
  provider   |  count  | percentage 
-------------+---------+------------
 wikipedia   |    2900 |          0
 windowslive |    7148 |          0
 github      |   16379 |          0
 openid      |  189114 |          2
 facebook    |  443209 |          4
 google      |  756662 |          8
             | 8009956 |         84
```

What I don't understand is what conclusion we are supposed to draw from that - are we supposed to infer that having an linked account is better than not having one in some way?

**Comment by lectrician1** [comment]
Exactly. This isn't really a useful statistic.

**Comment by pnorman** [comment]
We can conclude most people don't have linked accounts, so we shouldn't put them on the top of the log in form.

**Comment by lectrician1** [comment]
Given that third party logins haven't always been around and there are only [~5500 active accounts ](https://osmstats.neis-one.org/?item=members&date=16-11-2022) which is 0.5% of the overall number of accounts, you can't make that statement. We're trying to find the impact moving it to the top will have, not whether people have used it in the past or not.

**Comment by simonpoole** [comment]
> Given that third party logins haven't always been around and there are only [~5500 active accounts ](https://osmstats.neis-one.org/?item=members&date=16-11-2022) which is 0.5% of the overall number of accounts, you can't make that statement. 

Just for the record: you are reading that statistic wrong. OSM has ~5'500 unique active users on a per day base, ~45'000 per month and ~300'000 annually.

**Comment by mmd-osm** [comment]
Closing, since no one else supported the idea.
