### ISSUE TITLE
Third party login error (WordPress and Aol)

### ISSUE THREAD

**Issue by steincavelaars** [openstreetmap/openstreetmap-website#3555]
The third party login options for WordPress and Aol on [https://www.openstreetmap.org/login](url) fail with the following error: "Connection to authentication provider failed". Issue #1966 from 2018 briefly mentioned this problem when logging in with Yahoo was still an option too.

**Comment by tomhughes** [comment]
Do either of those still support OpenID? Chances are that they have dropped it and that's why it doesn't work.

**Comment by tomhughes** [comment]
I can't find anything about either of them dropping it but I also kind find anything recent about either of them offering it and neither seems to be including the relevant link attribute in their home page so I guess they've dropped it.

**Comment by steincavelaars** [comment]
Thanks Tom, that's some fast action!
