### ISSUE TITLE
Something went wrong with notes API

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#3558]
Code that used to work well to close notes stopped working

https://api.openstreetmap.org/api/0.6/notes/1000/close?text=Comment example from https://wiki.openstreetmap.org/wiki/API_v0.6#Close:_POST_/api/0.6/notes/#id/close also fails with the same error (instead of expected complaint of closing already closed note https://www.openstreetmap.org/note/1000 )

> Couldn't find a file/directory/API operation by that name on the OpenStreetMap server (HTTP 404)

so I suspect that it is not a bug in my code

**Comment by mmd-osm** [comment]
@matkoniecz : I tested your example in Postman, and I got a HTTP 409 error with the following error message in the response body: "The note 1000 was closed at 2018-04-18 08:24:56 UTC". This looks all fine to me.

If you're getting HTTP 404, you're most likely not using POST, as @tomhughes already mentioned. If you're clicking on the link provided on the OSM API wiki page, you'll trigger a GET request, which obviously won't work. Maybe we should simply fix the wiki page...

**Comment by matkoniecz** [comment]
Additional confusion: OSM Wiki doc claims that a different error should happen in case of not using POST:

> HTTP status code 405 (Method Not Allowed)
>    If the request is not a HTTP POST request

which appears to be either wrong or there is a bug

In addition, I am now highly confused why my code for closing notes stopped working (it used to work - see https://www.openstreetmap.org/user/Mateusz%20Konieczny%20-%20bot%20account/notes which closed wave of troll notes)

**Comment by tomhughes** [comment]
Yes in principle 405 might be more correct but rails treats the method as an argument to the routing algorithm (so the same URL might route to different methods for different methods) and as a result generally gives 404 when there is no matching route for any reason.

**Comment by mmd-osm** [comment]
> which appears to be either wrong or there is a bug

I changed parts of the OSM API wiki talking about notes/* endpoints and removed all hyperlinks pointing to POST endpoints, and also replaced the HTTP 405 by 404. I know that cgimap does send out some 405. That's why I don't want to change anything beyond notes/* at this time.
