### ISSUE TITLE
open links in notes in new tab as default

### ISSUE THREAD

**Issue by jf-simon** [openstreetmap/openstreetmap-website#3567]
### Description

it would be nice, if link in notes are been opened in new tab as default.
for example through streetcomplete there are often links to images.
so i could better "browse" notes without loosing my map view.

thanks

**Comment by tomhughes** [comment]
I disagree. I hate it when web sites force a new tab instead of allowing me to choose whether to open in the same tab or a new one.

**Comment by HolgerJeromin** [comment]
Tom is not alone here:
https://blog.tbhcreative.com/2015/07/pros-and-cons-of-opening-links-in-new-window.html

**Comment by FloEdelmann** [comment]
Another list of pros and cons: https://css-tricks.com/use-target_blank/

**Comment by 10992-osm** [comment]
Something some sites do is allow users (at least when logged in) to have a setting for what they want their default open-mode to be, but that might be adding unnecessary complexity.

**Comment by mmd-osm** [comment]
It seems the majority of people here want to keep it as is.
