### ISSUE TITLE
Allow loading of map image tiles from other domains

### ISSUE THREAD

**Issue by CorruptComputer** [openstreetmap/openstreetmap-website#3572]
### Description

When trying to load tiles from a custom tile server, the following CORS validation error is thrown on osm.org:

> Refused to load the image 'https://a.tile.openstreetmap.de/19/139398/209119.png' because it violates the following Content Security Policy directive: "img-src 'self' data: www.gravatar.com *.wp.com tile.openstreetmap.org *.tile.openstreetmap.org *.tile.thunderforest.com tileserver.memomaps.de *.openstreetmap.fr piwik.openstreetmap.org https://openstreetmap-user-avatars.s3.dualstack.eu-west-1.amazonaws.com https://openstreetmap-gps-images.s3.dualstack.eu-west-1.amazonaws.com".

I was able to trace this rule back to this line of this file:
https://github.com/openstreetmap/openstreetmap-website/blob/1612ea75c541016ff8c4312935e8bfc4462608c6/config/initializers/secure_headers.rb#L10

Images are unlikely to contain malicious content, and this rule reduces the functionality of the website by disallowing folks to use their own tile servers with osm.org. Would it be possible to allow images to load from custom tile servers here?

Found this Mozilla documentation for doing this in apache, not quite sure how this would translate to Rails but CORS does support this: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image#web_server_configuration

Currently, I am using the [Switcheroo](https://github.com/ranjez/Switcheroo) extension to test this on behalf of SomeoneElse who brought this issue up in the OpenStreetMap World Discord server. This extension was removed from the Chrome web store, but you can just load it as loose files if you want to test it as well. I had to tweak a couple of broken functions to get it to work, so if you run into issues let me know and I can give you the changes I did there.

### Screenshots

![image](https://user-images.githubusercontent.com/5573038/173872533-9d4a68f8-7d31-4977-a9a9-b1f7c7152ec1.png)

**Comment by Firefishy** [comment]
Could you include what link you are getting these errors from?

**Comment by CorruptComputer** [comment]
Tested this here: https://www.openstreetmap.org/#map=17/34.17969/-84.28230

Though the same error probably won't show for you without using that extension or some other similar extension, I am specifically trying to replace the default osm.org tiles with custom ones via an extension.

**Comment by mmd-osm** [comment]
I ran into the same issue a while ago when trying to switch to a custom Overpass API instance, replacing the one used on osm.org. The CSP directive pretty much blocks all those attempts, and Switcheroo has a pretty hard time to work around that.

**Comment by pnorman** [comment]
The website doesn't support substituting arbitrary tile servers. If this is a feature we want, we should add it properly, not rely on people using extensions. if it's not something we're going to support, then I don't see anything wrong with the way it is right now.

**Comment by tomhughes** [comment]
Firstly that is not CORS that is CSP.

Secondly we declare all the servers we use - if you decide to patch the site in your browser that you get to pick up the pieces. We're not going to reduce security for all our users just so you can play silly buggers.
