### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by JamieSlome** [openstreetmap/openstreetmap-website#3590]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@jhond0e) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by tomhughes** [comment]
Technically that's the policy for operations but it works fine - we don't have a good answer for what to put in SECURTITY.md for this repository yet or we would have created it.

**Comment by tomhughes** [comment]
Duplicate of #3553.

**Comment by JamieSlome** [comment]
@tomhughes - no worries, and thanks for your response :)

In any case, you can find the report we received here:
https://huntr.dev/bounties/4b42d833-8ae8-4fc2-9b79-7b833b4140d3/

It is private and only accessible to maintainers with repository write permissions 👍 

Also, we do currently sponsor bounties against your repository, so you can always put the following in your `SECURITY.md`:
https://huntr.dev/repos/openstreetmap/openstreetmap-website/
