### ISSUE TITLE
Leading and trailing spaces in traces tags

### ISSUE THREAD

**Issue by AntonKhorev** [openstreetmap/openstreetmap-website#3596]
### URL

https://www.openstreetmap.org/traces/new

### How to reproduce the issue?

Is it supposed to be possible to have leading and trailing whitespace in tags? I suspect that not because the tag string is split by this regexp: `/\s*,\s*/`. It will strip leading/trailing spaces from everything in the middle but not leading spaces from the first tag and trailing spaces from the last one.

1. go to *upload gps trace* page
2. set tag input to something like <pre>               1,2,3                  </pre>
3. set everything else to valid values and upload a file
4. after successful upload see what the tag links look like

Example:
https://master.apis.dev.openstreetmap.org/user/ankhtest1/traces/2041

**Comment by tomhughes** [comment]
I don't suppose anybody has ever given it an iota of thought, because why would anybody do that.

**Comment by HolgerJeromin** [comment]
If you enter the value via copy and paste could easy add white spaces before and after the intended words.

**Comment by AntonKhorev** [comment]
> I don't suppose anybody has ever given it an iota of thought, because why would anybody do that.

So the answer is "no, tags are not supposed to have leading/trailing spaces"?

**Comment by gravitystorm** [comment]
> So the answer is "no, tags are not supposed to have leading/trailing spaces"?

That's correct. I'd be happy to see a PR that fixes this.
