### ISSUE TITLE
Selected multipolygons are not rendered correctly filled

### ISSUE THREAD

**Issue by Sinuhe20** [openstreetmap/openstreetmap-website#3600]
### URL

https://www.openstreetmap.org/relation/14358790

### Expected behavior
Selected multipolygons should be filled correctly (without the inner holes). Selected multipolygons should be rendered as true multipolygons.

### Actual behavior
Selected multipolygons are not filled correctly or are not really rendered as multipolygons. It looks like each member (inner or outer line) is rendered individually.

### Links and screenshots illustrating the problem
Two temple sites with almost the same attributes, the one as way (Luxor) is filled, the other as multipolygon (Karnak) not:

- https://www.openstreetmap.org/way/1079039494 (filled)
- https://www.openstreetmap.org/relation/14358790 (not filled)

Overpass turbo renders multipolygons correctly filled:

https://overpass-turbo.eu/s/1kaj

And it seems not be related to the complexity of the outline:

https://www.openstreetmap.org/relation/2017780 (also not filled)

Another example, which works wrong in the other direction:

https://www.openstreetmap.org/relation/6713255

A multipolygon, where all areas, even the inner holes are filled. I think this can be related to the landuse property set or area=yes. Looks like all members are rendered individually and only their tags are considered, but not that of the multipolygon.
In my opinion selected multipolygons should all be rendered in the same way with the inner holes empty and the rest filled, no matter which tags are set.

**Comment by tomhughes** [comment]
This is outside our control - we use the `dataLayer` from https://github.com/openstreetmap/leaflet-osm to render the overlays so you get whatever it gives.

To be honest I'm not sure leaflet even has a way to render multipolygons.

**Comment by Sinuhe20** [comment]
Ok, so I hope this data layer can be improved. The relations and ways are referenced by Wikidata and it would be good to have multipolygons filled in the same way like normal polygons.

**Comment by woodpeck** [comment]
I think it is not a good idea to reference anything on the OSM API from Wikidata. Firstly, we cannot take the role of a geodata storage engine for Wikidata - we're already seeing all sorts of rubbish added to OSM just to satisfy someone's desire to make some kind of link. (By "rubbish" I mostly mean things that cannot be verified on the ground.) Secondly, our object IDs can change at any time, breaking any such link that may have been created. Thirdly, we can't spend our volunteer time to fix things "because Wikidata needs it". We have too little of it (volunteer time) as it is.

**Comment by Sinuhe20** [comment]
@woodpeck 

I think referencing is very important - in both directions - you're also referencing Wikidata objects and Wikipedia articles (even images and wikicommons categories). There's also a lot of volunteer work behind it and the same problems faced like deleted objects. I see no reason why OSM objects cannot be linked as stationary objects. Sure, there are some deletions, but it is recommended to keep the objects with their history. With the lastest [Kartographer extension](https://de.wikipedia.org/wiki/Wikipedia:Kartensaison/Kartographer) we also see OSM objects integrated directly into articles.

**Comment by AntonKhorev** [comment]
> To be honest I'm not sure leaflet even has a way to render multipolygons.

I think it can with its Polygon class, but you'll have to sort and collect way segments into rings and find inner rings corresponding to outer rings yourself.
