### ISSUE TITLE
Translation error in Swedish; väg -> sätt

### ISSUE THREAD

**Issue by turepalsson** [openstreetmap/openstreetmap-website#3614]
### URL

https://www.openstreetmap.org/node/8354741193

### How to reproduce the issue?

Make the website display its Swedish translation (not sure how to do this; it "just happens" for me). Look at the URL indicated above. Probably any node that is a member of exactly one way will do.

Text says "del av" (part of) "1 sätt". Now, "sätt" can mean "way", in the the metaphorical sense of "two ways of doing things", but it cannot mean "street" or "road". I believe the usual translation for the OSM "way" concept is "sträcka" (plural "sträckor").

### Screenshot(s) or anything else?

<img width="651" alt="Skärmavbild 2022-07-22 kl  08 58 49" src="https://user-images.githubusercontent.com/14193668/180383007-3dce5ced-2003-42ed-8542-ce76f1297cdb.png">

**Comment by tomhughes** [comment]
Translations are handled through TranslateWiki so this will need to be fixed there - see https://wiki.openstreetmap.org/wiki/Website_internationalization#How_to_translate for how to help.
