### ISSUE TITLE
Keyboard navigation: Focus directly on and highlight selections in right click menu when open

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/openstreetmap-website#3635]
### Description

On right click,
- set tabbing to focus on the right click menu. Tabbing will then select the second/next item in the right click menu. This is the case at least for Google Maps, Bing Maps, ... .
- add a highlight for selections within the right click menu (at least, those other map providers do)

Currently, when the right click menu is open, 
- Tab goes through the normal cycle (the page as a whole is being selected); also when routing 
- Eventually selects within the tab menu but has no highlights so the user is not, at least not visually, aware of this.

Google:

![image](https://user-images.githubusercontent.com/67521919/181639317-cd99e9aa-4d8f-46a6-8fd4-1bc795f8cdbd.png)

Bing:

![image](https://user-images.githubusercontent.com/67521919/181639937-14becccb-253d-4d78-9030-d44e2a52b249.png)

(the url preview in the bottom left corner of the browser doesn't update properly, but let's not try to troubleshoot this unless you really want to)

**Comment by tomhughes** [comment]
The context menu is a third party component (https://github.com/aratcliffe/Leaflet.contextmenu) and as far as I can see it does not offer any option to control this behaviour.

**Comment by danieldegroot2** [comment]
Partial duplicate of https://github.com/aratcliffe/Leaflet.contextmenu/issues/135.
