### ISSUE TITLE
Mouse navigation: Moving out of map window removes right click menu

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/openstreetmap-website#3636]
### How to reproduce the issue?

Moving out of the map window with the mouse removes the right click menu, eventhough I did not click anywhere or on anything else.

I'd personally expect the right click menu to remain active for ease in navigation (no additional clicks) when I come back to it.

**Comment by tomhughes** [comment]
The context menu is a third party component (https://github.com/aratcliffe/Leaflet.contextmenu) and as far as I can see it does not offer any option to control this behaviour.

**Comment by Firefishy** [comment]
@danieldegroot2 What browser are you seeing the issue with? The right click context menu only is available for me over the map area.

PS: To get the normal right click menu, hold down the shift key while right clicking.

**Comment by tomhughes** [comment]
I assumed that the map area was what he meant by "map window" but as I say that behaviour is builtin to the leaflet plugin we use I think.

**Comment by tomhughes** [comment]
Specifically https://github.com/aratcliffe/Leaflet.contextmenu/blob/master/src/Map.ContextMenu.js#L57 which registers a `mouseleave` handler the map that hides the menu.

**Comment by danieldegroot2** [comment]
Duplicate of https://github.com/aratcliffe/Leaflet.contextmenu/issues/70.
