### ISSUE TITLE
Keyboard navigation: Add close and reverse buttons as selectable in routing

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/openstreetmap-website#3637]
### Description

Add the close and reverse buttons as selectable in the routing window using the Tab key.

Currently, when pressing tab, only the input fields and OK button can be selected. The user can not close out of routing (nor deselect with Escape) nor select the reverse directions link.

**Comment by gravitystorm** [comment]
Close button was completed in #3631 and reverse directions is addressed in #3644

**Comment by gravitystorm** [comment]
Thanks for the report! This is now fixed.
