### ISSUE TITLE
Diary comment "save" text misleading

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/openstreetmap-website#3650]
### URL

https://www.openstreetmap.org/user/pnorman/diary/399680#comments

### How to reproduce the issue?

The diary comment page uses "Save" for posting a diary entry comment. This is somewhat misleading, as what's happening is posting or publishing, not saving, which could be saving a draft for working on later.

The new diary entry page uses "Publish", while changeset discussions use "Comment".

A consistent term across all three would be beneficial. 

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/1190866/182719564-b1a93813-40b5-452b-bd2c-529fa4c6723c.png)

**Comment by gravitystorm** [comment]
By default Rails will create appropriate text for submission buttons, based on the model, e.g. "Create Diary Comment". When they aren't suitable we can easily override these in the "en.helpers.submit" section of the translations file:

https://github.com/openstreetmap/openstreetmap-website/blob/d3388abe51a946ae0abc645d831a93b1b2cc6749/config/locales/en.yml#L11-L35

There's also a few other overrides that, for unimportant reasons, appear elsewhere in the file, e.g. Changeset Comments:

https://github.com/openstreetmap/openstreetmap-website/blob/d3388abe51a946ae0abc645d831a93b1b2cc6749/config/locales/en.yml#L2869

For comment submit buttons we currently have:

* "Comment" (Changeset Comments)
* "Add Comment" (Issue Comments)
* "Comment" (Note Comments)
* "Save" (Diary Comments)

I agree "Save" isn't a good term to use. I don't think it necessarily needs to be consistent with new Diary Entries though.

**Comment by ZhengLin-Li** [comment]
hi, @gravitystorm, I am new and interested in contributing to this project. I saw you add a `good first issue` label. Would this problem still need to be fixed? I'd like to give it a try.

**Comment by gravitystorm** [comment]
@ZhengLin-Li yes, this still needs to be fixed. You are welcome to work on fixing this!

**Comment by gravitystorm** [comment]
Fixed by #3864
