### ISSUE TITLE
Issues - "Reassign Issue" results in a 404

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/openstreetmap-website#3652]
### URL

Any issue on https://www.openstreetmap.org/issues?status=open

### How to reproduce the issue?

For context, I'm a [moderator](https://www.openstreetmap.org/user/SomeoneElse) on osm.org.

The specific example was with https://www.openstreetmap.org/issues/21488 .

I've been dealing with the "DWG" aspects of the issue, but a request came in to hide a link from the users profile page, which (rightly) isn't something that moderators can do, so typed a comment in the box, ticked the "Reassign Issue?" box and clicked "Add Comment".

I'm then shown https://www.openstreetmap.org/404 , possibly because https://www.openstreetmap.org/issues/21488 isn't in the moderators' queue any more, but the admins'.

**Comment by tomhughes** [comment]
Given that I do this all the time I'm well aware of it.

Technically it is correct (well 403 might be more accurate but due to the way rails works you tend to get 404 for pages you're not allowed to see).

What would you like it to do?

**Comment by SomeoneElseOSM** [comment]
Perhaps the same "your report has been sent" green bar as "Report this User" on a user profile, followed by a redirect to https://www.openstreetmap.org/issues?status=open ?
