### ISSUE TITLE
 Add ability for site moderators to hide a user profile

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/openstreetmap-website#3654]
### How to reproduce the issue?

n/a

### Screenshot(s) or anything else?

For completeness, this is touched on, but not exactly described by some of the issues at https://github.com/openstreetmap/openstreetmap-website/labels/moderation

It also forms "3.3 Ability to Hide User Profile" in "dwgwishlist.pdf" which has been discussed with the EWG.  The relevant text from that PDF is:

DWG needs to be able to hide a user profile that contains objectionable content. A hidden profile
should show a generic note (“this user profile is currently hidden”). That way, DWG could force
someone to remove objectionable content before releasing the profile again. The user must still be
able to edit his profile while hidden.
Priority: High, as extremly problematic content would currently require manual SQL from
sysadmin

An example is https://www.openstreetmap.org/user/OpenVandalMap .
(that link is now benign, having been since removed by Weebly/Square/Block)

A user profile was created for the sole purpose of vandalism and trolling.
The user was blocked, and edits reverted.
What remains is the user's changeset comments (just 1 in this case) and the user's user profile.
In this example I believe it would be appropriate to hide the user's profile.

Andy, from the DWG

**Comment by tomhughes** [comment]
Since when did DWG become the general moderators of what is and is not acceptable content?

They're the DATA WORKING GROUP not the WWW.OPENSTREETMAP.ORG MODERATION GROUP.

**Comment by SomeoneElseOSM** [comment]
@tomhughes First things first, can I suggest that you look again at the tone of your reply, and see how well it fits (or doesn't) with https://wiki.osmfoundation.org/wiki/Etiquette ?  We're all supposed to be on the same side here, volunteers working together to make the project happen.  Please don't make that any harder than it needs to be.

Secondly, to be clear, I said "site moderators" in the issue title.  As you know (but others may not) this is actually a role within the website (see for example the blue star against e.g. https://www.openstreetmap.org/user/SomeoneElse that says "This use is a moderator" and the orange one against e.g. https://www.openstreetmap.org/user/TomH that says "This user is an administrator").  Website moderators currently have the ability to hide various other items of problematic content (notes, diary and changeset comments etc.), as well as performing data redaction e.g. for licence reasons.  Currently most DWG members are also website moderators.

Thirdly, you've closed this as "completed".  In what way is that the case?  Do you mean that:

* the technical ability to hide a user profile exists, but I don't know how to do it or how to ask for it to happen?
* the technical ability to hide a user profile exists, but some other body (the board?  the LCCWG or similar?) ought to be the final arbiter or what should or shouldn't be allowed in a user profile?
* you don't think that the technical ability to hide user profile content should exist at all?

Regardless of whichever of those three you believe to be the case, I'm sure that anyone from the DWG is happy to discuss your concerns.(looping in the board if appropriate).

**Comment by attilakundev** [comment]
@tomhughes https://www.openstreetmap.org/user/MedwedianPresident%E2%A0%80 see this and you'll understand why we mean this.

**Comment by attilakundev** [comment]
+ most of the vandalism is reverted by DWG members like Frederik Ramm, and mostly when we report users AFAIK it's better to report to `data@openstreetmap.org`, because you'll get an answer faster than clicking on "Report this user".

**Comment by tomhughes** [comment]
As much as we may have a role of "site moderator" that is currently directly equivalent to being a DWG member.

If you want to suggest creating an additional role with wider ranging powers (and perhaps renaming the current "site moderator" to better indicate what it represents) then fine, but before we get into the technical details we need a community process for deciding who gets this power, what policies they are applying, what the route of appeal is for anybody that is subject to their powers, etc, etc.

**Comment by tomhughes** [comment]
Yes sure that account is an idiot. Should their views be censored? I'm not at all sure about that.

**Comment by berrely** [comment]
> Yes sure that account is an idiot. Should their views be censored? I'm not at all sure about that.
I would not deem a user using derogatory and racist language “censorship”. Providing remedies for a user whom has agreed to a terms of use is full acceptable, and arguing that doing so is censorship is wrong.

To my knowledge, a “moderator” is someone who moderates content. Moderation includes, and is not limited to, removing content that infringes the set rules. That is in no way unreasonable.

If you want to argue that it's best to get consensus from the community beforehand, then that's a valid point, as this is a wide-ranging change. But please don't cast aspersions on members of the DWG as thought police.

**Comment by woodpeck** [comment]
Ok, so at the very least there's an imbalance here. The DWG can already hide notes, or changeset discussions, or user profile discussions. I have done that occasionally when discussions became too heated, or when, in spite of us asking them not to, users brought up the same topic again and again in unrelated changeset discussions. I'm not aware of us using these features on a grand scale but we sometimes use them in the course of defusing a conflict. 

Being able to change or hide user profile text (as well as changeset comments which is a different issue and more pressing because not even the user themselves can hide them, and users sometimes accidentally reveal private information) are two tools currently missing from the DWG's toolbox and there have been situations where we would like to have used them to help defuse a conflict. These tools would surely make a sensible complement to the already existing ones mentioned above. 

Should the DWG wield these tools, or should some other body? I don't mind much; speaking as a DWG member, if there was a group to whom we could offload "user XY is annoying other mappers with their comments, please deal with that" and they could be trusted to deal with it efficiently, I don't see a problem.

The only way to make unwanted content on a user diary page go away (content of which the OSMF is the publisher) is currently for an admin to delete/disable the user account altogether. This is a drastic measure, especially if you would like to give the user the opportunity to rectify the situation. Hence the suggestion of being able to "hide" a profile without deleting/disabling the user account.

Users affected by a DWG action have the option of appealing to the OSMF board and this is a process that has been tried and tested so I'm not too worried there.

**Comment by tomhughes** [comment]
> To my knowledge, a “moderator” is someone who moderates content. Moderation includes, and is not limited to, removing content that infringes the set rules. That is in no way unreasonable.

Sure, but where are the "set rules" for what is and is not allowed in an openstreetmap.org user profile? I'm not aware of any...

**Comment by tomhughes** [comment]
> Ok, so at the very least there's an imbalance here. The DWG can already hide notes, or changeset discussions, or user profile discussions. I have done that occasionally when discussions became too heated, or when, in spite of us asking them not to, users brought up the same topic again and again in unrelated changeset discussions. I'm not aware of us using these features on a grand scale but we sometimes use them in the course of defusing a conflict.

There is no such thing as a "user profile discussion" so I'm not sure what you mean by that.

> The only way to make unwanted content on a user diary page go away (content of which the OSMF is the publisher) is currently for an admin to delete/disable the user account altogether. This is a drastic measure, especially if you would like to give the user the opportunity to rectify the situation. Hence the suggestion of being able to "hide" a profile without deleting/disabling the user account.

Not true. I can (and sometimes do) hide an individual diary entry or comment.

> Users affected by a DWG action have the option of appealing to the OSMF board and this is a process that has been tried and tested so I'm not too worried there.

Yes and we know what a *** up they created with one of those appeals...

**Comment by SomeoneElseOSM** [comment]
> Yes sure that account is an idiot. Should their views be censored? I'm not at all sure about that.

I linked to that as an example precisely because it was no longer a risk for people to browse there (after Weebly pulled the content off their site).  *Before* Weebly pulled that content, if it had been dangerous for people to browse to it, it would *absolutely* have made sense for OpenStreetMap to hide the user profile content.

I can think of other current examples (which I obviously won't link to here) that are some way along the line between ("that just says that the user is an idiot" and "that ought to be hidden").  

> but where are the "set rules" for what is and is not allowed in an openstreetmap.org user profile?

The fact that "there are no set rules" doesn't mean that "anything is allowed" - it just means that decisions need to be made on a case by case basis, by human beings capable of understanding nuance and intent.

As to who makes the decision, I agree with Frederik and I really don't mind, provided that they could be trusted to deal with it efficiently.  That's why I mentioned the board and the LCCWG (who have that role on a couple of mailing lists, per https://wiki.openstreetmap.org/wiki/Etiquette/Process_for_Moderation ) earlier.

**Comment by tomhughes** [comment]
And yes I'm very well aware that I basically in exactly the position I'm criticising right now, which is exactly why, other than spam, it is very rare for me to take action.

As far as I can tell from the reports I see many of our users are pretty thin skinned and expect us to ban people for the most trivial of perceived offences and I'm concerned that we don't wander into a situation where we are doing exactly that.

**Comment by SomeoneElseOSM** [comment]
> As far as I can tell from the reports I see many of our users are pretty thin skinned and expect us to ban people for the most trivial of perceived offences and I'm concerned that we don't wander into a situation where we are doing exactly that.

Agreed - and on a number of occasions I've suggested to people that changeset comments talking about them are best left as they are because they say rather more about the commenter than the person being commented upon.  

However, there are examples (such as the link to a racial slur from one of the profiles mentioned earlier**) where other action may be appropriate, and yes, as Frederik and I have both said, this needs to be done in an accountable way.

** it's likely that Google/Youtube will in time pull that content too.
