### ISSUE TITLE
App is rendering the standard map tiles, but i want that only shows the portion of the map that I imported to my DB

### ISSUE THREAD

**Issue by victorovento** [openstreetmap/openstreetmap-website#3656]
I m developing a local instance of Openstreetmap, and I only want that the user only can see the portion of map I imported using Osmosis:

Osmosis imported the map to the DB correctly:
![image](https://user-images.githubusercontent.com/85527043/184956129-b75ec1f3-3738-47e6-a003-51aa36dda9a1.png)

How can I do that my OSM ignore the the standard map tiles?

**Comment by tomhughes** [comment]
You need to run your own tile server and change `app/assets/javascripts/leaflet.map.js` to use layers provided by that server.

Help with running a tile server is outside the scope of this repository, but https://switch2osm.org/ may be of help.

**Comment by victorovento** [comment]
Thanks ❤️❤️

**Comment by mmd-osm** [comment]
https://community.openstreetmap.org/help would be a good place for follow up questions, in case you get stuck somewhere.

**Comment by victorovento** [comment]
What I need is that the website only render the OSM data I previously imported with osmosis. I am very confused please help...

**Comment by tomhughes** [comment]
We are not able to provide that help here - please use the resources that we have already suggested to ask for help on how to render your own maps.
