### ISSUE TITLE
Netherlands license has dead link

### ISSUE THREAD

**Issue by hiddewie** [openstreetmap/openstreetmap-website#3658]
### URL

https://www.openstreetmap.org/copyright

### How to reproduce the issue?

Open the copyright page.

The copyright notice about data in the Netherlands contains

> Netherlands: Contains © AND data, 2007 ([www.and.com](https://www.and.com/))

The link is dead. 

From https://blog.openstreetmap.org/2007/07/04/and-donate-entire-netherlands-to-openstreetmap/ it seems that the organization is currently called GeoJunxion since 2020, https://www.geojunxion.com/.

The relevant key in the translation files is `contributors_nl_html`.

**Comment by HolgerJeromin** [comment]
This is not easy #3645

**Comment by hiddewie** [comment]
OK I will close this issue because #3645 was also closed.

**Comment by hiddewie** [comment]
OK I will close this issue because #3645 was also closed.
