### ISSUE TITLE
numbering of tracks

### ISSUE THREAD

**Issue by OpenGreenStreet** [openstreetmap/openstreetmap-website#3659]
I just had to find my way around a large train station and missed the numbering of the tracks.
Did I miss the track number? If not, it would be great if these were stored in the future.

**Comment by HolgerJeromin** [comment]
You can find them in another style like ÖPNVKarte:
https://www.openstreetmap.org/#map=18/52.02950/8.53285&layers=O

**Comment by danieldegroot2** [comment]
@OpenGreenStreet Potsdam has
- multiple values on a single platform, which is not supported by most, if any, renderers. The platform may be split up.
- platform edge, which may not have wide support by renderers (usually the ref will be rendered only on the platform though).

**Comment by tomhughes** [comment]
As the issue template you were presented with when opening this says map rendering issues are not dealt with here.

**Comment by OpenGreenStreet** [comment]
Thank you for pointing out the public transport map. That makes sense. 

Regardless, I would like to see the track number displayed in the default view as well. From my point of view, that would be important for quick orientation. (You saw that I didn't immediately think of the obvious either. For searching line number I would have switched for sure). For me, track numbers are as much as house numbers are for buildings.

**Comment by tomhughes** [comment]
As I have said this is the wrong repository to ask for that. When you opened this issue you were presented with a list of options, one if which was this:
![image](https://user-images.githubusercontent.com/147741/185987206-86088e3a-31df-4805-9c57-f6a9f4f991ba.png)
That was the correct option to select to report this.
