### ISSUE TITLE
Docker builds failing without mini_portile2

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3662]
The docker builds have been failing for a few days, with the following error when trying to set up the database:

```
rake aborted!
Bundler::GemNotFound: Could not find mini_portile2-2.8.0 in any of the sources
```

I've checked the output from the `RUN gem install bundler  && bundle install` stage, and it appears to install every other gem OK, but for some reason not mini_portile2.

As far as I can tell, this started after bundler 2.3.20 was released - every build since then has failed, and the last successful build was using bundler 2.3.19.

Since bundler is insanely complex, I'm not planning on investigating this any further, and instead hoping that it magically fixes itself in the next bundler release. If not, then we can revisit this. At least for now, reporting this issue will give anyone else a head start on investigating.

**Comment by mmd-osm** [comment]
Adding `bundle exec` to the migration step fixes the issue here.

```
docker-compose run --rm web bundle exec rake db:migrate
```

Before:

```
docker-compose run --rm web rake db:migrate
Starting openstreetmap-website_db_1 ... done
Could not find mini_portile2-2.8.0 in any of the sources
Run `bundle install` to install missing gems.
```

After:

```
docker-compose run --rm web bundle exec rake db:migrate
Starting openstreetmap-website_db_1 ... done
/usr/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/var/lib/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/usr/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/var/lib/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: previous definition of BUFSIZE was here
/usr/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/var/lib/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: previous definition of Socket was here
/var/lib/gems/2.7.0/gems/dry-schema-1.10.2/lib/dry/schema/types_merger.rb:71: warning: Pattern matching is experimental, and the behavior may change in future versions of Ruby!
pngcrush worker: `pngcrush` not found; please provide proper binary or disable this worker (--no-pngcrush argument or `:pngcrush => false` through
...
```

**Comment by gravitystorm** [comment]
> Adding `bundle exec` to the migration step fixes the issue here.

Nice fix! Thank you. Next time you could make a PR to get the credit :smile:

**Comment by Datyv** [comment]
In my case it was a dependency of nokogiri
Bundler installed version `nokogiri 1.13.8 (x86_64-linux)` which misses the dependency of `mini_portile2-2.8.0`
i had to add it to the gemfile `gem 'mini_portile2', '~> 2.8'`

then it worked
