### ISSUE TITLE
Resolved note text

### ISSUE THREAD

**Issue by boothym** [openstreetmap/openstreetmap-website#3663]
The text at the bottom of a resolved note says (bold added by me):

> If this note contains sensitive information that needs to be removed, you can [Report this note](https://www.openstreetmap.org/reports/new?reportable_id=3226636&reportable_type=Note). For all other problems with the note, please **resolve** it yourself with a comment.

Since the note is already resolved, the bold text does not make sense - it should say something like "please reactivate the note and leave a comment", or be removed.

**Comment by gravitystorm** [comment]
cc @harry-wood who created #3581 and might have some thoughts on how to handle this.

**Comment by boothym** [comment]
Remembered I'd also opened a note about asking users to log in to comment on a note - see #2761 which would presumably change the same file for this.

**Comment by AntonKhorev** [comment]
> "please reactivate the note and leave a comment"

"please reactivate the note" -> user reactivates the note -> "please resolve it" -> user resolves it -> "please reactivate the note" -> ...
