### ISSUE TITLE
Translatewiki: change zh-hk to zh-HK

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3669]
This is one for @translatewiki  - could you please change the export of zh-hk to use `zh-HK`, i.e. change the capitalization of the filename and the root key inside the yaml. This will allow us to standardise some other stuff that we are working on.

If this is something we can control ourselves, please let me know how!

Additionally, is there somewhere we can check the mapping between translatewiki internal language codes and the language codes exported to this repo? I can see that in many cases they don't match, so there must be a list of conversions somewhere on your side. For example:

* (Translatewiki language code) -> (this repo language code)
* `pt` -> `pt-PT`
* `sr-ec` -> `sr`
* `sr-el` -> `sr-Latn`
* `zh-hans` -> `zh-CN`
*  etc

If this conversion list is publicly accessible (and ideally somewhere so that we can propose changes!) that would be great.

Refs #3653

**Comment by Nikerabbit** [comment]
I've submitted a patch for this here https://gerrit.wikimedia.org/r/c/translatewiki/+/828590

You can see the other mapped codes there.

**Comment by gravitystorm** [comment]
@Nikerabbit thanks very much!

**Comment by simon04** [comment]
The zh-HK change seems to be completed. Anything left to be done?

Shall we add a link to https://github.com/wikimedia/translatewiki/blob/master/groups/OpenStreetMap/OpenStreetMap.yaml in config/locales/README?

**Comment by mmd-osm** [comment]
@simon04 I added the link to the wiki page: https://wiki.openstreetmap.org/wiki/Website_internationalization#See_Also
