### ISSUE TITLE
Remove outdated pt translation

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3670]
As found while working on #3653 we have a stray translation file `pt.yml` that [hasn't been updated in around 8 years](https://github.com/openstreetmap/openstreetmap-website/blob/04ff7d4ee81040f152c38ee39ba84491c91a66f3/config/locales/pt.yml).

My first thought is to simply remove it immediately, since it's woefully outdated, and we have `pt-PT` and `pt-BR` translations that are kept up to date. But my concern is that without this file, any browser requesting "pt" will see the default English translation, since our Locale detection doesn't "fall-forwards" i.e. it doesn't choose a more specific locale if the more general locale is missing.

After removing the `pt.yml` file:

```ruby
Locale.available.preferred(Locale.list("pt"))
=> #<struct Locale language="en", script=nil, region=nil, variant=nil, extension=nil, privateuse=nil, grandfathered=nil>
Locale.available.preferred(Locale.list("pt-PT"))
=> #<struct Locale language="pt", script=nil, region="PT", variant=nil, extension=nil, privateuse=nil, grandfathered=nil>
```

Would this limitation be acceptable? Does anyone know how common it is for browsers to request "pt" translations, as opposed to "pt-PT" or "pt-BR"?

An alternative would be to change one of the two `pt-*` translations to use the `pt` key, and then the regular fallbacks would cover all situations. It's worth noting here that:

* [Translatewiki](https://translatewiki.net/wiki/Translating:OpenStreetMap) has `pt` and `pt-br`
* [transifex for iD](https://www.transifex.com/openstreetmap/id-editor/languages/) has `pt` and `pt_BR`
* [rails-i18n](https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale) also has `pt` and `pt-BR`.

So perhaps a better solution is to change the translatewiki export to:
1. stop the translatewiki export from remapping `pt` to `pt-PT`,
2. allow it to overwrite our old `pt.yml`,
3. and then finally remove the `pt-PT.yml` file instead.

Any thoughts?

**Comment by HolgerJeromin** [comment]
I would go for a different file matching.
1. find exact match `(request locale) == (file name locale)` "pt-br" => "pt-br.yml"
2. search first match for `(request locale).split('-')[0] == (file name locale)`    "pt-br" => "pt.yml" (if no pt-br.yml exists)
3. search first match for `(request locale).split('-')[0] == (file name locale).split('-')[0]`  "pt-foo" => "pt-pt.yml" (if no pt.yml exists)

**Comment by tomhughes** [comment]
We already have a matching algorithm thanks, and it's much more sophisticated than that!

**Comment by tomhughes** [comment]
The actual code is https://github.com/openstreetmap/openstreetmap-website/blob/master/lib/locale.rb but trying to understand it is not for the faint hearted ;-)

It will never try and add components though - there is actually data for that in CLDR but I don't really want to get into that and it's unnecessary here.

What @gravitystorm proposes will work just fine and is what I would do - it's also equivalent to your algorithm in it's effects if I'm understanding things correctly.

**Comment by vgeorge** [comment]
In the browsers I have in my machine, Chrome, Safari and Firefox, only the first allows setting `pt`, `pt-PT` or `pt-BR`. As it is very popular, I think the number of users that have `pt` setting might not be negligible.

If an user has a `pt` setting I think there is a higher probability of being a Brazilian user, because of the number of internet users in Brazil (160M) and Portugal (8M). If there isn't any other information about language usage I would go with `pt-BR` as the fallback in the approach proposed by @gravitystorm.

**Comment by tomhughes** [comment]
I would suggest that we go with what CLDR says which I assumed with be `pt-PT` but actually it seems to agree with you:

```
<likelySubtag from="pt" to="pt_Latn_BR"/>
<!--{ Portuguese; ?; ? } => { Portuguese; Latin; Brazil }-->
```

**Comment by gravitystorm** [comment]
Based on the previous two comments, I think we have decided to use the `pt-BR` translation for any plain `pt` requests. Is that correct? If so, we can ask translatewiki to change one line in their configuration, to export `pt-br` to `pt.yml` as per the following tables:

#### Current:

| Translatewiki code | current mapping TW-OSM | OSM filename | used for browsers requesting... |
|---|---|---|---|
| pt-br | pt-br: pt-BR | pt-BR.yml | `pt-BR` |
| pt | pt: pt-PT | pt-PT.yml | `pt-PT` |
| - | - | pt.yml | `pt` |

#### Proposed:

| Translatewiki code | proposed mapping TW-OSM | OSM filename | used for browsers requesting... |
|---|---|---|---|
| pt-br | pt-br: **pt** | **pt.yml** | `pt-BR`, **`pt`** |
| pt | pt: pt-PT | pt-PT.yml | `pt-PT` |

[Here's the source for the translatewiki remappings](https://github.com/wikimedia/translatewiki/blob/4c1d1153e5555309c5010b950407ca6fe123f093/groups/OpenStreetMap/OpenStreetMap.yaml#L16-L17), for reference.

**Comment by gravitystorm** [comment]
@translatewiki @Nikerabbit Please see the above comment, and please let me know if there's anything I can do to help with this. Thanks!

**Comment by gravitystorm** [comment]
Thanks @Abijeet for making the change for us!
