### ISSUE TITLE
Status of en-GB translation

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3671]
In #3653 @Firefishy wrote:

> en-GB should really be removed. Some translations also have incorrect old translations of the licensing text, specifically intro_3_1_html and credit_2_1_html. I asked awhile back: https://translatewiki.net/w/i.php?title=Support&offset=20220607083240#OpenStreetMap.org_Translation_Fixes_59953

I've had a look through the two translations and compared what is different between them. The most common differences are where someone has decided that "email" is "e-mail" in `en-GB`, and the second is where strings from `en` are currently untranslated in `en-GB` (and so that makes no difference due to the fallbacks). There are a few cases where the translations are outdated, and where those translations have had significant changes (like the intro and credit ones, which were heavily revised while keeping the same keys) and so this has had a detrimental impact. There's also a bunch that [have outdated http links](https://github.com/openstreetmap/openstreetmap-website/issues/2392) but that's not specific to `en-GB`.

I think it's worth keeping the en-GB translation, for two reasons. First, there's a few strings in the UI, particularly the turn-by-turn directions and the nominatim strings, that are genuinely different between the languages. Secondly, if we were to remove the `en-GB` translation, our code then [ignores the locale completely](https://github.com/openstreetmap/openstreetmap-website/blob/b36df9286a03c0dd034ce0829eb69a9b66f79ea2/lib/locale.rb#L38-L42) and we would not see `en-GB` formatted dates taken from [the rails-i18n en-GB file](https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/en-GB.yml).

Therefore I think we should do the following:

* Keep the `en-GB` translation
* Fix the intro and credit translations that need significant updates
* Remove the deletion request from translatewiki to avoid any confusion.

**Comment by Firefishy** [comment]
Closed the upstream delete request for `en-GB`

**Comment by Hufkratzer** [comment]
It seems like a strange idea to me to remove `en-GB`. AFAIK, the correct spelling of some words is different in UK- and US-English, e.g. "centre" vs. "center".

Related: https://github.com/openstreetmap/openstreetmap-website/issues/3189

**Comment by tomhughes** [comment]
Yes but our `en` is really `en-GB` so if anything that calls for an `en-US` translation.

**Comment by gravitystorm** [comment]
> Fix the intro and credit translations that need significant updates

I've fixed the remaining one today, the others have either been updated or removed in the meantime. So this issue can now be closed.
