### ISSUE TITLE
GPX visibility badge is not visible - coloured white on white background

### ISSUE THREAD

**Issue by jyooru** [openstreetmap/openstreetmap-website#3681]
### URL

https://www.openstreetmap.org/traces

### How to reproduce the issue?

1. Open the URL (tested in both Brave and Firefox)
2. Notice how there is no visibility badge next to the point count.
3. Press CTRL + A to highlight all text.
4. The badge is now visible.

### Screenshot(s) or anything else?

![20220909T193827+1000_thinkpad-e580](https://user-images.githubusercontent.com/63786778/189320806-661fe52b-a5a9-42a2-adce-8e322a54e86b.png)

**Comment by gravitystorm** [comment]
Thanks @jyooru for the report!
