### ISSUE TITLE
Feature-Request: Öffnungszeiten (speziell bei Arztpraxen): „nach Vereinbarung"

### ISSUE THREAD

**Issue by OpenGreenStreet** [openstreetmap/openstreetmap-website#3684]
### How to reproduce the issue?

Aus meiner Sicht wäre es wünschenswert, wenn man, speziell bei Arztpraxen, bei den Öffnungszeiten „nach Vereinbarung" auswählen/hinterlegen könnte.

**Comment by tomhughes** [comment]
Translation:

> From my point of view it would be desirable if, especially in the case of medical practices, one could select/store the opening hours "by appointment".

**Comment by tomhughes** [comment]
I'm afraid I don't really understand what you mean, but I suspect it's out of scope for the site whatever it is.

Are you asking for some way to select a store and have the site show the opening hours? or a way to enter a time and search for stores that are open then? or something else?

Fragen Sie nach einer Möglichkeit, ein Geschäft auszuwählen und die Website die Öffnungszeiten anzuzeigen? oder eine Möglichkeit, eine Zeit einzugeben und nach Geschäften zu suchen, die dann geöffnet sind? oder etwas anderes?

**Comment by OpenGreenStreet** [comment]
Konkret: eine Ärztin gibt für Mo. bis Do. Öffnungszeiten/Sprechzeiten an und weist für Freitag aus: „Termine nach Vereinbarung“

**Comment by OpenGreenStreet** [comment]
Beispiele:
https://www.google.de/imgres?imgurl=https%3A%2F%2Fwww.drjubitzlottholz.de%2Findex_htm_files%2F16554%402x.png&imgrefurl=https%3A%2F%2Fwww.drjubitzlottholz.de%2F&tbnid=ZIL_7aKZyI_weM&vet=12ahUKEwj44fKqtYz6AhXMPOwKHQM5AQgQMygUegUIARDOAQ..i&docid=AyvsVSQt3m0UPM&w=1202&h=1202&q=sprechzeiten%20nach%20vereinbarung&ved=2ahUKEwj44fKqtYz6AhXMPOwKHQM5AQgQMygUegUIARDOAQ

https://www.google.de/imgres?imgurl=https%3A%2F%2Fhasenleiser.net%2Fwp-content%2Fuploads%2F2021%2F05%2Fhallo-750x410.png&imgrefurl=https%3A%2F%2Fhasenleiser.net%2Fspe%2F&tbnid=loc_0Z3kY21W3M&vet=12ahUKEwj44fKqtYz6AhXMPOwKHQM5AQgQMygCegUIARCqAQ..i&docid=bsUUH_xt-3R8wM&w=750&h=410&itg=1&q=sprechzeiten%20nach%20vereinbarung&ved=2ahUKEwj44fKqtYz6AhXMPOwKHQM5AQgQMygCegUIARCqAQ

https://commons.wikimedia.org/wiki/File:ESA_EichrodterWeg48a_Bild2.jpg

So etwas lässt sich aus meiner Sicht nicht in SC beantworten.

**Comment by OpenGreenStreet** [comment]
Ich würde mir die Option(en) "Nach Vereinbarung" grundsätzlich und/oder für bestimmte Wochentage wünschen.

**Comment by mmd-osm** [comment]
Bitte diskutiere dises Thema am besten im StreetComplete Repo: https://github.com/streetcomplete/StreetComplete

Hier gehört das nicht wirklich rein.

(off topic for Rails Port)

**Comment by OpenGreenStreet** [comment]
@mmd-osm , Danke, meinst Du hier/so?: https://github.com/streetcomplete/StreetComplete/issues/4368
