### ISSUE TITLE
Notes posted as anonymous when oauth fails

### ISSUE THREAD

**Issue by iandees** [openstreetmap/openstreetmap-website#370]
Oauth authorization is failing on the osm.org homepage right now due to [this bug](https://github.com/osmlab/ohauth/issues/9), but instead of 4xx'ing the requests due to authorization failure, the railsport is posting notes anonymously.

**Comment by mmd-osm** [comment]
I'm going to close this issue. Notes posting was moved to OAuth 2.0. The issue described here with ohauth and signature heaers does no longer apply today.
