### ISSUE TITLE
Mention how to remove profile location

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3725]
On the edit profile page, if one has already set a location, there is no way to remove it apparently. One can only just pick a different location.

 But in fact the method to remove it is just to make the latitude and latitude longitude fields blank and then push Update Profile at the bottom. So perhaps mention this on that page. Because sometimes people might want to remove their location.

I can't find the exact file to put the words in to make a PR.

**Comment by openbrian** [comment]
@jidanni There is a way to unset your location.  Erase the latitude and longitude values from the text inputs.  Do not click on the map.  I run a development version of OSM and I can confirm in the database that the lat and lon values are removed.

**Comment by jidanni** [comment]
Yes, I'm saying this procedure is not clear to the user. So the web page to say that is the procedure to use. Else the user has no clear instructions about how to remove his location if that's what he wants to do.

**Comment by pnorman** [comment]
Why add a bunch of text instead of changing the UI?

**Comment by jidanni** [comment]
Splendid idea!

**Comment by mxdanger** [comment]
The edit profile page needs a complete overhaul anyways as this is something that should be resolved with an improved UX flow for adding your location or clearing it.

On a side node I honestly don't even think adding a location should be anywhere near as precise as it currently is, adding your city should be as detailed as it gets. I know many users just put their location at the center of the city marker anyways.

**Comment by tomhughes** [comment]
So currently users have the choice of how precise to make it but you'd rather take that away and somehow force them to use an imprecise location? Not that I'm even sure how that would work - how do you stop somebody putting the pin where they want?

**Comment by mxdanger** [comment]
> force them to use an imprecise location

Yes, like how it's done on every social media app, even GitHub does it although not as detailed. You just type country, state/province, county, city or click the location button to do it all for you. That means users could be granular in how precise they want to be (by omitting city field for example) and also have the option for users to display that location directly on their profile making the feature useful outside of the quite frankly useless hyper-local "Other nearby users" dashboard.

**Comment by tomhughes** [comment]
Well sure we can add a search using nominatim to help people find a location but I don't see why we should prohibit them from choosing to fine tune the result if they want - services provide that kind of search interface for ease of use rather than to control precision and in any case OSM is something of a special case given that location is our entire reason for existence rather than just being a nice extra.
