### ISSUE TITLE
Keyboard navigation: Multiple choice selection

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/openstreetmap-website#3749]
### How to reproduce the issue?

1. Go to someone's user profile
2. Click "Report user"
3. Navigate to a report reason using `Tab`. The first choice is not selected yet.
4. Press the `Down` arrow key. The second choice will be automaticly selected.
5. Press the `Up` arrow key. The first choice will now be selected.

---

**Current behaviour** (focus, but no automatic selection for the first choice)
![image](https://user-images.githubusercontent.com/67521919/194767855-1ca74255-fedb-46db-a657-0393f01fcd24.png)

---

**Expected behaviour**
Either
- The choice is automaticly selected like all others; or
- none of the choices are automaticly selected -and have to be selected manually using the arrow keys and space.

---

(Windows 7 Chrome)

**Comment by AntonKhorev** [comment]
> In the share menu,
> 
>     * pressing `Enter` does not select a choice when focusing on a checkbox, unlike `Space`.

Should it? Enter usually submits the form if it's possible to submit it.

**Comment by danieldegroot2** [comment]
@AntonKhorev I've dropped the issues with Enter from the ticket.

**Comment by AntonKhorev** [comment]
Radio buttons also behave like they do in browsers by default.
You can check this by creating an html file with a form and copying there the radio buttons markup from the report page. They will behave in the same manner.
