### ISSUE TITLE
Joining forms occur across buttons in "Share" panel for cursive scripts

### ISSUE THREAD

**Issue by bgo-eiu** [openstreetmap/openstreetmap-website#3754]
### How to reproduce the issue?

See in the image for example, کڑی ("link") becomes کڑیـ as if it is connected to the text in the next button.

This might be fixable by padding these values with zero width non-joiner characters (or maybe there is something unusual about how these button values are being populated, as I have not seen this elsewhere).

### Screenshot(s) or anything else?

![IMG_20221016_212515](https://user-images.githubusercontent.com/100172442/196070256-4e8e5cb0-6727-417c-b532-22be31885702.jpg)

**Comment by AntonKhorev** [comment]
Is it still happening after share button group update https://github.com/openstreetmap/openstreetmap-website/pull/3694 ?

**Comment by AntonKhorev** [comment]
https://www.openstreetmap.org/?locale=pnb

I see this
![image](https://github.com/openstreetmap/openstreetmap-website/assets/4158490/1dbc5cac-bd80-451a-bfac-d2bd5423a160)

So I guess it's fixed.

**Comment by gravitystorm** [comment]
I see the same as @AntonKhorev , so I'm going to mark this as fixed. 

@bgo-eiu please feel free to reopen if there is still a problem.
