### ISSUE TITLE
Names of the Karabakh region of Azerbaijan.

### ISSUE THREAD

**Issue by Nizami20052022** [openstreetmap/openstreetmap-website#3759]
The names of the Karabakh region of Azerbaijan should not be in Armenian.

**Comment by tomhughes** [comment]
Data issues are not the responsibility of this repository, and neither are map rendering choices.

We display tiles from a number of map providers but have no control over what names they choose to show - in the case of the default layer names will be from the `name` tag while some other layers may choose to show other names or more than one name.

Please do not just change the name tag though without first considering the [disputed names policy](http://wiki.osmfoundation.org/w/images/d/d8/DisputedTerritoriesInformation.pdf) and/or consulting with the [Data Working Group](https://wiki.osmfoundation.org/wiki/Data_Working_Group).
