### ISSUE TITLE
Problem with openstreetmap-website installation

### ISSUE THREAD

**Issue by lamisofteu** [openstreetmap/openstreetmap-website#3772]
### How to reproduce the issue?

I tried install openstreetmap-website according to the instructions for Ubuntu 20.02 LTS but without success. Exactly I have problem with node.js modules installation. 

Can anybody help?

### Screenshot(s) or anything else?

jdoe@www:~/openstreetmap-website$ bundle exec rake yarn:install
/usr/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/var/lib/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/usr/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/var/lib/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: previous definition of BUFSIZE was here
/usr/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/var/lib/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: previous definition of Socket was here
yarn install failed to execute.
Ensure yarn is installed and `yarn --version` runs without errors.

**Comment by gravitystorm** [comment]
@lamisofteu I'm sorry that we haven't got back to you on this over the last few weeks. Are you still having the same problem, or did you manage to find the solution?

**Comment by mmd-osm** [comment]
No feedback since one month -> let's close this one due to lack of activity.

**Comment by ZhengLin-Li** [comment]
@lamisofteu During which step / section of the [https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md](https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md) are you facing this problem. Which command have you executed? Could you provide more context?

**Comment by systemed** [comment]
I suspect this is a dupe of #3579 (in which case the solution mentioned there should work).
