### ISSUE TITLE
 OSM map no longer loads in Safari on iOS 9.3.6

### ISSUE THREAD

**Issue by saper** [openstreetmap/openstreetmap-website#3782]
### URL

https://www.openstreetmap.org/

### How to reproduce the issue?

Load openstreetmap.org on something like iPad Mini 1 generation running iOS 9.3.6. This was the last 32-bit release so it cannot be upgraded.

I understand that no one from developers may still have access to something like this, but I am happy to help as this device is still useful during travel.

This broke few months ago, not recently.

### Screenshot(s) or anything else?

The screenshots are exactly the same as on https://github.com/openstreetmap/openstreetmap-website/issues/3387 except that my language is set to Polish ("pl").

I have fired up [Google's ios-webkit-debug-proxy](https://github.com/google/ios-webkit-debug-proxy/releases/download/1.7.1) and it show the first exception is at https://www.openstreetmap.org/assets/i18n/pl-f04b993d4547b4842aeb34cf05df4886ef128649fd5375e4be846a4b4bc67aa7.js line 1 pointing at the dot after first `I18n`:

````js
I18n.translations||...
````

![Developer tools screenshot pointing at the exception in the pl-f04b993d4547b4842aeb34cf05df4886ef128649fd5375e4be846a4b4bc67aa7.js file](https://user-images.githubusercontent.com/248374/199803933-54c4641e-4f64-433c-9eff-1fd1bce2c4ed.png)

Looks like application.js has not been loaded yet, maybe this is a problem with an order of script loading?

**Comment by pnorman** [comment]
What version of Safari do you have?

**Comment by tomhughes** [comment]
Given that the developers here have no access to Safari somebody will need to provide the errors from the console but most likely there will be nothing we can do - it's probably just too old for leaflet and/or bootstrap to support any more.

**Comment by tomhughes** [comment]
It would also help to know when it last worked, but if it was a while ago then this may well be the same issue as Internet Explorer which was triggered by the bootstrap 5 upgrade.

**Comment by saper** [comment]
User-Agent: Mozilla/5.0 (iPad; CPU OS 9_3_6 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G37 Safari/601.1 

which is Safari 9

I can try to build the openstreetmap UI myself and try to find out.

**Comment by saper** [comment]
> somebody will need to provide the errors from the console

As far as iOS webkit proxy reports, there is no console error, but it stop on an (unfortunately unreported) exception on `I18N` as pointed on the screenshot above.

**Comment by tomhughes** [comment]
Safari 9 is from 2015 so seven years old now.

**Comment by saper** [comment]
Yes, I know :( but this cannot be upgraded to anything newer :( I'll try to build the UI myself and bisect where it worked last time.

**Comment by tomhughes** [comment]
As I say 3871d61be43857436d1eaefe9e84841e8a7d0f4f is probably a candidate for where it started failing as we know that caused the map to stop displaying in IE.

**Comment by saper** [comment]
https://github.com/twbs/bootstrap/blob/v5.1.3/.browserslistrc looks discouraging, but I do not see bootstrap loading at all yet. It seems that `pl-xxxx.js` is the first one being loaded.

**Comment by saper** [comment]
Just browsing the maps and the search. Sometimes I was fixing some tags from there. Thanks for the pointer to https://map.atownsend.org.uk/, need to find something similar with search, because [Nominatim moved on to ES6](https://github.com/osm-search/nominatim-ui/issues/195).

**Comment by tomhughes** [comment]
I just rechecked IE and it does look very similar, with I18n being one of the errors:
![Screenshot from 2022-11-03 19-26-00](https://user-images.githubusercontent.com/147741/199816043-fc3a8395-2319-4985-b5fd-5a71623b1e9c.png)

**Comment by saper** [comment]
Line 43 is where bootstrap loads... with `const` it has little chance of working I guess.

Trying https://www.openstreetmap.org/login gives me I18n error again and after I skip it looks like a whole DOM is not okay for Safari:

```text
> $(document)
<- Error: SyntaxError: DOM Exception 12
```

![$(document) fails with DOM Error 12 on Safari](https://user-images.githubusercontent.com/248374/199834572-38926530-9878-41c3-90ec-e5d27da0a3aa.png)

Unless you might consider going back to Bootstrap v4 I am out of luck I guess.

**Comment by HolgerJeromin** [comment]
We have a file with many libraries (jQuery and co). If one of the code uses for example arrow-functions this whole file will brake in Safari 9 and IE11. Thats why you see problems with `$(document)` because `$` is jQuery.
https://caniuse.com/arrow-functions

The code uses some modern stuff. So tuning some stuff will probably a bottomless pit.

**Comment by tomhughes** [comment]
I think we're going to have say this one is unfixable and such old browsers are no longer supported.

**Comment by saper** [comment]
Sorry to hear that, but I get what you mean.

Maybe it should be stated that browsers required by bootstrap 5 are now the minimum requirement and remove ES6 polyfills and the like. (I saw them in the code and thought we still support ES5).
