### ISSUE TITLE
Political layer

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3784]
What the OSM website lacks is a political areas layer.

Currently in metropolitan areas it would be great if Nibblesford Falls was in green, and Norfsberg Heights was in pink, etc.

That way one could tell at a glance exactly with suburb one was in, without having to examine very closely the boundaries themselves. [w:Four color theorem](https://en.wikipedia.org/wiki/Four_color_theorem).

Okay, at lower zoom levels have States and Provinces be the color item. And as we zoom in and in even get down to Mosquito Abatement Districts...

**Comment by tomhughes** [comment]
If you know of such a layer then feel feel to propose it following the [policy in the wiki](https://wiki.openstreetmap.org/wiki/Featured_tile_layers/Guidelines_for_new_tile_layers).

The developers of this repository do not operate any tile layers themselves - we rely on third parties to do that.
