### ISSUE TITLE
Background on the OSS4SDG Challenge 6?

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3786]
I'm left slightly confused as to what is going on with this United Nations project, and it would help me enormously if anyone out there has some more information that they can share with me on this topic.

As far as I can make out, the United Nations is currently running a Hackathon (or rather, the hackathon was in October and submissions are now being reviewed). The Hackathon is known as "OSS4SDG" - Open Source Software for the (UN) Sustainable Development Goals", and this Hackathon is on the subject of SDG 11 - "Sustainable Cities and Communities". For this Hackathon, the open source community chosen is OpenStreetMap. There is 10,000 € available as prizes.

https://ideas.unite.un.org/sdg11/Page/Overview

There are seven challenges in the Hackathon, and number 6 is "OpenStreetMap website improvement challenge"

https://ideas.unite.un.org/sdg11/Page/Challenge6

Does anyone know where all this has come from? For example who put together the list of topics on that page? To be clear, nobody has contacted the current maintainers about any of this, e.g. what we could do to help, any tips that we have to make the pull requests more likely to succeed, any technical pointers as to what might be achievable in the time allotted, any checking as to what work is currently under way (or is blocked by other tasks) or anything like that.

It says at the bottom of the page that "The solutions ... will be evaluated by a panel composed of representatives of [various orgs] and OpenStreetMap". Can anyone shed light on to who is representing OSM on this panel? Is it someone from OSMF, one of the chapters, or someone else?

Since this challenge is 100% focussed on contributing to this codebase, I think it would be great if we the maintainers were in the loop, and I hope that someone reading this can help.

**Comment by tomhughes** [comment]
Oh I wondered what that OSS4SDG was about.

I had forgotten about the whole UN nonsense where they were soliciting people to develop features, in some case features that were already under development, without any discussion with us beforehand and with an entirely unrealistic time frame of only a few weeks.

I was tipped off by @grischard just before it launched and he also approached me to be a judge but I said I wasn't interested.

**Comment by mmd-osm** [comment]
They've used the following osm account to post on the community site:

https://www.openstreetmap.org/user/Open%20Source%20Software%204%20SDGs
https://community.openstreetmap.org/u/open_source_software_4_sdgs/summary

Maybe you can try to reach out to them?

**Comment by grischard** [comment]
Hi! I've been the one in touch with the UN people, and that sixth challenge was quickly put together when I saw that all the other challenges were focused on using the data itself. If I were to do it again, I'd chat more with the maintainers of the website first. I was hoping that this could help encourage people to contribute to the website.

The two submissions for that challenge have been [a redesign](https://github.com/Playzinho/gaia/blob/main/Reimagining%20the%20OSM.org.pdf) and @openbrian's microcosms efforts.

**Comment by gravitystorm** [comment]
> If I were to do it again, I'd chat more with the maintainers of the website first.

Thanks! That would be appreciated, since after Hacktoberfest a few years ago it brings back bad memories to be the "target" of an unexpected third-party competition.

It's also an opportunity for us to help make sure the challenge is likely to be successful, as I mentioned above. Unfortunately some things have other development work that needs to be completed first, before they can be considered, and this is not always obvious. So I want to avoid frustration as much as possible, particularly if new contributors are working on something that seems to them straightforward but has no realistic chances of being merged.

> I was hoping that this could help encourage people to contribute to the website.

Contributions are always welcome!
