### ISSUE TITLE
Suggested ability to tag other users in 'fixme' tag in OSM

### ISSUE THREAD

**Issue by 2dreamy** [openstreetmap/openstreetmap-website#3793]
Hi.
I would like to thank the developers and administrators involved in OSM.

I am collaborating with another mapper, and it would be very useful to have a function to call a specific mapper from the ‘fixme’ tag in OSM.
Is this possible?
![fixme tag](https://telegra.ph/file/9d503a0adc2bb927c2dbc.jpg)

Thank you.

* I'm not good at English, so I don't know if I explained it well enough.
If you need more explanation, please ask.

**Comment by tomhughes** [comment]
What do you mean by "call another mapper" exactly?

Feel free to use your native language if that makes it easier to explain things.

**Comment by 2dreamy** [comment]
> What do you mean by "call another mapper" exactly?
> 
> Feel free to use your native language if that makes it easier to explain things.

I am sorry.
I'm talking about the ability to tag other users (mappers registered as my friends).
I added an image to my previous post.
Thank you.

**Comment by tomhughes** [comment]
Why would you want that in a fixme though? What would it actually do other than possibly linking to them when viewed on the web site.

It certainly won't be able to notify them if that's what you're hoping for.

**Comment by 2dreamy** [comment]
First of all, it must have been difficult to understand with my poor English, so thank you for asking a question.

**When I tag my co-worker in 'fixme' tag, I want it to go to notification to my co-worker.** (this is the key-point!)

I want to work with my co-workers and not just a bunch of random people, and to pass on the work to him.
(Of course, the 'fixme' tag is visible to anyone and can be edited by others.)
In particular, the OSM message function is very inconvenient, and in order to collaborate, links and work contents have to be transmitted through external functions, which is very inconvenient when there are a lot of work contents.

**Comment by tomhughes** [comment]
So I don't think we're going to be able to do this for a number of reasons.

Firstly the API is deliberately data agnostic - it does not attempt to infer the meaning of any tag or value and this would break that by requiring it to treat fixme tags specially.

Also it would require significant changes both to this repository and to https://github.com/zerebubuth/openstreetmap-cgimap both of which implement data upload to make it possible for them to generate notifications - that would be especially hard for cgimap given that notifications are implemented as serialised ruby objects in the database and it isn't written in ruby.

**Comment by 2dreamy** [comment]
I don't understand all of your words as they're professional, but I'll take it.
However, I want to say one more thing,
In OSM, the 'note' tag has the ability to tag other mappers.
Of course, the 'note' tag has a slightly different role than the 'fixme' tag, and the disadvantage is that the notification is not clear.
I thought if it was possible in the 'note' tag, it would also be possible in the 'fixme' tag.
Anyway, thanks for the review.

**Comment by 2dreamy** [comment]
If you tag another mapper for 'note', you will not receive a notification, but the note will be delivered to that user's 'Notes'.
!['노트' 항목에 보임](https://telegra.ph/file/5d6dfcc99a65522fbd562.jpg)

**Comment by tomhughes** [comment]
So firstly that isn't a `note` tag on a map data object, it's a comment on a note, which is something completely different.

Secondly there is nothing which parses the body of the comment and notices the `@adreamy` in the comment - the reason that `adreamy` is listed as the creator is because they created the note and added the first comment, not because of anything they wrote in the comment.
