### ISSUE TITLE
Github actions deprecation warnings

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3806]
I noticed today that we are getting two deprecation warnings from github actions:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: coverallsapp/github-action@1.1.3

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by tomhughes** [comment]
I don't know where the second one is coming from but the first one is outside our control until coveralls release an update and I assume the second one is also nested inside some third party action as I don't see us using it directly.

**Comment by tomhughes** [comment]
Also a proposed fix: https://github.com/coverallsapp/github-action/pull/136

**Comment by tomhughes** [comment]
Should be fixed by #3941.
