### ISSUE TITLE
Official Road Routing via multiple providers

### ISSUE THREAD

**Issue by karussell** [openstreetmap/openstreetmap-website#381]
I would like to have an "official" routing directly on the openstreetmap website. And because "official" is hard, I propose a solution where one can select from multiple provider like it is done [in Kai's solution](http://apmon.dev.openstreetmap.org/routing) under menu 'routing'.

See his comments: http://lists.openstreetmap.org/pipermail/dev/2013-July/027210.html

Instead of a ruby backend, in my opinion, you only need javascript to implement that e.g. via json(p). So even no additional servers are required on OSM side.

**Comment by saerdnaer** [comment]
I think as #716 was merged this issue can be closed
