### ISSUE TITLE
Application error opening note URL

### ISSUE THREAD

**Issue by joshas** [openstreetmap/openstreetmap-website#3811]
### URL

https://www.openstreetmap.org/note/3420572

### How to reproduce the issue?

1. Open URL in web browser: https://www.openstreetmap.org/note/3420572

### Screenshot(s) or anything else?

Exact error message:

> Application error
> 
> The OpenStreetMap server encountered an unexpected condition that prevented it from fulfilling the request (HTTP 500)

**Comment by mmd-osm** [comment]
Probably a duplicate of #2146

**Comment by tomhughes** [comment]
Indeed.
