### ISSUE TITLE
Changeset date/time abbr title doesn't show on mobile

### ISSUE THREAD

**Issue by boothym** [openstreetmap/openstreetmap-website#3823]
The changeset closed date/time text e.g. "almost/about/over 5 years" is wrapped in an abbr tag with a title value containing the actual timestamp of the changeset closure. If you are on a desktop browser and hover over the text you get a tooltip showing the timestamp.

However this does not work on a mobile browser, as you cannot hover on the abbr tag. A bit annoying if you want to know the exact timestamp when using your phone.

Could I suggest some extra CSS is added to show a tooltip when a user taps on the abbr tag? There is an example here which seems to work: https://bitsofco.de/making-abbr-work-for-touchscreen-keyboard-mouse/

**Comment by mmd-osm** [comment]
Related discussion https://github.com/openstreetmap/openstreetmap-website/issues/631#issuecomment-210361610

**Comment by boothym** [comment]
I did a search for "title", honest, but I missed that issue...

**Comment by mmd-osm** [comment]
Ok, let's close this one, then.
