### ISSUE TITLE
API stability policy

### ISSUE THREAD

**Issue by not-my-profile** [openstreetmap/openstreetmap-website#3837]
Since many applications rely on the OpenStreetMap editing API I think it would make sense to somewhere write something about how stable the API is guaranteed to be and how / how soon breaking changes would be announced if at some point deemed necessary.

For example Wikidata has the [Stable Interface Policy](https://www.wikidata.org/wiki/Wikidata:Stable_Interface_Policy).

**Comment by tomhughes** [comment]
I'm not sure that's a matter for us though - this is more of an implementation of the api and not the only one.

**Comment by mmd-osm** [comment]
We can basically do whatever we want with the API, it’s the responsibility of the api consumers to stay up to date: see https://wiki.osmfoundation.org/wiki/Terms_of_Use#IX._Disclaimers

**Comment by tomhughes** [comment]
To be clear in reality the API is very stable - while things may sometimes be added we would be very unlikely to remove things that were being used without a long period of deprecation and attempts to contact anybody still making use of it.

**Comment by mmd-osm** [comment]
Right, it’s rather unlikely in real life that we’re breaking things, but the ToU would allow us to do such changes if needed.

**Comment by not-my-profile** [comment]
Thanks for clearing that up :) I don't think an official looking statement of intent is necessary, I was just curious on your commitment to API stability.

>this is more of an implementation of the api and not the only one

Interesting! Which other implementations of the API are there?

**Comment by tomhughes** [comment]
Well https://github.com/zerebubuth/openstreetmap-cgimap is the main one - that is what actually runs much of the API on the production site.

**Comment by gravitystorm** [comment]
> how / how soon breaking changes would be announced if at some point deemed necessary.

The last major revision to the API was over a decade ago, so for the next major breaking change it's not possible to call upon any recent precedent. Any policy or discussion veers rapidly into the hypothetical.

Previously breaking changes were announced a few months in advance, but they were "stop the world" changes, where the API was switched off for a period (up to several days) and switched back on again with the new version. My personal opinion is that this "stop the world" approach is no longer practicable given the size of the project, and instead we are more likely to see an overlap period, with multiple versions of the API available and a months-long deprecation timeline. However, this is not a universally held opinion among the development community, and it also depends on what sort of changes are proposed. Again, this all becomes hypothetical quite quickly.

In the meantime, we've made several minor breaking changes to the API, for example removing the `/changes` endpoint, usually by contacting the individual projects using the affected API until the remaining traffic is minimal. I can see this approach continuing for other minor breaking changes, unless major API changes become routine enough that the minor changes can be combined into that process.

I realise this is a bit vague but I hope it is still useful. In short, for breaking changes and deprecation periods, the words "rarely" and "months not weeks" would generally apply.
