### ISSUE TITLE
Integrate Valhalla Routing (again)

### ISSUE THREAD

**Issue by nilsnolde** [openstreetmap/openstreetmap-website#3843]
### Problem

Implement support for another great FOSS routing engine.

### Description

We've been hosting a public Valhalla instance for the past year, funded by FOSSGIS and maintained by our company. I just got confimation that it'll be funded in the future as well, just like OSRM. The frontend is available here: https://valhalla.openstreetmap.de/.

If you agree, we'd like to PR the implementation in this repo soon-ish (Cc @chrstnbwnkl), so it can be used on osm.org next to Graphhopper & OSRM. @kevinkreiser mentioned that Valhalla was already supported back in the days. It has been added in this commit (https://github.com/openstreetmap/openstreetmap-website/commit/e54eadea95296a68044bd3f2b092b978a808f1b7), but I guess sufficiently many changes went over both Valhalla & the code in this repo since then.

**Comment by tomhughes** [comment]
I don't think much will have changed in this repo though I can't speak for valhalla.

I'd start by reverting 9340c461732ef7387dd453ea3fcf5e64ea782ab4 though as that represents the state when it was removed - obviously it will need renaming as fosgiss_valhalla or something.

Probably we also need to rename the existing fossgis routing references in the code to make it clear they are the osrm version.

**Comment by nilsnolde** [comment]
> I don't think much will have changed in this repo though I can't speak for valhalla.

Yeah, seems very straight-forward. 

> Probably we also need to rename the existing fossgis routing references in the code to make it clear they are the osrm version.

Agreed.

Ok cool, then you'd accept a PR it seems. I'll get the ball rolling in that case.
