### ISSUE TITLE
Ordnance Survey Dates on Copyright page(s) need updating

### ISSUE THREAD

**Issue by SK53** [openstreetmap/openstreetmap-website#3845]
### URL

https://www.openstreetmap.org/copyright

### How to reproduce the issue?

The section:

"United Kingdom: Contains Ordnance Survey data © Crown copyright and database right 2010-19."

should read:

United Kingdom: Contains Ordnance Survey data © Crown copyright and database right 2010-**22**."

And from early in January should read "2010-23"

I believe in some language versions this is even more out-of-date (e..g, some files from Translate Wiki seem to contain "2010-2"), but these are less significant than the EN version.

I've corrected this in my fork, and will try and create a PR

**Comment by tomhughes** [comment]
Any change to that page requires LWG approval.

**Comment by tomhughes** [comment]
Frankly unless there's a good reason to keep it I'd rather just get rid of the date.
