### ISSUE TITLE
How can we reduce the size of this repository?

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3849]
### Problem

Or at least, reduce the speed at which it grows? On my development machine, the git repo now takes up over 400MB, but less than 10% of that is code or assets that we manage here. From time to time this causes a few problems - slow clone speeds for most developers (e.g. those who want `git blame` to work, and can't work with just a shallow clone), and I've run into the issue when using this repository for things like Heroku where you might need to upload the entire repo to a remote host.

### Description

The most noticeable source of repo size, to me, is a combination of historical versions of potlatch2 and iD. I'm not sure what the reasons are or were, but release versions of both editors are/were copied directly into this repository. This means we have lots of versions of the potlatch2.swf binaries (around 1 - 1.5MB each), compiled versions of iD (largest of these is 12MB, but there are dozens and dozens in the 2+MB range) and even an old Potlatch2 mp4 help video (9.5MB). All this adds up, and the repo keeps growing e.g. every time iD is released.

Note that this isn't about the size of the latest checkout, which is mostly OK, it's the accumulation of all the historical versions that is slowly adding up.

There's probably two things worth considering:
* How do we handle vendored assets from this point on? Can we use our dependency managers (e.g. yarn) to handle the distribution of things like iD, without impact on the development experience? I don't want to require additional steps (e.g. "download a tgz from here and untar it into some directory") for getting up and running.
* What do we do about the stuff already in the git history? For some things, like rebuilding the repository without the P2 video, that would leave old checkouts in a partially not-functioning state. But do we need to worry about that? Or is there an easy way to handle it, perhaps some git magic to move large files out of old commits and into a different but linked repo?

**Comment by tomhughes** [comment]
There's nothing you can do about existing history, unless you're prepared to rewrite history and change all the commit IDs which I would be against.

**Comment by mmd-osm** [comment]
> I've run into the issue when using this repository for things like Heroku where you might need to upload the entire repo to a remote host.

I don’t quite see the need to upload the full history. Can’t you create a zip file without the .git directory and upload that instead?

**Comment by HolgerJeromin** [comment]
Can git submodules or subtree help with new id releases?

**Comment by gravitystorm** [comment]
> I don’t quite see the need to upload the full history. Can’t you create a zip file without the .git directory and upload that instead?

Sure, there are workarounds. But by default, Heroku (and perhaps other similar systems) work by doing a `git push` and pushing to an empty remote repository involves transferring the entire git history.

> Overall, I think of 400MB more as 0.4GB, or maybe even the size of a Denmark extract. It’s not the biggest concern to me.

Personally I think it's ~~madness~~ surprising for a repository with a few dozen code files to have hundreds of megabytes of historical baggage dragged around with them wherever they are needed. Perhaps we don't notice it because we've already run `git clone` once and have forgotten having to twiddle our thumbs while all that stuff was downloaded, never to be needed.

But in general, it seems like given @tomhughes is against fixing the history and it's not a concern to @mmd-osm then I'll file this under "nice to have, but there are more important things to work on" and close this issue.

**Comment by simonpoole** [comment]
I haven't looked at this detail, but couldn't https://git-scm.com/docs/partial-clone potentially be a solution?

**Comment by gravitystorm** [comment]
> I haven't looked at this detail, but couldn't https://git-scm.com/docs/partial-clone potentially be a solution?

I'd call that a workaround rather than a solution, personally. It does allow developers to avoid downloading all the large blobs, but at the cost of more complexity (in install instructions etc). 

A solution would be to avoid having to deal with these large blobs at all (since they aren't managed in this repo, they are just build artefacts from other projects).
