### ISSUE TITLE
Weird OSRM bicycle routing

### ISSUE THREAD

**Issue by rkozlo** [openstreetmap/openstreetmap-website#3855]
### Problem

Osrm bicycle profile on osm.org is very vulnerable on lack tags. It routes very aggressively on road for vehicles even though there is near cycleway.

### Description

Not talking about single situation but generally. Seems like algorithms on osm main page should represent better quality. Graphhooper handles this a lot better. Didn't you consider changing osrm bicycle profile? IMHO it may be better to remove this osrm bicycle if it routes like this or at least maybe add to name something like "shortest".
One  [example](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=54.3837%2C18.4687%3B54.3742%2C18.5681#map=16/54.3766/18.5113) and [another](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=54.38368%2C18.46845%3B54.37423%2C18.56814#map=17/54.37660/18.51227) after moving pinpoint few meters
I am aware that it is more about data and routing engine here, but I am talking about representative matters.

### Screenshots

![Screenshot_20221221_205406](https://user-images.githubusercontent.com/44550015/209001091-cbf1a219-7a47-4af1-840d-48788b7ffe1b.png)

**Comment by tomhughes** [comment]
We have no insight into or control over any of the routing engines - if you dislike the decisions one of them is making you will need to discuss it with the person running the routing engine in question.
