### ISSUE TITLE
OsmCommunityIndex fails when database_offline status is set

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#3858]
I've added an entry `status: "database_offline"` to my settings.local.yml and wanted to start up the Rails server. For some reason, the server wouldn't start up anymore and fails with the following error message:

openstreetmap-website/lib/osm_community_index.rb:4:in `add_to_i18n': uninitialized constant OsmCommunityIndex::Community (NameError)

Maybe this is some issue in my local set up. Once I remove the database_offline setting again, everything is working fine.

**Comment by gravitystorm** [comment]
We should figure out how to add some tests (at least test out booting the app) in the `database_offline` state. I think every time the sysadmins have to use offline mode, some more bugs are uncovered.

Thanks for finding this one!

**Comment by mmd-osm** [comment]
Someone on community.osm.org was asking what kind of HTTP responses to expect during the January downtime. When I tried to simulate the db downtime, this issue immediately popped up. I guess there are good reasons to test this stuff ahead of time, as mentioned in https://github.com/openstreetmap/operations/issues/548

**Comment by tomhughes** [comment]
I always do test it before we use it, but that won't be for a few weeks yet.
