### ISSUE TITLE
Pass on 'rel="me"' attribute for Mastodon Links

### ISSUE THREAD

**Issue by pietervdvn** [openstreetmap/openstreetmap-website#3859]
### Problem

When adding a link with an attribute `rel="me"`, this attribute is dropped. 

### Description

However, Mastodon uses this attribute for verification. If this attribute would be kept, we could "verify" this on our Mastodon profiles.

### Screenshots

https://www.openstreetmap.org/user/Pieter%20Vander%20Vennet is an example of a profile using this attribute in the description.

https://en.osm.town/@opencage is an example using verified links

**Comment by manoj1749** [comment]
@pietervdvn can you explain about the issue more?

**Comment by tomhughes** [comment]
No need. I understand what he means.

**Comment by pietervdvn** [comment]
@manoj1749 When adding 'rel=me' attribute to the description of your profile in a link, this attribute is stripped, making validation on Mastodon impossible. Validation on Mastodon scrapes the website, searches for links with a 'rel=me' tag.

**Comment by pnorman** [comment]
To support the rel attribute it would need to understand it in order to make sure that the `nofollow noopener noreferrer` are properly set on the links

**Comment by tomhughes** [comment]
The problem is that we have this in our sanitizer configuration:

```ruby
:add_attributes => { "a" => { "rel" => "nofollow noopener noreferrer" } },
```

in order to add various rel attributes, but that also has the effect of replacing any existing rel attribute.

**Comment by pietervdvn** [comment]
For future reference: the config is [here](https://github.com/openstreetmap/openstreetmap-website/blob/70d7d8d850148f714b70a3297c02a8203214dec6/config/initializers/sanitize.rb#L4)

**Comment by pietervdvn** [comment]
I had an _extremely_ quick look to the meaning of the various 'relation'-values. IMHO, using `rel="me noopener nofollow noreferrer"` would be fine, even though the combination of `me` and `nofollow` seem a bit contradictory. The `nofollow` signals that _OpenStreetMap.org does not endorse the link_ while the `me` signals that _this user has this mastodon account_ (but I'm not an expert in these matters. But maybe I should add a few of those tags on user-generated links in MapComplete too). 

I'm not familiar with Ruby; but it seems that [this](https://github.com/rgrove/sanitize#custom-configuration) library is used for sanitation, which uses a whitelist of what is allowed. As `rel`-tags are _not_ in this configuration; they are dropped before adding the `noreferer nofollow noopener` again.

I do think that adding `:attributes => {"a" => {"rel" => "me"} }` might just work to keep the `rel=me` intact.

**Comment by pnorman** [comment]
> I do think that adding `:attributes => {"a" => {"rel" => "me"} }` might just work to keep the `rel=me` intact.

That would add rel=me to all links, and not add the ones we add as an anti-spam measure.

**Comment by pietervdvn** [comment]
I used `:attributes`, not `:add_attributes` here - a small difference that is easy to miss.

This would _allow_ `rel=me` to be used, but not _add_ them to every link.

The full code would then look like

``` ruby
Sanitize::Config::OSM = Sanitize::Config.merge(
  Sanitize::Config::RELAXED,
  :elements => Sanitize::Config::RELAXED[:elements] - %w[div style],

  :attributes => { "a" => { "rel" => "me" } },  # Whitelist rel=me

  :add_attributes => { "a" => { "rel" => "nofollow noopener noreferrer" } },
  :remove_contents => %w[script style],
  :transformers => lambda do |env|
    env[:node].remove_class
    env[:node].kwattr_remove("style", nil)
    env[:node].add_class("table table-sm w-auto") if env[:node_name] == "table"
  end
)
```

**Comment by tomhughes** [comment]
That won't actually work because `add_attributes` is explicitly documented to replace any existing `rel` attribute.

It can be done with custom code in the transformer though.

**Comment by pietervdvn** [comment]
Ah, to bad. I should indeed have [read the documentation](https://github.com/rgrove/sanitize#add_attributes-hash) a bit better.

Anyway, thanks a lot for making the change! Looking forward to see it in production!

**Comment by pietervdvn** [comment]
It's working! :partying_face: 

You can see the 'verified' checkmark in my account now: https://en.osm.town/@pietervdvn
