### ISSUE TITLE
An invalid diary entry URL returns an error code 500

### ISSUE THREAD

**Issue by deevroman** [openstreetmap/openstreetmap-website#3865]
### URL

[https://www.openstreetmap.org/user/TrickyFoxy/diary/399621)](https://www.openstreetmap.org/user/TrickyFoxy/diary/399621\))

### How to reproduce the issue?

0. Login in https://openstreetmap.org
1. Open [https://www.openstreetmap.org/user/TrickyFoxy/diary/399621)](https://www.openstreetmap.org/user/TrickyFoxy/diary/399621\))
2. Application error. The OpenStreetMap server encountered an unexpected condition that prevented it from fulfilling the request (HTTP 500)

**Comment by ZhengLin-Li** [comment]
I think you may can visit by the following link: [https://www.openstreetmap.org/user/TrickyFoxy/diary/399621](https://www.openstreetmap.org/user/TrickyFoxy/diary/399621) 
Note it is not [https://www.openstreetmap.org/user/TrickyFoxy/diary/399621)](https://www.openstreetmap.org/user/TrickyFoxy/diary/399621)

**Comment by deevroman** [comment]
@ZhengLin-Li of course. But error 500 is an error that signals that something went wrong on the server. A suitable error: 4xx indicating that the url is incorrect.

**Comment by tomhughes** [comment]
The problem is that rails is coercing the ID to an integer and `"22)".to_i` in ruby actually gives 22 so it manages to find the record but then blows up trying to generate URLs in the page.
