### ISSUE TITLE
[Translation/DE] bridge=boardwalk should not be translated as "Strandpromenade"

### ISSUE THREAD

**Issue by spixi** [openstreetmap/openstreetmap-website#3866]
### URL

https://www.openstreetmap.org/way/56312785

### How to reproduce the issue?

`bridge=boardwalk` is erronously translated to German as "Strandpromenade" (which is literally a promenade along a beach). However, boardwalks also may appear in wetland like marshes or bogs. Nobody would call this as a "Strandpromenade" in German. The correct translation would be "Holzsteg".

Examples:
https://www.openstreetmap.org/way/56312785
https://www.openstreetmap.org/way/843249394

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/3192596/210057646-30f1c358-1173-4128-b162-ba4fe1512913.png)

**Comment by spixi** [comment]
Addition: "Holzpfad" would only be suitable for `surface=wood`. There may be boardwalks with other surfaces like `surface=metal`. A surface-neutral translation would be "Bohlenweg".

**Comment by mmd-osm** [comment]
Please refer to https://translatewiki.net/wiki/Translating:OpenStreetMap on how to fix translation issues.
