### ISSUE TITLE
Untranslatable strings 4 (GraphHopper)

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#3882]
https://osm.org/directions?engine=graphhopper_car&route=40.7860%2C-73.4478%3B40.8097%2C-74.4008#map=10/40.8320/-73.9160

Messages are partly in English, partly in a local language. How to fix them?
"Trzymaj się prawej strony `and take` NY 110 South `toward` Amityville"
"Trzymaj się prawej strony `and drive toward` Cross Island Parkway North, Whitestone Bridge"

**Comment by tomhughes** [comment]
That text all comes from GraphHopper.

We do pass it the locale and it does translate some stuff but apparently not everything - it needs to be reported to GraphHopper though as there's nothing we can do.
