### ISSUE TITLE
Don't treat "@" as a part of an email address in :conditional: tags

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#3884]
Some tags, such as `maxweight:conditional`, `maxspeed:conditional` or `agricultural:condtitional` use the "@" sign.
You shouldn't turn every something@something into an email address.

![conditional](https://user-images.githubusercontent.com/57260466/211374893-346b751e-85e0-49b4-b156-f5eb49141d4d.png)

I know that probably there should be spaces, but still it should not automatically create a link to the email. Such links should be created only for `email` and `contact:email` tags.

So we can exclude `*conditional*` tags from this automatic convertion or restrict it to `email` and `contact:email` tags only.

**Comment by tomhughes** [comment]
I suspect this just the generic behaviour of applying the auto linker and hard to avoid - we don't want to have to special case which tags can be links.

**Comment by tomhughes** [comment]
Maybe not... It seems we do it manually (https://github.com/openstreetmap/openstreetmap-website/blob/master/app/helpers/browse_tags_helper.rb#L128) but `URI::MailTo::EMAIL_REGEXP` is very generous in what it accepts as the domain...

**Comment by maro-21** [comment]
So at least modify this function to mark `something@something.some` as an email address, not `something@something` :-)

**Comment by tomhughes** [comment]
Well that's my point, but that's not our regexp so we don't control it - it come from ruby's URI library.
