### ISSUE TITLE
Allow translation of distances in directions output

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#3888]
Where: https://www.openstreetmap.org/directions

There are no spaces between numbers and units.
Ideally it should be a non-breaking space.
https://english.stackexchange.com/a/2911

Example:
https://osm.org/directions?engine=graphhopper_car&route=40.7182%2C-73.8983%3B40.7522%2C-74.1812

![spaces](https://user-images.githubusercontent.com/57260466/211626313-668c4da0-a89b-46dc-9a7d-245c73f21634.png)

**Comment by tomhughes** [comment]
Why do you think there should be a space? It wouldn't be normal in English.

**Comment by tomhughes** [comment]
I mean a space isn't wrong. but neither is not having one in my experience. Maybe @systemed has some copy editor thoughts on the subject...

**Comment by systemed** [comment]
It's more usual (though not universal) in British English to omit the space. See, for example, https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#measurements.

**Comment by maro-21** [comment]
So allow to add spaces in other languages, because in Polish it is incorrect.

**Comment by maro-21** [comment]
I think in English there should be a space too. Because meters are SI units. I don't know how it is with feet or how is it in Asian languages.
https://english.stackexchange.com/questions/15953/how-should-i-write-units
https://en.wikipedia.org/wiki/International_System_of_Units#Unit_symbols_and_the_values_of_quantities
