### ISSUE TITLE
wrong description for Browse.tag details.wiki link.key

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#3896]
`Browse.tag details.wiki link.key`: _The wiki description page for the %{key} tag_
Should be: _The wiki description page for the %{key} **key**_

**Comment by tomhughes** [comment]
Why? That's certainly not how we normally refer to tags in OpenStreetMap.

Yes at a database level we talk about, from a technical point of view, keys and values but at the human level we just talk about tags.

**Comment by maro-21** [comment]
This is how it is defined - a key is e.g. `amenity` and a tag is e.g. `amenity=parking`.

**Comment by tomhughes** [comment]
Well yes and no - tag is used in both senses. Nobody would talk about "the highway key" they would about "the highway tag" meaning the whole family of highway tags.

**Comment by tomhughes** [comment]
I've looked at the context of this now and I'm happy this is correct and key would be wrong so I'm going to close this.
