### ISSUE TITLE
Add "cannabis dispensary" place category

### ISSUE THREAD

**Issue by TalOrenshtein** [openstreetmap/openstreetmap-website#3897]
### Problem

Basically title. The lack of this category make it impossible to add information about those kinds of businesses.

**Comment by tomhughes** [comment]
Add it where? What part of the user interface are you looking to add it to?

**Comment by tomhughes** [comment]
I'm guessing that you want to add it to the presets in the iD editor that is embedded in the site? If so then https://github.com/openstreetmap/id-tagging-schema/issues is the place where you need to make your request.

It's not impossible to add them without that though as you can always add tags manually if there isn't a suitable preset.
