### ISSUE TITLE
Add the Location Panel to the map viewer and display it by default

### ISSUE THREAD

**Issue by joper34** [openstreetmap/openstreetmap-website#3901]
### Problem

The editor has a Location Panel that can be invoked by pressing CTRL + SHIFT + L.

The Location Panel would be very helpful for users that are simply viewing the map data at OpenStreetMap.org.

### Description

This feature request is to include the Location Panel in the map viewer and display it by default.

**Comment by tomhughes** [comment]
The viewer is totally different technology that is entirely unrelated to iD so there is nothing there to do that.
