### ISSUE TITLE
Tutorial: Navigation text is cut off on the left side

### ISSUE THREAD

**Issue by momentmal** [openstreetmap/openstreetmap-website#3902]
### URL

http://www.openstreetmap.org/edit?editor=id#walkthrough=true

### How to reproduce the issue?

I had Chrome open in a widescreen resolution (3440x1440) and started the tutorial as a fresh user who just logged in.
In the second step ("Navigation") of the tutorial, the text is severely cut off to the left.
Lowering the width of the browser window does not help.

Workaround/Temporal fix was to find a link to the tutorial (because when closing the tab end revisiting the website, the tutorial does not appear in edit mode anymore and I couldn't find a way to start it again) and have the browser already at a smaller width before click the tutorial link (which appears to be http://www.openstreetmap.org/edit?editor=id#walkthrough=true )

Btw: Doing the steps above again a second time does not seem to reproduce the issue, so it might be restricted to a newly created user, or similar edge case conditions.

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/9054832/213206960-34613361-2156-465f-b10e-e03556582b89.png)

**Comment by tomhughes** [comment]
Issues with the editor need to be filed at https://github.com/openstreetmap/iD as the menu presented when you opened this explained if you read the list of options.

**Comment by momentmal** [comment]
> Issues with the editor need to be filed at https://github.com/openstreetmap/iD as the menu presented when you opened this explained if you read the list of options.

thanks! i found an existing issue there with the same problem 👌
https://github.com/openstreetmap/iD/issues/9363
