### ISSUE TITLE
I thought I already granted access

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3909]
But I just granted access yesterday. Why is it asking me again? Okay it's true I used a different cell phone, but it's still my same account,  no?
> The application Mapwarper.net Login is requesting access to your account, jidanni. Please check whether you would like the application to have the following capabilities. You may choose as many or as few as you like.

I mean it should be like marriage vows, you only need to say them once, till you get a divorce. Not say them every time you come home.

**Comment by tomhughes** [comment]
That's entirely up to the application - what it should do is remember your access token but if it chooses not to do so then you will need to reauthorise it.

**Comment by HolgerJeromin** [comment]
>> Okay it's true I used a different cell phone, but it's still my same account, no?

> what it should do is remember your access token but if it chooses not to do so then you will need to reauthorise it.

A local application can not do that.
And yes, github for example remembers the app and does not ask again if the request is recurring for the same but grant it.
