### ISSUE TITLE
cursor pointer on marker in #openstreetmaps

### ISSUE THREAD

**Issue by GLucaFrassineti** [openstreetmap/openstreetmap-website#3914]
I have this code with openstreetmaps (is a cicle, then I have more marker named marker1, marker2 ,marker3 and so on), but property curosor: pointer dont workk (I tried with a lot of browser of course). 

```
    // Create a marker feature 1    
    var marker1 = new ol.Feature({
        geometry: new ol.geom.Point(ol.proj.fromLonLat([14.3619382, 46.0649361])),
        name: 'some text',
        description: 'other some text'
    });

    // Create a marker style 1  
    var markerStyle1 = new ol.style.Style({
        image: new ol.style.Icon({
        src: '/assets/images/ico.png',
        scale: 1            }),
        cursor: 'pointer'
    });
            
    // Set style to marker feature 1    
    marker1.setStyle(markerStyle1);

    // Add the marker feature 1 to the vector source
    vectorSource.addFeature(marker1);
```
    
    Also tried with css:

```
.ol-marker .ol-icon {
  cursor: pointer;
}
```
the same, dont work :( 
Someone can help me plese? 
Thanks in advanced

**Comment by tomhughes** [comment]
This does not appear to be an issue with the web site so it if off topic here.

Please use https://community.openstreetmap.org/help for help using OpenStreetMap.

**Comment by tomhughes** [comment]
To be honest this isn't an OSM problem at and you'd be better off asking in a forum related to whatever toolkit you're using, which you didn't specify but which I guess is OpenLayers?
