### ISSUE TITLE
Notes are missing and return error 500

### ISSUE THREAD

**Issue by tordans** [openstreetmap/openstreetmap-website#3917]
### URL

https://www.openstreetmap.org/note/3533103

### How to reproduce the issue?

# A

1. Open https://www.openstreetmap.org/note/3533103
2. ==> Error 500, should be a node

# B

1. Open https://www.openstreetmap.org/note/3540073#map=17/52.47257/13.43322&layers=N
2. ==> Should have more than 1 open node

API returns one https://www.openstreetmap.org/api/0.6/notes.json?bbox=13.429101705551147,52.47160590360475,13.440345525741579,52.47378871279819

It looks like, only notes created recently are visible, but older active notes are not.

---

FYI @SupaplexOSM

**Comment by tordans** [comment]
Update: This App shows the node https://ent8r.github.io/NotesReview/?view=map&map=16%2F52.4728%2F13.4338&bbox=13.4188%2C52.4705%2C13.4488%2C52.4751&apply-bbox=true&status=all&anonymous=hide

But clicking on "open on osm org" results in the error above.

**Comment by tordans** [comment]
Update 2: 

It looks like this might be two issue…

# 1

The node above is created by a user account that was not supposed to do anything than hold OSMCha filter. This account is currently blocked. `osmberlin_changeset_review`. So this is the blocked-user-node-broken issue (a Duplicate).

NOW the node is visible, because Supaplex030 commented…

# 2

But we also have JS Errors  `Uncaught TypeError: Cannot read properties of undefined (reading 'text')`

**Comment by tordans** [comment]
Update 3:

Now all is visible again. No JS Errors.  

Super weird, I will close this for now …

**Comment by AntonKhorev** [comment]
This is not going to get fixed because https://github.com/openstreetmap/openstreetmap-website/issues/3831

**Comment by tomhughes** [comment]
This will be a duplicate of #2146 and #3831 is the plan for fixing it - the first part (#3911) was merged this week.

**Comment by AntonKhorev** [comment]
js errors are fixed in https://github.com/openstreetmap/openstreetmap-website/pull/3617 but fixing them is not part of plans because "The output of the API has to remain the same for now"

**Comment by gravitystorm** [comment]
> fixing them is not part of plans

That's not true.

**Comment by AntonKhorev** [comment]
> That's not true.

Are you going to change the API, like adding a guarantee that there's at least one comment per note?
