### ISSUE TITLE
User Name Spoofing

### ISSUE THREAD

**Issue by map-per** [openstreetmap/openstreetmap-website#3919]
### Problem

It is possible to spoof users by creating fake user accounts with names that look identical to the name of the real account but use different Unicode characters. 

### Description

This happened yesterday with this account:
real account: https://www.openstreetmap.org/user/limes11
fake account: https://www.openstreetmap.org/user/Iimes11
The real account starts with a lower case 'L' and the fake account starts with an upper case 'i'.

The same thing is possible with e.g. the character 'a' which looks identical in Latin and Cyrillic alphabet. There is a good summary mentioning way more problematic characters on Wikipedia (1).

A solution to this might be to check whether an account with a similar name already exists when creating a new account (looks like there already is a check that prohibits names that just differ in lower-/uppercase) or to prohibit the use of characters from more than one alphabets in new usernames.

(1) https://en.wikipedia.org/wiki/IDN_homograph_attack

**Comment by tomhughes** [comment]
The problem is then you get into the question of deciding how similar is too similar - our position has always been that a name is just a name and we don't police them or give people any special privileges over particular names so picking a name doesn't give you some right to exclude a set of other names just because they happen to be in some way similar.

**Comment by map-per** [comment]
Ok, I guess this was/is a very extreme and rare case of vandalism anyway

**Comment by matkoniecz** [comment]
And note that in the end it is almost impossible to fully block something like this. Either way, malicious users should be reported.
