### ISSUE TITLE
Notes buttons pushed onto second line for moderators

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/openstreetmap-website#392]
After entering text to comment on an existing note, the buttons take up two lines for me

Without text entered: ![notesoneline](https://f.cloud.github.com/assets/1190866/876773/9a8c2f64-f8db-11e2-8d29-545771b01939.png)

With text: ![notesbuttons](https://f.cloud.github.com/assets/1190866/876769/6ff01cd4-f8db-11e2-93db-0daa44c3a851.png)

**Comment by mmd-osm** [comment]
The Issue is obsolete, notes are in the sidebar these days.
