### ISSUE TITLE
issue with pin properties save

### ISSUE THREAD

**Issue by Mr-aert** [openstreetmap/openstreetmap-website#3927]
### How to reproduce the issue?

We created a pin and saved our changes.
When we edit its properties (for ex: name) and click on the save button, we have an error 3 times out of 4:
 

### Screenshot(s) or anything else?

![image003](https://user-images.githubusercontent.com/37814984/218083009-1f96a8ef-9e88-4e6e-bde5-29c212129729.png)

**Comment by tomhughes** [comment]
I have no idea what that is a picture of but it's not www.openstreetmap.org so it's nothing to do with us.

**Comment by tomhughes** [comment]
If I had to guess I assume that is umap.openstreetmap.fr in which case you need to report it to the the operators or that umap instance, or at least to the umap issue tracker.
