### ISSUE TITLE
Map Marker only shows when iframe loads on the host page load

### ISSUE THREAD

**Issue by Joheyy** [openstreetmap/openstreetmap-website#3929]
### URL

https://www.openstreetmap.org/export/embed.html?bbox=-21.777659654617313%2C64.09986306895152%2C-21.76714539527893%2C64.102761455032&amp;layer=mapnik&amp;marker=64.1013111281992%2C-21.77240252494812

### How to reproduce the issue?

1. Go to the main page and select something
2. Use the share functionality
3. Generate an iframe with the HTML button with marker enabled
4. Embed the iframe in some website
5. Cut out the src attribute
6. Set the src attribute some time later via javascript

As you can now see, the marker is not visible.

(It's the same behavior when opening the embed URL itself, see the URL that I have linked in this issue)

### Screenshot(s) or anything else?

I think this issue is significant since because of the GDPR I have to ask the user of my website for permission before loading the map.
So I - like every other EU citizen - can not just load it with the html file like it was intended.

My guess why this issue happens is that the function that fetches the marker and places it only gets called while loading the parent page. (Maybe the window.onload event)

Here is a comparison between the behavior of a html load:

![Screenshot from 2023-02-10 16-14-27](https://user-images.githubusercontent.com/44101694/218134457-0c41d763-2dfd-4819-a0ce-cc320d0145ac.png)

![Screenshot from 2023-02-10 16-14-41](https://user-images.githubusercontent.com/44101694/218134421-14790372-eb9d-4d90-9e6b-12cff1b368e3.png)

... and a javascript load

![Screenshot from 2023-02-10 16-26-56](https://user-images.githubusercontent.com/44101694/218134560-e888ba63-079a-4109-a0b1-679cdcd6ad38.png)

![Screenshot from 2023-02-10 16-21-26](https://user-images.githubusercontent.com/44101694/218134531-81b33751-529f-4faa-9a13-9feedfca2f42.png)

You can clearly see that in the javascript case there is no get request for the marker.

**Comment by Joheyy** [comment]
One thing to add: Behaviour is consistens across all modern rendering engines. 
Tested in: Chrome, Firefox and Safari

**Comment by tomhughes** [comment]
Your diagnosis makes no sense as a frame (or at least a cross domain one like here) has no access to the parent page.

You're correct that all the work is done in `window.onload` but for a frame that will be the load of the frame not the parent document and if that wasn't running then nothing would be displayed as it sets up all the map layers not just the marker.

My guess is that you're mangling the parameters or something when trying to patch in the URL later.

**Comment by tomhughes** [comment]
You've even demonstrated the problem with the URL in your initial report - if you open that the marker is missing because the `&` characters have been escaped as `&amp;`.

**Comment by Joheyy** [comment]
You're correct. 
Sorry, should've payed closer attention to the URL.
