### ISSUE TITLE
"Hide" for notes is unclear

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/openstreetmap-website#393]
Users with the moderator role see a button labelled "Hide" to delete notes. Although technically accurate because it hides the note from everyone, we normally speak of deleting or removing the types of content that this button would be used on.

I suggest changing Hide to Delete or Remove, with a red background to reflect the special nature of the button.

**Comment by mmd-osm** [comment]
Diary entries use the same concept of "Hide this entry". For the sake of consistency this would have to be changed as well. Given the small number of users and the low impact of this change, this is probably not worth it. Closing here.

![image](https://github.com/openstreetmap/openstreetmap-website/assets/5842757/1ba4694d-97f9-4a29-8c0e-04c686d2c287)
