### ISSUE TITLE
Vagrant install instructions don't work anymore

### ISSUE THREAD

**Issue by amandasaurus** [openstreetmap/openstreetmap-website#3944]
### How to reproduce the issue?

IME the [current Vagrant install instructions](https://github.com/openstreetmap/openstreetmap-website/blob/87657108f6bd2a4afa41760dff1947a8349b28f8/VAGRANT.md) don't work. It runs the provision script as root, and (IIRC) bundler refuses to run as root now and fails to install the project.

**Comment by tomhughes** [comment]
Nobody understands or maintains the vagrant nonsense and we should remove it.

**Comment by gravitystorm** [comment]
I've been running the vagrant instructions (over and over) today, and they worked for me. So unfortunately I can't debug this further myself.

@amandasaurus if you can provide any more details, or if you have success with the current version, I'd love to hear more.

**Comment by chrisZingel** [comment]
I did a clean install today since I wanted to take this project for a spin. It was a pleasant experience to go from zero to hero with a fully running application.

Versions used:
Vagrant 2.3.7
Virtual Box 7.0.8

Maybe @amandasaurus  could try it again with the latest versions and close this issue in the meantime.

**Comment by gravitystorm** [comment]
Thanks @chrisZingel , glad to hear it worked for you too. 

@amandasaurus please feel free to reopen (or open another issue) if you have problems with the vagrant instructions - since we've now got confirmation that the current instructions work (and not just from me!) then I'll close this issue.
