### ISSUE TITLE
Query can't find big wastewater plant

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3954]
On [this big wastewater treatment plant](https://www.openstreetmap.org/relation/1866560) click [query](https://www.openstreetmap.org/query?lat=37.5450&lon=-122.2291).
It is not listed. Maybe because the person who put it on the map didn't do it right?
Hmm, no problem with this [other plant](https://www.openstreetmap.org/way/30678902). I suppose it is a relation vs. way problem.

**Comment by tomhughes** [comment]
You'll find it fine if you click on the border of it, but not by clicking in the middle because the search radius won't overlap any part of the geometry and it doesn't qualify as an area (per whatever rules overpass uses to determine areas) so won't show up in the enclosing objects search.
