### ISSUE TITLE
broken order on note creation dates with some RTL usernames

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#3964]
![screen01](https://user-images.githubusercontent.com/899988/223801754-36293412-2e00-420f-be1a-50180c0f94ff.png)

day counter should be after username, also RTL one, at least in English

may be subset of #3428

definitely subset of #3427

**Comment by AntonKhorev** [comment]
Can't see it here: https://www.openstreetmap.org/note/1733450

Maybe already fixed.

**Comment by matkoniecz** [comment]
why I left no link?

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/note/3574640

![screen](https://github.com/openstreetmap/openstreetmap-website/assets/899988/9c777b0b-1624-4094-827f-666a36c2aa75)

**Comment by bezdna** [comment]
![image](https://github.com/openstreetmap/openstreetmap-website/assets/518939/c4e227d2-a178-4083-84f5-9d04f40d60bf)
this is specific browser

![image](https://github.com/openstreetmap/openstreetmap-website/assets/518939/de584fba-67ce-4fe8-8c11-f9b76d8b3ba5)
need add attribute dir="rtl" to tag have  RTL Language Localization

**Comment by AntonKhorev** [comment]
dir=anything (including literally "anything" and empty value) also works

**Comment by mmd-osm** [comment]
#3427 is related

**Comment by AntonKhorev** [comment]
Have to pick new examples because relative dates change.

Current example:
https://www.openstreetmap.org/note/4235525
![image](https://github.com/user-attachments/assets/412943ef-a23a-4977-958f-9f0c106b5ee8)

**Comment by AntonKhorev** [comment]
Seems fixed now:
![image](https://github.com/user-attachments/assets/3a9b9ecf-070b-4c9a-a191-b885904c0a10)
