### ISSUE TITLE
Add spinner while waiting for editor to load

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3965]
### Problem

On slower networks, or slower laptops, when the user clicks `edit`,
the screen becomes white, and nothing happens for
about ten seconds, and then finally the editor loads.

Perhaps add a spinner in the middle of the screen.

No, the browser's spinners don't spin in this case.

No, you won't notice the problem on newer networks or hardware.

**Comment by tomhughes** [comment]
That's something you would need to take up with the iD authors as the delay is presumably in iD starting up and they have control of the display area at that point.
