### ISSUE TITLE
Show notes more often

### ISSUE THREAD

**Issue by Cj-Malone** [openstreetmap/openstreetmap-website#3971]
### Problem

I often have to re enable the notes layer, it seems to reset to be disabled quite often. And because I often forget to re enable it I solve less notes.

### Description

I think notes should be a more sticky setting, or potentially **enabled by default**.

**Comment by tomhughes** [comment]
It's already included in the layers cookie so I don't know how we could make it more sticky.

Personally I have the opposite problem to you, that I often come back to find it's on for some reason and have to turn it off.

Certainly we're not going to be making it the default, both because it's pretty annoying and because of the load it would likely put on the server.

Unless you can identify some specific case where it gets disabled when you don't think it should I don't think there's much we can do - as it stands this report is too vague to be actionable.

**Comment by Cj-Malone** [comment]
> It's already included in the layers cookie

I don't have an issue staying signed in. Do the different cookies have different TTL so something?

> so I don't know how we could make it more sticky

A user pref would be more sticky than a cookie, but that obviously has issues too.

As always, thanks for the discussion.

**Comment by tomhughes** [comment]
The cookie (the `_osm_location` one) has a ten year lifetime while logins are only valid for as long as the browser is open.

**Comment by Cj-Malone** [comment]
I just restarted Firefox twice, I stayed signed in, and notes stayed enabled so there must be a difference between the docs and the reality of that "as long as the browser is open".

So that `_osm_location` contains both the location and the open layers? And that gets overridden when I navigate to a new URL with a `#`? I think I've found the issue.

I often use OSM Smart Menu to switch between OSM, Mapillary, FHDOT and Survey Me. That sets the location in the url, but not any layers that were active.

**Comment by tomhughes** [comment]
Yes although cookies without a timeout are session cookies that traditionally vanish when you quit the browser many browsers these days have optional session preservation for at least some types of restart which confuses things.

The location cookie encodes both the location and the active layers yes - basically the state of your map view - so any time you visit the site it will be updated and if you visit a view that has the note layer disabled then that will update the location cookie to reflect that.

**Comment by Cj-Malone** [comment]
Also it seems it's not just links with `#`, enable notes then visit https://www.openstreetmap.org/?mlat=53.32607&mlon=-1.49033 and it will also disable the notes layer.

For links that I control, is there a way for me to link to a specific location without enabling or disabling a users notes preference?

**Comment by mmd-osm** [comment]
The issue here is in osm.js.erb: if mlon and mlat are set, we're not initializing "loc" from the _osm_location cookie. Later on we cannot set mapParams.layers, since "loc" should be nil at this time. This impacts both the notes layer, as well as the map layer.

```javascript
    } else if (params.mlon && params.mlat) {
      mapParams.lon = parseFloat(params.mlon);
      mapParams.lat = parseFloat(params.mlat);
      mapParams.zoom = parseInt(params.zoom || 12);
    } else if (loc = Cookies.get('_osm_location')) {
      loc = loc.split("|");
      mapParams.lon = parseFloat(loc[0]);
      mapParams.lat = parseFloat(loc[1]);
      mapParams.zoom = parseInt(loc[2]);
```

```javascript
    mapParams.layers = hash.layers || (loc && loc[3]) || '';
```

//CC:  fyi @AntonKhorev

**Comment by mmd-osm** [comment]
@Cj-Malone : issue should be fixed now.

**Comment by Cj-Malone** [comment]
Thank you @mmd-osm I really appreciate this.
