### ISSUE TITLE
dragging the map with mouse click-hold does not work

### ISSUE THREAD

**Issue by phu9Suop** [openstreetmap/openstreetmap-website#3977]
### How to reproduce the issue?

1. I use notebook with devuan chimaera OS
2. I use firefox 102.9.0esr (64-Bit) with ublock origin,  
3. I block some # of websites via dns
4. I go to  openstreetmap.org, left-click the map , hold button and drag the map , no success
5. same dragging the map works on nominatim.openstreetmap.org, https://leafletjs.com/ , maps.google.com and 
6. openstreetmap.org on another PC with debian / firefox (but not in my possession)
7. verified that no site from openstreetmap.org is blocked in ublock-origin
Probably some script is blocked to the browser. 
How to unblock the dragging function on my apparatus?

**Comment by tomhughes** [comment]
How are we supposed to know how to unbreak your system?

If you're blocking things then try unblocking them and see if that helps!

Given nobody else has this problem it's clearly a problem with the way you have configured your system rather than anything we have done.
