### ISSUE TITLE
Use user's preferred language to display labels in foreign countries

### ISSUE THREAD

**Issue by sjvudp** [openstreetmap/openstreetmap-website#3979]
### Problem

Say I can read German and English, but visit (e.g.) China on the map. Then all the labels are shown in Chinese (which are rather useless for me). Labels shown in one of the preferred languages would be (well) preferable.
As I found no settings in the OSM page, I'm assuming it is not settable yet.

### Description

Allow setting the preferred label language, or (preferably) derive the user's preference from the languages the browser sends in the HTTP headers.
If such a setting exists already, but is hidden, add some link on the main page to show it.

### Screenshots

![Screenshot 2023-03-21 at 22-30-05 OpenStreetMap](https://user-images.githubusercontent.com/6734808/226746326-05dae570-792e-4012-a908-8297de07b1f6.png)

**Comment by tomhughes** [comment]
The map is a prerendered image and this project has no control over the labels shown - showing per country labels is dependent on the move to a vector tile stack and this is not the place to deal with that.

**Comment by sjvudp** [comment]
OK, I wasn't aware of that; seems most vector maps do it differently.
Anyway the question is: Was it clever to do it like that?

**Comment by tomhughes** [comment]
Well that's the point, we're not using vector tiles yet.

Vector tiles didn't exist in 2007 or so when our tile stack was born and what we have now is an iterative development of that original stack - we very much want to move to vectors but it's not a trivial task and we've been trying to encourage things in that direction for some time.

None of that is anything to do with this repository though - this code just consumes the available tiles from other projects.

**Comment by sjvudp** [comment]
Interestingly when visiting [OpenStreetMap Deutschland - Karte](https://openstreetmap.de/karte/) there are labels in another language (i.e.: German):

![Screenshot 2023-03-22 at 22-37-07 OpenStreetMap Deutschland - Karte](https://user-images.githubusercontent.com/6734808/227044340-0e1c5941-00c7-4008-b70a-7d713aaca925.png)

**Comment by SomeoneElseOSM** [comment]
> As I found no settings in the OSM page, 

You've already mentioned external sites that show OSM data in different languages (such as openstreetmap.de; there are lots of others), but be aware that  2 of the 6 map renderings at openstreetmap.org show "local + English" names - the cycle map and the transport map.
