### ISSUE TITLE
Place a mark to show the result of a location search

### ISSUE THREAD

**Issue by sjvudp** [openstreetmap/openstreetmap-website#3980]
### Problem

If you search for some place (e.g. by specifying coordinates), OSM shows some part of a map, but it does not (in contrast to Google maps) a marker where the location searched actually is.
Instead such marker is only displayed while you hover the mouse over the coordinates.
Specifically when zooming in, the lack of a (temporarily) persistent marker makes the job of keeping the location more difficult than it has to be.

### Description

Place a point maker on the result of a location search. Maybe even (if the result is not point-type) draw an outline marking the search result.
Such marker should be "permanent" until the used decides to dismiss it.
A probably useful extension could be to allow multiple "permanent" markers on the map.

### Screenshots

Example (you can try to enter the same coordinates):
![Screenshot 2023-03-21 at 22-43-32 OpenStreetMap](https://user-images.githubusercontent.com/6734808/226748776-8e492709-f0f4-44be-a242-7d73786c412e.jpg)

**Comment by tomhughes** [comment]
A marker should be shown as soon as you put your mouse pointer over a result, of which there may be more than one.

**Comment by sjvudp** [comment]
> A marker should be shown as soon as you put your mouse pointer over a result, of which there may be more than one.

As I wrote: *As long*as I hover with the mouse over the coordinates on the left, I see a marker on the (right) map.
However the mouse wheel only works for zooming when I move the mouse inside the map area.
But yes: When you click an object from the search results, a permanent marker is placed.
Still I think a generic marker for any position would make sense.

**Comment by danieldegroot2** [comment]
See also #3991.

**Comment by sjvudp** [comment]
> See also #3991.

I think that is a different issue/solution.

**Comment by fgnievinski** [comment]
the current behavior is to zoom in on the first search result. I support the suggestion to, additionally, draw a marker. this change would help specially mobile users, which are unable to hover the mouse cursor (only to click). example:
https://www.openstreetmap.org/#map=18/-30.07547/-51.14875&layers=C
