### ISSUE TITLE
CSS Error using docker

### ISSUE THREAD

**Issue by icemagno** [openstreetmap/openstreetmap-website#3984]
### How to reproduce the issue?

1. Install from Docker
2. Access the server URL
3. The error is:

```
SassC::SyntaxError in Site#index
Showing /app/app/views/layouts/map.html.erb where line # raised:

Error: Invalid CSS after "l": expected 1 selector or at-rule, was "link ../common.scss"
        on line 1:1 of app/assets/stylesheets/ltr/common.scss
>> link ../common.scss
```

**Comment by icemagno** [comment]
Besides this, there is no ```small.scss```

**Comment by tomhughes** [comment]
Correct - it was removed in 5ab682dbbdc0bc4034d1c93aae3d082dae09fa65 and is not mentioned anywhere in the source so why do you care if it exists?

**Comment by gravitystorm** [comment]
> "link ../common.scss"

@icemagno Are you using Windows on the host? Is this perhaps a symlink error?

**Comment by gravitystorm** [comment]
> Correct - it was removed in [5ab682d](https://github.com/openstreetmap/openstreetmap-website/commit/5ab682dbbdc0bc4034d1c93aae3d082dae09fa65) and is not mentioned anywhere in the source so why do you care if it exists?

See https://github.com/openstreetmap/openstreetmap-website/pull/3985

**Comment by icemagno** [comment]
@gravitystorm 

No. I'm not using Windows at all. I'm in a Ubuntu host building a Docker image and running it in same Ubuntu server.

The frontend is complaining because there is a ```link ../common.scss``` inside ```app/assets/stylesheets/ltr/common.scss``` as you can see in my ticket.

And so for ```app/assets/stylesheets/ltr/small.scss``` but there is no ```small.scss``` anywhere.

https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/stylesheets/ltr/small.scss

The interpreter could not translate the word ```link``` anyway so I need to copy https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/stylesheets/common.scss to "ltr" and "rtl" folders and just ignore small.scss because the frontend was not care about it anyway.

I confess I'm not using Docker Compose because I don't like it ( don't ask. I simply don't like). Here are my steps:

First I've created the config files to point to my database. Nothing wrong about that. 

Then:

```docker build --tag=osm-web:1.0 --rm=true . ``` from the repo root folder and then

```
docker run --name osmseed-web --hostname osmseed-web --network mynetwork \
	-v /srv/osm-seed-web/app-tmp:/app/tmp \
	-v /srv/osm-seed-web/app-storage:/app/storage \
	-p 36300:3000 \
    -d osm-web:1.0 bundle exec rails s -p 3000 -b '0.0.0.0'
```

Then I face the error I mentioned. My workaround was just copy common.scss from stylesheets folder to "ltr" and "rtl" folders and all goes fine.

**Comment by gravitystorm** [comment]
> The frontend is complaining because there is a `link ../common.scss` inside `app/assets/stylesheets/ltr/common.scss` as you can see in my ticket.

Right, and that's deliberate. It's supposed to be a symlink. So the question is why is the symlink not working properly, because the sass compiler is seeing a file with the contents "link ../common.scss" instead of the contents of the target file.

We run the whole Docker setup in CI, and it doesn't have the same problem. So now we need to figure out what's different about your environment that makes the symlink not work for you.

I can see your docker command doesn't mount the current folder as `/app` within the container. That's the biggest difference that I can see with the docker-compose.yml section that you are replicating with that command line. Does this mean that you've changed the Dockerfile to add the code into the container?

**Comment by icemagno** [comment]
Here is my new Dockerfile to solve some problems like:

1. Yarn is not installed correctly  (https://blndxp.wordpress.com/2020/04/28/yarn-install-error-errno-2-no-such-file-or-directory-install/)
2. do the dummy config copy ( and the workaround above)
3. Copy all the app folder to the container so it can be build

```
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Install system packages then clean up to minimize image size
RUN apt-get update \
 && apt-get install --no-install-recommends -y \
      build-essential \
      curl \
      default-jre-headless \
      file \
      firefox-geckodriver \
      libarchive-dev \
      libffi-dev \
      libgd-dev \
      libpq-dev \
      libsasl2-dev \
      libvips-dev \
      libxml2-dev \
      libxslt1-dev \
      locales \
      nodejs \
      postgresql-client \
      ruby2.7 \
      ruby2.7-dev \
      tzdata \
      unzip \
      gnupg 

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
 
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y yarn
RUN apt-get -y upgrade

RUN apt-get clean \
 && rm -rf /var/lib/apt/lists/*

ENV DEBIAN_FRONTEND=dialog

# Setup app location
RUN mkdir -p /app
WORKDIR /app

COPY ./ /app/

# Install Ruby packages
ADD Gemfile Gemfile.lock /app/
RUN gem install bundler \
 && bundle install

# Install NodeJS packages using yarn
ADD package.json yarn.lock /app/
ADD bin/yarn /app/bin/
RUN yarn config set ignore-engines true
RUN bundle exec yarn install
RUN touch config/settings.local.yml
RUN cp app/assets/stylesheets/common.scss app/assets/stylesheets/ltr/
RUN cp app/assets/stylesheets/common.scss app/assets/stylesheets/rtl/common.r2.scss
```

**Comment by icemagno** [comment]
@gravitystorm I think I found the problem ( and I would like to sorry if I confirm it).

Seems I've checked out the repo inside a Windows machine and then do the copy to the linux server instead clone it directly into the server.

I can't remember that ... I'll do it all again from the beginning and tell you.

**Comment by icemagno** [comment]
Well...

SORRY !

The problem was that. Can I close this ?

**Comment by gravitystorm** [comment]
> SORRY !

No worries, glad we got to the bottom of it.
