### ISSUE TITLE
How can I configure iD editor to work?

### ISSUE THREAD

**Issue by icemagno** [openstreetmap/openstreetmap-website#3987]
### Problem

After having the website running, I'm trying to edit something but I'm facing the message "iD not configured".

### Description

Already created a user and gave it administrator rights (see nothing changed about this but it is not my question).

I've found some tips around there telling to configure an OAuth key and then put it in settings file but they are a bit old and the key names are different.

**Comment by tomhughes** [comment]
Full the instructions in `CONFIGURE.md` specifically the section on [OAuth Consumer Keys](https://github.com/openstreetmap/openstreetmap-website/blob/master/CONFIGURE.md#oauth-consumer-keys).

**Comment by icemagno** [comment]
Worked. Thanks.

**Comment by icemagno** [comment]
But ...

I'm facing some strange behaviour:

1. Can't get translation to work:

![osm-id-error-02](https://user-images.githubusercontent.com/4127512/227258828-2a429261-e6bf-43c2-a67b-7446efb2c315.png)


2. Some image files are not loaded even they are present in openstreetmap-website/vendor/assets/iD/iD/img :

![osm-id-error-01](https://user-images.githubusercontent.com/4127512/227258929-28dd79d9-78d1-47c5-b337-dc3014ee8a68.png)

any clue ?
