### ISSUE TITLE
Share button unusable on a cell phone

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3988]
When one wants to share their location, one taps the Share button on the right panel. Alas, on a cell phone the Share dialogue completely covers the entire screen! For instance, if we want to add a marker, we  want to see where the marker is going to be.

(More and more people are using cell phones these days.)

**Comment by ayushanand308** [comment]
@jidanni A possible solution can be to limit the size of share dialogue and make it appear on the top instead of right side same as we get the popup on clicking the hamburger icon on top. What do you suggest?

**Comment by jidanni** [comment]
Well all I know is e.g., https://maps.nlsc.gov.tw/
even has a PWA that makes using the site on a cell phone a breeze.

**Comment by Prathm-s** [comment]
Hello @jidanni, I am intreseted in this issue, Could you please assign it to me?

**Comment by jidanni** [comment]
I would love to but I'm not in charge here.
