### ISSUE TITLE
User preferences accepts only ASCII data

### ISSUE THREAD

**Issue by bryceco** [openstreetmap/openstreetmap-website#4001]
### URL

https://api.openstreetmap.org/api/0.6/user/preferences/test

### How to reproduce the issue?

I noticed this with emoji values, and verified it with a ć character. 

> curl -X PUT -d ‘👀’ https://api.openstreetmap.org/api/0.6/user/preferences/test
Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)

**Comment by matkoniecz** [comment]
I guess that for now https://en.wikipedia.org/wiki/Punycode can be used as workaround

**Comment by tomhughes** [comment]
Fixed in #4803.
