### ISSUE TITLE
The communities page doesn't mention the community site 

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#4003]
### Problem

[The communities page](https://www.openstreetmap.org/communities) doesn't mention [the community site](https://community.openstreetmap.org/) .

### Description

Therefore, at the bottom of the former, please add
"For help communities please see [Help](https://www.openstreetmap.org/help)."

**Comment by tomhughes** [comment]
The page is entirely driven by the data in the community index (https://github.com/osmlab/osm-community-index) so that is where any change needs to be made.

**Comment by jidanni** [comment]
I can't post issues to https://github.com/osmlab/osm-community-index .
