### ISSUE TITLE
Incorrectly "renamed" translations on translatewiki

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#4006]
I'm following up on comments that @tomhughes made on commit https://github.com/openstreetmap/openstreetmap-website/commit/9d72cbd0bfaa9f25c5f959320676ab0d4656a6c3 (and fixed in https://github.com/openstreetmap/openstreetmap-website/commit/25f83967dfa30ed4043852c1b2edf5414155d92f) to see if we can figure out what went wrong and how to avoid it happening again.

I found one of the translations on translatewiki: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=site.about.community_driven_1_html&group=out-osm-site&language=de&filter=&optional=1&action=translate

The history of the translation shows that it was an automatic rename (i.e. not copy+paste by a human translator) by [Fuzzybot](https://translatewiki.net/wiki/User:FuzzyBot)

https://translatewiki.net/w/i.php?title=Osm%3ASite.about.community_driven_1_html%2Fde&oldid=11507400&diff=prev&diffmode=source

The automatic renaming (when we change the key without changing the value) is super super helpful, and we haven't had any problems with it before, so I definitely want to keep it. But I'm wondering if anyone has any insight as to why these three translations changes were treated as a rename? The before/after values were different (different interpolations being the most important thing) so I'm surprised this happened. Is Fuzzybot doing some kind of fuzzy matching here? Or is it confused by multiline values in yaml? Or something else?

Secondly, the Translatewiki interface does flag up that there are problems with the translation:

![Screenshot from 2023-04-12 13-34-47](https://user-images.githubusercontent.com/360803/231460120-ff1381d5-25a4-4d9b-90b6-70c7f9ad4a16.png)

If the system knows that there are errors, should we be excluding these from the export?

**Comment by gravitystorm** [comment]
As I expected, [this week's automated sync from translatewiki](https://github.com/openstreetmap/openstreetmap-website/commit/adce63ea6d872ae9a9034218ef4395b8417b12d9) has re-introduced the incorrect translations that @tomhughes fixed earlier this week. So we need an upstream fix.

@translatewiki @Nikerabbit Any thoughts on how we should best tackle this?

**Comment by openbrian** [comment]
Speaking naively here, do we run tests before merging into master?

**Comment by gravitystorm** [comment]
The translatewiki automatic sync is currently committed direct into master.

**Comment by tomhughes** [comment]
I've reverted the broken translations again, and have removed write access from @translatewiki for now until we can resolve this properly.

**Comment by Firefishy** [comment]
@Nikerabbit ^

**Comment by Nikerabbit** [comment]
Acknowledged. I'll ensure we will clean up the mess.

**Comment by Nikerabbit** [comment]
I have deleted translations containing raw html links by looping:
```
curl 'https://translatewiki.net/w/api.php?action=query&format=json&list=search&formatversion=2&srsearch=insource%3Ahref&srnamespace=1222&srlimit=max&srwhat=text&srinfo=&srprop=&srsort=last_edit_desc' | jq '.query .search[].title' -r > deletelist
php /srv/mediawiki/workdir/maintenance/run.php deleteBatch --u FuzzyBot --r "https://github.com/openstreetmap/openstreetmap-website/issues/4006" deletelist
```

I believe this addresses your request. The rename was my mistake when processing incoming changes.

**Comment by tomhughes** [comment]
Thanks. I've turned your write access back on now.

I wonder if it would be better if you opened PRs rather than pushing - is that something you have the technology to do?

**Comment by Nikerabbit** [comment]
We now have the ability to do pull requests from local branches (not from forks).

**Comment by gravitystorm** [comment]
The original problem is now fixed, so I'm going to close this issue.
