### ISSUE TITLE
Import database with osm2pgsql

### ISSUE THREAD

**Issue by alenigrelli** [openstreetmap/openstreetmap-website#4015]
### Problem

Hello! I am trying to import OSM data into my database for Spain using osm2pgsql. However, when I run the import, it creates intermediate tables with names starting with ‘Planet_osm_*’. Instead, I need to save the data into specific tables such as ‘ways’, ‘current_ways’, ‘nodes’, ‘current_nodes’, ‘current_way_nodes’, ‘way_nodes’, etc. I am not sure what the next steps are to achieve this. Can you guide me on how to proceed?

### Screenshots

![image](https://user-images.githubusercontent.com/15861031/233699774-0f6b1994-ebd9-4321-87a1-cd647bc3e078.png)

**Comment by Firefishy** [comment]
osm2pgsql is a tool for creating a database format used for rendering or nominatim. It is not the database format used by this repo.

**Comment by Firefishy** [comment]
https://github.com/openstreetmap/openstreetmap-website/blob/master/CONFIGURE.md has details about how to populate the database.
