### ISSUE TITLE
About Page inaccessible on mobile

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#4019]
That's a great [About Page](https://www.openstreetmap.org/about),

![Screenshot_20230424_171312_Chrome Beta.jpg](https://user-images.githubusercontent.com/1230959/233953920-658dfd58-c3de-46ee-a962-3cf1b6e9ea2e.jpg)

But how is anybody supposed to get there, if there is no three bar menu or otherwise any link to it from the homepage?

![Screenshot_20230424_171412_Chrome Beta.jpg](https://user-images.githubusercontent.com/1230959/233954214-49cc8c79-b64c-47f7-a422-3dde79c9ff4f.jpg)

I swear I was not (chrome zoom) zoomed in. As you see I put the zoom right there for you to see.

**Comment by Firefishy** [comment]
What brand / model of phone? I cannot replicate this on an Android Google Pixel 5.

**Comment by gravitystorm** [comment]
There is a menu button (three horizontal stripes) to the right of the word "OpenStreetMap" in the title. If you press that, then you will (hopefully) see the link to the About page.

I don't know why you see the header (with the logo, the word "OpenStreetMap", and the menu button) on a dark background, it's supposed to be white and when it is dark the menu button is hard to see.

**Comment by jidanni** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1440071

Errr, you see I was using the so-called nifty chrome://flags/#enable-force-dark flag.


I was trying to impress my friends with how all websites left and right had changed into Halloween colors.


So the menu  became so dark that I didn't notice it. If you look real close in the second image above in the upper right corner there's the menu alive and well just dimmed down due to my reckless use of this experimental Chrome flag which I'm not going to be using anymore.

**Comment by gravitystorm** [comment]
@jidanni Thanks for the additional information.

**Comment by HolgerJeromin** [comment]
Chromium flags are experiments for "not ready for the wild" things. Otherwise they would be available in the normal settings.
