### ISSUE TITLE
Reporting an issue as inaccurate or improper.

### ISSUE THREAD

**Issue by IreMapper** [openstreetmap/openstreetmap-website#4022]
There is an issue reported by Osmose that may not an proper issue in the OSM data.  "Barrier blocking highway" is being reported where there is a gate on a path that separates a public path from a private area or security area.  It is also reported where a highway changes from access for all to access only from pedestrians and a point is tagged as a barrier that could be a line of bollards or a 'kissing gate'

**Comment by gravitystorm** [comment]
Hi IreMapper - this isn't the right place to report problems with Osmose. See https://wiki.openstreetmap.org/wiki/Osmose for more information.
