### ISSUE TITLE
Tip users to another way to use their GPXs

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#4027]
Maybe on https://www.openstreetmap.org/traces/new
mention: By the way, did you know about using GPXs as Custom Map Data in iD?

**Comment by mmd-osm** [comment]
I would assume that the first thing new users see on osm.org is the link to "GPS Traces". This page already lists a few uploaded traces by other people, including a link to "Edit Map". Does that suffice to learn how to use GPX traces for editing?
On the same page, they would also see the "Upload a trace" button, which suggests that the user could also upload their own traces. 
I don't see how users would start with https://www.openstreetmap.org/traces/new without noticing the other pages i mentioned.

**Comment by jidanni** [comment]
In fact looking in iD,
> 
> Custom Background Settings
> Enter a tile URL template below.
> 
> Supported WMS tokens:
> {proj}: requested projection (EPSG:3857 only)
> {wkid}: same as proj, but without the EPSG (3857 only)
> {width}, {height}: requested image dimensions (256 only)
> {bbox}: requested bounding box (e.g. minX,minY,maxX,maxY)
> Supported TMS tokens:
> {zoom} or {z}, {x}, {y}: Z/X/Y tile coordinates
> {-y} or {ty}: flipped TMS-style Y coordinates
> {switch:a,b,c}: DNS server multiplexing
> {u}: quadtile (Bing) scheme
> {@2x} or {r}: resolution scale factor
> Example:
> https://tile.openstreetmap.org/{zoom}/{x}/{y}.png
> 
> Enter a url template
> CancelOK

Maybe I was wrong thinking one could see single traces in iD...

**Comment by mmd-osm** [comment]
Both is possible. As a bakground layer, you would see all gpx traces uploaded by all users. When clicking on the  "Edit Map" link i mentioned, you would see one particular GPX highlighted:

Example: https://www.openstreetmap.org/edit?gpx=11385852

![grafik](https://github.com/openstreetmap/openstreetmap-website/assets/5842757/a07bf1f6-c3ba-4beb-8722-25735aa21440)

**Comment by jidanni** [comment]
The problem is if users begin in iD, they will never figure out that it is possible to see a just a single trace. 

The need to start on the OSM website to eventually learn that.

**Comment by mmd-osm** [comment]
You don't have to upload your traces to osm.org/traces for mapping purposes, this is all pretty much optional. The same "Custom Map Data" data layer shown in the screenshot lets you upload your local GPX file into iD:

![image](https://github.com/openstreetmap/openstreetmap-website/assets/5842757/9f64b4dc-bd29-4cb8-9cee-60625666a4af)

In general, this is more a documentation topic (although many people don't read any documentation).
