### ISSUE TITLE
Move site on to flexible grid

### ISSUE THREAD

**Issue by samanpwbb** [openstreetmap/openstreetmap-website#403]
As of the welcome osm and help pull requests, we're started implementing a flexible, 12-column grid with a max width of 740px for the content area. If the content area is more than 740px wide, our content stays centered within the container at 740px.

Notes: 
- 740px is probably a little too narrow.
- Content should be centered in content area, not flush left
- Needs a mobile strategy. This could be a good opportunity for us to eliminate the mobile stylesheet and use media queries instead for mobile.

**Comment by gravitystorm** [comment]
Recent work such as https://github.com/openstreetmap/openstreetmap-website/pull/2697 and https://github.com/openstreetmap/openstreetmap-website/pull/2498 means that we are no longer using a fixed grid, and the last traces of it have been removed. Instead are using Bootstrap's responsive grid.
