### ISSUE TITLE
Allow location to be searched with exiftool format

### ISSUE THREAD

**Issue by shdpl** [openstreetmap/openstreetmap-website#4040]
### Problem

Hi,
when i get location from the image using probably the most popular CLI tool which is the exiftool like that:
```
exiftool IMG_8109.JPG | grep 'GPS Position'
GPS Position                    : 55 deg 58' 24.28" N, 37 deg 24' 41.70" E
```
i am getting an output in fairly readable format, but when i search for it on https://www.openstreetmap.org/ nothing can be found.
I was thinking whether i should go straight for a github, but in the essence i think that's what open-source projects should be working like.

### Description

So my idea is to support the exiftool location format. I was also considering to put the request in my personal text file to come back straight with a pull request, but i got used to luxuries of having an issue request tracker so i decided to put it in open. I would appreciate any comments describing why is this not a good idea before i start to implement that myself.
Thanks!

**Comment by tomhughes** [comment]
Well that is a completely whacky and obscure format that I've never seen anything else use so I would be reluctant to add a special case for one obscure piece of software - the DMS parsing is already insanely complex as it is.

**Comment by pnorman** [comment]
exiftool can output in a format of your choice with the `-coordFormat` option. I recommend using that to get the format in a more sane format.

**Comment by shdpl** [comment]
@tomhughes well, the way i made it work is only a modification of a single regular expression. Ultimately it's always up to the maintainer whether he wants to merge it or not. I think it would be useful for less technical users of those, otherwise, you can make *exiftool* output already recognized format with `exiftool -c "%.6f" my/file.png`.

**Comment by tomhughes** [comment]
Yes I know it's only one regular expression - one already very complicated regular expression as demonstrated by the fact that there are something like 250 lines of code dedicated to testing that regular expression.

**Comment by gravitystorm** [comment]
As per #4041, I'm going to close this issue for now.
