### ISSUE TITLE
API: Allow to change GPS trace metadata via PATCH `/gpx/#id/details`

### ISSUE THREAD

**Issue by nonZero** [openstreetmap/openstreetmap-website#4046]
### Problem

If an app/user wants to mass change GPS trace metadata (for example, visibility) it can only use the update/PUT method which requires her to re upload the GPX trace itself:
https://wiki.openstreetmap.org/wiki/API_v0.6#Update:_PUT_/api/0.6/gpx/#id

Adding a new PATCH `_/api/0.6/gpx/#id` method can allow apps to modify visibility/description without re uploading.
See also:
https://github.com/openstreetmap/openstreetmap-website/blob/d4a014d3a6ca3f8f7d03528d39e4707dc256bc60/app/controllers/api/traces_controller.rb#L51

**Comment by mmd-osm** [comment]
It seems your assumption is not correct. You can update the visibility without re-uploading the trace. Only descriptions and tags need to be provided (from previous GET request).

Before:
![image](https://github.com/user-attachments/assets/0cddb42b-0638-4ce2-bab5-266b70bd1e45)

Request:
PUT http://localhost:3000/api/0.6/gpx/87

```XML
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6">
    <gpx_file id="87" visibility="private">
        <description>New Track_2016-08-06 181629</description>
        <tag>tag1</tag>
        <tag>tag2</tag>
        <tag>tag3</tag>        
    </gpx_file>
</osm>
```

After:

![image](https://github.com/user-attachments/assets/32df0ac3-4a35-4455-8f57-ecb631c4bec6)
