### ISSUE TITLE
ÖPNVKarte layer doesn't work

### ISSUE THREAD

**Issue by Discostu36** [openstreetmap/openstreetmap-website#4059]
### URL

https://www.openstreetmap.org/#layers=ON

### How to reproduce the issue?

1. Open openstreetmap.org and choose the ÖPNVKarte layer. 
2. Witness how the tiles don't load.

### Screenshot(s) or anything else?

![grafik](https://github.com/openstreetmap/openstreetmap-website/assets/30999326/a74794a4-1196-42ee-903d-489b54e77945)

The browser console shows that tileserver gives 404 answers after a (longish) while.
![grafik](https://github.com/openstreetmap/openstreetmap-website/assets/30999326/2a7b92cd-8997-4fd2-adab-acb1fc069351)

![grafik](https://github.com/openstreetmap/openstreetmap-website/assets/30999326/efb5e0ae-9ba4-4cf8-94ac-75d840f86bbe)

**Comment by Firefishy** [comment]
It appears to me that their render server might be overloaded and timing out with 404 responses.

**Comment by Firefishy** [comment]
Link: https://github.com/openstreetmap/openstreetmap-website/pull/4126
