### ISSUE TITLE
Wrong title for an area under Jaipur, Rajasthan, India

### ISSUE THREAD

**Issue by Raadheyyy** [openstreetmap/openstreetmap-website#4064]
### URL

https://www.openstreetmap.org/#map=16/26.9423/75.7544

### How to reproduce the issue?

I can rename it to the correct name

**Comment by tomhughes** [comment]
This does not appear to be reporting an issue with the web site code.

Please see https://www.openstreetmap.org/fixthemap for advice on improving the map.
