### ISSUE TITLE
Moderation-Tools: safe IP adress

### ISSUE THREAD

**Issue by natrius** [openstreetmap/openstreetmap-website#4066]
### Problem

It seems OSM does not safe ip adresses at all or make it usable for people at the DWG? (Not sure, just looks like to me) 

We have a user that is blocked right now (for quite some time, about 3 years) but is creating massively new accounts. The only thing "detecting" him seems to be by chance when a community member stumbles upon him and his mapping-style and cs-comments. The DWG is always asking "well, does this account fit him as well, account was created at the same time." 

While i'm aware this can lead to problem with universities or companies that work on OSM it might help moderating efforts. (or maybe this is such an isolated case that its not worth implementing something like that). 

(The same user is also deleting all his accounts so nobody can follow what he is /was doing, referring to https://github.com/openstreetmap/openstreetmap-website/issues/4018)

**Comment by tomhughes** [comment]
Yes we absolutely save the IP address used to create the account and DWG ask operations for details when that is necessary.

If you are a DWG member and are not aware of that then something has gone very wrong in the DWG onboarding process.

**Comment by SomeoneElseOSM** [comment]
@natrius If you'd like to have a chat about some of this issues (beyond what's already public on threads in the Austrian and Italian sections of the forum) email data@openstreetmap.org and we can explain the technical issues around internet access in 2023 :)

Re DWG members, I believe that https://wiki.osmfoundation.org/wiki/Data_Working_Group "who we are" is still up to date.

**Comment by natrius** [comment]
I think i misunderstood something here and additionally explained really poorly my intention as well. Sorry for wasting your time! :)
