### ISSUE TITLE
Could I publish data for the public?

### ISSUE THREAD

**Issue by SeiwonPark** [openstreetmap/openstreetmap-website#4069]
Hi I'm trying to use `geopy` library which uses OSM data. And I'm thinking of collecting data from it and then publish the data as public.

I've checked **OSM Copyright Policy** as follows:

> You are free to copy, distribute, transmit and adapt our data, as long as you credit OpenStreetMap and its contributors. If you alter or build upon our data, you may distribute the result only under the same licence. The full [legal code](https://opendatacommons.org/licenses/odbl/1.0/) explains your rights and responsibilities.
>
> Our documentation is licensed under the [Creative Commons Attribution-ShareAlike 2.0](https://creativecommons.org/licenses/by-sa/2.0/) license (CC BY-SA 2.0).

So, could I save the data on my own database and then deploy as public by noticing "Data is licensed under OpenStreetMap Oraganization"?

**Comment by tomhughes** [comment]
We are the developers of the code, we are not responsible for the licensing of the production database contents.

Maybe the [FAQ](https://wiki.osmfoundation.org/wiki/Licence/Licence_and_Legal_FAQ) the OpenStreetMap Foundation published will help you.

**Comment by SeiwonPark** [comment]
Thank you for sharing. [FAQ](https://wiki.osmfoundation.org/wiki/Licence/Licence_and_Legal_FAQ#1.5._Is_OSM_Data_Free_to_Use?) helped me :)
