### ISSUE TITLE
Update communities page

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/openstreetmap-website#4082]
### Problem

The communities page is out of sync with the "community index".

### Description

I've fixed the entry for the Swiss local chapter in the community index as it was slightly sub-optimal, but there isn't an obvious way of requesting an update of the community page on the website outside of opening an issue here.

Note that it doesn't seem as if a new release of the index itself has been generated yet, so maybe I'm just wasting time.

**Comment by gravitystorm** [comment]
Dependabot automatically updates our version of osm-community index when new versions are published. We're currently running 5.5.3, which was released on 20th June.

So I think the answer here is to wait for (or ask for) an upstream release, and then it'll be updated here automatically shortly afterwards.

**Comment by simonpoole** [comment]
Sounds good. I
