### ISSUE TITLE
osmnx.graph_from_place InvalidChunkLength

### ISSUE THREAD

**Issue by AlexWangVT** [openstreetmap/openstreetmap-website#4096]
### How to reproduce the issue?

I use osmnx.graph_from_place to load graph from .osm.pbf file. The code works for most U.S. states but Texas. When I tried to process Texas data with graph_from_place function, it always gives the error: InvalidChunkLength: InvalidChunkLength(got length b’‘, 0 bytes read); ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b’‘, 0 bytes read)", InvalidChunkLength(got length b’', 0 bytes read)). Fortunately, I had one successful run and got the data that I needed, which yet took 2 hours to run. Don’t know why it works this time and takes extreme longer than other states even though the data size is not significantly bigger. I think there must be something wrong in the server. 

I also tried to use pyrosm.get_network function to retrieve the .osm.pbf file for Texas in order to concert it to geodataframe, but ran out of memory. Highly suggest adding some arguments that could be used to filter columns as needed.

Another way I’ve tried is using osm2pgsql to load .osm.pbf file directly to postgresql but the data format is different from what I could get using get_network or graph_from_place function. Suggest creating style files that is used to extract the exactly same data format as get_network.

**Comment by Firefishy** [comment]
This repo is for issues with the OpenStreetMap.org codebase.

For questions about using OSM data, tools or similar best to ask these on https://community.openstreetmap.org/ or because you are in the US you could try the [OSM US Slack](https://slack.openstreetmap.us/)

**Comment by tomhughes** [comment]
Alternatively report it to the issue tracker for whatever software it is you're using that provides that function, because it isn't us and it sounds like that software has a problem with it's PBF decoder.
