### ISSUE TITLE
Display village name differently from suburb names

### ISSUE THREAD

**Issue by DabMK** [openstreetmap/openstreetmap-website#4098]
### Problem

It is very confusing the thing that village names and suburbs names are displayed in the same way in the OSM website (I know that in the 13rd and 12th levels of zoom the suburb names are slightly bigger, but it is pretty hard to notice).

### Description

I'd suggest to change just a little bit the font or the color of the text.

### Screenshots

![Tmp](https://github.com/openstreetmap/openstreetmap-website/assets/64862398/b13d0f5c-1bda-4bc3-93d4-31cecb01a1e2)

**Comment by tomhughes** [comment]
The menu presented when you opened this issue included this option:

![image](https://github.com/openstreetmap/openstreetmap-website/assets/147741/a4babdd7-8e5a-450d-b8ac-d1e9a9d16ece)

which would have directed you to the correct place to file this bug, namely https://github.com/gravitystorm/openstreetmap-carto/issues.
