### ISSUE TITLE
Code blocks in diary enteries appear reversed, with right-to-left locale

### ISSUE THREAD

**Issue by iriman** [openstreetmap/openstreetmap-website#4104]
### Description

Code blocks in diary enteries appear reversed, with right-to-left locale

### URL

https://www.openstreetmap.org/user/iriman/diary/401796?locale=fa

### How to reproduce the issue?

1. Visit [https://www.openstreetmap.org/user/iriman/diary/401796](https://www.openstreetmap.org/user/iriman/diary/401796?locale=fa)**?locale=fa**
2. Find "bread:wholemeal=yes"
3. It's reversed!

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/openstreetmap-website/assets/8467903/999159d8-47f3-4d3e-bb12-6e5d420cf5e0)

`unicode-bidi: embed` maybe is better than "bidi-override"?

**Comment by iriman** [comment]
another example:

https://www.openstreetmap.org/user/iriman/diary/391884?locale=fa

![image](https://github.com/openstreetmap/openstreetmap-website/assets/8467903/f93ab60f-193a-4893-9454-a0910374a46b)

**Comment by AntonKhorev** [comment]
adding `dir=ltr` on paragraphs wouldn't help because there's an override in css

```
direction: rtl;
unicode-bidi: bidi-override;
```

this is from Bootstrap, possibly processed later by r2
