### ISSUE TITLE
search field could be more prominent

### ISSUE THREAD

**Issue by fgnievinski** [openstreetmap/openstreetmap-website#4123]
### Problem

currently it takes two clicks to start searching: first the burger icon at the top right corner then the search field is revealed. 

### Description

for better user experience, there could be a magnifier icon in the top horizontal bar, between the OSM logo and the burger menu icon. this shortcut would expand to immediately accept text input, with a single click.

### Screenshots

![Screenshot_20230730-013342~2](https://github.com/openstreetmap/openstreetmap-website/assets/5018500/5a8001d3-4902-433e-b84e-b0124b0a3912)

**Comment by gravitystorm** [comment]
Thanks for the suggestion. There are other things that could be put here too, for example the user avatar, in order to make it easier to access those parts of the site too.

I think for the moment we're happy with just the one menu button show, and without any additional shortcut icons.
