### ISSUE TITLE
Geocoding: "undefined method `split'" when Nominatim (version 5) doesn't return full URL in more_url field

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/openstreetmap-website#4137]
### URL

https://www.openstreetmap.org/search?query=banana

### How to reproduce the issue?

Right now Nominatim doesn't seem to be reachable. The API request is done in Rails so I can't inspect the HTTP code or error message. If that happens the Rails prints an additional Ruby error "undefined method `split' for nil:NilClass" (which might or might not also be in the webserver error log)

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/openstreetmap-website/assets/3727288/a542e35e-08aa-4835-852a-001a0a83d715)

**Comment by gravitystorm** [comment]
It's working for me (both on osm.org and also on a local machine) so perhaps it's an intermittent problem?

Alternatively, it could be based on the location you are looking at. The only `.spilt` call in geocoder_controller comes while parsing the bounding box attribute of the returned results, so it might be something location-specific that triggers it.

https://github.com/openstreetmap/openstreetmap-website/blob/ff4a7dc36d8a4181e0c28df936b281babbe421e4/app/controllers/geocoder_controller.rb#L111

**Comment by mtmail** [comment]
I found the issue is a couple of lines up:

```ruby
 more_url_params = CGI.parse(URI.parse(results.attributes["more_url"]).query)
```

dulcy server returns just the query part of the URL in more_url, the other server return a full URL

```
curl 'https://dulcy.openstreetmap.org/search.php?q=london&format=xml'
more_url="q=london&amp;addressdetails=1&amp;limit=..."

curl 'https://vhagar.openstreetmap.org/search.php?q=london&format=xml'
more_url='https://vhagar.openstreetmap.org/search.php/?q=london&amp;exclude_p...
```

That causes the error:

```
ruby -e'require "cgi"; p CGI.parse(URI.parse("q=London").query)'
[...]/ruby/2.6.0/cgi/core.rb:384:in `parse': undefined method `split' for nil:NilClass

ruby -e'require "cgi"; p CGI.parse(URI.parse("http://example.com/search?q=London").query)'
{"q"=>["London"]}
```

Dulcy is running the next version of Nominatim, the rewrite in Python, with Python webserver. You might also notice it puts the attributes in single quotes instead of double quotes (Python XML vs PHP XML serializing library).

Adding @lonvia to ask if that's an oversight, the attribute is called 'URL' after all or meant to stay.

**Comment by Firefishy** [comment]
Lonvia is on leave at the moment.

The python based servers can be taken out of service by Ops if critical.

**Comment by tomhughes** [comment]
In any case it's a matter for the Nominatim issue tracker not this one.

**Comment by mtmail** [comment]
now tracked at https://github.com/osm-search/Nominatim/issues/3138

**Comment by pnorman** [comment]
I think there's still a bug where it's giving an incorrect error

**Comment by tomhughes** [comment]
Oh sorry I misunderstood. I thought the split was on the python side.

**Comment by tomhughes** [comment]
I think @mtmail has the correct diagnosis - this is the backtrace I get:

```
NoMethodError - undefined method `split' for nil:NilClass:
  app/controllers/geocoder_controller.rb:94:in `search_osm_nominatim'
  app/controllers/application_controller.rb:295:in `better_errors_allow_inline'
  config/initializers/compressed_requests.rb:27:in `call'
  config/initializers/cors.rb:9:in `call'

```

In which case I think that this is a Nominatim side bug and there's not a huge amount we can do on our side as the exception is in a library.

What did you mean by "incorrect error" exactly @pnorman?

**Comment by pnorman** [comment]
I find the message a bit misleading because it's not an error contacting, it's a (potentially) invalid response.

**Comment by mtmail** [comment]
@pnorman You're right, I updated the title

**Comment by tomhughes** [comment]
That's because we surround the entire method in an exception handler but the only exceptions we really expect to get are network related ones.

**Comment by lonvia** [comment]
Fixed the regression on the Nominatim side in https://github.com/osm-search/Nominatim/commit/996026e5ed9f1f07e618b67de9077c3e338c0302.

Looking at the code, the whole URL parsing is not really necessary. It is only done to get the excluded place IDs and they can be easier extracted from the `exclude_place_ids` attribute directly.
