### ISSUE TITLE
Nominatim starts to be more strict regarding viewbox parameter

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/openstreetmap-website#4138]
### URL

https://www.openstreetmap.org/search?query=banana#map=0/-41/-108

### How to reproduce the issue?

1. Zoom out until more than one "world" is displayed. 2. Search for a place.

Newest Nominatim (version 5, master) returns an error
```
curl 'https://dulcy.openstreetmap.org/search.php?q=london&format=xml&viewbox=-300,-90,300,90'
<error>
    <code>400</code>
    <message>Bounding box coordinates invalid.</message>
</error>
```

Older Nominatim was more forgiving
```
curl 'https://vhagar.openstreetmap.org/search.php?q=london&format=xml&viewbox=-300,-90,300,90'
<searchresults timesta[....]opyright' querystring='london' viewbox='-180,-90,180,90' exclude_place_ids='307[...]
```

cc @lonvia 

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/openstreetmap-website/assets/3727288/359ac321-0b5b-471b-9625-13f41c06ad9d)

**Comment by HolgerJeromin** [comment]
This issue should be raised in the correct repo: https://github.com/osm-search/Nominatim

**Comment by mtmail** [comment]
Now tracked in https://github.com/osm-search/Nominatim/issues/3137

**Comment by pnorman** [comment]
Regardless of the change of Nominatim behavior, should the website be sending an invalid bounding box?

**Comment by tomhughes** [comment]
Fair point, but what even is "correct" when you're that far zoomed out... Maybe we should just drop it?

**Comment by lonvia** [comment]
Old behaviour reinstated in https://github.com/osm-search/Nominatim/commit/8d9b5e477538b6ca8339623f2643bc69e7be98f2. I think it's fair to leave it to Nominatim to do the right thing when the viewbox becomes exceedingly large. It likely knows better what kind of viewbox still makes sense.
