### ISSUE TITLE
When registering in a Spanish (and other languages), the User's terms are in English

### ISSUE THREAD

**Issue by angoca** [openstreetmap/openstreetmap-website#4146]
### Problem

New users that do not speak English have to read an English sentence to accept the User's terms, which are also in English. The link to other translations does not point to a Spanish version after 3 more clicks.

### Description

I created a thread in communities about this issue in detail: https://community.openstreetmap.org/t/accepting-users-terms-for-a-spanish-non-english-speaker/102093

The registration page should include the English version (because it is necessary) but a direct link to the informal/unofficial translation. This allows new users to understand the rules. Otherwise, the new user could just "accept" without understanding the text and perform invalid operations (importing from commercial maps, using data with incompatible licenses, etc.)

### Screenshots

![image](https://github.com/openstreetmap/openstreetmap-website/assets/294317/0cf77423-22bc-4b65-a63f-b64be9c031d1)

**Comment by AntonKhorev** [comment]
Spanish translation is missing `users.terms.readable_summary` and `users.terms.informal_translations`. This can be fixed on Translatewiki.

What can be fixed in this repository is to link directly to localized versions of summary/informal translation pages.

**Comment by AntonKhorev** [comment]
I guess you want this: add a localization string for the informal translation link that's going to be still https://wiki.osmfoundation.org/wiki/Licence/Contributor_Terms/Informal_Translations in English, but in Spanish make it https://wiki.openstreetmap.org/wiki/ES:Licencia_Abierta_de_Base_de_Datos/T%C3%A9rminos_del_colaborador

**Comment by angoca** [comment]
I translated all missing strings, and I pointed Accounts.edit.contributor terms.link to the Spanish link.

**Comment by simon04** [comment]
The translations have been picked up via [23680cb](https://github.com/openstreetmap/openstreetmap-website/commit/23680cb44532a6983a2f9a41547b027052e87bc4#diff-4bbf4ee302c9607c80408361708b8b9fde3ee7afc5b505bfd69d429dd433f915). Is anything left to be done?

**Comment by angoca** [comment]
Great, all strings are now in Spanish. Last question, how often strings form transiflex are imported and published?

**Comment by tomhughes** [comment]
Not sure why this is still open - it should really have been closed with a reference to translatewiki.

I don't know what transiflex is but translatewiki normally push translations a couple of times a week but @simon04 has already pointed you at the commit where that happened in this case and they will then be deployed when we next deploy changes which again is usually several times a week.

**Comment by angoca** [comment]
Sorry:

s/Transiflex/Translatewiki/g

Many OSM tools translations are in Transifex.
