### ISSUE TITLE
In the mail about someone solved an issue on the map the attached image has a wrong extension, png instead of jpg

### ISSUE THREAD

**Issue by JensKorte** [openstreetmap/openstreetmap-website#4147]
### How to reproduce the issue?

I got a mail about an issue has been solved by someone else. In the attachments there is an avatar of the person. The image has .png but the file format is .jpg.
There were no further problems with the mail program, this report is just for the records.

![avatar](https://github.com/openstreetmap/openstreetmap-website/assets/2682123/faf376e6-5fec-4efb-a6f2-a801ebef43d8)
```
file avatar.png
avatar.png: JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=13, height=3262, manufacturer=samsung, model=SM-G998B, orientation=upper-left, xresolution=206, yresolution=198, resolutionunit=2, software=G998BXXU5CVGB, datetime=2022:08:27 19:07:36, GPS-Data, width=2342], baseline, precision 8, 36x50, components 3
```

**Comment by tomhughes** [comment]
I suspect that the user uploaded a JPEG with a PNG extension but most things just ignore the extension as it's never a reliable indicator of anything.

**Comment by tomhughes** [comment]
Actually that's just a hardcoded label for the image to allow the body to reference the attachment: https://github.com/openstreetmap/openstreetmap-website/blob/c65f808244a5042c5b437b5f3ea8dcc6d8513002/app/mailers/user_mailer.rb#L190
