### ISSUE TITLE
Banner content obfuscates close button

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/openstreetmap-website#4165]
The OpenStreetMap Funding Drive 2023 banner added in 242b73b632703c856b2d4ccbad77b6f9e5ad57c7 includes a lot of gray lines against the black background, which make it difficult for the user to find the ✖️ button. I’ve seen these banners before, so I know where to click to dismiss the banner, but less experienced users may have trouble with that.

<img src="https://github.com/openstreetmap/openstreetmap-website/assets/1231218/56226bdf-abb7-4377-89e6-97ee203d4fe0" width="350" alt="Support the map! OpenStreetMap is free to use, but not free to run">

It might be too late to address this issue for this particular banner, but maybe to prepare for future ones, we could modify the stylesheet to stick a background color behind the ✖️, which would make it easier to spot.

**Comment by tomhughes** [comment]
I did what I could in the short time available to try and make it visible but if you have a better solution then please feel free to open a PR to improve things.

Obviously the main problem is creating something that is visible regardless of the underlying image and without affecting the underlying image too much - we do at least now have a way to distinguish light/dark images which gives us more options in terms of how we style things.

**Comment by 1ec5** [comment]
I see that a generated rule `.btn-close` is getting `opacity: 0.5`. Removing that would keep the close button discernible in this case (as long as the lines in the image are off-white). However, I can’t tell where this property is being applied in SCSS.

**Comment by tomhughes** [comment]
It's from bootstrap.

**Comment by Zaczero** [comment]
Extract the icon (since it uses background:) to an element inside button and then set the button's background to something contrasting and remove opacity.

**Comment by JesseWeinstein** [comment]
For this banner, we could just modify it to have an appropriately sized white square in the upper corner, so the button shows up. Does anyone know where the original, non-jpeg version of the image is?

**Comment by Zaczero** [comment]
> For this banner, we could just modify it to have an appropriately sized white square in the upper corner, so the button shows up. Does anyone know where the original, non-jpeg version of the image is?

Modifying the image itself will break easily depending on the device resolution, dpi, and all this stuff. Proper fix is just to edit HTML and make it a proper white-black contrasting background.

**Comment by pnorman** [comment]
We have [specifications for the banner](https://github.com/openstreetmap/openstreetmap-website/blob/master/FAQ.md) that require sufficient visual contrast for the x to be seen. Surely the problem is that the graphic designer didn't follow them?

**Comment by Zaczero** [comment]
This should be reverted, this is not production ready clearly.

**Comment by stillhart** [comment]
The temporary "support the map" banner just made aware of the financial situation at OSM. I wasn't even a member until that. I think that I wouldn't mind a "become a member" (or similar) button for logged in users. Many apps offer some kind of pro features, of course we don't want that, but I feel like some kind of "upgrade your membership" is a fair statement to make. 
 
Here is a rough example:
![image](https://github.com/openstreetmap/openstreetmap-website/assets/9038148/09338195-91c8-45a6-a7df-8258efe99659)
