### ISSUE TITLE
Using Geo URIs

### ISSUE THREAD

**Issue by da5nsy** [openstreetmap/openstreetmap-website#4167]
### How to reproduce the issue?

_I'm not sure if this is a bug/feature request/support request_

How are people meant to use Geo URIs?

If I'm using openstreetmap.org it shows a Geo URI.

<img width="173" alt="Screeshot_20230814_110054" src="https://github.com/openstreetmap/openstreetmap-website/assets/3739866/90a52c10-8b35-4d83-90fd-e71fdbd86ba5">

Clicking on it (_it is hyperlinked, so that seems like a reasonable thing to do_) doesn't resolve.

<img width="475" alt="Screeshot_20230814_114028" src="https://github.com/openstreetmap/openstreetmap-website/assets/3739866/53d882aa-11f1-46cb-aa47-2cf9fc7728f5">

Copying it into the search bar (_let's say I saved it to come back to later, for some reason_) doesn't return any results.

<img width="257" alt="Screeshot_20230814_110116" src="https://github.com/openstreetmap/openstreetmap-website/assets/3739866/33091115-4115-4e11-86e9-1cc940972a8d"> <img width="256" alt="Screeshot_20230814_110133" src="https://github.com/openstreetmap/openstreetmap-website/assets/3739866/581d2fb6-b048-48b8-b24c-e6e2e2df0b68">

## Questions

- Should either (both) of those things work as I assumed they would?
- How do people use URIs?

**Comment by HolgerJeromin** [comment]
> Should either (both) of those things work as I assumed they would?

No. This should not work in the search field.

> How do people use URIs?

On mobile devices (at least) you can click on the links and any of the installed geo-affine applications can be called.

ref #799

**Comment by tomhughes** [comment]
As @HolgerJeromin they are mostly targeted at mobile devices which do useful things with them.

That said as with any URI it's up to each individual browser what it wants to do with it so this is really a browse issue.

**Comment by da5nsy** [comment]
Thanks both for the information that they're mainly for the benefit of mobile.

> That said as with any URI it's up to each individual browser what it wants to do with it so this is really a browser issue.

Do any browsers natively handle it? I just installed [this](https://addons.mozilla.org/en-US/firefox/addon/geo-uri-handler/) Firefox add-on, and now clicking the link does something 🎉

**Comment by da5nsy** [comment]
> This should not work in the search field.

I'm trying to work out whether there is a common-enough use-case for this to be a feature request.
I assumed it would work, but I'm not sure when it would actually be used.
Thoughts?

**Comment by tomhughes** [comment]
Well so far you seem to be the only person ever to have tried to search for one so my guess is that no it's not common enough?

**Comment by da5nsy** [comment]
🤣 Fair enough!

**Comment by hlfan** [comment]
Putting these in the search bar sounds suspiciously like #1123
