### ISSUE TITLE
rate-limit changeset comments

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#4196]
### Problem

see also #2342 where rate limit for edits was proposed

https://resultmaps.neis-one.org/osm-discussion-comments?uid=20047765&commented - typically such rate of comments has no legitimate purpose

### Description

consider rate limiting changeset comments, especially for new accounts

maybe add option to delete changeset comments when blocking some account as vandal-only account?

### Screenshots

![screen06](https://github.com/openstreetmap/openstreetmap-website/assets/899988/7f9c0e39-b5a4-498c-9a2c-f57a2f0584dc)

all 2800+ comments were slurs and insults

**Comment by tomhughes** [comment]
Some statistics to help guide possible limits...

There are roughly 20000 users (or ips) that have at some point posted over 10 comments an hour and roughly 400 that have exceeded 100 comments per hour.

There are about 1100 that have exceeded 100 per day and 23 that have exceeded 1000 per day

**Comment by matkoniecz** [comment]
> That will of course go wrong the first time DWG do a mass revert and try to comment on all the reverted changesets.

I mentioned "especially for new accounts" and giving rate limit exception for accounts with block rights would be probably a good idea anyway.

The tricker cases are power users not in DWG.

**Comment by matkoniecz** [comment]
Though limiting mass account creation would likely help with root cause here.

**Comment by tomhughes** [comment]
Tuning things like this in one dimension is hard enough without adding in a second variable like how old the account is and people will just create submarine accounts and wait a while before using them.

Looking at the non-abusive cases with large rates they're not necessarily DWG but as you say "power users" who once posted a thousand in quick succession for some reason - either closing out a bunch of notes or doing some sort of import of hints from another database as notes.

**Comment by matkoniecz** [comment]
Closing/opening notes is a separate thing.

Abusive changeset comments are especially annoying as you can easily harass any user you want (you cannot spam them by opening notes and it is trickier to do this by closing notes or commenting there, though I guess also possible)

**Comment by tomhughes** [comment]
Well it's not a separate thing at the moment because due to the broken data model of notes there are comments associated with those events.

**Comment by pnorman** [comment]
I've thought about this in the past but neglected to open an issue. I believe that *any* action that triggers an email should be rate limited similar to DMs. Catching someone from the DWG doing a revert that triggers thousands of emails because they left changeset comments on is a good thing, as if those emails go through they will cause problems on the email server or with spam prevention.

**Comment by matkoniecz** [comment]
For scale, one of people reverting this vandal got 37 000 email notifications about spam changeset comments.

At this rate (and given mail contents) there is, I think, real risk of our mails getting classified as a spam.

**Comment by tomhughes** [comment]
Don't you think I know there's a problem? Who do you think has been dealing with the mail queue!

I can't say too much now about what happened overnight, other than that the lack of a rate limit is not the main problem, but I'm working on it.

**Comment by gravitystorm** [comment]
I think it's helpful for the scale of the problem to be known - it's not telling you something that you don't know already, but it helps the rest of the community understand the issue and prioritise our efforts!

**Comment by tomhughes** [comment]
The most useful input right now that anybody that doesn't want to code it to provide is thoughts on what a reasonable rate limit might be - there are some statistics in https://github.com/openstreetmap/openstreetmap-website/issues/4196#issuecomment-1686300895 but feel free to ask for others if they would help.

**Comment by matkoniecz** [comment]
> what a reasonable rate limit might be

Is it feasible to have vastly lower rate limit for say first 100 changeset comments made by a given account? Actual new users are very unlikely to start making many of them.

Is it feasible to exempt DWG (account with block ability) from this limit?

If yes, how many non-DWG accounts are there with heavy changeset comment use? How many are blocked accounts (assumed to be vandals)? Is it possible to list them?

Is it feasible to add bot-type account flag allowed to exceed this limits, without ability to block accounts? I have seen it in few places. Though I guess that it comes with process for assigning it and obviously complicates code.

> Don't you think I know there's a problem? Who do you think has been dealing with the mail queue!

It was not intended as message for you, or implying that you are unaware of this problem. And I guess that info about mail queue state would be even more useful than much narrower piece of statistics that may be poorly representative.

But it, I think, is useful to record any indicator of the problem size and confirmation that it is an actual problem and to record this.

Sorry if that sounded like implication that you cannot figure how to access such statistics or similar. Though not sure how it could be better phrased.

> not repeated comments that add nothing new

It seemed to me that recording some nonsubjective info confirming that problem exists could be useful.

**Comment by tomhughes** [comment]
A lower rate limit for new accounts should be possible.

Exempting moderators (ie DWG) should be possible.

An account flag is doable but is significantly more work so would obvious delay things.
