### ISSUE TITLE
Map tiles are blurry on iOS: suboptimal viewport tag?

### ISSUE THREAD

**Issue by stillhart** [openstreetmap/openstreetmap-website#4220]
### URL

https://www.openstreetmap.org/#map=14/47.3619/8.5343

### How to reproduce the issue?

1. Open openstreetmap.org on a high resolution iOS device like an iPad or iPhone.
2. Compare the sharpness to the surrounding UI

Devices I used: iPhone 12 mini, iPad Pro 2021

### Screenshot(s) or anything else?

I assume and really hope it's some HTML header tag that's not optimally set, especially the viewport:
`<meta name="viewport" content="width=device-width, initial-scale=1">`
https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/layouts/_head.html.erb#L3

Maybe it's a fundamental limitation of tiles, then please go on and close this issue. At least it's documented until we get vector tiles :-)

Here are some screenshots to understand the situation. Compare the sharpness of "OpenStreetMap" to the sharpness of the tiles. It's especially noticable around non-map UI.
![IMG_85022](https://github.com/openstreetmap/openstreetmap-website/assets/9038148/65e07eb4-2400-4cf6-a4bc-b7fb6ffc0f70)

Here is the full screenshot
![IMG_8502](https://github.com/openstreetmap/openstreetmap-website/assets/9038148/03d2b465-fd13-45f8-8691-1b5e3937e245)

**Comment by gravitystorm** [comment]
Hi @stillhart , thanks for your report. The low-resolution map tiles on the standard map layer is a well-known issue, and cannot be fixed by changes in this repository. If you swap to a different map layer you will see high-resolution ("retina") tiles on the Transport and Cycle Map layers, for example.

I'll copy+paste what I wrote at https://github.com/openstreetmap/openstreetmap-website/issues/104#issuecomment-840595179 (there are some more details in followup comments, if you are interested:


> - This site supports high-dpi map tiles, and has done for many years. You can see this on the "Cycle Map" and "Transport" layers, for example.
> - The lack of support for high-dpi tiles from other providers will be solved by engaging with those providers directly, not by discussing it here. If you want the OSMF to serve high-dpi tiles, then that's a problem they need to solve (and let me be clear - everyone involved with both operating the servers and developing the stylesheets knows all about this, so please don't pester them - help them, yes, but please don't just pester).
> - When a specific provider has high-dpi tiles available, please open a request for us to enable them for that layer. Until then, there's nothing that we can do within this repo.
> - There are some low-dpi images used in various places around the site (for example, the banner image on the copyright page).
> 
> I'm keen to see those updated to have high-dpi variants, although it's not a current priority for the team. If you want to work on these assets (see the app/assets/images directory) please feel free to discuss these in separate issues.
