### ISSUE TITLE
Attraction node and area not show icon

### ISSUE THREAD

**Issue by dypa** [openstreetmap/openstreetmap-website#4227]
### URL

https://www.openstreetmap.org/node/9662836483

### How to reproduce the issue?

1. Open node with `attraction="roller_coaster"` to edit https://www.openstreetmap.org/node/9662836483
2. See in edit 
![image](https://github.com/openstreetmap/openstreetmap-website/assets/80477/7d9e579b-1d55-4e70-b027-ac2f5ab19e4e)
3. See in map
![image](https://github.com/openstreetmap/openstreetmap-website/assets/80477/ff4497ba-1716-468b-9702-e750e0a6fb58)

Expected to see on map icon as in edit

**Comment by tomhughes** [comment]
As explained when you opened this bug, this repository does not deal with issues relating to the map rendering. Please try again, making sure to select the option for issues relating to the map:

![image](https://github.com/openstreetmap/openstreetmap-website/assets/147741/1abcd3f0-33de-4923-8285-cc1b566e6ddf)
