### ISSUE TITLE
In /history, Version #1 should have text "Created by" rather than "Edited by"

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/openstreetmap-website#4244]
### URL

https://www.openstreetmap.org/relation/13586946/history#map=19/52.20335/0.12832

### How to reproduce the issue?

In listings of history, each edit has text like "Edited over 1 year ago by CycleStreets".

However, in the case of `Version #1`, i.e. the creation of the item, this is confusing. "Edited" implies there is something being amended. However, the first is a creation, not an edit.

So `Version #1` should have text "Created over 1 year ago by CycleStreets", i.e.

`(version == 1 ? 'Created' : 'Edited')`

**Comment by mmd-osm** [comment]
No rules without exception. Sometimes it’s even a deletion: https://www.openstreetmap.org/node/1/history

**Comment by tomhughes** [comment]
Indeed, editing seems general enough to cover creation and deletion to me so this does sound quite a lot like splitting hairs.

**Comment by mmd-osm** [comment]
There seems to be a majority here who thinks this is ok "as is". Closing here.
