### ISSUE TITLE
use different icons for different sites

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#4259]
### Problem

Sorry I can't find the previous bug report for this.

Anyway here we are looking at a browser New Tab window,
and as we see, two different OSM sites are using the same icon.
At least they could be colored differently.

Or one must use 3rd party hacks,
https://www.ghacks.net/2018/09/30/custom-site-icons-in-chrome-and-firefox/

### Screenshots

![chrome___newtab_](https://github.com/openstreetmap/openstreetmap-website/assets/1230959/1e6d360e-0d7f-4b70-b939-1ddf14ef2a7a)

**Comment by pnorman** [comment]
> Sorry I can't find the previous bug report for this.

If you *know* there's a previous bug report, don't open a new one.
