### ISSUE TITLE
Trust email validation from third-party logins

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/openstreetmap-website#4270]
Currently we trust emails from some providers, but not all. In the last ops meeting, we decided to accept third-party validated emails. I think this impacts the Github and Wikimedia providers.

**Comment by AshBakchod** [comment]
Hey @pnorman  I would like to work on this issue please assign me this issue

**Comment by tomhughes** [comment]
There's nothing really to work on - it's a one line fix once we've figured out which providers it affects.
