### ISSUE TITLE
Export as HTML doesn't work for the tracestrack layer

### ISSUE THREAD

**Issue by Binnette** [openstreetmap/openstreetmap-website#4273]
### URL

https://www.openstreetmap.org/#map=14/45.8360/6.8186&layers=P

### How to reproduce the issue?

1. Open osm.org
2. Select the layer "Tracetrack topo"
3. Click on Share button
4. In the panel, click on HTML button
5. Copy the html code
6. Paste the code in a website or local html file
7. Open the website/file in a web browser
8. BUG! the map is empty (no tiles are shown)

### Screenshot(s) or anything else?

Example with "Tracetrack topo" layer:

![image](https://github.com/openstreetmap/openstreetmap-website/assets/6597721/63d07a5d-fb9e-49a8-add7-8db9765e9e15)

<iframe width="425" height="350" src="https://www.openstreetmap.org/export/embed.html?bbox=6.746978759765626%2C45.8090593688804%2C6.890316009521485%2C45.862878930546415&amp;layer=tracestracktopo&amp;marker=45.83597565614144%2C6.818647384643555" style="border: 1px solid black"></iframe><br/><small><a href="https://www.openstreetmap.org/?mlat=45.8360&amp;mlon=6.8186#map=14/45.8360/6.8186&amp;layers=P">View Larger Map</a></small>

Example with "default Mapnik" layer:

![image](https://github.com/openstreetmap/openstreetmap-website/assets/6597721/559ed479-89df-4cce-b372-3c69b6d5c900)

<iframe width="425" height="350" src="https://www.openstreetmap.org/export/embed.html?bbox=6.746978759765626%2C45.8090593688804%2C6.890316009521485%2C45.862878930546415&amp;layer=mapnik&amp;marker=45.83597565614144%2C6.818647384643555" style="border: 1px solid black"></iframe><br/><small><a href="https://www.openstreetmap.org/?mlat=45.8360&amp;mlon=6.8186#map=14/45.8360/6.8186">View Larger Map</a></small>

**Comment by tomhughes** [comment]
Yes that won't work for the tracestrack layer because the tile provider limits the tiles to openstreetmap.org so they won't display on other sites.

**Comment by Binnette** [comment]
Ok, so maybe osm should be modifier to:
- display an info when clicking and sharing (and tracestrack is selected)
- and don't produce iframe code with a ref to tracestrack (and default it to mapnik)

**Comment by tomhughes** [comment]
Yes ideally we should disable export as HTML for that layer but that will need some work as it's not an ability we have right now.
