### ISSUE TITLE
Generate OSM_id locally

### ISSUE THREAD

**Issue by Cactustory** [openstreetmap/openstreetmap-website#4277]
### Problem

Hello
I want to edit my map locally and don't want to upload it to the OSM database, but nodes don't have OSM_id (maybe negative id).
How can I generate OSM_id for them locally?

**Comment by tomhughes** [comment]
This does not appear to be a question about the code in this repository so is off topic here.

Please use https://community.openstreetmap.org/help to ask for help from the community.
