### ISSUE TITLE
Waypoints ignored in GPS trace totals

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#4281]
In https://www.openstreetmap.org/user/jidanni/traces observe at the top today I have placed four traces.

Why would I put two pairs of duplicate traces?

Because one pair is missing their way points. It only has track points.

However the tallies just say xxxx points.

Well it turns out that that is only the track points.

Waypoints are not reflected in the totals.

They are not even lumped into the points total. 

Here is another program, osm tracker, which reports both totals for each:

![Screenshot_20231009_104101_OSMTracker for Android.jpg](https://github.com/openstreetmap/openstreetmap-website/assets/1230959/ee86e825-2206-420f-b657-71b8f5c4a311)

In

https://github.com/MarcusWolschon/osmeditor4android/issues/2415

 the problem is hidden on the tallies there on https://www.openstreetmap.org/user/jidanni/traces .

One cannot just by looking at the list, tell which traces are missing their way points. That's because the way point totals are completely not reported.

Well, they are shown on the map. So they also should be in the tallies.

**Comment by tomhughes** [comment]
Waypoints are not imported so they won't be counted.
