### ISSUE TITLE
Accept coordinates with a slash in search

### ISSUE THREAD

**Issue by thibaultmol** [openstreetmap/openstreetmap-website#4285]
### Problem

Currently if you put '52.47355/13.44108' in the search box, it won't realize you mean: "52.47355 13.44108"

**Comment by thibaultmol** [comment]
Pretty much any url from a maps related website will write the coordinates in their url like that.
It's surprisingly often that I copy coordinates from a url

**Comment by tomhughes** [comment]
Well sure, and I often copy fragments from URLs to other places, but when I do so I understand that I am doing something odd and that I'm responsible for decoding the URL and converting it to an acceptable format for the place where I'm going to use it.

The vast majority of people will never do things like that though...

**Comment by thibaultmol** [comment]
I'm currently also manually removing the slash.

But I figured there was no harm in having it maybe be included in the search bar behavior

**Comment by divyanshuagarwal-23** [comment]
Hi everyone @thibaultmol  I am working on this issue

Please assign this issue to me
is there any slack channel I can join, as I am new to this project

**Comment by HolgerJeromin** [comment]
@divyanshuagarwal-23 
Not every projects are working with bug assignments.
Some are finding them even a bad thing:
https://github.com/Microsoft/TypeScript/blob/main/CONTRIBUTING.md#issue-claiming
https://devblogs.microsoft.com/oldnewthing/20091201-00/?p=15843

We have over 550 open issues. 
I would suggest reading all comments of one bug you are interested in and just go ahead learning this code base. If this results in a PR: great.

**Comment by mmd-osm** [comment]
This would have to be added here https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/geocoder_controller.rb#L209-L225 and test cases updated here https://github.com/openstreetmap/openstreetmap-website/blob/master/test/controllers/geocoder_controller_test.rb
