### ISSUE TITLE
adding "print" button

### ISSUE THREAD

**Issue by pointhi** [openstreetmap/openstreetmap-website#430]
I find it is important to add a function to print the current map-view. Due to the different dimensions of screen, the print result isn't equal to the screen, and important pois on the side wouldn't be displayed.

The page-preview function in firefox and co. isn't a easy methode to become the sheet who you want, a special function like google and co is in my eyes necessary.

**Comment by gravitystorm** [comment]
I appreciate that printing the maps is something that a number of people want to do, but it's not a priority for our small team of developers to work on this. So I'm going to close this feature request. 

If anyone wants to make changes to the printing functionality, particularly if there's changes to the existing print.css stylesheet, then we welcome such pull requests.
