### ISSUE TITLE
zh-Hans and zh-Hant not supported in query feature box

### ISSUE THREAD

**Issue by SteveLz** [openstreetmap/openstreetmap-website#4310]
### How to reproduce the issue?

Set `zh-Hans` or `zh-Hant` as the preferred language. You will not get the display of `name:zh-Hans` or `name:zh-Hant`.

### Screenshot(s) or anything else?

[Query example](https://www.openstreetmap.org/query?lat=38.8950368&lon=-77.0365427)
![Query results display](https://github.com/openstreetmap/openstreetmap-website/assets/16166770/f21f963a-76e6-471d-b36c-c727868fe405)
[Target feature](https://www.openstreetmap.org/node/158368533)
Expected display: `华盛顿哥伦比亚特区` or `華盛頓哥倫比亞特區`
Actual display: `华盛顿哥伦比亚特区 / 華盛頓哥倫比亞特區`
Note: My secondary preferred language is `zh`

**Comment by tomhughes** [comment]
The only way I can see this happening is if `zh` comes before the longer versions in your preferred locales.

Are you logged in? What is your configured language list in your settings? If you're able to use the javascript console in the browser then what does `I18n.locales.get()` evaluate to?

**Comment by tomhughes** [comment]
A less obnoxious example than a low zoom query of an entire country would also be useful... That query doesn't even fine the UK relation for me.

**Comment by tomhughes** [comment]
Ah actually it did eventually as an enclosing object.

**Comment by SteveLz** [comment]
> The only way I can see this happening is if `zh` comes before the longer versions in your preferred locales.
> 
> Are you logged in? What is your configured language list in your settings? If you're able to use the javascript console in the browser then what does `I18n.locales.get()` evaluate to?

Yes, I forgot to mention, I put `zh` after `zh-hans`/`zh-hant`. If you have a second language set in your preferences it will also be displayed instead of `zh-hans`/`zh-hant`.

**Comment by SteveLz** [comment]
> A less obnoxious example than a low zoom query of an entire country would also be useful... That query doesn't even fine the UK relation for me.

I've replaced a node as an example, hoping it's less obnoxious.

**Comment by tomhughes** [comment]
I think the problem is that the locale list in the user settings is filtered against the available web site locales and that doesn't include `zh`, `zh-Hans` or `zh-Hant` as we use `zh-CN`, `zh-HK` etc.

What I don't understand is how you get chinese at all because I can't get `zh` to work as it also gets filtered out from the list given to the client.

**Comment by tomhughes** [comment]
Actually I think I understand - we only actually pass the server side locale (so in this case likely either `zh-CN`, `zh-HK` or `zh-TW`) to the client and the client then makes that the primary locale and adds `zh` and `en` as fallbacks.

**Comment by SteveLz** [comment]
In addition, the feature details box supports `zh-Hans`/`zh-hant`, even less commonly used tags such as `zh-hant-CN`. It's just that the query box doesn't support it.

**Comment by tomhughes** [comment]
They're completely unrelated - to start with one works on the server and the other on the client.
