### ISSUE TITLE
Unexplained 429 error (rate limiting?) on posting changeset comment, no error message

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#4320]
### URL

https://www.openstreetmap.org/changeset/143511539

### How to reproduce the issue?

1. be logged in my account
2. open https://www.openstreetmap.org/changeset/143511539
3. try to post changeset comment
4. it fails silently with error 429

I would at least expect some error message. Also, if that is rate limiting I would expect that it should not happen in this case. Within last hours I posted single changeset comment.

### Screenshot(s) or anything else?

![screen09](https://github.com/openstreetmap/openstreetmap-website/assets/899988/70dba29f-433f-43aa-96c2-684948503d1e)

**Comment by tomhughes** [comment]
Why are you showing a picture of the browser console rather than the UI which I believe would have clearly shown "rate limit exceeded" or similar as the error?

I can't comment on the specifics of whether the limit was correct without knowing the user you were trying to comment as.

**Comment by tomhughes** [comment]
I found your account and the problem is that there is an unresolved report against it, but we are overcounting the number of reports which is making the restriction harder than intended.

**Comment by tomhughes** [comment]
Hopefully b5995c5175b2fbc6743d4faeb404ad6cefb006ec should fix the over-enthusiastic rate limit.

**Comment by matkoniecz** [comment]
> Why are you showing a picture of the browser console rather than the UI which I believe would have clearly shown "rate limit exceeded" or similar as the error?

By "it fails silently" I meant that there is nothing in UI indicating a problem and I needed to check network logs to understand what is going on. My adblock is disabled at osm website.

I tried to reproduce it and failed - so likely either https://github.com/openstreetmap/openstreetmap-website/commit/b5995c5175b2fbc6743d4faeb404ad6cefb006ec is deployed and works or someone resolved bogus report.

Still, wondering about missing error message show if it was supposed to appear....

**Comment by tomhughes** [comment]
There is something odd going on - it definitely used to work but despite the response including `status: 429 Too Many Requests` that is not being passed to the xhr error callback so we wind up displaying a blank error message.

Not sure if it's a browser change, or something in rails 7.1 or what...

**Comment by tomhughes** [comment]
I'm not really sure how the traditional status text from the response is passed in HTTP/2.0 but I'm guessing that is missing... I was thinking the status header had replaced it but I think that is separate.

Using `xhr.getResponseHeader("status")` does get the header and `xhr.status` is 429 but `xhr.statusText` is just "error" and the actual error passed in the third argument of the callback is completely blank.

**Comment by tomhughes** [comment]
Apparently HTTP/2 doesn't support the text part of the traditional status line which is helpful... What I don't understand it how this worked in testing when originally implemented :-(

**Comment by HolgerJeromin** [comment]
https://stackoverflow.com/a/41637669/2194590
The http/2 protocol does not define this statustext anymore, so it is filled for the xhr api from the browser:

https://greenbytes.de/tech/webdav/rfc7540.html#rfc.section.8.1.2.4.p.2
