### ISSUE TITLE
Failed to install bigdecimal

### ISSUE THREAD

**Issue by Cactustory** [openstreetmap/openstreetmap-website#4325]
### How to reproduce the issue?

root@srv94600149:~/openstreetmap-website# bundle install
Don't run Bundler as root. Installing your bundle as root will break this application for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Installing bigdecimal 3.1.4 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/3.0.0/gems/bigdecimal-3.1.4/ext/bigdecimal
/usr/bin/ruby3.0 -I /usr/lib/ruby/vendor_ruby -r ./siteconf20231106-175013-k85mp2.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/3.0.0/gems/bigdecimal-3.1.4 for inspection.
Results logged to /var/lib/gems/3.0.0/extensions/x86_64-linux/3.0.0/bigdecimal-3.1.4/gem_make.out

  /usr/lib/ruby/vendor_ruby/rubygems/ext/builder.rb:95:in `run'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /usr/lib/ruby/3.0.0/tempfile.rb:317:in `open'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/builder.rb:161:in `build_extension'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/builder.rb:195:in `block in build_extensions'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/builder.rb:192:in `each'
  /usr/lib/ruby/vendor_ruby/rubygems/ext/builder.rb:192:in `build_extensions'
  /usr/lib/ruby/vendor_ruby/rubygems/installer.rb:847:in `build_extensions'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/source/rubygems.rb:203:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer/parallel_installer.rb:130:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer/parallel_installer.rb:115:in `install_serially'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer/parallel_installer.rb:91:in `call'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer/parallel_installer.rb:67:in `call'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer.rb:244:in `install_in_parallel'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer.rb:201:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer.rb:89:in `block in run'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/process_lock.rb:12:in `block in lock'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/process_lock.rb:9:in `open'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/process_lock.rb:9:in `lock'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer.rb:71:in `run'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/installer.rb:23:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/cli/install.rb:62:in `run'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/cli.rb:261:in `block in install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/settings.rb:142:in `temporary'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/cli.rb:260:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/cli.rb:34:in `dispatch'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/cli.rb:28:in `start'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/exe/bundle:37:in `block in <top (required)>'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /var/lib/gems/3.0.0/gems/bundler-2.4.21/exe/bundle:29:in `<top (required)>'
  /usr/local/bin/bundle:25:in `load'
  /usr/local/bin/bundle:25:in `<main>'

An error occurred while installing bigdecimal (3.1.4), and Bundler cannot continue.

In Gemfile:
  rails was resolved to 7.1.1, which depends on
    actioncable was resolved to 7.1.1, which depends on
      actionpack was resolved to 7.1.1, which depends on
        actionview was resolved to 7.1.1, which depends on
          rails-dom-testing was resolved to 2.2.0, which depends on
            activesupport was resolved to 7.1.1, which depends on
              bigdecimal

### Screenshot(s) or anything else?

I get this error when I use "bundle install".
How can I solve this?

**Comment by tomhughes** [comment]
You don't appear to have the ruby headers installed - you need to install whatever package contains the ruby headers that allow compiled extensions to be built.

What that package is called depends on what distribution you're running but it's probably `ruby-dev` or `ruby-devel`.
