### ISSUE TITLE
Is there any community that i can interact with ?

### ISSUE THREAD

**Issue by BLSowmya** [openstreetmap/openstreetmap-website#4327]
### Problem

Hello ,

Is there any way to contact community for this project?
i would like to know if there are any good first issues that to be done or how to get around with codebase 

Thankyou

### Description

I would like to contribute to this project - looking for some guidance or how to get started

**Comment by matkoniecz** [comment]
> looking for some guidance or how to get started

Have you seen https://github.com/openstreetmap/openstreetmap-website/blob/master/CONTRIBUTING.md ?

> if there are any good first issues

And https://github.com/openstreetmap/openstreetmap-website/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 ?

(such file and label is common among open source repositories)

**Comment by BLSowmya** [comment]
> > looking for some guidance or how to get started
> 
> Have you seen https://github.com/openstreetmap/openstreetmap-website/blob/master/CONTRIBUTING.md ?
> 
> > if there are any good first issues
> 
> And https://github.com/openstreetmap/openstreetmap-website/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 ?
> 
> (such file and label is common among open source repositories)

Yeah I had seen,thank you for mentioning again....I would like to ask for community channels on discord or any other social media ...please mention if there is any

**Comment by mmd-osm** [comment]
Have you checked out https://openstreetmap.community/ already?

**Comment by BLSowmya** [comment]
> Have you checked out https://openstreetmap.community/ already?

I have checked just now and joined ....Thank youu so much for mentioning

Have a great day!!
