### ISSUE TITLE
HTTP 500 error when trying to get access-token from master.apis.dev.openstreetmap.org with "openid" scope

### ISSUE THREAD

**Issue by hauke96** [openstreetmap/openstreetmap-website#4334]
### URL

https://master.apis.dev.openstreetmap.org/oauth2/token

### How to reproduce the issue?

It seems that adding the scope `openid` to the list of requested scopes returns a HTTP 500 error on the `https://master.apis.dev.openstreetmap.org/oauth2/token` endpoint. Yes, I gave permission to that scope and yes I used all correct client-id and -secret values. Removing `openid` from the list of wanted scopes solves the problem.

The error does _not_ appear on the productive www.openstreetmap.org server!

This bug does not affect me (and would have a very low priority for me personally), I just saw it by accident.

### Reproduce

Requires python3 `authlib` dependency:

```python
from authlib.integrations.requests_client import OAuth2Session

# dev server:
client_id = "..."
client_secret = "..."
domain = "master.apis.dev"

# prod server:
#client_id = "..."
#client_secret = "..."
#domain = "www"

redirect_uri = 'http://127.0.0.1:8000/callback'

# Remove the "openid" entry here and it'll work
scope = ["read_prefs", "openid"]

oauth = OAuth2Session(client_id=client_id, redirect_uri=redirect_uri, scope=scope)

authorization_url, state = oauth.create_authorization_url('https://'+domain+'.openstreetmap.org/oauth2/authorize')
print("Please visit:\n" + authorization_url)
print("")
authorization_response = input('Enter the redirect url from your browser and paste it here:\n')
token = oauth.fetch_token(
        'https://'+domain+'.openstreetmap.org/oauth2/token',
        authorization_response=authorization_response,
        client_secret=client_secret)
print("")
print("Access token is:")
print(token["access_token"])
```

1. Execute the script
2. Click on the presented link to open the OSM login form and grant access
3. The browser will redirect to `http://127.0.0.1:8000/callback?...`, copy the whole url from the browsers address bar, paste it into the terminal and press Enter
4. If everything works, the access token should appear. In the above script, the error message `requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://master.apis.dev.openstreetmap.org/oauth2/token` comes up.

This situation also appears using golang and the `golang/oauth2` library.

**Comment by mmd-osm** [comment]
OIDC needs a signing key in its config, which may simply be still missing on the dev instance.

Here’s the respective setting for production: https://github.com/openstreetmap/chef/blob/9c82d0eb2c75d1f5eb9b0689c5e3bed194fd1e0b/cookbooks/web/recipes/rails.rb#L151

**Comment by Zaczero** [comment]
I find it interesting how such an oversight passed the testing server.

**Comment by westnordost** [comment]
Actually, right now, I get a 404 on https://master.apis.dev.openstreetmap.org/oauth2/token

**Comment by westnordost** [comment]
Oh, I am sorry about that. Must have skipped that part in the spec.

**Comment by westnordost** [comment]
(Speaking of not reading the RFC correctly. Why do you send the client secret in the token request? I do not see it mentioned in https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3 )

**Comment by mmd-osm** [comment]
@tomhughes : could you please take a look at the `doorkeeper_signing_key` setting for master.apis.dev.openstreetmap.org?

I wanted to start testing JOSM OAuth2 settings with @tsmock, which is not possible as long as https://master.apis.dev.openstreetmap.org/.well-known/oauth-authorization-server doesn't work.

**Comment by tomhughes** [comment]
Thanks for actually explaining what the problem is - it's not going to be an easy thing to fix though so I'll need to have a think about how to do it.

**Comment by mmd-osm** [comment]
My assumption here is that doorkeeper-openid_connect gem depends on the signing key to work properly. Once I configured a signing key in my local settings, .well-known/oauth-authorization-server was also available, which is a prerequisite for JOSM.

**Comment by tomhughes** [comment]
Hopefully https://github.com/openstreetmap/chef/commit/1859ef73b97959019cfa27cfa446f1900f52ff3f has fixed this.
