### ISSUE TITLE
Export .pbf data 

### ISSUE THREAD

**Issue by Cactustory** [openstreetmap/openstreetmap-website#4338]
### Problem

How can I export whole data from my openstreetmap site on my server with .osm.pbf format?

**Comment by mmd-osm** [comment]
We're using https://github.com/zerebubuth/planet-dump-ng for this purpose in production.

**Comment by tomhughes** [comment]
That's may not be very helpful for a typical user though given the need to work from a postgres dump - the only option is likely to be osmosis though.

In case questions like this about using OpenStreetMap are probably better directed at https://community.openstreetmap.org/help than the bug tracker.

**Comment by AntonKhorev** [comment]
You may say that there is an *Export* button. If you press it, it will tell you about planet.openstreetmap.org where you can download the pbf dump. That's on the real openstreetmap.org website.

If you run your own osm instance, there's still an *Export* button, and it still tells you about planet.openstreetmap.org, but now it's useless.

**Comment by Cactustory** [comment]
> That's may not be very helpful for a typical user though given the need to work from a postgres dump - the only option is likely to be osmosis though.
> 
> In case questions like this about using OpenStreetMap are probably better directed at https://community.openstreetmap.org/help than the bug tracker.

what is the command for exporting data from my server?

**Comment by tomhughes** [comment]
That is not a feature offered by the web site - there are ways to do it but they are complex and you are better off seeking advice in the wider community as I have already suggested.
