### ISSUE TITLE
Button groups incorrectly displayed in RTL mode

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/openstreetmap-website#4347]
Button groups are rounding the wrong corners in RTL mode, for example:

![image](https://github.com/openstreetmap/openstreetmap-website/assets/147741/ac03c48f-8f4e-4f35-a245-8ee329a8b42d)

**Comment by tomhughes** [comment]
This is because r2 is reversing bootstrap's rules...

**Comment by gravitystorm** [comment]
See also https://github.com/openstreetmap/openstreetmap-website/issues/3910 but it's probably best to have two different issues for the buttons and the placeholders, so let's keep this one open too.

**Comment by jainsaksham1004** [comment]
I am interested in working on this issue.

**Comment by tomhughes** [comment]
I've already opened #4347 to fix it.
