### ISSUE TITLE
How to load planet diff into app?

### ISSUE THREAD

**Issue by Zaczero** [openstreetmap/openstreetmap-website#4354]
### Problem

I want to test some of the functionality on my local PC, as well as perform some performance benchmarks. I was unable to find instructions that would let me setup a database with the planet data loaded into it. I would assume there is some handy script to achieve just that.

### Description

I checked:
- https://github.com/openstreetmap/openstreetmap-website/tree/master/script
- https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md
- https://github.com/openstreetmap/openstreetmap-website/blob/master/CONTRIBUTING.md
- https://github.com/openstreetmap/openstreetmap-website/blob/master/README.md

**Comment by danieldegroot2** [comment]
This repository is focused on the source code for the openstreetmap.org website itself and the API, not the map data.
(as mentioned in the [README.md](https://github.com/openstreetmap/openstreetmap-website/blob/master/README.md).); "database" as used in [INSTALL.md](https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md) refers to the "development", "test" and "production" versions of the website source code.

* Documentation for using diffs can be found at [Planet.osm/diffs](https://wiki.openstreetmap.org/wiki/Planet.osm/diffs#Using_the_replication_diffs) on the OSM Wiki.
(I am skipping here general documentation on this and Planet.osm page as "diff" is included in your title already..)
* For your info, source code for planet.openstreetmap.org can be found at [openstreetmap/chef/.../cookbooks/planet](https://github.com/openstreetmap/chef/tree/master/cookbooks/planet)
* *  and the planet-dump-ng repo can be found at [https://github.com/zerebubuth/planet-dump-ng](https://github.com/zerebubuth/planet-dump-ng).


If you want to [use the tiles](https://switch2osm.org/using-tiles/), you do not need to clone the map database (though in your case this is likely unrelevant).

For any further questions on using map data, I would recommend creating a new post at the [OpenStreetMap Community Forum - Help and support category](https://community.openstreetmap.org/c/help-and-support/7/none), where your questions can be answered by many smart people, and these answers are open for others to benefit from.

**Comment by Zaczero** [comment]
Hey thank you for such a rich response! But I believe there was a slight misunderstanding. I am asking for a way to populate the API database with downloaded planet data so I can perform some testing. Like a basic development setup. I don't want to run on an empty database as it would be a poor testing/benchmarking experience. I am specifically looking for some script that would do that step for me - like setup development environment script or something.

**Comment by danieldegroot2** [comment]
Edited my reply with a link to the configuration page.

**Comment by Zaczero** [comment]
This answered my question! Thank you so much! As a suggestion, I think it would be a good idea to hint this in the [CONTRIBUTING.md](https://github.com/openstreetmap/openstreetmap-website/blob/master/CONTRIBUTING.md) file. I can imagine quite many new contributors needing that for working on the API.

**Comment by danieldegroot2** [comment]
While it is relevant to those tasks, it is not directly relevant to others and including it loses some overview.
In [Configuration](https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md#configuration) section, it may be useful to list the available 'configuration steps', so they are less easily overlooked.
