### ISSUE TITLE
OAuth 2: Granting partial permissions not possible

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/openstreetmap-website#4360]
### Problem

OAuth 2 does not allow granting permissions partially, which was possible with OAuth 1.0a.

This may scare off some privacy / security-aware users from using software that **can** e.g. create notes, upload GPX tracks etc. but doesn't need these permissions when these features are not used.

### Description

Using authorization with OAuth 1.0a, it was possible for users to choose which of the permissions an application requests are granted. Which of these permissions were actually granted then could be queried with `/permissions` endpoint. This seems to be not possible with OAuth 2.0 scopes anymore.

As the author and maintainer of StreetComplete, I actually did get several requests and inquiries why the app needs the "create note" as well as the "read/write gpx tracks" permission.

As the latter is only used for a relatively minor and difficult to discover feature, it was made optional following https://github.com/streetcomplete/StreetComplete/issues/4122. I.e. the user is able to not grant this particular permission and the app would work normally.

**Comment by AntonKhorev** [comment]
It is possible, there's just no ui for that. Right now users would have to manually edit the scopes parameter in the url.

**Comment by westnordost** [comment]
I believe we mean something different. In the authorization step where the user selects on osm.org which permissions requested by the client he is going to grant. I do *not* mean that a client can request less permissions than for which the client has been registered for.

Note the checkboxes:

### Authorization with OAuth 1.0a
![oauth1](https://github.com/openstreetmap/openstreetmap-website/assets/4661658/e524f80a-59ef-41b9-bfb8-a817fb760019)

### Authorization with OAuth 2.0
![oauth2](https://github.com/openstreetmap/openstreetmap-website/assets/4661658/193c9d40-8a88-4be8-88c5-2fbf1b882010)

**Comment by tomhughes** [comment]
I'm not sure it's a good idea to allow it though - the user has no way of knowing the effect of disabling permissions that the client has asked for after all.

I would have thought client authors would actually be against this because it will tend to create support load for them when people manage to break things by removing permissions.

**Comment by woodpeck** [comment]
This is one of my perennial peeves with the HOT tasking manager - if I want to look up some task that somebody has created, I need to grant the tasking manager the permission to "modify the map" which I never trusted it enough to do and which cannot be deselected.

OSMcha, on the other hand, also asks for the permission to "modify the map" but you can simply not grant that, and it will still work (unless you try anything that requires permissions not granted). I am not sure how gracefully it fails if you try.

**Comment by westnordost** [comment]
Well, client developers had to deal with this situation somehow in OAuth 1.0a. And they were able to deal with it *very* gracefully, by querying the permissions endpoint. The permissions endpoint still exists, though I am not sure for what it would be useful now.
Or less gracefully, just show an error or force a re-login if any particular API call fails due to missing permissions. (StreetComplete does that in case of trying to use the GPX track feature without having granted that permission.)

It would be easier of course for client developers to not deal with this at all. But it would also be easier for (Android) app developers if an app would just have all the permissions it asks for on app install instead of the user being able to grant only a subset of what has been asked for. (As it had been the case before runtime app permissions were introduced in Android 6)

**Comment by tomhughes** [comment]
The other problem is that is somebody changes their mind their is no way for them to add the extra permissions - that is true for OAuth 1 as well I believe but at least there the client can start a new authorisation but with OAuth 2 that will wind up reusing the existing one unless the user revokes that on the server side.

**Comment by westnordost** [comment]
Hmm, maybe the preferred OAuth 2 way to do it would be that the client requests different tokens for different purposes.

E.g. HOT could request only the minimum it needs to function on login, and then when using the map-edit feature, it would again ask for authorization upon using that feature. Because the user is likely already logged in in his browser at least from the last authorization request, the user is able to quickly authorize it.

Now, for non-browser applications, this flow is a little less convenient. At least StreetComplete and IIRC Vespucci both use a WebView instead of a browser to authorize which then of course does not save the login cookie. Which means, for every new token, the username and password needs to be reentered.
(I know, it is recommended to not use a WebView but the device's browser, but we had problems in the past with that. There a quite a number of browsers for Android, and some - e.g. if I remember correctly the default browser for a popular custom rom - fail to forward a redirect URI like `streetcomplete://oauth` to whichever app registered this uri scheme. Maybe @simonpoole also remembers if there were other reasons to use a WebView.)

**Comment by tomhughes** [comment]
Well the problem is that you can't (with our implementation at least) just request multiple tokens because the server aggregates all authorisations for a given client, so when you try and get a new token it will see the existing authorisation and return a token for it without asking the user to authorise again.

That wasn't true for OAuth 1 but that led to people having vast lists of authorisations for the same client if it was a client that didn't save tokens and got a new one every time.

**Comment by westnordost** [comment]
Oh, but what happens if for a client that registers to have all permissions, I call

authorize?response_type=code&client_id=AaV513LxeuSA1EL5q9jhiwRTi5bZyaQFCuZdYMebNwg&redirect_uri=https%3A%2F%2F127.0.0.1%3Aoauth&scope=**read_prefs%20write_prefs**

, authorize, and then later call

authorize?response_type=code&client_id=AaV513LxeuSA1EL5q9jhiwRTi5bZyaQFCuZdYMebNwg&redirect_uri=https%3A%2F%2F127.0.0.1%3Aoauth&scope=**write_api**

I get the same token, but that token now has all three permissions? (I guess that would be fine for the described use case, wouldn't it?)

**Comment by tomhughes** [comment]
I honestly don't know but it will come down to https://github.com/doorkeeper-gem/doorkeeper/blob/9fc81d5009aef533ca8116285148cb6e37549ff2/lib/doorkeeper/oauth/client_credentials/creator.rb#L11 I think.

We have `reuse_access_token` set but it looks like that code may consider the scopes when deciding if an existing token is a match?

**Comment by tomhughes** [comment]
Actually I think that one is for the client credentials flow but there is likely similar code somewhere for other flows.

**Comment by simonpoole** [comment]
> I know, it is recommended to not use a WebView but the device's browser, but we had problems in the past with that.
Historically, being very nice, it didn't work "reliably" and googles arguments against using a Webview have mostly been self serving in any case.

Given that we, in the 1.0a case, ask for nearly all (that's the nature of the beast) permissions to start with it isn't a big deal for us, though I would prefer if users would at least in principle be able to control things more fine grained.

**Comment by westnordost** [comment]
> Well the problem is that you can't (with our implementation at least) just request multiple tokens because the server aggregates all authorisations for a given client, so when you try and get a new token it will see the existing authorisation and return a token for it without asking the user to authorise again.

I just tested this. I created one access token to access everything, and then one access token for only `read_prefs`. It works as expected, i.e. the second token really only has access to reading preferences while the other has access to everything.

**Comment by westnordost** [comment]
So anyway, after having read the RFC, it doesn't look like OAuth 2 is designed to allow this kind of flow we used to have with OAuth 1.0a. It would be a (possibly non-RFC compliant, would need to read the exact wording) extension to OAuth 2.

To summarize:

- With the authorization flow in OAuth 1.0a, it was possible for the user not to grant all requested permissions. The client then (ideally) had to verify after using the `permissions/` endpoint whether it got all permissions it needed and handle it.

- The authorization flow in OAuth 2 (instead) does not allow the user to selectively only grant some of the requested permissions. However, it provides *clients* a way to request less permissions than what has been listed during registration for the client. This flow enables the client to dynamically only request the permissions it needs right now, using several different tokens to access different parts of the API.
  This solution is somewhat superior to the OAuth 1.0a flow for fine-grained permissions and also convenient for users, however, only for applications that use in-browser authorization (like any web-app)

So, I will close this. Web-apps (such as the mentioned HOT tasking manager) already can implement fine-grained permissions with OAuth 2.

**Comment by AntonKhorev** [comment]
> So anyway, after having read the RFC, it doesn't look like OAuth 2 is designed to allow this kind of flow we used to have with OAuth 1.0a.

It is designed to allow this.

https://datatracker.ietf.org/doc/html/rfc6749#section-3.3

> The authorization server MAY fully or partially ignore the scope requested by the client, based on the authorization server policy or the resource owner's instructions.

checkboxes = "the resource owner's instructions"

**Comment by westnordost** [comment]
I see, and also quite convenient for the client developer, as the granted scopes are returned to the redirect uri.

**Comment by westnordost** [comment]
In any case it would be helpful to have a decision about if checkboxes are to return for the OAuth 2 implementation (at some point) because it affects client implementations.

I.e. in that case, clients should not assume that everything that has been requested was granted, but must read the `scope` parameter of the response to learn which permissions have been granted. I.e. similar to but more straightforward than the old OAuth 1.0a auth flow.

My preference then would also be if the checkboxes returned, because while it may be possible to request granular permissions as described in https://github.com/openstreetmap/openstreetmap-website/issues/4360#issuecomment-1822949775 I doubt that any client developer will actually implement that. In any case, whether or not it is done depends on the individual **client** developers, while actually it should be the **user**'s choice.

**Comment by westnordost** [comment]
I ended up implementing checking for the granted scopes to be forward compatible to a possible change in the UI on osm.org when the user should grant the authorization request. Was just a few lines of code anyway.

**Comment by mmd-osm** [comment]
So I tried this out in https://gist.github.com/mmd-osm/a8edb405918795d7d823b9088bd12f41 and replaced the static list by some checkboxes. You can deselect some of the scopes before authorizing the request, and resulting token would only include the exact list of scopes which have been selected.

> Well the problem is that you can't (with our implementation at least) just request multiple tokens because the server aggregates all authorisations for a given client, so when you try and get a new token it will see the existing authorisation and return a token for it without asking the user to authorise again.

I think on the UI, you would indeed only see a single entry per application. However, on the database there are several tokens for each distinct set of scopes. To be honest, that's a bit confusing for a user. I haven't checked which of the different tokens is shown on /oauth2/authorized_applications in the end.

![image](https://github.com/openstreetmap/openstreetmap-website/assets/5842757/90b6e3a0-f454-44c0-8ed8-eeb3d08e56ed)

There's another issue here. Since a few weeks, I'm getting the /oauth2/authorize "Authorization Required" dialog, even if I have previously authorized the app. If I'm not completely mistaken, this used to be different in the past. Maybe the recent addition of openid has changed the default behavior?

Now with this dialog showing up all the time, it would be good, if the checkboxes would reflect the previous scope selection. Otherwise this is getting fairly annoying for users to deselect some scopes each time. I haven't really looked into this part yet, but I believe it might be useful to do so.
