### ISSUE TITLE
Report a feature in the website

### ISSUE THREAD

**Issue by angoca** [openstreetmap/openstreetmap-website#4375]
### Problem

Vandalism could be everywhere in OSM, but new users could find it difficult to report it.
Especially from the OSM website, where there is no direct option to it once they detect it.

A user could create a note and then wait several years to be processed, but this is not a very effective way.

Also, the visitor could identify the contributor who committed the vandalism and then report it from the user's profile. But again, this is a difficult way for a new user.

### Description

For example, a friend told me about these trees with an invalid denotation pointing to a SPAM URL of German Porn: https://www.openstreetmap.org/node/11361549930#map=19/51.37801/12.41796

I would like something on the map, like a "feedback" option, or a similar thing as "reporting" the notes that creates a form for them.
Something pointing to:

https://www.openstreetmap.org/reports/new?reportable_id=11361507746&reportable_type=Node

### Screenshots

This is the way to report a note, in the lower part:
<img width="380" alt="image" src="https://github.com/openstreetmap/openstreetmap-website/assets/294317/2f11dc88-02cd-4e05-bd60-0e41eb5618a4">

What I propose is to have something similar to report OSM features (Node, Way, Relation)
<img width="451" alt="image" src="https://github.com/openstreetmap/openstreetmap-website/assets/294317/68926599-7ac3-4853-89c4-a222e493a977">

Or directly in the changeset:
<img width="416" alt="image" src="https://github.com/openstreetmap/openstreetmap-website/assets/294317/c31b3c71-cc02-4415-ab7b-43d2d0fd47d3">

And the URL could accept more options for this form:
<img width="693" alt="image" src="https://github.com/openstreetmap/openstreetmap-website/assets/294317/63f91b93-2a27-4cf1-bd5e-dced98d91a4f">

It only accepts Users or Notes: https://github.com/openstreetmap/openstreetmap-website/blob/97d2c223aa4706054b1219d30c1ea048a2805872/app/controllers/reports_controller.rb#L57

**Comment by tomhughes** [comment]
Seems like this is just asking for #4370 so this is best addressed there.
