### ISSUE TITLE
RTL text view on Safari iOS compared to Firefox

### ISSUE THREAD

**Issue by habi** [openstreetmap/openstreetmap-website#4377]
### URL

https://www.openstreetmap.org/node/1939345603

### How to reproduce the issue?

Viewing node above on iOS (17.2, on an iPhone 12 mini) trips up the table view, while viewing it on Firefox 120.0 (64-bit) on Ubuntu 20.04 shows it as expected.

Related to https://github.com/openstreetmap/openstreetmap-website/issues/3427

### Screenshot(s) or anything else?

iOS
![IMG_6345](https://github.com/openstreetmap/openstreetmap-website/assets/1651235/d5f517ee-310f-40ff-9b7a-7871282ef32c)

Ubuntu
![Screenshot from 2023-11-29 11-36-55](https://github.com/openstreetmap/openstreetmap-website/assets/1651235/33bf922d-f15e-4ed8-95b3-188e6d807b13)

**Comment by tomhughes** [comment]
Presumably you think this is a bug in our code rather than a bug in Safari? Is there some particular reason why you think that?

**Comment by tomhughes** [comment]
As an additional data point it seems that Chrome agrees with Firefox.

**Comment by habi** [comment]
> Presumably you think this is a bug in our code rather than a bug in Safari?
> 
I *did* think that, but after spending a tiny bit more brain cycles on it, it is evident that this is a Safari problem, not an OSM one.

**Comment by habi** [comment]
> Chrome agrees with Firefox.

And Safari Version 17.1 (19616.2.9.11.7) on macOS 14.1.1 (23B81) agrees with Safari on iOS :)

<img width="361" alt="Screenshot 2023-11-29 at 14 14 19" src="https://github.com/openstreetmap/openstreetmap-website/assets/1651235/19ae0130-ef06-4a72-bcfa-94a71bd2087e">

I'll try to find a way to submit this issue to Apple.

**Comment by habi** [comment]
For what it's worth, this was submitted to Apples Feedback assistant as: "FB13424819 (RTL text in a table renders table borders wrong.)"
