### ISSUE TITLE
Report rate limit settings in capabilities API call

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/openstreetmap-website#4380]
### Problem

Recently, hourly upload limits (#4319) were introduced to the API. Especially new mapper will not know about this limitation and could be irritated, confused or even discouraged to see hours of work be rejected by the API. For example: a new mapper maps 200+ rectangular buildings during a mapathon over the course of 3 hours (this would be about 1 building per minute). As this totals to a number of over 1000 _"changes"_, it will be rejected by the rate limiting of the API. This is not a great user experience, as now all the mapper can do is to wait 17+ hours in order for his quota to have grown sufficiently to accept the change, or undo an unknown amount of map edits to get back within their current quota.

It would be better if OSM editor software would inform the user beforehand (i.e. while mapping) that the user is approaching the rate limit. Optionally, in the case when a limit was hit, an OSM editor could also show how many changes would have to be undone or how long the required wait would be.

In order to implement such features into OSM editors, the values for these limits would need to be known to the applications, as using any hardcoded values might get outdated any time when these settings are changed on the API side.

### Description

It would be possible to include the settings of the rate limiting in the response of the capabilities call, for example like this:

```xml
<osm version="0.6" …>
  <api>
    <version minimum="0.6" maximum="0.6"/>
    …
    <ratelimit min_changes_per_hour="100" initial_changes_per_hour="1000" max_changes_per_hour="100000" days_to_max_changes="7" />
    …
  </api>
  …
</osm>
```

It might also be useful to add an indication which "algorithm" is used to calculate the respective current rate limit value, to accommodate potential future changes to the internal method. For example by adding a `algorithm_version` attribute.

Alternatively (or additionally), the capabilities call could return the user-specific current rate limit for the logged in user when (OAuth2 bearer) credentials are provided during the call to the `capabilities` (or `user/details`?) request.

**Comment by mmd-osm** [comment]
> It would be possible to include the settings of the rate limiting in the response of the capabilities call

I don't think this will buy you much, since you don't have all the information available on client side to do the same calculation that will be done on the server. It's even impossible, because some of the information is only available to admins/moderators and not exposed through any APIs, not even private ones.

> could return the user-specific current rate limit for the logged

At one point we included this information in the API error message, but in the end decided to remove any such information. Please refer to #4319 for more details on the discussion, it's all mentioned there.

**Comment by mmd-osm** [comment]
If you're happy to use some heuristics, you might as well take the "account_created" info in https://api.openstreetmap.org/api/0.6/user/details.json into account, and encourage users to save more frequently during the first few days of their mapping, i.e. by reducing the save button alert threshold values. While not an ideal solution, it might avoid a "losing hours of work" kind of scenario.

**Comment by tordans** [comment]
> and encourage users to save more frequently during the first few days of their mapping, i.e. by reducing the save button alert threshold values.

:+1: for this. The scenarios that have been discussed are "new mapper + mapping event" which IMO leads to mapping activity that can easily be saved in smaller chunks (again and again) because they will follow the same pattern ("`Add buildings as part for #SomeCampaign`").

**Comment by mmd-osm** [comment]
I'm going to close this one now. As mentioned earlier, new (humanitarian) mappers should be encouraged to save their work more frequently. This could be accomplished by evaluating the account_creation date returned by the user/details API endpoint.
