### ISSUE TITLE
Blocked upload due to rate limiting counts as successful upload

### ISSUE THREAD

**Issue by wolfgang-8** [openstreetmap/openstreetmap-website#4386]
### URL

https://www.openstreetmap.org/user/Testing_limit1

### How to reproduce the issue?

In [this example](https://community.openstreetmap.org/t/the-new-rate-limiting-prevents-participants-to-missing-maps-mapathons-from-saving-buildings/106610/29) user [Testing_limit1](https://www.openstreetmap.org/user/Testing_limit1) successfully upload the first changeset and get a block message during the second upload. But on its profile page two edits are shown - the successful and the blocked one. The changesets page correctly list only the first successful upload.

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/openstreetmap-website/assets/105060323/8c25eb0a-ae34-4709-8b26-5c586d4d8a4f)
![image](https://github.com/openstreetmap/openstreetmap-website/assets/105060323/16ec562c-090e-4e2d-b461-f00ba0c86523)

**Comment by mmd-osm** [comment]
This is related to #3592, the changeset list on the left empty hides changesets, while the edit count at the top counts all changesets. Before you can upload any data, you need to create a new empty changeset. If the upload later fails, that empty changeset will be still around.

**Comment by tomhughes** [comment]
Ad @mmd-osm says this is expected as the changeset has been created, it just doesn't contain any edits as the upload failed.

**Comment by wolfgang-8** [comment]
Thanks for explanation! From the user's perspective it's a bit confusing, as the information labels say the opposite. I think, it would be clearer, if on the profile page "Changesets X" and on the changesets page "Edits by XY" are shown.
