### ISSUE TITLE
Annonymous note message is misleading

### ISSUE THREAD

**Issue by angoca** [openstreetmap/openstreetmap-website#4400]
This message appears on the website whenever an anonymous note is visualized: "This note includes comments from anonymous users which should be independently verified."

https://github.com/openstreetmap/openstreetmap-website/blob/67b0b5b885b8c488986260617775548fd5a5acc5/config/locales/en.yml#L2968

I have seen that many mappers have started to close them automatically, without thinking, just because they are anonymous (And they do not have another source to validate). You can see an excellent example in Spain - https://www.openstreetmap.org/note/4010044.

I have closed thousands of anonymous notes with valid content, and I have had enough criteria to make a map change. I know that we fear to introduce vandalism into the map. But who is going to do vandalism by stating a hydrant is missing from a note?

Regarding the anonymous notes, let's check the possible sources.

Let's start with the notes from OnOSM.org, which are all anonymous.  A person who follows the steps to fill out the form knows the place, and the result is an anonymous note. In this case, the mapper has the necessary information (creation date of the note, street-level photos could also be available, existing OSM data from the area, historical notes from the area), and the mapper's criterion could lead to a map change or not. In this case, the message on the OSM website about anonymous notes could be misleading. If a mapper wants to close notes will close it, and the valuable report will be lost in the hidden notes.

A similar case happens when someone is doing an on-field survey. If the mapper checks the time between the notes' creation time and location, then the mapper has enough information to trust the note. No one else must go to each note's place to validate the data.

Conversely, a 5-year-old or even a 10-year-old note is less trustful, even if a registered user created it. Many things have happened in the last few years.

Also, let's put us in the position of a person has taken the time to give us this feedback via a note. That person will want to see his feedback on the map someday. But in contrast, we close it because that person is not registered. In that case, we are losing Map users because that person will think: Feedback (on notes) is never considered, this is an obsolete map.

(I know there are issues about notes, that we should include the app source and other data, but that is a different discussion that is already in the GitHub issues.).

I want this message from the OSM change to be changed to something different. They are preventing mappers from closing notes just because they are anonymous.

**Comment by SomeoneElseOSM** [comment]
> But who is going to do vandalism by stating a hydrant is missing from a note?

I suspect you might be surprised.  With a DWG hat on I've seen lots of anonymous notes used to "add evidence" to support fake names added for all sorts of reasons (lakes and streets named after friends, someone pretending that their back garden is a park, etc.)

> Let's start with the notes from OnOSM.org, which are all anonymous. A person who follows the steps to fill out the form knows the place

Not necessarily - while some are obviously valid, a significant number are just misplaced spam.

Personally, I'm far more worried by people taking anonymous notes at face value and just adding the data without stopping to think about the evidence.

I believe that the current wording of the message ("This note includes comments from anonymous users which should be independently verified." in English) gets the balance about right.

**Comment by matkoniecz** [comment]
> But who is going to do vandalism by stating a hydrant is missing from a note?

Trolls and malicious people.

Also, we had people being highly confused or copying google maps.

**Comment by matkoniecz** [comment]
> I have seen that many mappers have started to close them automatically, without thinking, just because they are anonymous (And they do not have another source to validate). You can see an excellent example in Spain - https://www.openstreetmap.org/note/4010044.

not sure about context there, but there were also trolls or confused people adding huge volume of low value notes (see onosm.org notes in Iran - https://resultmaps.neis-one.org/osm-notes-country?c=Iran ).

though this type of notes would be eligible for closure also when created by registered mapper

**Comment by matkoniecz** [comment]
I propose to close this issue as in fact you need to verify anonymous notes rather than blindly trust them.

**Comment by divyanshuagarwal-23** [comment]
Hi everyone @angoca  I am working on this issue

Please assign this issue to me
is there any slack channel I can join, as I am new to this project

**Comment by mmd-osm** [comment]
Closing as suggested by earlier comments .
