### ISSUE TITLE
Feature request: Wikipedia links and name tooltips for Wikidata tags

### ISSUE THREAD

**Issue by AndrewHain** [openstreetmap/openstreetmap-website#4416]
### Problem

There is an ongoing level of friction between “I don’t want to update duplicate tags” and “I prefer human readable information”, with https://lists.openstreetmap.org/pipermail/talk/2023-December/088465.html as a recent example.

### Description

The proposal is to add a Wikipedia link icon, which could be a “w” favicon the same size as the colour preview, to each Wikidata tag in the tag listing, and link to the associated article in Wikipedia, in the user’s interface language if there is one.

In addition a tooltip of the name from Wikidata, also in the user’s language, could be added to the Wikidata link.

**Comment by tomhughes** [comment]
Don't we already turn wikipedia and wikidata tags into links?

**Comment by AntonKhorev** [comment]
They want to turn wikidata tag into wikipedia link. You get wikidata Q123456 and somehow figure out its wikipedia article.

**Comment by tomhughes** [comment]
We're not going to be doing anything that requires us to query wikidata so I think we'll have to say no to this one.
