### ISSUE TITLE
Add openairportmap.org as link to tags with icao-key

### ISSUE THREAD

**Issue by dktue** [openstreetmap/openstreetmap-website#4420]
### Description

Hi,

first of all a disclaimer: I'm the author of [openairportmap.org](https://openairportmap.org).

I saw the currently in tag-list the icao-Tags are not linked anywhere and I was thinking if it wouldn't be nicer if they linked to [openairportmap.org/{ICAO}](https://openairportmap.org) ?

I'm looking forward to your opinions. :-)

Best regards
dktue

### Screenshots

![image](https://github.com/openstreetmap/openstreetmap-website/assets/2878623/e7e019bb-4c59-423f-8dab-34dabaf365dd)

**Comment by tomhughes** [comment]
Speaking personally my opinion is that we shouldn't be blessing one site over others with a link like this - if we do it for then what do we do when another site comes along and asks for the same? Do we start adding a popup menu to allow users to select their preferred site? That way lies madness...
