### ISSUE TITLE
Why i am blocked by Fizzie41 in OpenStreetMap

### ISSUE THREAD

**Issue by Juner13** [openstreetmap/openstreetmap-website#4444]
Okay so i just made several edits of the Cat Hai - Cat Ba Bridge project in Vietnam, but Hoang Tuan Viet keeps reverting it and leaves a discussion on my changeset along Fizzie41. However, i gave up and went to OpenStreetMap Forum to create a new post thread about this incident, but apm-wa flagged my post as inappropriate and locked me from commenting more, and once i engaged with Fizzie41 by resolving one of the notes and writing disruptive messages, Fizzie41 blocks my account in OpenStreetMap and now i can't edit the map, add new notes, and do other actions here. Can you please tell me the reason why i am blocked from OpenStreetMap guys?

**Comment by SomeoneElseOSM** [comment]
For information - [forum thread](https://community.openstreetmap.org/t/cat-hai-cat-ba-bridge-project-keeps-undoing/107416) and [temporary editing block](https://www.openstreetmap.org/user_blocks/15515).

The block message says "Again, if you should wish to discuss this matter further, please contact us by e-mail at data@osmfoundation.org quoting Ticket #2023072810000016 — (User “Bvonter23”)".  IF you wish to discuss it, I suggest you do that.
-- Andy, also from the DWG (and nothing to do with this repository).

**Comment by tomhughes** [comment]
This is completely off topic - this tracker is for bugs in the web site software not complaints about operational decisions relating to a specific deployment of this software.
