### ISSUE TITLE
Dead Link on /copyright page

### ISSUE THREAD

**Issue by hungerburg** [openstreetmap/openstreetmap-website#4470]
### URL

https://www.openstreetmap.org/copyright/en

### How to reproduce the issue?

Where on the page the text reads

> Austria: Contains data from … and Land Tirol (under [CC BY AT with amendments](https://www.tirol.gv.at/applikationen/e-government/data/nutzungsbedingungen/)).

The resource linked above now is at https://www.tirol.gv.at/data/nutzungsbedingungen/ - It might be a bit of interest, as the amendments are posted there? The new URL looks like it might be stable for some time too.

The link to Vorarlberg is also broken, but there is already an issue for that.

**Comment by tomhughes** [comment]
Unfortunately we can't make changes to that page without LWG agreement.

**Comment by hungerburg** [comment]
I see, sounds reasonable, not only the URL did change, content too: [There was no CCPL4 in 2012](https://github.com/openstreetmap/openstreetmap-website/commit/76b568b9f0b1e8dcc19c4c093901fa9f6cf8a9fc), this only came in 2013.

**Comment by gravitystorm** [comment]
@hungerburg thanks for pointing this out.

Please see: https://github.com/openstreetmap/openstreetmap-website/blob/master/CONTRIBUTING.md#copyright-attribution

> The list of attributions on the /copyright page is managed by the [OSMF Licensing Working Group (LWG)](https://wiki.osmfoundation.org/wiki/Licensing_Working_Group).
>
> If you want to add another attribution, or make changes to the text of an existing attribution, please follow these steps:
>
> * First, contact the LWG to discuss your proposed changes.
> * If the LWG approves, please create a pull request with your proposed changes.
> * Finally, please ask the LWG to formally approve the wording used in the pull request (by having an LWG member comment on the PR).
>
> When we have formal confirmation from LWG, we can go ahead and merge the PR.
