### ISSUE TITLE
Trim username/e-mail whitespace in login page

### ISSUE THREAD

**Issue by zstadler** [openstreetmap/openstreetmap-website#4471]
### Problem

OSM users are redirected to OSM login for authentication. We continuously receive complaints about users unable to access their accounts.

95% of the user issues are due to extra space added to the OSM username/email that is added by many mobile keyboards with auto-completion. Users do not notice that extra space and their login fails

### Description

The requested solution to the problem is to trim leading and trailing whitespace. It is a safe change since leading and trailing whitespace characters are not permitted as OSM usernames or an e-mail address

### Screenshots

The error produced when a space character is appended to the username, as done by many mobile keyboards with auto-completion

![image](https://github.com/openstreetmap/openstreetmap-website/assets/1304610/66999f36-6b57-4e02-a286-cd4e213856cf)

**Comment by tomhughes** [comment]
We already have validations on the user model to prevent leading and trailing whitespace on these fields?

**Comment by zstadler** [comment]
Apparently, we do. 

For leading whitespace
![image](https://github.com/openstreetmap/openstreetmap-website/assets/1304610/106de83b-0b02-41c5-bdfd-11ecf3bd139c)

For trailing whitespace:
![image](https://github.com/openstreetmap/openstreetmap-website/assets/1304610/869f534e-1e6d-4c06-9152-b647e3ca60dc)

**Comment by birante** [comment]
Hi everyone @tomhughes @zstadler,

I'm Birante, a newcomer. I've been working on this bug and have created a [PR](https://github.com/openstreetmap/openstreetmap-website/pull/4501) to fix it. I would appreciate your feedback on my proposal. Thank a lot.

**Comment by divyanshuagarwal-23** [comment]
Hi everyone @zstadler I am working on this issue
1. Please assign this issue to me
2. is there any slack channel I can join, as I am new to this project
