### ISSUE TITLE
Comment vs. Subscribe on diary posts

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#4491]
### Problem

1. Fill out a comment on somebody's diary post.
2. At the bottom you will find two buttons:
- Comment, and
- Subscribe

The user thinks s/he can only pick one.

Yes, if one presses "comment" one does also get subscribed, but the interface makes it look like one must make a choice.

**Comment by gravitystorm** [comment]
I agree, the design here isn't great. I've thought about it before without coming up with an obvious good solution.

**Comment by divyanshuagarwal-23** [comment]
Hi everyone @jidanni  I am working on this issue

Please assign this issue to me
is there any slack channel I can join, as I am new to this project

**Comment by jidanni** [comment]
@divyanshuagarwal-23 I would love to,  but I'm not in charge here.

**Comment by AntonKhorev** [comment]
Something like this, with the _Subscribe_ button above comments, similar to changeset discussion?

![image](https://github.com/openstreetmap/openstreetmap-website/assets/4158490/0b977401-3c74-400c-93f7-8c146e19b941)

**Comment by AntonKhorev** [comment]
After #4518 the Subscribe button is no longer at the bottom.
