### ISSUE TITLE
Display authenticatoin-related timestamps on Oauth2 tab

### ISSUE THREAD

**Issue by mnalis** [openstreetmap/openstreetmap-website#4494]
### Problem

When logged in, on `Oauth1 settings` tab `https://www.openstreetmap.org/user/MYUSERNAME/oauth_clients` I can see the  application name and **when it was issued**.

However, on `OAuth 2 authorizations` tab at https://www.openstreetmap.org/oauth2/authorized_applications there is no timestamp column, only `Application` and `Permissions` .

### Description

I find timestamp information very valuable for my authorizations. I'd like to suggest adding two additional columns to `OAuth 2 authorizations` tab:

- timestamp where it was issued (i.e. just like Oauth1 tab shows)
- timestamp when that authentication token was last used (that helps a lot determining if it should be revoked).

**Comment by mmd-osm** [comment]
> timestamp where it was issued 

Token creation timestamps would at least be available in database table oauth_access_tokens as field "created_at". To display these timestamps, some additional filtering might be needed, like excluding revoked (+ possibly expired tokens, if this happens to be supported at one point).

> timestamp when that authentication token was last used 

That's not possible. Validating tokens is a read only database operation, i.e. a last used timestamp is not stored anywhere.

**Comment by tomhughes** [comment]
As @mmd-osm says there is no record of when a token was last used so we can't display that.

What do you think showing the issue time would help with? I wouldn't use the OAuth 1 tab as a good example of anything to be honest as it's pretty horrible UI and I think was probably mostly just the upstream example code.

**Comment by mnalis** [comment]
> As long as our tokens are not expiring, that information would always reflect the very first time a token has been requested. With OAuth1.0a you might see multiple entries for an app, in case they're not properly persisting the token locally, and need to request a new token.

I understand that (and have seen it in practice, with several pages worth of old Oauth1 that I've cleaned up recently, while Oauth2 remains clean).

However I assume that when I revoke an Oauth2 app, it would disappear (from the list and from the existence) along with its token, and if I decide to grant access to that app again in the future, then it would generate new (different) token, and it would have a new timestamp too, right?

If that assumption is correct, then I would find that timestamp valuable (e.g. if device with stored tokens was found to be compromised at some point it time I'd like to know what tokens were active, _or_ one might just want to expire their tokens manually after some time as a good security hygiene [as auto expiration is not supported], _or_ it might be useful just from readonly/historical/time-orienteering way e.g. _"I started using this app just after doing X, so X happened around there"_, etc.)

>> timestamp when that authentication token was last used

> That's not possible. Validating tokens is a read only database operation, i.e. a last used timestamp is not stored anywhere.

Ah, that's too bad. It would've been quite useful though, to spot unauthorized accesses and other things. But what can one do...

Can we have just the first (i.e. token creation) timestamp then?

**Comment by mmd-osm** [comment]
>  I assume that when I revoke an Oauth2 app, it would disappear (from the list and from the existence) along with its token, and if I decide to grant access to that app again in the future, then it would generate new (different) token, and it would have a new timestamp too

Yes, it would disappear from the list. However, the old token is still stored on the database with a revoked_at timestamp set. This way, the API could tell you that the token has been revoked.

Next time you request a token, you get a new (different) one  with a new created_at timestamp.
