### ISSUE TITLE
Puntuaction and orthorgraphy in the website

### ISSUE THREAD

**Issue by angoca** [openstreetmap/openstreetmap-website#4519]
### Problem

The OSM website contains some punctuation and orthography errors. I recommend reviewing all strings to validate this. Similarly, translators validate every single entry among them.

Errors like:

* Starting a sentence in lowercase.
* Sentence not finished with a period.
* No colon to present a list.
* Sentences in bullets finishing without a period.

One example is the registry process.

Disclaimer: English is not my mother language, but I have reviewed many translations into Spanish, and I see many issues in the source sentence.

**Comment by mmd-osm** [comment]
Maybe it would help if you could take a screenshot, mark all issues in red, and upload it here?

**Comment by angoca** [comment]
These are some examples from the sign-up process.

<img width="355" alt="Screen Shot 2024-02-19 at 10 04 21 AM" src="https://github.com/openstreetmap/openstreetmap-website/assets/294317/0f4ccb21-afd7-40a7-a1b5-07bda3755d7f">
<img width="492" alt="Screen Shot 2024-02-19 at 10 04 57 AM" src="https://github.com/openstreetmap/openstreetmap-website/assets/294317/c1849f9c-a87e-4e11-994b-e862b629da52">
<img width="495" alt="Screen Shot 2024-02-19 at 10 07 18 AM" src="https://github.com/openstreetmap/openstreetmap-website/assets/294317/2a522ea3-8d16-4458-b6d1-620e63582e3b">
<img width="243" alt="Screen Shot 2024-02-19 at 10 07 57 AM" src="https://github.com/openstreetmap/openstreetmap-website/assets/294317/6e600d77-48b7-48d3-ba0e-0664780b8fed">
<img width="203" alt="Screen Shot 2024-02-19 at 10 08 03 AM" src="https://github.com/openstreetmap/openstreetmap-website/assets/294317/b676f365-8267-4e40-a976-0f3032c76e96">
<img width="972" alt="Screen Shot 2024-02-19 at 10 09 12 AM" src="https://github.com/openstreetmap/openstreetmap-website/assets/294317/bd07e5fc-faef-461f-83c4-b8e3aeec8d83">

**Comment by tomhughes** [comment]
Those are design choices, not errors (for the most part at least).

Certainly a ticket as vague as this as not actionable - if there are specific things you want to challenge then raise them or propose changes and we can discuss them but nobody is going to review every string according to some set of rules of your invention.

**Comment by tomhughes** [comment]
To give a bit more detail for at least some of the things you pointed out:

* Using title case for input field labels is a design choice
* Not having a full stop after checkbox field labels is a design choice and the same goes for most of the other missing full stops I think
* The error messages come from rails and I believe the lack of an initial capital there is a design choice on their part though I happen to agree it's a bit weird
