### ISSUE TITLE
Missing en translation: community.uk-london-mastodon.name

### ISSUE THREAD

**Issue by RedAuburn** [openstreetmap/openstreetmap-website#4520]
### How to reproduce the issue?

Make an edit on osm.org in London
see the recommended community suggestions

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/openstreetmap-website/assets/26939824/f68b67ec-b2ad-4637-bc47-0baa87c1ed91)

**Comment by mmd-osm** [comment]
I'm a bit undecided if this belongs to https://github.com/openstreetmap/iD or https://github.com/osmlab/osm-community-index, but for sure the osm website repo isn't the right place.

**Comment by SomeoneElseOSM** [comment]
If it was me I'd ask first at https://github.com/osmlab/osm-community-index .  The actual file https://github.com/osmlab/osm-community-index/blob/main/resources/europe/united_kingdom/uk-london-mastodon.json doesn't differ in language codes from the others in the UK area, so I suspect you'll need to explain what browser you're using and how it's set up for languages too.

**Comment by gravitystorm** [comment]
See https://github.com/openstreetmap/iD/issues/10109
