### ISSUE TITLE
Add OAuth 1.0a deprecation warning to authorize.erb.html 

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#4526]
Follow up for https://github.com/openstreetmap/operations/issues/867#issuecomment-1925203709

Please check the link for some sample code and screenshots, as well as a bit of discussion what should be shown in the text box.

**Comment by tomhughes** [comment]
The problem with this that it would hard code openstreetmap.org plans for all users of the site - the ability to turn OAuth 1 on and off is an option. So really we'd have to hide it behind a "deprecate oauth 1 after" setting.

Frankly it all seems like far more work than it's worth as I explained on the other ticket - this is putting the warning in the wrong place anyway.
