### ISSUE TITLE
London Mastodon missing English translation

### ISSUE THREAD

**Issue by dankarran** [openstreetmap/openstreetmap-website#4531]
### URL

https://www.openstreetmap.org/edit

### How to reproduce the issue?

1. edit something in London
2. hit save
3. see missing translation

### Screenshot(s) or anything else?

"[Missing en translation: community.uk-london-mastodon.name](https://en.osm.town/@OSMLondon)
Missing en translation: community.uk-london-mastodon.description"

<img width="359" alt="Screenshot 2024-02-22 at 20 18 09" src="https://github.com/openstreetmap/openstreetmap-website/assets/207287/c0713beb-28d7-43f7-a105-785cd6912519">

**Comment by tomhughes** [comment]
Duplicate of #4520.

**Comment by dankarran** [comment]
Ah sorry, I did a quick search of issues, but it was filtered to open issues so that didn't show up.
