### ISSUE TITLE
Whether to allow users to use easily confused characters such as "Zero-width Space" in their usernames.

### ISSUE THREAD

**Issue by LaoshuBaby** [openstreetmap/openstreetmap-website#4538]
### Problem

Recently encountered a strange username, the UID of this user is 20978700.

https://www.openstreetmap.org/user/%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B

This was first reported in [OSMTW Telegram group](https://t.me/OSMTaiwan/12882) and [OpenStreetMap.org Telegram group](https://t.me/OpenStreetMapOrg/115740) by @iigmir.

### Description

This is using Unicode's ["Zero-width Space"](https://en.wikipedia.org/wiki/Zero-width_space) ([U+200B](https://symbl.cc/en/200B/)) for 15 times.

I am concerned that this may be used to impersonate other users, and it will be more difficult to distinguish than the confusion caused by the letter "p (U+0070)" in English with "р (U+0440)" Russian. Therefore, I suggest that OWG or other technical teams responsible consider whether this Unicode character should be prohibited from being used in usernames.

For example, I can register an account using 14 or 16 zero-width spaces, and they will appear identical to this user. Alternatively, I could register as "快_乐_的_老_鼠_宝_宝" (with each "_" representing a zero-width space).

### Screenshots

!["missing" username](https://github.com/openstreetmap/openstreetmap-website/assets/42690037/7c0a48d3-8289-4e34-bafc-16e9ce6707cc)

**Comment by tomhughes** [comment]
The problem is that you can't just ban zero width codepoints as some scripts may need them - probably not U+200B but I believe U+200D ZERO WIDTH JOINER is sometimes needed?

**Comment by tomhughes** [comment]
Much the same goes for U+200C (https://en.wikipedia.org/wiki/Zero-width_non-joiner) as well.

**Comment by tomhughes** [comment]
What we could maybe do is to change the current requirement that the be at least 3 bytes long to a requirement that it have a unicode display width of 3 characters - there is a [gem](https://rubygems.org/gems/unicode-display_width) for getting that width.

That would at least prevent names made up entirely of invisible characters.
