### ISSUE TITLE
Give thanks

### ISSUE THREAD

**Issue by OpenGreenStreet** [openstreetmap/openstreetmap-website#4542]
### Problem

If I want to thank someone, I have to write them an e-mail.

### Description

I would like to see a function for saying thank you, like the one on WIkipedia.

In my view, such a function could help to create a friendly atmosphere.

### Screenshots

https://commons.wikimedia.org/wiki/File:20240225xl_171048-WP_Give_thanks.jpg

**Comment by tomhughes** [comment]
What exactly do you want this function to do?

**Comment by OpenGreenStreet** [comment]
I would like to thank contributors, for example, for following up on a tip I left.

**Comment by mmd-osm** [comment]
Isn't that a duplicate of #875?

**Comment by OpenGreenStreet** [comment]
Yes, it is

**Comment by tomhughes** [comment]
I'll close this as a duplicate then.
