### ISSUE TITLE
Misoriented altitude labels on contour lines

### ISSUE THREAD

**Issue by maze88** [openstreetmap/openstreetmap-website#4556]
### URL

https://www.openstreetmap.org/#map=18/29.78000/34.96927&layers=P

### How to reproduce the issue?

With any layer that shows contour lines active, some of the lines' altitude labels are misoriented. This issue can cause confusion, since it deviates from the convention of topographical map notation ([source](https://getoutside.ordnancesurvey.co.uk/guides/advanced-contours-and-relief/)).

## Current behavior
The current logic appears to be "display the contours' labels perpendicular to their line, in the orientation that is most readable on the viewer's screen".

## Expected bahavior
All the number labels on countours should be aligned with the top of the number uphill.

### Screenshot(s) or anything else?
In the following screenshot (of an obvious mountain) I have marked in _green_ and in _red_ contours that are and are not (respecively) oriented correctly - relative to the mountain peak.

<img src="https://github.com/openstreetmap/openstreetmap-website/assets/16841581/ae414879-a054-4bba-b694-41dab67f204d" width="720" />

**Comment by tomhughes** [comment]
That's something you would have to report to the author of the layer(s) in question - we do not deal with map renderings here.

The menu you got when reporting this bug would have prompted you to report issues with the default style to the correct location but that doesn't have contours - for other layers see the attribution in the bottom right for a link to the layer's upstream site to report things.

**Comment by maze88** [comment]
> That's something you would have to report to the author of the layer(s) in question - we do not deal with map renderings here.
> 
> The menu you got when reporting this bug would have prompted you to report issues with the default style to the correct location but that doesn't have contours - for other layers see the attribution in the bottom right for a link to the layer's upstream site to report things.

Thanks for the tip, I have filed an issue for [_Tracetrack_](https://www.tracestrack.com/)'s layer: https://github.com/tracestrack/tracestrack-maps/issues/24
I have also sent an E-mail to [_Thunderforest_'s support](https://www.thunderforest.com/contact/).
