### ISSUE TITLE
Changeset comment text is lost when switching entity pages

### ISSUE THREAD

**Issue by dreua** [openstreetmap/openstreetmap-website#4561]
### URL

https://www.openstreetmap.org/changeset/148222445?way_page=1

### How to reproduce the issue?

1. You need a changeset with multiple pages of changed enitties
2. Write some text in the comment box
3. Click on one of the numbers in order to see more of the changed entities
4. Your comment is gone forever

### Screenshot(s) or anything else?

This is *very* bad UX. I am very grateful to everyone who built openstreetmap.org as well as iD but I'll be even more grateful when this bug is fixed and I won't loose a comment ever again.

**Comment by HolgerJeromin** [comment]
Solution: Add conditionally a `beforeunload` handler. But beware of this:

> Important: the beforeunload event should only be used to alert the user of unsaved changes. Once those changes are saved, the event should be removed. It should never be added unconditionally to the page, as doing so can hurt performance in some cases. 

https://developer.chrome.com/docs/web-platform/page-lifecycle-api#the_beforeunload_event

**Comment by dreua** [comment]
This was Firefox on Linux btw, haven't tried other browsers.

**Comment by dreua** [comment]
Ideally I'd say there isn't a reload at all, just load the data via JS and leave the text field alone? But a warning would be definitely better than nothing

**Comment by danieldegroot2** [comment]
Related #2088(, #4028, #3928, #3303, #933, #1089(, #647, #4039), #2973, #1212, #1333 (not reproduced));

_[How you can help with reviewing pull requests](#3815)_

**Comment by AntonKhorev** [comment]
How is https://github.com/openstreetmap/openstreetmap-website/issues/933 related to this? Unless you think that anything about the sidebar is related.

**Comment by danieldegroot2** [comment]
@AntonKhorev Reduced to relevant issues only.
