### ISSUE TITLE
Are /api/0.6/notes/addPOIexec, closePOIexec etc api entry point still necessary?

### ISSUE THREAD

**Issue by AntonKhorev** [openstreetmap/openstreetmap-website#4588]
### Problem

There's a number of api entry points for notes
https://github.com/openstreetmap/openstreetmap-website/blob/e9666aa673e9c69fd9391765ac3390853eeca344/config/routes.rb#L102-L106
that are duplicates of documented entry points.
They existed since openstreetbugs times
https://github.com/openstreetmap/openstreetmap-website/commit/e3b8b8933044104bb515d34c3d36851caba78ac7#diff-959bc9abc46a55332bb64d5155a79323afa75a50ec1a2137ddd22d926f62c6c5

Are they still in use now? Can they be removed?

**Comment by tomhughes** [comment]
They were added for compatibility with old clients but I have no idea if anything still uses them - checking will need a full list so I can check the logs so here it is:

* POST to api/0.6/notes/addPOIexec
* POST to api/0.6/notes/closePOIexec
* POST to api/0.6/notes/editPOIexec
* GET from api/0.6/notes/getGPX
* GET from api/0.6/notes/getRSSfeed

**Comment by tomhughes** [comment]
None of those appears to have been used in the last month that we have logs for.

**Comment by gravitystorm** [comment]
Closed by #4610
