### ISSUE TITLE
Order of comments in changeset comments feeds

### ISSUE THREAD

**Issue by AntonKhorev** [openstreetmap/openstreetmap-website#4613]
### Problem

Does it make sense for comments in a feed to go in ascending order, oldest first?

Comment feeds for all comments are sorted in descending order:
https://master.apis.dev.openstreetmap.org/history/comments/feed

But feeds for individual changesets are sorted in ascending order:
https://master.apis.dev.openstreetmap.org/changeset/307182/comments/feed

If you add a limit, and there's more comments than the limit, you'll never get new comments:
https://master.apis.dev.openstreetmap.org/changeset/307182/comments/feed?limit=1

**Comment by milan-cvetkovic** [comment]
We probably want descending order, with newest comments being fist on the list.

I think it would also be useful to order them by `id` instead of `created_at`, since in theory ordering by timestamp and id does not have to match.
