### ISSUE TITLE
E-mail needs to be entered twice on the registration page

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/openstreetmap-website#464]
https://www.openstreetmap.org/user/new
What the "Confirm e-mail" field is for? I can understand the reason for password confirmation (it is hidden), but e-mail is right there.

I propose to remove this redundancy.

**Comment by gravitystorm** [comment]
I agree with @Zverik that it would be good to remove the duplicate email field, but of course not if that just makes more work for the sysadmins.

In my experience of running another site, people sign up with the wrong address all the time. But they soon realise it and just sign up again with the correct address, and life goes on.

I would suggest:
* Figure out some way to avoid "taken" usernames with typo emails. That's the most compelling reason why a user would ask for sysadmin intervention.
* Show the email address on http://www.openstreetmap.org/user/Foobar/confirm - that will reduce the time taken to spot the mistake if a user is waiting for a confirmation that's not going to arrive.
* Expire (delete) unconfirmed accounts after some period of time? That would stop the database from filling up with cruft.
