### ISSUE TITLE
Make new message notification red colored

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#4657]
### Problem

If someone sends you a message, there will be a number next to your photograph, on the upper right corner of the screen.

Problem is, that number needs to have a red or otherwise more noticeable background, for you to be more likely to notice it.

Yes, even though there is an email notification also sent.

Red is what most sites choose these days.

**Comment by Dimitar5555** [comment]
See #4070

**Comment by mmd-osm** [comment]
Let's close this one, since it's a duplicate really.
