### ISSUE TITLE
No space between redaction buttons

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/openstreetmap-website#466]
The number of users hit by this bug is pretty small, but non-zero

![redaction](https://f.cloud.github.com/assets/1190866/1037700/d0a87938-0f54-11e3-9b25-ac543f1cda4c.png)
There is no space between the buttons, making it hard to tell them apart.

Compare with a set of reply message buttons which have a bit of whitespace
![reply](https://f.cloud.github.com/assets/1190866/1037702/dd8cd86a-0f54-11e3-8ec6-0e147210d571.png)

**Comment by gravitystorm** [comment]
I get a space - I suspect this has been fixed since reporting. Please reopen if it's still a problem.

![screenshot from 2017-08-30 12-38-55](https://user-images.githubusercontent.com/360803/29870597-5699fbea-8d80-11e7-9bdd-69d03eede2d8.png)

**Comment by pnorman** [comment]
There is 1px of space, but other buttons now have 2px. There's also some differences in the corners.
