### ISSUE TITLE
Long links are overriding the tag name

### ISSUE THREAD

**Issue by HarelM** [openstreetmap/openstreetmap-website#4709]
### URL

https://www.openstreetmap.org/node/2570217182

### How to reproduce the issue?

Open the page and look at the tags, this is what I see (Hebrew UI):
Images links are overriding the tags name:
![image](https://github.com/openstreetmap/openstreetmap-website/assets/3269297/bd345a2b-2585-4ebb-8f2d-4d565ffa02bf)

### Screenshot(s) or anything else?

I'm using chrome, and I'm guessing this is a simple css fix of wordbreak somewhere.

**Comment by mmd-osm** [comment]
I can see the same issue in Chrome. On Firefox, rendering looks ok here:

![image](https://github.com/openstreetmap/openstreetmap-website/assets/5842757/e01f8aa0-ed19-421c-919a-58f8ad65e2bd)
