### ISSUE TITLE
illegible "click here to edit" message (for newly registered users)

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/openstreetmap-website#471]
The "click here to edit" message for newly registered users is too narrow is overlapped by the regular edit tooltip.

![osm-intro-message](https://f.cloud.github.com/assets/1927298/1075909/0d50f7ce-14d8-11e3-9a7f-df7976fa867b.png)

Seen on Opera 12.1

**Comment by mmd-osm** [comment]
Issue is outdated and no longer relevant.

**Comment by tyrasd** [comment]
true :smile:
