### ISSUE TITLE
Setting an editor-preference 

### ISSUE THREAD

**Issue by pietervdvn** [openstreetmap/openstreetmap-website#4719]
### How to reproduce the issue?

When setting a preference with a non-ascii character (e.g. `ü`), the API responds with an error 500

curl 'https://www.openstreetmap.org/api/0.6/user/preferences/example-perference' -X PUT  --data-raw $'Den T\xfcrk'

**Comment by tomhughes** [comment]
Well 0xfc is not a valid UTF8 encoding of ü so what encoding exactly are you trying to use because the API will want UTF8.

**Comment by tomhughes** [comment]
It looks like that is Latin 1 or something similar like Latin 15 but there's no way for the API to know so it has to just try and decode it as UTF8 and error when it fails.
