### ISSUE TITLE
weird characters in font in canada map

### ISSUE THREAD

**Issue by miqueet** [openstreetmap/openstreetmap-website#4749]
### URL

https://www.openstreetmap.org/#map=8/50.172/-76.009

### How to reproduce the issue?

![image](https://github.com/openstreetmap/openstreetmap-website/assets/5346303/31524b24-12c1-4028-80d8-730bd9cf4601)

is there a way to have it only show a-z characters? It shows this on the openstreetmaps map and my own osm server. Is there anything in the fonts that can be done to eliminate this?

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/openstreetmap-website/assets/5346303/31524b24-12c1-4028-80d8-730bd9cf4601)

**Comment by tomhughes** [comment]
I assume by "weird characters" you mean "the name in the language of the local indigenous population" right?

In any case map styling issues are not a matter we can deal with here - the correct place to report them, as the menu you were shown when report this said, is at [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto/issues).

**Comment by miqueet** [comment]
Thanks for directly me to the proper place. I was unaware this was a native
language. My apologies.

-Mike Wheat
