### ISSUE TITLE
"Mark as unread" doesn't do anything inside messages

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/openstreetmap-website#4750]
### URL

https://www.openstreetmap.org/messages/{message_id}

### How to reproduce the issue?

1. Open a message
2. (Decide that you will reply to it later)
3. Press "Mark as unread"
4. "Message has been marked as unread"
5. Go to the inbox
6. Notice that the message you just marked as unread is actually read

### Screenshot(s) or anything else?

Maybe at step 3 the user should be sent back to the inbox, so that he doesn't "read" the message again?

**Comment by tomhughes** [comment]
It does actually mark the message as unread but of course it then reloads the message view which immediately marks it as read again...
