### ISSUE TITLE
mirrored text in login in hebrew

### ISSUE THREAD

**Issue by amiad** [openstreetmap/openstreetmap-website#4780]
### URL

https://www.openstreetmap.org/login

### How to reproduce the issue?

1. use hebrew (maybe other rtl language)
2. try to login
3. see the tabs for login are mirrored. The correct text is כניסה, הרשמה. 

### Screenshot(s) or anything else?

![IMG_20240512_145611_961](https://github.com/openstreetmap/openstreetmap-website/assets/402108/5ab5d969-0068-4343-a191-87c335a33bb3)

**Comment by tomhughes** [comment]
Thanks for the report - the fix should roll out shortly.

**Comment by AntonKhorev** [comment]
That's what you get for putting tabs inside "header-illustration".
