### ISSUE TITLE
Improve Github issues by modelling issues after Microsoft Powertoys repo

### ISSUE THREAD

**Issue by kleenkanteen** [openstreetmap/openstreetmap-website#4788]
### Problem

There are 541 open issues. Some even from 10+ years ago.

### Description

I appreciate the organization of the powertoys repo: [https://github.com/microsoft/PowerToys/issues?q=is%3Aopen+is%3Aissue](https://github.com/microsoft/PowerToys/issues?q=is%3Aopen+is%3Aissue)

Specifically these 3 things: 
1. Every new issue gets tagged with the "Need-Triage" tag. 
2. Allowing people to make issues with the label "Issue-Bug label". This initial labelling helps know what an issue is about quickly.
3. They have a similarity score done on similar issues by a github bot that reduces the number of duplicate issues by letting people know of the most similar existing issues. Example of it working today by making the author close their duplicate issue: [https://github.com/microsoft/PowerToys/issues/32850](https://github.com/microsoft/PowerToys/issues/32850)

The fisrt 2 are probably not much effort on the maintainers of this repo. 

The last one is a bit involved, but I am willing to implement it. I do not know where the powertoys bot is from, but I can find the source, and if it doesn't exist, I can make a basic, open source version of it. I have a decent amount of knowledge of LLM's.

**Comment by gravitystorm** [comment]
> There are 541 open issues. 
> [...]
> The fisrt 2 are probably not much effort on the maintainers of this repo.

So anything to do with 500+ issues **is** a lot of effort for the maintainers. And I think our time is, right now, better spent on dealing with the 130+ open pull requests. If, for example, I stopped reviewing pull requests for the next 3 months (~10 days volunteer time, 50+ issues per day?) and just tagged and categorised issues, then I would be three months down the line with no PR reviews done but with more tags on issues. Which I don't think will make it faster to do the PRs in future, so it's hard to see how I would make up for lost time.

Tagging issues is useful, yes, but it's not a priority for someone who could be doing PR reviews, in my opinion.

We have other (non-maintainer) contributors who have rights to tag issues, we have the "bug" label (and several others), and we frequently have contributors who spot duplicate issues and these get resolved. If you want to join that team, you would be very welcome.

**Comment by kleenkanteen** [comment]
Looking at the issues, just the last 20 are after 2024 months so it's not that many it seems. Being new to the repo, I do like organized issues so I can scan easier for which ones are problems. Not that impactful though it seems in this situation, as you said.

I did look up the "good first issue" label and there was just one result. Quick link to the search results here: [https://github.com/openstreetmap/openstreetmap-website/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22](https://github.com/openstreetmap/openstreetmap-website/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

The issue was not actually a good first issue according to someone in the comments. I'd be interested to take a look at the codebase if I could get a pointer to a good first issue. Hard to know where to start. 

I'm interested in joining that team of contributors. Can look around and spend a few hours a week.

**Comment by kleenkanteen** [comment]
@gravitystorm Let me know if you have a good first issue you could have me take a look at. And if I could help out with tagging issues.
