### ISSUE TITLE
Avoid using Basic Authorization in tests

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#4801]
We currently use `basic_authorization_header` extensively in our tests (around 200 times). It's typically used to check that a controller behaves correctly (i.e. differently than for requests that have no authorization).

Since we're dropping basic_auth support in the API (by changing a config to disable it), it makes sense for us to remove all the code too, at some point soon after. Before that happens, we need to refactor these tests.

The most obvious (to me) option is to move to using the `bearer_authorization_header` approach, with OAuth2 tokens, as already used in some tests. Unless anyone has a different idea? 

It might also be worth considering we should have a helper that sorts out creating the token and scopes automatically, since in these cases we're not interested in whether the token is correctly set up (that's tested elsewhere) but rather these tests are focussed on what happens when a particular user is doing something.

**Comment by mmd-osm** [comment]
I've been playing around with https://github.com/zerebubuth/openstreetmap-cgimap/pull/392#issuecomment-2068164657 to automatically create users + OAuth tokens, which could later be used to send a proper Bearer Authorization headers. In fact that's something I'd like to see as part of a rake task to easily set up new demo users and register some default apps along with corresponding tokens.

By the way, in CGImap we've also replaced all Basic auth headers by Bearer tokens a while ago.
