### ISSUE TITLE
add wiki:symbol link to the data browser

### ISSUE THREAD

**Issue by werner2101** [openstreetmap/openstreetmap-website#481]
Hi developers,

it would be cool if wiki:symbol tags would have a link to the Files in the wiki:
The wiki:symbol=Symbol_Jakobsweg.svg refers the file http://wiki.openstreetmap.org/wiki/File:Symbol_Jakobsweg.svg. Just similar as the wikipedia tag links to the wikipedia page.

wiki:symbol tag description and usage:
http://wiki.openstreetmap.org/wiki/Key:wiki:symbol

example: Relation with a wiki:symbol tag:
http://www.openstreetmap.org/browse/relation/2264545

A more advanced idea:
Get the image URL from the media-Wiki-API and show a small Image in the data browser. Additionally add a link to the FILE: in the wiki.
 (API URL: http://wiki.openstreetmap.org/w/api.php?action=query&prop=imageinfo&titles=FILE:Symbol_Jakobsweg.svg&iiprop=url)

Regards
Werner

**Comment by mmd-osm** [comment]
It seems a link for wiki:symbol is already available today.

**Comment by werner2101** [comment]
Great, that I can close the request.

PS: I was wondering what ticket this was, after more than 7 years.

**Comment by pyrog** [comment]
This tag isn't handle by OSM website (except if it contain an URL).
It should be handled like [wikimedia_commons](https://wiki.openstreetmap.org/wiki/Key:wikimedia_commons) tag.
- relation [1197928](https://www.openstreetmap.org/relation/1197928).

OSM website handle it:
- way [225383058](https://www.openstreetmap.org/way/225383058) 😀
