### ISSUE TITLE
Add "Like" button to diary entries

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#4819]
### Problem

There we are reading https://www.openstreetmap.org/diary
and we stumble upon a diary entry we really like... but
there's no Like button to press! (it feels *like* year 1998 or something.)

### Description

Yes, we found a "Report this entry" button, but no Like button.

Yes, there is a comment box, but if that is how users are to express their pent up likes, you will end up with
- Like!
- like
- Like it.
- Cool
- Groovy

etc. one word comments that would be more tidy if just expressed by the Like button.

Comments too. All there is now is a "Report this comment" button. They also need Like buttons. Especially because one cannot "comment just on a comment."

Sure, the Like buttons could be fancy up/down counters, or just "good news only" positive counters. They could even have several emotion choices.

**Comment by mmd-osm** [comment]
I think we've seen this before:  #2551

**Comment by gravitystorm** [comment]
Closed as duplicate.
