### ISSUE TITLE
Wikipedia links with question mark

### ISSUE THREAD

**Issue by alnzrv** [openstreetmap/openstreetmap-website#4851]
### URL

https://www.openstreetmap.org/node/945504911

### How to reproduce the issue?

1. Go to this page in the browser:
https://www.openstreetmap.org/node/945504911

2. Click on Wikipedia link: en:Are Years What? (for Marianne Moore)
3. Get the error.

Correct link:
https://en.wikipedia.org/wiki/en:Are%20Years%20What%3F%20(for%20Marianne%20Moore)?uselang=en

Current link:
https://en.wikipedia.org/wiki/en:Are%20Years%20What?%20(for%20Marianne%20Moore)?uselang=en

The same bug was fixed in the iD editor earlier:
https://github.com/openstreetmap/iD/issues/10065

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/openstreetmap-website/assets/7187657/96069cb1-3231-431a-9fc8-2ccdd327c6b5)
![image](https://github.com/openstreetmap/openstreetmap-website/assets/7187657/4891a34b-204b-44b9-aa51-bb5fcb79e38a)

**Comment by GEORGIAN86** [comment]
can you assign this issue to me?

**Comment by matkoniecz** [comment]
@GEORGIAN86 there are already two open PRs, why do you think new one is needed?
