### ISSUE TITLE
Address of building:part is not shown

### ISSUE THREAD

**Issue by alnzrv** [openstreetmap/openstreetmap-website#4852]
### URL

https://www.openstreetmap.org/#map=18/44.81439/20.42977

### How to reproduce the issue?

1. Go to the URL:
https://www.openstreetmap.org/#map=18/44.81439/20.42977

2. Verify that addresses on this building are not shown on the map:
https://www.openstreetmap.org/way/1257524525

This building contains multiple building:part with the addresses, for example:
https://www.openstreetmap.org/way/516512490
https://www.openstreetmap.org/way/516512489

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/openstreetmap-website/assets/7187657/dbdedfe1-ef0d-4721-a6f8-c1873be721be)
![image](https://github.com/openstreetmap/openstreetmap-website/assets/7187657/fab236c0-941e-4051-b8ae-79a24505c93a)

**Comment by tomhughes** [comment]
That's a screenshot of iD not openstreetmap-website. Please report it to iD as per the instructions in the bug reporting form you went through to ge here.

**Comment by tomhughes** [comment]
Or are you talking about what's rendered on the map? That's still not an issue for here though, it's an issue for openstreetmap-carto which you can find in the same form.
