### ISSUE TITLE
Netherlands contributor URL on Copyright page no longer valid

### ISSUE THREAD

**Issue by talllguy** [openstreetmap/openstreetmap-website#4865]
### URL

https://www.openstreetmap.org/copyright

### How to reproduce the issue?

1. Head to the [copyright page](https://www.openstreetmap.org/copyright)
2. Look under _Our Contributors_
3. Notice the Netherlands (8th bullet down) has a source of `Contains © AND data, 2007 ([www.and.com](https://www.and.com/))`
4. Head to and.com and notice the domain is not in use

### Screenshot(s) or anything else?

![image](https://github.com/openstreetmap/openstreetmap-website/assets/1827881/bc9e41db-258b-45f2-8936-5fe7a17518fd)

**Comment by HolgerJeromin** [comment]
Thanks for the report.

This is a duplicate of #3998

**Comment by talllguy** [comment]
Thanks, sorry, I was expecting the reporting template to find a duplicate. I'll close this.
