### ISSUE TITLE
Note resolved email notifications are failing to return address

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/openstreetmap-website#4874]
### How to reproduce the issue?

Recently, numerous email notifications 'note was resolved/commented on by [user] near [place]' return 'near [some coordinates]' instead of 'near [a comprehensive address]' (i.e. 52,544, -7,386 instead of "..., Callan Urban, The Municipal District of Callan — Thomastown, County Kilkenny, Leinster, Ierland";

1. User resolves/comments on note
2. Author receives email, but frequently with coordinates instead of address.

https://www.openstreetmap.org/note/3312835 results in email with address
https://www.openstreetmap.org/note/3367617 results in email with coordinates
https://www.openstreetmap.org/note/3746649 however results in email with address

(occurs as early as May 19, 2024.)

**Comment by tomhughes** [comment]
That will presumably just be down to whether nominatim is able to return an address for those coordinates.

**Comment by tomhughes** [comment]
Indeed, as you can see with https://nominatim.openstreetmap.org/ui/reverse.html?lat=6.8908471&lon=52.2180723+&zoom=18 it is not able to return an address for the coordinates of the second note so we won't be able to add one.

**Comment by danieldegroot2** [comment]
URL is incorrect, try reversing coordinates so they are not over the ocean.
https://nominatim.openstreetmap.org/ui/reverse.html?lat=52.2180723+&lon=6.8908471&zoom=18

**Comment by tomhughes** [comment]
I definitely had the coordinates that way round so I'm not sure why the URl was reversed. Most likely nominatim just timed out for some reason anyway - we only allow a fairly short timeout I think to stop thinks being delayed if there is a problem.

**Comment by lonvia** [comment]
That's an operational issue: https://github.com/openstreetmap/operations/issues/921
