### ISSUE TITLE
There are additional, but false Streets shown in different zoomlevels (16 / 17 )

### ISSUE THREAD

**Issue by Huehnertod** [openstreetmap/openstreetmap-website#4893]
### URL

https://www.openstreetmap.org/#map=17/50.97542/7.39009

### How to reproduce the issue?

The Streets are shown in the view mode, but in the edit mode the data seems to be ok. 
Additional Example2: https://www.openstreetmap.org/#map=16/50.9685/7.3719 

Some street names are russian some english (Windsor Garth, Earswick Chase, Petersway, Chapter House Street etc.)
![Screenshot 2024-06-13 160137](https://github.com/openstreetmap/openstreetmap-website/assets/172611535/bde27f15-188c-435a-b922-ab7894499987)

Best Regards

**Comment by Firefishy** [comment]
We are aware of the issue. Vandalism has been reverted in the data and the map rendering is updating. A forced refresh in browser often fixes the issue.
