### ISSUE TITLE
Phantom street appears at particular zoom levels

### ISSUE THREAD

**Issue by angushewlett** [openstreetmap/openstreetmap-website#4903]
### URL

https://www.openstreetmap.org/search?query=violet%20lane%2C%20croydon#map=16/51.3660/-0.1107

### How to reproduce the issue?

1. Chrome 125.xxx, Apple Silicon, macOS 13.6.2
2. Open the map at the above URL
3. Note the phantom street "Dalguise Grove" appears running East/West immediately north of Duppas Hill Road
4. Zoom in or out
5. Note that the phantom street "Dalguise Grove" no longer appears.

First screenshot shows phantom street.
Second screenshot does not.

There is no road "Dalguise Grove" in the area, so I'm not sure where the data is coming from, the only road with the same name - and a very different geometry - is 150 miles away in York.

### Screenshot(s) or anything else?

<img width="1694" alt="image" src="https://github.com/openstreetmap/openstreetmap-website/assets/6906539/b6a5dbe7-00e3-4d2e-9ddb-e47ecfe0f23b">
<img width="1694" alt="image" src="https://github.com/openstreetmap/openstreetmap-website/assets/6906539/867b3da4-9b5b-457b-a816-3377a4d3f282">

**Comment by gravitystorm** [comment]
This not the right place to report map errors.

Please see https://community.openstreetmap.org/t/have-you-spotted-vandalism-on-openstreetmap-org/114684 for more information.

**Comment by angushewlett** [comment]
My bad - I was unaware of the vandalism issue and so thought it was a query or render error rather than a map error: as it didn't appear at other zoom levels or in cleartext search by name.

Clearing the browser cache appears to have purged it. Thanks!
