### ISSUE TITLE
Add Bezier Curves

### ISSUE THREAD

**Issue by asmallpileofash** [openstreetmap/openstreetmap-website#4907]
### Problem

Because there is no tool for creating smooth curves, most places where curves are necessary to represent the feature, people use many, many nodes, creating worse performance, and higher storage costs. This could be solved by adding quadratic bezier curves, instead of using 7 points for a road curve, you can use 4 points in a quadratic bezier.

**Comment by HolgerJeromin** [comment]
This would be an addition to the osm data model. 
https://github.com/osmlab/osm-planning
is probably a better place to discuss.

**Comment by Dimitar5555** [comment]
There is a suggestion/plan (not sure how official it is) to include Bezier curves in API 0.7 (https://wiki.openstreetmap.org/wiki/API_v0.7#B%C3%A9zier_curves).

**Comment by tomhughes** [comment]
Yes this is a much larger thing then anything we as web site maintainers can do on our own and should be addressed initially in other ways.
