### ISSUE TITLE
Automate some code review comments

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#4912]
There's a few common code review comments that could be automated (or in the meantime, community members are welcome to jump in and help out the maintainers with these reviews!):

* Any changes to locale files, other than `en.yml`, should be flagged and the PR amended
* Any PRs that have a merge commit should be flagged and the PR amended

In both cases, the response is more-or-less the same content each time, usually with a link to the right place in our documentation. 

We could automate this, which would bring a few benefits, namely
* Faster feedback cycle. Contributors would get the message straight away, while they might still be working on their PR, and not several hours/days later.
* Less work for maintainers - we're overstretched already, so it's one less thing to take care of.
* More polished responses - sometimes we're a bit pressed for time, or forget the link to the documentation, or similar.
* More support for maintainers - like linters and tests, it could highlight things we might miss.

I've seen other projects using Danger for this, since it's able to access the state of the PR in git, i.e. it can reason about the changes, not just the end state (otherwise we'd use linters etc for that).

https://danger.systems/ruby/

Anyone fancy implementing these rules? Or any reasons not to?

**Comment by rkoeze** [comment]
This seems reasonable. One alternative could be to use a [Github PR template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) with a checklist of requirements. With that said I think there are benefits to automatically enforcing certain things.

(I also wonder if using a template to ensure consistent PR descriptions would make life easier for the maintainers. I’m happy to put together a draft PR if that would be helpful, but I don't want to steer this conversation off-topic!)

**Comment by nenad-vujicic** [comment]
> This seems reasonable. One alternative could be to use a [Github PR template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) with a checklist of requirements. With that said I think there are benefits to automatically enforcing certain things.

Or perhaps a combination of these two? Using templates for enforcing better (standardized) descriptions and e.g. Danger for automatized labeling of PRs?

**Comment by gravitystorm** [comment]
I've merged both these PRs, so this issue can be closed. 

If anyone has ideas for how to automate more aspects of reviewing pull requests, please open an issue! The more that we can do automatically, the quicker that contributors will get feedback, and the more likely they are to update their PR.
