### ISSUE TITLE
Mobile: Hidden close history tab button

### ISSUE THREAD

**Issue by CharliePlett** [openstreetmap/openstreetmap-website#4924]
### URL

https://openstreetmap.org

### How to reproduce the issue?

When you open the history tab on mobile then there is no way to close the tab again except by reloading or switching to horizontal.

### Screenshot(s) or anything else?

![Screenshot_2024-06-26-00-54-52-402_org mozilla firefox](https://github.com/openstreetmap/openstreetmap-website/assets/35817820/fe1a0b1e-c4a6-4419-aa7e-39ae224081f6)

**Comment by mmd-osm** [comment]
You can either click on the osm logo in the top left, or the [hamburger menu](https://en.wikipedia.org/wiki/Hamburger_button) on the top right.

**Comment by nenad-vujicic** [comment]
> You can either click on the osm logo in the top left, or the [hamburger button](https://en.wikipedia.org/wiki/Hamburger_button) on the top right.

Just to make it more clear. As a current workaround, you can either click on the osm logo in the top left (to return you to OSM home page), or the hamburger button on the top right (which will expose 'X' button for closing history).

Thanks,
Nenad.

**Comment by mmd-osm** [comment]
@CharliePlett : does this answer your question and we can clsoe the issue, or did you expect something else, maybe?

**Comment by CharliePlett** [comment]
I personally don't care, I just saw it as a problem so I reported it. I guess this is a similar issue to issue #4825.

**Comment by mmd-osm** [comment]
Well, you might have some expectation how it should look like, if the proposed approach works for you, something like that. If you don't care, then there's really not much we can do here to help you out :)  Yes, #4825 might be related.
