### ISSUE TITLE
Searches for latitudes or longitudes between 1 and -1 result in invalid E-notation numbers

### ISSUE THREAD

**Issue by zyphlar** [openstreetmap/openstreetmap-website#4950]
### URL

https://www.openstreetmap.org/search?query=0.0000123%2C0.0000456

### How to reproduce the issue?

Search for a coordinate within 1 degree of the equator or prime meridian, such as very near Greenwich or Ecuador. Note that the resulting coordinates are displayed in computery syntax like "1.23e-05" instead of "0.0000123". This may cause confusion or errors (for example if the values are copy-pasted into a program expecting plain decimal coordinates, or if average users are unfamiliar with E notation.)

This may in fact be an upstream issue with Nominatim, etc, in which case hopefully we can fix it there as well. This issue was discovered when a user attempted to import or access a bookmark with E notation coordinates inside of Organic Maps: it's unclear which software generated the offending geo: URI, but my understanding of the RFC and coordinate systems is that such a rendering should never be presented to end users and is generally unsupported in parsers. Since we often validate odd input on mobile against the OSM website and other OSM ecosystem tools, it makes sense to try and squash this bug wherever it's found.

Example queries:

https://www.openstreetmap.org/search?query=45.0%2C0.0000456

https://www.openstreetmap.org/search?query=0.0000123%2C-75.456

**Comment by mmd-osm** [comment]
This seems like an issue in Rails with the way "to_f" works: https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/geocoder_controller.rb#L222
