### ISSUE TITLE
Geocoded address missing from the OSM notes RSS feed

### ISSUE THREAD

**Issue by bkil** [openstreetmap/openstreetmap-website#4955]
### URL

https://www.openstreetmap.org/api/0.6/notes/feed

### How to reproduce the issue?

This feed included the the street, locality, city and country in the `<title>` geocoded from the coordinates of each issue. This textual information went missing a few days ago. Its data content had also been reduced since last year.

**Comment by tomhughes** [comment]
That information comes from an external service and is only included if we are able to get it in a reasonably short timeframe.

**Comment by tomhughes** [comment]
I'm pretty sure there is already an issue for this but I can't find it right now but basically that relies on nominatim so if the server we are talking to is overloaded for any reason we will time out and return a feed without it.

**Comment by bkil** [comment]
Thank you for the quick response. Maybe related to this?
https://github.com/openstreetmap/operations/issues/1069
https://github.com/osm-search/Nominatim/issues/3405

**Comment by lonvia** [comment]
You are thinking of #4874.

I'm not sure it is related. It has been quiet on stormfly for the last couple of days. There shouldn't have been any timeouts except if I've accidentally blocked the OSM servers.

**Comment by lonvia** [comment]
So I did. Fixed.

Any chance you can send custom user agents instead of the generic 'Ruby' and 'Faraday'? Would make it easier to catch these kind of mistakes.

**Comment by tomhughes** [comment]
I've opened #4957 to fix the user agents.
