### ISSUE TITLE
Missing American English localization

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/openstreetmap-website#4975]
As far as I can tell, config/locales/en.yml is _de facto_ written in Commonwealth English, with Britishisms such as “centre”, “colour”, “licence”, and “shop” generally prevailing over Americanisms such as “center”, “color”, “license”, and “store”. There’s also an en-GB.yml for even more classically British turns of phrase, but no en-US.yml for even basic quirks of American English. A user who knows American English will most likely configure their browser and account to prefer the en-US locale code, but they’ll see Commonwealth English instead.

For the most part, this is no problem: “colour” and “licence” merely look quirky, maybe slightly erroneous to someone unfamiliar with the dialect. But this codebase also maintains translations for a number of feature tags that would be much less intuitive to an American English speaker.

Not a single American knows what these are, even though “license” is spelled the American way:

https://github.com/openstreetmap/openstreetmap-website/blob/63f0b9257d62818d435ef6510340b9681efe547b/config/locales/en.yml#L1275

You’d have to be an OpenHistoricalMap contributor like me to know what these are:

https://github.com/openstreetmap/openstreetmap-website/blob/63f0b9257d62818d435ef6510340b9681efe547b/config/locales/en.yml#L749

99.9 out of 100 Americans would tell you this is scientific laboratory. iD calls it a “drugstore”, which is apparently closer to the intended use of this tag:

https://github.com/openstreetmap/openstreetmap-website/blob/63f0b9257d62818d435ef6510340b9681efe547b/config/locales/en.yml#L1297

For sure, Americans know what these are, but `amenity=toilets` isn’t supposed to refer to a lavatory fixture specifically, and it’s a bit impolite:

https://github.com/openstreetmap/openstreetmap-website/blob/63f0b9257d62818d435ef6510340b9681efe547b/config/locales/en.yml#L2387

Americans mostly use “shop” and “store” interchangeably, and so does this repository:

https://github.com/openstreetmap/openstreetmap-website/blob/63f0b9257d62818d435ef6510340b9681efe547b/config/locales/en.yml#L1301-L1307 https://github.com/openstreetmap/openstreetmap-website/blob/63f0b9257d62818d435ef6510340b9681efe547b/config/locales/en.yml#L1384-L1390

One way or another, we should provide more regionally appropriate terms to American English speakers, to reduce confusion about what these tags mean. I don’t have an opinion on whether we should split out a separate en-US.yml or have the Americanisms take over en.yml, since either way we’d be more likely to load the expected strings when the user says they prefer en-US in their account settings.

**Comment by tomhughes** [comment]
Localisation is managed through translatewiki and we don't have any control over what locales they provide to us,

**Comment by 1ec5** [comment]
OK, so en.yml should be in American English, not mostly British English?

**Comment by tomhughes** [comment]
I don't think we really have a clear answer to that... It probably should unless we're going to get TW to remap things in a different way but the problem is that the people doing the merges are mostly en-GB speakers who won't notice british spellings.

The en-GB translation is mostly annoying to be honest because it's full of strings which were copied even though they don't actually change which means I often wind up wondering why I'm not seeing a change and it's because I'm seeing the en-GB copy of the string.

**Comment by tomhughes** [comment]
Previous discussion in #3653 and #3671.

**Comment by 1ec5** [comment]
> I don't think we really have a clear answer to that... It probably should unless we're going to get TW to remap things in a different way but the problem is that the people doing the merges are mostly en-GB speakers who won't notice british spellings.

If this project is open to using en.yml for American English, I’d be happy to proofread it thoroughly and monitor changes to it going forward. I’ve been doing the same thing for years for id-tagging-schema, which has the same challenge. There’s also a #language channel in OSMUS Slack where developers can request proofreading. StreetComplete’s developers take advantage of this channel on a regular basis.

> The en-GB translation is mostly annoying to be honest because it's full of strings which were copied even though they don't actually change which means I often wind up wondering why I'm not seeing a change and it's because I'm seeing the en-GB copy of the string.

Could en-GB.yml be a sparse translation, just the strings that we need to override en.yml? On Translatewiki.net, some projects periodically bulk delete translations that are identical to the source. Then I think the site would fall back to en.yml automatically. If not, config/i18n-tasks.yml could probably backfill the missing translations from en.yml.

Incidentally, you might appreciate this mismatched en-GB string I just fixed in iD (not yet released):

American English | British English
----|----
<img src="https://github.com/openstreetmap/openstreetmap-website/assets/1231218/6d89cd30-8887-492b-96bc-e9d2daf511f2" width="379" alt="Building has unsquare corners: Buildings with unsquare corners can often be drawn more accurately."> | <img src="https://github.com/openstreetmap/openstreetmap-website/assets/1231218/44256a8e-25eb-4138-8751-51306efe7b41" width="379" alt="Building has unsquare corners: Its stability, quality, independence, and strength depend on donations from people like you.">

**Comment by gravitystorm** [comment]
> OK, so en.yml should be in American English, not mostly British English?

Yes, I think it should be. It's similar to the [discussion that we had with portuguese](https://github.com/openstreetmap/openstreetmap-website/issues/3670) where we had to decide if requests for "pt" should be answered with "pt-BR" or "pt-PT" and went with the CLDR recommendation of pt-BR. And I strongly suspect that the equivalent for "en" will be "en-US". Therefore:

|Language|Locales|Files|
|---|---|---|
|American English| en, en-US|en.yml|
|British English|en-GB|en-GB.yml|

So to make this work, all we have to do is to make sure the source translations in en.yml are "en-US" and everything will work as intended (apart from some Brits who might need to update their browsers preferred languages, if they haven't done so already).

> But this codebase also maintains translations for a number of feature tags that would be much less intuitive to an American English speaker.

It's worth noting that many of these feature translation strings are written by non-English speakers, often native German speakers, so it's hard for them to spot any Britishisms, particularly if the British term is more similar to either the tag (traditionally OSM uses en-GB for tag values) and/or if the term is more similar to those used in other European languages.

The other non-tag translation strings in the repo are, as @tomhughes says, more often written by en-GB speakers.

**Comment by tomhughes** [comment]
Also "unsquare" is not a word ;-)

**Comment by gravitystorm** [comment]
> The en-GB translation is mostly annoying to be honest because it's full of strings which were copied even though they don't actually change which means I often wind up wondering why I'm not seeing a change and it's because I'm seeing the en-GB copy of the string.

I mostly find this annoying when developing, but I remind myself that it would be the same if I was a native French developer and was trying to update the en.yml sources and not seeing the updates.

The main problems with sparse translations on Translatewiki include the minimum percentage of translated strings, before the translation becomes valid. For en-GB I think the threshold might not be met if only the strings that differ are counted. But in any case, if the translators only translated the ones that differed, they'd face a constant list of thousands of "untranslated" strings, and have to pick through them over and over, searching for any that genuinely differed. So I don't blame them for copy+pasting where they match.

As far as I can see there's only three problems for en-GB speakers:
* Some dodgy en-GB translations from translatewiki contributors. The use of "E-mail" (with hyphen) seems archaic to me! But dodgy translations are found in all our languages, so this isn't unique to en-GB
* Outdated en-GB translations in production. This is most noticeable where the en.yml has https links but the en-GB.yml still has http. Again, not exclusive to en-GB
* Local development for en-GB speakers. Admittedly this is a high proportion of the maintainers right now :smile: But I can live with it.

**Comment by pnorman** [comment]
> So to make this work, all we have to do is to make sure the source translations in en.yml are "en-US" and everything will work as intended

We should aim to have the only spelling differences between en-US and en-GB. If phrase or term is specific to one country or the other the odds are it will cause confusion to English-speaking people somewhere. Phrases or terms that will be understood by all English speakers are more easily understood by everyone.

**Comment by 1ec5** [comment]
That’s a reasonable request, considering the lack of an en-CA, en-NZ, en-IN, etc. so far. However, I don’t know that it’s possible to totally avoid dialectal terminology. Some terms like _chemist_ versus _drugstore_ will be confusing and surprising to someone either way. The most we can do is to avoid gratuitously regional turns of phrase, especially legal terms that are tied to a particular jurisdiction regardless of the dialect spoken.

If there were some other place to put an American English localization, we could do whatever we want with the main English one, but unfortunately that isn’t the current situation.

**Comment by maro-21** [comment]
So is `en` US English now?

**Comment by 1ec5** [comment]
No, currently there is no U.S. English localization. This issue was closed almost immediately, and #5029 is only a draft for discussion about what a U.S. English localization would contain, if we could find a Translatewiki.net-compatible code for it.

**Comment by maro-21** [comment]
Pity. So `en` is a mix of British and American or is it only British?

It would be good to have US English somewhere. Translatewiki has `en-gb` and `en-ca` [link](https://translatewiki.net/wiki/Special:MessageGroupStats?group=out-osm-0-all&messages=&language=en&x=D) so I thought `en` is US English.
In case Translatewiki won't add `en-us`, maybe you can add US translations to `en-ca`?;) Isn't Canadian English similar to US English?

**Comment by 1ec5** [comment]
As the original post and #5029 illustrate, `en` is currently a mix of British English, American English, OSM English, and some outright mistakes. Nevertheless, Translatewiki.net assumes `en` is American English, as does pretty much every user agent (operating system or browser). It is possible to create our own custom mapping from Translatewiki.net’s locale codes to YAML files. However, Translatewiki.net contributors probably wouldn’t abide by any unusual mapping from `en-CA` to `en-US`, especially not any Canadian translators there, who would be rightfully proud of their country code.

**Comment by andrewharvey** [comment]
Reading the prior responses here it sounds like we should make `en` exclusively US English, it's not fair on the Americans to not allow them to have their own translations. Could you imagine not allowing Germans to have their own translations? `en-CA` is for Canadians.

**Comment by maro-21** [comment]
> it's not fair on the Americans to not allow them to have their own translations. Could you imagine not allowing Germans to have their own translations?

Why not fair? There should be one source file in one language. It will simply be a source for translations, not a translation.

**Comment by andrewharvey** [comment]
> Why not fair? There should be one source file in one language. It will simply be a source for translations, not a translation.

Exactly. @1ec5 suggested that the source file is not in one language, but a mix of UK and US English. In OSM, I'm more inclined to make the source neutral and close to OSM tags, and then translate US from it, but that's another point.

**Comment by 1ec5** [comment]
> Isn't Canadian English similar to US English?

For the kinds of strings being translated in this repository, Canadian English spelling is closer to Australian English than American English, for example, “cancelled”, “centre”, and “licence” (versus AmEng “canceled”, “center”, and “license”, respectively). But as I mentioned in the PR, I’m more concerned about vocabulary than spelling, which most users can simply get used to. Unfortunately, there are also some differences in terminology that could cause confusion, such as “parkade” (versus “parking garage”) and “washroom” (versus “restroom”).

**Comment by maro-21** [comment]
> I'm more inclined to make the source neutral and close to OSM tags

I didn't know that such language exists :)

**Comment by andrewharvey** [comment]
> I didn't know that such language exists :)

`en_OSM` OpenStreetMaplish

https://wiki.openstreetmap.org/wiki/Tag:shop%3Dalcohol#Localized_variants
Where en_US it's Liquor Store, en_AU it's Bottle Shop, en_GB it's Off-license, in en_OSM it's simply an Alcohol Shop.
