### ISSUE TITLE
'Show address' no longer adds coords to search box

### ISSUE THREAD

**Issue by samwilson** [openstreetmap/openstreetmap-website#4997]
### URL

https://www.openstreetmap.org/search?lat=-32.05040&lon=115.77587#map=19/-32.05040/115.77587

### How to reproduce the issue?

1. Right click anywhere on the map and select 'Show address'
2. See the coordinates show up under 'Results from Internal'
3. Note that the coordinates _do not_ show up in the search box as they used to.

### Screenshot(s) or anything else?

![OpenStreetMap](https://github.com/user-attachments/assets/67e55583-6bea-4c71-8776-59b49aa17e9a)

**Comment by samwilson** [comment]
I originally raised this at #3466.

**Comment by tomhughes** [comment]
This originates in #4959.
