### ISSUE TITLE
Add Rate limiting for diary comments

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#5015]
It seems users are currently able to add lots of comments to a diary entry in some automated way. It would be good to also add rate limiting there, like we already do in other places.

<details>
For context: https://www.openstreetmap.org/user_blocks/16498
</details>

**Comment by tomhughes** [comment]
I think that's rather an overreaction to a single incident that looks a lot like some sort of silly programming error to me.

I'm also not really sure what good you think blocking them has done given it has no effect on their ability to comment - it would have made more sense to refer it to the administrators.

**Comment by SomeoneElseOSM** [comment]
@tomhughes We know they've been doing silly things in OSM diary comments, so we're stopping them doing silly things in OSM Data - at least until they talk to us about it.  The content of https://www.openstreetmap.org/user/dzejlandemon and https://www.openstreetmap.org/user/dzejlandemon/diary suggests that it is very much not a "programming error".

**Comment by tomhughes** [comment]
Well that depends on how you define it. I'm pretty sure it's somebody running a vulnerability scanner or else probing for vulnerabilities by hand and that's something that I definitely want to know about so I can take action.

**Comment by mmd-osm** [comment]
Being able to post hundreds of comments in no time can easily turn into a DoS, e.g. think about email notifications for diary entries many existing comments. 

I can’t think of a valid use case where creating so many comments would be reasonable.

**Comment by tomhughes** [comment]
I'm not saying there's a good reason to allow it. I'm saying it's not worth spending a lot of time on when we have more important things to worry about.
