### ISSUE TITLE
Unlinked pagination showing up on Diary listing page

### ISSUE THREAD

**Issue by KathleenLD** [openstreetmap/openstreetmap-website#502]
When looking at a diary page with only a few posts ([mine, for example](http://www.openstreetmap.org/user/KathleenLD/diary)) the "Older Entries | Newer Entries" text displays at the bottom of the page, but they aren't linked to anything. I would not have expected them to appear at all unless I had enough diary posts to necessitate another page, and even then I'd only expect the "Older Entries" option to display, unless I were already paging through them. 

![diary screenshot](https://f.cloud.github.com/assets/1473105/1262393/4c30e7e2-2c3e-11e3-9332-5b5f94bdae6a.png)

I ran into this issue while using Chrome.

**Comment by gravitystorm** [comment]
The links are now buttons, which "light up" when they are clickable and are grey when they are not. 

![Screenshot from 2021-03-24 15-23-56](https://user-images.githubusercontent.com/360803/112336736-40db1180-8cb5-11eb-993f-413183de3f4f.png)

Clickable version:

![Screenshot from 2021-03-24 15-24-24](https://user-images.githubusercontent.com/360803/112336740-4173a800-8cb5-11eb-80a2-622404d3d344.png)

There's still room for improvement, but I think this original issue can be closed.
