### ISSUE TITLE
'GPX Import success' e-mail contains only HTML and not a text part

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/openstreetmap-website#5025]
### URL

n/a

### How to reproduce the issue?

The '[OpenStreetMap] GPX Import success' e-mail contains only HTML and not a text part.

The message consists of:

![Screenshot 2024-07-26 at 17 24 32](https://github.com/user-attachments/assets/e05ca973-ff0a-42d2-a4a9-4e4db1365952)

**Comment by mmd-osm** [comment]
Confirmed. We seem to have gpx_failure.html.erb and gpx_success.html.erb in /app/viewa/user_mailer, but no text.erb variant to generate a text only version.

**Comment by tomhughes** [comment]
You're quite correct.

Presumably you feel this is a problem for some reason?

**Comment by mvl22** [comment]
Great, thanks. We'll be able to read these directly in our mail archives now.
