### ISSUE TITLE
Facebook login keeps asking to confirm login

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/openstreetmap-website#5026]
### How to reproduce the issue?

On logging in with Facebook, goes to URL `https://www.facebook.com/privacy/consent/gdp/`
Facebook asks 'Do you want to continue logging in to your OSM account with your Facebook account?' so it can continue to use the data to detect the account. Click 'continue'. Logs in fine. (as expected)
However, this question has to be answered for every login, which is a waste of human time. (cookie is not properly saved)
I would suggest checking with Facebook if there is a way to save this cookie properly.

Browser: Chrome 127.0.6533.73 on Windows 10.

**Comment by tomhughes** [comment]
We have absolutely no control over Facebook and suggesting we talk to somebody there is just a joke as you'd know if you new the effort we had to go to previously to try and get somebody there to unblock our account.
