### ISSUE TITLE
Rendering Man Made 

### ISSUE THREAD

**Issue by KillerKingSolo** [openstreetmap/openstreetmap-website#5052]
### Problem

[man_made](http://wiki.openstreetmap.org/wiki/Key:man_made) Does not render on OSM or other programs without being in the edit mode. This would be very useful for stuff like [mineshaft](http://wiki.openstreetmap.org/wiki/Tag:man_made=mineshaft), [adit](http://wiki.openstreetmap.org/wiki/Tag:man_made=adit), [storage_tank](http://wiki.openstreetmap.org/wiki/Tag:man_made=storage_tank), [tower](http://wiki.openstreetmap.org/wiki/Tag:man_made=tower), and other [man_made](http://wiki.openstreetmap.org/wiki/Key:man_made) stuff. I know of some places that don’t actually renter the man_made stuff and I can’t save it as a waypoint or anything like that on Organic Maps because it’s not rendering so I have to make my own waypoint and not have the actual name save place of the man_made location.

Examples:
https://www.openstreetmap.org/#map=19/34.35652/-117.74442
https://www.openstreetmap.org/#map=19/34.36081/-117.74441

### Screenshots

![image](https://github.com/user-attachments/assets/db39a984-18d9-43fb-a97e-3b895e4eede6)
![image](https://github.com/user-attachments/assets/d31198b3-c1e8-4ceb-b6a6-10a88221bf2b)
![image](https://github.com/user-attachments/assets/059e0bb2-1fc8-4430-b2f1-92a03dad045a)
![image](https://github.com/user-attachments/assets/e8cd65be-5f88-42d8-a599-e5c82ce17c5d)

**Comment by mmd-osm** [comment]
Hello, this is really the wrong place to report issues regarding map rendering. There are dedicated repos, for osm carto.
I have to close your issue since it’s not actionable for us here.

**Comment by KillerKingSolo** [comment]
> Hello, this is really the wrong place to report issues regarding map rendering. There are dedicated repos, eg. for osm carto.
> 
> I have to close your issue since it’s not actionable for us here.

Then where do I post it? This is the official OSM website GitHub where else would I go?

**Comment by mmd-osm** [comment]
Map styles are separate and independent projects really. One example is: https://github.com/gravitystorm/openstreetmap-carto

**Comment by tomhughes** [comment]
Also the menu of options you were given when you opened this bug explicitly pointed you at the correct place:

![image](https://github.com/user-attachments/assets/e7ea4343-4474-4b69-8377-dd6810095d91)
