### ISSUE TITLE
Search Results Results from → Search Results from

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#5065]
### Problem

Perhaps the repeated word "Results" could be compacted into just one instance.

![Screenshot 2024-08-11 19 05 38](https://github.com/user-attachments/assets/1487dcce-7fbf-40cd-a51b-bbbb04dac771)

Yes, even when there are more than one source too.

**Comment by mmd-osm** [comment]
@jidanni can you maybe take a look at the screenshots above if this looks as expected?
