### ISSUE TITLE
MIME type mismatch preventing CSS from loading

### ISSUE THREAD

**Issue by zekefarwell** [openstreetmap/openstreetmap-website#5079]
### URL

https://www.openstreetmap.org/

### How to reproduce the issue?

I'm finding osm.org to be fairly unusable at the moment as the CSS is not loading.   I've tried clearing the browser cache but that has not helped.  In Firefox (version 129.0.1) I'm seeing this error in the dev tools console:

> The resource from “https://www.openstreetmap.org/assets/screen-ltr-4b8b2b903e4c2372327208c82022baac871edd2bd02de9aa49b6a2b630bfac61.css” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff)

And a similar error in Chrome (version 127.0.6533.120):

> Refused to apply style from 'https://www.openstreetmap.org/assets/screen-ltr-4b8b2b903e4c2372327208c82022baac871edd2bd02de9aa49b6a2b630bfac61.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

I asked if other people were seeing the same on the OSM US Slack and the OSM World Discord.  It seems that for some people the site is working normally but some others have confirmed they are seeing the same things as me.  I'm also seeing the same on my phone.  

### Screenshot(s) or anything else?

![Screenshot 2024-08-14 at 5 36 02 PM](https://github.com/user-attachments/assets/4365f2e6-02a3-432c-bb2f-81b3e9221c29)
![Screenshot 2024-08-14 at 5 35 51 PM](https://github.com/user-attachments/assets/76e3b83a-2d4a-458e-84a7-659363efcebd)

**Comment by pnorman** [comment]
Based on a log provided by someone else it's a 404 error, not a MIME error. The MIME type just gets flagged as 404 responses aren't CSS or JS.

![1ajnp3ibRBiI](https://github.com/user-attachments/assets/72beabb5-d127-40e5-bd4a-c85d0279099e)

This is probably a deployment issue, not an openstreetmap-website issue.

**Comment by zekefarwell** [comment]
Apologies if this was the wrong repo to report this sort of issue.  I'm never quite sure where the right place is with all the different pieces we have. I'm happy to move the report.

**Comment by tomhughes** [comment]
I've purged the cache which should fix it.
