### ISSUE TITLE
sidebar_classic_pagination - width calculation not clear

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#5105]
I've noticed that in some cases, pagination cells are very narrow, in particular when we're showing two disabled cells ("..."), like in example 1 below.

To calculate a threshold value, we're currently applying the following logic (introduced in  cfa1ce8617430cdec47409a455ea2aead713334e):

```ruby
      width += body.length
```

I'm wondering why we're not taking the actual length of the strings we're showing on the screen into account, rather than the number of array elements (that includes some technical details). So instead of the previous calculation, that would be:

```ruby
      width += body.first.length
```

### Example 1

![image](https://github.com/user-attachments/assets/5067cd13-3d76-4132-9b11-e1cd188ed687)

Debug output:

```
====
["1", 1] --- 2
["...", "disabled"] --- 2
["5", 5] --- 2
["6", 6] --- 2
["7", "active"] --- 2
["8", 8] --- 2
["9", 9] --- 2
["...", "disabled"] --- 2
["11", 11] --- 2
====
36
====
```

### Example 2

![image](https://github.com/user-attachments/assets/80d786d2-9014-4e0a-8a1f-e32613099d6c)

Debug output:

```
====
["1", 1] --- 2
["2", 2] --- 2
["3", "active"] --- 2
["4", 4] --- 2
["5", 5] --- 2
["...", "disabled"] --- 2
["11", 11] --- 2
====
28
====
```

Example in production: https://www.openstreetmap.org/changeset/155575172?node_page=5

### Debug code

```ruby
  def sidebar_classic_pagination(pages, page_param)
    max_width_for_default_padding = 35

    puts "===="
    width = 0
    pagination_items(pages, {}).each do |body|
      width += 2 # padding width
      width += body.length
      puts "#{body} --- #{body.length}"
    end
    puts "===="
    puts width
    puts "===="
    link_classes = ["page-link", { "px-1" => width > max_width_for_default_padding }]
```

**Comment by AntonKhorev** [comment]
If you look at the original, you'll notice `|body, n|` instead of `|body|` which destructures the 2-element array. In https://github.com/openstreetmap/openstreetmap-website/commit/d404bc04d542d381a3233e8cf461f5c9fb981af2 I deleted `n`, probably to avoid warnings about unused variable, not noticing that it also disables destructuring.
