### ISSUE TITLE
Test failures on issues pagination

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#5127]
We're getting test failures related to the issue pagination, e.g.

```
Failure:
IssuesTest#test_issues_pagination [test/system/issues_test.rb:184]:
expected to find visible css "tr" 31 times, found 51 matches: 
"Status Reports Reported Item Reported User Last Updated",
"Open 0 Reports User 83 User 83 less than 1 minute ago", 
"Open 0 Reports User 82 User 82 less than 1 minute ago", 
"Open 0 Reports User 81 User 81 less than 1 minute ago", 
"Open 0 Reports User 80 User 80 less than 1 minute ago", 
...
```

Here's an example from [a recent unrelated PR](https://github.com/openstreetmap/openstreetmap-website/actions/runs/10601741224/job/29382202917)

Refs #5057 cc @nertc

**Comment by tomhughes** [comment]
Yes this is basically the timing issue that we discussed on that PR I think, that sometimes turbo doesn't complete changing the page in 2s and the assert fails.

**Comment by nertc** [comment]
Yes, I agree with @tomhughes. If it slows the process down, we can either delete tests temporarily, add custom `:wait`-s or change default waiting time.

**Comment by gravitystorm** [comment]
Capybara has "intelligent waiting" by default, where it doesn't fail assertions immediately after a click, it retries until it detects the content on the page and then runs the assertions. So I wonder if it's not that the next page is taking 2+ seconds to render (and that would be a problem in itself) but rather that the turbo has just started to run, but capybara thinks the content is already present and so immediately tests it, before turbo is finished (which might be only a few ms later).

So it might not be related to timeouts (and there's no timeout information in the error) but rather that capybara's running too quickly. In which case extending the (maximum) wait time might not help.

It's perhaps notable that this particular assertion isn't checking that a specific thing will appear (e.g. specific text, or html with a specific id, from the second page of results) that capybara would normally intelligently wait for. Instead it's checking for html that's also on the original page (just in a different count). Could that be interfering with the intelligent waiting?

https://github.com/teamcapybara/capybara#asynchronous-javascript-ajax-and-friends

**Comment by tomhughes** [comment]
Turbo adds the `aria-busy` attribute (https://turbo.hotwired.dev/reference/attributes#automatically-added-attributes) to the frame while a navigation is in progress so maybe we can wait until that is removed before re-evaluating?

**Comment by nertc** [comment]
I'll rewrite the test to check specific reported issues. It will solve the problem @gravitystorm linked.

**Comment by mmd-osm** [comment]
#5129 is merged. Can we close this now?
