### ISSUE TITLE
An old deleted GPS trace is still visible on the rendered GPS traces map

### ISSUE THREAD

**Issue by NeatNit** [openstreetmap/openstreetmap-website#5134]
### How to reproduce the issue?

About a year ago I uploaded a GPS trace to OpenStreetMap and deleted it a few minutes later. Today I see that it's still visible in the rendered map when GPS traces are shown (&layers=G).

I don't want to publicly share a link to the coordinates because it reveals my home address which I'd rather keep private. If you give me a private email address I will be happy to send it there.

**Comment by mmd-osm** [comment]
That’s a known issue with the gps tile layer: https://github.com/openstreetmap/gpx-updater/issues/7

It’s off topic for the osm website repo. Please follow up in the gpx-updater repo.

**Comment by NeatNit** [comment]
Thank you for pointing me in the right direction. According to https://github.com/openstreetmap/gpx-updater/issues/4 "Unfortunately the OSM GPS database doesn't provide any way to be notified when traces are deleted, so the map server doesn't know anything about the deletions."

Isn't this a missing feature in the OSM website repo?

**Comment by mmd-osm** [comment]
I’m not sure this would help in the end. The way this works today is that every trace keeps on adding some colored points to a given png tile. Once you have added a few traces, it might be challenging to remove the very first trace again. There’s really no database in place which allows us to render all remaining traces for a tile. The png file is the only way traces are stored. You probably realize this is a bit of a bigger topic.

**Comment by NeatNit** [comment]
Why isn't it be possible to re-render a tile from scratch by using [the bounding box endpoint](https://wiki.openstreetmap.org/wiki/API_v0.6#Get_GPS_Points:_Get_/api/0.6/trackpoints?bbox=left,bottom,right,top&page=pageNumber) to get all relevant traces, similar to how JOSM can show GPS traces?

**Comment by mmd-osm** [comment]
Nobody has implemented it, and that endpoint is really really slow. It might not be feasible for traces spanning a larger area.

**Comment by mmd-osm** [comment]
There’s a bit more detail on the topic in https://github.com/openstreetmap/gpx-updater/issues/4 since I last checked it. Subscribing to the issue might be a good idea.
