### ISSUE TITLE
Docker compose deployment not working properly

### ISSUE THREAD

**Issue by RilusMahmud** [openstreetmap/openstreetmap-website#5167]
### How to reproduce the issue?

If you follow the instruction with docker installation for self hosting, then if you import or don't the changeset is fetched as expected. you can try.

### Screenshot(s) or anything else?

![Screenshot 2024-09-08 at 12 54 31 PM](https://github.com/user-attachments/assets/24c7602a-8a46-4be9-914f-f6f3746a87fc)
![Screenshot 2024-09-08 at 12 55 25 PM](https://github.com/user-attachments/assets/f773db8e-5a48-404b-8914-572b437863b5)

got this error,
`web-1  | Unpermitted parameter: :xhr. Context: { controller: ChangesetsController, action: index, request: #<ActionDispatch::Request:0x0000651f40bd53c0>, params: {"xhr"=>"1", "controller"=>"changesets", "action"=>"index"} }
`
I've configured as the instruction described and data import was successful without any error.
NB. also I've tried without the data import, got the same error message.

Can anyone help me, if i'm doing anything wrong?

**Comment by tomhughes** [comment]
That doesn't look like it's anything to do with docker to be honest.

**Comment by AntonKhorev** [comment]
There are still dubious uses of `params.permit()` in the code but they shouldn't prevent anything from working.

**Comment by RilusMahmud** [comment]
> That doesn't look like it's anything to do with docker to be honest.

Got your point, it's not exactly got anything to do with docker, but I've described that way that I've used docker for installation.

**Comment by RilusMahmud** [comment]
> There are still dubious uses of `params.permit()` in the code but they shouldn't prevent anything from working.

It shouldn't, it was working in previous version, last version I was using was with 3 years old codebase, so I thought let's pull the latest changes, all was done smoothly, but after all the setup got this error.

**Comment by mmd-osm** [comment]
The empty changeset list is expected, and I've also experienced it. I think osmosis, the tool used to upload the data, isn't populating all fields in all tables in a proper way. You should try to upload some data using JOSM or so.

**Comment by RilusMahmud** [comment]
> You should try to upload some data using JOSM or so.

Okay thanks, let me try this.

**Comment by tomhughes** [comment]
Right, but you've titled this issue as if docker was the issue, which is very misleading.

I can't actually reproduce it for the `xhr` parameter but I can for the `format` parameter but as far as I can tell it's just a warning so there's no actual problem here - that is an automatically added parameter that is not used by the server for that action.

**Comment by mmd-osm** [comment]
> Okay thanks, let me try this.

You should try with an empty database, otherwise there might be duplicate objects from your previous osmosis import attempt. Osmosis doesn't properly set the maximum object id for PostgreSQL sequences, which is causing all sorts of weird issues.

**Comment by RilusMahmud** [comment]
> > Okay thanks, let me try this.
> 
> You should try with an empty database, otherwise there might be duplicate objects from your previous osmosis import attempt. Osmosis doesn't properly set the maximum object id for PostgreSQL sequences, which is causing all sorts of weird issues.
> 
> We should also update the documentation to only use PBF extracts with metadata from https://osm-internal.download.geofabrik.de
> 
> For "non-public PBF extracts" osmosis will create huge changesets with id = 0 (!)

Thanks a lot, turned out you are right about the data, the import process malformed the id of the changeset and also most of the primary_key, then if I restore that db backup it was working as expected.

Thanks for the support! 🚀
