### ISSUE TITLE
The Ruby API ignores getting a specific version of an object in a Multi Fetch request

### ISSUE THREAD

**Issue by deevroman** [openstreetmap/openstreetmap-website#5183]
### How to reproduce the issue?

`http://localhost:8008/api/0.6/nodes.json?nodes=5113v2` CGImap returns a specific version
```json
{
  "version": "0.6",
  "generator": "openstreetmap-cgimap 2.0.1 (16 d2f7ab0286d9)",
  "copyright": "OpenStreetMap and contributors",
  "attribution": "http://www.openstreetmap.org/copyright",
  "license": "http://opendatacommons.org/licenses/odbl/1-0/",
  "elements": [
    {
      "type": "node",
      "id": 5113,
      "lat": 59.9573376,
      "lon": 30.3069732,
      "timestamp": "2024-09-07T16:17:24Z",
      "version": 2,
      "changeset": 73,
      "user": "LOL",
      "uid": 2
    }
  ]
}
```

`http://localhost:3000/api/0.6/nodes.json?nodes=5113v2` Returns the latest version of the object

```json
{
  "version": "0.6",
  "generator": "OpenStreetMap server",
  "copyright": "OpenStreetMap and contributors",
  "attribution": "http://www.openstreetmap.org/copyright",
  "license": "http://opendatacommons.org/licenses/odbl/1-0/",
  "elements": [
    {
      "type": "node",
      "id": 5113,
      "lat": 59.9573376,
      "lon": 30.3069732,
      "timestamp": "2024-09-11T07:21:31Z",
      "version": 3,
      "changeset": 74,
      "user": "admin",
      "uid": 1,
      "tags": {
        "name": "test"
      }
    }
  ]
}
```

Moreover, the Ruby API allows any characters after the object id, and only takes into account the first digits of the element array ?nodes=

**Comment by tomhughes** [comment]
So how does this square with #5005 where you are talking about the response to exactly that call? Is that bug actually about cgimap?

**Comment by deevroman** [comment]
When I reported about https://github.com/openstreetmap/openstreetmap-website/issues/5005 I expected the Ruby implementation to be consistent with CGImap. But deploying a local instance of openstreetmap-website without cgimap, I found differences.

I see a mention of the ability to get a specific version of an object here https://wiki.openstreetmap.org/wiki/API_v0.6#Multi_fetch:_GET_/api/0.6/[nodes|ways|relations]?#parameters

As a result, the question is: if the Ruby implementation is considered the leading one, then what is this difference? A bug in the Ruby API or a feature that exists only in CGImap?

**Comment by mmd-osm** [comment]
Yes, it's a duplciate of #3715. The version based multi fetch hasn't been implemented yet on Rails.

**Comment by deevroman** [comment]
It's quite unusual to find mentions of issues only in Pull Requests, but thank you for your response

**Comment by tomhughes** [comment]
Ah that's the bug I was looking for in fact, as I thought this was a duplicate!

**Comment by AntonKhorev** [comment]
The actual issue is #1067.
