### ISSUE TITLE
website not entirely in English

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#5193]
I temporarily set the English language using the link
https://www.openstreetmap.org/?locale=en

And almost the entire website is in English except for Map Key. Why?

It's the same when I set the English language permanently in Preferences.

![osm-website-en-pl](https://github.com/user-attachments/assets/cafe7b69-f3a2-4047-87e8-169dc4068c4f)

**Comment by tomhughes** [comment]
That is a development tool that is not intended for end users.

Critically it only applies to the immediate page load and not to any links followed from that page, or sub-documents (like the key) fetched from it.

**Comment by AntonKhorev** [comment]
This is why:
https://github.com/openstreetmap/openstreetmap-website/blob/17bea98e199f204b22847356fc64beaa81a9373a/app/controllers/site_controller.rb#L60-L61
