### ISSUE TITLE
translation of Osm:Site.key.table.entry.stop

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#5194]
What is "Osm:Site.key.table.entry.stop" and where is it visible on the website? It's a translation string. I coulnd't find. I think it should in the Map Key section, but couldn't find it there.

See also:
* https://www.openstreetmap.org/user/Aphaia_JP/diary/405038
* https://translatewiki.net/wiki/Osm:Site.key.table.entry.stop/en

**Comment by tomhughes** [comment]
It will be visible in any map key with an entry named "stop" but I have no idea what keys that might be.

**Comment by tomhughes** [comment]
It's used in the opnvkarte key:

https://github.com/openstreetmap/openstreetmap-website/blob/17bea98e199f204b22847356fc64beaa81a9373a/config/key.yml#L192

The opnvkarte layer was removed in 75a4d406b9e8471c0fe0ebf2a47d47f0ae36289a though so it's not used anymore.

**Comment by maro-21** [comment]
Can we then remove this string for translation?

**Comment by HolgerJeromin** [comment]
AFAIU #5196 will remove this.
