### ISSUE TITLE
some translated strings don't appear

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#5198]
On pages like
https://www.openstreetmap.org/user_blocks?locale=de
translations of the strings
https://translatewiki.net/wiki/Osm:Shared.pagination.user_blocks.older/de
https://translatewiki.net/wiki/Osm:Shared.pagination.user_blocks.newer/de
don't appear even though they were translated in April this year.

![osm-website-no-translation](https://github.com/user-attachments/assets/7b59ed49-3ddc-4949-a2e9-91e571b13f8c)

**Comment by tomhughes** [comment]
Those keys didn't even exist until 7633657ecb93d45fef823f7707d91e1576c18a1f which is from yesterday, so they can't possibly have been translated in April.

They may have been translated under the old name, and TranslateWiki may have migrated them to the new names, but that won't reflect on the site until the next time they feed changes back.
