### ISSUE TITLE
buttons on userpages visible after logging out

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#5199]
On a userpage
https://www.openstreetmap.org/user/test?locale=en
we have buttons like
`Send Message` | `Add Friend` | `Report this User` | `Mute this User`
and on the same userpage after logging out from above ones we can't see
`Report this User` and `Mute this User` anymore
but we still can see `Send Message` and `Add Friend`.

I think these two actions shouldn't be visible either, because they require logging in.

What do you think?

**Comment by tomhughes** [comment]
Is there a good reason now to show them? if you use them then you're prompted to login and then you can continue?

**Comment by mmd-osm** [comment]
> [...] actions shouldn't be visible either, because they require logging in.

I don't think this will work in the long run. Once we start working on GDPR recommendations, you would have to essentially remove nearly all the links there. The requirement to log in shouldn't determine if a link is shown or not.

**Comment by nenad-vujicic** [comment]
> > [...] actions shouldn't be visible either, because they require logging in.
> 
> I don't think this will work in the long run. Once we start working on GDPR recommendations, you would have to essentially remove nearly all the links there. The requirement to log in shouldn't determine if a link is shown or not.

I think the logic behind this issue is "if you removed Report / Mute, remove them all (Send Message, Add Friend / Unfriend), i.e. this looks unfinished, complete it".

**Comment by tomhughes** [comment]
Did we actually remove report and mute? or were they just never enabled for non-logged in users?

The point about friend/unfriend needing to know state is very valid though.

**Comment by nenad-vujicic** [comment]
> Did we actually remove report and mute? or were they just never enabled for non-logged in users?
> 
> The point about friend/unfriend needing to know state is very valid though.

The report feature was added in commit bdc6add for both logged-in and not-logged-in users. Later, it was restricted to display only for logged-in users.

The mute feature was added in commit efc61f1 for non-logged-in users only.

**Comment by tomhughes** [comment]
It was 206e1309a95b498a220d8de6cf4ed5970ebd6778 in #1576 that hid report for non-logged in users and it's not clear what the reason was though I haven't tried to read the entire PR thread...
