### ISSUE TITLE
`/messages/{id}/mark?mark={unread/read}` returns HTML code

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/openstreetmap-website#5222]
### URL

https://www.openstreetmap.org/messages/inbox

### How to reproduce the issue?

0. Have at least 1 message in the inbox
1. Mark it as read/unread
2. Notice that two requests are made at the same time (one POST and one GET).

The POST request goes to `https://www.openstreetmap.org/messages/{id}/mark?mark=unread`, while the GET request goes to `https://www.openstreetmap.org/messages/inbox`. Both requests return the same HTML code, which seems a bit wasteful on server resources if both are generated independently.

The most logical solution would be to change the response body of the POST request to have some short status code/text instead of the whole page HTML (assuming that won't break the turbo integration).

### Screenshot(s) or anything else?

![2024-09-18_00-39](https://github.com/user-attachments/assets/54255672-ea65-417f-887a-72be29f7097d)

**Comment by mmd-osm** [comment]
This seems a bit odd. The POST request already returns an HTTP return code 303 along with a `location: https://www.openstreetmap.org/messages/inbox` header for the redirect. 

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303 the browser is supposed to ignore the payload in the body and follow the redirect. I'm not clear why Rails is sending the payload as well in this case.

**Comment by AntonKhorev** [comment]
I'm not convinced that POST actually sends the response body even though Firefox shows it.

**Comment by mmd-osm** [comment]
@AntonKhorev : you're right, I checked the response in wireshark, and the POST request returns HTTP 302 without any payload. Closing here, since there's no issue really.
