### ISSUE TITLE
add changeset visualisation when seeing a changeset 

### ISSUE THREAD

**Issue by Marc-marc-marc** [openstreetmap/openstreetmap-website#5240]
### Problem

when seeing a changet https://www.openstreetmap.org/changeset/<...>
it only list objets and bbox without any info about the change itself

### Description

display changeset changes
and/or and link to such tools
for ex  https://www.openstreetmap.org/user/TrickyFoxy/diary/405188
And the tags diff  from the previous diary entry https://www.openstreetmap.org/user/TrickyFoxy/diary/404417
https://osmlab.github.io/changeset-map/

### Screenshots

https://cdn.trickyfoxy.ru/better0.5-changeset.jpg
https://cdn.trickyfoxy.ru/better0.5-history3.webp
https://telegra.ph/file/77677fcd617b236efdaa1.png

**Comment by mmd-osm** [comment]
Changeset visualization is very similar to #1376. Please add your comments there as well.
Tag coloring is already covered in #738

-> closing as duplicate
