### ISSUE TITLE
Share button should preserve the node/way/relation id when creating the URL

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#5252]
### Problem

Check this magnificent genuine working link I created,
https://www.openstreetmap.org/way/579405035?mlat=24.181444&mlon=120.865815#map=16/24.181444/120.865815
It's packed with
1. a way
2. a zoom level
3. a screen center position
4. a marker
5. a (default) map layer

I can't think of much more one could pack in.

### Description

How did I ever create it? Did I use the Share button?

Well I tried, but it threw away the way. I wish it wouldn't.

So I ended up crafting it by hand.

See also #905.

### Screenshots

![zzz](https://github.com/user-attachments/assets/650b9bd7-eba4-46af-9dda-3103ad492f4e)

### Narration
The bad guys came up the orange path on their way to the four-corner junction marked with the marker.

**Comment by jidanni** [comment]
> How do you want the html embed to behave in this case?

Naturally it should look just like the picture I posted.

**Comment by jidanni** [comment]
Very good question. And I think the answer should be just the map only never mind the sidebar. Because the person doing the in bed should be responsible for putting the words they want in their own caption for their picture. 

For instance I select that road but the OSM way number of that road is not important at all for the people I want to show it to. So in my caption I would write "this is the road that criminals went up"  (and thank goodness there is no extra verbiage from that sidebar entering my presentation.)

**Comment by mmd-osm** [comment]
I don't think share links with node/way/relations are a good fit for sharing and publishing elsewhere. Remember, element ids are not stable and could change at any time, even by your "criminals".

I vote for closing this issue, since it's fairly off topic for the site.

**Comment by AntonKhorev** [comment]
We could have links to specific versions of elements that don't change but even the actual osm website can't show them currently. There is a pull request for nodes though #4930.
