### ISSUE TITLE
update link for Austria data sources

### ISSUE THREAD

**Issue by kathleenlu09** [openstreetmap/openstreetmap-website#5253]
### URL

https://www.openstreetmap.org/copyright

### How to reproduce the issue?

It has been reported to LWG that the last link here:

> Austria: Contains data from [Stadt Wien](https://data.wien.gv.at/) (under [CC BY](https://creativecommons.org/licenses/by/3.0/at/deed.de)), [Land Vorarlberg](https://www.vorarlberg.at/vorarlberg/bauen_wohnen/bauen/vermessung_geoinformation/weitereinformationen/services/wmsdienste.htm) and Land Tirol (under [CC BY AT with amendments](https://www.tirol.gv.at/applikationen/e-government/data/nutzungsbedingungen/)).

for `CC BY AT with amendments` to https://www.tirol.gv.at/applikationen/e-government/data/nutzungsbedingungen/ is a dead link, and it should be updated to https://www.tirol.gv.at/data/nutzungsbedingungen/

Can this please be updated?

**Comment by tomhughes** [comment]
As we explained in #4470 we're happy to change it if LWG are OK with that, given that the text as currently written is there to record a legally required attribution.

**Comment by mmd-osm** [comment]
@kathleenlu09 is LWG member, that's why I created the PR right away.

**Comment by tomhughes** [comment]
Yes I know, it just wasn't clear that this was an LWG decision/request given it said "it has been reported to" rather than saying that they had decided/agreed that it should be changed. I assume that was the intention though.
