### ISSUE TITLE
Refactor PaginationMethods to Support Sorting with Turbo Integration

### ISSUE THREAD

**Issue by kcne** [openstreetmap/openstreetmap-website#5259]
### Problem

Currently, we use a custom `PaginationMethods` module, which sorts and filters data using IDs. Sorting by other non unique attributes does not work correctly, and implementing sorting with these attributes would require changes to `PaginationMethods`. Refactoring it to support sorting with pagination would allow seamless integration of this feature.

### Description

`PaginationMethods` could be modified to handle sorting on attributes other than IDs, integrated with Turbo for pagination. This would allow us to add sorting to tables across the site. As an example, this feature could later be extended to the Notes page, where Turbo pagination would enhance the user experience with sortable columns and icons next to headers.

I am eager to do some research and explore the best approach for this. Would appreciate any suggestions or ideas on how to proceed.

### Screenshots

On the UI end, integrating this into tables could look something like this (we would just add the sorting icons):
<img width="775" alt="Screenshot 2024-10-13 at 16 21 36" src="https://github.com/user-attachments/assets/ca4cddfc-8060-437a-b49a-4eebdb56b554">

**Comment by tomhughes** [comment]
Did you close this because you realised the problem with it? That pagination needs any ordering to be on a unique index so that the cursor positioning can work...

**Comment by kcne** [comment]
Tom, I want to dig a bit deeper into this to explore limitations and what are some solid ways to approach this, after which I will reopen this again. I've read few blog posts where people use Turbo with [Stimulus](https://github.com/hotwired/stimulus) but I'm not sure if that would fit the bill for our use case.

**Comment by tomhughes** [comment]
Just to be clear my concerns are not about how the UI works, it's about the database queries being performed on the backend and whether they are safe/efficient.

**Comment by kcne** [comment]
You bring up a valid point about the limitations of cursor-based pagination with sorting. Cursor pagination works efficiently when sorting by a unique or sequential field (like `id`, `created_at`, or `updated_at`), but it breaks down when we try to sort by non-unique columns (e.g., `name`, `status`).

To address this, there are a couple of potential solutions:

1. **Combined Sorting**: We could continue using cursor-based pagination but with a fallback to a secondary unique column like `id`. This way, sorting by `name` or `status` would still function but would maintain stable pagination by also ordering by `id` to ensure uniqueness:
   
   ```sql
   ORDER BY name ASC, id ASC
   ```

   This approach would retain the benefits of cursor-based pagination while allowing some flexibility with sorting.

2. **Offset-based Pagination**: If we want to fully support sorting by arbitrary columns, we could switch to offset-based pagination when sorting by non-unique columns. This is less efficient on larger datasets but avoids the problem of ambiguous cursor positions.

3. **Hybrid Approach**: Implement cursor-based pagination for sortable fields that are unique (like `id` or timestamps), and fallback to offset-based pagination for others.

Before proceeding, I’d like to get some thoughts on which approach fits best with our performance requirements and use cases. If we'd prefer sticking with cursor-based pagination, I can explore implementing the combined sorting method, as it strikes a balance between efficiency and flexibility.

**Comment by tomhughes** [comment]
It's only efficient if there's also an index on the columns in question and there's a limit to how many of those we want to add, and you also need uniqueness though that can be achieved by appending id to any other cursor field(s) to create a composite cursor.

The whole point of moving to cursor based pagination is to get away from offset based pagination so we definitely don't want to go back to that,
