### ISSUE TITLE
Reminder for unanswered messages

### ISSUE THREAD

**Issue by malenki** [openstreetmap/openstreetmap-website#526]
Regarding the OSM messaging interface.  

It would be handy if there was a possibility to get reminded to messages one has sent but the recipient hasn't answered.

Reasoning:  
I often send messages to users who seemed to have made an error. When they haven't replied after about seven days, I fix the error the to my best knowledge.  
For now I have to compare the sent messages in the outbox with the received messages in the inbox to make sure not to miss some errors I detected and reported to its creators but which still aren't fixed due to a lacking response.

**Comment by jjiglesiasg** [comment]
We have several dozens of Edits (mostly adding places) made from maps.me, Osmand and other mobile applications and try to keep them under control using achavi and neis-one.org tools. And also try to be "proactive" in guiding good practices for editing, so sending comments on changesets or messages to the users.
My question is: Are those messages or notifications being delivered to such applications users?
If not, there is ilogic to have people that add crazy data and we mappers have no way to guide them...
Please advise

**Comment by tomhughes** [comment]
All user-user messages and changeset comments are emailed to the user. Strictly speaking I think you can unsubscribe from your own changeset and then wouldn't get notified but you'd have to do it for each one and I doubt anybody does it routinely.

Other than that I don't think there is anything actionable here - we don't really link messages in the way that would be necessary for the original suggestion and as other people have said it would problematic from a privacy point of view to reveal if people had read messages.
