### ISSUE TITLE
Directions need to say "go straight onto road B"

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#5280]
At an intersection, even if no left or right turn is involved,
directions should still say "go straight onto road B",
when departing road A.

To get from green marker to red marker, one takes these roads,

1. 仁愛路四段48巷
2. 四維路52巷19弄
3. 信義路四段99巷

Alas, due to no turns being involved,

https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=25.036723%2C121.547048%3B25.034351%2C121.547037
only mentions 1 and 3.

And

https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=25.036723%2C121.547048%3B25.034351%2C121.547037#map=18/25.035535/121.547056

also

https://www.openstreetmap.org/directions?engine=fossgis_valhalla_foot&route=25.036723%2C121.547048%3B25.034351%2C121.547037

only mention 1.

**Comment by tomhughes** [comment]
We're just relaying the instructions from the routing engines - if you have a problem with the instructions then you need to address it with those engines as we have no control over them.

**Comment by AntonKhorev** [comment]
This is the Graphhopper instructions for the query:

![image](https://github.com/user-attachments/assets/8b9875cb-379e-4a6c-a51f-5f02c9097540)

None of the engines mentions "19" in their instructions.

**Comment by mmd-osm** [comment]
https://discuss.graphhopper.com/t/how-to-handle-when-street-name-changes-on-a-route/5528 mentions some url parameter to get all street names. I haven’t checked what options other routing engines are offering.

**Comment by jidanni** [comment]
And the winner is...

https://www.google.com/maps/dir/?api=1&origin=25.036723%2C121.547048&destination=25.034351%2C121.547037

**Comment by jidanni** [comment]
Bing Maps also has all the
>Road name changes to 信義路四段99巷

And even adds
> The last intersection before your destination is 四维路66巷

>If you reach 四維路76巷, you've gone too far

And it even tells you how to say the words.

**Comment by jidanni** [comment]
Odd, other times what looks straight on the map is detected as a fork, so the bug of assuming it is the same road is avoided.

https://www.openstreetmap.org/directions?engine=fossgis_valhalla_car&route=24.153800%2C120.733500%3B24.157770%2C120.733740
