### ISSUE TITLE
Error in bundle exec db:create 

### ISSUE THREAD

**Issue by alongLFB** [openstreetmap/openstreetmap-website#5281]
### How to reproduce the issue?

when I use M1 Mac to build this project. it can not run this command 'bundle exec rails db:create'

bundle exec rails db:create
bin/rails aborted!ls db:create                                                                                                                                                                               ─╯
LoadError: Couldn't load the gd2 library. (LoadError)
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/gd2-ffij-0.4.0/lib/gd2-ffij.rb:158:in `rescue in <module:GD2FFI>'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/gd2-ffij-0.4.0/lib/gd2-ffij.rb:144:in `<module:GD2FFI>'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/gd2-ffij-0.4.0/lib/gd2-ffij.rb:10:in `<module:GD2>'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/gd2-ffij-0.4.0/lib/gd2-ffij.rb:9:in `<main>'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/bundler-2.5.16/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/bundler-2.5.16/lib/bundler/runtime.rb:55:in `each'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/bundler-2.5.16/lib/bundler/runtime.rb:55:in `block in require'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/bundler-2.5.16/lib/bundler/runtime.rb:44:in `each'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/bundler-2.5.16/lib/bundler/runtime.rb:44:in `require'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/bundler-2.5.16/lib/bundler.rb:212:in `require'
/Users/along.li/openstreetmap-website/config/application.rb:7:in `<main>'
/Users/along.li/openstreetmap-website/Rakefile:4:in `require_relative'
/Users/along.li/openstreetmap-website/Rakefile:4:in `<main>'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/command.rb:156:in `invoke_rake'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/command.rb:73:in `block in invoke'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/command.rb:149:in `with_argv'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/command.rb:69:in `invoke'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/commands.rb:18:in `<main>'
<internal:/Users/along.li/.rvm/rubies/ruby-3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/Users/along.li/.rvm/rubies/ruby-3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'

Caused by:
LoadError: Could not open library '': dlopen(, 0x0005): tried: '' (no such file), '/System/Volumes/Preboot/Cryptexes/OS' (not a file), '/usr/lib/' (not a file, not in dyld cache), '' (no such file), '/usr/local/lib/' (not a file), '/usr/lib/' (not a file, not in dyld cache). (LoadError)
Could not open library '/opt/homebrew/lib/': dlopen(/opt/homebrew/lib/, 0x0005): tried: '/opt/homebrew/lib/' (not a file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/' (no such file), '/opt/homebrew/lib/' (not a file).
Could not open library '/usr/local/lib/': dlopen(/usr/local/lib/, 0x0005): tried: '/usr/local/lib/' (not a file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/' (no such file), '/usr/local/lib/' (not a file).
Could not open library '/usr/lib/': dlopen(/usr/lib/, 0x0005): tried: '/usr/lib/' (not a file), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/' (not a file), '/usr/lib/' (not a file, not in dyld cache).
Could not open library 'lib.dylib': dlopen(lib.dylib, 0x0005): tried: 'lib.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlib.dylib' (no such file), '/usr/lib/lib.dylib' (no such file, not in dyld cache), 'lib.dylib' (no such file), '/usr/local/lib/lib.dylib' (no such file), '/usr/lib/lib.dylib' (no such file, not in dyld cache).
Searched in <system library path>, /opt/homebrew/lib, /opt/local/lib, /usr/local/lib, /usr/lib
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/ffi-1.17.0-arm64-darwin/lib/ffi/dynamic_library.rb:94:in `load_library'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/ffi-1.17.0-arm64-darwin/lib/ffi/library.rb:95:in `block in ffi_lib'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/ffi-1.17.0-arm64-darwin/lib/ffi/library.rb:94:in `map'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/ffi-1.17.0-arm64-darwin/lib/ffi/library.rb:94:in `ffi_lib'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/gd2-ffij-0.4.0/lib/gd2-ffij.rb:145:in `<module:GD2FFI>'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/gd2-ffij-0.4.0/lib/gd2-ffij.rb:10:in `<module:GD2>'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/gd2-ffij-0.4.0/lib/gd2-ffij.rb:9:in `<main>'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/bundler-2.5.16/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/bundler-2.5.16/lib/bundler/runtime.rb:55:in `each'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/bundler-2.5.16/lib/bundler/runtime.rb:55:in `block in require'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/bundler-2.5.16/lib/bundler/runtime.rb:44:in `each'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/bundler-2.5.16/lib/bundler/runtime.rb:44:in `require'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/bundler-2.5.16/lib/bundler.rb:212:in `require'
/Users/along.li/openstreetmap-website/config/application.rb:7:in `<main>'
/Users/along.li/openstreetmap-website/Rakefile:4:in `require_relative'
/Users/along.li/openstreetmap-website/Rakefile:4:in `<main>'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/command.rb:156:in `invoke_rake'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/command.rb:73:in `block in invoke'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/command.rb:149:in `with_argv'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/command.rb:69:in `invoke'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/railties-7.2.1.1/lib/rails/commands.rb:18:in `<main>'
<internal:/Users/along.li/.rvm/rubies/ruby-3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/Users/along.li/.rvm/rubies/ruby-3.2.5/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/Users/along.li/.rvm/gems/ruby-3.2.5/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)

**Comment by tomhughes** [comment]
Apparently you don't have the gd2 library installed so you will need to fix that. I have no idea about Mac's but I believe the `brew install gd` from https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md#macosx is supposed to take take of that.

**Comment by kcne** [comment]
I encountered the same issue on my M4 Mac and found a solution. The problem is that the `gd2-ffij` gem can't find the GD2 library in the Homebrew installation path.

Looking at the `gd2-ffij` gem's source code, it searches for the library in these paths:
```ruby
paths = if ENV['GD2_LIBRARY_PATH']
  [ ENV['GD2_LIBRARY_PATH'] ]
else
  [ '/usr/local/{lib64,lib}', '/opt/local/{lib64,lib}', '/usr/{lib64,lib}', '/usr/lib/{x86_64,i386}-linux-gnu' ]
end
```

As you can see, it doesn't include Homebrew's library path (`/opt/homebrew/lib`), which is where the library is installed on M1 Macs.

Here's how to fix it:

1. First, make sure GD2 is installed via Homebrew:
```bash
brew install gd
```

2. Then, set the `GD2_LIBRARY_PATH` environment variable to point to the Homebrew GD2 library location:
```bash
export GD2_LIBRARY_PATH=/opt/homebrew/Cellar/gd/2.3.3_6/lib
```

3. After setting this environment variable, try running your Rails commands again:
```bash
bundle exec rails db:create
```

The issue occurs because the `gd2-ffij` gem doesn't include Homebrew's library path in its search locations. I will open a PR to the `gd2-ffij` gem repository to add support for Homebrew installations.

For now, setting the `GD2_LIBRARY_PATH` environment variable is a workaround that allows the gem to find the library in the Homebrew installation path.

You might want to add this environment variable to your shell configuration file (`.zshrc` or `.bashrc`) to make it permanent:
```bash
echo 'export GD2_LIBRARY_PATH=/opt/homebrew/Cellar/gd/2.3.3_6/lib' >> ~/.zshrc
```
