### ISSUE TITLE
How to configure rapid editor in a local deployment environment? 

### ISSUE THREAD

**Issue by jeepli** [openstreetmap/openstreetmap-website#5285]
### Problem

When I tried to use rapid, I encountered an authorization failure issue.

### Description

`oauth2/authorize` success but `token` call failed with 401 and 

{
    "error": "invalid_client",
    "error_description": "Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."
}

### Screenshots

oauth config:
![image](https://github.com/user-attachments/assets/1d593bd8-4157-4dbd-9442-828e35e626b9)
![image](https://github.com/user-attachments/assets/d4f632fc-d2d5-40ae-bece-6a21f191b2f0)

settings.local.yml
![image](https://github.com/user-attachments/assets/022e301b-063d-4659-8930-63cfef67352e)

rapid config:
client_id: "YXkdh3Tjr38he9lDgZwPvmHjnb_NrtUHTkDuiZgo6Tk",
client_secret: "Vbc0nCTwkBxSCbHCNFWOLSDUWfl_5Z5QV5Ru43rnxAo",

**Comment by tomhughes** [comment]
We don't write rapid or know anything about it so we are unable to help - you should address your questions to the rapid developers.

**Comment by tomhughes** [comment]
The only thing I would say (and it won't be the cause of the problem) is that you don't need to put the rapid id or keys in `settings.local.yml` as the rails code doesn't need them and by doing so you're duplicating those settings and overwriting the id and key the web site uses for itself.
