### ISSUE TITLE
Show point that Location Panel is referring to

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#5287]
### Problem

Here we observe the Location Panel.

Ah, but where is the location it is referring to?

Is it the coordinates of
- A, where the mouse pointer currently is?
- B, where the mouse pointer departed the map, a few minutes ago?
- C, the selected item? (as it would be in the Measurement Panel)

### Description

Answer: B, the only _invisible_ point of the three!

Therefore there should be a checkbox "[ ] Show marker", (like the Share function) , so users can see where in fact it is actually referring to.

### Screenshots

![Screenshot 2024-10-25 16 31 24](https://github.com/user-attachments/assets/cfbeb22c-ef37-4cdd-a467-52dddfdf0ff3)

**Comment by mmd-osm** [comment]
This seems like the wrong place, you need to report iD topics here: https://github.com/openstreetmap/iD
