### ISSUE TITLE
Bogus comment is added when a note is reopened

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/openstreetmap-website#5359]
### URL

https://www.openstreetmap.org/note/4537701

### How to reproduce the issue?

1. Press "Reopen" on a closed note

The bogus is content is likely dynamically generated, since it "leaks" the user's UI language and the current map view.

### Screenshot(s) or anything else?

Also see 
https://www.openstreetmap.org/note/3958106
https://www.openstreetmap.org/note/4482755
https://www.openstreetmap.org/note/4537279

**Comment by tomhughes** [comment]
If you want to open test notes please use https://master.apis.dev.openstreetmap.org/ not the live site!
