### ISSUE TITLE
notes.json endpoint returns empty (redacted?) notes

### ISSUE THREAD

**Issue by pietervdvn** [openstreetmap/openstreetmap-website#5379]
### URL

GET 	https://api.openstreetmap.org/api/0.6/notes.json?limit=10000&closed=7&bbox=4.21875,50.73645513701065,4.5703125,50.95842672335991

### How to reproduce the issue?

Query for https://api.openstreetmap.org/api/0.6/notes.json?limit=10000&closed=7&bbox=4.21875,50.73645513701065,4.5703125,50.95842672335991 via the browser. This will include note with URL: https://www.openstreetmap.org/note/4541086 and content:

```
{
"id":4541086,
"url":"https://api.openstreetmap.org/api/0.6/notes/4541086.json",
"comment_url":"https://api.openstreetmap.org/api/0.6/notes/4541086/comment.json",
"close_url":"https://api.openstreetmap.org/api/0.6/notes/4541086/close.json",
"date_created":"2024-12-02 15:45:33 UTC",
"status":"open",
"comments":[]}}
```

Very noticeable is that `comments` is an empty list. In normal circumstances, these should contain at least the first comment of the user whom opened the note.

I suspect that this comment got redacted because of spam or personal data.

Also note that visiting the URL of the note (as linked above) results in an error page.

My request is to not include these rogue notes in this endpoint. I'm currently filtering them out client side.

### Screenshot(s) or anything else?

Originally reported here: https://github.com/pietervdvn/MapComplete/issues/2299

![](https://private-user-images.githubusercontent.com/1466478/391722174-59b8a020-41da-4867-aeab-ae59cc1e36cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzAyMjQsIm5iZiI6MTczMzMyOTkyNCwicGF0aCI6Ii8xNDY2NDc4LzM5MTcyMjE3NC01OWI4YTAyMC00MWRhLTQ4NjctYWVhYi1hZTU5Y2MxZTM2Y2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMTYzMjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWE1MWNkNDY0N2FiODIyNjJlZTlhYmY0OTI2NjlmMDg1YmI3ZjY0Y2Q4N2Q0NGUwNDQwMDQ4MzRmNjg4NWMzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rCe6Xr1mTZkV9Z0Vvis2alZ2r1vlY9f53btZI_-73uU)

**Comment by tomhughes** [comment]
More likely the user has been deleted and there's already a ticket for that.

**Comment by AntonKhorev** [comment]
#2146

**Comment by tomhughes** [comment]
This is just the API version of #2146.
