### ISSUE TITLE
Dark mode preference not respected after OAuth expiry

### ISSUE THREAD

**Issue by hlfan** [openstreetmap/openstreetmap-website#5407]
### How to reproduce the issue?

1. Have color scheme preference set.
2. Have login expire.
3. Website doesn't respect color scheme preference anymore.

### Screenshot(s) or anything else?

Could be fixed by not relying on inserting the data-bs/map-theme flags on the server side and check against a cookie/localStorage

**Comment by HolgerJeromin** [comment]
It is an known issue that not-logged-in users have no settings to change that.
So this is a duplicate to one of the open issues

**Comment by AntonKhorev** [comment]
What does it have to do with OAuth?

**Comment by gravitystorm** [comment]
I think this is unrelated to OAuth. I belive it's another way of asking for non-db preferences, so I'm closing this in favour of #5324
