### ISSUE TITLE
Menu overlapping on Opera with sidebar opened

### ISSUE THREAD

**Issue by sabas** [openstreetmap/openstreetmap-website#559]
Just reporting from Italian FB page
Opera 12.16 build 1860, Kubuntu 13.10, screen resolution 1280x800

![1472096_10202634080278621_634222147_n](https://f.cloud.github.com/assets/1304918/1649133/7ac93234-59e4-11e3-82e1-f1222f6b1581.jpg)

**Comment by gravitystorm** [comment]
I think this issue is fixed. In the current situation, the menu is drawn in the requested language, and then measured, before being hidden if it's too large. This means that it doesn't matter how long the translated labels are, since it will adjust the breakpoint automatically.
