### ISSUE TITLE
Deleted users still show up as hyperlinks in notes

### ISSUE THREAD

**Issue by emacsen** [openstreetmap/openstreetmap-website#579]
If there is a note created by a user who is then subsequently deleted (eg for creating note spam) then the notes still have the old display name which is hyperlinked.

Instead, we should probably replace this with [DELETED] or something similar.

Even better would be that notes where the deleted user is the only author being automatically hidden.

**Comment by AntonKhorev** [comment]
This is no longer true. Notes and their comments by deleted users are hidden, which currently leads to a bunch of other bugs. Actually replacing with [DELETED] would have helped to avoid these bugs.

**Comment by mmd-osm** [comment]
Closing as per @AntonKhorev's comment above.
