### ISSUE TITLE
When looking at a user's changeset history it's less obvious to see which changeset is highlighted in both the list and on the map than previously

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/openstreetmap-website#588]
The "highlight colour" used for both is now an off-white instead of the previously more obvious yellow.

It's no longer possible to easily link changesets in the list to changesets on the map and vice versa.

**Comment by danieldegroot2** [comment]
cc: @SomeoneElseOSM @gravitystorm

**Comment by SomeoneElseOSM** [comment]
As @AntonKhorev noted last year, it was yellow (again?) then and is still yellow now.
