### ISSUE TITLE
Print preview on "notes" (and at least some other object view) pages

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/openstreetmap-website#607]
I've just added

http://www.openstreetmap.org/note/82427

and had a look at it in "print preview".  The bottom of the page looks like this:

![ppreview](https://f.cloud.github.com/assets/5311740/1666059/945a6192-5c40-11e3-8fcb-daf15e2415b7.png)

So the map's displayed, but there's no text from the note.  That's on Firefox 25.0.1 on Windows 7.  On Chrome on Windows 7 the map's bigger but there's still no note text.

**Comment by AntonKhorev** [comment]
fixed in #4184

**Comment by mmd-osm** [comment]
Closing as per previous comment by @AntonKhorev
