### ISSUE TITLE
Add view pages for specific versions

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/openstreetmap-website#662]
Frequently I need to link to a specific version of an object. Currently what I have to do instead is link to /history, e.g. http://www.openstreetmap.org/way/252421610/history

It would be useful if http://www.openstreetmap.org/way/252421610/1 were to display version 1 of that way

**Comment by mmd-osm** [comment]
This has been implemented in #4480, respective URL is: https://www.openstreetmap.org/way/252421610/history/1
