### ISSUE TITLE
increase message body field width

### ISSUE THREAD

**Issue by richlv** [openstreetmap/openstreetmap-website#665]
in the previous design, when sending an internal message, body field was wider. in the new design it is more narrow, making message composing and reviewing a bit harder. increasing width to the previous size or so would be preferred.

while many browsers nowadays allow to change field size anyway, having a wider default would be preferred, and in this case increasing width results in "Parsed with Markdown" block overlapping with the message body field :)

**Comment by mmd-osm** [comment]
Ok, this issue is old, the Opera version is no longer around. Closing.
