### ISSUE TITLE
Bouncing map in Chrome when it wants to translate

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/openstreetmap-website#687]
I've had this a couple of times, but haven't reproduced the exact sequence that got me to this state.

I end up on a page like http://www.openstreetmap.org/changeset/16312254#map=13/-22.3864/-42.2706 which Chrome offers to translate for me, changing the page URL to http://www.openstreetmap.org/changeset/16312254#map=13/-22.3863/-42.2706. The process of changing the URL removes the translate bar, which then changes the URL back to the first one, and repeat.

**Comment by mmd-osm** [comment]
This issue is very old, and i can't reproduce it anymore. Even if so, it's most likely outside of our control.
