### ISSUE TITLE
Clicking on logo while changeset view loading zooms you out

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/openstreetmap-website#692]
To reproduce

Go to http://www.openstreetmap.org/history#map=17/49.24456/-123.12284
Click on the logo before all the changesets have loaded
You end up at http://www.openstreetmap.org/#map=2/-21.7/0.0

If you wait for loading to be complete, you go to http://www.openstreetmap.org/#map=17/49.24456/-123.12471.

Another oddity is that after landing on the zoomed out map, if you press back you go to a zoomed out history, not the previous page.

**Comment by mmd-osm** [comment]
I can reproduce the issue, though I find it a bit too niche to look into. Maybe when we're down to 50 remaining issues. Closing here.
