### ISSUE TITLE
Relation membership should be on top of detail pages

### ISSUE THREAD

**Issue by daganzdaanda** [openstreetmap/openstreetmap-website#794]
Hi!

When you look at the details of a /node /way or /relation, if it is a member of one or many relations, the info is given at the bottom of the list. Since the list can be very long, I would like to see the relations on top of the other information. So the preferred order would be  relations > ways > nodes

E.g., on a way, relation membership is usually more important than the 100s of nodes that are part of the way. 
On a relation, it would also be helpful to see if it is a member of another relation first.
Nodes are the least concern, since they can only be members of bigger things and don't have members... but for consistency's sake, the order should be as above.

(Sorry if this is a duplicate, I searched but did not find anything)

**Comment by daganzdaanda** [comment]
I just thought about this again... It seems the idea is well liked, and we have a piece of code already that should do it. So I tried to be brave and implemented the code from @danstowell in a pull request. I never did that before, so please excuse any mistakes.

**Comment by tomhughes** [comment]
That's not a pull request, it's just a commit in your tree ;-)

**Comment by daganzdaanda** [comment]
Ah, ok :-) 
So what do I need to do to make that into a pull request?

**Comment by rmikke** [comment]
YES!
I came here to propose just this, but a little bit extended.
And I think all the relations should be promoted, not only multipolygons. 
Try to see from end user perspective. What is more important about, say, a road? That it is part of this and this route, or a list of its nodes? And it's not only an end user. newer mappers won't even see relations that are hidden behind a boring list of nodes.

So, again, YES, relations -> ways -> nodes, I think.

**Comment by daganzdaanda** [comment]
I updated the pull request to make the same change for the relation view.

> And I think all the relations should be promoted, not only multipolygons.

The code does not make a difference about the type of relation at the moment, as far as I can tell. My PR only changes the order of the details, so that the relation-info comes first.
