### ISSUE TITLE
The 'Where am I?' button doesn't give me my right location

### ISSUE THREAD

**Issue by raosudha89** [openstreetmap/openstreetmap-website#815]
I tried using the 'Where am I?' option inside the search button and it said I am in Germany (attached is the screen shot) when I am in US!
![openstreetmapbuglocation](https://cloud.githubusercontent.com/assets/7291397/4659731/6a08db8e-5510-11e4-8eb5-0dd6dfca3171.png)

**Comment by rudolfmayer** [comment]
I would advocate renaming the "Where am I" button, as others also pointed out, the text and the functionality don't match well.
