### ISSUE TITLE
Display number of discussion comments in changeset list

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/openstreetmap-website#820]
Moved from https://github.com/openstreetmap/openstreetmap-website/pull/772#issuecomment-60828176

> This seems like a great idea. One small improvement I'd suggest is to show the number of comments in the change set list so you can see at a glance any changesets which may be controversial
> ![](https://cloud.githubusercontent.com/assets/207287/4816801/ed637652-5ee2-11e4-999f-b69acd9d00d3.png)
> Would it also be beneficial to list a user's changeset comments somewhere in their user profile?

**Comment by AntonKhorev** [comment]
Isn't it implemented already?

**Comment by danieldegroot2** [comment]
This feature has since been implemented in https://github.com/openstreetmap/openstreetmap-website/commit/91bd0b4b12469746a6e867332262907e35b2a013 .

cc: @gravitystorm
