### ISSUE TITLE
Subscribe users to their old changesets discussions

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/openstreetmap-website#823]
*Was: Users are not subscribed to their changeset discussions by default*

So when somebody comments a changeset, the user who made that change isn't notified. And the discussion ends there.

Run a script that subscribes users to all discussions for their old changesets (prior to November 2014).

**Comment by tomhughes** [comment]
Fixed in 821a22c6073d4b50ae7038e9c1aacbb5e68cd55a which has been (in slightly modified form to avoid lock contention) run on the live database over the last 36 hours.

**Comment by Zverik** [comment]
Thanks!
