### ISSUE TITLE
make sidebar vertical padding consistent

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/openstreetmap-website#831]
The  padding of overpassquery result "#sidebar_content .query-results ul li" and changesets "#sidebar .changesets li" have
"padding-bottom: 15px;padding-top: 15px;"
while the nominatim result ".inner12" has only 
"padding-bottom: 10px;padding-top: 10px;"

with the nominatim padding we have more results visible, while still looking nice.

Perhaps the full object tree should be more consistent (and the css even merged):
Nominatim results have (li)(p class="inner12 search_results_entry clearfix")
Overpass results have (li class="query-result")(p)
changeset results have (li class)

**Comment by mmd-osm** [comment]
This issue is very old. It seems we have the same padding for both results today. Closing.
