### ISSUE TITLE
United States English spelling error

### ISSUE THREAD

**Issue by mikeshenson** [openstreetmap/openstreetmap-website#836]
There is an United States English spelling error in:
https://www.openstreetmap.org/user/USER/oauth_clients

The "s" in "Authorised" should be a "z" Authorized

![screenshot from 2014-11-17 08 51 11](https://cloud.githubusercontent.com/assets/7337270/5071552/70b60386-6e37-11e4-86e5-68ace47e4355.png)

**Comment by mmd-osm** [comment]
I'm closing this one. The screenshot abobe refers to the OAuth 1.0a config, which will go away soon anway, and won't be fixed anymore.

The new OAuth 2.0 based screen uses "My Authorized Applications" as page header: https://www.openstreetmap.org/oauth2/authorized_applications
