### ISSUE TITLE
Allow users to subscribe to 'notes' without having to comment on them

### ISSUE THREAD

**Issue by rickmastfan67** [openstreetmap/openstreetmap-website#840]
With the new changeset feature where you can leave comments (#772), or subscribe to one to see if somebody else leaves a comment, I would love to see the 'subscribe/unsubscribe' feature brought over to the Notes as well.

This would be very helpful if, say, a bridge had to have an emergency closure because a pier settled and somebody else created a note about it before you did.  As of right now, you would then be FORCED to comment on said note just to be subscribed to e-mail notifications.  It would be a lot easier if there was just a button to subscribe to it like changesets have now so you weren't forced to make a comment if you didn't want/need to.

**Comment by donaldrnoble** [comment]
I agree this would be a nice feature, but it is relatively easy to make a short moment if you are interested, so not a massive issue

**Comment by gravitystorm** [comment]
Implemented in https://github.com/openstreetmap/openstreetmap-website/pull/5284, https://github.com/openstreetmap/openstreetmap-website/pull/5304, https://github.com/openstreetmap/openstreetmap-website/pull/5310, https://github.com/openstreetmap/openstreetmap-website/pull/5314, https://github.com/openstreetmap/openstreetmap-website/pull/5346.
