### ISSUE TITLE
Allow option to attach personal note to friend

### ISSUE THREAD

**Issue by ethan-nelson** [openstreetmap/openstreetmap-website#847]
When adding someone as a friend, it would be great to have an option to assign a brief note/label to that person visible only to the adder.

For example, if someone is mapping in an area I frequent in Chicago, IL, I could put "maps near yogurt in Naperville" to remind me in the future of how I know them or why I added them.

**Comment by mmd-osm** [comment]
I tend to close this issue since nobody has suggested a similar feature in the last 10 years or so. Also there are no comments or upvotes.
