### ISSUE TITLE
Not all right-hand-side buttons are available on small screens

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/openstreetmap-website#849]
The RHS buttons available on small screens are just chosen top-down.  It'd be nice if they were chosen for suitability on a small screen (or even better, scrollable so you can get at them all).  For example, yesterday I wanted to ask the question "what is that feature" and was disappointed that the new button for that was some way off the bottom of the screen:

![img_20141201_162408](https://cloud.githubusercontent.com/assets/5311740/5249063/14ebea7e-7978-11e4-8ee4-94ff01b0ec85.png)

Top to bottom, on a small phone screen, I'd suggest that:

Zoom in:  Less useful (people will probably have "pinch to zoom")
Zoom out:  Less useful
Show my location:  Really Useful
Layer Switcher:  Useful
May Key:  Useful
Share:  Not useful
Add a note:  Useful
Query:  Really Useful

**Comment by vincentdephily** [comment]
FWIW I'd rate "map key" less usefull than "share".

How small a screen do we want to cater for ? Would it be reasonable to shrink the buttons and remove the gap between them, or do we want a more future-proof solution such as scrolling or a "more buttons" button ?

**Comment by SomeoneElseOSM** [comment]
@vincentdephily Notwithstanding tomhughes' entirely valid comment above, but with the perfect the enemy of the good enough and all that, I'd like to suggest down to 720 vertical (because that's what's in front of me) or maybe even 320 (smartwatch size)?
