### ISSUE TITLE
 OSM.org Browsing Help unfindable

### ISSUE THREAD

**Issue by a-pirard** [openstreetmap/openstreetmap-website#871]
One way to promote OSM is to teach the general public to write to more people things like [I'll be waiting for you here] (http://www.openstreetmap.org/way/5013364?mlat=48.85783&mlon=2.29513#map=18/48.85826/2.29478) and OSM links (or pictures) in Web pages or signatures.  But they must be helped using OSM.org browsing.
Generally, a program has a direct Help menu to help using it, and even a F1 key assignment.
OSM.org does not.  The page Help menu leads to general documentation deep in which is the [Browsing Help page] (http://wiki.openstreetmap.org/wiki/Browsing), 3 clicks away if you know where it is (a tiny [Browse](http://wiki.openstreetmap.org/wiki/Browsing)), at least 8 and much distraction if you know there is one, and a countless number if you don't.  **They don't find it**.
The request is to have a separate, direct Browsing Help menu and possibly a F1 key.
I have substantially but uselessly improved that page.  I'm waiting for being useful to continue.

**Comment by tomhughes** [comment]
What exactly are you asking for? What is "browsing help" exactly?

**Comment by tomhughes** [comment]
I'm sorry but I've just looked at that wiki page, and in no way is it suitable for introducing the general public to use the site - it's full of all sorts of hacky low level details.

Our web site is not intended to be a "google maps" style end user mapping site, so I really think this request is out of scope. Our target audience is mappers. Certainly our help page coud be improved, and I'd be happy to take pull requests to do so, but please don't just add links to random wiki pages full of years works of acreted nonsense.

**Comment by a-pirard** [comment]
On 2015-01-12 23:56, Tom Hughes wrote :
>
> I'm sorry but I've just looked at that wiki page, and in no way is it
> suitable for introducing the general public to use the site - it's
> full of all sorts of hacky low level details.
>
> Our web site is not intended to be a "google maps" style end user
> mapping site, so I really think this request is out of scope. Our
> target audience is mappers. Certainly our help page coud be improved,
> and I'd be happy to take pull requests to do so, but please don't just
> add links to random wiki pages full of years works of acreted nonsense.
>

I am extremely disconcerted and completely stunned by this answer.
I'm acquainted with persons writing publications for hundreds of people,
who consequently could advertise OSM widely by referring to places by
writing links to the OSM.org main map <http://www.openstreetmap.org> but
who were unable to do so, less to embed a picture.
I improved the section Adding a Marker
<http://wiki.openstreetmap.org/wiki/Browsing#Adding_a_Marker>, and some
other parts of that page plus French translation, showed it, and they
were suddenly able to make links. They asked why [the heck] that page is
not highlighted as the help page of that map.
And now you denigrate my work, and that of all who contributed to that page.
You call the successful, very clearly explained and strictly necessary
procedure to make a link "full of all sorts of hacky low level details".
You say that the OSM.org map audience is mappers and not the general
public. (The cycle map to be used between mapping sessions, probably).
And you extend the alleged crappy nature of that page to its links and
maybe all of the OSM wiki, being full of nonsense.
Your remarks belong to the destructive nature of many comments instead
of constructive remarks for improvement in a devoted cooperation spirit.

Obviously, I will not continue to improve OSM documentation before the
help page of the map is made visible to those who use the map and need
it, and before I stop receiving destructive comments and being insulted.

**Comment by joostschouppe** [comment]
Sounds like a good idea to me. Of course, my ideas for OSM.org are sometimes called [insane](https://github.com/openstreetmap/openstreetmap-website/issues/950), so maybe you won't like my support, André.

**Comment by simonpoole** [comment]
@joostschouppe a good idea except that the world has moved on in the last 10 months and the help tab now contains pointers to all relevant help sources, including the "Beginners Guide" which contains the above referenced section on "Browsing" (three clicks might be considered a lot, but then there is not really that much on the website which is not immediately clear)..

**Comment by joostschouppe** [comment]
It is a good effort, I agree. There is something slightly off with the
logic though: it seems to assume that contributing to the map comes before
using the map. I do know that that has happened, but I think almost any
newbie will be user before being

2015-11-01 23:15 GMT+01:00 Simon Poole <notifications@github.com>:

> @joostschouppe <https://github.com/joostschouppe> a good idea except that
> the world has moved on in the last 10 months and the help tab now contains
> pointers to all relevant help sources, including the "Beginners Guide"
> which contains the above referenced section on "Browsing" (three clicks
> might be considered a lot, but then there is not really that much on the
> website which is not immediately clear)..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openstreetmap/openstreetmap-website/issues/871#issuecomment-152869569>
> .
>



-- 
Joost @
Openstreetmap <http://www.openstreetmap.org/user/joost%20schouppe/> |
Twitter <https://twitter.com/joostjakob> | LinkedIn
<https://www.linkedin.com/pub/joost-schouppe/48/939/603> | Meetup
<http://www.meetup.com/OpenStreetMap-Belgium/members/97979802/> | Reddit
<https://www.reddit.com/u/joostjakob> | Wordpress
<https://joostschouppe.wordpress.com/>

**Comment by a-pirard** [comment]
@joostschouppe: I appreciate your support.  Sometimes somebody understands.

@simonpoole: as I replied on Tagging@osm.org where you accused me to be out of topic, **you** are out of topic. Here and there, the subject is informing the general public like in the Browsing page that is nohow to find. And you're showing the "Beginners Guide" that's made for the mapper.
