### ISSUE TITLE
Map key contains misleading entries

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/openstreetmap-website#882]
I stumbled across this forum post

http://forum.openstreetmap.org/viewtopic.php?pid=481542#p481542

and thought "that can't be right", but sure enough https://github.com/openstreetmap/openstreetmap-website/blob/068471fc0e797428c48b8917d62fe7db0331cc65/config/key.yml does seem to contain an entry for "unsurfaced" (and also "byway" which also isn't rendered) - unless I've misunderstood where the map key for the standard layer comes from.

Arguably this could be considered an openstreetmap-carto problem rather than an openstreetmap-website one because presumable any change to "what gets rendered at what layer" there should involve an equivalent change to the map key here.

**Comment by tomhughes** [comment]
I just whatever the cartographers give me there - if you want it updated it's probably best to take it up with them.

**Comment by SomeoneElseOSM** [comment]
Yes - makes sense - I've created https://github.com/gravitystorm/openstreetmap-carto/issues/1268 .

**Comment by joostschouppe** [comment]
Wouldn't it make sense to have the map key link through to this page http://wiki.openstreetmap.org/wiki/Standard_tile_layer , at least as long as the carto issue isn't closed? Might make sense permanently, as it allows for a bit more background info.
