### ISSUE TITLE
Automatically add addr:place

### ISSUE THREAD

**Issue by hope15** [openstreetmap/openstreetmap-website#885]
Most small villages in Austria have street names, but they don't match with the name of the street that corresponds with the house number. 

E.g. 

http://www.openstreetmap.org/#map=19/46.89243/10.50261
The name of the street is "Mittergasse" but the address for the building is "Nauders (Dorf) 61"

Unfortunately this happens quite often and most house numbers got added with the addr:street + addr:housenumber tag. As there is not street with this name in the immediate vicinity, the housenumber can not be found using the search.

I wouldn't mind to add some addr:place tags, but that problem occurs in most of the villages here and I'm simply not able to change it for all of them.

Therefor my suggestion that the addr:place tag gets automatically added with the name of the addr:street tag if there is no street with the same name in the proximity.

(Another possibility would be to allow the search to find the house number with the street name no matter if the street does even exist in the village)

**Comment by tomhughes** [comment]
What does this have to do with the web site code?

**Comment by tomhughes** [comment]
To explain a bit more clearly, if you want search to work different you should report it at https://github.com/twain47/Nominatim, if you want the names rendered differently then you should report it at https://github.com/gravitystorm/openstreetmap-carto, but I don't any way that this relates to the code in this repository.

In all honesty it sounds like the data is just wrong, and the correct approach is to fix the data - the `addr:` tags should denote the address, and if the address of a build is not street based then it shouldn't be tagged as if it is.

**Comment by hope15** [comment]
Well thanks for the info, gonna ask there for a solution. 

To your approach, things here in Austria are a bit different than in other countries. The houser numbers were added later on and the street names (at least in smaller villages) aren't that important. To fix that problem the people decided to add one main street name, which is valid for the whole village and each building gets a house number. Basically there are just two street names which are used, the first one is the name of the village as street name and the second one is "Dorf" which translates into "Village".

The addr:street tag is actually correct but it's not the name of the street that is in front of the building.

**Comment by tomhughes** [comment]
Well `addr:street` should be the street name that appears in the address, even if that's not the street the house is on. At least that is my understanding, but you would be better discussing this with the Austrian OpenStreetMao community who will doubtless have a better handle on these things.

Try the mailing list (https://lists.openstreetmap.org/listinfo/talk-at) if you want to reach them.
