### ISSUE TITLE
The routing "start/end here" icons is are  initially opaque

### ISSUE THREAD

**Issue by emj** [openstreetmap/openstreetmap-website#888]
This is a trivial issue for  #716 

If I drag the "green icon" beside the "from" textbox the background will not be transparent until you place it on the map.

The background then becomes transparent on further drags.

http://jsrouting.apis.dev.openstreetmap.org/directions

**Comment by danstowell** [comment]
I can't reproduce this on Firefox v35 on Ubuntu.

**Comment by emj** [comment]
True! Works for me on FF as well, doesn't work on Chrome 41 though.

**Comment by tomhughes** [comment]
Please don't raise issues here for unmerged code.
