### ISSUE TITLE
Missing section to share a link on Firefox (Windows)

### ISSUE THREAD

**Issue by britiger** [openstreetmap/openstreetmap-website#889]
Hi,
if I (and also other people) use the Firefox on Windows (e.g. 31.2.0 ESR) to share a Link it is not possible. There is only the section to share an image (see screenshot), not the section for creating a link. I've testet Chrome and IE on Windows and also Firefox on Linux, there it always works. Only the combination Firefox on Windows don't show the section for sharing a link.  It was reproduceable on different computers by different users and networks. I don't know if it makes a difference, the language we used was german.

![share](https://cloud.githubusercontent.com/assets/2057760/6055660/054523aa-ad04-11e4-9237-470627ab1fa7.png)

**Comment by tomhughes** [comment]
This is a problem with your browser, or your ad blocker, or something. It works find for me in firefox - see previous ticket at https://trac.openstreetmap.org/ticket/5263 where I posted an image.

**Comment by HolgerJeromin** [comment]
Works with 35.0.1 on Windows. I did not test the ESR, but i suspect an adblocker, too.
