### ISSUE TITLE
Google is removing OpenID 2.0 support on 20th April

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/openstreetmap-website#897]
Logging in with a Google OpenID displays this message:

> OpenID 2.0 for Google accounts is going away.
> Developers should migrate to OpenID Connect by April 20, 2015.

Which I assume is going to affect us, or they wouldn't show it...

Volunteers wishing to investigate what needs to change would be gratefully accepted...

**Comment by tomhughes** [comment]
More information at https://support.google.com/accounts/answer/6135882 and https://developers.google.com/accounts/docs/OpenID#shutdown-timetable with details of the new system at https://developers.google.com/accounts/docs/OpenIDConnect.

Short version is that it's a completely new system based on OAuth and not really OpenID at all.

At least that means that implementing it might help us on the road to Twitter support, but it means it is probably a big job.

**Comment by tomhughes** [comment]
Preliminary work to resolve this is in #906 which adds the framework for multiple authentication backends.

Note that using the new OAuth 2 based system requires registering the application with Google as with Facebook and MS Live so it would be helpful if somebody could look at any legal issues involved there and get LWG or whoever to clear it.

**Comment by simonpoole** [comment]
@tomhughes I've hat a look at it and forwarded the request to the LWG, as far as I can see the only relevant document is their normal API ToS which has similar issues as the FB one, aka we probably can proceed with the risk that the service could potentially be disabled (and a plan B for that should exist).

**Comment by simonpoole** [comment]
I've reviewed the relevant google terms and can find nor real qualitive difference to FB and other similar ToS. In line with the LWG here https://docs.google.com/document/u/0/d/1uemhXWKwbu3RNjAWcG0R-nEFaN1FHjZl1McFwjXkNSc/pub (item 10). agreeing to the google terms is OK.
