### ISSUE TITLE
Routing dialog boxes impacts lat/lon

### ISSUE THREAD

**Issue by kerosin** [openstreetmap/openstreetmap-website#899]
Hey,

I just noticed the following:
When opening and closing the routing dialog box, the lat value changes on the last decimal place.

![gif of opening and closing routing dialog box affecting lat/lon](http://gifyu.com/images/hq8tm.gif)
So the mapview moves a little every time opening/closing this new dialog.
System: Chrome 40 on Ubuntu 14.04 64bit

Would be nice to keep the mapview constant, so that users are not confused.

Thanks

**Comment by ximex** [comment]
Tested on Firefox & Chromium on Ubuntu Gnome -> no problem

**Comment by kerosin** [comment]
Can't reproduce anymore with Chrome (strange). Still reproducable with Midori. Sorry no possibilities to test it on any other platform. Firefox worked fine out of the box.

**Comment by ximex** [comment]
maybe some caching problem?

**Comment by kerosin** [comment]
Yep, seems to be a caching problem. After removing browser cache+data everything works fine on all three browsers.
Thanks!
