### ISSUE TITLE
Routing over areas: display failure? routing failure? router<->OSM failure?

### ISSUE THREAD

**Issue by neiljp** [openstreetmap/openstreetmap-website#900]
URL:
http://www.openstreetmap.org/directions?engine=graphhopper_foot&route=51.86268%2C0.95445%3B51.86259%2C0.95594#map=16/51.8633/0.9544

This is somewhat of an indirect route - presumably it doesn't route via the car-park area? Is this a graphhopper limitation or how it is being used by OSM?

The same search on mapquest also has a similar situation; it sort of provides a routed solution, but does not provide the path:
http://www.openstreetmap.org/directions?engine=mapquest_foot&route=51.8627%2C0.9544%3B51.8626%2C0.9559#map=19/51.86267/0.95543

**Comment by tomhughes** [comment]
We display what the engine gives up - you will have to take this up with the developers of those engines.

**Comment by danstowell** [comment]
@neiljp it's quite simply an issue for graphhopper to consider - you can prove this to yourself by going to the graphhopper website and searching for the [exact same route request](https://graphhopper.com/maps/?point=51.8627%2C0.9545&point=51.8626%2C0.9559&vehicle=foot&elevation=true&layer=Lyrk).

**Comment by neiljp** [comment]
It is an issue for graphhopper (and mapquest) to consider, but using it on the main site is going to add a tendency for people to map for the router, ie. add 'fake' paths between endpoints of paths/roads in order for routing to 'work' using these advertised routers. For example, I could 'cheat' and add routes between the 3 or so entrances to that car park area to allow foot traffic, but I'm fairly sure that is undesirable.

**Comment by vincentdephily** [comment]
https://github.com/graphhopper/graphhopper/issues/82
