### ISSUE TITLE
Routing directions mentioning that roads are unnamed

### ISSUE THREAD

**Issue by kerosin** [openstreetmap/openstreetmap-website#904]
Directions made by car routes with OSRM are explicitly calling streets without names "unnamed".

![image of routing directions with OSRM on osm.org - directing via unnamed road](http://i.imgur.com/Czd8jMD.png)
see live: http://bit.ly/1FHR6O9

Unsure if this is a OSRM issue, but seems to be a frontend thing. osrm.at and osrm.at frontend2 is not mentioning unnamed roads.

this is confusing users (read some comments about this) and doesn't provide any valuable information

**Comment by tomhughes** [comment]
All directions come directly from the upstream routing engine.

**Comment by kerosin** [comment]
So opening a issue at [repository osrm-backend](https://github.com/Project-OSRM/osrm-backend) might be more expedient? Might this be configuration problem or are you getting directions directly from a OSRM server?

**Comment by tomhughes** [comment]
We're using the project-osrm.org server.

**Comment by tomhughes** [comment]
It looks we are deliberately saying "unnamed" when the server doesn't provide a name while the OSRM UI leaves the name out  - see https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/javascripts/index/directions/osrm.js#L72.

**Comment by tomhughes** [comment]
I don't think mentioning the fact that the road has no name is a problem as such, but I've changed it to say `unnamed road` rather than `(unnamed)` which I think looks better.

**Comment by mmd-osm** [comment]
I'm not sure if https://github.com/tomhughes/openstreetmap-website/commit/1729a680ac24bcf9fc45b97abe0228e41305bd57 causes some regressions here or if it's something completely different. At least when requesting route instructions with locale set to German, street names are no longer shown. English version looks ok, though.

Some reference screenshots:

English:
![g2](https://cloud.githubusercontent.com/assets/5842757/8577236/9395e7ea-25a7-11e5-8c66-958206c6b7c2.png)

German:
![g1](https://cloud.githubusercontent.com/assets/5842757/8577240/98a85fa6-25a7-11e5-8bf0-9140415123e3.png)

Link to query: http://www.openstreetmap.org/directions?engine=osrm_car&route=51.5216%2C6.9292%3B51.4572%2C7.0115

**Comment by tomhughes** [comment]
@mmd-osm the translations likely need updating.

**Comment by mmd-osm** [comment]
Would it be complete nonsense to fall back to the old behaviour unless `%{name}` is present in the translation. I can imagine that it might take some time until all 50+ languages get an update. IMHO showing a name (possibly out-of-line) is probably still slightly better than showing no street name at all for the time being.

**Comment by tomhughes** [comment]
No it wouldn't be nonsense, it would be a lot of work.

What I should really have done is to change the translation names, so that it would fallback to english until they were retranslated, but again it was a lot of work.

**Comment by mmd-osm** [comment]
Thanks, I'm getting your point. I don't seem to find a way in the [I18n lib](https://github.com/fnando/i18n-js/blob/master/app/assets/javascripts/i18n.js) to deal with missing variable names. I can only think about some crazy workarounds like the following (not tested) or even checking for `%{name}` in `I18n.t(TURN_INSTRUCTIONS[instCodes[0]]`. Maybe others have some better ideas to ease the transition phase without causing lots of work.

```Javascript
            var name = s[1] ? "<b>" + s[1] + "</b>" : I18n.t('javascripts.directions.instructions.unnamed');
            if (instCodes[0] === "11" && instCodes[1]) {
              instText += I18n.t('javascripts.directions.instructions.roundabout_with_exit', { exit: instCodes[1], name: name } );
            } else {
              var transl1 = I18n.t(TURN_INSTRUCTIONS[instCodes[0]], { name: name });
              var transl2 = I18n.t(TURN_INSTRUCTIONS[instCodes[0]]);
              if (transl1 === transl2) {           // fallback to legacy mode where name variable is missing
                instText += transl2 + " " + name;
              } 
             else
                instText += transl1;
            }
```

**Comment by tomhughes** [comment]
No, we are not doing anything crazy like that - apart from anything else we would never be able to remove it.

The old way was technically buggy anyway, because different language may need to put the road name in different places - glueing strings together is bad for i18n.

**Comment by tomhughes** [comment]
I've pushed d28ae2ad0ab336a5c1f1b7152945b30a4e2cfd02 now to rename the strings.

**Comment by mmd-osm** [comment]
Thanks a lot! The fallback to English looks way better now,
