### ISSUE TITLE
Marker icons missing

### ISSUE THREAD

**Issue by malenki** [openstreetmap/openstreetmap-website#910]
When sharing the map with "include marker", the icons
http://www.openstreetmap.org/images/marker-icon.png 
and
http://www.openstreetmap.org/images/marker-shadow.png
are missing.

Reported by MCMic on IRC

**Comment by tomhughes** [comment]
Is this not the same as #909 that I fixed a few hours ago? (those URLs are wrong by the way, and are not expected to work).

**Comment by tomhughes** [comment]
Oh, you mean when placing the marker, not on the exported embed.html?

**Comment by malenki** [comment]
When I try to place the marker, neither shadow nor marker are displayed.
The shared link then shows a map with a marker but without shadow.
Right-clicking the place holders for the missing icons and copying the image URL gives the URLs mentioned above.
Is your change live already since I still have the mentioned issue?

**Comment by MCMic** [comment]
Seems fixed to me now, both marker and shadow are showing.
