### ISSUE TITLE
Chrome: dragging icon for routing shows white background (instead of transparence)

### ISSUE THREAD

**Issue by kerosin** [openstreetmap/openstreetmap-website#912]
Hey,

Dragging the start/endpoint marker of the routing feature has a white background in Google Chrome browser.

That's how it looks like (without cursor):
![icon of routing start point with white background](http://i.imgur.com/xroyrvs.png)

Guess fixing this has minor priority.

Thanks in advance!

**Comment by tomhughes** [comment]
Sounds like a bug in chrome to me. It's fine in firefox, and the image definitely has an alpha mask with a transparent background.

**Comment by tomhughes** [comment]
@kerosin does this only happen when dragging from the search box? or when dragging a marker this already on the map as well?

**Comment by kerosin** [comment]
Also visible on WebKitGTK+ browser Midori (this time black background):
![](http://i.imgur.com/EnXKUdH.png)
Will test IE in VirtualMachine...

@tomhughes happens in both cases.

**Comment by tomhughes** [comment]
My commit probably won't help then...

**Comment by kerosin** [comment]
Couldn't reproduce this on Windows IE11 or Chrome... Maybe related to Linux? Can anybody else reproduce this?

**Comment by kerosin** [comment]
Chrome bug on Linux -> for more see https://code.google.com/p/chromium/issues/detail?id=463617
