### ISSUE TITLE
Only display the last requested route

### ISSUE THREAD

**Issue by emj** [openstreetmap/openstreetmap-website#913]
If you make two routes quickly it's not given which of these will en up being displayed.

1. make a long route which takes 10 seconds to finish (I tried with mapquest )
2. make a short route

result: 

1. the short route will display almost directly
2. 5 seconds pass
3. the long route will be displayed 
4. the end points of the short route will be displayed

**Comment by tomhughes** [comment]
I suspect this is going to be very hard because there are three independent code bases (for the three different providers) that would need to co-operate.

**Comment by tomhughes** [comment]
You're obviously faster than me at interacting with it as I find it almost impossible to achieve this!

**Comment by tomhughes** [comment]
I think I've managed to fix this, though it's quite hard to trigger...

**Comment by emj** [comment]
I got very good (slow) results by using mapquest and routing from "Stockholm, Sweden" to "paris, France".  Thanks for the fix.

**Comment by tomhughes** [comment]
Well slow on the order of some seconds sure, but you still have to be quite quick to do another route before it finishes ;-)

I resorted to doing London to Beijing and then London to somewhere nearby...
