### ISSUE TITLE
small errors in OSRM routing directions in German language

### ISSUE THREAD

**Issue by kerosin** [openstreetmap/openstreetmap-website#915]
![](http://i.imgur.com/KeF5QG8.png)

There is a space missing in every OSRM instruction in German (only rechecked en which is fine) and instruction for roundabouts is a mix of German/English.

Should be something like this: "9. Im Kreisverkehr 3. Ausfahrt"

Thanks in advance!

**Comment by tomhughes** [comment]
It's completely useless to report things like this without giving us a way to reproduce it - assuming the bug is even in our code we need to know where you are routing from and to in order to be able to debug it!

**Comment by tomhughes** [comment]
The space thing is utterly weird. As best I can tell there is a newline there in the HTML which should collapse to a space when rendered, and it does in English but not in German.

**Comment by kerosin** [comment]
Basically choose a route where you need to cross a roundabout, e.g.http://www.openstreetmap.org/directions?engine=osrm_car&route=54.2864%2C9.6788%3B54.3047%2C9.6645#map=13/54.2965/9.6752&layers=N
(of course you need to switch language to de) 

Now it is saying: " 2. Im Kreisverkehr nehme[missing "de.javascripts.directions.instructions.exit" translation] K 27"
Seems like translation is missing

**Comment by tomhughes** [comment]
Oh that's a dependency bug when the javascript translations are changed that I haven't got around to finding a fix for yet... It should be fixed now.

**Comment by kerosin** [comment]
Okay, but still there is this strange mix, see  [this route](http://www.openstreetmap.org/directions?engine=osrm_car&route=54.28778%2C9.67845%3B54.28735%2C9.67907#map=19/54.28755/9.67861&layers=N)
![](http://i.imgur.com/xQeqCT6.png)
Couldn't find this on [translatewiki](https://translatewiki.net/) :/

**Comment by tomhughes** [comment]
The "exit" translation is new and won't appear on translatewiki until the next time they sync to us.
