### ISSUE TITLE
Make it more obvious that markers on routing feature are draggable

### ISSUE THREAD

**Issue by kerosin** [openstreetmap/openstreetmap-website#920]
> Good design of draggable elements should have at least some sort of visual cue of what can be dragged (and what can't), at least something to set it apart from other (undraggable) elements on the page

quoted from "HTML5 Unleashed" by Simon Sarris

suggestions:
- change cursor to grab or similiar for routing markers 
- when mouseover at marker: show a small tooltip that says something like "drag this marker to set a start point"

read a few comments that it wasn't clear to some users that those markers are draggable.

**Comment by claudiush** [comment]
Using Opera 27 the cursor changes when
a) above green route start or red route end markers: These can be moved
b) above blue route line: Dragging here just moves the map

Looks like a) already reflect what you asked for. If not. Can you please specify which behaviour you are asking for?

**Comment by HolgerJeromin** [comment]
The markers left to the "route from" and "route to" (not in map, but on the sidebar) could/should have the move or grab css cursor (via routing_marker class). 
The markers on the map have already a different cursor.

**Comment by kerosin** [comment]
Okay I will try to clarify. Instead of entering two search terms for start/end point, you can also drag both markers( from the upper left corner) on the map.
See:
![](http://i.imgur.com/bgmOxgV.gif)
This is not visible to users. There is no visual difference between these markers to any other static image on the website.
![](http://i.imgur.com/OpdO2i3.gif)

The case you mention with b) also doesn't make sense to me. Why change cursor on the blue line when there is no function or anything? It does the same as on the rest of the map.

**Comment by floscher** [comment]
@kerosin what do you think of #927?

**Comment by kerosin** [comment]
Good idea, but maybe it should be consistent with the cursor for markers on the map?
Maybe there could be also a visual clue before hoovering. Many apps/websites are using one of the two:
![](https://www.drupal.org/files/issues/draggable_2.png)
to show that items are draggable.
Tooltip could also give a good feedback for the user ;)
It's a bit of discussion - I'm not a ux/ui expert

**Comment by HolgerJeromin** [comment]
I think a tooltip on this markers would be nice, too. 

It could not be consistent to the markers on the map, because these have the "click" style (because the surrounding map has the drag cursor).

I can not find the code which adds the css class "leaflet-clickable" to the routing line. Perhaps this is the default for leaflet objects. This could be removed imo.

**Comment by kerosin** [comment]
Yes cursor:pointer seems to be default on Leaflet markers. So change cursor of markers on the sidebar to cursor:pointer? It is the same cursor like on the "go" button. Alternatively we could also choose a different cursor like  cursor: move on sidebar+map for the markers. 
`.leaflet-clickable {
  cursor: move !important;
}`
`.routing_marker { width: 15px; position: absolute; cursor: move; }`
> because these have the "click" style (because the surrounding map has the drag cursor).

This is cursor: -webkit-grab or cursor: -moz-grab; isn't it?
They would look very similar but not identical.

**Comment by floscher** [comment]
I've updated the pull request with `.leaflet-marker-draggable{ cursor:move; }` to make the cursors the same when hovering the marker on the map and in the sidebar.
I wouldn't like a tooltip additional to the cursor-change. But I'd like a small persistent visual clue near the marker or a infobox appearing only on first use.

**Comment by tomhughes** [comment]
We really didn't need an animated GIF to prove your bloody point. It was entirely clear what you mean without that.

**Comment by HolgerJeromin** [comment]
should we close this now?

**Comment by kerosin** [comment]
>It was entirely clear what you mean without that.

Obviously not - look at claudiush comment.

>We really

Who are talking about when you say we?

>should we close this now

Yep. I will try to a avoid small improvement suggestions via Github issues in the future. When I will have plenty time, I will try to make pull requests for small changes like this.
