### ISSUE TITLE
User blocks do not state the created date.

### ISSUE THREAD

**Issue by nomoregrapes** [openstreetmap/openstreetmap-website#923]
I'm viewing a block on a user and it displays the status ("Active until the user logs in" in this case) to say when it ends, but it does not state when it was created. This would be helpful when investigating an issue with others. I just said to a mailing list "but they are blocked it must have been noticed some time ago so delete their mistakes and get on with life"(paraphrase) to which I got the reply "[admin] might've put that block in after I sent a message [last night]".

**Comment by SomeoneElseOSM** [comment]
See also https://github.com/openstreetmap/openstreetmap-website/issues/907 (not quite the same, but similar).

@nomoregrapes , if you've got a question about a specific block, I or the person who applied the block can probably figure out the start date, or if not someone else at the data@osmfoundation.org address would be able to.
