### ISSUE TITLE
www.openstreetmap.org broken on IE8

### ISSUE THREAD

**Issue by davidearl** [openstreetmap/openstreetmap-website#931]
It displays the search box, and a random selection of close 'x's but no map and none of the controls down the right. As well as a real IE8, it also fails in the IE8 emulator in IE11 so shouldn't be too hard to find, though I can't see any relevant Javascript console messages.

I know IE8 is obsolete, but sadly, both my local authorities (Camridge City and Cambridgeshire County Council) still use it. I suspect many other councils do too.

Leaflet in general works OK on IE8.

IE9 is OK.

IE7 doesn't even display the search box, just the logo

**Comment by tomhughes** [comment]
We know, and we don't really care. To be using IE8 you not only have to be using an obsolete and unsupported operating system, but you also have to have chosen not to allow it to upgrade to IE9!

The idea of using IE7 is just utterly bonkers. It's usually IE6 or IE8 that people are stuck on, not IE7.

**Comment by davidearl** [comment]
I agree entirely, of course, but unfortunately some of the key users don't. Local authorities are people we need on our side! I suspect they can't afford to move from XP and they aren't willing to support Chrome. Please reconsider.

**Comment by tomhughes** [comment]
Well I literally have no way to even test this, so there really isn't much I can do even if I did have any interest at all in spending my time banging my head against a brick wall.

**Comment by davidearl** [comment]
Surely someone must be testing some version of IE somewhere, otherwise how do you know that any version of IE works? And any version of IE can be used to locate the problem, they don't need an IE8 native install, just the emulator in IE11 or IE10. It just seems rather peremptory to close this immediately just because you personally can't fix it. It's still a bug! And it is a showstopper in terms of communicating with my local authorities.

**Comment by tomhughes** [comment]
Well I for one never test anything in IE except in response to specific bug reports and I have no idea how to go about using this "emulator" that you refer to, nor did I even know that it existed. I assume what you're really referring to is the compatibility mode? Is that actually accurate enough work as a means of really testing IE8 support, given that isn't really it's intended use.

In fact when it comes to IE bugs the lack of developer tools usually means that I'm reduced to randomly tweaking the source in the hope of fixing the problem which means it's not the easiest of problems to solve.

I'm not going to refuse to take PRs that fix IE8 issues, but nor am I personally going to spend any time on them, and I don't see what use a generic bug like this is going to be - it's just going to sit in the bug tracker for ever most likely.

When would we even close this bug in your view? How perfectly would the site have to work before you considered it fixed?

**Comment by davidearl** [comment]
It's F12 like in Chrome. It's very much like the Chrome debuggger. They call it 'emulation' on the tab, and it's the next step on from compatibility mode: you select which version. It's not perfect, especially when it comes to @font-face and file downloads, but in this case the bug is absolutely visible using it and because it's so blatant and it used to work, I expect it won't take that much to find it. I can see that it is loading two tiles (though they aren't actually visible, the positions are first and second on the top row), only. I have seen similar problems when I've got something wrong setting up leaflet in such a way that its stylesheet doesn't load. At a wild guess I'd suspect it's the routing addition that broke it.

I'm very happy to check it out any fix on a real IE8 - though it's not hard even on Linux to set up a VirtualBox virtual Windows XP to test it - MS provides XP/IE8 virtual images at https://www.modern.ie/en-gb/virtualization-tools#downloads (as well as many others - you could check the most recent IEs this way). But where bugs are evident in the IE emulator, that's an easier way to deal with them in IE11 because it has a far better debugger, pretty much on par with Chrome or Firebug.

And to answer your last question, misaligned boxes and text and things (typical of the silly differences in older IEs) aren't important, though it makes it look rather unprofessional, but being actually able to see the map at all would be a good start. I don't think it would matter much if the editor(s) didn't work, especially if it said to people that it didn't work.

I wish I didn't have to worry about IE8 either, but key players are still using it in many of the things I do (nothing to do with OSM). As you know, the problem is there is no upgrade path for IE8 on XP, and the lack of MS support for XP seems to come second to having no money for LAs. They could use Chrome, but they keep saying they have systems that require IE (though they were saying this about IE6 and have still been able to be dragged screaming to IE8). (I only mention IE7 BTW as I was interested to see whether it was different from IE8 as that might offer some clue; but I don't think it does).

**Comment by tomhughes** [comment]
I think if leaflet's stylesheet wasn't loading we'd have bigger problems than this!

Are you saying this has broken recently then?

Look if it'll make you happy I'll reopen this. I don't see that it will make any difference to whether the site gets fixed, but if it makes you feel happy then so be it.

**Comment by davidearl** [comment]
> I think if leaflet's stylesheet wasn't loading we'd have bigger problems than this!

Of course. I meant maybe something was stopping this working in IE8 only, or maybe the separate style sheet it loads for IE is doing something that has a similar effect.

> Are you saying this has broken recently then?

I don't really know - it's a guess, as being a recent change, and we know from older reports I found that it was working in IE8 in 2012 after a previous bug was fixed.

> Look if it'll make you happy I'll reopen this. I don't see that it will make any difference to whether the 
> site gets fixed, but if it makes you feel happy then so be it.

If I had enough rails knowledge, I'd set up a test system myself. It may be I'll be able to trace it just from the IE end and let you know at least in outline what the fix might be. I haven't found it after a half hour's scrutiny, but it's hard when you only have access to one side of the system.

**Comment by davidearl** [comment]
OK, I have a theory. I'm using square brackets below because github wipes out sections with angle brackets, presumably because of the markdown.

The doctype is html, but we have (NB there are two occurrences)...
[span class="icon close" /]
for the x icon in the "Close the directions panel" link, the span is self-closed in XHTML style. I think this is not valid as a self-closing tag for that doctype (not just for IE8, but everywhere). While modern browsers close it automatically in a forgiving way, in IE8 it doesn't (because it doesn't see it as XHTML because that's not in the doctype) and the span effectively encloses most of what follows, hiding it and changing layout so dramatically leaflet doesn't load its tiles properly.

I suspect
[span class="icon close"][/span]
will improve things a lot.

BTW, when I worked this out I ran it through the W3C validator, which complains about a few other things as well which may be worth following up.

I'll be happy to test this change in IE8 if you can make it (tell me the URL if you want me to test it in a dev version).

**Comment by tomhughes** [comment]
If you're right then hopefully 6d9d688080ebcf166addb868b8fceeee55c3e700 (which is now live) will improve things.

**Comment by davidearl** [comment]
Yay, that works! IE8 now looks like every other openstreetmap home page. So my wild guess was spot on. Thanks for applying the fix.
