### ISSUE TITLE
IE11 and IE10 fail to display anything in panel after clicking on a search result

### ISSUE THREAD

**Issue by davidearl** [openstreetmap/openstreetmap-website#932]
Sorry about this, I know how much you hate Internet Explorer... this is the current version, not an old one.

If you search for a street (I used the search string "Middleton Close, Cambridge") it displays the result correctly, but if you click on that result, you get a blank left panel.

Opening the debugger it seems it is aborting the Javascript execution because of an error at
var a=t.getResponseHeader("X-Page-Title");document.title=decodeURIComponent(escape(a))
with error "SCRIPT5025 : The URI to be decoded is not a valid encoding"
Examnining variable a, it shows
  "OpenStreetMap | Way: â€ªMiddleton Closeâ€¬ (â€ª331105333â€¬)"
(i.e. with the a-hat and euro symbol etc).

X-Page-Title is 
"OpenStreetMap | Way: %E2%80%AAMiddleton Close%E2%80%AC (%E2%80%AA331105333%E2%80%AC)"

It appears these strings contain open and close left-to-right embedding UTF-8 characters 0xE280AA and 0xE280AC. escape produces %u... for these, and decodeURIComponent blows up on this in IE11. escape is deprecated. I'm not sure what is trying to be achieved here. Incidentally the debugger shows the X-Page-Title string in decoded form and Chrome doesn't, but this may just be the debugger - or maybe it could indicate that IE11 is decoding this string when you aren't expecting it to.

If you refresh the page (that is, so that the URL "http://www.openstreetmap.org/way/331105333" fetches the way info directly, then it does display it OK, presumably because the title is already set in the HTML so this Javascript doesn't need to be executed.

IE9 and IE8 (ironically, given yesterday's IE8 bug) are fine!

**Comment by tomhughes** [comment]
Yeah that code is a PITA but I suspect there is properly portable way to do it so we're probably pretty stuck. The problem is you have no real way to know what encoding mangling XHR may have done on the response headers and therefore how to turn them into proper unicode that you can display.

**Comment by tomhughes** [comment]
The commit that introduced that odd escape+decode sequence is 248d0b863cde44881574ef01b974afeb2cad12e9 and as the commit comment explains I got it from http://monsur.hossa.in/2012/07/20/utf-8-in-javascript.html as a magic hack to get JS to treat that header string as UTF-8 and decode it properly.

**Comment by davidearl** [comment]
Rather than putting it in the headers, how about putting it as an attribute of the first H2 in the HTML, so it is much more predictable how the encoding behaves. You can then extract it from the dom once it's been added to the panel. You could leave the header for anyone who is relying on it, though that wouldn't be that helpful in a browser - though maybe it would with cURL.

**Comment by tomhughes** [comment]
Is that `H2` actually generated in a single consistent place though? Do all requests that go through there even have an `H2` to attach it to?

**Comment by davidearl** [comment]
Dunno - I was assuming that code was specific to this panel. But if you think that code is used on many different requests and funnels through some common server side code to deal with the xhr=1 query parameter, then you could insert a div into all such requests with a class which always causes it to be hidden, and an attribute which supplies the browser title. The principle is the same though - doing it through the HTML removes the uncertainty over the encoding.

**Comment by tomhughes** [comment]
Well actually at the moment I don't think there is any common view code where we could insert anything. I do have an idea of how to fix it though, so I'll try and have a look this evening.

**Comment by tomhughes** [comment]
Hopefully e2aef40437767e779f97a7447de69b4540839ff5 will help with this...

**Comment by davidearl** [comment]
Yes, that works fine in IE11 now, thanks.
