### ISSUE TITLE
Diary doesn't show modifiaction time of an entry

### ISSUE THREAD

**Issue by woodpeck** [openstreetmap/openstreetmap-website#937]
In a situation where a user changes their diary entry later, the only date displayed is the original creation date. Users can replace their diary entries with "..." (e.g. https://www.openstreetmap.org/user/nomatrix/diary) and you'll see long-ish discussions underneath but no indication that the original article has been changed between now and the time the discussion was had. 

Suggestion: Add a forum-like "changed at ..." if a diary entry has been changed after writing.

**Comment by tomhughes** [comment]
This is not something we record, so we are not able to show it.
