### ISSUE TITLE
List of wiki pages (config/wiki_pages.yml) is outdated

### ISSUE THREAD

**Issue by stefanb** [openstreetmap/openstreetmap-website#943]
Scraped list was last updated in june 2014, almost a year ago:
https://github.com/openstreetmap/openstreetmap-website/commits/master/config/wiki_pages.yml

Please re-run script/misc/update-wiki-pages.
Thanks

**Comment by tomhughes** [comment]
You could always rerun and send a pull request you know...

**Comment by stefanb** [comment]
:) i know, i just don't have the working environment set up at the moment.
