### ISSUE TITLE
App crashes when selecting "Always ask" as logging interval

### ISSUE THREAD

**Issue by robwe** [openstreetmap/openstreetmap-website#945]
1) Go to Settings -> Trip recording
2) Select any profile
3) Select "Logging interval during navigation" or "Online tracking interval"
4) When you select "Always ask", then the app crashes.

**Comment by floscher** [comment]
You probably wanted to open an issue for OsmAnd (with "Record your trips" plugin).

This is the repository for the website [//openstreetmap.org](//openstreetmap.org), not for OsmAnd.

**Comment by robwe** [comment]
Sorry for posting in the wrong place. I close the issue here.
