### ISSUE TITLE
diary: provide readership statistics

### ISSUE THREAD

**Issue by joostschouppe** [openstreetmap/openstreetmap-website#950]
When writing on a blog, it's always motivating to see it's being read. Right now, OSM.org does not provide this feature to Diary users. Basic statistics such as views, clickthrough and backlinks could be provided.

**Comment by tomhughes** [comment]
I'm sorry, but we're not going to rebuild wordpress inside osm - it's a basic blog system and it would be insane to try and build into something that other people specialise in.
