### ISSUE TITLE
Diary: following discussions

### ISSUE THREAD

**Issue by joostschouppe** [openstreetmap/openstreetmap-website#951]
Currently, diary informs you of comments on your own posts. But it's hard to keep track of discussions started by someone else. It would be nice to have a feature to be notified if someone comments on a post that interests you.
I would suggest a checkbox for "Notify me of new comments on this article", checked by default when you add a comment. Maybe also a button "follow this discussion" and "follow this diary" for people who don't necessarily want to comment themselves.

**Comment by matkoniecz** [comment]
It would be great to add this feature. It seems that people almost never notice replies to their comments.

**Comment by marcows** [comment]
I have written a Greasemonkey user script, which can be used as a partial alternative solution for this issue:
https://github.com/marcows/osm-diaries-toc

**Comment by joostschouppe** [comment]
This has been fixed!

Thanks everyone.

**Comment by tomhughes** [comment]
Fixed by #1309.
