### ISSUE TITLE
Diary: Provide a popular" feed in OSM.org

### ISSUE THREAD

**Issue by joostschouppe** [openstreetmap/openstreetmap-website#952]
Currently, it is possible to see recent posts, posts by language and posts of friends. What is missing is "popular" posts. This kind of ranking would motivate people to write mire and better entries. It could also be a way to softly filter out spam and "hello world" posts. Ranking could be done reddit style, based on upvotes and downvotes. Or statistically, based on number of comments and number of views.
The resulting feed could be used for a periodic mailing or rss feed. Or on the front page. Or on users profiles.

**Comment by tomhughes** [comment]
Again, we're not going to rebuid reddit inside osm. If you want reddit it's at reddit.com not osm.org.

**Comment by kevinsimper** [comment]
@tomhughes What do you refer to with again? :)

@joostschouppe sounds like a good idea, as a newcomer to the diaries it was very confusing to see all kinds of post and languages, at first I wasn't even aware of what I was looking it.
