### ISSUE TITLE
New tiles are "reverted" to the older version

### ISSUE THREAD

**Issue by kocio-pl** [openstreetmap/openstreetmap-website#955]
(I'm not sure where should I report it, but it's probably not the osm-carto issue and I observe the problem on our main site.)

I often see my changes on default layer rendered almost instantly, but then the tiles are "reverted" to the older version (the data are not). Not all of them, the time of "revert" is also not fixed and even if I use /dirty I can't be sure when the newer version will be back.

Maybe some caching/load balancing problems? I thought it was a Firefox issues with its cache, but Chromium was no different.

**Comment by tomhughes** [comment]
What it most certainly isn't is an issue with the web site code, so this is clearly not an appropriate place to discuss it.

If it's anything then it's an operations issue, but in reality with potentially three levels of caching (browser, tile cache, tile renderer) and a network of machines that dynamically rearranges itself as machines come and go this is bound to happen sometimes so I'm not sure I consider it a bug at all.

**Comment by kocio-pl** [comment]
It was introduced one day few months ago (don't remember exact moment though) and I never saw it before, so I guess it is a bug - I'll ask at talk list about it.

**Comment by tomhughes** [comment]
If it is a bug then it absolutely is not a bug in the code in this repository, because none of the code in this repository has anything to do with rendering tiles.

What you are seeing is probably just the effect of us having added more caches - the whole system is, in effect, only eventually consistent.
