### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by alexk77** [openstreetmap/openstreetmap-website#956]
Good day,every1!
In Debian amd64 7.8.0 i do have errors after running bundle exec rake test:

  1) Failure:
UserControllerTest#test_account [/opt/osm/openstreetmap-website/test/controllers/user_controller_test.rb:763]:
Expected exactly 0 elements matching "div#errorExplanation", found 1..
Expected: 0
  Actual: 1

  2) Failure:
ApiControllerTest#test_changes_start_end_valid [/opt/osm/openstreetmap-website/test/controllers/api_controller_test.rb:348]:
Expected response to be a <success>, but was <500>

  3) Failure:
ApiControllerTest#test_changes_zoom_valid [/opt/osm/openstreetmap-website/test/controllers/api_controller_test.rb:315]:
Expected response to be a <success>, but was <500>

  4) Failure:
ApiControllerTest#test_changes_hours_valid [/opt/osm/openstreetmap-website/test/controllers/api_controller_test.rb:336]:
Expected response to be a <success>, but was <500>

  5) Failure:
ApiControllerTest#test_changes_simple [/opt/osm/openstreetmap-website/test/controllers/api_controller_test.rb:274]:
Expected response to be a <success>, but was <500>

1024 runs, 265386 assertions, 5 failures, 0 errors, 0 skips
[Coveralls] Outside the CI environment, not sending data.

---

Please do make any advise, any help is good. I'm not in deep knowledge with linux

**Comment by tomhughes** [comment]
My advise is to follow the published instructions. In particular to make sure you install the 3GL functions in your database as explained here:

https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md#postgresql-functions

**Comment by alexk77** [comment]
THX for reply! This functions installed ok. I have no method to recheck this.
Trying to repeat this part causes this:
 ERROR:  function "$NAME" already exists with same argument types

**Comment by tomhughes** [comment]
Make sure you install them in the test database as well.

**Comment by alexk77** [comment]
i've add the functions to osm_test and osm databases.
Now i get lot of new errors and will go to analyze them

-----------

osm@hostname:/opt/osm/openstreetmap-website$ bundle exec rake test
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's 'rails' settings.
Run options: --seed 2623

# Running:

......................F.............................................................................F.............................................................................................................FF...............................................................................................................................................................................................................................................................................................................FF.....FF...FF.....F........................................................................................................F...........F.................F........F.............F......F............F....................................................................................................................................................................................F....................................................Entity: line 1: parser error : Start tag expected, '<' not found
nonsense
^
.......................Entity: line 1: parser error : Attribute lat redefined
<osm><node id='123' lon='23.23' lat='23.1' lat='12' changeset='23' version='23'
                                                                               ^
Entity: line 1: parser error : Attribute lat redefined
<osm><node id='123' lon='23.23' lat='23.1' lat='12' changeset='23' version='23'
                                                                               ^
.......................................................

Finished in -261588515.827344s, -0.0000 runs/s, -0.0010 assertions/s.

  1) Failure:
MessageControllerTest#test_new [/opt/osm/openstreetmap-website/test/controllers/message_controller_test.rb:125]:
Expected |2015-04-16 15:59:08 +0300 - 2015-04-16 12:58:57 UTC| (10.973131804) to be <= 2.


  2) Failure:
ApiControllerTest#test_changes_simple [/opt/osm/openstreetmap-website/test/controllers/api_controller_test.rb:295]:
Expected exactly 10 elements matching "tile", found 0..
Expected: 10
  Actual: 0


  3) Failure:
WayControllerTest#test_create_invalid [/opt/osm/openstreetmap-website/test/controllers/way_controller_test.rb:235]:
way upload to closed changeset did not return 'conflict'.
Expected: 409
  Actual: 200


  4) Failure:
WayControllerTest#test_delete [/opt/osm/openstreetmap-website/test/controllers/way_controller_test.rb:324]:
Expected response to be a <conflict>, but was <200>.
Expected: 409
  Actual: 200


  5) Failure:
NotesControllerTest#test_index_closed [/opt/osm/openstreetmap-website/test/controllers/notes_controller_test.rb:712]:
Expected: 4
  Actual: 6


  6) Failure:
NotesControllerTest#test_destroy_success [/opt/osm/openstreetmap-website/test/controllers/notes_controller_test.rb:562]:
Expected: "hidden"
  Actual: "opened"


  7) Failure:
NotesControllerTest#test_feed_success [/opt/osm/openstreetmap-website/test/controllers/notes_controller_test.rb:838]:
Expected exactly 8 elements matching "item", found 12..
Expected: 8
  Actual: 12


  8) Failure:
NotesControllerTest#test_comment_success [/opt/osm/openstreetmap-website/test/controllers/notes_controller_test.rb:229]:
Expected: "commented"
  Actual: "opened"


  9) Failure:
NotesControllerTest#test_close_success [/opt/osm/openstreetmap-website/test/controllers/notes_controller_test.rb:375]:
Expected: "closed"
  Actual: "opened"


 10) Failure:
NotesControllerTest#test_reopen_success [/opt/osm/openstreetmap-website/test/controllers/notes_controller_test.rb:425]:
Expected: "reopened"
  Actual: "opened"


 11) Failure:
NotesControllerTest#test_index_success [/opt/osm/openstreetmap-website/test/controllers/notes_controller_test.rb:592]:
Expected exactly 2 elements matching "item", found 3..
Expected: 2
  Actual: 3


 12) Failure:
ChangesetControllerTest#test_unsubscribe_fail [/opt/osm/openstreetmap-website/test/controllers/changeset_controller_test.rb:2149]:
Expected response to be a <not_found>, but was <409>.
Expected: 404
  Actual: 409


 13) Failure:
ChangesetControllerTest#test_create_comment_success [/opt/osm/openstreetmap-website/test/controllers/changeset_controller_test.rb:1985]:
"ChangesetComment.count" didn't change by 1.
Expected: 5
  Actual: 4


 14) Failure:
ChangesetControllerTest#test_subscribe_success [/opt/osm/openstreetmap-website/test/controllers/changeset_controller_test.rb:2068]:
"changeset.subscribers.count" didn't change by 1.
Expected: 1
  Actual: 0


 15) Failure:
ChangesetControllerTest#test_query [/opt/osm/openstreetmap-website/test/controllers/changeset_controller_test.rb:1557]:
Expected exactly 1 element matching "osm>changeset", found 3..
Expected: 1
  Actual: 3


 16) Failure:
ChangesetControllerTest#test_unsubscribe_success [/opt/osm/openstreetmap-website/test/controllers/changeset_controller_test.rb:2113]:
"changeset.subscribers.count" didn't change by -1.
Expected: 1
  Actual: 2


 17) Failure:
UserChangesetCommentsTest#test_displaying_form [/opt/osm/openstreetmap-website/test/integration/user_changeset_comments_test.rb:37]:
Expected at least 1 element matching "textarea[name=text]", found 0..
Expected 0 to be >= 1.


 18) Failure:
ChangesetHelperTest#test_changeset_details [/opt/osm/openstreetmap-website/test/helpers/changeset_helper_test.rb:13]:
Expected /^Closed <abbr title='Created: Mon, 01 Jan 2007 00:00:00 \+0000&#10;Closed: Tue, 02 Jan 2007 00:00:00 \+0000'>.*<\/abbr> by <a href="\/user\/test2">test2<\/a>$/ to match "Created <abbr title='Mon, 01 Jan 2007 00:00:00 +0000'>about 3 hours ago</abbr> by <a href=\"/user/test2\">test2</a>".


 19) Failure:
UserControllerTest#test_account [/opt/osm/openstreetmap-website/test/controllers/user_controller_test.rb:763]:
Expected exactly 0 elements matching "div#errorExplanation", found 1..
Expected: 0
  Actual: 1

1024 runs, 265268 assertions, 19 failures, 0 errors, 0 skips
[Coveralls] Outside the CI environment, not sending data.

**Comment by tomhughes** [comment]
Well if you get any failures then there is something wrong with your setup - we run the tests all the time and they all pass.

**Comment by danstowell** [comment]
Timezone issue. First look at this:

         Finished in -261588515.827344s

OK so the test took a large negative amount of time?
Then look at failure 1:

         1) Failure:
         MessageControllerTest#test_new [/opt/osm/openstreetmap-website/test/controllers/message_controller_test.rb:125]:
         Expected |2015-04-16 15:59:08 +0300 - 2015-04-16 12:58:57 UTC| (10.973131804) to be <= 2.

I personally don't know what that test is doing, so I don't know if this means @alexk77 needs to fix some part of the server timezone settings, or if the test is making an unwarranted timezone assumption. But maybe someone else can help alex to understand.

**Comment by tomhughes** [comment]
@danstowell That's actually quite interesting, and relates to something I was intending to look at that the latest rubocop pointed out with the new Rails/TimeZone test. It needs some careful thought though to figure out what the right answer is in each case.

I'm surprised though, that, if that is an issue, that we don't see failures when switching in and out of summer time...

**Comment by alexk77** [comment]
Russia/Moscow introduced new timezone in Oct 2014
I'll try to switch to GMT+3 TZ and rerun test

**Comment by tomhughes** [comment]
The actual timezone won't matter, only whether it is not GMT.

**Comment by tomhughes** [comment]
Hopefully b0ed60617330a7e9758cd1d5adcb89fc64b1f6fd will fix the timezone issues - with that I can run the tests OK with `TZ` set to Moscow time.
