### ISSUE TITLE
/about copy is not accurate

### ISSUE THREAD

**Issue by tristen** [openstreetmap/openstreetmap-website#965]
This line:

> OpenStreetMap powers map data on hundreds of web sites, mobile apps, and hardware devices

_hundreds_ is not exactly accurate :p Is there a better figure or better copy to use here?

![screen shot 2015-05-07 at 11 04 16 pm](https://cloud.githubusercontent.com/assets/61150/7529898/8a70aac6-f50d-11e4-967d-07660dd8b553.png)

**Comment by tomhughes** [comment]
Well of course not - how are we ever supposed to know an exact number?

**Comment by tristen** [comment]
I mean, this is a false statement. Surely there is better copy to use here. Why close this issue?

**Comment by danstowell** [comment]
I don't see any false statements in that text.

Maybe it would be helpful if you could explicitly propose the text that you think would be better.

**Comment by tomhughes** [comment]
Are you saying you think it is less than a couple of hundred? Because any number that is more than 200 is "hundreds" surely?
