### ISSUE TITLE
missing longditude and latitude options in openstreetmaps

### ISSUE THREAD

**Issue by roeselpi** [openstreetmap/openstreetmap-website#966]
hello,

i constantly notice that the navigation systems are not accurate and if i enter an address, then it either takes me to far or not far enough down a street until i reach my destination that i entered. i do not know why the navigation system does that but i have learned to live with it or rather more use a work around to get me to the spot i want to go to:

i enter longditude and latitude entries into the navigation system and then it always leads me to the
exact spot i want to go to. this may sound a bit stupid but if you get around a lot then you will know how frustrating it is to look for a certain house in a street where no houses have any numbers near their door. that is why i personally got used to the feature that google maps used to have they always offered by a right-click option a thing called "what is here?"

if you clicked that then you got the following information:

52.789991,5.028250
52°47'24.0"N 5°01'41.7"E

in the old classic google maps you even got the name of the street and the town as additional information. 

however google maps has shut down their classic version and i hate the new updated new google maps version for many reasons, so i am looking for an alternative that still provides similar features to what the old and no longer available classic google maps offered. 

i can see that in the address line (url-line) from openstreetmap there is the entry 

#map=17/51.23653/11.88086

from which i can work out the real longditude and latitude, but however this part of the url line is for an undefined part of what i can see on the screen, so i do not know what exactly is that location. that is a feature that i am missing so much.

to give you a better example of what i mean, i would urge you to go onto these two urls to understand and see what i mean:

bing.com/maps
there just rightclick on land anywhere and you will get something like this:
0575 Oslo, Norway
59,923940 10,788655

once you have those coordinates you can find out that this is 59°55'26.18"N,10°47'19.15"E

same goes for the old classic google maps:

google.com/lochp
there just rightclick anywhere on the map and you choose the option "what is here?". then activate the green arrow and you get:
38.997737, 1.429338

once again you can now find out what is the degrees: 38°59'51.85"N,1°25'45.61"E

with these degrees you can  now enter the exact location of the house into your navigation system and do not need to worry looking at houses that have no numbers anywhere because you looked before on the maps and found the house where you wanted to go to and just entered the exact longditude and latitude of that specific house.

this is a feature that i would like to suggest to be implemented into openstreetmap.

kind regards

**Comment by SomeoneElseOSM** [comment]
Does clicking "where am I" at top left on osm.org do what you want?

**Comment by simonpoole** [comment]
A really easy way to resolve this would be to add coordinates to the output of the "query tool* @SomeoneElseOSM thats returns the center of the map display (which is the same as the coordinates in the URL).

**Comment by tomhughes** [comment]
I think my problem is that even after reading the massive essay I still don't understand exactly what it is @roeselpi wants us to add...

**Comment by woodpeck** [comment]
@tomhughes Apparently they would like a "your mouse pointer is at lat=... lon=... display of some sort. @roeselpi if you make a quick OpenLayers based website yourself (requires only a couple lines of code) then adding a coordinate display is just one line of Javascript. Or use any web site that shows OSM tiles and coordinates, like e.g. informationfreeway.org

**Comment by lonvia** [comment]
Or (mis)use the share function for it: open share panel, select 'include marker', move marker to expected location. The lat/lon coordinates in the URL will now be the position of the marker.

**Comment by roeselpi** [comment]
hello,

yes @woodpeck got it exactly right:

"your mouse pointer is at lat=... lon=... display

that is exactly what i would like the programmers to add to make it better for me and more useful.

kind regards

**Comment by tomhughes** [comment]
I'm afraid I think that's far too esoteric a use case to be worth using precious screen space on - it has been suggested before and we've always decided it's too much of a specialised tool of interest to only a few people.

**Comment by roeselpi** [comment]
@tomhughes ... well if that is the opinion of the programmers, then you can not be angry or disappointed, if your user numbers do no not increase, just because it is to "esoteric". i will continue to use bing maps then instead because they offer this vital and for me most important feature of all:

if i mark a spot, then i must know exactly where this spot is and the only way to do so is to know its longditude and latitude. this is not just some dumb feature, it is essential to maps and reading them and knowing where on earth you are.

kind regards

**Comment by danstowell** [comment]
@roeselpi Sarah Hoffman suggested a good thing that you can do to see exact lat/lon:

>  open "share" panel, select 'include marker', move marker to expected location. The lat/lon coordinates in the URL will now be the position of the marker.
