### ISSUE TITLE
Map position register

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/openstreetmap-website#970]
There are various optional side panels down the left hand side of the screen (e.g. directions interface) and these interfere with the position of the map. Can this effect be stopped please - by identifying the map position by the right hand edge of the screen instead of the left ? I've had numerous cases of placing a marker on the map only for the map to move a couple of inches and the marker land 2" away from where I placed it. Similarly, I've been planning to edit part of the map and suddenly found it has moved due to the effect of the LH side panel.

Mike.

**Comment by tomhughes** [comment]
There are many bugs open for this already, so we don't really need another.
