### ISSUE TITLE
Bing aerial imagery only available in edit mode?

### ISSUE THREAD

**Issue by bagage** [openstreetmap/openstreetmap-website#974]
This issue must have been discussed already but I could not find it either here or on [help.openstreetmap.org](help.openstreetmap.org). 

Currently Bing is only available when entering `Edit mode`, but it would also be useful for final users in my opinion (for instance when routes are missing, or simply to localize yourself spatially). Is there a reason to this choice?

**Comment by danstowell** [comment]
Yes, it's Bing's terms of use. They are kindly letting us use Bing imagery, for a specific purpose: as a support for editing.

Also note that the purpose of OSM.org is editing the map, not using the map: its "final users" **are** its map editors. The purpose of the site is to help people edit, so it's not even certain that the OSM.org developers would want to show aerial imagery even if they were allowed to.
