### ISSUE TITLE
About database setup

### ISSUE THREAD

**Issue by dhthong92** [openstreetmap/openstreetmap-website#978]
At this time I post this question, everything is ok. But during installation process, I've met some problem that make me so confused.
- I've built Postgresql from source, so I've ran it as instance in console. And when I ran the command: bundle exec rake db:create, it take the error that cannot connect to Postgres database, although I've set its setting to listen to all address and run in port 5432. So, I've had to install postgresql as service like your instructions and everything is ok. !?

- I've login as root user to build, and nothing happen until I run the three commands to create function: psql -d openstreetmap -c "CREATE FUNCTION .... The error has occured: libpgosm permission denied. I can't understand, I've ran everything as root user at the beginning and I've also create root role for postgres database. I've tried to login to the database as root role and ran the command but nothing changed. Maybe CREATE FUNCTION call to something that did not run as root?

Hope to see your help!

**Comment by tomhughes** [comment]
This is the openstreetmap issue tracker, not the postgres help desk. You need to make sure you have a working postgres server that you can connect to before you start trying to install our code.

If "psql template1" does not work at the command line then you are not ready to install out code and you need to seek help from an appropriate postgresl forum.

I would add that installing postgres from source is almost certainly a mistake. You don't say what platform you are using, but unless it is seriously obscure I would imagine there are far better solutions using a prebuilt version.

**Comment by dhthong92** [comment]
Sorry, tt's my mistake to tell you my platform is Ubuntu 14.04 (trusty tar). I've make sure that my postgres server ran normally. The others program still connect to it ok. Because I don't know anything about ruby, therefore I can't go into your source code to debug.
Thanks for your help!

**Comment by tomhughes** [comment]
So why on earth have you installed from source instead of installing from either the Ubuntu APT repos or the postgres ones?

In any case the issue is almost certainly that your locally built postgres is using some weird directory in /usr/local for it's sockets, so you will need to configure database.yml appropriately. You'll need to google for the details though because I have no idea.
