### ISSUE TITLE
Custom installation with multiples databases

### ISSUE THREAD

**Issue by franckt** [openstreetmap/openstreetmap-website#980]
Hello to ruby experts,

I'm currenlty work on a project with multiple osm databases installed 
and a modified osm api instance, i added a X-Venue header for requests to route to a specified correctly installed database. 

i updated ApplicationController to connect to the specified database, it works but when i connect to a non existing database, it keeps that connection and returns database not found

https://gist.github.com/franckt/7c6a8cf5f0d7deffb9be

i'm not sure how rails works with pgsql and if establish_connection() is the good way, it seems that some connection polling somewhere keeps latest bad connection

Any help on that ?

**Comment by tomhughes** [comment]
What does this have to do with us exactly? If you want help with getting to rails to talk to multiple databases dynamically then that is a rails problem, not an openstreetmap-website problem.
