### ISSUE TITLE
Satellite Layer

### ISSUE THREAD

**Issue by oddityoverseer13** [openstreetmap/openstreetmap-website#983]
Is there any chance we can have a satellite layer added? Maybe options for Mapbox Satellite and Bing Satellite? I hate having to click edit just to see the satellite layer.

**Comment by danstowell** [comment]
Please see #974

**Comment by oddityoverseer13** [comment]
Alright, so that answers the question about Bing imagery. What about Mapbox Satellite?

**Comment by tomhughes** [comment]
More to the point, it is out of scope - our goal is to provide an interface for developing our data not an end user map site.
