### ISSUE TITLE
Mail sent via the DMCA form mangles some non-ascii characters

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/openstreetmap-website#987]
An email with German content has just come through to the DWG with umlauted characters mangled ("Ã¶" instead of "o umlaut").

I presume that it was generated by http://dmca.openstreetmap.org/ , but have no idea at what point the content "broke".

**Comment by Firefishy** [comment]
My baby. I'll have a go at fixing it after SOTM.us

**Comment by tomhughes** [comment]
This has nothing to do with the web site code.
